### ISSUE TITLE
Containers started with --project-name set not affected by other commands

### ISSUE THREAD

**Issue by drmacro** [docker/compose#2817] opened 2016-02-04 00:11 UTC
Using docker-compose version 1.5.2, build 7240ff3 on OS X, if I use --project-name with "up", subsequent commands (stop, kill, pause) do not affect the containers. If I remove the --project-name the containers are affected as expected.

**Comment by dnephin** [comment] 2016-02-04 00:25
You would need to provide `--project-name` to every command. The project name is what is used to isolate one instance from another, so if it's excluded the other commands think they are operating on a difference instance.

You can also set the environment variable `COMPOSE_PROJECT_NAME` so that you don't have to keep setting the command line flag.

#745 is related. We should make some progress on that for the next release.

**Comment by dnephin** [comment] 2016-03-21 22:27
Closing this since it's working as designed, and there are other issues open to improve it.

**Closed by dnephin** 2016-03-21 22:27 UTC
Labels: area/cli, kind/question
