### ISSUE TITLE
Error while Killing - level=error msg="got 3 SIGTERM/SIGINTs, forcing shutdown

### ISSUE THREAD

**Issue by Zainzzkk** [docker/compose#9087] opened 2022-01-06 17:26 UTC
**Description**

**Steps to reproduce the issue:**
1. with docker running in terminal use ctrl+c to stop
2. ctrl + c again to force it to stop
3. error message appears

**Describe the results you received:**
level=error msg="got 3 SIGTERM/SIGINTs, forcing shutdown"

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.2.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)  
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., v0.14.0)     

Server:
 Containers: 13
  Running: 1
  Paused: 0
  Stopped: 12
 Images: 13
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 24.84GiB
 Name: docker-desktop
 ID: 3NNE:S3JO:7PS5:XYME:K5M4:HHNM:HNPX:TBBB:2JPY:NORI:GEDC:ZAUN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**

**Comment by justinpage** [comment] 2022-01-07 04:48
Seeing the same behavior from the exact same version.

**Comment by bitshiftnetau** [comment] 2022-01-09 14:22
Same behaviour, ArchLinux in LXC. Forced to reboot LXC every time.

**Comment by Zainzzkk** [comment] 2022-01-31 17:52
This has been fixed in docker desktop 4.4.4

**Comment by pgcd** [comment] 2022-07-05 09:59
> This has been fixed in docker desktop 4.4.4

Not for me - happening on Docker Desktop 4.10.0 (82025)

**Comment by glours** [comment] 2022-07-05 10:02
@pgcd can you provide a reproducible example? It often happens that the underlying stack is the cause of this behavior and not Compose.

**Comment by pgcd** [comment] 2022-07-05 10:14
> @pgcd can you provide a reproducible example? It often happens that the underlying stack is the cause of this behavior and not Compose.

Happy to but I have no idea how to come up with something reproducible, so I'm going to try to explain the situation (so you can tell me what can help finiding the issue).
At the moment, `docker-compose.yml` includes three services: redis, postgres and a django webapp (with gunicorn) that `depends` on the other two; the `Dockerfile`s are pretty minimal, I guess.
The problem arises if I run `docker-compose up` then use CTRL-C to close the processes; on the other hand, I tried `docker-compose up webapp` (which brings up the other services as expected) and closing it works without error.

**Comment by glours** [comment] 2022-07-05 10:25
A simple thing you can do is to run the samples from awesome-compose and check if you can reproduce the issue. For example you can try samples using same tech as your stack (django, flask-redis ones)

**Comment by pgcd** [comment] 2022-07-06 12:58
I tried a few variations of the configurations and it looks like the problem only arises when Django `runserver` or `gunicorn`, so it's probably due to the servers intercepting the CTRL-C somehow.

**Comment by KhanMechAI** [comment] 2022-12-21 22:44
Experiencing this issue with docker compose 2.14.1

**Comment by ntompson** [comment] 2022-12-22 01:14
Likewise - I've never seen this before, but it's started for me when I upgraded to docker-compose 2.14.1 a few days ago.

**Comment by KhanMechAI** [comment] 2022-12-22 01:42
Further context from me then: running a single service, uses a rtsp camera stream and redis (redis is hosted else where). Pretty simple setup service wise.

Docker version: 
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:03 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:22 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
 nvidia:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Docker compose version

```
❯ docker compose version
Docker Compose version v2.14.1
```

**Comment by jonerrr** [comment] 2023-01-03 16:54
I am having the same issue when I run `docker compose logs -f` on Debian 11 and docker compose version 2.14.1.

Docker version:
```
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:22 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jkossis** [comment] 2023-01-06 14:53
I'm seeing the same behavior as @jonerrr, same versions and all.

@Zainzzkk, any chance we could get this issue re-opened?

**Comment by glours** [comment] 2023-01-18 14:11
Hi everyone,
Is it possible that one of you provide a full reproducible example please, as mentioned before most of the time this an issue with the underlying stack which doesn't handle properly SIGTERM send by Compose.
You can take a look to this [doc](https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop) for more details
If someone could give a reproducible sample, I'll happy to jump in and see what's happening

**Comment by kaos14** [comment] 2023-01-18 14:27
@glours here goes: 

**docker-compose.yaml**
```
version: '3.8'

services:
  test:
    image: alpine:3.17
    command:
      - sleep
      - 1d
```

Repro:
```
kaos@kaos:~/docker_logs$ docker compose up --build --wait
[+] Running 1/1
 ⠿ Container docker_logs-test-1  Healthy                                                                                                                                                                                                                                                                                                       0.8s
kaos@kaos:~/docker_logs$ docker compose logs -t -f 
^C^C^CERRO[0016] got 3 SIGTERM/SIGINTs, forcing shutdown
kaos@kaos:~/docker_logs$
```
**docker compose version**
```
Docker Compose version v2.14.1
```

**docker info**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 86
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: a5nhj609hyxrcc0hef8zui0zf
  Is Manager: true
  ClusterID: 9m3boeejoecuyiainnkifbcpd
  Managers: 1
  Nodes: 4
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 1
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.42.0.1
  Manager Addresses:
   10.42.0.1:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-135-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.17GiB
 Name: kaos
 ID: XTH4:MDRF:FKUK:LKU2:JDL3:GDZY:VK4Q:CECH:EF3A:DMSJ:2HC5:4MS6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by glours** [comment] 2023-01-18 14:29
Thanks @kaos14

**Comment by kaos14** [comment] 2023-01-18 14:29
In my case that's a very recent regression.

**Comment by glours** [comment] 2023-01-18 14:39
@kaos14 I can't reproduce with the `v2.15.0` release of Compose 😬 , can you upgrade to check if this wasn't fix in between?
```shell
> docker compose version
Docker Compose version v2.15.0
> bat --decorations never compose.yml
services:
  test:
    image: alpine:3.17
    command:
      - sleep
      - 1d
> docker compose up --build --wait
[+] Running 1/1
 ⠿ Container issue-9087-test-1  Healthy                                                                                                                                                                                                   0.5s
> docker compose logs -t -f
^Ccanceled
> echo $?
130
```

**Comment by glours** [comment] 2023-01-18 14:58
You can download the binary [here](https://github.com/docker/compose/releases/tag/v2.15.1) and add it to the `~/.docker/cli-plugins` directory 😉

**Comment by kaos14** [comment] 2023-01-18 15:16
Tested all versions from 2.14.1 up to 2.15.1. The issue for me was fixed in 2.14.2. Thank you. Any idea when compose will be updated for ubuntu focal?

**Comment by glours** [comment] 2023-01-18 15:25
The `v2.15.1` should be the [next version](https://github.com/docker/docker-ce-packaging/blob/710a8db654098783fa4c4a079bee2f6820467389/common.mk#LL43C10-L43C30) available in package managers, but I don't know exactly when this will be published, maybe @thaJeztah will know?

**Comment by thaJeztah** [comment] 2023-01-20 00:35
docker 20.10.23 was released to download.docker.com, which also includes `.deb` and `.rpm` packages for docker compose 2.15.1 👍

**Comment by glours** [comment] 2023-01-20 09:06
Thanks @thaJeztah 🙏 
@jkossis @kaos14 could you test the latest release and let me know if your issue is fixed, please?

**Comment by kaos14** [comment] 2023-01-20 13:59
My issue is fixed.

**Comment by jonerrr** [comment] 2023-01-20 14:31
The issue is fixed for me too. Thank you!

**Comment by laurazard** [comment] 2023-01-23 11:19
🥳

**Closed by laurazard** 2023-01-23 11:19 UTC
