### ISSUE TITLE
Document that fig does not always rebuild images automatically

### ISSUE THREAD

**Issue by jamshid** [docker/compose#614] opened 2014-11-04 20:00 UTC
Fig does not seem to rebuild the image it uses to create a container when the referenced "build:" Dockerfile or directory has changed. More documentation about how using "build:" differs from "docker build" would be good.

E.g., I have directories "foo" and "foo-single":

foo/Dockerfile
```
...
```
foo-single/Dockerfile
```
FROM foo
...
```
I changed foo/Dockerfile and rebuilt both images with "docker build -t foo ./foo" and "docker build -t foo-single ./foo-single" (though I guess that doesn't matter, fig only looks at the build directory?).

My fig.yml has this so I expected it to pick up the new foo-single, but it does not. I even tried deleting the container ("docker rm myproject_bar") thinking it would check for build changes, but it still used the outdated "myproject_bar" image . 
```
bar:
  build: foo-single
```
I guess fig doesn't check if the Dockerfile or its directory contents have changed? I had to explicitly "docker rmi myproject_bar" in order to get the new "foo" changes.

**Comment by aaronshaf** [comment] 2015-01-11 21:41
This bit me today. +1

**Comment by 83tb** [comment] 2015-01-11 22:18
Same here, took me half an hour today to figure out that the image is not being rebuilt when I make changes to Dockerfile. I think default docker behaviour is rebuilding from the first changed line in a file so I was expecting this.

**Comment by aanand** [comment] 2015-01-12 12:06
@83tb that's not "default docker behaviour", it's what Docker does if you run `docker build`, as well as what Fig does if you run `fig build`. Docker will *never* automatically build your image for you.

It's clear that Fig's behaviour is confusing a lot of new users. I can see two obvious ways to alleviate this:

- by default, build on every invocation of `fig up` (#12)
- by default, don't build on `fig up` (#693)

**Comment by 83tb** [comment] 2015-01-12 13:31
I meant default for ```docker build``` not ```docker run```, my mistake

I would vote for #2.

**Comment by jamshid** [comment] 2015-01-21 21:55
I think I lean towards option 2, forcing people to make `build` an explicit part of their workflow (#693).

**Comment by lorinbeer** [comment] 2015-01-21 23:16
+1
bit by this today

documentation for 'fig up' also compounds the issue http://www.fig.sh/cli.html
documents that it "(re)creates ... containers", but that does not imply a rebuild of the image the container is dependent on.

While technically correct, this was confusing.

**Comment by hadim** [comment] 2015-01-22 08:13
I would vote for options 2 also.

**Comment by bitliner** [comment] 2015-01-22 15:31
+1 for option 1, to rebuild image at each fig up.

Furthermore, I was wondering: why don't you change the flow, such that it is: `build → stop → start` at each fig up? If you run `build` after `stop` then you have downtime that is not nice to have.

If you don't like it, you may provide developers with commands to run the single steps indipendently (like fig build/fig run/fig stop/fig rm), they already esixt but the problem is that they are applied to only one container at a time, while it could be nice if I run `fig start` and it is applied to each container declared in fig.yml

**Comment by cancan101** [comment] 2015-03-02 18:24
:+1 rebuild image on each up.

**Comment by develar** [comment] 2015-03-11 08:05
Correct dockerfile doesn't lead to slow rebuild. Even on my old slow MacBook Air it tooks less than a second. Otherwise I have to use "docker-compose build && docker-compose up" to not worry about it on each change. So, +1 "rebuild image on each up.".

**Comment by pospispa** [comment] 2015-03-16 10:54
My opinion:
- up does not rebuild if it's available locally
- if I want explicit rebuild I must call it explicitly:
docker-compose build 
docker-compose up

**Comment by udl** [comment] 2015-03-16 11:56
Would a parameter make sense?
```docker-compose up --rebuild``` or something like that?

**Comment by develar** [comment] 2015-03-16 12:06
@udl No. Imagine:

1) You push changes.
2) Your colleague pull the changes.
3) "docker-compose is so cool — you need just "run docker-compose up and Compose will start and run your entire app."" But... wait... oh, ***, I need to prepend "docker-compose build &&".

So, in the end, the question — what is the purpose of this command, if it cannot "start and run your entire app" and need in any case use another command (or option) in addition?

I think, "up" in any case is not "incremental" command — to speedup (if need) development, I will use restart/reload commands (docker-compose doesn't support completely this workflow yet, but it is another topic).

**Comment by udl** [comment] 2015-03-16 12:10
@develar I personally would prefer re-building on every ```docker-compose up``` as well. Just thought, a CLI parameter would be a compromise for those, that don't want to have it.

I think the confusion about how ```up``` works comes from the fact, that it automatically builds when the image is not available (which is great). But from that behaviour, one expects that it always automatically checks, that the image is up to date.

**Comment by RoeyPrat** [comment] 2015-03-21 11:44
Sorry if this is naive, but is it possible to automatically rebuild if *.yml or Dockerfile were updated since last build?
It seems to me if the user updates said files they would like to rebuild, without stating so explicitly.

**Comment by sometimesalready** [comment] 2015-04-24 13:29
@develar hello! I have continues delivery process, where:
development server:
1. docker-composer build on development server
2. docker save all built images on dev
2. send  tar files to production server
production server:
3. docker load all images from tar files
4. docker-compose up which throw error, because it tries to build images first which are already in `docker images`
it is real problem.

**Comment by k0377** [comment] 2015-05-22 11:56
thought this woul be the default behaviour of compose :+1:

**Comment by lwcolton** [comment] 2015-09-21 19:48
This is technically fixed, https://docs.docker.com/compose/reference/up/  However, I think the language used is very confusing.  Instead of talking about "picking up changes", it might be better to just say "By default, if a service's image and configuration have not changed, that service's containers will not be re-created."  Can a core contributor either close this issue or +1 my suggestion and I will PR?

**Comment by dnephin** [comment] 2016-03-21 16:21
In #2601 we added a warning any time `up` actually builds an image to inform you that this is a one-time thing. This should prevent confusion in the future.

We also add the `--build` flag.

**Comment by dnephin** [comment] 2016-03-21 16:21
We're always interested in PRs which improve the docs, so please don't hesitate to submit a PR to improve them. Thanks!

**Closed by dnephin** 2016-03-21 16:21 UTC
Labels: kind/docs
