### ISSUE TITLE
`docker-compose build service` should not care about the other service's env file

### ISSUE THREAD

**Issue by agate** [docker/compose#5375] opened 2017-11-14 00:32 UTC
Hi Docker Compose Team,

I have a docker-compose.yml file which contains multiple services in it. And each service has env_file section. But when I run `docker-compose build service-a` I found it will tell me the service-b, service-c, ... is missing their env files. Which I think it's not making sense.

**Comment by shin-** [comment] 2017-11-14 01:42
Duplicate of #5290

**Closed by shin-** 2017-11-14 01:42 UTC

**Comment by agate** [comment] 2017-11-14 05:24
@shin- I don't think these two issue is the same. #5290 is only giving you a warning. In my case the build will be stopped.

**Comment by shin-** [comment] 2017-11-14 20:35
Please refer to my answer [here](https://github.com/docker/compose/pull/3955#issuecomment-341231156) regarding making env_file directives optional.

**Comment by agate** [comment] 2017-11-15 19:47
1. That issue is also different to this scope. Issue #3955 was asking you to make env_file as optional. I already have the right env_file for the right service.
2. I do have my proper env file for my service. My point is if you just run `docker-compose build service-a`. docker-compose should not complain if any other service (service-b, service-c...) is missing env_file!
3.  And also. If you run `docker build --help`. Docker will give you this message:
```
Usage:	docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

Options:
      --add-host list              Add a custom host-to-IP mapping (host:ip)
      --build-arg list             Set build-time variables
      --cache-from stringSlice     Images to consider as cache sources
      --cgroup-parent string       Optional parent cgroup for the container
      --compress                   Compress the build context using gzip
      --cpu-period int             Limit the CPU CFS (Completely Fair Scheduler) period
      --cpu-quota int              Limit the CPU CFS (Completely Fair Scheduler) quota
  -c, --cpu-shares int             CPU shares (relative weight)
      --cpuset-cpus string         CPUs in which to allow execution (0-3, 0,1)
      --cpuset-mems string         MEMs in which to allow execution (0-3, 0,1)
      --disable-content-trust      Skip image verification (default true)
  -f, --file string                Name of the Dockerfile (Default is 'PATH/Dockerfile')
      --force-rm                   Always remove intermediate containers
      --help                       Print usage
      --iidfile string             Write the image ID to the file
      --isolation string           Container isolation technology
      --label list                 Set metadata for an image
  -m, --memory bytes               Memory limit
      --memory-swap bytes          Swap limit equal to memory plus swap: '-1' to enable unlimited swap
      --network string             Set the networking mode for the RUN instructions during build (default "default")
      --no-cache                   Do not use cache when building the image
      --pull                       Always attempt to pull a newer version of the image
  -q, --quiet                      Suppress the build output and print image ID on success
      --rm                         Remove intermediate containers after a successful build (default true)
      --security-opt stringSlice   Security options
      --shm-size bytes             Size of /dev/shm
      --squash                     Squash newly built layers into a single new layer
      --stream                     Stream attaches to server to negotiate build context
  -t, --tag list                   Name and optionally a tag in the 'name:tag' format
      --target string              Set the target build stage to build.
      --ulimit ulimit              Ulimit options (default [])
```

You can see there is no `--env-file` option in it. So why docker-compose build needs to care about if I have --env-file?

**Comment by shin-** [comment] 2017-11-15 19:53
As part of the config validation process, all declared `env_file` entries must exist on the filesystem. Validation must be performed before a build can be executed, as it is impossible to execute any command based on an invalid Compose file.
While we could consider doing partial validation in some cases (which is essentially what is suggested in #5290), this is a massive task with very little payoff, and as such, is very low on our list of priorities.

Thank you for your understanding.

**Comment by agate** [comment] 2017-11-16 00:28
OK. Got it! I think I can live without that. Just make sure you guys know there is a problem out there.
