### ISSUE TITLE
Safely Restart a Service When --abort-on-container-exit Is Used

### ISSUE THREAD

**Issue by ComfyDust** [docker/compose#10310] opened 2023-02-24 07:55 UTC
### Description

When `--abort-on-container-exit` is used with `docker compose up`, everything is stopped when `docker compose restart` is run.

It would be great to be able to die when a container crashes but still allow for controlled restarts.

**Comment by DesignByOnyx** [comment] 2023-04-26 21:38
This is such a necessary feature, especially in a monorepo where you might have a dozen or more services start at the same time and you also need to restart individual services (eg. when a file changes).
- `docker compose up --abort-on-container-exit` should abort if a container exits with an error like it already does.
- `docer compse restart <service>` should stop a container with a kill signal, but the "abort-on-container-exit" code should know that a container is restarting and not take down the entire cluster.

**Comment by ndeloof** [comment] 2023-04-27 09:03
Such a change might impact other users who expect an actual exit to happen whatever the cause is, so maybe we would need an additional flag. Anyway a better understanding of your development workflow would help us improve usability, so I wonder: why do you rely on `--abort-on-container-exit` here? If your container exit with error, I assume your next command is to (fix code then) `docker compose up` to recreate this container in your stack, so why would you require other services to be killed?

**Comment by DesignByOnyx** [comment] 2023-04-27 16:31
When we start our cluster, we have dozens of services logging all sorts of information for debugging. When a single service fails to start, the 5 lines of error logs are frequently lost in the hundreds/thousands of lines of start-up logs. Without the abort flag, the cluster comes up and it sometimes takes minutes before we encounter an error because a single service failed to start. Leaving this to humans to sit and watch a stream of logs has not been productive. I'd rather docker abort so that we can fix the error and restart the cluster without the false impression that everything is OK.

Then, later, when the cluster is running, we have watch commands that rebuild things when a file changes. A single file change can affect multiple services which depend on that file. We rebuild all of the necessary services and then call `docker compose restart` on all affected services. This is a fairly "normal" way to use a monorepo with a microservice architecture. We use docker compose for development because of it's ease of use. Maybe something like k8s is what we really need, but compose is like 95% there and would prefer to use it and not get all dev-ops-y with it. I hope that helps.

**Comment by ndeloof** [comment] 2023-04-27 17:01
Just a note: you actually don't need to run `docker compose restart` with modified services, you could just run `docker compose up` which will take care or re-creating services for those with a newer image available.

**Comment by DesignByOnyx** [comment] 2023-04-27 17:28
Thanks. And maybe some of our startup woes can go away with a proper healthcheck setup... which we use in our prod k8s cluster, but not in development (again, trying not to get too dev-ops-y). And thanks for the tip about using `up`. None of our containers are actually changing when a file changes - we are compiling TypeScript and need the running process to restart to load the new code.

**Comment by ndeloof** [comment] 2023-04-28 08:33
> we are compiling TypeScript and need the running process to restart to load the new code.

Interesting. I wonder how this could be covered by the new `watch` command (https://www.docker.com/blog/docker-compose-experiment-sync-files-and-automatically-rebuild-services-with-watch-mode/).
Based on your description, we would need to support something like:
```yaml
services:
  web:
    build: .
    x-develop:
      watch:
        - actions: [sync, restart]
          path: ./web
          target: /src/web
```
cc @milas @glours

**Comment by ndeloof** [comment] 2023-04-28 09:44
just as I feared, as the moby `ContainerRestart` API is invoked to restart a service container, the "container stopped" event we receive do not have the `State.Restarting` flag set: this one is only set when the docker engine manage container's restart policy and restarts container after failure, but not when triggers by user.
We have no way to track this from distinct `docker compose ...` command execution as compose is stateless, and only relies on metadata exposed by docker engine.

**Comment by ndeloof** [comment] 2023-05-15 15:01
I logged https://github.com/moby/moby/issues/45538 so we maybe could better support this scenario in the future
for now closing this issue as "not planned"

**Closed** 2023-05-15 18:44 UTC
Labels: kind/feature
