### ISSUE TITLE
Network alias was not filled when start container with run

### ISSUE THREAD

**Issue by artemkaint** [docker/compose#3437] opened 2016-05-10 09:07 UTC
Version 1.7.1

**Comment by ashb** [comment] 2016-05-11 19:56
Duplicate of #2908

**Comment by artemkaint** [comment] 2016-05-11 20:40
I suppose this bug isn't duplicate issue 2908, because that is the old bug, but this one arose after upgrade to the version 1.7.1

**Comment by ashb** [comment] 2016-05-12 07:55
Ah right sorry - I was guessing from the description it was similar.

**Comment by Ryanb58** [comment] 2018-02-26 19:05
I am also having issues with this. Watching this Issue.

**Comment by NdubisiOnuora** [comment] 2018-05-25 16:12
@shin-: any update on this issue?

**Comment by NdubisiOnuora** [comment] 2018-05-25 16:23
Have people tried the using the `--use-aliases` parameter? It uses the service's network alias. See `https://docs.docker.com/compose/reference/run/` for more information.

**Comment by shin-** [comment] 2018-11-05 22:35
Fixed by #5725

**Closed by shin-** 2018-11-05 22:35 UTC
Labels: area/run, kind/bug
