### ISSUE TITLE
terminal handling on exec is completely unusable in 2.3.4

### ISSUE THREAD

**Issue by rfay** [docker/compose#9315] opened 2022-03-25 15:25 UTC
**Description**

In 2.3.4, you can't `docker-compose exec -it` into a container... your terminal gets captured and you can't do anything.

**Steps to reproduce the issue:**

1. Use this docker-compose.yaml:
```yaml
services:
  deb:
    image: debian:bullseye
    command: tail -f /dev/null
```
2. `docker-compose up -d`
3. `docker-compose exec -it deb bash`

You'll get the initial prompt, but you can't interact with bash at all. It hangs. And you have to kill the terminal emulator to continue.

**Describe the results you expected:**

This has worked for years, of course, and was fine in 2.3.3.

**Output of `docker compose version`:**

Docker Compose version v2.3.4

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 6
  Running: 1
  Paused: 0
  Stopped: 5
 Images: 10
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 2.922GiB
 Name: docker-desktop
 ID: TUH5:TMNE:DVL2:J3WB:RCCS:YIPF:PO3Z:DODW:C3QF:NELR:TSNC:TTZU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details:**

This seems to happen on all OSs. I ran a set of DDEV tests and all failed with this behavior.

**Comment by 1ace** [comment] 2022-03-25 19:33
Came here to report the same issue :slightly_frowning_face:

And I agree, 2.3.x has seen many major regressions like this one; perhaps something should to be done for QA (both CI and human) to address this :slightly_smiling_face:

**Comment by matiux** [comment] 2022-03-25 20:57
Same issue
Back to version 2.3.3 on Linux arch

**Comment by suchmaske** [comment] 2022-03-28 09:28
Same happened to me on arch. I had to roll it back to v `2.3.3`

```
sudo pacman -U docker-compose-2.3.3-1-x86_64.pkg.tar.zst
```

**Comment by ondrej-ivanko** [comment] 2022-03-28 12:48
I can confirm this issue. I have to stick running v2.3.3.

Docker
```
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.18
 Git commit:        a224086349
 Built:             Thu Mar 24 09:16:17 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18
  Git commit:       87a90dc786
  Built:            Thu Mar 24 09:15:51 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.2
  GitCommit:        de8046a5501db9e0e478e1c10cbcfb21af4c6b2d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

OS:
```
Artix Linux x86_64
5.16.16-artix1-1
shell: zsh, terminal: alacritty
```

**Comment by denmaddog** [comment] 2022-03-28 20:54
I have the same issue.

Docker version 20.10.10, build b485636

OS:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

Had to revert to Docker Compose version v2.2.3.

**Comment by lbenard** [comment] 2022-03-29 08:40
Just tested building several commits, it seems to happen since 1d4b4e3c8ebd60c2d3f71cb8f26801fee43b8b3f

**Comment by glours** [comment] 2022-03-29 08:54
Can you build a local version of Compose from the `v2` branch and let us know if you can reproduce this behavior which should have been fixed with this [PR](https://github.com/docker/compose/pull/9318)

**Comment by lbenard** [comment] 2022-03-29 09:17
Oh sorry didn't see you already fixed it, it does indeed work with your changes

**Comment by suchmaske** [comment] 2022-03-29 09:30
I just tested the most recent version `Docker Compose version v2.3.4-5-ga73a2c92`. It worked for me.

**Comment by 1ace** [comment] 2022-03-29 10:59
I tested with [`v2.3.4`](https://github.com/docker/compose/releases/tag/v2.3.4) + #9318 and the bug is fixed; thanks @glours for the quick fix!

**Comment by Foxboron** [comment] 2022-04-19 18:59
@glours  This issue can be closed :)

**Closed** 2022-05-24 00:15 UTC
