### ISSUE TITLE
[BUG] docker-compose up rebuilds a container without network

### ISSUE THREAD

**Issue by knishimo** [docker/compose#10577] opened 2023-05-17 19:04 UTC
### Description

Full disclosure: this issue was seen once and has no known reproducible steps. I searched all issues and in stackoverflow, but didn't see anything that matched what we're seeing.

We have a running service, but need to rebuild it because the image changed. To do this, we user "docker compose up -d" to let compose detect the changed service and rebuild it. The rebuilt service is up, but it was recreated without a network. There are no errors in logs or console.

If there is a low/no impact debugging switch I can use to log more information in case this happens again, please suggest.

### Steps To Reproduce

No known reproducible steps

### Compose Version

```Text
Docker Compose version v2.17.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 23.0.4
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Authorization: opa-docker-authz:latest
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  userns
  cgroupns
 Kernel Version: 5.4.0-144-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 47.15GiB
 Name: redacted.com
 ID: f071aba4-db94-4999-8f49-f419b9ccae8e
 Docker Root Dir: /var/lib/docker/1111.1111
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
```

### Anything else?

Compose YAML file (private information changed):

```yaml
version: "2.4"
services:

  icon:
    restart: on-failure
    container_name: icon
    image: dockerhub.redacted.com/redacted/icon:icon-redacted
    userns_mode: host
    cgroup_parent: common.slice
    ports:
      - "5056:5056"
    volumes:
      - /data/log/icon:/var/log/robot
      
    environment:
      COMPONENT: ICON
      SYSLOG_ADDR_IP: ${SYSLOG_ADDR_IP}
      SYSLOG_ADDR_PORT: ${SYSLOG_ADDR_PORT}
      TLS_CERTIFICATE_FILE: ${TLS_CERTIFICATE_FILE}
      TZ: ${TZ}

    networks:
      - infra_network
    deploy:
      resources:
        limits:
          memory: 6g
    pids_limit: 5000
    cpuset: 2-11

networks:
  infra_network:
    external: true
```

**Comment by ndeloof** [comment] 2023-05-18 07:05
could you please capture output from `docker inspect <container>` as well as `docker network inspect infra_network`?

**Comment by kmotrebski** [comment] 2023-05-18 15:51
Experiencing very similar issue since recently (probably after some automatical Docker-Compose update). The network is there but it even cannot ping `google.com`.

`docker network inspect nowe-s2_default` displays:
```json
[
    {
        "Name": "nowe-s2_default",
        "Id": "a2b44286d17b73a18a7de5a330889b51b0023285c43e8adeb7265db82fc545be",
        "Created": "2023-05-18T16:52:12.664269963+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.26.0.0/16",
                    "Gateway": "172.26.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "3a5d0910f18dc3b7b6264065da30bd6b91ae6cd09cb786d4197e857fa7f95d75": {
                "Name": "nowe-s2-mysql-1",
                "EndpointID": "8956ef1b53c4a5046d89b6425af0fb1fb41914549c6837d00fc74635fdf0340c",
                "MacAddress": "02:42:ac:1a:00:02",
                "IPv4Address": "172.26.0.2/16",
                "IPv6Address": ""
            },
            "9b714fe3578b5c009a74f41cd6388f2f12720ed514cb34be1c5d4d32acda3d52": {
                "Name": "nowe-s2-php-1",
                "EndpointID": "2e2a2f40abaed5220ed5ecf953cefafa024a3b0d525bad6f7a9ef4ecc8a65870",
                "MacAddress": "02:42:ac:1a:00:03",
                "IPv4Address": "172.26.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "nowe-s2",
            "com.docker.compose.version": "2.17.2"
        }
    }
]
```

**Comment by knishimo** [comment] 2023-05-18 20:48
docker inspect icon:

```
[
    {
        "Id": "c4c4beb2b7d86a9f268234b793e424963586b86a2fc9fd3f3acf5ef811ad592c",
        "Created": "2023-04-28T21:23:15.128294338Z",
        "Path": "/usr/local/bin/robot-entrypoint.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2381179,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-05-15T19:44:17.667780378Z",
            "FinishedAt": "2023-05-15T19:43:24.461900278Z"
        },
        "Image": "sha256:e1702b7423c4e41a0a6f3aa11aba7fbd577ad369c2e99173918a52a77354e6a8",
        "ResolvConfPath": "/var/lib/docker/1111.1111/containers/c4c4beb2b7d86a9f268234b793e424963586b86a2fc9fd3f3acf5ef811ad592c/resolv.conf",
        "HostnamePath": "/var/lib/docker/1111.1111/containers/c4c4beb2b7d86a9f268234b793e424963586b86a2fc9fd3f3acf5ef811ad592c/hostname",
        "HostsPath": "/var/lib/docker/1111.1111/containers/c4c4beb2b7d86a9f268234b793e424963586b86a2fc9fd3f3acf5ef811ad592c/hosts",
        "LogPath": "/var/lib/docker/1111.1111/containers/c4c4beb2b7d86a9f268234b793e424963586b86a2fc9fd3f3acf5ef811ad592c/c4c4beb2b7d86a9f268234b793e424963586b86a2fc9fd3f3acf5ef811ad592c-json.log",
        "Name": "/icon",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/data/log/icon:/var/log/robot:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-size": "10m"
                }
            },
            "NetworkMode": "infra_network",
            "PortBindings": {
                "5056/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5056"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "host",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 6442450944,
            "NanoCpus": 0,
            "CgroupParent": "common.slice",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "2-11",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": -1,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 5000,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/1111.1111/overlay2/8bf745df77965001bbbfc67cba6afd35ae6bed35b4837084fd1698b8ad67b033-init/diff:/var/lib/docker/1111.1111/overlay2/03288cc1aac0de69e250828cfc2271346bf8c54f5357a495e9c9e1220ecfc996/diff:/var/lib/docker/1111.1111/overlay2/48ef1e93b9681cdf76b5d6bb5b26485e944b0b40b56406c30f986465413c4f7e/diff:/var/lib/docker/1111.1111/overlay2/042f9017b79448c66d1dabbee56ccc66bbd6c7e3a3a1ad63c80f4ae12d77dd56/diff:/var/lib/docker/1111.1111/overlay2/9ecf7f5044c2ef36046492ad69bc535bd41afbc74c46e8645f0c95fdb01d1aa7/diff:/var/lib/docker/1111.1111/overlay2/45e14d78a2897dffb6c9adfb6b780e150cdc71ced1639b08a099582ef2c77c5b/diff:/var/lib/docker/1111.1111/overlay2/28b1f02b619bbcc3bc08ce67afa894cd1750e2de444d3c139708abaa20a5b32e/diff:/var/lib/docker/1111.1111/overlay2/909e8679a853b51476f0e2f688cae9055a1b1f96ebbc0d1aa7179159528fd09e/diff:/var/lib/docker/1111.1111/overlay2/49f9839311bd0bea1121999ecd539bab63cc5a1ee2b606e0ab9be71a561c4dbd/diff:/var/lib/docker/1111.1111/overlay2/11d240f8a68d2087e2d3da3f0e08537619bcfdbde11db89dd8bb021d18c3b37f/diff:/var/lib/docker/1111.1111/overlay2/4b32e2002beb2c3b88419f0e4d364673ddf3688a49da93d66637aac214bca6ba/diff:/var/lib/docker/1111.1111/overlay2/42ba7536c2d3e3344b96d8cf4d8ecea7220a50721ae032624d5bbd3414d5466e/diff:/var/lib/docker/1111.1111/overlay2/eb6c61cdd62ed68d5043016c797593c036f2ddcb32c4db9cec2bd8cc430ab0ea/diff:/var/lib/docker/1111.1111/overlay2/aee5b0c1d5ca116d521f99051776c4c71ce532007e3914510a57ea482ff6c65f/diff:/var/lib/docker/1111.1111/overlay2/169247cff857f67a5b7adc2c8d3454ffea80e014a7a5f8a88adb1dfe05673f03/diff:/var/lib/docker/1111.1111/overlay2/0bb4f17956633d9ff46e8229170359360c4a5e0fc809cd55f1a5d6543752f475/diff:/var/lib/docker/1111.1111/overlay2/abc187f09c3a25e50cc9c1370ce74efcfacbb7179a870919ae92a58546dcaae9/diff:/var/lib/docker/1111.1111/overlay2/22c52e2e9cca022fa2236e08cb05e28722d7545be75205cd643024c69a4d4118/diff:/var/lib/docker/1111.1111/overlay2/5e675e03e9ef2869fddc0a52dcf8a026a7472e256af3d2baecb32bd2137e51b9/diff:/var/lib/docker/1111.1111/overlay2/ecbe08f6111a38531b2796650d881b3a152a0e9a0e4770ae8765311eb6899e95/diff:/var/lib/docker/1111.1111/overlay2/a2509f20507661be24f0c850dacb6b8a67c55aaffe1ef389fea8e90137318a97/diff:/var/lib/docker/1111.1111/overlay2/6421175fb04e8ab9d53ab464bf7fa5216164ee61d7452b717d35ec27fcba4c65/diff:/var/lib/docker/1111.1111/overlay2/8da8d88a042d377346a44b5b69dc9cacae3ca0295162a7225de986e89dfc2636/diff:/var/lib/docker/1111.1111/overlay2/15abedc1b4bbd89d9e0eb0d22eee686648dc34bd8b24ba9b1f237833628e2c31/diff",
                "MergedDir": "/var/lib/docker/1111.1111/overlay2/8bf745df77965001bbbfc67cba6afd35ae6bed35b4837084fd1698b8ad67b033/merged",
                "UpperDir": "/var/lib/docker/1111.1111/overlay2/8bf745df77965001bbbfc67cba6afd35ae6bed35b4837084fd1698b8ad67b033/diff",
                "WorkDir": "/var/lib/docker/1111.1111/overlay2/8bf745df77965001bbbfc67cba6afd35ae6bed35b4837084fd1698b8ad67b033/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/data/log/icon",
                "Destination": "/var/log/robot",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "c4c4beb2b7d8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5056/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "COMPONENT=ICON",
                "PATH=:/bin:/usr/bin:/sbin/:/usr/sbin:/usr/local/bin:/opt/robot/bin:/usr/local/pgsql/bin",
                "ROBOT_BIN=/opt/robot/bin",
                "ROBOT_DATA=/mnt/datafs",
                "ROBOT_CONFIG=/etc/robot",
                "ROBOT_LOG=/var/log",
                "MANIFEST_FILE=/usr/local/bin/manifest.json",
                "LOG=/var/log",
                "TERM=xterm-256color",
                "JAVA_HOME=/opt/jre/current/",
                "JRE_HOME=/opt/jre/current",
                "CLASSPATH=/opt/jre/current/lib/ext:/opt/jre/current/lib/ext/*",
                "CONFIG_HOME=/etc/robot/config/",
                "SUPERVISOR_PROGRAM1=icon",
                "SUPERVISOR_COMMAND1=/opt/robot/bin/start.sh",
                "SUPERVISOR_STOPASGROUP1=true",
                "SUPERVISOR_KILLASGROUP1=true"
            ],
            "Cmd": null,
            "Image": "dockerhub.redacted.com/redacted/icon:icon-redacted",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/local/bin/robot-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "Name": "icon",
                "Version": "5.0.0",
                "base_image": "",
                "com.docker.compose.config-hash": "8162060b323a5646374821b0bb2338472afb26b67574d632d4d0aff92f041a44",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:e1702b7423c4e41a0a6f3aa11aba7fbd577ad369c2e99173918a52a77354e6a8",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "common",
                "com.docker.compose.project.config_files": "/opt/cache/features/common/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/opt/cache/features/common",
                "com.docker.compose.service": "icon",
                "com.docker.compose.version": "2.17.2",
                "name": "Alpine JRE base image"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "55d7fc2b005019979a28bd3d2b34f9b3a4cf01e6c13bac40096a494a64feb185",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5056/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5056"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "5056"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/55d7fc2b0050",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": { }
            }
        }
    }
]
```

docker network inspect infra_network:
```
[
    {
        "Name": "infra_network",
        "Id": "6ab887fb7af3f746425ac2bf5b3cdabebd558848612cfa9caff508a352df6f05",
        "Created": "2023-02-28T21:20:28.577563642Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "169.254.128.0/24",
                    "Gateway": "169.254.128.1"
                },
                {
                    "Subnet": "fddb:cafe:dead:beef::/64",
                    "Gateway": "fddb:cafe:dead:beef::1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "08b278042dd35707439fcc5a7eb0d34c5c5fec0f9db6e878511ae555cf952104": {
                "Name": "image",
                "EndpointID": "338ddda3dcb5bb1abc218be2604188164f56aa0e995f79df1606a748ee48d7ec",
                "MacAddress": "02:42:a9:fe:80:fc",
                "IPv4Address": "169.254.128.252/24",
                "IPv6Address": "fddb:cafe:dead:beef::252/64"
            },
            "138ee2d267eb6cbe421a90a5170474c76f9337a727539ba023d030013a41633d": {
                "Name": "oam",
                "EndpointID": "da620abcc2f2b096b641bc476401b1191c9b4b39de45aa552c8bcabaa2f0a06d",
                "MacAddress": "02:42:a9:fe:80:fa",
                "IPv4Address": "169.254.128.250/24",
                "IPv6Address": "fddb:cafe:dead:beef::250/64"
            },
            "58a1c5b9f9f4492c4d5c9d5297dc1b35692e8d4d37c2b46eede90c8504842146": {
                "Name": "snmp",
                "EndpointID": "019ea8ee13f599e76cf75a80597054e3a565550f4ae0e05820715a97973480a0",
                "MacAddress": "02:42:a9:fe:80:02",
                "IPv4Address": "169.254.128.2/24",
                "IPv6Address": "fddb:cafe:dead:beef::2/64"
            },
            "6924541234cc9d55fe70c512f451357555388a97df5a078dbfa31b4e923585f5": {
                "Name": "netconf",
                "EndpointID": "5418da789799f20c8023eac9d51f55e39c8c78748d46fa1d7126225e90ea981b",
                "MacAddress": "02:42:a9:fe:80:03",
                "IPv4Address": "169.254.128.3/24",
                "IPv6Address": "fddb:cafe:dead:beef::3/64"
            },
            "83503a3e13236856a36c36650990a298933b8034b1c6b0ade1e420b9460e6aca": {
                "Name": "gateway",
                "EndpointID": "33d0df0a14cc98f7ca7e5c62743837e88eacd5303ab5b7265fb71d358e06619e",
                "MacAddress": "02:42:a9:fe:80:fb",
                "IPv4Address": "169.254.128.251/24",
                "IPv6Address": "fddb:cafe:dead:beef::251/64"
            },
            "857c6b46994469efa5efe27090128cfcc29782fdccfe7f10a78f507b62d0ccce": {
                "Name": "mdt",
                "EndpointID": "f8ef7ccfda9f8d67eb33f847f5b439e91675b70f4c035cac1b42494ca98f9894",
                "MacAddress": "02:42:a9:fe:80:07",
                "IPv4Address": "169.254.128.7/24",
                "IPv6Address": "fddb:cafe:dead:beef::7/64"
            },
            "be14598a78a9420792fd65a44d1672e9f7628f76d2bb5bd30eb8280711ac7584": {
                "Name": "cli",
                "EndpointID": "60f820ee9255bc2c0f408d96c038746b8bd257e108b29ce75da37fda8c5e7951",
                "MacAddress": "02:42:a9:fe:80:06",
                "IPv4Address": "169.254.128.6/24",
                "IPv6Address": "fddb:cafe:dead:beef::6/64"
            },
            "c581028ebe2d49d164be7fab1c8df02ad6e033e70de385801a36f6444bba14d1": {
                "Name": "syslog",
                "EndpointID": "1b9b83cb28ef4a2db522d57d3be5ca4c75c695e1be8f70b6b992be4abc40ea2d",
                "MacAddress": "02:42:a9:fe:80:05",
                "IPv4Address": "169.254.128.5/24",
                "IPv6Address": "fddb:cafe:dead:beef::5/64"
            },
            "d80f1d74dce04de915a402a64affcacf9b6cca83897c98c3c5dcb2431670a896": {
                "Name": "gnmi",
                "EndpointID": "45ee434009f7a6cffb42dce175d96fb35325f8ac2b4e76076286db2b68ea5780",
                "MacAddress": "02:42:a9:fe:80:04",
                "IPv4Address": "169.254.128.4/24",
                "IPv6Address": "fddb:cafe:dead:beef::4/64"
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "network",
            "com.docker.compose.project": "infra",
            "com.docker.compose.version": "2.17.2"
        }
    }
]
```

**Comment by kmotrebski** [comment] 2023-05-19 09:34
In my case what helped was doing those:
- kill Docker containers and remove all volumes of the failing project 
- restart my machine and internet router too

Helped ;)

**Comment by LesnyRumcajs** [comment] 2023-07-21 09:08
A similar issue here. The compose file is defined [here](https://github.com/ChainSafe/forest-iac/blob/8a5eb7cbc22b679ded6abbf96ce529b9a0e601e2/sync_check_terraform/modules/sync_check/service/docker-compose.yml)

The `forest-tester` should attach to the `calibnet` network, also on a restart forced from the watchtower.
```
  forest_tester:
    build:
      context: .
      dockerfile: Dockerfile-tester
    container_name: forest-tester
    networks:
      - mainnet
      - calibnet
```

It didn't attach to it. This is a random failure, though. Typically, it works correctly.

```
[root@2aa241381d54 chainsafe]# docker network inspect 47795fe56b6c
[
    {
        "Name": "root_calibnet",
        "Id": "47795fe56b6ccc94a81e317f91f11c63f1bcb932513489b2726074969aad6cf4",
        "Created": "2023-07-19T11:19:58.100242759Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "b9d9a3dfb2294464c680d4efb3ae34520de81f1c42b86b040f9e0454aaec871e": {
                "Name": "forest-calibnet",
                "EndpointID": "5d47f17cbf95fe70ec0709efc526c7ac107ebc447efaa0386d01cbaaa3fefd70",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "calibnet",
            "com.docker.compose.project": "root",
            "com.docker.compose.version": "2.19.1"
        }
    }
]
[root@2aa241381d54 chainsafe]# docker network inspect 545c77e7b4b8
[
    {
        "Name": "root_mainnet",
        "Id": "545c77e7b4b81bfe7d5a2e66f6143364bb5f7e3806057f5270d5da6e19bcd5d3",
        "Created": "2023-07-19T11:19:58.192372423Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "07fccbacfc87d267f3c4f1f4de1eed55e13bc2d5ac735502079b0d04b607e16b": {
                "Name": "forest-tester",
                "EndpointID": "200b72657b17e3a7bc6a162b2fc5c31d9c24cd586038f3785ea75d3d9b4720ed",
                "MacAddress": "02:42:ac:13:00:03",
                "IPv4Address": "172.19.0.3/16",
                "IPv6Address": ""
            },
            "ec493cc1a8f843ba3032c7cbd6f11801d75e0d22c87f2a795ad8eafc5b1473a6": {
                "Name": "forest-mainnet",
                "EndpointID": "8ce7f1053ec95f3392c2e488f48aad928b80e380f4905da44ffe1b5ba42c0da6",
                "MacAddress": "02:42:ac:13:00:02",
                "IPv4Address": "172.19.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "mainnet",
            "com.docker.compose.project": "root",
            "com.docker.compose.version": "2.19.1"
        }
    }
]

```

The OS is Fedora 38, with Docker version 24.0.4, build 3713ee1.

**Comment by LesnyRumcajs** [comment] 2023-07-21 12:20
Perhaps https://github.com/docker/compose/pull/10778 resolves this issue.

**Comment by LesnyRumcajs** [comment] 2024-10-15 15:47
Hey @jhrotko, I can't update the service at the moment to validate. On compose `2.17.2` it works fine with my current setup.

**Comment by jhrotko** [comment] 2024-10-15 16:37
@LesnyRumcajs that is a pretty old compose version ;) (from March 2023). I could not reproduce with success locally the given example by @knishimo. Is this still an issue?

**Comment by LesnyRumcajs** [comment] 2024-10-15 16:45
@jhrotko Yes, it was downgraded on purpose. After that, I switched to a dedicated Docker image on DO, https://marketplace.digitalocean.com/apps/docker, which includes all the required Docker binaries. I'll be happy to verify once the upstream image is updated (difficult to say when).

**Comment by knishimo** [comment] 2024-10-15 19:14
We've been upgrading docker-compose, docker engine, and containerd to the latest release as they appear and have not had any reports of this issue in the past few months. However, since there isn't a known way to always reproduce the error, I can't say if it's fixed or just hibernating.

I understand this is a poor quality issue report so if it's closed due to an inability to reproduce or it's believed to be fixed, I would not have an issue with that decision. https://github.com/docker/compose/pull/10778 looks similar, but I can't say it's definitely related.

**Comment by ndeloof** [comment] 2024-10-15 19:40
let's close this then, feel free to open a follow-up issue if you have additional inputs that could help diagnose the problem

**Closed by ndeloof** 2024-10-15 19:40 UTC
Labels: kind/bug, area/build, area/networking
