### ISSUE TITLE
udp port assignment ignored

### ISSUE THREAD

**Issue by tpaz** [docker/compose#1334] opened 2015-04-23 19:40 UTC
setting yml file with something like the following:

dockerspy:
    image: iverberk/docker-spy
    ports: 
     - "172.17.42.1:53:53"
     - "172.17.42.1:53/udp:53/udp"
    volumes: 
     - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true

and then running: 
  docker-compose up -d dockerspy
results in (docker-compose ps output):
prod_dockerspy_1   /bin/docker-spy                  Up       172.17.42.1:53->53/tcp, 172.17.42.1:49157->53/udp 

expected result (works fine with regular docker run or tools like Crane):
prod_dockerspy_1   /bin/docker-spy                  Up       172.17.42.1:53->53/tcp, 172.17.42.1:53->53/udp 

It seems like docker-compose (fig?) ignores the udp public port assignment and assigns a high port (49157/udp in this example) instead of the desired 53/udp

or maybe I used a wrong syntax for:  "172.17.42.1:53/udp:53/udp"  ??
from examples in docs I could not see what's wrong with that.

version: docker-compose 1.2.0

**Comment by jverdeyen** [comment] 2015-05-05 12:03
I'm seeing the same kind of ignorance in my port forwarding.

Using:

```
root@vagrant:/home/vagrant/data# docker-compose --version
docker-compose 1.2.0
```

My `docker-compose.yml` has something like this:

```
web:
  build: .
  command: /run.sh
  links:
   - statsd
   - grafana
  ports:
   - "8080:8080"
   - "80:80"
```

After running `docker-compose run web` I see in `docker ps`:
```
2265275024e3        data_web:latest                "/run.sh"              23 seconds ago      Up 22 seconds       80/tcp, 8080/tcp                                                                   data_web_run_1      
```

When I run the build from docker:
```
docker run -p 80:80 custom
```

I see:

```
f342aa207594        custom:latest                  "/run.sh"              20 seconds ago      Up 20 seconds       0.0.0.0:80->80/tcp, 8080/tcp                                                       kickass_lumiere     
```

And the forwarding to port 80 is working as it should.

Any idea?

**Comment by aanand** [comment] 2015-05-05 16:13
@tpaz You've got an extra "/udp" in your YAML. It should be this, which works for me:

```yaml
ports:
  - "172.17.42.1:53:53"
  - "172.17.42.1:53:53/udp"
```

So it looks like we're not validating the `ports` entries properly.

@jverdeyen Use `docker-compose up` if you want the ports to be exposed. See the [docker-compose run docs](http://docs.docker.com/compose/cli/#run) for why it doesn't map ports.

**Comment by jverdeyen** [comment] 2015-05-06 06:30
@aanand Indeed, my bad! I should read more docs!

**Comment by tpaz** [comment] 2015-05-07 11:07
ok @aanand I will check and revert if it doesn't work.

**Comment by dnephin** [comment] 2015-08-31 20:00
Sounds like this was resolved, so I'll close this issue. Please re-open if you can still reproduce it.

**Closed by dnephin** 2015-08-31 20:00 UTC
Labels: kind/question

**Comment by trcarden** [comment] 2015-11-14 21:12
Updated link for docker-compose run docs: https://docs.docker.com/compose/reference/run/
