### ISSUE TITLE
Stopping `fig up` using CTRL+c does not always shutdown containers

### ISSUE THREAD

**Issue by mbentley** [docker/compose#1040] opened 2015-02-27 21:30 UTC
I am having issue where a CTRL+c to a session running `fig up` is just exiting with `Aborting.` using docker-compose 1.1.0.  I am just doing a `fig up`, my containers start up as expected but when I go to do a CTRL+c, it aborts and leaves my containers running.  If code is needed to replicate, I am using this >> https://github.com/mbentley/docker-db_bootstrap

```
$ docker-compose up
Found multiple config files with supported names: docker-compose.yml, fig.yml
Using docker-compose.yml

Creating dockerdbbootstrap_db_1...
Creating dockerdbbootstrap_bootstrap_1...
Creating dockerdbbootstrap_web_1...
Attaching to dockerdbbootstrap_db_1, dockerdbbootstrap_bootstrap_1, dockerdbbootstrap_web_1
db_1        | Running mysql_install_db ...
db_1        | 2015-02-27 21:11:45 13 [Note] InnoDB: Using atomics to ref count buffer pool pages
bootstrap_1 | Unable to connect to MySQL, retrying...
db_1        | 2015-02-27 21:11:45 13 [Note] InnoDB: The InnoDB memory heap is disabled
db_1        | 2015-02-27 21:11:45 13 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1        | 2015-02-27 21:11:45 13 [Note] InnoDB: Memory barrier is not used
...
bootstrap_1 | Post import databases:
bootstrap_1 | +--------------------+
bootstrap_1 | | Database           |
bootstrap_1 | +--------------------+
bootstrap_1 | | information_schema |
bootstrap_1 | | classicmodels      |
bootstrap_1 | | mysql              |
bootstrap_1 | | performance_schema |
bootstrap_1 | +--------------------+
bootstrap_1 |
bootstrap_1 | Database bootstrap complete!
^C
Aborting.
```

Not sure if I am doing something wrong or what but I can reproduce it consistently.

**Comment by kojiromike** [comment] 2015-02-28 16:52
I was unable to reproduce this with

```
$ boot2docker version
Boot2Docker-cli version: v1.5.0
Git commit: ccd9032
$ docker-compose --version
docker-compose 1.1.0
$ ( cd ~/dev/fig && git describe --tags )
1.1.0-6-g44f5a3e
```

I get

```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping dockerdbbootstrap_web_1...
Stopping dockerdbbootstrap_bootstrap_1...
Stopping dockerdbbootstrap_db_1...

Aborting.
```
and then
```
$ docker-compose ps
Found multiple config files with supported names: docker-compose.yml, fig.yml
Using docker-compose.yml

            Name                          Command               State     Ports 
-------------------------------------------------------------------------------
dockerdbbootstrap_bootstrap_1   /bootstrap.sh sleep infinity   Exit 137         
dockerdbbootstrap_db_1          /entrypoint.sh mysqld          Exit 0           
dockerdbbootstrap_web_1         node /src/index.js             Exit 137         
```

**Comment by mbentley** [comment] 2015-02-28 17:05
Hmm, it took me two tries to reproduce it again when I was taking a quick asciinema recording >> https://asciinema.org/a/17144

**Comment by Glideh** [comment] 2015-10-14 12:31
I'm getting this almost 100% of the time when hitting Ctrl+C from `docker-compose up`.
It seems to happen only on web containers for me (Apache more specifically)

**Comment by dnephin** [comment] 2015-10-19 21:46
Sorry for the slow reply on this. I've updated the title to better reflect what I think the issue is here.

Seeing "Aborting" is not itself an issue (we echo that when we get a KeyboardInterupt). The issue is that we're not properly shutting down containers.

We setup a signal handler for sigint, so I'm not entirely sure how the signal handler is skipped.

**Comment by Glideh** [comment] 2015-10-20 10:43
I'm getting the impression a timeout (maybe too short) is hit before the services can stop entirely.

**Comment by dnephin** [comment] 2015-11-13 21:21
I believe this will be fixed by #2364 (and I've marked it as such). If you're able to reproduce this reliably, and have a minute to try it out, it'd be great if you could grab that branch and let me know.  Or even if you want to wait until it gets into master to try it with the master build, that would also be great.

**Closed** 2015-11-20 16:58 UTC
Labels: area/up, kind/bug

**Comment by dnephin** [comment] 2015-11-20 20:20
Ok, I believe this to be fixed in master. It was a little difficult to reproduce the issue, so if you have a chance, please try it out with master. If you can still reproduce the issue, please let me know.

Normally you can download a master build from https://dl.bintray.com/docker-compose/master/ , but it looks like travis-ci is having problems with the linux builds.  It seems to be working for the osx builds, so those should be updated.

**Comment by dnephin** [comment] 2015-12-28 22:03
There is a change up in #2585 which goes back to using exceptions. If you're interested please try it out, and let me know if this issue has resurfaced with those changes.

**Comment by jayfk** [comment] 2016-02-17 09:36
Still seeing this on master.

    ^CERROR: Aborting.

Maybe reopen the issue?

**Comment by jamesrwhite** [comment] 2016-02-17 14:12
I'm also seeing this since updating to the latest version of docker-compose recently.

**Comment by dnephin** [comment] 2016-02-17 15:59
I opened #2904 for this, which includes more details.

**Comment by lorenmh** [comment] 2016-03-08 21:40
```
^CERROR: Aborting.
```

I am also seeing this on all of my devices that I use docker-compose.

I had an older version of docker-compose on my Macbook pro (sorry, not sure of what version it was) from ~ a year ago, and this never happened.  Once I upgraded to the version used in Docker toolbox (1.6.0, build d99cad6), it began doing it on my Macbook as well.

I have seen this on my Ubuntu machine and on two MBPs.

Running `docker-compose up -d` with `docker-compose kill` never has this issue

**Comment by Vanuan** [comment] 2016-04-19 04:22
Seeing as well
docker-compose --version
docker-compose version 1.6.2, build 4d72027

**Comment by dreyks** [comment] 2016-05-12 23:18
Still happening
docker-compose version 1.7.1, build 0a9ab35

@dnephin reopen maybe?

**Comment by dnephin** [comment] 2016-05-12 23:53
#3347
