### ISSUE TITLE
compose doesn't unmount volumes on recreation [ v 1.2.1 ]

### ISSUE THREAD

**Issue by pramodhkp** [docker/compose#3657] opened 2016-06-29 05:45 UTC
docker-compose doesn't remove the mount points inside the container when you remove it in docker-compose file and recreate the container. 

For example, 

Inital config:

```
kibana:
  image: registry.ops.directi.com/slant/arcus-kibana
  ports:
    - 172.17.40.59:19200:80
 volumes:
    - ./kibana/default.conf:/etc/nginx/conf.d/default.conf

```

Start the container, and the volume is mounted.
Edited config:

```
kibana:
  image: registry.ops.directi.com/slant/arcus-kibana
  ports:
    - 172.17.40.59:19200:80
```

Recreating the container should remove the volume, but it still exists. Removing the container and creating it back works.

**Comment by shin-** [comment] 2018-03-28 21:56
Closing as this is by design: https://docs.docker.com/compose/overview/#preserve-volume-data-when-containers-are-created

**Closed by shin-** 2018-03-28 21:56 UTC
