### ISSUE TITLE
Disable yaml file checks unrelated to 'build' command

### ISSUE THREAD

**Issue by KamilKopaczyk** [docker/compose#2667] opened 2016-01-15 10:33 UTC
Hello,

docker-compose version 1.5.2

i'm unable to build images, if there's 'env_file' pointing to nonexistent file. Since building has nothing to do with container's environment, maybe it should be possible?

I think it's related to #1585 and possibly other properties, that are used solely for containers, not building/images.
I also remember(but couldn't find it), there was a discussion whether the build tool should be separated from container management commands. Maybe this issue should be stated as an argument there too.

**Comment by dnephin** [comment] 2016-01-15 16:03
This is a duplicate of #1973, it would be nice to support, but at this point it's really large change and it's not a frequently requested feature, so it's hard to prioritize.

Closing this issue as a duplicate.

**Closed by dnephin** 2016-01-15 16:03 UTC
