### ISSUE TITLE
links not work for network_mode: "bridge"

### ISSUE THREAD

**Issue by wangliangliang2** [docker/compose#9053] opened 2021-12-19 01:54 UTC
the following yaml will automatic create new network, then  nginx2 can ping nginx1.
```
version: '3'
services:
    nginx1:
        image: nginx:alpine
        container_name: "nginx1"
    nginx2:
        image: nginx:alpine
        container_name: "nginx2"
```
but I don't want it to create  new network , so I use the following yaml. it turns out that nginx2 can't ping nginx1. 
 it shows me:  ping: bad address 'nginx1'.
```
version: '3'
services:
    nginx1:
        image: nginx:alpine
        network_mode: "bridge"
        container_name: "nginx1"
    nginx2:
        image: nginx:alpine
        network_mode: "bridge"
        links:
            - nginx1
        container_name: "nginx2"
```
but  when you use the following code , nginx1 and nginx2 will add to default bridge network and nginx2 can ping nginx1.
```
docker run -d --name nginx1  nginx:alpine
docker run -d --name nginx2 --link nginx1 nginx:alpine
```
 docker inspect nginx2 will show then the follwing code.
```
"Links": [
                "/nginx1:/nginx2/nginx1"
            ],
```

so,  is there a way to fix this problem when docker-compose use default bridge can't link other service?

**Comment by ghislain-bernard** [comment] 2022-03-07 10:18
Hello,
I have exactly the same problem links tag KO into bridge mode.... le I went back to docker-compose version 1.29.2.
Best regards.

**Comment by navneet0693** [comment] 2022-06-17 13:48
I have the almost same issue where I am using "depends_on" instead of links and the containers are not able to see each other when I use docker compose. So, I am forced to revert to docker-compose v1

**Comment by navneet0693** [comment] 2022-06-17 13:53
The documentation here: https://docs.docker.com/network/bridge/ says the containers should be able to see each other using links but links is legacy.

**Comment by laurazard** [comment] 2022-06-18 11:49
Hiya @wangliangliang2 (and everyone else facing the same issue): I believe [this commit](https://github.com/docker/compose/commit/81182fca536124778d722a14814a8858ee14029f) should address this issue. Please check again when the next version is released to see if the issue is resolved!

**Comment by navneet0693** [comment] 2022-06-18 16:03
@laurazard Thank you for this! <3 Also, I would like to throw out one observation that the `depends_on`  on Docker for Mac is working fine and the containers are able to connect to each other using the services name. While this doesn't work on Linux. Trust me, I have read a lot of documentation related to Docker compose & network but it doesn't mention this behavior or anything related.

My PR is: https://github.com/goalgorilla/open_social_scripts/pull/44

**Comment by laurazard** [comment] 2022-07-03 19:48
I'm going to close this issue since the original problem has been fixed/shipped. @navneet0693 feel free to open another issue for the problem you're dealing with.

**Closed by laurazard** 2022-07-03 19:48 UTC
