### ISSUE TITLE
Provide a way to override environment variables

### ISSUE THREAD

**Issue by kballenegger** [docker/compose#1089] opened 2015-03-11 00:56 UTC
A fairly common use case on our team is to keep `docker-compose.yml` in source control, but custom dev setups require overriding some configuration variables set in `docker-compose.yml`. The only way for that to work is to use a variable with no value, so it gets pulled from the environment.

It'd be nice to provide a default value for it, however. Something akin to `SOMEVAR ||= defaultvalue`.

**Comment by thaJeztah** [comment] 2015-03-15 22:20
I think this is a dup of https://github.com/docker/compose/issues/495. There's a pull request that implements this in https://github.com/docker/compose/pull/845.

If you agree that this is a duplicate of #495, could you close this issue (for housekeeping :))

**Comment by kballenegger** [comment] 2015-03-16 02:18
In the thread for #495 somebody suggested this syntax in `fig.yml`:

```yaml
app:
  image: mickey/theapp:${APP_VERSION:latest}
```

If it were implemented like that, that would solve this issue.

**Comment by thaJeztah** [comment] 2015-03-16 06:57
I think #845 will cover that; you can see some sample in the code; https://github.com/docker/compose/pull/845/files

**Comment by dnephin** [comment] 2016-01-18 23:47
We've got a few duplicate issues about default values. Going to close this issue for #2441

**Closed by dnephin** 2016-01-18 23:47 UTC
Labels: area/config, kind/enhancement
