### ISSUE TITLE
mounts param is not supported in API versions < 1.30

### ISSUE THREAD

**Issue by quinn** [docker/compose#5500] opened 2017-12-21 02:59 UTC
this is my config:

```
version: '3.2'

services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
```

it throws the error after building the image:

```
ERROR: for example_app_1  mounts param is not supported in API versions < 1.30

ERROR: for rails-app  mounts param is not supported in API versions < 1.30
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 956, in up
  File "compose/project.py", line 479, in up
  File "compose/parallel.py", line 80, in parallel_execute
docker.errors.InvalidVersion: mounts param is not supported in API versions < 1.30
Failed to execute script docker-compose
```

I'm using docker for mac.

**Comment by quinn** [comment] 2017-12-21 03:06
Update: using the "short syntax" worked as expected / the same. I prefer the long syntax :'(

**Comment by shin-** [comment] 2017-12-21 06:55
Duplicate of #5489 

It'll be fixed in the next d4mac update, but until then if you bump your Compose file version to `3.3` things should clear up.

**Closed by shin-** 2017-12-21 06:55 UTC
