### ISSUE TITLE
[BUG]  failed to compute cache key: failed to calculate checksum of ... COPY file from local to docker enviroment

### ISSUE THREAD

**Issue by lethienhoang** [docker/compose#11667] opened 2024-03-27 14:47 UTC
### Description

<img width="1490" alt="Screenshot 2024-03-26 at 9 39 52 PM" src="https://github.com/docker/compose/assets/45428011/ba7ed017-c873-48b9-8fb4-5b6a0b4db9ea">

And change as picture
![image](https://github.com/docker/compose/assets/45428011/4e54a618-7ce4-4a9f-a642-8f7b2665787c)

I'm using Orbstack instead Docker app.
I'm trying to build docker compose with structure as above picture. I alwasy getting same error while copy file.

I dont know that what's happing. Where is the root causes???

Thanks all.

### Compose Version

```Text
Docker Compose version v2.24.5
```

### Docker Environment

```Text
Version:    25.0.5
```

**Comment by lethienhoang** [comment] 2024-03-27 14:51
I also try to copy from stage as `COPY --from=build-stage /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf:`. It still be failed

**Comment by lethienhoang** [comment] 2024-03-28 01:04
> @lethienhoang can you build the image with the `docker build` command? If you have the same issue that would mean the problem isn't on the Compose side

Yes, I have the same issue with the docker build. :(

**Comment by Karlitos88** [comment] 2024-03-28 01:37
Thanks for confort  personal Processing
Account reVility code questions confirmt
Support systems until transaction fees
Trayectoria fantasma critery radical fund
Ussing principal mrenver assed prodicg
Método expectantd cloud minimal united
Price
db3277984.S3 Amazomaws  thisXML
File does not appears  costum any is
Style three generations Standards is
Show

**Comment by ndeloof** [comment] 2024-03-28 07:23
closing as issue is not related to Docker Compose
Please report build issues to github.com/docker/buildx with a reproduction example

**Closed by ndeloof** 2024-03-28 07:23 UTC
Labels: kind/bug, status/0-triage

**Comment by franconte98** [comment] 2024-05-22 14:41
I had the same issue on my project and i have no idea why this got closed without actual solving the issue. I solved it by changing:

`COPY --from=app /app/dist /usr/share/nginx/html`

to:

`COPY --from=app /app/dist/"Name_Of_The_Project" /usr/share/nginx/html`

I was using angular and here you can find the Name_Of_The_Project inside your angular.json. The issue is that the error you get really says nothing about it and therefor it's difficult to understand the deal. Hope this was helpful 😄

**PS:** The complete **Dockerfile** i made is:

```
FROM node:14.17.1-alpine AS app
WORKDIR '/app'
COPY . '/app'
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=app /app/dist/My_Project /usr/share/nginx/html
RUN ls /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
```

**Comment by azwdevops** [comment] 2024-07-25 13:12
I had the same issue when using react and vite, i was referencing the /app/build but vite builds file into dist not build folder 
Code causing the error 
`FROM node:20-alpine AS builder
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder **/app/build** /usr/share/nginx/html`

Corrected code 

`FROM node:20-alpine AS builder
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder **/app/dist** /usr/share/nginx/html`

**Comment by biradarsm** [comment] 2024-11-10 14:06
Yes, changing the app/build to app/dist resolved the error for me
