### ISSUE TITLE
docker-compose up fails when image doesn't exist

### ISSUE THREAD

**Issue by andrefreitas** [docker/compose#1728] opened 2015-07-20 09:48 UTC
When I invoke docker-compose as:

    docker-compose up

Sometimes it fails saying that the image needs to be build and that --no-build  was passed. I managed to fix this by destroying all containers, but is an ugly solution.

    docker stop $(docker ps -a -q)
    docker rm $(docker ps -a -q)

**Comment by aanand** [comment] 2015-07-20 11:08
Can you reliably reproduce it? Please paste the steps if so.

**Comment by andrefreitas** [comment] 2015-07-21 19:27
Hi,
I tried but I could not reproduce it. But I believe this is something related with changing the compose file after launching a container.

If this happens again I will try to trace what might happen and let you know.

**Comment by thaJeztah** [comment] 2015-08-09 01:42
I think this can be closed then?

**Comment by andrefreitas** [comment] 2015-08-09 15:20
@thaJeztah if you believe that there is no issue/bug here close it :)

**Comment by thaJeztah** [comment] 2015-08-09 16:04
@andrefreitas sorry, my commend was a bit short (not my intent to sound rude).

I'm not saying there *isn't* a bug, but not having a repro-case makes it hard to resolve, and keeping the issue opened probably doesn't help in that case.

I'm not a maintainer in *this* repository; but in the Docker repository, we try to cleanup the issues once in a while to keep it manageable. My comment was intended as a reminder that this issue would probably be a candidate for closing (pending a way to reliably reproduce it)

**Closed** 2015-09-29 15:10 UTC
