### ISSUE TITLE
Avoid underscore on names (ie: project_container)

### ISSUE THREAD

**Issue by mostolog** [docker/compose#4475] opened 2017-02-13 09:10 UTC
As commented in https://github.com/docker/distribution/issues/2160 and trying to converge in all docker products, not any hostname-related value should contain underscores _"\_"_

Currently, even for V3, compose/stack containers seems to be created like **project_service** and that seems to be an undesired behavior.

cc @thaJeztah @stevvooe

Regards
Related (opened within this repo):
https://github.com/docker/compose/issues/4442
https://github.com/docker/compose/issues/4002
https://github.com/docker/compose/issues/3912
https://github.com/docker/compose/issues/229

**Comment by mostolog** [comment] 2017-02-15 15:36
May I know duplicate issue #?

**Comment by stevvooe** [comment] 2017-02-15 23:24
@shin- PTAL. What is this a duplicate of?

**Comment by shin-** [comment] 2017-02-16 00:19
#3912 which is a duplicate of #229

**Comment by mostolog** [comment] 2017-02-16 08:51
Well...not exactly a duplicate, as I'm talking about the separator between project and service, but would accept whatever you like, if it fixed :stuck_out_tongue:

**Comment by teutat3s** [comment] 2019-10-12 17:13
Not stale at all, I'd say this is still unresolved? Consul DNS also doesn't like underscores in hostnames and complains... Is it possible to make this more flexible? Like letting the user change the seperator?

**Comment by ndeloof** [comment] 2019-10-14 09:21
Closing as a duplicate for https://github.com/docker/compose/issues/229

**Closed by ndeloof** 2019-10-14 09:21 UTC
Labels: duplicate
