### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by fgirardey** [docker/compose#1885] opened 2015-08-18 14:53 UTC
Hi,

I am experiencing a problem with the command docker-compose.

I am on OS X 10.10.5, I just installed the new [Docker Toolbox](https://www.docker.com/toolbox) and try to run a `docker-compose up` and I got an `Illegal instruction: 4` error.

Even if I do a simple `docker-compose --version` I got the same error. I tried to install by the [CURL way](http://docs.docker.com/compose/install/) and I've got the same error again.

**Comment by aanand** [comment] 2015-08-18 16:29
Duplicate of #271

**Comment by aanand** [comment] 2015-08-18 16:29
In summary: the Compose binary doesn't yet work on older Macs. The simplest workaround is to install using pip.

**Closed by aanand** 2015-08-18 16:29 UTC

**Comment by fgirardey** [comment] 2015-08-18 18:32
Do you mean at a material level ?

The mac i work on is a 2009 one…

**Comment by aanand** [comment] 2015-08-19 10:09
No, older models. To be precise, it's your CPU. https://github.com/docker/compose/issues/271#issuecomment-113326266:

> This is happening because by default, Homebrew builds Python with all of the optimizations that the build machine can support. Assuming the build is happening on a Mac with a Sandy Bridge or newer processor, those optimizations will include the use of AVX instructions.

**Comment by Tiamat59** [comment] 2015-08-20 15:08
I have the same issue.

I try to install docker-compose with git.
<code>git clone https://github.com/docker/compose.git</code>
<code>cd compose</code>
<code>sudo python setup.py install</code>

And it's work but, the up function return this message.

<code>
Couldn't connect to Docker daemon at http://localhost:4243 - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
</code>

**Comment by cleemansen** [comment] 2016-01-06 18:10
The [referenced workaround](https://github.com/docker/compose/issues/271#issuecomment-62573709) ```brew install python; pip install docker-compose``` worked for me (MacBook Pro Mid 2009).

**Comment by javierdechile** [comment] 2016-01-23 22:06
Great! `pip install docker-compose` worked awesome on my Macbook Core 2 duo mid 2009.

**Comment by iiman** [comment] 2016-03-24 00:56
I had the same problem: `pip install --upgrade docker-compose` fixed the error.

**Comment by WidgetsBurritos** [comment] 2016-04-13 15:55
For anyone running into this issue and who find this page from Google: If the `pip` method mentioned by @iiman doesn't work, I've setup an alternate repository that compiles docker-compose directly from an older mac. This way you can download a binary that should work on your system.

https://github.com/WidgetsBurritos/docker-compose-old-mac

The good thing with these binaries is they are forward compatible with newer Macs as well (at least so far). 

These binaries are currently being used by Kalabox, so they don't have to worry about whether or not the user is on an old/new Mac.  [See: kalabox/kalabox#901]

**Comment by WidgetsBurritos** [comment] 2016-04-13 16:01
Actually after a bit of digging, it appears Docker fixed the issue in 1.7.0-rc1 so, my repository isn't necessary anymore.  See: https://github.com/docker/compose/issues/271#issuecomment-201203732
