### ISSUE TITLE
Docker-compose copy/add for single files/directories 

### ISSUE THREAD

**Issue by jadon1979** [docker/compose#6643] opened 2019-04-11 15:49 UTC
**Scenario:**  
SomeService\
conf files are stored in `/etc/someservice/conf.d`\
the directory contains a, b, and c conf files.

Your task is to add|override conf files in this directory given particular environments (dev, staging|feature, etc).  You cannot map the conf.d directory, using `volumes`, because that will override the conf.d directory and destroy the current conf files.  Option 1: Add these files as individual entries under `volumes`.  Ultimately, you may end up with quite a few files, going numerous places, and a very large volumes key.  Option 2: Add a copy, add, or inject key in the docker-compose that allows you to specify a file, or directory, to copy over.

```
svc:
  ...
  copy:
    - ./services/someservice/conf.d:/etc/someservice/conf.d
  ...
...
```

This would copy the files from the local conf.d directory and add or replace files in the image's conf.d directory.

_"Why wouldn't you just add the service as a separate image?"_

I would still have the same issue with handling multiple confs on-the-fly.

_"Why wouldn't you just handle it in the dockerfile?"_

There are numerous reasons and all of them are why docker-compose exist.

**Comment by chris-crone** [comment] 2019-04-12 11:49
Thanks for the suggestion @jadon1979. I believe this is a duplicate of https://github.com/docker/compose/issues/5523 so will close this issue.

**Closed by chris-crone** 2019-04-12 11:49 UTC
