### ISSUE TITLE
Building from remote git folder

### ISSUE THREAD

**Issue by Nitr4x** [docker/compose#6375] opened 2018-11-27 16:50 UTC
## Description of the issue

Since the last docker update on windows 10 pro, I'm unable to build docker image from a remote git repository through the docker-compose command.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.1, build b02f1306
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
version: '3'

services:
  test:
    build: https://github.com/Nitr4x/p0wn-box
```

## Steps to reproduce the issue

1.  docker-compose up -d
2.
3.

### Observed result

Cannot build the associated services

### Expected result

Build the given services

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1080, in up
  File "compose\cli\main.py", line 1076, in up
  File "compose\project.py", line 475, in up
  File "compose\service.py", line 356, in ensure_image_exists
  File "compose\service.py", line 1080, in build
  File "site-packages\docker\api\build.py", line 142, in build
TypeError: You must specify a directory to build in path
[18908] Failed to execute script docker-compose
```

## Additional information

I tried serveral method that I found over the internet, without success.

e.g. Using the context and dockerfile keywords and so on...

**Comment by shin-** [comment] 2018-11-27 20:04
Duplicate of #6354

**Closed by shin-** 2018-11-27 20:04 UTC
