### ISSUE TITLE
orphaned containers are not removed

### ISSUE THREAD

**Issue by MichaelNesterenko** [docker/compose#2593] opened 2016-01-02 20:38 UTC
I have following simple services:

```
srv_0:
  image: busybox
  command: sleep 300
  links:
    - srv_1
 
srv_1:
  image: busybox
  command: sleep 300
```

They are successfully started with `up` command:

> docker-compose up srv_0

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                   NAMES
3f553caaedfb        busybox                       "sleep 300"              18 seconds ago      Up 17 seconds                                                               dockercompose_srv_0_1
45bf185cc27f        busybox                       "sleep 300"              31 minutes ago      Up 18 seconds                                                               dockercompose_srv_1_1
```

Now srv_1 is deprecated and I replace it with srv_2:

```
srv_0:
  image: busybox
  command: sleep 300
  links:
    - srv_2
 
srv_2:
  image: busybox
  command: sleep 350
```
> docker-compose up srv_0

still works successfully, but it leaves orphaned `srv_1`:

```
[vagrant@epplkraw0047t1 docker_compose]$ sudo docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                   NAMES
5262677b73c9        busybox                       "sleep 300"              41 seconds ago      Up 40 seconds                                                               dockercompose_srv_0_1
922f5e4172b8        busybox                       "sleep 350"              33 minutes ago      Up 51 seconds                                                               dockercompose_srv_2_1
45bf185cc27f        busybox                       "sleep 300"              33 minutes ago      Up 2 minutes                                                                dockercompose_srv_1_1
```

**Comment by vvitayau** [comment] 2016-01-04 03:05
:+1: 

Seeing a similar issue for ``docker-compose run`` but not for ``docker-compose up``

where __./docker-compose.yml__
```
myservice:
  image: mongodb:3
```

### WORKS for ``docker-compose up``
GM28126:test victorv$ docker-compose -f docker-compose.debug.yml up -d myservice
Starting test_myservice_1
GM28126:test victorv$ docker-compose -f docker-compose.debug.yml stop myservice
Stopping test_myservice_1 ... done
GM28126:test victorv$ docker-compose -f docker-compose.debug.yml rm -vf myservice
Going to remove test_myservice_1
Removing test_myservice_1 ... done
```

### FAILS for ``docker-compsoe run``
```
GM28126:test victorv$ docker-compose -f docker-compose.debug.yml run -d myservice
test_myservice_run_1
GM28126:test victorv$ docker-compose -f docker-compose.debug.yml stop
GM28126:test victorv$ docker-compose -f docker-compose.debug.yml rm -vf
No stopped containers
GM28126:test victorv$ docker-compose -f docker-compose.debug.yml ps
        Name                  Command          State     Ports
----------------------------------------------------------------
test_myservice_run_1   /entrypoint.sh mongod   Up      27017/tcp
```

**Comment by dnephin** [comment] 2016-01-04 16:29
I think this is a duplicate of #1477 which has a PR open for it (#2218)

**Comment by dnephin** [comment] 2016-02-03 19:29
Closing as duplicate.

**Closed by dnephin** 2016-02-03 19:29 UTC
Labels: area/cli, kind/enhancement
