### ISSUE TITLE
Blank lines in docker-compose pull output when piping

### ISSUE THREAD

**Issue by wader** [docker/compose#1839] opened 2015-08-10 19:19 UTC
Hi, when piping the output from `docker-compose pull` the progress details seems to just be blank lines. Not really sure what one would like the output to be when there is not tty, wait for all layers to download and then output "final" status for each?

How to reproduce:

    docker-compose pull | cat

**Comment by aanand** [comment] 2015-08-11 16:00
`docker pull redis | cat` is pretty messy, but better than outputting blank lines. Perhaps we need to do a bit more manual flushing.

**Comment by dnephin** [comment] 2015-11-05 19:05
Duplicate of #1490

**Closed by dnephin** 2015-11-05 19:05 UTC
