### ISSUE TITLE
Evaluate `environment` variables when setting

### ISSUE THREAD

**Issue by timfallmk** [docker/compose#1553] opened 2015-06-15 19:43 UTC
When using the `environment` setting in the yml file, it does not appear to evaluate any input to env variables. For example:

```yaml
environement:
  - HOST_IP=${<some other service>_PORT_4001_TCP_ADDR}
```
yields `HOST_IP=HOST_IP=${<some other service>_PORT_4001_TCP_ADDR}`

But running:
```shell
docker run --env HOST_IP=${<some other service>_PORT_4001_TCP_ADDR}
```
will yield
`HOST_IP=<proper address>`

The primary use case here is to properly set env variables for linked containers using the env variables set by `--link`

**Comment by aanand** [comment] 2015-06-16 18:01
Duplicate of #1377

**Closed by aanand** 2015-06-16 18:01 UTC
