### ISSUE TITLE
Network created by compose using --x-networking should be deleted when the servers are removed

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#2346] opened 2015-11-08 19:02 UTC
Started an application using https://github.com/arun-gupta/docker-images/blob/master/wildfly-mysql-javaee7/docker-compose.yml as:

```console
docker-compose --x-networking up -d
Creating network "wildflymysqljavaee7" with driver "None"
Creating wildflymysqljavaee7_mywildfly_1
Creating db
```

```console
docker-compose --x-networking up -d
Creating network "wildflymysqljavaee7" with driver "None"
Creating wildflymysqljavaee7_mywildfly_1
Creating db
```

Compose creates a bridge network (related to https://github.com/docker/compose/issues/2345). Stopping and removing the application remove the network as well.

`docker-compose --x-networking stop` has no effect as well.

Good thing is the network is not created with every invocation of `docker compose up -d`.

**Comment by dnephin** [comment] 2015-11-08 19:06
Duplicate of #2279

**Closed by dnephin** 2015-11-08 19:06 UTC
