### ISSUE TITLE
`create` does not create default network, only `up` does

### ISSUE THREAD

**Issue by spacediver** [docker/compose#3068] opened 2016-03-03 08:46 UTC
```
:~/test$ docker-compose config
networks: {}
services:
  web:
    image: nginx
version: '2.0'
volumes: {}

:~/test$ docker-compose create
Creating test_web_1
ERROR: network test_default not found
```

Mustn't `create` create network as well? 

I see this command as "create everything (including networks, especially handy default), but not start yet"

**Comment by dnephin** [comment] 2016-03-03 14:45
Duplicate of #2908

**Closed by dnephin** 2016-03-03 14:45 UTC
