### ISSUE TITLE
Networks & overriding configuration

### ISSUE THREAD

**Issue by kongslund** [docker/compose#2843] opened 2016-02-07 02:04 UTC
I have the following files:

`docker-compose.yml`
```yaml
version: "2"
services:
  some-service:
    image: busybox
    command: "sleep 120000"
    networks:
      - some-tier

networks:
  some-tier:
```

`docker-compose.override.yml`
```yaml
version: "2"
services:
  some-service:
    environment:
      FOO: bar
```

When running Compose I experience the following

```sh
$ docker-compose --version
docker-compose version 1.6.0, build d99cad6
$ docker-compose up -d
WARNING: Some networks were defined but are not used by any service: some-tier
Creating developer_some-service_1
$ docker inspect -f "{{json .NetworkSettings.Networks}}" developer_some-service_1
{"developer_default":{...}}
```

I would've expected that the network `some-tier` would be used by `some-service`. Is my expectation wrong?

**Comment by dmaumenee** [comment] 2016-02-07 07:54
Hello,
This is the same issue as #2839

**Comment by kongslund** [comment] 2016-02-07 07:57
The example above is not using `extends`.

**Comment by dmaumenee** [comment] 2016-02-07 08:23
This issue looks like #2840
`docker-compose up`
is roughly the shortcut of :
` docker-compose -f docker-compose.yml -f docker-compose.override.yml up`

**Comment by dnephin** [comment] 2016-02-07 17:43
This is a duplicate of #2839.  One uses extends and the other uses multiple files, but the same function is used to merged in both cases.

Going to close as a duplicate and track in #2839

**Closed by dnephin** 2016-02-07 17:43 UTC
