### ISSUE TITLE
[BUG] Error since 2.29.3 when --force-recreate is used with container that mounts npipe - Error response from daemon: invalid mount config for type "bind": CreateFile \\.\pipe\docker_engine\

### ISSUE THREAD

**Issue by mjusix** [docker/compose#12128] opened 2024-09-16 12:05 UTC
### Description

With 2.29.3 the following docker-compose.yml in combination with the following command leads to an error:

docker-compose.yml:
```
    ...
    volumes:
      - \\.\pipe\docker_engine\:\\.\pipe\docker_engine\
    ...
```

command:
`
docker compose up -d --force-recreate <CONTAINER_NAME> --remove-orphans
`

I'm using a Admin-Powershell.

### Steps To Reproduce

1. Install docker-ce for Windows (10, 11, Server 2019, etc.)
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1" -o install-docker-ce.ps1
.\install-docker-ce.ps1`
2. Install docker compose
`choco install docker-compose --version=2.29.3 -y`
3. Create a docker-compose.yml like above.
4. Open Admin-Powershell (v5)
5. Run the following command in Admin-Powershell:
6. docker compose up -d --force-recreate <CONTAINER_NAME> --remove-orphans

### Compose Version

```Text
v2.29.3
```

### Docker Environment

```Text
Client:
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.3
    Path:     C:\ProgramData\Docker\cli-plugins\docker-compose.exe

Server:
 Containers: 8
  Running: 6
  Paused: 0
  Stopped: 2
 Images: 156
 Server Version: 26.1.4
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 22631 (22621.1.amd64fre.ni_release.220506-1250)
 Operating System: Microsoft Windows Version 23H2 (OS Build 22631.4169)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.69GiB
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by glours** [comment] 2024-09-17 09:22
Should have been fixed by https://github.com/docker/compose/releases/tag/v2.29.5

**Comment by mjusix** [comment] 2024-09-19 05:34
Thank you for your reply :)

I've updated now to 2.29.5, but I'm getting the following (new) error message:
`Error response from daemon: invalid mount config for type "bind": invalid propagation mode: rprivate`

Kind regards
Dominic

**Comment by samruddhikhandale** [comment] 2024-09-19 19:23
> 've updated now to 2.29.5, but I'm getting the following (new) error message:
Error response from daemon: invalid mount config for type "bind": invalid propagation mode: rprivate

@glours  Same here, since we updated to docker-compose `v2.29.5`, we started getting followings errors while creating docker compose containers 👇 

```
Error response from daemon: invalid mount config: must use either propagation mode \"rslave\" or \"rshared\" when mount source is within the daemon root, daemon root: \"/var/lib/docker\", bind mount source: \"xyz\", propagation: \"rprivate\""}
```

Also, I'd like to highlight that we are using Linux distro where we could reproduce this issue.

**Comment by Crosenhain** [comment] 2024-09-19 21:25
Downgrading to 2.29.2 on Linux seems to be a workaround for now. 

I suspect that the change that introduced the problem is https://github.com/docker/compose/pull/12133 but I have yet to test reverting that change.

**Comment by Crosenhain** [comment] 2024-09-23 10:03
@glours the [v2.29.7](https://github.com/docker/compose/releases/tag/v2.29.7) release is working for me, thank you.

**Comment by mjusix** [comment] 2024-09-25 13:26
Thank you!!! 2.29.7 fixed my problem too :)

**Closed** 2024-09-25 13:27 UTC
Labels: kind/bug
