### ISSUE TITLE
Make docker's `exec` command available through docker-compose

### ISSUE THREAD

**Issue by Torte** [docker/compose#1073] opened 2015-03-06 10:04 UTC
Hi,

this is actually a feature request. Docker was adding the `exec` command with Docker 1.4 which lets you execute commands on a running container (rather than creating a new container each time, like `run` does). I would love this to be available in docker-compose as well. 
Right now I can use the `docker exec` command directly, but it is not as convenient as using the commands through compose.
Thanks.

**Comment by Starefossen** [comment] 2015-03-06 10:11
Duplicate of #593

**Comment by Torte** [comment] 2015-03-06 10:12
Ok, I was not able to find that issue. Thanks. This one can be closed then. :)

**Closed** 2015-03-06 10:58 UTC
