### ISSUE TITLE
Proposal: Add the possibility to create binstubs

### ISSUE THREAD

**Issue by eidge** [docker/compose#1362] opened 2015-04-27 22:25 UTC
I'm using docker from development to production and while developing I find annoying the need to prepend ```docker-compose run --rm SOME-CONTAINER PUT-YOU-FAVORITE-TOOL-HERE arg1 arg2```.

For instance, image you're working in a ruby project, you'll run ```docker-compose run ruby-container --rm rake some-task``` at least a dozen times a day. The way I'm solving this right now is creating a binstub under ```./bin/rake``` and adding ```.bin```to my ```PATH```.

The binstub is a simple delegate to a new container run implemented like so: ```docker-compose run --rm ruby-container rake $@```.

My proposal is to **add a new key to docker-compose.yml**, like so:

```yml
ruby:
  image: ruby
  binstubs:
    - rake
    - rails
    - some-other-random-executable
```

And then (maybe) in the build process actually generate these binstubs.

Let me know if this makes sense for you, of if you've solved this in any other way.

Thank you,
Hugo Ribeira

**Comment by kojiromike** [comment] 2015-04-29 14:31
I actually like the idea of binstubs as an aliasing shortcut, but for now, without that syntactical sugar, am I right in thinking it's the same as below?

```yaml
ruby:
    image: ruby
    entrypoint: ["bash", "-c"]
rake:
    extends: ruby
    entrypoint: ["rake"]
rails:
    extends: ruby
    entrypoint: ["rails"]
…
```

**Comment by eidge** [comment] 2015-04-30 17:47
Sort of, yes.

You end up creating another service (new build included, although it should get everything from cache) if I understand correctly and it only shaves off a single word of the command.

You'd use:

```docker-compose run --rm rake ARGS```

instead of

```docker-compose run --rm app rake ARGS```

right?

It's still impossible to use without a stub. Imagine writing ```docker-compose run --rm rspec // test framework for ruby``` a couple hundred times a day :P

:boy: :gun:

**Comment by villlem** [comment] 2015-04-30 18:34
I use compose the same way the @kojiromike suggests. And as you say its annoying. But if you mix `entrypoint` and `command` you can save a lots of typing. Also aliases are usefull. Right now i have alias for `docker-compose run --rm` and it saves me a lot of typing.

**Comment by kojiromike** [comment] 2015-04-30 18:56
Yessssss.

```bash
##
# Because `docker-compose` is too long.
compose () { 
    docker-compose "$@"
}

##
# Because `docker-compose run --rm` is too long.
compost () { 
    compose run --rm "$@"
}
```

**Comment by eidge** [comment] 2015-05-01 11:12
yup combining both does make sense and basically replaces the binstub functionality! :)

Would you consider this one closed or do you think it's still relevant?

**Comment by villlem** [comment] 2015-05-02 21:06
From what I see around this is not how compose is intended to be used. As much I would love compose support this use cases I'm fine with home breed solutions.

**Comment by kojiromike** [comment] 2015-05-02 23:42
@villlem I'm all in favor of the SRP, but docker currently doesn't have something else filling this gap. In my opinion this is closer to the original intent of fig than using compose to spec and control prod environments over machine or swarm (which is where I see it heading).

Both problems need to be solved, and not necessarily by the same tool, but if not by compose, then what?

**Comment by eidge** [comment] 2015-05-03 18:06
I see compose as a tool to spec and manage/control docker containers lifecycle.

On the other end, I see docker as a way to containerize and replicate environments in an hassle free way. Effectively allowing you to use the same environment in production and development but to use it in development we actually need a pleasant way to interact with *dockerized* tools, binstubs provide that interface in a way we're used to.

Feeling complicated and costly (think home breed solutions to problems as simple as command line verbosity) actually drives new users away. The same way docker drove me away before I actually found out it could be simple if used in conjunction with fig.

Regarding SRP, I see this more as an interface problem than a new responsibility.

Take [bundler](http://bundler.io/) for instance, it's responsibility is to manage dependencies for each project but writing ```bundle exec```every time got in the way, so they added binstubs.

If they ended up creating a different program just to create binstubs I think it would have ended up hurting more than not having a 5 line shell script.

**Comment by dnephin** [comment] 2015-09-01 14:57
I think it's unlikely we will implement a feature like this. Aliasing commands is just not within the scope of compose.

Either way, this issue is basically a duplicate of #433.

Going to close as duplicate.

**Closed by dnephin** 2015-09-01 14:57 UTC
