### ISSUE TITLE
`config` should validate the service name provided in `links`

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2933] opened 2016-02-16 17:39 UTC
From: https://github.com/docker/compose/issues/1203#issuecomment-184175514

`config` should validate everything it can, and the names of services in `links` are easily available (we already do this for `depends_on`).

**Comment by johnharris85** [comment] 2016-04-17 19:38
Duplicate of #2922?

Fixed by #3340

**Closed** 2016-04-17 22:25 UTC
Labels: area/config, kind/bug
