### ISSUE TITLE
Trouble with env vars and compose

### ISSUE THREAD

**Issue by freeseacher** [docker/compose#2860] opened 2016-02-09 06:37 UTC
Hi!
i have such compose file
```
version: '2'
services: 
    web:
      image: ${FPM_IMAGE}
      cpu_quota: ${CPU_QUOTA}
```
i have the variable $CPU_QUOTA
```
# echo $CPU_QUOTA
50000
```
but on `docker-compose up web`
instead of launched container i got an error
```
docker-compose up web                
WARNING: The GITHUB_TOKEN variable is not set. Defaulting to a blank string.
WARNING: Some networks were defined but are not used by any service: front
Recreating 60ca3b4481_60ca3b4481_60ca3b4481_60ca3b4481_60ca3b4481_60ca3b4481_webcommontestprojectmaster_web_1
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 55, in main
    command.sys_dispatch()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 174, in perform_command
    handler(project, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 640, in up
    detached=detached)
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 316, in up
    detached=detached
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 370, in execute_convergence_plan
    for container in containers
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 410, in recreate_container
    quiet=True,
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 258, in create_container
    previous_container=previous_container,
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 623, in _get_container_create_options
    one_off=one_off)
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 656, in _get_container_host_config
    cpu_quota=options.get('cpu_quota'),
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 141, in create_host_config
    return utils.create_host_config(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 712, in create_host_config
    raise host_config_type_error('cpu_quota', cpu_quota, 'int')
TypeError: Invalid type for cpu_quota param: expected int but found <type 'str'>
```

pip freeze 
```
# pip freeze                          
Jinja2==2.8
MarkupSafe==0.23
Pillow==2.6.1
PyYAML==3.11
Pygments==2.0.1
SOAPpy==0.12.22
ansible==2.1.0
argparse==1.2.1
cached-property==1.3.0
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
consulate==0.7.0-rc0
cryptography==0.6.1
decorator==3.4.0
defusedxml==0.4.1
docker-compose==1.6.0
docker-py==1.7.0
dockerpty==0.4.1
docopt==0.6.2
docutils==0.12
ecdsa==0.13
enum34==1.1.2
functools32==3.2.3-2
html5lib==0.999
iotop==0.6
ipython==2.3.0
jsonschema==2.5.1
ndg-httpsclient==0.3.2
paramiko==1.16.0
pexpect==3.2
ply==3.4
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
pycrypto==2.6.1
python-apt==0.9.3.12
python-consul==0.4.7
python-debian==0.1.27
python-debianbts==1.11
reportbug==6.6.3
requests==2.7.0
roman==2.0.0
simplegeneric==0.8.1
six==1.10.0
texttable==0.8.4
urllib3==1.9.1
websocket-client==0.35.0
wheel==0.24.0
wsgiref==0.1.2
wstools==0.4.3
```
the system is 
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.3 (jessie)
Release:	8.3
Codename:	jessie
```

if i use value instead of variable container launched well

**Comment by freeseacher** [comment] 2016-02-09 10:13
got the same kind of error with cpu_shares 
```json: cannot unmarshal string into Go value of type int64```

**Comment by dnephin** [comment] 2016-02-09 15:24
Duplicate of #2730

**Closed by dnephin** 2016-02-09 15:24 UTC
