### ISSUE TITLE
Cannot preserve symbolic link when building image

### ISSUE THREAD

**Issue by antmanler** [docker/compose#633] opened 2014-11-11 16:37 UTC
My container running depends on a package which is already added to images,
in that package contains a  symbolic link point to /code, which will be used in runtime.

for example these is copy to image, in Dockerfile I used COPY gopath /gopath 

```
   /gopath
       /foo.com/
            bar/
            foobar/ ----> /code
```

`foobar ` point to /code, this folder is used in runtime

This works fine using docker's client, but when I put it to fig.yml

```yml
publisher:
    build: .
    environment:
        CONFIG_PATH: /etc/rest/publisher.json
    volumes:
        - ./code:/code
```

and fig up, I found the `foobar` is missing!

**Comment by dnephin** [comment] 2015-09-18 20:16
I'm not sure what would cause the file to just be missing entirely. Maybe the tar implementation in docker-py? A lot has changed in the 10 months since this issue has been opened, and there haven't been any other reports of this type of issue.

I'm going to close it for now. If you can still reproduce with the latest `docker-compose` and `docker` please do re-open the issue.

**Closed by dnephin** 2015-09-18 20:16 UTC
