### ISSUE TITLE
top-level extends docker-compose.yml from local file or uri

### ISSUE THREAD

**Issue by prologic** [docker/compose#1438] opened 2015-05-21 09:43 UTC
It would be nice if the ``extend(s):`` directive in the ``docker-compose.yml`` were able to extend from another ``docker-compose.yml`` from a URI. That we we can build up libraries of common things and services defined in a common place that's web accessible.

e.g:

```#!yaml
extends: http://mydomain.com/mypaas.yml

service1:
    ...

service2:
    ...
```

Here I"m talking about "extending" the local ``docker-compose.yml`` to "bring in" and include services/definitions from an external file.

**Comment by dnephin** [comment] 2015-09-29 14:50
This sounds a lot like #318 

We've implemented something similar in #2051 (will be in 1.5.x).

Going to close this and as a duplicate of #318

**Closed by dnephin** 2015-09-29 14:50 UTC
