### ISSUE TITLE
Tests with docker-compose pass only locally, fail on github actions

### ISSUE THREAD

**Issue by FlockiiX** [docker/compose#9557] opened 2022-06-13 16:06 UTC
**Description**

I have a Spring Boot application with integration and unit tests running in a Docker container. Locally my tests pass as expected, but on Github actions, a test fails due to a different, not expected HTTP status code.

**You cannot reproduce the problem because the problem is that the tests pass locally but not on Github Actions**
**Locally, the tests are passing. Try it out:**
1. Clone this [repository](https://github.com/FlockiiX/Login-Registration-Backend)
2. Run `docker-compose -f docker-compose-test.yml up --build`

**Describe the results you received:**
The tests only pass if you clone the repository and run the tests on your machine with docker-compose. On Github actions, one test fails.

**Describe the results you expected:**
That the tests work both locally and on Github actions with docker.

**Additional information you deem important (e.g. issue happens only occasionally):**
Same command on Github actions and locally in a shell.
Results: Local tests pass without problems as expected. On Github actions, one test fails.

**Note**
I have already tried it on other machines where Docker is installed. Conclusion: If you clone the repository and run the tests with docker, they all pass.

Configuration:
Workflow (test.yml):
```yml
name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from app
```
Docker-Compose (docker-compose-test.yml):
```yml
version: '3.9'
services:
  app:
    build:
      context: .
      target: test
    container_name: app
    depends_on:
      - db
      - maildev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_MAIL_HOST=maildev
    ports:
      - "8080:8080"
  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
volumes:
  db-data:
```

Some useful links:
[Repository](https://github.com/FlockiiX/Login-Registration-Backend)
[Build URL](https://github.com/FlockiiX/Login-Registration-Backend/actions/runs/2482675299)
The test that fails: [line `13630`](https://github.com/FlockiiX/Login-Registration-Backend/runs/6848389908?check_suite_focus=true#step:3:13631)

**Comment by milas** [comment] 2022-06-14 15:37
Hi, the response shown is coming from your application:
```
{"timeStamp":"06-12-2022 09:19:23","httpStatusCode":403,"httpStatus":"FORBIDDEN","reason":"FORBIDDEN","message":"You need to log in to access this page"}
```

Unfortunately, this is not an issue with Compose, so I am closing this issue.

**Closed by milas** 2022-06-14 15:37 UTC

**Comment by milas** [comment] 2022-06-16 20:07
Hi @FlockiiX, with the detail & logs you've provided, there's unfortunately nothing that points to an issue in Compose: your application's test code is running properly and is receiving a `403 FORBIDDEN` result, which also comes from your application code. I understand it behaves differently locally vs in CI, but nothing points to Compose being the cause.

One suggestion would be to try running your tests again locally with a clean slate:
```
docker-compose -f docker-compose-test.yml down --remove-orphans --rmi=all --volumes
docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit --exit-code-from app
```
For example, it's possible that your local `db-data` volume already has data in it, which causes it to behave differently than in CI.
