### ISSUE TITLE
1.17.0 broke docker-compose up

### ISSUE THREAD

**Issue by delmartechdude** [docker/compose#5349] opened 2017-11-07 20:14 UTC
The latest update to 1.17.0 suddenly broke our normal `docker-compose up`. No other changes have been made to the compose file or the system. Reverting back to 1.16.1 fixes everything.

Sample output of the 1.17.0 failure:

```
Creating elasticsearch ... 

ERROR: for elasticsearch  dictionary update sequence element #0 has length 39; 2 is required

ERROR: for elasticsearch  dictionary update sequence element #0 has length 39; 2 is required
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 68, in main
  File "compose/cli/main.py", line 121, in perform_command
  File "compose/cli/main.py", line 952, in up
  File "compose/project.py", line 455, in up
  File "compose/parallel.py", line 70, in parallel_execute
ValueError: dictionary update sequence element #0 has length 39; 2 is required
Failed to execute script docker-compose
```

**Comment by thaJeztah** [comment] 2017-11-07 21:03
Can you post an example docker-compose file that you have this issue with?

**Comment by shin-** [comment] 2017-11-07 21:39
Duplicate of #5336 

You might want to use the dictionary notation for container labels in the meantime, and stay tuned for the 1.17.1 release later this week.

**Closed by shin-** 2017-11-07 21:39 UTC

**Comment by delmartechdude** [comment] 2017-11-08 00:44
Gotcha. Thank you! @shin- when did this change? If I change our notation to dictionary, will dictionary notation alone break older versions of Docker Compose?

**Comment by shin-** [comment] 2017-11-08 01:00
@delmartechdude No, both notations were always supported, so it'll be backwards compatible. The list notation mostly exists because it's easier to translate to it from the Docker CLI flags.

**Comment by delmartechdude** [comment] 2017-11-08 01:02
Ah awesome. Thank you so much! @shin-

**Comment by weeger** [comment] 2017-12-05 09:30
Hi,

Thanks but what can we do if label have no equal sign in it ?

```   
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
```
