### ISSUE TITLE
Progress markers are not shown correctly for `docker-compose up`

### ISSUE THREAD

**Issue by jpetazzo** [docker/compose#4801] opened 2017-05-08 00:18 UTC
Note: this might be a 1.13 regression, since I don't remember seeing it with 1.12.

**What I do:**

I have a simple Compose file with two NGINX servers.

```bash
cat >docker-compose.yml <<EOF
www1:
  image: nginx
www2:
  image: nginx
EOF
```

I start them.

```bash
docker-compose up -d
```

**What I expect to see:**

The radiant beauty of the first-class, Python-powered, terminal-aware, ANSI-enlightened CLI which makes Compose a perpetual joy and delight to use and brings happiness to my darkest hours, i.e.:

```
$ docker-compose up -d
Creating tmp_www1_1 ... done
Creating tmp_www2_1 ... done
Starting tmp_www1_1 ... done
Starting tmp_www2_1 ... done
```

**What I see instead:**

Stuff gets slightly glitchy, i.e.:

```
$ docker-compose up -d
Creating tmp_www2_1 ... 
Creating tmp_www1_1 ... 
Creating tmp_www2_1
Creating tmp_www1_1 ... done
```

**Additional notes:**

While `up` is playfully humoring me, `down` won't let me, ahem, *down*, if I may intend the pun:

```
$ docker-compose down
Stopping tmp_www1_1 ... done
Stopping tmp_www2_1 ... done
Removing tmp_www1_1 ... done
Removing tmp_www2_1 ... done
```

It appears that `scale` took sides with `up`:

```
$ docker-compose scale www1=2
Starting tmp_www1_1 ... done
Creating tmp_www1_2 ... 
Creating tmp_www1_2 ... done
```

**Is this an important issue?**

I don't know! What is important? Is the breeze that blows through the bubbles of dew on morning leaves of blue mint important? In the grand scheme of things, it's not a big deal, but I know that my Compose fellows are perfectionists, and that they shan't have any of this. 

In all seriousness, though: I'm so used to Compose embodying the eternal jewel of software perfection, that when I saw this, I thought my containers had been lost at sea. So I think it's fix-worthy.

♥,

**Comment by stealthybox** [comment] 2017-05-08 04:16
10/10 💯🎨 read it twice.

I couldn't reproduce this on Docker-for-Windows with **compose 1.12**:
```bash
λ docker-compose version
docker-compose version 1.12.0, build ee0f34e1
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```
output:
```bash
λ docker-compose up -d
The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating compose_www1_1
Creating compose_www2_1

λ docker-compose down
Stopping compose_www2_1 ... done
Stopping compose_www1_1 ... done
Removing compose_www2_1 ... done
Removing compose_www1_1 ... done
```

**Comment by stealthybox** [comment] 2017-05-08 05:38
looks like a 1.13 regression, at least with my version of docker-engine:
```bash
function test-compose() {
  TAG=${1}
  docker run \
    -v //var/run/docker.sock://var/run/docker.sock \
    -v //$PWD://data \
    --workdir //data \
    --entrypoint ash \
    docker/compose:${TAG} \
    -c 'docker-compose up -d; docker-compose down'
}

> test-compose 1.12.0  # different from jerome's expectations
Creating data_www2_1
Creating data_www1_1
Stopping data_www1_1 ... done
Stopping data_www2_1 ... done
Removing data_www1_1 ... done
Removing data_www2_1 ... done

> test-compose 1.13.0-rc1  # change in behavior
Creating data_www2_1 ...
Creating data_www1_1 ...
Creating data_www2_1
Creating data_www2_1 ... done
Stopping data_www1_1 ... done
Stopping data_www2_1 ... done
Removing data_www1_1 ... done
Removing data_www2_1 ... done

> test-compose 1.13.0  # change still here
Creating data_www2_1 ...
Creating data_www1_1 ...
Creating data_www2_1
Creating data_www1_1 ... done
Stopping data_www1_1 ... done
Stopping data_www2_1 ... done
Removing data_www1_1 ... done
Removing data_www2_1 ... done
```
---
```
> docker version
Client:
 Version:      17.05.0-ce-rc1
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce-rc1
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2878a85
 Built:        Tue Apr 11 20:55:05 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by jpetazzo** [comment] 2017-05-17 03:40
Alright, I shall attempt a pagan ritual to summon the makers and destroyers of code; the ones who can track bugs creeping through the fabric of spaces and tabs; slayers of untested commits. :imp:

Yo @shin-, sup, whaddya think of that one? :)

**Comment by shin-** [comment] 2017-05-23 21:33
Thanks everyone! Acknowledging the issue. It probably won't be fixed in 1.14 (sorry!) but I'll definitely do a pass on this when I get the time.

**Closed** 2017-11-09 22:29 UTC
Labels: area/logs, kind/cleanup

**Comment by jpetazzo** [comment] 2017-11-10 18:22
Thousand thanks to @garribas for taking the time to fix this! <3

**Comment by stealthybox** [comment] 2017-11-10 21:19
seriously -- glad to have this UX back to normal

**Comment by JeroenBoersma** [comment] 2017-12-14 14:00
Hmm, if I start a new container it still tries to start the intermediate containers even if the are already running

So doesn't look resolved to me yet.

**Comment by JeroenBoersma** [comment] 2017-12-14 14:00
In 1.18 rc

**Comment by shin-** [comment] 2017-12-14 17:52
Can you provide an example of what you mean by that?

**Comment by JeroenBoersma** [comment] 2017-12-20 10:49
Of coarse...

https://asciinema.org/a/WtI9FzWMRnhhGAPl1ZIbqCu9o

When you are working with one dependency it's somewhat do-able, but when you have already multiple running dependencies it gets cluttered.
For instance running one of php commands from the command line depending on *db/redis/blackfire*
which are also running services in the background.

Hope this makes it more clear.

Again, this behavior is introduced after 1.12.

**Comment by shin-** [comment] 2017-12-20 18:45
This seems unrelated to the original issue (though maybe Compose is being more verbose with what it's doing now). You can use the `--no-deps` flag to get the behavior you want.
