### ISSUE TITLE
V1 incompatiblity: V2 does not scale to 0 containers

### ISSUE THREAD

**Issue by jamshid** [docker/compose#8654] opened 2021-09-22 04:23 UTC
## Description of the issue

The V1 `docker-compose up -d --scale foo=0` will remove all containers. V2 `docker-compose up -d --scale foo=0` scales to **one** container.

## Context information (for bug reports)

- [X ] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           newdefault
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

## Steps to reproduce the issue

1. `docker-compose up -d --scale foo=3`
```
services:
  foo:
    image: centos
    command: sleep 600
```
2. `docker-compose up -d --scale foo=0`

### Observed result

```
% docker-compose ps
docker-compose ps
NAME                COMMAND             SERVICE             STATUS              PORTS
test_foo_2          "sleep 600"         foo                 running             
```
### Expected result

Like V1:
```
% docker-compose up -d --scale foo=3
...
% docker-compose up -d --scale foo=0
Stopping and removing test_foo_1 ... 
Stopping and removing test_foo_2 ... 
Stopping and removing test_foo_3 ... 
% docker-compose ps
Name   Command   State   Ports
------------------------------
```
## Additional information

Docker for Mac 4.0.1

**Comment by mat007** [comment] 2021-09-22 04:46
Duplicate of #8571

**Closed by mat007** 2021-09-22 04:46 UTC
Labels: kind/bug

**Comment by jamshid** [comment] 2021-09-22 06:32
Thanks @mat007 so this will be fixed in rc4? Is there an easy way to install a build with the fix on Docker for Mac?

Do you happen to know if there is already a fix for `--no-deps` being ignored when using `--scale`?
```
% docker-compose up -d --no-deps --scale two=2
...
 ⠿ Container test_three_1  Started                                                                                 1.5s
```

**Comment by mat007** [comment] 2021-09-22 07:35
Here is a link to an internal build you can try: https://desktop-stage.docker.com/mac/main/amd64/68933/Docker.dmg

I don’t know about `--no-deps`, that doesn’t ring a bell. Can you open a separate issue with some reproduction steps?

**Comment by mat007** [comment] 2021-09-22 07:37
Oh wait, no the Docker Desktop build doesn’t yet have this fix.
You will have to build compose yourself, or wait for the next release (in about a week or so).

Sorry!
