### ISSUE TITLE
Cannot pipe docker-compose output (node wrap)

### ISSUE THREAD

**Issue by stephaneerard** [docker/compose#1506] opened 2015-06-03 18:23 UTC
Hi,

I'm trying to run docker-compose from a node app and pipe its outputs to the node app stdout.

I have two problems here :
Node app does not get the correct output order (looks like a buffer is flushed when I send CTRL+C)
I get a python stacktrace

```
serard@debian:~/dc$ node n.js
start
Recreating dc_test_1...
Killing dc_test_1...
Attaching to dc_test_1
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
test_1 | hello world
Gracefully stopping... (press Ctrl+C again to force)
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 552, in __bootstrap_inner
  File "/code/build/docker-compose/out00-PYZ.pyz/threading", line 505, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 41, in _enqueue_output
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 62, in _make_log_generator
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.container", line 140, in wait
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 918, in wait
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 79, in _post
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 425, in post
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 383, in request
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 486, in send
  File "/code/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 374, in send
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
dc exited

```

Here is my setup

~/dc/docker-compose.yml

```
test:
  image: busybox
  entrypoint: /bin/sh
  command: -c "while true; do echo hello world; sleep 1; done"

```

~/dc/n.js

```
#!/usr/bin/env node

console.info("start");

var DC_BIN="/usr/local/bin/docker-compose";

var cp = require("child_process");

var p = cp.spawn(DC_BIN, ["up"], {
        stdio: "pipe"
});


p.stdout.pipe(process.stdout);
p.stderr.pipe(process.stdout); // process.stderr gives same result

// catching nodejs app CTRL+C
process.on("SIGINT", function(){
        p.kill("SIGINT"); // sending it to docker-compose

        p.on("close", function(){ // same with exit event, gives same python stack trace
                console.log("dc exited");
                process.exit();
        });
});

```

command :
```
~/dc$ node n.js
```

docker-compose v: 1.2.0
docker v: 1.6.3
nodejs: 0.10, 0.12.4
debian wheezy

And I get the output given on top.

Is this a docker-compose bug or a nodejs one ? :) 

Thank you very much !

**Comment by stephaneerard** [comment] 2015-06-03 21:49
Got something working : not relying on docker-compose command output but on npm dockerode module.

```
#!/usr/bin/env node
console.info("start");
var Docker = require("dockerode");
var cp = require("child_process");
var p = cp.execSync("docker-compose up -d", {
stdio: "inherit"
});


var docker = new Docker();

var container = docker.getContainer("dc_test_1");
container.attach({stream: true, stdout: true, stderr: true}, function(err, stream){
        //stream.pipe(process.stdout);

        container.modem.demuxStream(stream, process.stdout, process.stderr);
});

process.on("SIGINT", function(){
        container.stop(function(){
                process.exit(0);
        });
});

```

Just giving up on docker-compose

**Comment by edwinlunando** [comment] 2015-06-04 05:12
I maybe get the same error. I used Rails and when I tried to go to Rails console, it raise an exception like this.
```
Loading development environment (Rails 4.1.6)
[1] pry(main)> Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.2.0', 'console_scripts', 'docker-compose')()
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/Library/Python/2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/Library/Python/2.7/site-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/Library/Python/2.7/site-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 345, in run
    dockerpty.start(project.client, container.id, interactive=not options['-T'])
  File "/Library/Python/2.7/site-packages/dockerpty/__init__.py", line 27, in start
    PseudoTerminal(client, container, interactive=interactive, stdout=stdout, stderr=stderr, stdin=stdin).start()
  File "/Library/Python/2.7/site-packages/dockerpty/pty.py", line 154, in start
    self._hijack_tty(pumps)
  File "/Library/Python/2.7/site-packages/dockerpty/pty.py", line 242, in _hijack_tty
    write_stream.do_write()
  File "/Library/Python/2.7/site-packages/dockerpty/io.py", line 164, in do_write
    raise e
OSError: [Errno 32] Broken pipe
```

**Comment by aanand** [comment] 2015-06-04 09:55
@stephaneerard Glad you found a solution. We've recently fixed a bug (#658) where output was truncated or out-of-order, so if you do want to try Compose again, 1.3.0 will contain the fix.

As for the stack trace: interesting. I haven't seen that error before, but going off the discussion on https://github.com/kennethreitz/requests/issues/1599, it sounds like it could be a race condition where the connection is closed before `container.wait()` is called.

**Comment by aanand** [comment] 2015-06-04 09:56
@edwinlunando Does it work if you run the equivalent `docker run` command? i.e.

    docker run -it <image name> rails console

**Comment by edwinlunando** [comment] 2015-06-04 09:57
@aanand yes it runs. Using the docker command I can go to the rails console. The problem comes if I use docker-compose.

**Comment by jakubpawlowicz** [comment] 2015-07-14 16:10
Same story here with `docker-compose run ...` but `docker run -it <image name>` did the trick for me too. Thanks @aanand! 

It did not happen in 1.2 so has to be a 1.3 regression. I'm using OS X 10.10.4 and docker 1.6 if it helps anyhow.

**Comment by dnephin** [comment] 2015-09-29 03:28
I believe this was a bug with a previous version of requests. We've upgraded requests a couple times since then.  I'm going to close this issue, but if you're still able to reproduce it, please do re-open or let us know.

Thanks!

**Closed by dnephin** 2015-09-29 03:28 UTC
