### ISSUE TITLE
`pip freeze` call in compose/cli/__init__.py adds 2s to execution time

### ISSUE THREAD

**Issue by mlowicki** [docker/compose#5381] opened 2017-11-16 18:34 UTC
I was checking why running every command of `docker-compose` takes 2-3s and it turned out that https://github.com/docker/compose/blob/d48002a09de988ca2974912c09014bf86d9f84aa/compose/cli/__init__.py#L19 is the reason. Maybe we can add some flag to disable such check?

**Comment by mlowicki** [comment] 2017-11-16 18:47
It seems that https://github.com/docker/compose/pull/5320 tries to already solve this issue.

**Comment by shin-** [comment] 2017-11-16 19:54
Duplicate of #5038

**Closed by shin-** 2017-11-16 19:54 UTC
