### ISSUE TITLE
Improve variable interpolation, required flag and default value.

### ISSUE THREAD

**Issue by aramalipoor** [docker/compose#2441] opened 2015-11-21 15:24 UTC
As first proposed in #1377 I think it would be very useful to have a way to set a variable as required, and  also set some default value.

```yaml
web:
   image: org/app:${VERSION?} # Required
```
Or
```yaml
web:
   image: org/app:${VERSION:latest} # Default Value
```

**Comment by majidgolshadi** [comment] 2015-11-22 07:43
:+1:

**Comment by dustinblackman** [comment] 2015-11-27 15:18
:+1:

**Comment by armab** [comment] 2015-11-28 17:10
:+1:

**Comment by valeriangalliat** [comment] 2015-11-30 16:13
:+1:

**Comment by mseashor** [comment] 2015-12-02 17:48
:+1:

**Comment by shane-axiom** [comment] 2015-12-18 03:54
+1, defaults for environment variables would be great. Simple syntax this would be great:

    mycontainer:
      image: ubuntu:latest
      ports:
        - ${THEPORT:8080}:8080

**Comment by bennycornelissen** [comment] 2016-01-05 13:42
:+1:

**Comment by plouc** [comment] 2016-01-07 08:58
I'm working on a project where people have heterogeneous env, I'm working on OSX and some are using Ubuntu, when using docker-machine with virtualbox provider, I have to put the full path to make Volume works:

```yaml
myservice:
  volumes:
    - ${HOST_VOLUME_PATH}/src:/src
```

The problem is now people who don't use virtualbox have to define the value, it should be great if we could  have a default value:

```yaml
myservice:
  volumes:
    - ${HOST_VOLUME_PATH:.}/src:/src
```

In other words :+1:

**Comment by obazoud** [comment] 2016-01-07 09:10
:+1:

**Comment by jlrigau** [comment] 2016-01-11 11:59
:+1:

**Comment by scasagrande-d2l** [comment] 2016-01-13 17:09
+1

**Comment by leogamas** [comment] 2016-01-13 19:50
:+1:

**Comment by roll** [comment] 2016-01-19 06:35
:+1:

**Comment by asilluron** [comment] 2016-01-27 19:41
:+1:

**Comment by digitalLumberjack** [comment] 2016-01-30 08:49
:+1:

**Comment by hadim** [comment] 2016-02-04 19:14
This feature is a must have. Any devs from the docker-compsose team working on it ? If not I could propose a PR.

**Comment by dnephin** [comment] 2016-02-04 19:20
While having defaults would be really nice, we haven't decided on any implementations yet.

I (personally) think it's more likely we go with something like #2636 for default values. It supports more use-cases, and doesn't require us to invent new syntax for defaults.

**Comment by marcellodesales** [comment] 2016-02-17 08:06
I'd like to see the same implementation as https://docs.docker.com/engine/reference/builder/#environment-replacement Right now, I'd like the ability to switch from 2 different implementations for the log driver.

Given the following Base implementation:

```yml
intuitive-syslog:
  log_driver: "syslog"
  labels:
    - net.c.d.datacenter: ${DATA_CENTER}
    - net.c.d.env: ${NPMO_ENV}
    - net.c.d.hostname: ${HOSTNAME}
    - net.c.d.role: ${NPMO_ROLE}

intuitive-json:
  log_driver: "json"
  labels:
    - net.c.d.datacenter: ${DATA_CENTER}
    - net.c.d.env: ${NPMO_ENV}
    - net.c.d.hostname: ${HOSTNAME}
    - net.c.d.role: ${NPMO_ROLE}
```

I'd like to run the syslog driver by default and select the regular logs while debugging.

```yml
mycouch:
  extends:
    file: base.yml
    service: intuitive-${LOG_DRIVER:-syslog}
  build: roles/couchdb
  restart: always
  ports:
    - "5984"
  log_opt:
    syslog-tag: "mycouch"

myredis:
  extends:
    file: base
    service: intuitive-${LOG_DRIVER:-syslog}
  image: redis
  restart: always
  expose:
    - "6379"
  log_opt:
    syslog-tag: "myredis"
```

I'm getting the following error:

```
docker-compose -f services/new1.yml ps
ERROR: Invalid interpolation format for "extends" option in service "myredis": "intuitive-${LOG_DRIVER:-syslog}"
```

**Comment by gittycat** [comment] 2016-02-22 23:48
:+1: for both required and default values.
I actually believe variables should be `required` by default but it might be too late for that now.

**Comment by matleh** [comment] 2016-03-03 11:05
+1 - without this, the usefulness of variable expansion (which is a great feature) is severely limited

**Comment by marcellodesales** [comment] 2016-03-10 20:27
Just hit this problem again :(

```
$ docker-compose  up    
ERROR: Invalid interpolation format for "env_file" option in service "rabbitmq": "env/${DATA_CENTER:-aws}/${ENV:-dev}.env"
```

I agree with @matleh, without this in docker-compose, this is definitely useless...

**Comment by marcellodesales** [comment] 2016-03-10 20:30
Please please support the same features ALREADY SUPPORTED in Dockerfile https://docs.docker.com/engine/reference/builder/#environment-replacement

**Comment by marcellodesales** [comment] 2016-03-10 20:31
@aramalipoor Can you update the description of this issue to include the link to the currently supported variable interpolation as of Dockerfile?

thanks!

**Comment by marcellodesales** [comment] 2016-03-10 20:42
The section https://docs.docker.com/compose/compose-file/#variable-substitution describes that it is not supported... If this gets implemented, this documentation should be updated.

**Comment by mazerty** [comment] 2016-04-11 11:24
:+1:

**Comment by eduardoleal** [comment] 2016-07-13 20:57
👍

**Comment by xFlatlinex** [comment] 2016-07-20 16:58
👍 to have this implemented the same way as in the Dockerfile implementation

**Comment by bufface** [comment] 2016-07-25 14:40
:+1:

**Comment by xeor** [comment] 2016-08-25 13:18
Anyone got any news about this, it's been a whole 27 days since the last :+1: ?
Much much needed!

**Comment by jpbochi** [comment] 2016-08-25 13:21
is there a PR already open with this change? Perhaps we need a volunteer to implement it.

**Comment by dattran-vn01** [comment] 2016-08-25 15:02
let me implement this and send one PR

**Comment by phutchins** [comment] 2016-09-22 13:46
Definitely need this...

**Comment by bongole** [comment] 2016-09-28 06:34
+1

**Comment by daleobrien** [comment] 2016-09-28 06:39
👍 +1

**Comment by kouki-o** [comment] 2016-10-05 06:44
+1

**Comment by shin-** [comment] 2016-10-05 21:23
Closing via #3108

**Closed by shin-** 2016-10-05 21:23 UTC
Labels: area/config, kind/enhancement

**Comment by shane-axiom** [comment] 2016-10-05 22:45
:tada:

**Comment by Kxrr** [comment] 2017-12-08 06:36
+1
