### ISSUE TITLE
Use hyphens, not underscores, for hostnames

### ISSUE THREAD

**Issue by joaquincasares** [docker/compose#3912] opened 2016-09-06 17:40 UTC
I recently filed this ticket:

https://issues.apache.org/jira/browse/KAFKA-4121

which is a duplicate of this ticket:

https://issues.apache.org/jira/browse/KAFKA-3017.

The important part to note is:

> The Internet standards (Requests for Comments) for protocols mandate that component hostname labels may contain only the ASCII letters 'a' through 'z' (in a case-insensitive manner), the digits '0' through '9', and the hyphen ('-')
> https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names

Could we make the Docker hostnames match the Internet Standards naming scheme?

Thanks!

**Comment by thaJeztah** [comment] 2017-01-19 23:19
I think this is a duplicate of https://github.com/docker/compose/issues/229

**Closed** 2017-07-21 00:35 UTC
Labels: duplicate
