### ISSUE TITLE
scale to setup network automatically

### ISSUE THREAD

**Issue by jianbin-netskope** [docker/compose#2890] opened 2016-02-11 22:43 UTC
Without running `up` first, the network does not exist.  Then the `scale` fails.   

Any reason that the network should not created within `scale` command?

```
docker-compose -f kafka-cluster.yml scale zookeeper=2                                                                                                                        
Creating and starting 1 ... error
Creating and starting 2 ... error
ERROR: for 1  network docker_default not found
ERROR: for 2  network docker_default not found
```

**Comment by dnephin** [comment] 2016-02-11 23:09
Duplicate of #2602

I'd rather avoid having `scale` duplicate a lot of behviour from `up`, be we can discuss in #2602

**Closed by dnephin** 2016-02-11 23:09 UTC
