### ISSUE TITLE
"docker compose build" fails to build image whereas "docker-compose build" works successfully

### ISSUE THREAD

**Issue by jacek-jablonski** [docker/compose#8532] opened 2021-06-23 10:52 UTC
Hi,
I am unable to build docker images using `docker compose build` when using private artifact registry (GCP):
```
╰─❯ docker compose build
[+] Building 0.4s (8/10)
 => [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-api:latest internal] load build d  0.0s
 => => transferring dockerfile: 32B                                                                             0.0s
 => [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-gui:latest internal] load build d  0.0s
 => => transferring dockerfile: 32B                                                                             0.0s
 => [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-api:latest internal] load .docker  0.0s
 => => transferring context: 34B                                                                                0.0s
 => [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-gui:latest internal] load .docker  0.0s
 => => transferring context: 2B                                                                                 0.0s
 => ERROR [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-api:latest internal] load m  0.3s
 => [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-gui:latest internal] load metadat  0.0s
 => [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-gui:latest base 1/2] FROM europe-  0.0s
 => CANCELED [europe-west4-docker.pkg.dev/xxx/docker-dev-tools/pg-dashboard-gui:latest internal] loa  0.2s
 => => transferring context: 10.07MB
```

Everything works when using old `docker-compose build`.

Here is my `~/.docker/config.json`:
```json
{
  "experimental" : "disabled",
  "auths" : {
    "gcr.io" : {

    }
  },
  "credHelpers" : {
    "gcr.io" : "gcloud",
    "us.gcr.io" : "gcloud",
    "staging-k8s.gcr.io" : "gcloud",
    "europe-west4-docker.pkg.dev" : "gcloud",
    "asia.gcr.io" : "gcloud",
    "marketplace.gcr.io" : "gcloud",
    "eu.gcr.io" : "gcloud"
  },
  "credsStore" : "desktop"
}
```

As you can see gcloud helper should be used to authenticate to artifact registry.

Do you have any idea what might be wrong?

**Comment by ulyssessouza** [comment] 2021-09-10 01:06
Could not reproduce. I pushed an image to `gcr.io` and it just worked.  Here is my docker config file after `gcloud auth configure-docker`:
```json
{
  "credsStore": "desktop",
  "stackOrchestrator": "swarm",
  "experimental": "enabled",
  "auths": {
    "https://index.docker.io/v1/": {}
  },
  "credHelpers": {
    "gcr.io": "gcloud",
    "us.gcr.io": "gcloud",
    "eu.gcr.io": "gcloud",
    "asia.gcr.io": "gcloud",
    "staging-k8s.gcr.io": "gcloud",
    "marketplace.gcr.io": "gcloud"
  }
}
```

**Comment by mat007** [comment] 2021-09-14 07:03
@jacek-jablonski what version of Docker Desktop are you on? Is it on Mac or Windows?

**Comment by jacek-jablonski** [comment] 2021-09-14 09:40
Hi,
it was Docker Desktop for Mac. But it was several versions ago, now it seems to be working.

**Comment by mat007** [comment] 2021-09-14 09:47
All right, thanks. I’ll just close this ticket now then.

**Closed by mat007** 2021-09-14 09:47 UTC
Labels: Docker Compose V2
