### ISSUE TITLE
Brew installation broken as of rebranding

### ISSUE THREAD

**Issue by LinusU** [docker/compose#1024] opened 2015-02-25 16:42 UTC
Don't know if this is the correct place to post this, but just a heads up that someone should fix the brew formula. The formula should also be renamed to `docker-compose` as soon as the first stable version is out.

Adding the following lines to `fig.rb` and installing with `brew install fig --devel` results in a broken package.

```ruby
  devel do
    url "https://github.com/docker/compose/archive/1.1.0-rc2.tar.gz"
    version "1.1.0-rc2"
  end
```

When running `docker-compose` it complains that it can't find the python packages. But it seems like they are in the correct place. Unfortunately I don't know enough about how python loads packages to debug further :(

**Comment by aanand** [comment] 2015-02-25 17:41
Is it complaining about the version of `requests`? If so, it's probably caused by #918 (and fixed by #1026).

**Comment by LinusU** [comment] 2015-02-26 10:27
Hmm, that seems like it should be a problem but I believe that it couldn't find `docker-py`. I assumed that it couldn't find any of the installed python packages.

No idea why it works with `fig 1.0.1` thought.

**Comment by aanand** [comment] 2015-02-26 15:40
Now that 1.1.0 stable is out, you could try updating the formula to that. (I don't know much about Homebrew - we don't maintain the formula.)

**Comment by kriswill** [comment] 2015-02-26 18:31
The owners of homebrew want me to make some adjustments.  I'll do it and see what they think.

**Comment by kriswill** [comment] 2015-02-26 21:06
I updated the PR to reflect official website for docs and manual installation on OS/X. see https://github.com/kriswill/homebrew/commit/8333cd474da6f1856ad97a1a7d815702b140c05f

**Comment by bfirsh** [comment] 2015-03-09 11:52
@kriswill Is this fixed now?

**Comment by kriswill** [comment] 2015-03-09 19:29
@bfirsh yes, they merged this commit thru their Jenkins CI instead of through the github PR.  They use a script on Jenkins to add a "bottle" clause to the formula file, which tars up the content of the formula to make it faster/less brittle to download and install.

**Closed** 2015-06-12 07:20 UTC
