### ISSUE TITLE
Log driver syslog breaks docker-compose run

### ISSUE THREAD

**Issue by mikehaertl** [docker/compose#2524] opened 2015-12-09 14:04 UTC
I've configured a `syslog` log driver for a container and now get an error whenever I try to run a command in that container:

```
$ cat docker-compose.yml 
foo:
    image: php:5.6.10-apache
    log_driver: "syslog"
$ docker-compose up -d
Starting test_foo_1
$ docker-compose run --rm foo ls
Error attaching: configured logging reader does not support reading
                                                                   Error attaching: configured logging reader does not support reading
```

**Comment by aanand** [comment] 2015-12-09 16:39
Might be a duplicate of https://github.com/docker/compose/issues/2524

**Comment by aanand** [comment] 2015-12-09 16:39
Might be a duplicate of https://github.com/docker/compose/issues/2448

**Comment by mikehaertl** [comment] 2015-12-09 16:55
Hmm, yeah, sounds like the same problem. But maybe @dnephin should confirm, that his fix will also affect the `syslog` driver. The other issue only mentions `gelf`.

**Comment by dnephin** [comment] 2015-12-09 18:47
Yes, I believe it is a duplicate. Both of these log drivers are handled the same way by engine I believe.

**Closed by dnephin** 2015-12-09 18:47 UTC
