### ISSUE TITLE
[Request] Make docker-compose support default value for ENV variable substitution

### ISSUE THREAD

**Issue by nschoe** [docker/compose#3505] opened 2016-05-24 13:41 UTC
It's possible to use ENV varaible in docker-compose files with `${ENV_VAR}` but it defaults to empty when `ENV_VAR` is not set.

I think it would be good to support default value, as in shell syntax, like so: `${ENV_VAR:-defaultValue}`.

**Comment by shin-** [comment] 2016-05-24 17:02
You could use a `.env` file for that.

**Comment by nschoe** [comment] 2016-05-25 08:03
@shin- ah thanks, I'll try that. But usually, my wrapper call `docker-compose` by exporting the ENV variable on the same command lie, smth like `MY_ENV_VAR=myValue docker-compose -f /path/to/docker-compose.yml -p projectName up -d`.

In the case where `MY_ENV_VAR` is defined in a .env file so that it has a default value, **and** I still define in the command-line like above, what's the behavior? Is it reliable? Which has precedence?

(i'm going to try it anyway)

**Comment by shin-** [comment] 2016-05-25 22:16
Yes, by design, environment variables from the shell will always override values in the `.env` file.

**Comment by shin-** [comment] 2016-05-25 22:17
The [docs](https://github.com/docker/compose/blob/master/docs/env-file.md) confirm that as well.

**Comment by nschoe** [comment] 2016-05-26 07:29
Okay great, thanks. Sorry I could have found this myself.

Should we close this issue or is it still a good idea to think about default for docker-compose.yml files?

**Comment by shin-** [comment] 2016-05-26 21:46
We actually already have #2441 to track that same request. I think the .env file covers 95% of the use cases where we would want that syntax, so it's lower priority.

I'll close this as a result.

**Closed by shin-** 2016-05-26 21:46 UTC
