### ISSUE TITLE
[BUG] docker-compose-plugin 2.24.1+ does not read the .env file in docker dir

### ISSUE THREAD

**Issue by ZubchenkoAV** [docker/compose#11427] opened 2024-01-30 15:06 UTC
### Description

Sorry if i'll miss something, this is my first issue.

I have following project structure (simplified for this example):
```
~/test_project$ tree -a .
.
├── docker
│   └── dev
│       ├── compose.yaml
│       └── .env
└── .env
```
With following content:
```
~/test_project$ cat .env
COMPOSE_PATH_SEPARATOR=:
COMPOSE_FILE=docker/dev/compose.yaml

~/test_project$ cat docker/dev/.env
COMPOSE_PATH_SEPARATOR=:
COMPOSE_FILE=docker/dev/compose.yaml
MYSQL_IMAGE="percona:8.0"

~/test_project$ cat docker/dev/compose.yaml 
version: '3.8'

services:

  mysql:
    image: $MYSQL_IMAGE
```

This structure was working fine prior upgrading to docker-compose-plugin 2.24.1-1~ubuntu.22.04~jammy but now i'm getting following error:
```
~/test_project$ docker compose config
WARN[0000] The "MYSQL_IMAGE" variable is not set. Defaulting to a blank string. 
service "mysql" has neither an image nor a build context specified: invalid compose project
```

### Steps To Reproduce

1. Prepare test project from description
2. `sudo apt install docker-compose-plugin=2.24.2-1~ubuntu.22.04~jammy`
3. run from the project root `docker compose config`
4. Results in `WARN[0000] The "MYSQL_IMAGE" variable is not set`
5. downgrade compose plugin using `sudo apt install docker-compose-plugin=2.21.0-1~ubuntu.22.04~jammy`
6. run again `docker compose config`
7. now all is fine:
```
~/test_project$ docker compose config
name: dev
services:
  mysql:
    image: percona:8.0
    networks:
      default: null
networks:
  default:
    name: dev_default
```

### Compose Version

```Text
Docker Compose version v2.24.2
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 87
  Running: 6
  Paused: 0
  Stopped: 81
 Images: 126
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-15-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 35.17GiB
 Name: BA100298
 ID: 4cc8e674-89ff-46a9-ad36-91e618a81b72
 Docker Root Dir: /home/oleksandr.zubchenko/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by glours** [comment] 2024-01-30 15:07
duplicate of #11412

**Closed by glours** 2024-01-30 15:07 UTC
Labels: kind/bug, status/0-triage
