### ISSUE TITLE
allow ignoring unsupported config options

### ISSUE THREAD

**Issue by brancz** [docker/compose#1655] opened 2015-07-06 11:54 UTC
There are tools and services popping up that orient themselves on the `docker-compose.yml` specification. However for some use-cases it is necessary to extend this reference, but when trying to use the same `docker-compose.yml` in `dev`, `test` and `prod` it causes docker-compose to exit and say `unsupported config options ...`. I propose a flag such as `--ignore-unsupported` which only skips an option and prints that compose skipped that option since it is unknown. Any thoughts?

**Comment by raohuaming** [comment] 2015-07-12 12:40
I like the idea +1

**Comment by aanand** [comment] 2015-07-14 10:14
A flag would be one way to do it; another would be a way to allow unsupported options as long as they're explicitly demarcated as such. For example, CSS has [vendor prefixes](http://www.sitepoint.com/web-foundations/vendor-specific-properties/); perhaps we could do something with a similar structure.

Or we could allow reverse-DNS notation, e.g. `com.example.new-option`.

**Comment by dnephin** [comment] 2015-09-10 19:02
I like the idea of vendor prefixes. We should allow field starting with `x-` to be ignored by our validation.

**Comment by fentas** [comment] 2015-09-21 09:07
Any progress on this? +1

**Comment by marcosnils** [comment] 2015-09-28 21:14
:+1:

**Comment by wallyqs** [comment] 2015-10-16 23:01
+1

**Comment by ProTip** [comment] 2015-11-14 00:48
This would help me out a ton too. Any direction on this?

**Comment by gionn** [comment] 2016-01-18 15:28
@dnephin what are the chances that a submitted PR with vendor prefix support will get merged for the next release?

**Comment by dnephin** [comment] 2017-08-17 16:49
Closing as duplicate of #2942

**Closed by dnephin** 2017-08-17 16:49 UTC
Labels: area/config, kind/feature

**Comment by vzuevsky** [comment] 2022-04-28 19:51
Sorry can docker(conpose) ignore unsupported options or not? If former, what option does it? If latter, why not?
