### ISSUE TITLE
Make error output more informative

### ISSUE THREAD

**Issue by marcospgp** [docker/compose#6241] opened 2018-09-30 21:13 UTC
## Description of the issue

When Docker for Windows has not been initialized, and `docker-compose up` is run, the error message is not descriptive.

## Steps to reproduce the issue

1. Do not start docker
2. Run `docker-compose up` in your project root
3. Observe

### Observed result

ERROR: for <service name here> Cannot create container for service postgres: b'open \\\\.\\pipe\\docker_d4w_systray: The system cannot find the file specified.'

### Expected result

ERROR: for postgres  Cannot create container for service postgres: b'open \\\\.\\pipe\\docker_d4w_systray: The system cannot find the file specified.'
Please make sure Docker has been initialized in this system.

## Additional information

Windows 10 Professional, Docker for Windows

Edit: Okay actually I'm not even sure the issue was related to Docker not having started. I tried a bunch of things, kept getting different errors (even "Are you trying to mount a directory onto a file (or vice-versa)?"), restarted Docker a few times.

In the end, I ran `docker-compose down -v` and on the next start it seemed fine!

**Comment by shin-** [comment] 2018-10-02 08:14
Duplicate of #6175

**Closed by shin-** 2018-10-02 08:14 UTC
