### ISSUE TITLE
`docker-compose create $service` doesn't create networks

### ISSUE THREAD

**Issue by ashb** [docker/compose#3394] opened 2016-04-29 13:31 UTC
Best iluustrated with a simple example:

My compose file `docker-compose-test.yml`:

```yaml
---
version: '2'
networks:
  public:
services:
  test:
    image: alpine:3.3
    command: ["/bin/sleep", "60"]
    networks:
      public: {}
```

And then try to run `create`

```
% docker-compose -p test -f docker-compose-test.yml create test
Creating test_test_1
ERROR: network test_public not found
```

but a `up` works fine:

```
% docker-compose -p test -f docker-compose-test.yml up
Creating network "test_public" with the default driver
Creating test_test_1
Attaching to test_test_1
```

### Version

```
docker-compose --version
docker-compose version 1.7.0, build unknown
```

**Comment by Anonymooseable** [comment] 2016-04-29 14:33
You don't even need to specify a network, this issue occurs with the default network on a compose file with the v2 format.

**Comment by dnephin** [comment] 2016-04-29 14:43
Duplicate of #2908

**Closed by dnephin** 2016-04-29 14:43 UTC

**Comment by dnephin** [comment] 2016-04-29 14:44
You probably shouldn't use `create`. I think it was a mistake to add it.

I created #3395
