### ISSUE TITLE
`docker-compose build` shouldn't complain about missing env file

### ISSUE THREAD

**Issue by garyp** [docker/compose#3346] opened 2016-04-18 21:06 UTC
Our docker-compose.yml file references an `env_file` that gets auto-generated by a script that we run before `docker-compose up`. Which means that the env file isn't available when we run `docker-compose build`. Since the build process doesn't use environment variables, this shouldn't be a problem. But `docker-compose build` exits with an error of "Couldn't find env file: /foo/bar/my.env".

Instead, `docker-compose build` should ignore the non-existent env file. It should only print the error if the env file isn't found by the time `docker-compose up` is run.

**Comment by dnephin** [comment] 2016-04-18 21:17
Duplicate of #1973

**Closed by dnephin** 2016-04-18 21:17 UTC
Labels: duplicate

**Comment by alanjds** [comment] 2017-07-05 18:02
Seems to me that this is not a duplicate. Separating the parse in 2 steps will not allow some env_file to be non-existent. On the phase that it is read, non-existing files will raise an error.

The asked here is to be ok and simple ignored when a non-existing file got tried. I would like a warning, anyway...

**Comment by alanjds** [comment] 2017-07-05 18:05
See: https://github.com/docker/compose/pull/3955/files
