### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by sandywater** [docker/compose#642] opened 2014-11-12 18:23 UTC
When I try and fig up or fig pull I get

```
SSL error: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

If I try and do a fig up --allow-insecure-ssl, I get:
```
Couldn't connect to Docker daemon - you might need to run `boot2docker up`.
```

Running `docker pull redis` works fine.

NOTE: I am in a corp proxied environment, so I think fig is not using the proxy/ssl ca cert that I put into the boot2docker vm.

Also I am running OSX 10.9

Thank you.

**Comment by imton** [comment] 2015-01-26 01:16
To be able to connect to Azure I have to patch the docker_client.py

````
            verify=False,
            assert_hostname=False,
            client_cert=client_cert,
            ca_cert=ca_cert, <<=== delete this
````

any other alternative?

**Comment by bitliner** [comment] 2015-02-04 13:37
Same problem here. It looks not being  related to only fig, but to docker itself.
Any process that I run inside a container have issues to validate the SSL certificate (e.g. pip while building image on AWS, wordpress for connecting to the plugin repository still in a container on AWS, etc.).

Installing the packet `ca-certificates` is not enough, the error still appears.

**Comment by NickTomlin** [comment] 2015-02-21 17:28
This seems to be an issue with homebrew's version of openssl.  I was able to fix it by removing fig from my system python and installing with brew. Instructions [here](https://github.com/docker/fig/issues/890#issuecomment-73221605).

**Comment by aanand** [comment] 2015-05-28 08:17
Duplicate of #890

**Closed by aanand** 2015-05-28 08:17 UTC
