### ISSUE TITLE
.env file multiline strings

### ISSUE THREAD

**Issue by sandrodz** [docker/compose#3607] opened 2016-06-16 08:17 UTC
In docker-compose.yml file I've:

```
    LETSENCRYPT_HOST: |
          abc.domain.com,
          abe.domain.com,
          aba.domain.com

```
I'd like to move this to `.env` file, is this possible?

docs say 

> Compose expects each line in an env file to be in VAR=VAL format

**Comment by shin-** [comment] 2016-06-21 01:14
Hi,

This is a duplicate of #3527 :)

**Closed by shin-** 2016-06-21 01:14 UTC

**Comment by keithy** [comment] 2019-01-06 14:08
No it is not a duplicate of 3527.

**Comment by jacobbogers** [comment] 2019-03-18 15:23
this solved already?

**Comment by talsen-team** [comment] 2019-06-26 11:08
Hi,
This is still unchanged.
Does anybody know a suitable workaround?, it would be nice to avoid storing e.g. GitLab configuration directly in docker-compose file, so that the compose configuration could be managed by version control.
Thanks in advance!

**Comment by keithy** [comment] 2019-06-26 14:03
I have a script: ```docker-compose-use <a.yml> <b.yml>```
This script just processes readable a.yml and b.yml into a single .env file, by removing comments and supporting newlines. It is that simple.

It works really well, and is the basis of my ```angelbox``` docker toolkit.

The idea of ```angelbox``` is that any docker image can be packaged as a single docker-compose service in which all of the relevant parameters are broken out into environment variables.

Then you provide your configuration as two files, one defining the services that you want composed, the other providing parameters specific to that deployment scenario (i.e. per server). Thus far this works for every scenario that I can envisage.

https://github.com/keithy/sprankle-pod

**Comment by keithy** [comment] 2019-06-26 14:21
Hi my solution to this works very well https://github.com/keithy/sprankle-pod

**Comment by efinal** [comment] 2020-08-13 05:58
according to the document: https://docs.docker.com/compose/compose-file/#environment
you can define envs in compose file like this

environment:
  RACK_ENV: development
  SHOW: 'true'
  SESSION_SECRET: |
        new line 1
        new line 2

**Comment by sshishov** [comment] 2022-02-23 12:28
We want to have multiline variables inside `dotenv` file
