### ISSUE TITLE
Allow underscores "_" in project name?

### ISSUE THREAD

**Issue by nanawel** [docker/compose#4387] opened 2017-01-25 12:43 UTC
Hi,
Would it be a problem in some cases to also allow underscore character in the project name? That would be very convenient.
(see `get_project_name()` at https://github.com/docker/compose/blob/master/compose/cli/command.py#L118)

Thanks in advance

**Comment by shin-** [comment] 2017-01-25 22:54
Duplicate of #4002

**Closed by shin-** 2017-01-25 22:54 UTC
