### ISSUE TITLE
version 1.27.0: volumes contains unsupported option: 'gid'

### ISSUE THREAD

**Issue by micheelengronne** [docker/compose#7733] opened 2020-09-08 08:56 UTC
# Description of the issue

The version 1.27.0 gives the error `volumes contains unsupported option: 'gid'`.

I have a tmpfs volume mounted as such:

```yaml
      - type: tmpfs
        target: /run/user/1005/
        tmpfs:
          mode: 0700
          uid: 1005
          gid: 1005
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
1.27.0
```

**Output of `docker version`**
```
19.03.12
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
docker-compose up
```

## Steps to reproduce the issue

1. Create a docker-compose.yml file with a volume like this:
```yaml
      - type: tmpfs
        target: /run/user/1005/
        tmpfs:
          mode: 0700
          uid: 1005
          gid: 1005
```
2. run `docker-compose up`

### Observed result
`volumes contains unsupported option: 'gid'`

### Expected result
docker-compose up should run without errors

### Stacktrace / full error message

```
The Compose file './docker-compose.yml' is invalid because:
`volumes contains unsupported option: 'gid'`
```

## Additional information

On ubuntu focal (20.04), docker-compose installed through pip.

**Comment by ulyssessouza** [comment] 2020-09-08 09:23
Thanks for the report @micheelengronne ! 

This looks like a regression on our new schema.
We are having a look at this and it should be corrected in `1.27.1`.

**Comment by elovin** [comment] 2020-09-08 10:21
I get the same error with `mode`, it worked perfectly with the lat few previous versions.

Error message:
```
ERROR: The Compose file './development.yml' is invalid because:
services.php-fpm.volumes contains unsupported option: 'mode'
```

**Comment by aiordache** [comment] 2020-09-08 19:31
Hi @micheelengronne, @elovin . Thanks for reporting this. 

You get the error due to having a more strict schema validation that checks that the properties you pass are in the schema. 
I have checked the documentation and so far, the only valid property for `tmpfs` I have found is `size`. I have not found anything related to `mode`, `uid`, or `gid` for `tmpfs` in v2 or v3 compose formats. Am I missing something here?

I may be wrong but I looked into the code and I don't see any of those properties applied. Could you check please if those properties have some effects in your setups? My understanding is that they are simply ignored by old docker-compose versions, you could add a random field there and the old docker-compose versions will not raise any issue.

This confusion of what properties are applied should be better addressed with the merged schema as we'll get the error outs for unknown/unsupported properties. As it seems to me it is the case here.

I will continue to investigate, we could add properties to the compose schema and try to set them in the code such that they are applied. But from the docs here: https://docs.docker.com/storage/tmpfs/  seems the docker daemon API supports only `size` and `mode` options for `tmpfs`.

So we could add `mode` to the properties in the schema, but I don't see what we could do about `uid` and `gid`.

**Comment by micheelengronne** [comment] 2020-09-09 08:07
@aiordache You are perfectly right. My builds work without it. @elovin do I close this issue ?

**Comment by elovin** [comment] 2020-09-09 08:57
@aiordache I tested this and those properties are indeed ignored e.g. I can write any none existing property name and it will not complain and thus setting the mode property apparently does not do anything.

@micheelengronne 
I did not start this issue but I think you can close it

**Closed** 2020-09-09 09:13 UTC
Labels: kind/bug
