### ISSUE TITLE
failed to get console mode for stdout: The handle is invalid.

### ISSUE THREAD

**Issue by AnthonyMastrean** [docker/compose#8186] opened 2021-03-09 15:07 UTC
## Description of the issue

The `docker-compose build` command prints this `failed` error every time.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  web:
    build:
      context: C:\Users\anthony\example
      dockerfile: Dockerfile
version: '2.4'
```

and the Dockerfile can be anything, this works

```
FROM nginx:stable
```

## Steps to reproduce the issue

1. Create any Dockerfile on Windows
2. Create any Docker Compose manifest with a build section pointing to the same Dockerfile
3. Run `docker-compose build`

### Observed result

The Docker Compose build command always prints the `failed` line. Nothing else _seems_ to be wrong, but I'm not sure.

```
WARNING: Native build is an experimental feature and could change at any time
Building web
failed to get console mode for stdout: The handle is invalid.
[+] Building 0.1s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 31B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/nginx:stable            0.0s
 => CACHED [1/1] FROM docker.io/library/nginx:stable                       0.0s
 => exporting to image                                                     0.0s
 => => exporting layers                                                    0.0s
 => => writing image sha256:b3914da1a942520904ff755103e5eb24c87fee1a5af36  0.0s
 => => naming to docker.io/library/downloads_web                           0.0s
```

### Expected result

The plain Docker build command works as expected.

```
[+] Building 0.1s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                            0.0s 
 => => transferring dockerfile: 31B                                                                                                                                                                             0.0s 
 => [internal] load .dockerignore                                                                                                                                                                               0.0s 
 => => transferring context: 2B                                                                                                                                                                                 0.0s 
 => [internal] load metadata for docker.io/library/nginx:stable                                                                                                                                                 0.0s 
 => CACHED [1/1] FROM docker.io/library/nginx:stable                                                                                                                                                            0.0s 
 => exporting to image                                                                                                                                                                                          0.0s 
 => => exporting layers                                                                                                                                                                                         0.0s 
 => => writing image sha256:b3914da1a942520904ff755103e5eb24c87fee1a5af365037b7fa48e38c6a16e                                                                                                                    0.0s 
 => => naming to docker.io/library/web                                          
```

### Stacktrace / full error message

```
failed to get console mode for stdout: The handle is invalid.
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

![image](https://user-images.githubusercontent.com/217842/110490340-34a06300-80be-11eb-8bbd-b498e9448662.png)

**Comment by AnthonyMastrean** [comment] 2021-03-09 15:13
I noticed this warning message only appears when running Docker Compose commands. It looks like both Docker and Docker Compose merged changes to use native build / buildx by default now. Why is this warning still here?

```
WARNING: Native build is an experimental feature and could change at any time
```

And why does the handle error disappear when I turn off native build?

```
PS> [System.Environment]::SetEnvironmentVariable('COMPOSE_DOCKER_CLI_BUILD', '0', 'Process')

PS> docker-compose build
Building web
Step 1/1 : FROM nginx:stable
 ---> 05f64a802c26

Successfully built 05f64a802c26
Successfully tagged downloads_web:latest
```

**Comment by ternavsky** [comment] 2021-03-10 06:30
Same for me. After yesterday update console output for `docker-compose build` changed. And it throws "failed to get console mode for stdout: The handle is invalid."

**Comment by JorisDebonnet** [comment] 2021-03-10 12:52
I had the same issues since upgrading to 3.2.1 yesterday (on Windows 10). Aside of that failed message, my builds also seemed to hang on one specific line, so I also reverted to version 3.1.0.

Afterwards I figured that the line probably just takes a long time and it would actually have completed ... but 3.1.0 shows the console output I'm used to, which gives a more comfortable feeling: it's "clearly still doing stuff and not just hanging". So this does indeed feel like a serious issue.

(The screenshot in the OP confuses me a bit, because it shows 3.1.0, while the issue for ternavsky and I only appeared on 3.2.1.)

**Comment by xiaohuahou** [comment] 2021-03-12 02:47
same issue.

**Comment by kalvintera** [comment] 2021-03-12 17:58
same issue

**Comment by jehadassaf** [comment] 2021-03-15 10:42
Same issue. Is there a way to prevent auto update?

**Comment by ternavsky** [comment] 2021-03-15 11:04
> Same issue. Is there a way to prevent auto update?

I just deny Docker desktop to make changes in system on startup. After that you should run Docker by yourself, cause autostart won't work.

**Comment by Myhael76** [comment] 2021-03-15 22:18
> I noticed this warning message only appears when running Docker Compose commands. It looks like both Docker and Docker Compose merged changes to use native build / buildx by default now. Why is this warning still here?
> 
> ```
> WARNING: Native build is an experimental feature and could change at any time
> ```
> 
> And why does the handle error disappear when I turn off native build?
> 
> ```
> PS> [System.Environment]::SetEnvironmentVariable('COMPOSE_DOCKER_CLI_BUILD', '0', 'Process')
> 
> PS> docker-compose build
> Building web
> Step 1/1 : FROM nginx:stable
>  ---> 05f64a802c26
> 
> Successfully built 05f64a802c26
> Successfully tagged downloads_web:latest
> ```

Same fore me. In normal command window this works:

```
set COMPOSE_DOCKER_CLI_BUILD=0
docoker-compose build
```

If I put the variable on 1 it gives the handle error.

I updated today, March 15th

```
c:\>docker-compose version
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Comment by sigmanil** [comment] 2021-03-16 13:18
same issue.

**Comment by bc3tech** [comment] 2021-03-16 17:22
+1

**Comment by nunoperalta** [comment] 2021-03-16 22:49
Great suggestion above.

In VS Code, I'm adding to the workspace settings:

		"terminal.integrated.env.windows": {
			"COMPOSE_DOCKER_CLI_BUILD": "0"
		},

The first time, VS Code will ask if you allow setting this variable, when you open the terminal.
Press "Allow", kill the terminal and restart the terminal.

"docker-compose build" will now work properly.

**Comment by Warfront1** [comment] 2021-03-19 16:21
Same issue on windows docker desktop 3.2.2. 
![image](https://user-images.githubusercontent.com/1920038/111811318-4e575c80-88ad-11eb-947a-8887fb21e6cd.png)

The most upsetting part of this all is how docker just auto updated. 
Previously I would wait numerous months after a update, to actually update my docker, to avoid these kind of small bugs.
I would typically update on another test development machine, prior to updating my actual development machine
to ensure there are no bugs on the latest version.
We really need a way to opt out of updates, as this can really kill productivity.

**Comment by icavalheiro** [comment] 2021-03-25 18:48
This is actually driving me crazy, I have so many developers affected because of this...
Setting COMPOSE_DOCKER_CLI_BUILD to 0 actually breaks it (same error we get when docker service is not initialized).

**Comment by ZukkyBaig** [comment] 2021-03-26 14:57
Any update on what's happening with this? It's happening to all of my developers, and it's obscuring the logs.

**Comment by tvaudelin** [comment] 2021-03-31 09:21
Same problem on my side. It would be great to get an update.

**Comment by jski** [comment] 2021-04-02 15:23
Having this same issue and interested in a solution as well.

**Comment by ndeloof** [comment] 2021-04-06 14:45
seems error is triggered by https://github.com/containerd/console/blob/master/console_windows.go#L54

**Comment by ndeloof** [comment] 2021-04-06 15:30
I expected this could be fixed by running build with --progress=plain, but unfortunately error persists. There might be another piece of code using `ConsoleFromFile` :(

**Comment by Westmorland** [comment] 2021-04-06 19:36
+1

**Comment by didier-rda** [comment] 2021-04-07 01:34
same issue.

**Comment by ChristophorusReyhan** [comment] 2021-04-07 05:10
Same issue, docker-compose build stuck at  

> => [stage-0 2/8] RUN apt-get update && apt-get install -y     git       202.4s 

after updating, and 

> failed to get console mode for stdout: The handle is invalid. 

warning appears. COMPOSE_DOCKER_CLI_BUILD=0 doesn't solve the problem. 

> D:\>docker-compose version
> docker-compose version 1.28.5, build c4eb3a1f
> docker-py version: 4.4.4
> CPython version: 3.9.0
> OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

It would be great if auto-update is an option.

**Closed** 2021-04-09 17:29 UTC
Labels: kind/bug

**Comment by almogtavor** [comment] 2021-04-10 15:36
What's the solution to this? @ndeloof why did you close?

**Comment by AnthonyMastrean** [comment] 2021-04-10 15:56
Looks like it’s been fixed. There’s a linked MR. Guess we’re waiting for a release!

**Comment by alexpapworth** [comment] 2021-04-20 14:07
Fixed in docker-compose version 1.29.1, for those that want to cross-reference with `docker-compose version`.

**Comment by JeremyKennedy** [comment] 2021-04-21 19:13
I can confirm that I don't get this error anymore. On Windows, I had to manually download the new `compose` binary and replace it on my system, since Docker for Windows didn't seem to be able to pull the most recent update.

**Comment by AlissonRS** [comment] 2021-04-23 06:21
@JeremyKennedy I can confirm that too. Only solved after manually downloading the binary (link below) and replacing it manually.

https://github.com/docker/compose/releases

**Comment by shakyav** [comment] 2021-04-24 07:00
> @JeremyKennedy I can confirm that too. Only solved after manually downloading the binary (link below) and replacing it manually.
> 
> https://github.com/docker/compose/releases

How to replace docker-compose manually on windows ?

**Comment by AlissonRS** [comment] 2021-04-24 16:53
@shakyav download the .exe from the link: https://github.com/docker/compose/releases

![image](https://user-images.githubusercontent.com/4753901/115966391-c1cf3800-a503-11eb-9475-c5c6ec9defb2.png)

Replace the `docker-compose.exe` in your machine with the one you downloaded.

If you don't know where `docker-compose.exe` is located in your machine, open Git Bash, type `which docker-compose`, this command will reveal the folder where docker-compose is installed in your machine.

![image](https://user-images.githubusercontent.com/4753901/115966356-a106e280-a503-11eb-8474-c298bd5e7e53.png)

![image](https://user-images.githubusercontent.com/4753901/115966536-66517a00-a504-11eb-821b-c58c6d108ca0.png)

**Comment by SetTrend** [comment] 2021-05-18 10:12
Just like to add a way to search using standard tools of the operating system:

```ps
(Get-ChildItem Env:Path).Value.Split(';')
  | Where-Object { $_.IndexOf('Docker') -gt 0 }
  | ForEach-Object { Get-ChildItem -Path $_ -Include 'docker-compose.exe' -Recurse 2>$Null }
```

... returning:

```batch
   Directory: C:\Program Files\Docker\Docker\resources\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          12.05.2021    23:38       10452224 docker-compose.exe
```

**Comment by buddha314** [comment] 2021-05-27 22:08
I had this problem launching from PowerShell.  However, when launching from WSL2 it built correctly.

**Comment by cw0102** [comment] 2021-06-08 06:09
This seems to be tangentially relayed to the docker-compose command being merged into the "docker" command, i.e. "docker compose up -d" vs "docker-compose up -d". Using the latter I was getting this error, but the former spits out the error described.

**Comment by gebrouwe** [comment] 2022-02-28 12:20
Got the same error "failed to get console mode for stdout: The handle is invalid." for the command "docker compose run --rm <service> <command>".
The error disappears when I replace "docker compose" by: "docker-compose".

I am using Docker Desktop for Windows 10.

$ docker --version
Docker version 20.10.10, build b485636

$ docker-compose --version
docker-compose version 1.29.2, build 5becea4c

**Comment by j-p-e** [comment] 2022-04-06 16:50
seconded - it's back with these on Win10
Docker version 20.10.13, build a224086
Docker Compose version v2.3.3

**Comment by sokraflex** [comment] 2022-04-22 08:24
Same here - getting the warning on Windows 11: failed to get console mode for stdin: The handle is invalid.
Docker version 20.10.14, build a224086
Docker Compose version v2.4.1

Warning appears every time when I run `docker-compose up` or `docker-compose down`.
COMPOSE_DOCKER_CLI_BUILD=0 doesn't help

**Comment by maximepel** [comment] 2022-09-30 12:55
**I'm having the same "issue" on Windows while running a shell script containing the command:**
`cat context.tar.xz | docker build - --tag "something:1.0"`

**But when I run the same script on macOS (Apple M1):**
I don't get this issue at all

It seems that the Docker image builds anyway but this could be problematic as my container won't work when run from Windows built image...

**Comment by CollinAlpert** [comment] 2023-03-31 06:07
I am experiencing the issue when piping a docker command (e.g. `docker build`) into `tee`.

**Comment by ndeloof** [comment] 2023-03-31 06:14
@CollinAlpert try running `com.docker.cli build | tee ..`. I wonder this is a side effect for legacy telemetry mechanism in Docker Desktop

**Comment by FlorentP42** [comment] 2023-08-23 08:18
Getting the same error message except it's directly from `docker build`, not from `docker-compose` with versions:
```
Client:
 Cloud integration: v1.0.35-desktop+001     
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.22.0 (117440)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

When redirecting the output of a bat script to a file from regular Windows cmd:
Withing cmd:
`build.bat`
Works fine, display full output in cmd.

Withing cmd:
`build.bat > out.txt`
Executes everything, display full output in cmd but in `out.txt` logs stops after:
```
docker build . --progress=plain -f .\build_with_docker\Dockerfile -t some_project_options...
failed to get console mode for stdout: The handle is invalid.
```
Then continues logging after the execution of the docker command is complete.

**Comment by blueblakk** [comment] 2023-08-30 08:16
Same issue executing my git hooks with docker compose.

![image](https://github.com/docker/compose/assets/83833956/b4a12651-ab15-484c-9caa-f6d19a2cf021)

**Comment by tewha** [comment] 2023-09-12 17:14
I only started getting this last week with Git for Windows' bash run through Windows Terminal.

I tee'd it to see the output (I hope):

```bash
$ docker run --entrypoint bash --rm -it $(docker build -q . | tee output)
Unable to find image 'failed:latest' locally
docker: Error response from daemon: pull access denied for failed, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

$ cat output
failed to get console mode for stdout: The handle is invalid.
sha256:c7c0efb9f8895c8a9d41e630051d503dc31d1537bbdbd8fb7a0e0de6b58499d8

```

I think I only turned on WSL usage recently, so I'll try later with HyperVisor.

**Comment by entrptaher** [comment] 2024-01-24 03:36
I am facing same in **powershell**.

No issue,
```
docker build -q .          
sha256:06e2720c9ad96e85cfb75b71b5e669a6d17026eaef3b6ed9b3d7583062a58969```
```

Having issue,
```
echo $(docker build -q .)       
failed to get console mode for stdout: The handle is invalid.
sha256:06e2720c9ad96e85cfb75b71b5e669a6d17026eaef3b6ed9b3d7583062a58969
```

Running this in the wsl (but not with docker desktop, directly installed with get.docker.com),
```
docker build -q .
sha256:02456f9476874d8e72b8e658fcfd774175ded1c4b40efd4b72c826fd16aa889b

echo $(docker build -q .)
sha256:02456f9476874d8e72b8e658fcfd774175ded1c4b40efd4b72c826fd16aa889b
```

Running inside wsl in docker desktop,
```
docker build -q .
sha256:bf899b8ae1802f3d4415c33343b66b1d636a41e9121f19dfabe93073859e76b4

echo $(docker build -q .) 
sha256:bf899b8ae1802f3d4415c33343b66b1d636a41e9121f19dfabe93073859e76b4
```

**Comment by jcmuel** [comment] 2024-02-08 13:21
Our Windows developer has the same problem on Windows 11:

1. Docker: [4.27.1](https://docs.docker.com/desktop/release-notes/#4271)
2. GitBash: 2.43.0, with the following non-standard options:
    a. "Use Windows' default console Window"
    b. "Enable experimental support for pseudo consoles"

The following docker command produced the same error message.
```
> docker ps -aqf "name=^our_image_name_here"
failed to get console mode for stdout: The handle is invalid.
10edc44cf0c3
```

**We downgraded docker to version** [4.26.1](https://docs.docker.com/desktop/release-notes/#4261) **and that also solved the issue for us.**

**Comment by FlorentP42** [comment] 2024-02-08 14:25
@AnthonyMastrean Would you mind reopening this issue? As it is clrearly still broken in the latest release so far...

**Comment by ndeloof** [comment] 2024-02-08 14:36
@jcmuel please report this issue to github.com/docker/cli as you can reproduce with a plain `docker ps ...` command

**Comment by jcmuel** [comment] 2024-02-08 16:55
The issue is also discussed here: https://github.com/docker/for-win/issues/13891

@ndeloof : Should I report it anyway also in docker/cli ?

**Comment by ndeloof** [comment] 2024-02-08 16:59
nope, https://github.com/docker/for-win/issues/13891 already has enough details AFAICT

**Comment by karimkod** [comment] 2024-02-13 13:49
on pwsh the only way I tought of to get around this is by using `Select-Object`: 
`
docker ps --filter "status=running" --filter "name=mongodb" -q | Select-Object -Skip 1
`

**Comment by quarky42** [comment] 2024-03-07 23:00
Docker Desktop 4.27.2 had this error.  Docker Desktop 4.28.0 fixed this for me.
I was using `volumes=$(docker volume ls -q)` and getting the error stored in the variable as part of a larger script that removed all listed volumes but only if $volumes was defined / non-empty.  (Using Git-Bash)
