### ISSUE TITLE
docker-compose v2 services dns don`t work

### ISSUE THREAD

**Issue by pahaz** [docker/compose#3703] opened 2016-07-07 13:33 UTC
How to reproduce:

**docker-compose-consul-test.yml**
```
version: '2'

services:
   tmp:
     image: buildpack-deps:jessie
     command: cat /etc/resolv.conf
     dns_search: service.consul
     dns: 8.8.8.8
```

test1:
```
$ docker-compose -f docker-compose-consul-test.yml up
Starting infrastructure_tmp_1
Attaching to infrastructure_tmp_1
tmp_1  | search service.consul
tmp_1  | nameserver 127.0.0.11
tmp_1  | options ndots:0
infrastructure_tmp_1 exited with code 0
```

test2:
```
$ docker run -it --dns 8.8.8.8 --dns-search service.consul --rm buildpack-deps:jessie cat /etc/resolv.conf
search service.consul
nameserver 8.8.8.8
```

**Compose ignore dns configuration!**

Info:
```
$ docker --version
Docker version 1.12.0-rc2, build 906eacd, experimental
$ docker-compose --version
docker-compose version 1.7.1, build 6c29830
$ pip freeze | grep docker
docker-compose==1.7.1
docker-py==1.8.1
dockerpty==0.4.1
```

**Comment by aanand** [comment] 2016-07-07 18:00
This is a duplicate of https://github.com/docker/compose/issues/2847, and isn't a bug.

DNS is configured differently when using a custom network (as is the case when using v2 of the Compose file format), but the `dns` setting is still respected. From the [Docker networking docs](https://docs.docker.com/engine/userguide/networking/configure-dns/):

> The IP addresses passed via the `--dns` option is used by the embedded DNS server to forward the DNS query if embedded DNS server is unable to resolve a name resolution request from the containers. These `--dns` IP addresses are managed by the embedded DNS server and will not be updated in the container's `/etc/resolv.conf` file.

**Closed by aanand** 2016-07-07 18:00 UTC
