### ISSUE TITLE
Partial services started/exited when images in other service is not available

### ISSUE THREAD

**Issue by arun-gupta** [docker/compose#3225] opened 2016-03-28 19:04 UTC
Tried to start a multi-container application using `docker-compose.yml`:

```
version: "2"
services:
  db:
    container_name: "db"
    image: arungupta/oreilly-couchbase
    ports:
      - 8091:8091
      - 8092:8092 
      - 8093:8093 
      - 11210:11210
  web:
    image: arungupta/oreilly-wildfly
    depends_on:
      - db
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
```

Got the error:

```
docker-compose up -d
Creating network "hellojavaee_default" with the default driver
Pulling db (arungupta/oreilly-couchbase:latest)...
Pulling repository docker.io/arungupta/oreilly-couchbase
ERROR: Error: image arungupta/oreilly-couchbase not found
```

Built the image, and then tried the command again. This gave the error:

```
docker-compose up -d
Creating db
ERROR: Conflict. The name "/db" is already in use by container 1eea595a71f84e47a5b889951e950534f1b1d949666fb85a577795f0423a8a1b. You have to remove (or rename) that container to be able to reuse that name.
```

If one of the service could not be started then the containers started by other services are exited. But this does not allow to run the `docker-compose up -d` command again.

**Comment by dnephin** [comment] 2016-03-28 22:47
I don't think that is the cause of this error. Compose never created that container. 

The problem is that the container name is already in use by something else. This is a common problem with using `container_name`, you're breaking the isolation provided by Compose.

If you `docker inspect db`, I think you'll see the container is part of some other project and doesn't have the labels that Compose would assign it (or at least not the ones for this project).

If you remove `container_name` or `docker rm db`  it should work again.

**Closed** 2017-02-17 02:02 UTC
Labels: kind/question
