### ISSUE TITLE
[BUG] `Application failed to start after update` when rebuilding Go process with `docker compose watch` that has external network

### ISSUE THREAD

**Issue by nickzelei** [docker/compose#11253] opened 2023-12-06 18:55 UTC
### Description

I'm trying to use `docker compose watch` to restart my Go process any time I run a build.
The docs state this is equivalent to `docker compose up --build`, which works as expected. However the watch command results in the `Application failed to start after update` error.

The workaround was to instead use `sync+restart`

### Steps To Reproduce
1. Clone this repo: https://github.com/nickzelei/docker-watch-error
2. Ensure you have Go installed
3. Run: `make build`
4. Run: `docker compose -f compose-external.yml up -d`
5. Run: `docker compose up -d`
6. Run: `docker compose watch`
7. Run: `make build`
8. Process will result in error

To get it to work:
1. Remove the `my-network2` from the `services.my-api.networks` and the `networks` section in `compose.yml`
2. Run: `docker compose down && docker compose up -d && docker compose watch`
3. Run: `make build`
4. Process will restart with no error

```
➜  docker-watch-error git:(main) ✗ docker compose watch
[+] Building 0.0s (0/0)                                              docker:desktop-linux
[+] Running 1/0
 ✔ Container my-api  Running                                                         0.0s 
watching [/Users/nick/code/personal/docker-watch-error/bin]
Rebuilding my-api after changes were detected:
  - /Users/nick/code/personal/docker-watch-error/bin/api
[+] Building 0.4s (9/9) FINISHED                                     docker:desktop-linux
 => [my-api internal] load .dockerignore                                             0.0s
 => => transferring context: 2B                                                      0.0s
 => [my-api internal] load build definition from Dockerfile.dev                      0.0s
 => => transferring dockerfile: 133B                                                 0.0s
 => [my-api internal] load metadata for docker.io/library/alpine:3.18                0.3s
 => [my-api 1/4] FROM docker.io/library/alpine:3.18@sha256:34871e7290500828b39e2229  0.0s
 => [my-api internal] load build context                                             0.0s
 => => transferring context: 6.45MB                                                  0.0s
 => CACHED [my-api 2/4] RUN mkdir /app                                               0.0s
 => CACHED [my-api 3/4] WORKDIR /app                                                 0.0s
 => CACHED [my-api 4/4] COPY /bin/api /app                                           0.0s
 => [my-api] exporting to image                                                      0.0s
 => => exporting layers                                                              0.0s
 => => writing image sha256:e5ddaa9b2d3ca4d016fa7a97869b401c6cd5ec5e2dec392643dbf75  0.0s
 => => naming to docker.io/library/my-api                                            0.0s
Application failed to start after update
```

### Compose Version

```Text
➜  ~ docker compose version
Docker Compose version v2.23.0-desktop.1
```

### Docker Environment

```Text
➜  ~ docker info
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/nick/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/nick/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/nick/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/nick/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/nick/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/nick/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/nick/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/nick/.docker/cli-plugins/docker-scout

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 20
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 23.44GiB
 Name: linuxkit-263db725e496
 ID: 06e4846c-251a-4ec1-a074-26d259b4dfef
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Anything else?

Here is the PR where I changed it from `rebuild` to `sync+watch`
https://github.com/nucleuscloud/neosync/pull/764

I thought this was fixed with: https://github.com/docker/compose/pull/11092 but maybe that hasn't been released yet, not sure.

**Comment by jhrotko** [comment] 2024-01-08 12:45
Hello, @nickzelei. I just tested with the latest version of compose (v2.24.0) and could not reproduce the error you mentioned in this issue. I also tested with the docker compose version you stated and in fact, the error happens as you describe. So I believe the issue has been fixed in newer versions. Could you please re-test again?

**Comment by jhrotko** [comment] 2024-01-12 15:58
Hey, @nickzelei. Your issue was fixed in https://github.com/docker/compose/commit/c7e31a3c1597eec0d5b7c9d31d076979ca31cafe . Please update docker compose to the latest version

**Closed by jhrotko** 2024-01-12 15:58 UTC
Labels: kind/bug, status/0-triage

**Comment by nickzelei** [comment] 2024-01-12 16:58
Hey, my apologies for the delay, I'll test this locally today! Thanks for letting me know it has been fixed.

**Comment by nickzelei** [comment] 2024-01-13 22:09
Is the release wrapped in to compose 2.24?

I just updated docker desktop on my mac but 2.24 doesn't seem to be released quite yet.

```
~ docker compose version
Docker Compose version v2.23.3-desktop.2
➜  ~ docker-compose version
Docker Compose version v2.22.0
```
