### ISSUE TITLE
docker-compose ignores one (?)  entry under labels:

### ISSUE THREAD

**Issue by hansij66** [docker/compose#7426] opened 2020-05-04 19:08 UTC
## Description of the issue
I have following (minimal, stripped to demo issue) docker-compose.yml file
```
version: '3.7'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana

    labels:
     - "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
     - "traefik.http.routers.grafana.middlewares=authelia@docker"
```
Output of docker-compose config
```
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    labels:
      traefik.httpp.routers.grafana.middlewares: authelia@docker
version: '3.7'
```
--> one of the entries under labels: is missing

I can fix this by "playing" with the entries. E.g. change in one of the entries routers --> router (remove s) and it works....but routers is a traefik keyword...

Issue hit me hard, difficult to find, and I ended up exposing a few docker services to the internet because authentication label disappeared....

I could not find any limitations on labels: usage in the dc documentation.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

## Steps to reproduce the issue

1. See docker-compose.yml above
2. docker-compose config
3.

### Observed result

One of the entries under labels: is missing

### Expected result
Both entries under labels are present
### Stacktrace / full error message

```
(paste here)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by thaJeztah** [comment] 2020-05-04 19:31
This is expected; labels are key/value pairs, so the second value for `traefik.http.routers.grafana.middlewares` overwrites the first value. If traefik supports multiple values to be passed through this label, they should find some other convention for that (e.g. comma-separated values `traefik.http.routers.grafana.middlewares=<one>,<two>,<three>`)


Closing this ticket because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-04 19:31 UTC
Labels: kind/bug

**Comment by hansij66** [comment] 2020-05-04 19:39
Hi Sebastiaan, I feel very stupid.....looking at this for
hours....overlooking the obvious....

Many thanks!
Cheers
Hans

**Comment by thaJeztah** [comment] 2020-05-04 21:02
You're welcome! It's slightly confusing because the compose-file format accepts both a `map` and an array (which would easily lead to the conclusion that entries in the array don't have to be unique).
