### ISSUE TITLE
Docker-compose doesnt mount local folder

### ISSUE THREAD

**Issue by terbooter** [docker/compose#1121] opened 2015-03-17 14:37 UTC
I can start my container in two ways:
1) Using console commands (bash script)
2) Using docker-compose util
Before each start I remove all containers and remove all images

In first case I made
```bash
docker build -t web-image .
docker run --restart=always -d -v $(pwd)/www:/app -p 82:80 web-image
```
Container working as expected. In folder /app I have my mounted project files

In second case I have docker-compose.yml config file
```yml
web:
  build: .  
  volumes:
    - www:/app
  ports:
    - "82:80"
  restart: always
```
```sh
docker-compose up -d 
```
In this case container folder /app is empty

**Comment by LeoCBS** [comment] 2015-04-07 14:38
Same problem here, compose doesn’t mount folder
Ubuntu 14.04
Docker version: 1.5.0, build a8a31ef
Compose version: 1.1.0

**Comment by LeoCBS** [comment] 2015-04-07 15:46
i solved this problem removing and building the image again

**Comment by dnephin** [comment] 2015-09-04 16:15
I think this is a duplicate of #1882 going to close

Removing the containers is a good workaround for now

**Closed by dnephin** 2015-09-04 16:15 UTC
Labels: area/volumes
