### ISSUE TITLE
Support for container names containing dots or dash

### ISSUE THREAD

**Issue by bitliner** [docker/compose#869] opened 2015-01-22 14:21 UTC
Do you plan to add support for dash and dots in container names?

**Comment by dnephin** [comment] 2015-01-22 15:35
Once docker has [support for labels](https://github.com/docker/docker/pull/9882) fig/compose will be able to use these labels instead of rely on container and image naming conventions.  At that point we should be able to remove any restrictions on the names, and support anything supported by dockerd.

**Comment by hadim** [comment] 2015-01-22 17:03
+1

**Comment by lazyval** [comment] 2015-01-28 14:12
Semi-duplicate of https://github.com/docker/fig/issues/799

**Comment by thaJeztah** [comment] 2015-03-17 08:43
Happy to inform that support for labels (https://github.com/docker/docker/pull/9882) was merged and will be included in the upcoming 1.6 release of Docker.

Also, I think there are currently a number of related issues in this area (https://github.com/docker/compose/issues/652, https://github.com/docker/compose/issues/869, https://github.com/docker/compose/issues/941 among others); perhaps the discussion should be focussed on the global proposal https://github.com/docker/compose/issues/1066 (but that's just a suggestion)

**Comment by oblop** [comment] 2015-04-14 12:12
Docker 1.6 is about to be released.

Any news on the changes needed in docker-compose to allow for custom container name?

**Comment by thaJeztah** [comment] 2015-04-14 17:06
I think basic labels support (which is just the start) was implemented, but had to be reverted because of incompatibilities with some library :(

**Comment by aanand** [comment] 2015-06-05 13:39
Closing in favour of https://github.com/docker/compose/issues/1519

**Closed by aanand** 2015-06-05 13:39 UTC
