### ISSUE TITLE
Possibility to define in fig.yml if container should be created or not

### ISSUE THREAD

**Issue by vidarl** [docker/compose#542] opened 2014-10-15 13:20 UTC
There are use-cases where you want to create base images ( which you'll use for creating other images ), but you don't need any containers from those images.

There are also use-cases where you want containers to be created, but purged once they ends ( like ```docker run --rm ...``` )

This could be configurable with the following syntax:
```
ubuntu:
  build: dockerfiles/ubuntu
  create_container: false # true is default
foobar:
  build: dockerfiles/foobar
  remove_container: true # false is default
```

**Comment by dnephin** [comment] 2015-09-18 14:23
Duplicate of #1896

**Closed by dnephin** 2015-09-18 14:23 UTC
