### ISSUE TITLE
[BUG] 'down <service>' does not close dependencies

### ISSUE THREAD

**Issue by EdwinKM** [docker/compose#11287] opened 2023-12-19 19:53 UTC
### Description

For all commands we honor and start/stop all dependencies:
  - up
  - up [service]
  - run
  - down

However, the 'down [service]' command doesn't adhere to these default dependencies.

### Steps To Reproduce

Dockerfile
```
FROM alpine
CMD sleep infinity
```
Build images
```
docker build --tag "localhost/dbimage" --file Dockerfile .
docker build --tag "localhost/app1image" --file Dockerfile .
docker build --tag "localhost/app2image" --file Dockerfile .
```

docker-compose.yml
```
version: "3.8"
services:
  dbservice:
    image: localhost/dbimage
    pull_policy: never
    container_name: dbcontainer

  app1service:
    image: localhost/app1image
    pull_policy: never
    container_name: app1container
    depends_on:
      - dbservice

  app2service:
    image: localhost/app2image
    pull_policy: never
    container_name: app2container
    depends_on:
      - dbservice

```

Start "app2service"
```
docker compose up --detach app2service
[+] Running 3/3
 ✔ Network compose_down_bug_default  Created                                                                                                            0.1s
 ✔ Container dbcontainer             Started                                                                                                            0.0s
 ✔ Container app2container           Started
```

Terminate "app2service"
```
docker compose down app2service
[+] Running 2/1
 ✔ Container app2container           Removed                                                                                                           10.4s
 ! Network compose_down_bug_default  Resource is still in use                                                                                           0.0s
```
Current Outcome: It exclusively shuts down 'app2container' and issues a warning related to the network.

Expected Outcome: It should honor the specified dependency and terminate the 'dbcontainer' only if no other containers are reliant on it. 
Additionally, the removal of 'compose_down_bug_default' should not lead to any failures.

The rationale behind this approach is to facilitate the ability to launch a secondary 'app' 
service at a later time while reusing the existing database container. 
When initiating a 'close' action, if only one instance of the 'app' service is running,
we can also shut down the associated database container.

Altering the current behavior could pose a risk as there might already be companies relying on the existing setup.
Alternatively, an additional solution could involve introducing a new flag, 
such as 'docker compose down --close-dependencies app2service', to address this scenario.

### Compose Version

```Text
Docker Compose version v2.23.3-desktop.2
```

### Docker Environment

```Text
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.689GiB
 Name: docker-desktop
 ID: f74684c6-f352-49c4-9340-f5379ea3726f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

**Comment by ndeloof** [comment] 2023-12-20 08:13
this is the expected behavior. `down SERVICE` only target an explicit list of service, assuming the reason you only selected a subset is you want the other ones to stay up.
Can you please clarify your actual needs here ?

**Comment by ndeloof** [comment] 2023-12-20 10:44
As you noticed, running `docker compose down app1service` **CAN't** remove a dependency as it maybe is required by another service. Could be an explicit dependency set by `depends_on` but also an implicit one just accessed by a shared network. Network use on the other hand can be detected, so the warning.
That's the main reason `down` when used with an explicit service doesn't manage dependencies. There no intent to look "symetrical" here with the `up` command, just to ensure the application is in a correct state. When you shut down a service, you don't ask to shut down the whole application, so other services must still be healthy, including dependencies (database in your example). On the other hand, when you run `down` without arguments you ask compose to shut down the whole application, so it will do a full cleanup.

I'm closing this issue as "won't fix", also just consider making changes in this behavior would be a major breaking change that would impact thousands users.

**Closed by ndeloof** 2023-12-20 10:44 UTC
Labels: kind/bug, status/0-triage

**Comment by ndeloof** [comment] 2023-12-20 10:48
Best I can suggest is we introduce some `--deps` flags to mimic `up --no-deps` and force `down` to also consider service dependencies.

**Comment by EdwinKM** [comment] 2023-12-20 13:00
@ndeloof 
I understand that the dependency can not be closed if another service is still using it. But that is fixable with some logic.
And indeed changing this can impact other users. The choice seems deliberate.

Maybe explicitly add it to the documentation that the behavior is a " asymmetrical"?
https://docs.docker.com/engine/reference/commandline/compose_down/

--deps would be useful in our case, but only if it ***only*** shutdowns unused containers.

If not possible i will remove the feature to partly close the stack in our wrapper script.

**Comment by ndeloof** [comment] 2023-12-20 13:13
> only if it only shutdowns unused containers.

that's the challenge: we can't guess a container is in use by another one

Also, this behavior in not "asymmetrical": `compose up` will create container in dependency order, while `compose down` will remove them in reverse order: if you run `compose down database` you'll see both your app services being stopped.

**Comment by EdwinKM** [comment] 2023-12-20 13:43
yeah, i meant in reverse order. Dependencies are defined in the compose file so i would imagine things can be calculated/verified. (But maybe that information is lost on active containers?).

aka: stop app2service -> try dbcontainer -> dbcontainer see still that app1service has a dependency and it will only "info/warn"  about not closing the dependency.

But dependency management can become difficult fast with multiple dependencies.
The "--deps" with implied "force close" is not useful. And dangerous.

Lets keep the state "wontfix". I will remove this feature in our wrapper script (and documentation)

Thanks for the fast reactions!
