### ISSUE TITLE
use docker-compose build  and docker build generate different images from the same Dockerfile  

### ISSUE THREAD

**Issue by PureLo** [docker/compose#9390] opened 2022-04-14 07:11 UTC
** used the same Dockerfile, execute [docker-compose build] and [docker build] The "Cmd" for generating the image is different.**

**Steps to reproduce the issue:**
1.(1)Dockerfile
```
FROM golang:alpine AS builder

WORKDIR /build

ADD go.mod .
COPY . .
RUN go build -o hello main.go


FROM alpine:3.12 

WORKDIR /build

COPY --from=builder /build/hello /build/hello

CMD ["./hello"]
```
(2)docker-compose.yml
```
version: '3.2'

services:
  hello:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    image: hello:v-docker-compose
    container_name: hello
    ports:
      - 8081:8081
```
2.docker build -t hello:v-dockerfile .
```
Sending build context to Docker daemon   5.12kB
Step 1/9 : FROM golang:alpine AS builder
 ---> dd6fd110e957
Step 2/9 : WORKDIR /build
 ---> Running in 5ed9e972ee6e
Removing intermediate container 5ed9e972ee6e
 ---> a2d89fbd6f8c
Step 3/9 : ADD go.mod .
 ---> e92ece92147c
Step 4/9 : COPY . .
 ---> 029d694967da
Step 5/9 : RUN go build -o hello main.go
 ---> Running in 7e9b5f375a97
Removing intermediate container 7e9b5f375a97
 ---> 1f4d09ced03f
Step 6/9 : FROM alpine:3.12
 ---> 24c8ece58a1a
Step 7/9 : WORKDIR /build
 ---> Running in d57996180a8a
Removing intermediate container d57996180a8a
 ---> 589fd67fb49e
Step 8/9 : COPY --from=builder /build/hello /build/hello
 ---> 18f7c6e8e134
Step 9/9 : CMD ["./hello"]
 ---> Running in c72019df80ad
Removing intermediate container c72019df80ad
 ---> 4c176df4d04b
Successfully built 4c176df4d04b
Successfully tagged hello:v-dockerfile
```
3.docker-compose build
```
[+] Building 0.7s (14/14) FINISHED                                                                                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                                                                                                 0.0s
 => => transferring dockerfile: 91B                                                                                                                                                                                  0.0s
 => [internal] load .dockerignore                                                                                                                                                                                    0.0s
 => => transferring context: 2B                                                                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/golang:alpine                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12                                                                                                                                                       0.0s
 => [builder 1/5] FROM docker.io/library/golang:alpine                                                                                                                                                               0.0s
 => [internal] load build context                                                                                                                                                                                    0.0s
 => => transferring context: 570B                                                                                                                                                                                    0.0s
 => [stage-1 1/3] FROM docker.io/library/alpine:3.12                                                                                                                                                                 0.0s
 => CACHED [builder 2/5] WORKDIR /build                                                                                                                                                                              0.0s
 => CACHED [builder 3/5] ADD go.mod .                                                                                                                                                                                0.0s
 => [builder 4/5] COPY . .                                                                                                                                                                                           0.0s
 => [builder 5/5] RUN go build -o hello main.go                                                                                                                                                                      0.6s
 => CACHED [stage-1 2/3] WORKDIR /build                                                                                                                                                                              0.0s
 => CACHED [stage-1 3/3] COPY --from=builder /build/hello /build/hello                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                               0.0s
 => => exporting layers                                                                                                                                                                                              0.0s
 => => writing image sha256:5308620cc7423a5a60423e5afaeeafa1ad6d5af72a11899f392da6629ded7fc0                                                                                                                         0.0s
 => => naming to docker.io/library/hello:v-docker-compose                                                                                                                                                            0.0s
```
**Describe the results you received:**
(1)hello:v-dockerfile
``` 
[
    {
        "Id": "sha256:4c176df4d04b5dd765ec5b84efc282c542a4b8878fbdff332afd0e705b2acf59",
        "RepoTags": [
            "hello:v-dockerfile"
        ],
        "RepoDigests": [],
        "Parent": "sha256:18f7c6e8e134f80fae272bd2a512097ffd119668b18165793259d2c0bf019e41",
        "Comment": "",
        "Created": "2022-04-14T06:58:39.229165576Z",
        "Container": "c72019df80ad0eb797383b9fabe71dd8adc83e008ccf6b53faea372f605c64a8",
        "ContainerConfig": {
            "Hostname": "c72019df80ad",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"./hello\"]"
            ],
            "Image": "sha256:18f7c6e8e134f80fae272bd2a512097ffd119668b18165793259d2c0bf019e41",
            "Volumes": null,
            "WorkingDir": "/build",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "19.03.7",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "./hello"
            ],
            "Image": "sha256:18f7c6e8e134f80fae272bd2a512097ffd119668b18165793259d2c0bf019e41",
            "Volumes": null,
            "WorkingDir": "/build",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 11866196,
        "VirtualSize": 11866196,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/3d9f997844dbd7fd6bc772492f45b48ed5a10f6f362367377786d48f579f4a88/diff:/var/lib/docker/overlay2/a494fb045d7e190a3bcbc39ab5f45f9b5a2e8d4759eb1aa83b7cab74c829f259/diff",
                "MergedDir": "/var/lib/docker/overlay2/66195436c466caacb9b8eea3e0260ed0aec3e3c0cdf351566b5ba5be93310a4c/merged",
                "UpperDir": "/var/lib/docker/overlay2/66195436c466caacb9b8eea3e0260ed0aec3e3c0cdf351566b5ba5be93310a4c/diff",
                "WorkDir": "/var/lib/docker/overlay2/66195436c466caacb9b8eea3e0260ed0aec3e3c0cdf351566b5ba5be93310a4c/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:1ad27bdd166b922492031b1938a4fb2f775e3d98c8f1b72051dad0570a4dd1b5",
                "sha256:24503e2979aff7bcdf21c81504734a800c3a9f760df77f3e8194a49235ebbf3b",
                "sha256:88ac5f93371b8711c87d569c7eabf223b578427d1e9e6d65400bd335354d7b99"
            ]
        },
        "Metadata": {
            "LastTagTime": "2022-04-14T14:58:39.251086249+08:00"
        }
    }
]
```
(2)hello:v-docker-compose
```
[
    {
        "Id": "sha256:5308620cc7423a5a60423e5afaeeafa1ad6d5af72a11899f392da6629ded7fc0",
        "RepoTags": [
            "hello:v-docker-compose"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "buildkit.exporter.image.v0",
        "Created": "2022-04-14T13:45:07.972502392+08:00",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 11866196,
        "VirtualSize": 11866196,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/tvf9zz01cri0c211mjf32uwlv/diff:/var/lib/docker/overlay2/a494fb045d7e190a3bcbc39ab5f45f9b5a2e8d4759eb1aa83b7cab74c829f259/diff",
                "MergedDir": "/var/lib/docker/overlay2/njjzeupat2r1fk8xcooibvyjw/merged",
                "UpperDir": "/var/lib/docker/overlay2/njjzeupat2r1fk8xcooibvyjw/diff",
                "WorkDir": "/var/lib/docker/overlay2/njjzeupat2r1fk8xcooibvyjw/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:1ad27bdd166b922492031b1938a4fb2f775e3d98c8f1b72051dad0570a4dd1b5",
                "sha256:ad6e84c8b7042724c771153cba2467f5b25471f80576171fea90193ad228e7ff",
                "sha256:4847ab57c6bb95849ffea368cc8cbc14d4b1ce914fe5947221fa149b9258b11a"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
**Describe the results you expected:**
I want the "Cmd" Value is same

**Additional information you deem important (e.g. issue happens only occasionally):**
the docker build generated
 ```
"Cmd": [
                "./hello"
            ]
```
the docker-compose build generated
 ```
 "Cmd": null
```
**Output of `docker compose version`:**

```
Docker Compose version v2.4.1
```

**Output of `docker info`:**

```
docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.777GiB
 Name: localhost.localdomain
 ID: 3RBF:33N7:B5E5:D5DD:33TX:M2AH:3R33:ADGN:W4NY:AFV6:3GRT:FSOR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
CentOS Linux release 7.9.2009 (Core)

**Comment by rsent-ls** [comment] 2022-10-05 21:14
I had a similar issue with docker compose v2.10.2 and docker v19.03.6 on an Ubuntu 18.04 machine. Updating docker to v20.10.7 resolved the issue.

**Comment by laurazard** [comment] 2022-10-06 21:58
@PureLo can you check whether this issue is fixed with a recent version of Docker Compose?

**Comment by gfngoncalves** [comment] 2022-10-10 17:40
Observing the same issue here, on Docker v20.10.18, Docker Compose v2.11.2, Ubuntu v18.04.1.

**Comment by ndeloof** [comment] 2022-11-29 08:16
Please compare image built by `docker buildx build ...` which is used under the hood by Compose

**Comment by jhrotko** [comment] 2024-10-09 10:46
Just tested in v2.29.7 and the issue is solved

**Closed by jhrotko** 2024-10-09 10:46 UTC
