### ISSUE TITLE
Make nightly builds available

### ISSUE THREAD

**Issue by michaeljs1990** [docker/compose#2147] opened 2015-10-07 04:03 UTC
Possibly this is already done but I can't find anything about it. I tried running...

```
pip install https://github.com/docker/compose/archive/master.zip
```

But i get an odd error saying ImportError: No module named queue.

Anyway since this project on a weekly basis is merging in PRs that make my life significantly easier such as the recent addition of allowing multiple files with the -f flag I feel like it would be worthwhile to have a nightly available.

**Comment by dnephin** [comment] 2015-10-07 04:09
I think this issue is a duplicate of #1070 which is in progress.

However, I wouldn't expect the current master to be raising a queue error either. What OS and python version are you running?

If you extra the contents of master.zip and `pip install -r requirements.txt` does the error go away?

Thanks!

**Closed by dnephin** 2015-10-07 04:09 UTC
Labels: kind/question

**Comment by michaeljs1990** [comment] 2015-10-07 04:20
I am running on version osx 10.11 and when I try and pip install -r requirements.txt i get the error found in this post http://stackoverflow.com/questions/31900008/oserror-errno-1-operation-not-permitted-when-installing-scrapy-in-osx-10-11. I don't want to mess with that one much :-1: since i have a feeling i'm a few short rm commands away from messing up my system at that point... Really don't like mac sometimes.

**Comment by dnephin** [comment] 2015-10-07 04:21
So I'm guessing that's python3, but compose master should be working against python3.

Could you paste the whole stack trace? I'd like to find out why it's failing to install

**Comment by michaeljs1990** [comment] 2015-10-07 04:24
sure thing.

```
pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): docker-py==1.4.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): dockerpty==0.3.4 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): enum34==1.0.4 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): jsonschema==2.5.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): requests==2.7.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 7))
Collecting six==1.7.3 (from -r requirements.txt (line 8))
  Using cached six-1.7.3-py2.py3-none-any.whl
Collecting texttable==0.8.2 (from -r requirements.txt (line 9))
  Using cached texttable-0.8.2.tar.gz
Requirement already satisfied (use --upgrade to upgrade): websocket-client==0.32.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 10))
Installing collected packages: six, texttable
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/34/g33qnd6x0xl58l5v2k8502sh0000gn/T/pip-qd8uV7-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

Version
```
$ python --version
Python 2.7.10
```

**Comment by dnephin** [comment] 2015-10-07 04:33
That is helpful as well, but I was looking for the original ` ImportError: No module named queue.
ing for the origin ` ImportError: No module named queue` stack trace.

**Comment by michaeljs1990** [comment] 2015-10-07 04:34
sorry about that.

```
docker-compose version
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.0dev', 'console_scripts', 'docker-compose')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 20, in <module>
    from ..progress_stream import StreamOutputError
  File "/Library/Python/2.7/site-packages/compose/progress_stream.py", line 1, in <module>
    from compose import utils
  File "/Library/Python/2.7/site-packages/compose/utils.py", line 11, in <module>
    from six.moves.queue import Empty
ImportError: No module named queue
```

**Comment by dnephin** [comment] 2015-10-07 04:37
Ok, I think that is because the system package version of six is older and doesn't have this import.

Thanks!

If you're still looking for a way to install master before I get the automated build setup, I'd recommend https://virtualenv.pypa.io/

**Comment by michaeljs1990** [comment] 2015-10-07 04:41
@dnephin awesome I will get that setup for myself. Unfortunately I would also have to roll out that setup to about 10 other developers who already have enough complexity with all the tools we are using. virtualenv will be useful for getting PRs ready to merge in a few days before the official version is released. Can't wait till this 1.5 release :+1:

**Comment by schmunk42** [comment] 2017-09-24 20:26
Are there up-to-date nightly builds available?
I tried the links in https://github.com/docker/compose/issues/1070 - but they are outdated.
I am able to build from the repo, but I need compose in another Docker image and would like to use multi-stage builds ... therefore I created an automated build https://hub.docker.com/r/schmunk42/compose/builds/ - but I wonder if there's no official nightly or latest...
