### ISSUE TITLE
[BUG] Third container stuck on starting and HNS hangs on Windows Server 2022

### ISSUE THREAD

**Issue by mammadalius** [docker/compose#10383] opened 2023-03-19 22:53 UTC
### Description

Previously I had a Windows Server 2019 and I could start hundreds of containers without any issue. Now I'm trying to renew my environment with a Windows Server 2022 Datacenter.

I have 3 copies of docker-compose.ymls. Each has a exposed port as follows:

```
version: '3.8'
services:
  web:
    image: "mcr.microsoft.com/windows/nanoserver:ltsc2022"
    ports:
      - "4604:80"
    command: "ping 4.2.2.4 -t"
```

The exposed ports are different on each yml so there is no conflict.

First container starts, Second container start but when staring the THIRD container, the Host Network Service (HNS) comes up in TaskManager, taking 20-30% of CPU and container stuck on starting and nothing happens after this.

I tried several scenarios to reach the simplest way to reproduce this error. The key point is exposing ports on containers. Without exposing ports I can start multiple containers.

![Host Network Service (HNS) use CPU.](https://i.stack.imgur.com/XDyPR.png)

What is the difference between networking defaults in Windows Server 2019 and 2022?

Should I start some windows services on 2022?

**Comment by milas** [comment] 2023-03-23 14:56
To confirm, do you only see this behavior when using Compose?

If you launch containers via `docker run -p 1234:5678 ...`, do you see similar hangs?

**Comment by RETH666** [comment] 2023-03-28 12:36
@ndeloof  Yes, I can confirm that. If I run the containers with their ports with docker run, not a problem

**Comment by mariotomek** [comment] 2023-08-21 11:33
Hey!
I have got the same issue that I described here (I didn't found a similar bug here before): [github.com](https://github.com/docker/compose/issues/10895). So you can maybe link this bug with the one I entered.

I also describe the same issue on the [forums.docker.com](https://forums.docker.com/t/docker-compose-does-not-start-container-for-second-environment-on-host-windows-server-2022/137258) where is more information about it in the comments.

**Comment by valse** [comment] 2024-04-04 07:23
Hi, I have the same issue and I solved creating an external common network for both the compose configurations:

- first docker-compose.yml

```yaml
version: '3.4'
services:
  service1:
    ...
	ports:
      - "8440:80"
    networks:
      - mynet
  service2:
    ...
	ports:
      - "8441:80"
    networks:
      - mynet
  service3:
    ...
	ports:
      - "8442:80"
    networks:
      - mynet
networks:
  mynet:
    name: mycommonnet
    external: true
```

second docker-compose.yml
```yaml
version: '3.4'
services:
  service1:
    ...
	ports:
      - "8443:80"
    networks:
      - mynet
  service2:
    ...
	ports:
      - "8444:80"
    networks:
      - mynet
  service3:
    ...
	ports:
      - "8445:80"
    networks:
      - mynet
networks:
  mynet:
    name: mycommonnet
    external: true
```

The shared `network` is created by: 
`docker network create --driver nat mycommonnet`

**Comment by leojth** [comment] 2024-04-26 09:38
Hi,

I believe this error is caused by [issue #486 in Windows Containers](https://github.com/microsoft/Windows-Containers/issues/486).

It's a network issue in Windows Server 2022 rather than a Docker Compose issue.

Because it is rare to create networks without orchestrators like Docker Compose, it appears to be Docker Compose that is faulting when it's not.

Docker Compose creates a new network by default for each compose file you run. That's why the error appears when you start the third compose setup, or creating several networks in one compose setup. Spinning up multiple containers outside Docker Compose works because no networks are created.

See issue 486 in the link above how to reproduce this exact without Docker Compose.

**Comment by marceliwac** [comment] 2024-07-09 09:03
As @leojth mentioned, this is caused by an issue with Windows Containers. The most recent issue being tracked for the resolution is [microsoft/Windows-Containers #140](https://github.com/microsoft/Windows-Containers/issues/140). For me, a temporary workaround for usecases with only one network has been to customise the default network, rather than defining a new one under top-level `networks` in **docker-compose.yml**.

**Comment by ndeloof** [comment] 2024-07-09 09:08
ok then, closing this issue so you can watch progress made on https://github.com/microsoft/Windows-Containers to cover this usage

**Closed by ndeloof** 2024-07-09 09:08 UTC
Labels: kind/bug
