### ISSUE TITLE
Epic: Make Compose a Docker container

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#169] opened 2014-03-26 14:30 UTC
$ docker run compose up

**Update, 2015-03-10:** #619 is the first step towards this, but we still have to pass loads of options to `docker run` to make it work properly. Next step is figuring out if we can make any changes to Docker so we don't have to pass these options – e.g. some way of setting default options for an image, some way of passing the Docker socket through to the container, etc.

**Comment by dduportal** [comment] 2015-02-01 08:23
Ping @bfirsh :
https://github.com/docker/fig/issues/598

I provide since a bit of time this image : https://registry.hub.docker.com/u/dduportal/fig/ .
But the filesystem problem that @aanand spoke is a real struggle for beginners : i have this issue as concrete example : https://github.com/dduportal/dockerfiles/issues/4 .

Maybe the command that will run fig inside a container should try a big "/" mount in privileged mode, in order to get the docker host and container in sync ?

Don't we depend on the "docker -v" future (streaming from local client to daemon the files) ?
I propose to write a bit of doc if provided officially that way, forbidding relative path, or at least warning the user, what do you think ?

**Comment by dduportal** [comment] 2015-02-01 09:17
OK, some thoughts around that :
* Fig relative path resolving
If i understand well this function - https://github.com/docker/fig/blob/fd30920aac060b03d6e67ec5c3170f670a73d00e/compose/service.py#L590 - fig will just ask Python to resolve the full OS path, so locally.
* The struggle : fig should be running as close as possible as the host, in order to guarantee absolute file path homogeneity
* To illustrate : the wordpress example on the fig website only work if the absolute file path exists both on the docker client OS and the docker HOST. I tried to run the example on Mac OS with boot2docker :
  * From a folder which is inside /Users (auotmounted to /Users by boot2docker) => perfect
  * From another folder (like /tmp for reproducing), /code volume of the 'web' service will be empty because the folder doesn't exists in b2d filesystem

I'm thinking about that kind of thing :
* If running fig inside a container, providing a way to fig to know it
* Running that container, auto mounting the all / in /hostroot for example and use workdir to /figroot/$(pwd) :
```
docker run -w /figroot/$(pwd) -v /:/figroot -ti dduportal/fig up -d
```
* When in that case, fig will resolve the "external" path to /figroot/.....

This is a fig inside container solution, and the perfect solution will be with that https://github.com/docker/docker/issues/7249, but it doesn't seems very simple...

**Comment by thaJeztah** [comment] 2015-02-01 11:22
Looks like you need to rename your repository to `docker-compose` soon, Damien :)

**Comment by bfirsh** [comment] 2015-02-04 11:26
Also see https://github.com/docker/fig/pull/619

**Comment by josephpage** [comment] 2015-03-20 16:56
@dduportal  The solution for relative paths with dockerized docker-compose is :

```bash
alias docker-compose='docker run --rm -t \
	-v $(pwd):$(pwd) -w=$(pwd) \
	-v /var/run/docker.sock:/var/run/docker.sock \
	dduportal/docker-compose'
```

Inspired from https://github.com/docker/compose/blob/master/script/dev#L21

**Comment by dduportal** [comment] 2015-03-22 10:28
@thaJeztah @josephpage : Yep with the latest docker-compose, we have relative path enabling which make it easier ! Thank for pointing the relative solution.

**Comment by dnephin** [comment] 2015-08-07 02:31
PR with one option in #1806

**Closed** 2015-10-02 16:12 UTC
Labels: kind/epic
