### ISSUE TITLE
Support build --network

### ISSUE THREAD

**Issue by cjbottaro** [docker/compose#4665] opened 2017-03-23 20:50 UTC
`docker build` supports `--network` option (note, this is different from `docker run`'s `--net` option).

Request extending docker-compose yaml spec to include the following:
```yaml
build:
  context: .
  network: host
```

Thanks.

**Comment by czerasz** [comment] 2017-04-20 08:23
This is a really useful feature. Specially for Ruby environments. With this option one can use [Gemstash](https://github.com/bundler/gemstash) to cache the gems.

**Comment by ColinHebert** [comment] 2017-05-01 09:19
Duplicate of #4095

**Comment by gustavosbarreto** [comment] 2017-05-20 01:53
> This is a really useful feature. Specially for Ruby environments. With this option one can use Gemstash to cache the gems.

Also for "RUN npm install --registry http://my-private-repo" instruction with private npm repository.

**Comment by eyz** [comment] 2017-06-08 20:21
I could use this in our environment as well

**Closed** 2017-07-06 19:17 UTC
Labels: area/build, kind/feature, kind/parity
