### ISSUE TITLE
[BUG] Service "app" can't be used with `extends` as it declare `depends_on`

### ISSUE THREAD

**Issue by alireaza** [docker/compose#11568] opened 2024-03-02 08:22 UTC
### Description

After upgrading to version [v2.24.6](https://github.com/docker/compose/releases/tag/v2.24.6), when running docker compose up, I get the above error.

But by downgrading to [v2.24.5](https://github.com/docker/compose/releases/tag/v2.24.5), the problem was solved.

**Comment by mstyles** [comment] 2024-03-06 22:46
Duplicate of https://github.com/docker/compose/issues/11544

**Closed** 2024-04-19 12:01 UTC
Labels: kind/bug, status/0-triage
