### ISSUE TITLE
Command option -p don't set variable COMPOSE_PROJECT_NAME

### ISSUE THREAD

**Issue by achertov** [docker/compose#8143] opened 2021-02-20 15:28 UTC
**OS: linux
docker-compose version: 1.28.4**

I have option in docker-compose yaml file:

> hostname: ${COMPOSE_PROJECT_NAME}.userfront.local

I start stack with command:
`docker-compose -p DEMO up`

Container hostname is **.userfront.local**

With command `docker-compose -p DEMO config` I have message:

> WARNING: The COMPOSE_PROJECT_NAME variable is not set. Defaulting to a blank string.

**Comment by jonatanrs** [comment] 2021-02-23 18:35
Duplicate of ##8125

**Comment by thaJeztah** [comment] 2021-02-23 18:42
yes, looks like a duplicate of , which in itself is a duplicate of https://github.com/docker/compose/issues/2565 (which got merged into https://github.com/docker/compose/issues/2294)

**Closed by thaJeztah** 2021-02-23 18:42 UTC
Labels: kind/bug

**Comment by jonatanrs** [comment] 2021-02-23 19:07
> yes, looks like a duplicate of #8125, which in itself is a duplicate of #2565 (which got merged into #2294)

Right, I hadn't seen issue #2294.
It looks like the problem has not been solved yet.
