### ISSUE TITLE
One service failed to be started with the same name, and all services are in the created state ?

### ISSUE THREAD

**Issue by othersonlyme** [docker/compose#9851] opened 2022-09-16 03:20 UTC
![image](https://user-images.githubusercontent.com/55185255/190549750-219418d9-7a55-4452-aa5f-51dc370343b0.png)

**Comment by laurazard** [comment] 2022-09-16 14:09
Hi @othersonlyme, thanks for the report.

I'm closing this issue because there isn't any information for us to be able to dig into this. Please feel free to open another issue with more information, including which version of Docker Compose this is happening on, which version of Docker, OS, etc. Please fill out the template to look at what kind of information we'd like, and include a `compose.yaml`/which commands you ran so we can reproduce it.

**Closed by laurazard** 2022-09-16 14:09 UTC
