### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xd6' in position 36: ordinal not in range(128)

### ISSUE THREAD

**Issue by Serkan-devel** [docker/compose#4060] opened 2016-10-23 12:51 UTC
The full output was 

[patently@Porzellangardine cloud]$ docker-compose build
Building db
Step 1 : FROM armhf/alpine
 ---> 65e22dd58e7d
Step 2 : RUN apk add --upgrade --no-cache mysql
 ---> Running in fcdc74dce23e
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/armhf/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/armhf/APKINDEX.tar.gz
(1/12) Upgrading busybox (1.24.2-r9 -> 1.24.2-r11)
Executing busybox-1.24.2-r11.post-upgrade
(2/12) Upgrading libcrypto1.0 (1.0.2h-r1 -> 1.0.2j-r0)
(3/12) Upgrading libssl1.0 (1.0.2h-r1 -> 1.0.2j-r0)
(4/12) Installing mariadb-common (10.1.18-r0)
(5/12) Installing libaio (0.3.110-r0)
(6/12) Installing ncurses-terminfo-base (6.0-r7)
(7/12) Installing ncurses-terminfo (6.0-r7)
(8/12) Installing ncurses-libs (6.0-r7)
(9/12) Installing libgcc (5.3.0-r0)
(10/12) Installing libstdc++ (5.3.0-r0)
(11/12) Installing mariadb (10.1.18-r0)
Executing mariadb-10.1.18-r0.pre-install
(12/12) Installing mysql (10.1.18-r0)
Executing busybox-1.24.2-r11.trigger
OK: 130 MiB in 20 packages
 ---> 516bb3d389ad
Removing intermediate container fcdc74dce23e
Step 3 : ENV MYSQL_ROOT_PASSWORD [password]
 ---> Running in 15f44aa8ed62
 ---> 9b9a65d1bbba
Removing intermediate container 15f44aa8ed62
Step 4 : ENV MYSQL_USER [user]
 ---> Running in 24e5e54a89bf
 ---> 00a2dd260fd8
Removing intermediate container 24e5e54a89bf
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.8.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 62, in main
    command()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 114, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 220, in build
    force_rm=bool(options.get('--force-rm', False)))
  File "/usr/lib/python3.5/site-packages/compose/project.py", line 300, in build
    service.build(no_cache, pull, force_rm)
  File "/usr/lib/python3.5/site-packages/compose/service.py", line 731, in build
    all_events = stream_output(build_output, sys.stdout)
  File "/usr/lib/python3.5/site-packages/compose/progress_stream.py", line 23, in stream_output
    print_output_event(event, stream, is_terminal)
  File "/usr/lib/python3.5/site-packages/compose/progress_stream.py", line 91, in print_output_event
    stream.write("%s%s" % (event['stream'], terminator))
UnicodeEncodeError: 'ascii' codec can't encode character '\xd6' in position 36: ordinal not in range(128)
[patently@Porzellangardine cloud]$

on a raspberry pi 2 model b, arch linux, Docker version 1.12.2, build bb80604

**Comment by shin-** [comment] 2016-10-24 18:43
Which compose version? Can you try the [1.9.0 RC](https://github.com/docker/compose/releases/tag/1.9.0-rc1) and check if you still have the same issue?

**Comment by zajca** [comment] 2016-12-02 10:56
I have same problem with laradock workspace build
https://github.com/laradock/laradock/tree/master/workspace
when ```INSTALL_NODE=true```.

```
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.9.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 65, in main
    command()
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 117, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.5/site-packages/compose/cli/main.py", line 223, in build
    force_rm=bool(options.get('--force-rm', False)))
  File "/usr/lib/python3.5/site-packages/compose/project.py", line 300, in build
    service.build(no_cache, pull, force_rm)
  File "/usr/lib/python3.5/site-packages/compose/service.py", line 746, in build
    all_events = stream_output(build_output, sys.stdout)
  File "/usr/lib/python3.5/site-packages/compose/progress_stream.py", line 23, in stream_output
    print_output_event(event, stream, is_terminal)
  File "/usr/lib/python3.5/site-packages/compose/progress_stream.py", line 91, in print_output_event
    stream.write("%s%s" % (event['stream'], terminator))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 45-47: ordinal not in range(128)
```

```
docker-compose --version 
docker-compose version 1.9.0, build 2585387
```

```
docker --version
Docker version 1.12.3, build 6b644ec
```

**Comment by abmantis** [comment] 2017-02-14 23:33
I'm also having this problem on Raspbian with docker-compose 1.11.1 (installed with pip).

**Comment by LiranV** [comment] 2017-04-07 09:43
This issue is probably due to misconfigured system locale.
On a systemd box, the following should fix it (Use your preferred language UTF-8 locale variant):
`localectl set-locale LANG=en_US.UTF-8`

Check your distribution WIKI for more information about enabling specific locales.

**Comment by n0v3xx** [comment] 2017-11-07 09:56
?????????

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.8.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 61, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 110, in perform_command
    project = project_from_options('.', options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 35, in project_from_options
    environment=environment
  File "/usr/lib/python2.7/dist-packages/compose/cli/command.py", line 102, in get_project
    config_data = config.load(config_details)
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 319, in load
    service_dicts = load_services(config_details, main_file)
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 409, in load_services
    return build_services(service_config)
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 388, in build_services
    for name, service_dict in service_config.items()
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 381, in build_service
    config_details.environment)
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 658, in finalize_service
    normalize_build(service_dict, service_config.working_dir, environment)
  File "/usr/lib/python2.7/dist-packages/compose/config/config.py", line 883, in normalize_build
    resolve_build_args(build, environment)
  File "/usr/lib/python2.7/dist-packages/compose/utils.py", line 98, in build_string_dict
    return dict((k, str(v if v is not None else '')) for k, v in source_dict.items())
  File "/usr/lib/python2.7/dist-packages/compose/utils.py", line 98, in <genexpr>
    return dict((k, str(v if v is not None else '')) for k, v in source_dict.items())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 3: ordinal not in range(128)

**Comment by Yajo** [comment] 2018-02-07 09:19
Confirmed: just `export LANG=C.UTF-8` before running `docker-compose` and it works.

**Comment by MonsieurWave** [comment] 2018-02-08 14:05
Having the same issue 
`UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 34: ordinal not in range(128)`
on arch with docker-compose version 1.18.0

tried `export LANG=C.UTF-8` and `localectl set-locale LANG=en_US.UTF-8`, without success.
Any ideas?

**Comment by shin-** [comment] 2018-02-08 17:01
@MonsieurWave full stacktrace please?

**Comment by MonsieurWave** [comment] 2018-02-10 22:44
could not reproduce the issue
it is probably linked to the encoding used by python though
can also be fixed by setting `PYTHONIOENCODING = utf8`

**Comment by jpmelos** [comment] 2018-02-21 10:02
Having same issue:

```
$ docker-compose build --no-cache
db uses an image, skipping
queue uses an image, skipping
cache uses an image, skipping
beat uses an image, skipping
worker uses an image, skipping
Building web
Step 1/14 : FROM python:3.6.4
 ---> 336d482502ab
Traceback (most recent call last):
  File "/home/jpmelos/myvenv/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/home/jpmelos/myvenv/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/home/jpmelos/myvenv/lib/python3.6/site-packages/compose/cli/main.py", line 124, in perform_command
    handler(command, command_options)
  File "/home/jpmelos/myvenv/lib/python3.6/site-packages/compose/cli/main.py", line 254, in build
    build_args=build_args)
  File "/home/jpmelos/myvenv/lib/python3.6/site-packages/compose/project.py", line 372, in build
    service.build(no_cache, pull, force_rm, memory, build_args)
  File "/home/jpmelos/myvenv/lib/python3.6/site-packages/compose/service.py", line 994, in build
    all_events = stream_output(build_output, sys.stdout)
  File "/home/jpmelos/myvenv/lib/python3.6/site-packages/compose/progress_stream.py", line 23, in stream_output
    print_output_event(event, stream, is_terminal)
  File "/home/jpmelos/myvenv/lib/python3.6/site-packages/compose/progress_stream.py", line 90, in print_output_event
    stream.write("%s%s" % (event['stream'], terminator))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe3' in position 25: ordinal not in range(128)
```

Have not figure it out yet.

**Comment by shin-** [comment] 2018-02-21 17:34
@jpmelos what version of Compose is this?

**Comment by jpmelos** [comment] 2018-02-21 19:27
Hey, @shin-! It's the latest one, but the problem was not actually in Compose, as I found out. 😞 My terminal had the wrong `LC_TYPE` defined, and defining it correctly and creating the locale with `localedef` fixed the issue. (I don't quite understand the issue completely, but this worked.)

**Comment by shin-** [comment] 2018-03-29 00:27
Closing this now ; if someone witnesses a similar issue with 1.20.1 or above, please create a new issue.

**Closed by shin-** 2018-03-29 00:27 UTC

**Comment by tashrifbillah** [comment] 2020-11-25 15:48
`docker run --rm -e LANG=en_US.UTF-8 tbillah/pnlpipe` worked for me.
