### ISSUE TITLE
[cli] `up` command prints mal-formatted text

### ISSUE THREAD

**Issue by ofek** [docker/compose#5689] opened 2018-02-19 19:21 UTC
The logic to print `done` involves finding the right place using ansi codes. For some reason, this is not properly done because it appears to do this by writing over the previous line and not the line itself. This includes one's terminal session.

```
Ofek@Ofek-PC ~\Desktop $ docker-compose version
docker-compose version 1.18.0, build 8dd22a96
docker-py version: 2.6.1
CPython version: 2.7.14
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```

I captured the raw output to show what is happening.

See:

```
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:21:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> output = 'Creating desktop_nginx_1 ... \r\r\n\x1b[2A\x1b[2K\rCreating desktop_nginx_1 ... \x1b[32mdone\x1b[0m\r\x1b[2BCreating agent_nginx_stub_default ... \r\r\n\x1b[2A\x1b[2K\rCreating agent_nginx_stub_default ... \x1b[32mdone\x1b[0m\r\x1b[2B'                                                                     
>>>                                                                                                                                                            
>>> print(output)
```

and then:

```
Python 3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:21:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> output = 'Creating desktop_nginx_1 ... \r\r\n\x1b[2A\x1b[2K\rCreating desktop_nginx_1 ... \x1b[32mdone\x1b[0m\r\x1b[2BCreating agent_nginx_stub_default ... \r\r\n\x1b[2A\x1b[2K\rCreating agent_nginx_stub_default ... \x1b[32mdone\x1b[0m\r\x1b[2B'                                                                     
>>>                                                                                                                                                            
Creating desktop_nginx_1 ... done
Creating agent_nginx_stub_default ... done
Creating agent_nginx_stub_default ...

>>>
```

**Comment by ofek** [comment] 2018-02-19 20:39
I should also note that this doesn't happen with `kill`, `rm`, etc., only `up`.

**Comment by shin-** [comment] 2018-02-20 17:24
Duplicate of #5627

**Closed by shin-** 2018-02-20 17:24 UTC
