### ISSUE TITLE
Multiple compose files not working as per User Manual

### ISSUE THREAD

**Issue by leowmjw** [docker/compose#2812] opened 2016-02-03 17:14 UTC
As per manual, I am expecting that docker-compose.override.yml is ignored when specifying multiple compose files; however this is not what I observe:

```
To deploy with this production Compose file you can run

docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
This deploys all three services using the configuration in docker-compose.yml and docker-compose.prod.yml (but not the dev configuration in docker-compose.override.yml).
```

Relevant docker-compose.yml segment 

```
popit_ng:
  extends: 
    service: common
  build: .
  hostname: popit
  domainname: localdomain
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
    - elastic:elastic
  command: ./manage.py runserver 0.0.0.0:8000
```

and the app's (popit_ng) Dockerfile:

```
from django:python2

# Just make sure pip latest version so it does not complain
RUN pip install --upgrade pip 

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

# Copy all code over for production deployment
# Dev will use override to VOLUME mount local code 
COPY . /usr/src/app/

RUN pip install --no-cache-dir -r requirements.txt

# Any other extra software; put it here ...
# Below are some standard sysadmin tools I use
# Might want to add so can use ps auxwwf and less
RUN apt-get update && apt-get install -y \
        vim \
        htop \
        sysstat \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

EXPOSE 8000 

VOLUME "/usr/src/app"
```

My override files:

```
bash-3.2$ cat docker-compose.override.yml 
popit_ng:
#  volumes_from:
#    - data
  volumes:
    - .:/usr/src/app

bash-3.2$ cat docker-popit-test.yml 
postgres:
  environment:
    - POSTGRES_PASSWORD=123456
```
- **bash-3.2$ docker-compose -f docker-compose.yml -f docker-popit-test.yml up -d**
- **bash-3.2$ docker-compose run popit_ng /bin/bash** 
- Observe the file created from within the container is seen in the host.  This is contrary to the supposed behavior.

Docker + Compose Info:

```
bash-3.2$ docker --version
Docker version 1.9.1, build a34a1d5
bash-3.2$ docker-compose --version
docker-compose version 1.5.2, build 7240ff3
```

**Comment by dnephin** [comment] 2016-02-03 17:40
There is a bug here, but I think it is misleading. 

When you ran that `docker-compose -f ... -f ... up -d` command, was it after running a regular `docker-compose up -d` that included the `override.yml` ?

Compose [preserved volumes on recreate](https://docs.docker.com/compose/#preserve-volume-data-when-containers-are-created), so if you `up` again, it will recreate the containers, but copy the volumes.

I think the issue isn't actually that it's reading the `override.yml`, the problem is that host volumes are copied over on recreate. 

This was fixed in #2706 which will be in Compose 1.6.0 (it's not in an rc yet).

You can try it out with a master build from https://dl.bintray.com/docker-compose/master/

**Comment by leowmjw** [comment] 2016-02-04 06:45
@dnephin Does not seem to work with the latest docker-compose :( 

Yes, definitely I had run docker-compose (with override file first); as would be expected in a normal reasonable development workflow:

**bash-3.2$ ./my-docker-compose --version**
```
docker-compose version 1.6.0dev, build c81cc24
```

Before starting the test steps; I have ensured all the containers are stopped and removed.

**bash-3.2$ ./my-docker-compose stop**
```
Stopping popitng_popit_ng_1 ... done
Stopping popitng_postgres_1 ... done
Stopping popitng_elastic_1 ... done
```

**bash-3.2$ ./my-docker-compose rm**
```
Going to remove popitng_popit_ng_1, popitng_postgres_1, popitng_elastic_1, popitng_common_1
Are you sure? [yN] y
Removing popitng_popit_ng_1 ... done
Removing popitng_postgres_1 ... done
Removing popitng_elastic_1 ... done
Removing popitng_common_1 ... done
```

Steps:
- Create a file in the host; called fileA

- Run without the override file; so content including fileA is copied into the container. [**./my-docker-compose -f docker-compose.yml -f docker-popit-test.yml up -d**]

- Exec into the container; rm fileA [**./my-docker-compose run popit_ng /bin/bash**]

- Observe that out in the host file; fileA is also removed! The expectation is that since the files are copied over; it should no longer be linked to the host volume.

**Comment by dnephin** [comment] 2016-02-04 18:57
Ok, my manual testing does show that override is ignored when using `-f` so I think the issue is related to volumes.  Could you include the output of `docker inspect popit_ng_1` (at least the `Mounts` and `Binds` sections) ?

**Comment by leowmjw** [comment] 2016-02-05 08:42
@dnephin Here is the full output (without the override).  Further down I ran through the whole process from scratch again and captured the requested segments.  Hope it helps!
```
bash-3.2$ docker inspect popitng_popit_ng_1
[
{
    "Id": "35940b6bfbf6f56c635721280bad7548dfa622f7a394d90c7292860b5cea3c72",
    "Created": "2016-02-05T08:00:41.452244805Z",
    "Path": "./manage.py",
    "Args": [
        "runserver",
        "0.0.0.0:8000"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 1251,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2016-02-05T08:00:49.653165205Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "bda98e41d3ecf666dbec5e25feb5a019885c2788ff7ea1cb50a3c97bbfcc3bac",
    "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/35940b6bfbf6f56c635721280bad7548dfa622f7a394d90c7292860b5cea3c72/resolv.conf",
    "HostnamePath": "/mnt/sda1/var/lib/docker/containers/35940b6bfbf6f56c635721280bad7548dfa622f7a394d90c7292860b5cea3c72/hostname",
    "HostsPath": "/mnt/sda1/var/lib/docker/containers/35940b6bfbf6f56c635721280bad7548dfa622f7a394d90c7292860b5cea3c72/hosts",
    "LogPath": "/mnt/sda1/var/lib/docker/containers/35940b6bfbf6f56c635721280bad7548dfa622f7a394d90c7292860b5cea3c72/35940b6bfbf6f56c635721280bad7548dfa622f7a394d90c7292860b5cea3c72-json.log",
    "Name": "/popitng_popit_ng_1",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "8000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8000"
                }
            ]
        },
        "Links": [
            "/popitng_elastic_1:/popitng_popit_ng_1/elastic",
            "/popitng_elastic_1:/popitng_popit_ng_1/elastic_1",
            "/popitng_elastic_1:/popitng_popit_ng_1/popitng_elastic_1",
            "/popitng_postgres_1:/popitng_popit_ng_1/popitng_postgres_1",
            "/popitng_postgres_1:/popitng_popit_ng_1/postgres",
            "/popitng_postgres_1:/popitng_popit_ng_1/postgres_1"
        ],
        "PublishAllPorts": false,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": [],
        "Devices": null,
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Name": "95279b69adbc41420007a2ac737ceb0bc9a9f014cb7aab28ad86cbeb39821975",
            "Source": "/mnt/sda1/var/lib/docker/volumes/95279b69adbc41420007a2ac737ceb0bc9a9f014cb7aab28ad86cbeb39821975/_data",
            "Destination": "/usr/src/app",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "popit",
        "Domainname": "localdomain",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "8000/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "POSTGRES_PASSWORD=passw0rd",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "GPG_KEY=C01E1CAD5EA2C4F0B8E3571504C367C218ADD4FF",
            "PYTHON_VERSION=2.7.11",
            "PYTHON_PIP_VERSION=7.1.2",
            "DJANGO_VERSION=1.9.2"
        ],
        "Cmd": [
            "./manage.py",
            "runserver",
            "0.0.0.0:8000"
        ],
        "Image": "popitng_popit_ng",
        "Volumes": {
            "/usr/src/app": {}
        },
        "WorkingDir": "/usr/src/app",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {
            "com.docker.compose.config-hash": "1640c37daa4bc5fbd217b3d8deacaf5e4dff77bf150a7672f21ab104085c0437",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "popitng",
            "com.docker.compose.service": "popit_ng",
            "com.docker.compose.version": "1.6.0dev"
        }
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "bdbf7ebea4929d8cfd243c1b67041cd2f0f3fc8a98c569778bea070f1024249e",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "8000/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "8000"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/bdbf7ebea492",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "757c76cfc90a805e5270ac5d55f37b191fa62f42a446afb8175648ade93847d0",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.4",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "MacAddress": "02:42:ac:11:00:04",
        "Networks": {
            "bridge": {
                "EndpointID": "757c76cfc90a805e5270ac5d55f37b191fa62f42a446afb8175648ade93847d0",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.4",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:04"
            }
        }
    }
}
]
```

For data point; ran the whole process again:

**Step 1: start up docker-compose as per default:**
```
bash-3.2$ docker inspect popitng_popit_ng_1 | grep -A 10 -B 2 Bind
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/Users/leow/Desktop/PROJECTS/SINARPROJECT/POPIT-DOCKER/CODE/popit_ng:/usr/src/app:rw"
        ],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
--
--
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "8000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8000"
                }
            ]
        },
        "Links": [
            "/popitng_elastic_1:/popitng_popit_ng_1/elastic",
            "/popitng_elastic_1:/popitng_popit_ng_1/elastic_1",
bash-3.2$ 
bash-3.2$ 
bash-3.2$ docker inspect popitng_popit_ng_1 | grep -A 10 -B 2 Mounts
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/Users/leow/Desktop/PROJECTS/SINARPROJECT/POPIT-DOCKER/CODE/popit_ng",
            "Destination": "/usr/src/app",
            "Mode": "rw",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "popit",
        "Domainname": "localdomain",
```

**Step 2: Stopped and run without the override:**
```
bash-3.2$ docker inspect popitng_popit_ng_1 | grep -A 10 -B 2 Bind
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
--
--
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "8000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8000"
                }
            ]
        },
        "Links": [
            "/popitng_elastic_1:/popitng_popit_ng_1/elastic_1",
            "/popitng_elastic_1:/popitng_popit_ng_1/popitng_elastic_1",
bash-3.2$ 
bash-3.2$ 
bash-3.2$ docker inspect popitng_popit_ng_1 | grep -A 10 -B 2 Mounts
        "Data": null
    },
    "Mounts": [
        {
            "Name": "fc0e40f44cd6414a6b6a191bab70556e3d9435db3c217878abe9a464cc85ea58",
            "Source": "/mnt/sda1/var/lib/docker/volumes/fc0e40f44cd6414a6b6a191bab70556e3d9435db3c217878abe9a464cc85ea58/_data",
            "Destination": "/usr/src/app",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {

```

**Step 3: Confirmed that modifying file inside container is reflected in host; even though it should be isolated**

**Step 4: Repeat step with the containers stopped first (same result)**
```
bash-3.2$ ./my-docker-compose stop
Stopping popitng_popit_ng_1 ... done
Stopping popitng_postgres_1 ... done
Stopping popitng_elastic_1 ... done
bash-3.2$ ./my-docker-compose rm
Going to remove popitng_popit_ng_1, popitng_postgres_1, popitng_elastic_1, popitng_common_1
Are you sure? [yN] y
Removing popitng_popit_ng_1 ... done
Removing popitng_postgres_1 ... done
Removing popitng_elastic_1 ... done
Removing popitng_common_1 ... done
bash-3.2$ vim BOB
bash-3.2$ cat BOB 
Test is inside
bash-3.2$ ./my-docker-compose -f docker-compose.yml -f docker-popit-test.yml up -d
Creating popitng_common_1
Creating popitng_elastic_1
Creating popitng_postgres_1
Creating popitng_popit_ng_1
bash-3.2$ ./my-docker-compose run --rm popit_ng /bin/bash
root@popit:/usr/src/app# rm BOB 
root@popit:/usr/src/app# exit
exit
bash-3.2$ ls BOB
ls: BOB: No such file or directory
bash-3.2$ 
bash-3.2$ docker inspect popitng_popit_ng_1 | grep -A 10 -B 2 Bind
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [],
        "ContainerIDFile": "",
        "LxcConf": null,
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
--
--
        "MemorySwappiness": null,
        "Privileged": false,
        "PortBindings": {
            "8000/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "8000"
                }
            ]
        },
        "Links": [
            "/popitng_postgres_1:/popitng_popit_ng_1/postgres_1",
            "/popitng_elastic_1:/popitng_popit_ng_1/elastic",
bash-3.2$ 
bash-3.2$ docker inspect popitng_popit_ng_1 | grep -A 10 -B 2 Mounts
        "Data": null
    },
    "Mounts": [
        {
            "Name": "11ee6000c875035c5eebb2fe670bdd2afe5bc1cc7372d4378099d196d0376617",
            "Source": "/mnt/sda1/var/lib/docker/volumes/11ee6000c875035c5eebb2fe670bdd2afe5bc1cc7372d4378099d196d0376617/_data",
            "Destination": "/usr/src/app",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
```

**Comment by aanand** [comment] 2016-02-05 12:13
It looks like your `docker-compose run` command (`./my-docker-compose run popit_ng /bin/bash`) omits the `-f` arguments; this causes it to use the override file and means that the one-off container will be created with the volume binding specified there.

From your description of that step as "Exec into the container", it sounds like you expected it to perform the equivalent of a `docker exec` into the already-running container, but that's not the case. `docker-compose run` is like `docker run` - it creates a new container.

If you run this command, the host directory should not be mounted:

    ./my-docker-compose -f docker-compose.yml -f docker-popit-test.yml run popit_ng /bin/bash

**Closed** 2018-11-06 21:57 UTC
Labels: area/volumes
