### ISSUE TITLE
docker-compose bundle warnings

### ISSUE THREAD

**Issue by mavencode01** [docker/compose#3680] opened 2016-07-03 10:34 UTC
I'm trying out the `docker-compose bundle` command but am getting some bunch of WARNINGS below:

WARNING: Unsupported key 'container_name' in services.master - ignoring
WARNING: Unsupported key 'volumes_from' in services.config - ignoring
WARNING: Unsupported key 'volumes' in services.config - ignoring
WARNING: Unsupported key 'container_name' in services.config - ignoring
WARNING: Unsupported key 'links' in services.keycloak - ignoring

Now, when I deploy the generated bundle, the services / containers doesn't work and I feel the WARNINGS are kind of errors that my docker-compose file isn't compatible with the new bundle file requirements. I can fix the warnings on container_name, but not sure how I would fix the warnings on volume_from, volumes and  links in my compose file.

How do I fix the warning message and Is there any sort of reference for the new `docker-compose bundle` command ?

Here is my docker-compose file:

```
version: "2"

services:

  master:
    container_name: "citus_master"
    image: "citusdata/citus:5.1.0"
    ports: 
    - "5432:5432"
    labels: 
    - "com.citusdata.role=Master"

  worker:
    image: "citusdata/citus:5.1.0"
    ports: 
    - "5433:5432"
    labels: 
    - "com.citusdata.role=Worker"

  config:
    container_name: "citus_config"
    image: "citusdata/workerlist-gen:0.9.0"
    volumes: 
    - "/var/run/docker.sock:/tmp/docker.sock"
    volumes_from: 
    - "master"

  keycloak:
    image: "jboss/keycloak-postgres"
    links: 
    - "master:postgres"
    ports: 
    - "8080:8080"
    environment: 
    - KEYCLOAK_USER=admin 
    - KEYCLOAK_PASSWORD=password 
    - POSTGRES_DATABASE=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_PORT_5432_TCP_ADDR=postgres
    - POSTGRES_PORT_5432_TCP_PORT=5432

  pgweb:
    image: "sosedoff/pgweb"
    ports: 
    - "8081:8081"
```

**Comment by johnharris85** [comment] 2016-07-04 03:45
Bundles are still experimental right now. They are intended to represent 'portable' deployable services. I don't know, but my guess is that those things won't be supported as they are things that tend to tie containers to either a specific host or a specific number of instances or a specific topology.

'container_name' - Only really works for one instance
'volumes_from' - Not portable / topology-specific
'volumes' - Only one that makes sense to include, named volumes using some distributed storage driver (flocker etc...)
'links' - Are deprecated, docker native networking supersedes this.

**Comment by mavencode01** [comment] 2016-07-04 12:55
@johnharris85 thanks!

**Comment by rayjohnson** [comment] 2016-08-03 16:21
Bummed that volumes is missing.  Makes it not useable for a good 1/3 of our current apps.  Would also like to see it support the new global swarm mode.  (Think deploying something like cadvisor or other monitoring stacks.)

**Comment by RRAlex** [comment] 2016-08-16 15:43
It seems like pretty much everything is missing right now (especially security configurations!), at least on our docker-compose.yml :
```
aliases
cap_add
cap_drop
container_name
cpu_shares
depends_on
ipv4_address
links
mem_limit
networks
read_only
restart
volumes
``
So I'm really not sure how one is supposed to use docker swarm in practice except for launching a single service by hand.
Has anyone seen a complex example working? Or more importantly, are all the arguments to `docker run` being ported to `docker services`?

**Comment by Vanuan** [comment] 2016-08-31 03:09
It looks like volumes are supported in `docker service create` (though with some new syntax, `--mount`).

But how does it work exactly? Do I have to use some global/network filesystem? Or consistency is not important? Or docker should support replicated filesystem itself? Or docker would just error out when I try to scale service with volumes? How does it move to another host if it goes down?

These questions need to be answered before we expect `docker-compose bundle` to magically work with volumes.

**Comment by Vanuan** [comment] 2016-08-31 06:03
Here's some interesting discussion: https://forums.docker.com/t/docker-1-12-swarm-storage-options-with-dab-distributed-application-bundles-on-gce/16204/3

**Comment by Vanuan** [comment] 2016-08-31 06:27
Also related to https://github.com/docker/docker/issues/24089

**Comment by RRAlex** [comment] 2016-11-16 20:00
Has anyone seen a Roadmap showing from which future version will the bundle feature actually become usable fully?

... so people can migrate to pure swarm setup, including all the security options.

**Comment by jamshid** [comment] 2017-02-07 20:15
Found this issue because I'm also unable to use docker compose and swarm to deploy containers that require systemd. 

```
Ignoring unsupported options: cap_add, devices, privileged, security_opt, tmpfs
```
When will stack/bundle/dab/whatever support systemd containers, which require `cap_add` and `tmpfs`? 

Ref https://github.com/docker/docker/issues/28614#issuecomment-261724902
```
    cap_add:
      - SYS_ADMIN
    tmpfs: /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - container=docker
```

PS: `devices` would also be very useful especially if the value could somehow be made specific on each swarm node.

**Comment by ntwrkguru** [comment] 2018-01-10 20:06
So, swarm-mode strips functionality that was present using docker-compose and, while swarm-mode supports compose files, it ignores most of what makes one use compose files in the first place. I love Docker, I really do, but swarm-mode is a complete regression.

**Comment by shin-** [comment] 2018-03-28 21:54
I don't think we'll do any more work on the bundles / DAB format at this point. `docker stack` / v3 is the logical continuation of that effort.

> So, swarm-mode strips functionality that was present using docker-compose and, while swarm-mode supports compose files, it ignores most of what makes one use compose files in the first place. I love Docker, I really do, but swarm-mode is a complete regression.

A lot of the options that were removed in v3 aren't applicable to distributed environments (clusters). Other things are a work in progress (happening here: https://github.com/docker/swarmkit)

**Closed by shin-** 2018-03-28 21:54 UTC

**Comment by ntwrkguru** [comment] 2018-03-28 22:39
I respectfully disagree 100%. The missing piece is that things aren’t fully shared across the swarm. Docker Hub credentials, cached images, etc. Further, how are things like env files and builds not applicable to a distributed environment? But, in the end, swarm-mode is dead anyway, so it really doesn’t matter much, does it?

**Comment by shin-** [comment] 2018-03-28 23:09
> The missing piece is that things aren’t fully shared across the swarm. Docker Hub credentials,

Not sure what that specific piece has to do with Compose. It's also a one-time setup thing.

> cached images, etc.

You mean pulled images? Ideally I agree this would be handled. Pretty sure it's covered under the "work in progress" clause.

> Further, how are things like env files 

??? https://docs.docker.com/compose/compose-file/#env_file

> and builds not applicable to a distributed environment?

If node A goes down and node F goes up to replace it and needs to start a task for service X, it's unlikely it'll have the files to build the underlying image. It makes sense that services would instead rely on pullable images.

> But, in the end, swarm-mode is dead anyway, so it really doesn’t matter much, does it?

k

**Comment by ntwrkguru** [comment] 2018-03-29 02:28
> Not sure what that specific piece has to do with Compose. It's also a one-time setup thing.

You closed this as development has been moved to swarmkit, ergo I brought it up. Anyway, credentials are not necessarily a one-time thing and, even then, that has nothing to do with all swarm members not having access to the credentials. Basically, it shouldn't be required to pass `--with-registry-auth`...it's pointless and should be done automatically given that any workload can run on any node. Besides, shouldn't swarm managers hold the credentials and pass them as needed? Granted, ths has more to do with the awful way in which docker engine manages Hub credentials, but it's still something that should be fixed.


> Further, how are things like env files

Env file parsing and var substitution/interpolation are not handled when using swarm...which *IS* a function of compose.

> If node A goes down and node F goes up to replace it and needs to start a task for service X, it's unlikely it'll have the files to build the underlying image. It makes sense that services would instead rely on pullable images.

You store the built image and make it available to all nodes. How does that not make sense. The simple fact is that, if I'm using swarm-mode, I MUST have some external registry, somewhere. It adds layers of complexity and dependencies that shouldn't be needed.

> k

And yes, Kubernetes won this war, unfortunately. Swarm was much simpler for smaller deployments, but it's mired in slow progress and was probably rolled out before it should have been. Progress is slow as the project has gotten larger. Feature velocity has increased, but the features seem to be missing the mark for a pretty large chunk of the user base.

Lastly, the fact that full compose functionality is not supported in swarm-mode, combined with the lack of DAB development, and the fact that over a year has gone by and there's still no good way to deploy stacks in an automated fashion severely limits the usefulness of this in a production environment. 

I don't have the answers, and not even sure if anyone cares, but look at the Slack channel and Github you'll see just how disappointed many users are with the current state.
