### ISSUE TITLE
Rules about variables in env files

### ISSUE THREAD

**Issue by bewareilive** [docker/compose#9890] opened 2022-09-30 03:12 UTC
For example :
```
#.env
spring.cloud.consul.config.acl-token=dsafoi8fsdf78g8asf789
```
_unexpected character "-"(or . ) in variable name near_ 

I can't use "." in version 2.6.0 and "-" cannot be used in version 2.11.2.

I have many services and the same environment variables. So I want to use only .env files without setting yml's environment.No problem with 1.29.2

I want to know the variable rules, and the solution to this problem.

**Comment by glours** [comment] 2022-09-30 06:27
duplicate of #9570

**Closed by glours** 2022-09-30 06:27 UTC
