### ISSUE TITLE
json-file logs are not valid JSON

### ISSUE THREAD

**Issue by Ry7n** [docker/compose#2156] opened 2015-10-08 03:22 UTC
This is probably working as intended, but using `docker-compose logs` turns out output that isn't valid JSON, e.g.:

```
nginx | 2010/08/23 15:25:35 [error] This is some random log "with quotes".
app_1 | { "msg": "Hello world" }
app_2 | { "msg": "Hello as well" }
```

This means that my JSON log entries can't be piped to JQ, and I can't use Amazon's [CloudWatch Logs  Filters](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/FilterAndPatternSyntax.html). I'd love if docker-compose allowed me to tweak this so I could have a docker-compose.yml like:

``` yml
nginx:
  # the default
  log_format: text
app_1:
  log_format: json
app_2:
  log_format: json
```

And be be able to do something like:

``` bash
$ docker-compose logs --json
{ "docker": "nginx", "log": "This is some random log \"with quotes\"." }
{ "docker": "app_1", "log": { "msg": "Hello world" } }
{ "docker": "app_2", "log": { "msg": "Hello as well" } }
```

I'm fine if docker-compose trusts that logs I say are JSON actually are valid JSON. From the look of things, that wouldn't be a terrifically challenging pull request, if you'd entertain it.

**Comment by thaJeztah** [comment] 2015-10-08 11:17
I think it's not really recommended to use the output of docker-compose logs for actual production. In addition, the default (json) logging driver used in Docker is not very efficient for high-volume logging.

Docker now supports logging drivers, that allow you to send logs to, for example, fluentd or journald. A new driver was just added, which directly sends container-logs to Amazon CloudWatch; https://github.com/docker/docker/blob/master/docs/reference/logging/awslogs.md; this driver will be part of the docker 1.9 release

**Comment by chiefy** [comment] 2015-10-08 13:28
@thaJeztah the issue is that the [new logging drivers don't currently work with compose](https://github.com/docker/compose/issues/1869). #1869 So as of right now you're pretty much stuck with syslog or json.

**Comment by thaJeztah** [comment] 2015-10-08 13:31
@chiefy ah, you're right, it's not released yet.
I saw that work is in progress to publish "master" builds, so in case you want to *try*; that might be possible soon: https://github.com/docker/compose/pull/2154

**Comment by ijc** [comment] 2019-03-27 13:26
Issue grooming: Closing, I believe log drivers are now supported [docs](https://docs.docker.com/compose/compose-file/compose-file-v2/#logging).

**Closed by ijc** 2019-03-27 13:26 UTC
Labels: area/logs, kind/feature
