### ISSUE TITLE
v2.3.0+: `docker-compose build` fails on linux if Dockerfile not in context directory

### ISSUE THREAD

**Issue by rfay** [docker/compose#9277] opened 2022-03-11 18:35 UTC
**Description**

On Linux with 
* docker-compose v2.3.0+
* A docker-compose.yaml with Dockerfile and context in different directories

`docker-compose build` will fail with 
`* Error response from daemon: dockerfile parse error line 1: unknown instruction: .DOCKERIGNORE` 

This doesn't happen before compose v2.3.0- and it doesn't seem to happen on macOS in Docker Desktop 4.5.0 or Colima.

**Steps to reproduce the issue:**

I've prepared a demo repo to show this, it's super easy, https://github.com/rfay/dcbug - just check it out and follow the README. 

`docker-compose -f docker-compose-bad.yaml build` will show the problem on Linux with compose v2.3.3

The demonstration setup is exactly the one in the spec: https://github.com/compose-spec/compose-spec/blob/master/build.md#illustrative-sample

**Describe the results you received:**

https://github.com/rfay/dcbug#readme shows both actual and expected. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
2.3.3
```

**Output of `docker info`:**

```
parallels@ubuntu-20-04-arm64:~/workspace/dcbug$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 48
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-66-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 1.934GiB
 Name: ubuntu-20-04-arm64
 ID: IHLF:K6KY:DXXR:RCTK:IRUY:S5M6:4ZWL:RRQP:FHCO:N6ZR:GURE:YTFG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: randyfay
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details:**

Happens on multiple amd64 and arm64 linux machines with same docker server version as current docker desktop. (20.10.12)

**Comment by ndeloof** [comment] 2022-12-16 11:57
Tested on latest release, and can't reproduce with https://github.com/rfay/dcbug, so I assume this has been fixed in the meantime. Feel free to comment/open a follow-up issue if some similar error happens

**Closed by ndeloof** 2022-12-16 11:57 UTC
