### ISSUE TITLE
Specify unrunnable service

### ISSUE THREAD

**Issue by jylin** [docker/compose#3684] opened 2016-07-04 14:10 UTC
Supposed I have a docker-compose.yml file like this:

```
version: '2'
services:
        base:
                build: ./base
                image: my-base
        service:
                container_name: my-service
                build: ./service
                image: my-service
                ports:
                        - 80:80
```

I mainly keep the "base" target in my compose file as a convenient way to build everything. In other words, I'm sort of using docker-compose.yml as a Makefile. This way I can just do `docker-compose up --build` to rebuild and re-run everything. However, the base image doesn't have an entrypoint, so if you run it, then it will quit right away. It would be nice if there were some way to specify that a service is not runnable so that compose doesn't even try to start it.

**Comment by dnephin** [comment] 2016-07-04 16:39
Duplicate of #1294

docker-compose is not designed to be a replacement for a Makefile.

**Closed by dnephin** 2016-07-04 16:39 UTC

**Comment by dnephin** [comment] 2016-07-27 01:33
If you're still interested in a "makefile" like tool that uses containers you should check out https://dnephin.github.io/dobi/. It's designed for exactly this use case.
