### ISSUE TITLE
Project name behavior 2.3.0 regression (`no such project: <project name>`)

### ISSUE THREAD

**Issue by nocive** [docker/compose#9239] opened 2022-03-07 13:20 UTC
**Description**

An otherwise working project under compose 2.2.3 now throws `no such project: <project name>` errors.

The only thing special about this project is that it uses `COMPOSE_PROJECT_NAME` environment variable to define the project name. Unsetting the environment variable results in a warning + the same error:

```
WARN[0000] The "COMPOSE_PROJECT_NAME" variable is not set. Defaulting to a blank string. 
no such project: <project name>
```

I suspect the error happens when trying to remove a container that is not created with `docker compose rm` (this was fine to do with all previous versions) due to this line https://github.com/docker/compose/pull/9148/files#diff-5dabf34848ad18b1b30364b2fd814b7678dbcc4d398227392578ef8266b0ac67R103.

**Comment by glours** [comment] 2022-03-07 13:24
duplicate of #9234
A new release is coming soon

**Closed by glours** 2022-03-07 13:24 UTC

**Comment by glours** [comment] 2022-03-07 13:27
No worries, it's because this issue is already fixed and closed, we're currently doing some check and will do a fix release if everything is ok

**Comment by glours** [comment] 2022-03-07 16:13
release with the fix available https://github.com/docker/compose/releases/tag/v2.3.1
