### ISSUE TITLE
Since docker 1.3.0 / fig 1.0.0 volumes are not mounted when fig up'ing existing containers

### ISSUE THREAD

**Issue by morvans** [docker/compose#622] opened 2014-11-06 14:47 UTC
Since docker 1.3.0 / fig 1.0.0 (I upgraded both at the same time), I cannot fig up my projects without fig rm'ing before.

If I do fig up on already existing (stopper) containers, volumes specified in fig.yml aren't remounted (default docker mounts instead, so empty dirs).

fig rm && fig up recreates everything correctly but for locally built containers this is pretty time consuming.

**Comment by dreamcat4** [comment] 2015-01-04 22:54
Same experience as @gquemener here:  docker 1.4.1 + fig 1.0.1. adding host volumes does not work unless i do a 'fig rm' first. Not so-sure what happens on restarts. #723

**Comment by dmp1ce** [comment] 2015-01-07 23:16
I also experienced the same thing.  For one of my containers the 'fig up' would not mount host volumes.  However it would mount if I used 'fig run --rm mycontainer bash'.  Running 'fig rm mycontainer' fixed it.

**Comment by budjizu** [comment] 2015-01-29 07:45
Same issue: docker 1.4.1 + docker-compose 1.1.0-rc1. Fixed it to run 'docker rm container' before 'docker-compose up'

**Comment by jgillich** [comment] 2015-02-06 12:04
+1, I just wasted a lot of time on this.
```
Docker version 1.3.2, build 39fa2fa/1.3.2
fig 1.0.1
CentOS Linux release 7.0.1406 (Core)
```

**Comment by nomadster** [comment] 2015-02-06 12:38
+1 This features actually makes docker+fig a tool to make a deploy in just two days :)

`
Docker version 1.3.2, build 39fa2fa/1.3.2
fig 1.0.1
CentOS Linux release 7.0.1406 (Core)
`

**Comment by ddliu** [comment] 2015-02-11 09:47
+1

```
fig 1.0.1
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

**Comment by aanand** [comment] 2015-02-11 14:10
Can anyone produce a minimal failing case? I'm currently unable to reproduce. Here's my test case:

```
$ cat docker-compose.yml
test:
  image: busybox
  command: cat /data/hello.txt
  volumes:
    - ./data:/data

$ docker-compose --version
docker-compose --version

$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

$ docker-compose rm --force
$ mkdir -p data
$ echo "hello world" > data/hello.txt

$ docker-compose up
Creating 622_test_1...
Attaching to 622_test_1
test_1 | hello world
622_test_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)

$ docker inspect -f '{{.Volumes}}' 622_test_1
map[/data:/Users/aanand/work/docker/compose-bugs/622/data]

$ docker-compose up
Recreating 622_test_1...
Attaching to 622_test_1
test_1 | hello world
622_test_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)

$ docker inspect -f '{{.Volumes}}' 622_test_1
map[/data:/Users/aanand/work/docker/compose-bugs/622/data]
```

**Comment by cpuguy83** [comment] 2015-02-11 14:28
@aanand 1.5 has some fixes in it that would resolve this, and maybe one more in 1.5.1 for some fig users.

**Comment by dnephin** [comment] 2015-02-11 15:37
I suspect (based on the early comments on this thread, and my personal experience helping people new to fig) that this is often an issue with copying old volumes during `fig up` instead of creating things from scratch.

If you have an existing container with data volumes, and you change the content of those volumes, when you `fig up`, you'll still get the old data, which makes it seem like the volume is not mounted.  The workaround of `fig rm` seems to have worked for a few people.

I think #858 helps with this. 

There is still a case where the volume path hasn't changed but the contents or structure of the data volume have changed.  That one is harder to deal with and maybe just needs to be called out better in the docs.

**Comment by nomadster** [comment] 2015-02-11 15:51
@dnephin it's not my case.
fig stop && fig up 

doesn't mount the volume. If i go to the volume i don't have *any* data at all.

**Comment by dnephin** [comment] 2015-02-11 15:53
@nomadster can you `docker inspect <container name>` and include a link to a pastebin with the output?  

`fig stop && fig up` is actually what I described, what if you `fig stop; fig rm --force; fig up` (this will remove data volume containers).

**Comment by nomadster** [comment] 2015-02-11 15:55
Cannot reproduce right now, I've switched to docker 1.1.2 and fig 0.5.2 to be able to work :)

**Comment by morvans** [comment] 2015-02-13 15:42
@aanand, I've got a scenario with fig where volumes aren't re-mounted correctly upon fig up when docker daemon has been restarted between stop/kill and up. I can provide you (privately preferably) the full log with docker inspect outputs. It forces me to fig rm my containers every morning after booting my workstation (event if containers where "gracefully" fig-stopped before the reboot or docker daemon restart)

**Comment by aanand** [comment] 2015-02-13 17:35
@morvans Does the problem *only* surface when the docker daemon has been restarted? If so, that's a separate issue, and it's worth investigating whether that behaviour can be reproduced using Docker without Fig.

Can you produce a failing case with private information stripped out?

**Comment by morvans** [comment] 2015-02-13 17:41
Ok I'll try to get back to you with a stripped down fig.yml and/or a test case involving docker alone.

**Comment by saritasa** [comment] 2015-02-13 22:41
I can't mount relative folder through fig on centos7:

[root@localhost using-fig]# uname -a
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost fig-master]# fig --version
fig 1.0.1

[root@localhost fig-master]# docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
[root@localhost fig-master]# 

fig.yml:

/home/apps/using-fig/fig.yml
es:
    image: library/elasticsearch:1.4.3
    volumes:
        - elasticsearch:/data
    ports:
        - "9200:9200"
        - "9300:9300"


[root@localhost using-fig]# pwd
/home/apps/using-fig

[root@localhost using-fig]# ls -l
total 4
drwxr-xr-x. 3 root root  41 Feb 13 17:30 elasticsearch
-rwxr-xr-x. 1 root root 141 Feb 13 17:16 fig.yml
drwxr-xr-x. 2 root root  59 Feb 13 15:32 web
[root@localhost using-fig]# ls -l elasticsearch/
total 4
drwxrwxrwx. 2 root root  6 Feb 13 16:59 data
-rwxr-xr-x. 1 root root 49 Feb 13 16:23 elasticsearch.yml
[root@localhost using-fig]# 

so when I run fig up -d
[root@localhost using-fig]# fig up -d
Recreating usingfig_es_1...
[root@localhost using-fig]# docker ps
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS              PORTS                                            NAMES
e7f8547a4ad1        library/elasticsearch:1.4.3   "elasticsearch"     5 seconds ago       Up 4 seconds        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   usingfig_es_1       

[root@localhost using-fig]# docker exec -ti usingfig_es_1 bash
root@e7f8547a4ad1:/# ls -l /data/
ls: cannot open directory /data/: Permission denied

however if I change  fig to absolute path

fig.yml:

/home/apps/using-fig/fig.yml
es:
    image: library/elasticsearch:1.4.3
    volumes:
        - /elasticsearch/data:/data
    ports:
        - "9200:9200"
        - "9300:9300"
everything works just fine

**Comment by nomadster** [comment] 2015-02-18 16:10
@dnephin I've managed to find some time to check for the bug:

```
$ docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2
----
$ fig --version
fig 1.0.1
```

I've deleted every single image I had and built them from scratch then run fig up (some container use links, I can provide the fig.yml privately if needed).
Everything is ok:
```
$ nsenter -m -u -p -n -i -t $PID
container$ ls /var/lib/mysql
my_db_from_volume_1
...
my_db_from_volume_N
```

Now I `fig stop` all the containers and `fig up` them again (not running fig rm --force)
And the bugs doesn't happen: everything just works fine.
All the data is where I wanted it to be.

Just in case this will happen again later on I've pasted the output of the command you asked [ here](http://pastebin.com/fvXmx0wF)

**Comment by dnephin** [comment] 2015-02-18 16:12
Ok, this sounds a lot like re-using old volumes, and might be fixed by #858

**Comment by morvans** [comment] 2015-02-18 16:31
@nomadster, if you restart the docker daemon between fig stop and fig up, are the volumes re-mounted correctly ?

**Comment by nomadster** [comment] 2015-02-18 16:56
```
fig stop
systemctl stop docker #Stopped Docker Application Container Engine
systemctl start docker #Started Docker Application Container Engine.
fig up -d container1 #(ups other container via links, same command as above)
```
Some of the container doesn't start correctly.

**Comment by morvans** [comment] 2015-02-26 12:34
FWIW, I updated to docker 1.5.0 and the issue seems to be gone.
I'm able to fig up stopped containers without fig rm them beforehand, and volumes are re-mounted correctly.

**Comment by UnknownHero** [comment] 2015-03-02 15:31
yes, 1.4.0 not work , but 1.5.0 work fine

**Comment by Vrakfall** [comment] 2015-03-03 08:02
@morvans Yeah, I think the problem was mainly coming from docker itself and the last big update was meant to solve big mounting issues.

**Comment by aanand** [comment] 2015-03-03 10:44
I'm closing this issue as it seems to be a confusion of different reports - if anyone can produce a minimal failing case, please open a new one.

**Closed by aanand** 2015-03-03 10:44 UTC

**Comment by CWSpear** [comment] 2016-01-28 21:45
I'm seeing some behavior that seems related and I have a reduced test case here: https://github.com/docker/compose/issues/2776

**Comment by pavankumarkatakam** [comment] 2016-02-16 03:37
Hi, im experienceing with same problem, after restarting my server the containers are starting but not mounting the volumes, the changes i have done to my server is updated to Ubuntu server 15.10 and docker-compose version is 1.6.0, but when i goto my docker-compose folder and start them them volumes are mounting correctly.

**Comment by dnephin** [comment] 2016-02-16 16:52
You might be hitting #2912
