### ISSUE TITLE
`docker-compose up --no-start` hangs indefinitely for services with `depends_on`  `condition: service_completed_successfully`

### ISSUE THREAD

**Issue by nicolas-2008** [docker/compose#8913] opened 2021-11-10 16:31 UTC
I have a docker-compose configuration with an orchestrated services startup.
Currently I'm using `docker-compose create` to create services without starting them.
This command shows a message `The create command is deprecated. Use the up command with the --no-start flag instead.`, however suggested command `docker-compose up --no-start` hangs for some of services.
As turned out, it happens for services with a dependent service configured with a `condition: service_completed_successfully`

**Steps to reproduce the issue:**
1. Create docker compose with the following content:
```
services:
  service1:
    image: alpine
    entrypoint: ["echo", "noop"]
  service2:
    image: alpine
    entrypoint: ["echo", "noop"]
    depends_on:
      service1:
        condition: service_completed_successfully
```
2.  Execute `docker-compose up --no-start`

**Describe the results you received:**

docker-compose creates network and service1 then hangs indefiitely.
Command output:
> Creating network "dev_default" with the default driver
> Creating dev_service1_1 ... done

**Describe the results you expected:**

Command creates all services then exits (same as `docker-compose create`).

**Additional information you deem important (e.g. issue happens only occasionally):**

Other conditions in depends_on service config (`service_healthy`, `service_started`) work as expected.

**Output of `docker compose version`:**

```
`docker-compose up --no-start`
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 81
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.772GiB
 Name: docker-desktop
 ID: BTQZ:QT4K:VX3Y:354S:IBV3:Y7MV:THZP:4X6U:HHAN:F33D:QGKH:DZOZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://my.company.proxy:8080
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by KoditkarVedant** [comment] 2022-02-25 11:27
@nicolas-2008 @ndeloof I unable to reproduce this issue locally. I've used the docker-compose config specified by you.  We can close this issue.

**Output of docker compose version:**
```
Docker Compose version v2.2.3
```

**Output of docker info:**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 26
  Running: 4
  Paused: 0
  Stopped: 22
 Images: 51
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 7.73GiB
 Name: docker-desktop
 ID: ZR5E:QMLQ:YMXZ:OUNY:XVU2:EBLM:XEUT:SFE5:MFYX:NNMV:BNGV:ZW2C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by nicolas-2008** [comment] 2022-03-06 12:25
@KoditkarVedant , it is reproducible in docker-compose 1.29.2 which is a default version in current Docker Desktop (4.5.1).
`docker-compose --version`
`docker-compose version 1.29.2, build 5becea4c`

I can confirm it is working as expected if I enable 'Use Docker Compose V2' in Docker Desktop settings.

**Comment by laurazard** [comment] 2022-07-04 13:43
Closing this issue since Compose V2 is now GA.

**Closed by laurazard** 2022-07-04 13:43 UTC
Labels: Docker Compose V2

**Comment by eruslmu** [comment] 2023-01-28 09:00
It is still hanging forever on my end. I tried both versions, version 1.29.2 and version 2.2.3.
It hung in both versions. I also tried it on MacOS Ventura 13.1 and the latest Ubuntu, no luck.

As soon as I provide `service_completed_successfully` in the .yml file, it hangs indefinitely.

```
depends_on:
      service1:
        condition: service_completed_successfully
```

**Comment by laurazard** [comment] 2023-01-28 14:10
@eruslmu you'll have to provide some more information, like a sample Compose file that replicates this issue, for us to be able to dig in to it. v2.2.3 is also quite old, please make sure the issue still exists with a newer version of Compose.
