### ISSUE TITLE
[BUG] open -: no such file or directory

### ISSUE THREAD

**Issue by Pyxxil** [docker/compose#12262] opened 2024-11-03 19:28 UTC
### Description

I'm not sure that the fix in https://github.com/docker/compose/issues/12248 has actually changed anything, as I still seem to be getting this issue in compose 2.30.1

### Steps To Reproduce

1. docker compose --file - up
2. See a similar error as in the issue title

### Compose Version

Docker Compose version 2.30.1

Docker Compose version 2.30.1

### Docker Environment

Client:
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.18.0
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.30.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 44
  Running: 43
  Paused: 0
  Stopped: 1
 Images: 57
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 57f17b0a6295a39009d861b89e3b3b87b005ca27.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.58-1-lts
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.18GiB
 Name: andromeda
 ID: 6WJ7:VZ23:KMIX:YN3K:CWPS:WCCQ:CBHH:SIGF:VNAW:AONR:7YYV:XI55
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by idsulik** [comment] 2024-11-04 05:33
@glours hi! Pushed changes from the main branch and as I see, there are no changes from this PR https://github.com/compose-spec/compose-go/pull/705, but at the same time the `go.mod` has the correct version of the `compose-go`

**Comment by idsulik** [comment] 2024-11-04 08:54
Strange things. If I download the latest release and check - I'm able to reproduce the issue, but if I checkout the source code to the releases's commit and check - I'm not able to reproduce it.
Continue checking...

**Comment by idsulik** [comment] 2024-11-04 09:33
The fix should be delivered within the next release because for some reason the fix is in the `compose-go` [v2.4.3](https://github.com/compose-spec/compose-go/releases/tag/v2.4.3) while it should be in the [v2.4.2](https://github.com/compose-spec/compose-go/releases/tag/v2.4.2).

**Comment by idsulik** [comment] 2024-11-05 04:37
@glours hi! Do you know what the problem might be? Maybe I'm missing something?

**Comment by glours** [comment] 2024-11-05 07:34
@idsulik I didn't check, but I suppect `go mod` not being happy with the re-push of an existing tag

**Comment by idsulik** [comment] 2024-11-05 07:48
> I suppect go mod not being happy with the re-push of an existing tag. 

I'm more than sure it's the reason) interesting case

**Comment by glours** [comment] 2024-11-05 14:52
Fix by Compose `v2.30.2` release

**Closed by glours** 2024-11-05 14:52 UTC
Labels: kind/bug, status/0-triage
