### ISSUE TITLE
ENOSYS: function not implemented, scandir  NTFS

### ISSUE THREAD

**Issue by piotr-sikora-v** [docker/compose#7466] opened 2020-05-18 18:55 UTC
##  Description of the issue
When we use gulp task-name on windows 10 and NTFS filesystem we have error:
```
www_1         | [17:55:06] Error: ENOSYS: function not implemented, scandir '/var/www/html/vendor/xxxxxx/modules'
```
This happen only with bind mount via volume.
On others systems, or without bind-mounts we don't have this problem
Is something wrong with NTFS and bind-mount ?

Docker image is alpine:3.11 with gulp, nodejs

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Docker version 19.03.8, build afacb8b
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
(paste here)
```

## Steps to reproduce the issue

1.
2.
3.

### Observed result
ENOSYS: function not implemented, scandir 
### Expected result
Without error

## Additional information

OS version / distribution, `docker-compose` install method, etc.
Windows 10 Pro Version 10.0.18363 Compilation 18363

**Comment by thaJeztah** [comment] 2020-05-18 20:36
This is an issue in the current 2.3.x version of docker for windows; the team is currently working on a fix (which should be included in an upcoming patch release), and the issue is tracked in https://github.com/docker/for-win/issues/6646

Given that this issue is not related to docker compose, I'll close it here, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-18 20:36 UTC
Labels: kind/bug
