### ISSUE TITLE
affinity:container messes up environment variables

### ISSUE THREAD

**Issue by lmakarov** [docker/compose#1598] opened 2015-06-24 20:33 UTC
Compose v1.3.0+ adds a set of `affinity:container` environment variables inside containers when those are **recreated** (second time a `docker-compose up -d` command is issued).

```
root@web:/var/www# env|grep affinity
VOYA_DB_1_ENV_affinity:container==f75d8c6ced29ed8e7f12cd60e3716e62844031caabb003d1feb74168bde942bc
DB_ENV_affinity:container==f75d8c6ced29ed8e7f12cd60e3716e62844031caabb003d1feb74168bde942bc
affinity:container==76df92d213821482e706251a81d9c9fde5416515f43c6813dcaf3816777a9849
DB_1_ENV_affinity:container==f75d8c6ced29ed8e7f12cd60e3716e62844031caabb003d1feb74168bde942bc
```

Such variables have invalid identifiers and cannot be exported/read by shell.

```
root@web:/var/www# export {affinity:container}==f75d8c6ced29ed8e7f12cd60e3716e62844031caabb003d1feb74168bde942bc
bash: export: `{affinity:container}==f75d8c6ced29ed8e7f12cd60e3716e62844031caabb003d1feb74168bde942bc': not a valid identifier
```

```
printf %q ${affinity:container}
''
```

Unfortunately there are fatal side effects of the empty ENV variables.

In my case all ENV variables are written into `/etc/php5/fpm/pool.d/env.conf` by a startup.sh script. The `affinity:container` variables value cannot be read properly, thus an empty value is written.
php-fpm does not tolerate empty variables in env.conf and simply crashes.

I added checks in the script, however it would make sense if docker-compose did not inject bad environmental variables to start with.

**Comment by saada** [comment] 2015-07-30 01:43
:+1:

**Comment by SpeCT** [comment] 2015-08-20 14:34
:+1:

**Comment by dnephin** [comment] 2015-09-29 04:03
Thanks for the bug report.

Unfortunately this is not something we can change on the compose side. This is the key that swarm expects. I believe https://github.com/docker/swarm/issues/288 is the issue to change this to use labels instead.

Since this isn't something we can change from the compose side, I'm going to close this issue. As a workaround you should be able to strip out the environment variables you don't want with a wrapper script that unsets things.

**Closed by dnephin** 2015-09-29 04:03 UTC

**Comment by luiselizondo** [comment] 2016-04-17 01:06
How do I unset such variables? 

I have:

MYSQL_1_ENV_affinity:container==7c9320f488cb47242157e41a10476e0a59d4f14d849ce91914de09ca47379172

And if I do:

```root@a5a210f22223:/var/www# unset MYSQL_1_ENV_affinity:container  
bash: unset: `MYSQL_1_ENV_affinity:container': not a valid identifier
root@a5a210f22223:/var/www# unset MYSQL_1_ENV_affinity:container=
bash: unset: `MYSQL_1_ENV_affinity:container=': not a valid identifier
root@a5a210f22223:/var/www# 
````

**Comment by chiller** [comment] 2016-04-21 08:39
@luiselizondo I have not yet figured out how to do that in bash, but in zsh or ash you are able to unset those.

**Comment by chiller** [comment] 2016-04-21 08:52
@luiselizondo the only way I have found how to do that in bash is that if you have `mycommand` that breaks because of affinity:container you can do `env --unset='affinity:container' mycommand`

**Comment by lmakarov** [comment] 2016-04-21 13:29
@luiselizondo If you are looking for a fix for PHP, take a look at this commit - https://github.com/blinkreaction/docker-drupal-cli/commit/217c24b9839e324e7b29e78e9865411f8928f0bd
It simplifies things considerably in my case.

**Comment by luiselizondo** [comment] 2016-04-21 14:27
Thanks. @lmakarov the problem is that `clear_env` doesn't work with older versions of PHP 5 and Ubuntu 14.04 doesn't provide newer versions of PHP either so I had to compile PHP to make it work. I think clear_env was introduced in PHP ~5.5.10
