### ISSUE TITLE
The -p flag don't set the environment variable COMPOSE_PROJECT_NAME

### ISSUE THREAD

**Issue by jonatanrs** [docker/compose#8125] opened 2021-02-17 00:38 UTC
**Description**

**Steps to reproduce the issue:**
1.The following docker compose file
```
version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_db
.
.
.
```
2. docker-compose -p myprojectname up -d

**Describe the results you received:**

```
 - _db  Creating                                                           0.0s
Error response from daemon: Invalid container name (_db), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "npipe:////./pipe/docker_engine",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 12.38GiB
 Name: docker-desktop
 ID: T7NT:FQ4P:BRHB:N5DE:7C2K:QFWI:7WZ3:NDCI:JDEY:3XQQ:3PQT:XTSX
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 112
  Goroutines: 108
  System Time: 2021-02-07T22:08:38.8968002Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by jonatanrs** [comment] 2021-02-17 00:40
I understand then that the documentation is wrong.

According to [this](https://docs.docker.com/compose/reference/overview/#set-up-environment-variables), I understand that the -p and -f flags should set the environment variables.

**Comment by thaJeztah** [comment] 2021-02-23 18:43
Looks like a duplicate of https://github.com/docker/compose/issues/2565 (which got merged into https://github.com/docker/compose/issues/2294)

The `-p` flag does not set the environment variable, but the reverse is true (the `COMPOSE_PROJECT_NAME` environment variable can be used to set the `-p` flag)

**Closed by thaJeztah** 2021-02-23 18:43 UTC
Labels: kind/bug
