### ISSUE TITLE
`run` does not set links

### ISSUE THREAD

**Issue by mihneadb** [docker/compose#1276] opened 2015-04-09 22:16 UTC
I have a docker-compose.yml file along the lines of:

	analytics:
	    build: .
	    links:
		- mongo:mongo
	    ports:
		- 80:80
	mongo:
	    build: docker_containers/mongo
	    expose:
		- 27017

Running `docker-compose up` creates a link in `/etc/hosts` to the `mongo` service. However, running `docker-compose run analytics bash` does not create the link -- I checked the `/etc/hosts` file.

The docs of docker-compose do not mention anything about this, so I'm confused.

1. Why isn't the link set when using `run`?
2. How can I achieve this?

[original SO question](https://stackoverflow.com/questions/29474299/docker-compose-run-does-not-set-links)

**Comment by aanand** [comment] 2015-04-14 13:31
This can happen if your mongo container has died before the analytics container has started. Is it still running? You can check with `docker-compose ps`.

**Comment by mihneadb** [comment] 2015-04-14 13:40
It is still running, yes. For the record, my workaround is to start the
mongo container with `docker-compose run -d mongo` and then do
`docker-compose run analytics <...>`.

On Tue, Apr 14, 2015 at 4:31 PM, Aanand Prasad <notifications@github.com>
wrote:

> This can happen if your mongo container has died before the analytics
> container has started. Is it still running? You can check with docker-compose
> ps.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/compose/issues/1276#issuecomment-92837025>.
>



-- 
Mihnea Dobrescu-Balaur

**Comment by kpettijohn** [comment] 2015-04-23 21:02
I can also confirm that `docker-compose run` is not setting up links for me as well. 

```
docker-compose --version
docker-compose 1.2.0rc3

docker --version
Docker version 1.4.1, build 5bc2ff8
```

**Comment by victuxbb** [comment] 2015-05-15 08:15
I have the same issue, there is some solution?
Thanks!

**Comment by victuxbb** [comment] 2015-05-15 09:02
Ok, sorry, forget it, It works, was a bad config in my app pointing to localhost instead of hostname of the link...
Thanks.

**Comment by calebeoliveira** [comment] 2015-07-10 12:06
The same here. I have a nodejs container who tries to access a redis container,  and I receive the folowing: `Error: Redis connection to redis:6379 failed - connect EHOSTUNREACH`
But sending a `ping` via redis-cli, I receive `PONG`.

**Comment by magicclaw** [comment] 2015-09-01 20:02
We have run into the same issue when using docker-compose run. Our docker-compose.yml file specifies a link from our test_container to an "es" container for elasticsearch. docker-compose up works, but always returns 0 even if an error code was returned by the executing container. Upon further reading, it appears that is expected behavior, and one should use docker-compose run instead. Unfortunately, when doing this, it appears to ignore the links defined in the docker-compose.yml file, requiring one to first docker-compose run -d es, and then docker-compose run test_container. At this point, there is little value provided in using docker-compose vs. simply specifying the necessary docker commands to achieve the same thing. Is there any traction on a solution to this issue?

**Comment by aanand** [comment] 2015-09-01 20:07
@magicclaw:

> Unfortunately, when doing this, it appears to ignore the links defined in the docker-compose.yml file, requiring one to first docker-compose run -d es, and then docker-compose run test_container.

It should not be doing that - if `test_container` has a link to `es`, then `docker-compose run test_container` should start `es` first and link to it.

However, the link will not appear if `es` exits before `test_container` can start.

Can you produce a minimal example that showcases the problem?

**Comment by nfsantos** [comment] 2015-09-07 15:38
I'm having the same problem. I have two containers, one linked to the second. If I try to start with docker-compose up, the links are not created. If I started first the container at the end of the link, then the container that links to it, everything works fine.

For reference, I'm running docker-compose 1.4, boot2docker 1.8, Windows 10 and cygwin.

**Comment by GustavoRPS** [comment] 2015-09-18 11:36
+1

**Comment by christianbundy** [comment] 2015-10-04 21:37
:+1: this is a blocking bug for us

**Comment by dnephin** [comment] 2015-10-05 15:33
I think you'll need to provide some more details about this error in order for us to debug what's happening. 

Can you confirm the problem is not that the container being linked to is failing to start?

**Comment by dnephin** [comment] 2016-01-15 15:52
Closing this issue.

Additional details about the error were not provided and links are being deprecated and replaced with networks.

**Closed by dnephin** 2016-01-15 15:52 UTC
Labels: area/run, kind/bug

**Comment by robinelvin** [comment] 2016-03-04 11:00
I have this issue too. I have MySQL, Selenium and Django test defined in my docker-compose.yml
If I start with `docker-compose up test` then the Selenium webdriver can connect to 'test:8081' however if I start with `docker-compose run --publish 8081:8081 test` then it cannot connect

**Comment by dnephin** [comment] 2016-03-04 14:54
You need to use `--service-ports` with `--run` I believe.

**Comment by robinelvin** [comment] 2016-03-04 15:02
@dnephin That doesn't work either.

**Comment by stcalica** [comment] 2016-03-11 23:05
Having the same exact issue. 
Python Flask app with Postgresql and Rabbitmq. 

version: '2'
services:
 web:
  build: .
  volumes:
    - .:/usr/app/src
  command: python /usr/app/src/dashboard/runserver.py
  ports:
    - "5000:5000"
  links:
   - postgres
   - rabbitmq
 postgres:
  image: postgres
 rabbitmq:
  image: rabbitmq 


My links are not being set up at all.

**Comment by christianbundy** [comment] 2016-03-12 00:12
@stcalica Use fenced code blocks (\`\`\`) to format your code. For example:

``` yml
version: '2'
services:
  web:
    build: .
    volumes:
      - .:/usr/app/src
    command: python /usr/app/src/dashboard/runserver.py
    ports:
      - "5000:5000"
    links:
      - postgres
      - rabbitmq
  postgres:
    image: postgres
  rabbitmq:
    image: rabbitmq
```

**Comment by stcalica** [comment] 2016-03-12 00:30
Having the same exact issue.
Python Flask app with Postgresql and Rabbitmq.
```
version: '2'
services:
web:
build: .
volumes:
- .:/usr/app/src
command: python /usr/app/src/dashboard/runserver.py
ports:
- "5000:5000"
links:

    postgres
    rabbitmq postgres: image: postgres rabbitmq: image: rabbitmq
```
My links are not being set up at all.

**Comment by stcalica** [comment] 2016-03-12 18:30
Okay so I found out why my /etc/hosts is not being updated or environment variables. 
I'm posting this for anyone else who has this problem: 

[Docker doesn't edit the /etc/hosts file any more to make connections, it has an internal DNS server. I couldn't find that in the documentation but I found it on a Stackoverflow question back in February. I see alot of posts for this problem so many people seem to get confused. Possibly because of old tutorials, that's why I was confused. Try pinging the services and it should work.  ](http://stackoverflow.com/a/35666124/4775199)

**Comment by mercadocommerce-r303** [comment] 2016-03-14 10:49
I am using ```docker-compose version 1.6.2, build 4d72027``` and I can definitely confirm that even with ```--service-ports``` container DNS resolution *does not* work with ```docker-compose run <container>``` but *does* work with ```docker-compose up <container>```

I'm happy to help test any suggestions.

**Comment by robinelvin** [comment] 2016-03-14 11:01
I am using ```docker-compose version 1.6.2, build 4d72027``` and I can definitely confirm that even with ```--service-ports``` container DNS resolution *does not* work with ```docker-compose run <container>``` but *does* work with ```docker-compose up <container>```

I can get by using 'up' but it would be nice for the console output to be coloured as it is with 'run' (I am running BDD tests)

I'm happy to help test any suggestions.

EDIT: Just to make this clear; I can ping, connect etc. from the container I run to other containers but I cannot connect from the other containers to the one I run.

In my case I have Django, MySQL and Webdriver containers. If I use ```docker-compose up testserver``` which runs a Django test server and performs Webdriver tests then the 'webdriver' container can resolve the 'test' host. If I use ```docker-compose run testserver``` it cannot but the 'testserver' container can still resolve 'mysql' and 'webdriver' so it seems when using run the DNS is not being updated.

**Comment by dnephin** [comment] 2016-03-14 17:37
Is all you need is colors, you can set `tty: True` on the service, which should allow the BDD output format to recognize that color is supported.

**Comment by pkucmus** [comment] 2016-03-14 22:25
This still look's like an issue to me. Please explain why it's closed if I did not understood something. Previously I had linked services for e.g. two Django apps and a Nginx one.  
I opened three terminals and in order run:  
```
#first term
$ docker-compose run --rm --no-deps app_1
#second term
$ docker-compose run --rm --no-deps app_2
#third term
$ docker-compose run --rm --no-deps --service-ports nginx
```
Nginx was configured to 'see' app_1 and app_2 by their service names. I can successfully ping project_app_run_1 but I simply don't want to. 

Did you change this intentional? Or is it a bug? @dnephin you said that links are deprecated in favor of networks - how can I use networks to fix this? 

P.S.
I can't use `up` which works fine with the exception that I can't use `pbd` with `up`.

**Comment by dnephin** [comment] 2016-03-14 22:57
Containers created by run are not expected to be discoverable as the service name. They are considered "one-off" or "adhoc" containers for running a task, not "regular service containers".

If you need to `pdb`, you can use `docker attach` I think.

**Comment by pkucmus** [comment] 2016-03-14 23:52
Thank you. Overall it's a huge downfall of Compose for me. I'll have to figure out something else :( 
`attach` doesn't work - can't input anything there. 
Thanks again.

**Comment by dnephin** [comment] 2016-03-15 00:07
You may need to use `stdin_open: True` to input things (as well as `tty: True`).

**Comment by pkucmus** [comment] 2016-03-15 00:14
Worked! Many thanks!

**Comment by elju** [comment] 2016-04-12 19:44
This is also breaking my debugging and is difficult to get around since I use supervisord for my `CMD`. Could really go for a `run_discoverable_by_dns` flag that makes a run container discoverable on startup if no other containers of the service are already discoverable.

Thanks for the `exec` workaround tip though!
