### ISSUE TITLE
Blank "attaching to" when up'ing containers w/ docker-compose

### ISSUE THREAD

**Issue by salihozd** [docker/compose#2067] opened 2015-09-18 13:03 UTC
Description of problem:
When I perform a docker-compose up I see very little useful info, and logs never flow. This is different than from previous versions.

docker version

```
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64
```

docker-compose version

```
docker-compose version: 1.4.1
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

```

docker-compose up

```
Starting somining_db_1...
Starting somining_redis_1...
Starting somining_web_1...
Attaching to 
```

Just waiting and do/log nothing. But application/docker running normaly.

Same issue opened there (https://github.com/docker/docker/issues/16397) by @ryanbaldwin and dublicated here by me.

**Comment by ecylmz** [comment] 2015-09-18 13:05
Same here.

**Comment by funkygibbing** [comment] 2015-09-18 13:06
Confirming same behaviour for all composed containers after the upgrade to 1.4.2
```
docker-compose version: 1.4.1
docker-py version: 1.3.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by dnephin** [comment] 2015-09-18 13:41
This was fixed by #1965 which should have been in 1.4.1 (but wasn't).

**Comment by drpheltright** [comment] 2015-09-18 15:25
OH NOES

**Comment by maxpollack** [comment] 2015-09-18 17:16
Is there a known workaround or cause for this issue? Something I can do to fix it locally until we wait for a release?

**Comment by salihozd** [comment] 2015-09-18 19:29
@maxpollack , downgrade docker-compose to 1.3.0 with this commands, :disappointed: 

```
sudo sh -c "curl -kL https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
sudo chmod +x /usr/local/bin/docker-compose
```

**Comment by dnephin** [comment] 2015-09-18 19:38
You can apply the patch from https://patch-diff.githubusercontent.com/raw/docker/compose/pull/1965.patch and `script/build-linux`. 

Otherwise there should be a new release out next week.

**Comment by brunowego** [comment] 2015-09-19 15:05
+1

**Comment by maxpollack** [comment] 2015-09-19 15:07
Thank you very much!

**Comment by jmagnusson** [comment] 2015-09-21 09:44
@salihozd Actually `1.4.0` worked just fine for me.

**Comment by brunowego** [comment] 2015-09-21 11:00
@salihozd yes, `1.4.0` worked fine.

**Comment by salihozd** [comment] 2015-09-21 11:03
@jmagnusson @brunowego okay then, thanks for information. i am fine with 1.3.0 for now. just waiting for new release with fix.

**Comment by yomguy** [comment] 2015-09-22 09:36
1.4.0 is fine.. Who will fix this nasty regression?

**Comment by dnephin** [comment] 2015-09-22 13:25
It's already fixed, it just needs a release. I'll prepare one today

**Comment by yomguy** [comment] 2015-09-22 13:34
@dnephin wonderfull!

**Comment by dnephin** [comment] 2015-09-22 18:17
https://github.com/docker/compose/releases/tag/1.4.2

**Closed by dnephin** 2015-09-22 18:17 UTC

**Comment by yomguy** [comment] 2015-09-22 20:10
It works!
Thanks and congrats @dnephin for 1.4.2!

**Comment by dimh** [comment] 2015-09-23 13:46
thank you @dnephin

**Comment by pandeiro** [comment] 2015-09-23 19:18
While the blank "Attaching to" is fixed in 1.4.2, there is still weirdness involving the output of `docker-compose up` in the new version. I'm seeing a mix of stale/fresh stdout output after killing with Ctrl-C and running `docker-compose up` again. This was not happening in 1.3.3.

**Comment by dnephin** [comment] 2015-09-23 19:21
@pandeiro I think what you might be seeing is that in 1.4.x we made `docker-compose up --x-smart-recreate` the default behaviour. Containers are no longer recreated by default, only when the configuration of the container changes. So the logs for the old container will still be in the  output.

If you `docker-compose rm` or use `--force-recreate` I think you'll see the old behaviour.

**Comment by pandeiro** [comment] 2015-09-23 19:58
Ouch, much noisier output by default now but okay. Thanks for the explanation @dnephin .

**Comment by dnephin** [comment] 2015-09-23 20:08
Yes, we have a few issues open for revamping the options to logs. I think we need to do something to reduce the noise when containers are re-used.

**Comment by pandeiro** [comment] 2015-09-23 20:14
@dnephin Would showing any log output from the current invocation of `docker-compose up` (but all existing logs on `docker-compose logs`) be a possibility? That would mesh with previous behavior and be ideal IMO.

**Comment by Alexis-benoist** [comment] 2016-04-20 14:09
I'm experiencing the same problem:
$ docker-compose --version

    docker-compose version 1.7.0, build unknown

$ docker --version

    Docker version 1.11.0, build 4dc5990

$ docker-compose up

    Starting cothwebsite_server_1
    Attaching to cothwebsite_server_1

and freezing

**Comment by yomguy** [comment] 2016-04-21 09:55
@Alexis-benoist try `docker-compose rm' and re-up again?

**Comment by Alexis-benoist** [comment] 2016-04-21 10:05
Thanks for the advice @yomguy but it doesn't work on my machine:

    $ docker-compose rm
    WARNING: Not including one-off containers created by `docker-compose run`.
    To include them, use `docker-compose rm --all`.
    This will be the default behavior in the next version of Compose.
    
    Going to remove cothwebsite_server_1
    Are you sure? [yN] y
    Removing cothwebsite_server_1 ... done
    $ git:(master) docker-compose up
    Creating cothwebsite_server_1
    Attaching to cothwebsite_server_1

**Comment by dnephin** [comment] 2016-04-21 16:28
I don't see anything wrong here. After attaching it should go to print the logs from the container, but if there are no logs then no output is correct.

Either way, this is an old issue, so whatever you're hitting is most likely unrelated to the original issue.

Please open a new issue and include the output of `docker-compose --verbose up` and what you expect to see.  If you want `up` to exit, you can use `-d`.

**Comment by Alexis-benoist** [comment] 2016-04-22 10:22
It can be my bad...

**Comment by mauricio** [comment] 2017-05-11 15:32
I'm seeing this issue now:

``` $ docker-compose --version
docker-compose version 1.13.0, build unknown```

``` $ docker --version           
Docker version 17.05.0-ce, build 89658be```

When running up:

``` $ docker-compose --verbose up
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.find_config_file: Trying paths: ['/Users/mauriciolinhares/.docker/config.json', '/Users/mauriciolinhares/.dockercfg']
docker.auth.find_config_file: No config file found
compose.cli.command.get_client: docker-compose version 1.13.0, build unknown
docker-py version: 2.2.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016
compose.cli.command.get_client: Docker base_url: https://192.168.99.100:2376
compose.cli.command.get_client: Docker version: KernelVersion=4.4.66-boot2docker, Arch=amd64, BuildTime=2017-05-04T21:43:09.220628248+00:00, ApiVersion=1.29, Version=17.05.0-ce, MinAPIVersion=1.12, GitCommit=89658be, Os=linux, GoVersion=go1.7.5
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
compose.cli.verbose_proxy.proxy_callable: docker info -> {u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'ContainerdCommit': {u'Expected': u'9048e5e50717ea4497b757314bad98ea3763c145',
                       u'ID': u'9048e5e50717ea4497b757314bad98ea3763c145'},
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=cloud', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set([])
Attaching to 
```

When running logs:

``` $ docker-compose logs
Attaching to ```

I'm on OSX with docker-machine:

``` $ docker-machine --version
docker-machine version 0.11.0, build 5b27455```

Using the docker command manually works.

**Comment by mauricio** [comment] 2017-05-11 15:35
Running it with force-recreate doesn't change much either:

```
 $ docker-compose --verbose up --force-recreate --build --remove-orphans 
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.find_config_file: Trying paths: ['/Users/mauriciolinhares/.docker/config.json', '/Users/mauriciolinhares/.dockercfg']
docker.auth.find_config_file: No config file found
compose.cli.command.get_client: docker-compose version 1.13.0, build unknown
docker-py version: 2.2.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016
compose.cli.command.get_client: Docker base_url: https://192.168.99.100:2376
compose.cli.command.get_client: Docker version: KernelVersion=4.4.66-boot2docker, Arch=amd64, BuildTime=2017-05-04T21:43:09.220628248+00:00, ApiVersion=1.29, Version=17.05.0-ce, MinAPIVersion=1.12, GitCommit=89658be, Os=linux, GoVersion=go1.7.5
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
compose.cli.verbose_proxy.proxy_callable: docker info -> {u'Architecture': u'x86_64',
 u'BridgeNfIp6tables': True,
 u'BridgeNfIptables': True,
 u'CPUSet': True,
 u'CPUShares': True,
 u'CgroupDriver': u'cgroupfs',
 u'ClusterAdvertise': u'',
 u'ClusterStore': u'',
 u'ContainerdCommit': {u'Expected': u'9048e5e50717ea4497b757314bad98ea3763c145',
                       u'ID': u'9048e5e50717ea4497b757314bad98ea3763c145'},
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=cloud', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set([])
Attaching to 
```

**Comment by mauricio** [comment] 2017-05-11 15:56
Ignore, my bad, was missing some of the dependent files here.

**Comment by TomasBombadil** [comment] 2020-07-27 20:48
Have same issue with:
```
Docker version 19.03.12, build 48a66213fe  
docker-compose version 1.25.0, build unknown 
5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
```
Single service docker-compose.yml file, running python app.
I had an output when manually run it from Docker:
```docker build . -t <service> && docker run  -v $(pwd)/data:/app/data -v $(pwd)/logs:/app/logs -it <service>```
but docker-compose hanged on ```Attaching to ```

Solved it by reinstalling docker-compose directly from github to version
```docker-compose version 1.20.1, build 5d8c71b```
- https://docs.docker.com/compose/install/

**Comment by stefanpl** [comment] 2020-08-12 16:13
For me, the root cause was pretty simple. Since I had started the app with
`docker-compose up -d -p my-fancy-name`, to receive the logs for this, I also have to pass the same `-p` flag to the `logs` command:
`docker-compose logs -f -p my-fancy-name`.

This is somewhat logical, but still, the blank `Attaching to` message is everything but helpful in identifying the issue.

**Comment by Rechdan** [comment] 2021-04-17 03:40
Trying to run `docker-compose up` but I'm getting a blank `Attaching to`, I'm on `1.29.1`

```
$ docker-compose up
Starting project_db_1         ... done
Starting project_phpMyAdmin_1 ... done
Attaching to
$ 
```

```
docker-compose -v
docker-compose version 1.29.1, build c34c88b2
```

**Comment by stefanpl** [comment] 2022-03-24 07:23
@PeterTucker did you check @CharlesB2 's answer? 

It explained in a little more detail [here on SO](https://stackoverflow.com/a/63380716/2072165) (disclaimer: I wrote that answer). Seems to be the culprit for some people facing this problem.
