### ISSUE TITLE
slow compose down when using depends_on

### ISSUE THREAD

**Issue by nico525** [docker/compose#9800] opened 2022-08-30 22:43 UTC
I have a compose file which is pretty complex that utilizes multiple depends_on in combination with service_healthy and service_started conditions.
I now figured out that the stopping of these containers is pretty slow. probably it tires to preserve some order in which the services are shut down.
Is there a way to bypass this and make the shutdown work fast again?
if I run the same compose file without any dependencies, the down command takes about 15 seconds compared to 4+ minutes when using depends_on

**Comment by Lenormju** [comment] 2022-08-31 09:47
I think it is the expected behavior, cf [Compose specification](https://docs.docker.com/compose/compose-file/#depends_on) :  
> `depends_on` expresses startup and shutdown dependencies between services.
> [...]
> Compose implementations MUST remove services in dependency order.

There is :
`docker compose down --help`  
> -t, --timeout int       Specify a shutdown timeout in seconds (default 10)

Example `docker-compose.yml` :  
```yaml
---
x-service-template: &service-template  # creating a "YAML anchor"
  image: alpine:latest
  command: ['/bin/sh', '-c', 'sleep 999999']

services:
  service1:
    <<: *service-template  # applying the content of the anchor
    depends_on: {}
  service2:
    <<: *service-template
    depends_on: [service1]
  service3:
    <<: *service-template
    depends_on: [service2]
  service4:
    <<: *service-template
    depends_on: [service3]
...
```
```shell
$ docker compose up -d
[+] Running 5/5
 ⠿ Network docker_compose_9800_default       Created                 0.1s
 ⠿ Container docker_compose_9800-service1-1  Started                 0.8s
 ⠿ Container docker_compose_9800-service2-1  Started                 1.2s
 ⠿ Container docker_compose_9800-service3-1  Started                 1.5s
 ⠿ Container docker_compose_9800-service4-1  Started                 1.8s

$ docker compose down
[+] Running 5/5
 ⠿ Container docker_compose_9800-service4-1  Removed                10.4s
 ⠿ Container docker_compose_9800-service3-1  Removed                10.4s
 ⠿ Container docker_compose_9800-service2-1  Removed                10.4s
 ⠿ Container docker_compose_9800-service1-1  Removed                10.5s
 ⠿ Network docker_compose_9800_default       Removed                 0.2s
```
The `down` waited for the default (conservative) timeout for each.

```shell
$ docker compose down --timeout 1
[+] Running 5/5
 ⠿ Container docker_compose_9800-service4-1  Removed                 1.4s
 ⠿ Container docker_compose_9800-service3-1  Removed                 1.4s
 ⠿ Container docker_compose_9800-service2-1  Removed                 1.4s
 ⠿ Container docker_compose_9800-service1-1  Removed                 1.4s
 ⠿ Network docker_compose_9800_default       Removed                 0.2s
```
The containers had much less time to exit before to get killed, which may be a solution to you (if you understand the risk).

Otherwise, you should check how your container's process handles Unix signals.
When you `Ctrl+C`, or `down` after a `up -d`, Compose sends a SIGTERM to the container's process pid=1, and if it has not exited after the default timeout, then sends a SIGKILL (which is handled by the OS so can't be "ignored") which quickly put an end to the process, and thus the container.
So usually, a well-behaved process should exit quickly after receiving a SIGTERM. If yours do not, take care at what `entrypoint`/`cmd` you are using (both in the images' Dockerfile and in the Compose file which can override them). For example, citing the docs about [`docker kill`](https://docs.docker.com/engine/reference/commandline/kill/#description) :  
> `ENTRYPOINT` and `CMD` in the *shell* form run as a child process of `/bin/sh -c`, which does not pass signals. This means that the executable is not the container’s PID 1 and does not receive Unix signals.

**Comment by nico525** [comment] 2022-09-01 16:53
That makes sense, but can't we just add a command to ignore the order when forcing down?
Anyways, due to your help and explanation of signals I was able to cut down the time required to shutdown my process from 2 minutes to 10 seconds.

**Comment by Lenormju** [comment] 2022-09-02 05:41
Something like adding `docker compose up --ignore-depends-on-shutdown` and `docker compose down --ignore-depends` ?  
I'm not a contributor to this repository, so I can't say if it is easily doable, nor if it is desired as it somewhat conflicts with the purpose of `depends_on`. But the project accepts [contributions](https://github.com/docker/compose/blob/v2/CONTRIBUTING.md) so if you want to implement it (in Go
), consider creating a Pull Request. 

Glad to have helped you anyway :smiley:

**Comment by milas** [comment] 2022-09-02 16:52
When Compose stops a service/container, it sends `SIGTERM` by default and then waits `timeout` (default: 10 secs) before forcibly killing it.

(Personally, I often run `docker compose down --timeout=0 --volumes --remove-orphans` to quickly & fully clean up a project.)

If you have images that don't respond nicely to `SIGTERM`, there's a couple of good options:
* Set `init: true` -> https://docs.docker.com/compose/compose-file/#init
* Define a `stop_signal` with something the application _does_  respond to: https://docs.docker.com/compose/compose-file/#stop_signal

**Comment by milas** [comment] 2022-09-08 18:27
Closing this because it's working as designed.

If you want to stop a project as fast as possible and don't care about doing it "cleanly": `docker compose down --timeout=0`

If you want to allow services to gracefully shut down but they are not, see the tips in the previous comment.

**Closed by milas** 2022-09-08 18:27 UTC
