### ISSUE TITLE
Please add --platform command line parameter like docker

### ISSUE THREAD

**Issue by AceHack** [docker/compose#5617] opened 2018-01-27 01:09 UTC
Please add --platform or come up with an alternative solution to support running linux and windows containers both on windows LCOW.

See resolved docker issue for the same here
https://github.com/moby/moby/issues/33854

Still would like to take advantage of multi-arch tags so explicit tags for a specific OS would not be an option.  Thanks.

**Comment by shin-** [comment] 2018-01-28 03:03
Duplicate of#5548

**Closed** 2018-01-28 03:04 UTC
