### ISSUE TITLE
`routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed` on CentOS with docker 1.5.0 client and server

### ISSUE THREAD

**Issue by grahamc** [docker/compose#1427] opened 2015-05-18 20:15 UTC
Server:
- CoreOS Stable
- Docker 1.5.0

Client:
- CentOS 6.6, 64-bit
- kernel 2.6.32-042stab105.14
- Docker client 1.5.0
- docker-compose 1.2.0
- SSL certificates placed at `~/.docker/{ca.pem,cert.pem,key.pem}`
- `DOCKER_HOST=tcp://docker-builder:2376`
- `DOCKER_TLS_VERIFY=1`

Using the following Makefile to build the SSL certificates:

``` makefile
SERVER=docker-builder

clean:
    rm ca.* server.* client.* *.key

all: ca.crt server.crt client.crt

%.key:
    openssl genrsa -out $@ 4096

ca.crt: ca.key
    openssl req -new -x509 -days 365 -key ca.key -sha256 -out ca.crt \
        -subj "/C=US/ST=Texas/L=Austin/O=Abc123/OU=Operations/CN=${SERVER}/emailAddress=ops@abc123.io"

server.csr: server.key
    openssl req -new -key server.key -out server.csr \
        -subj "/C=US/ST=Texas/L=Austin/O=Abc123/OU=Operations/CN=${SERVER}/emailAddress=ops@abc123.io"

server.crt: ca.key ca.crt server.csr
    openssl x509 -req -days 365 -in server.csr -CA ca.crt -CAkey ca.key \
        -CAcreateserial -out server.crt

client.csr: client.key
    openssl req -new -key client.key -out client.csr \
        -subj "/C=US/ST=Texas/L=Austin/O=Abc123/OU=Operations/CN=Docker Client/emailAddress=ops@abc123.io"

client.ext.cnf:
    echo "extendedKeyUsage = clientAuth" > client.ext.cnf

client.crt: client.csr ca.crt ca.key client.ext.cnf
    openssl x509 -req -days 365 -in client.csr -CA ca.crt -CAkey ca.key \
        -CAcreateserial -out client.crt -extfile client.ext.cnf
```

Using the `docker` client I have good success accessing the remote docker server. We call the remote server up to a hundred thousand times a day with good success.

Attempting to use `docker-compose`, installed either via curl OR `pip install --upgrade` with python 2.7, we get an SSL error:

```
$ docker-compose up -d
SSL error: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

This is the case after manually specifying `DOCKER_CERT_PATH=/home/user/.docker/` as well as `REQUESTS_CA_BUNDLE=/home/user/.docker/ca.pem`, individually and together.

To be clear: this setup works great with just docker daemon, but something about `-compose` is amiss.

**Comment by grahamc** [comment] 2015-05-18 20:20
Here is the (admittedly less than ideal) user-data script to provision this machine:

```yaml
#cloud-config

write_files:
    - path: /home/core/server.crt
      owner: core:core
      permissions: 0644
      content: |
        -----BEGIN CERTIFICATE-----
        <cert goes here>
        -----END CERTIFICATE-----


    - path: /home/core/server.key
      owner: core:core
      permissions: 0644
      content: |
        -----BEGIN RSA PRIVATE KEY-----
        <key goes here>
        -----END RSA PRIVATE KEY-----


    - path: /home/core/ca.crt
      owner: core:core
      permissions: 0644
      content: |
        -----BEGIN CERTIFICATE-----
        <ca cert goes here>
        -----END CERTIFICATE-----

coreos:
  update:
    reboot-strategy: reboot
  units:
  units:
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount RAM to /var/lib/docker
        Before=docker.service
        [Mount]
        What=tmpfs
        Where=/var/lib/docker
        Type=tmpfs
        Options=size=200g
    - name: docker.service
      command: restart
      content: |
        [Unit]
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.io
        After=network.target
        [Service]
        ExecStartPre=/bin/mount --make-rprivate /
        # Run docker but don't have docker automatically restart
        # containers. This is a job for systemd and unit files.
        ExecStart=/usr/bin/docker -d \
          --tlsverify \
          --tlscert=/home/core/server.crt \
          --tlscacert=/home/core/ca.crt \
          --tlskey=/home/core/server.key \
          -H 0.0.0.0:2376 -H unix:///var/run/docker.sock

        [Install]
        WantedBy=multi-user.target
```

**Comment by grahamc** [comment] 2015-05-22 17:03
*bump*

**Comment by grahamc** [comment] 2015-05-28 01:27
*9 day bump*

**Comment by aanand** [comment] 2015-05-28 08:17
Duplicate of #890

**Comment by grahamc** [comment] 2015-05-28 12:11
Thank you for taking a look, @aanand.

**Comment by grahamc** [comment] 2015-06-02 12:39
Note: fig 1.0.1, 1.1.0, 1.2.0, and 1.3.0 are affected.

**Comment by aanand** [comment] 2015-06-02 12:48
I was wrong - this is a separate bug from #890.

To help others reproduce this, could you make a repo with a Dockerfile equivalent to your cloud-config script?

**Comment by grahamc** [comment] 2015-06-02 12:49
What do you mean a dockerfile equivalent?

**Comment by grahamc** [comment] 2015-07-10 02:30
This replicates it: https://github.com/grahamc/docker-compose-1427

**Comment by aanand** [comment] 2015-07-14 15:54
ping @dmcgowan or anyone who knows about Docker and TLS certificates - is @grahamc's cert generation process in [this Makefile](https://github.com/grahamc/docker-compose-1427/blob/master/server/Makefile) in line with how cert generation for Docker is supposed to work?

For some reason Compose is failing to authenticate using the certs, but the Docker client works just fine.

**Comment by yun-wang** [comment] 2016-01-17 01:39
@grahamc @aanand I had a similar issue, today I tried on two machines, one with Python 2.7.6, the other with Python 3.5.0b3, the certs worked with Python3. I attached the details in #2668.

**Comment by heikofriedrich** [comment] 2017-01-25 12:14
i have the same problem. docker client works but docker-compose not. for me, a workarround that works is if i pass all the parameters explicitly:
docker-compose --tlsverify --tlscacert=/var/lib/jenkins/.docker/ca.pem --tlscert=/var/lib/jenkins/.docker/cert.pem --tlskey=/var/lib/jenkins/.docker/key.pem -H <host>:2376 up -d

**Comment by ijc** [comment] 2019-03-26 16:57
Issue grooming: This seems like an ancient configuration issue which based on the comment traffic people aren't seeing today, so I'm going to speculatively close. If this is still happening with modern versions then we can reopen (but please provide full details of the modern case). If you are still seeing this and you aren't the original submitter then please create a new issue with full details.

**Closed by ijc** 2019-03-26 16:57 UTC
