### ISSUE TITLE
abort-on-container-exit not working if a service is given 

### ISSUE THREAD

**Issue by fchennouf** [docker/compose#3909] opened 2016-09-04 16:19 UTC
Hi everybody,

Is it normal that abort-on-container-exit option of the up command is not working if a service is given for example: docker-compose up --abort-on-container-exit web doesn't stop the db service if the web service stops, whereas docker-compose up --abort-on-container-exit stops it

version: '2'

services:

```
db:
      image: postgres:9.3

web:
      build: ./
      links:
              - db
```

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

docker-compose version 1.8.0, build f3628c7
docker-py version: 1.9.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

**Comment by shin-** [comment] 2016-09-08 01:12
Hi!

I believe that is the expected behavior, yes. The command you're running `docker-compose up [...] web` is explicit about handling the `web` service, and not any other - having it stop the `db` service, which as far as compose is concerned is running independently, would seem very counter-intuitive to me. Is there a specific reason why you need to do things that way?

**Comment by fchennouf** [comment] 2016-09-08 05:51
Hi Shin,
Thanks for the answer. In my view  --abort-on-container-exit should work as long as linked containers are started. If I give a service like web in param, by default linked services are also started and I think that  --abort-on-container-exit should by default stopped these services. What I wanna do is to put two différent configurations of a service in the compose file (web1 and web2 for example), and i can precise one of the service if i want to separately start it with its linked containers.

**Comment by Zoltu** [comment] 2016-09-16 16:34
We also are running into problems with this.  We are using `docker-compose` for integration testing and so we do `docker-compose up ... test app_under_test`.  This will allow us to see the console output for `app_under_test` and `test` but it won't show us the massive spam of output from our dependencies like MySQL, Zookeeper, Kafka, etc. which in almost all cases we don't care about, isn't under our control, and is very noisy.

However, after the `test` container exits only the `app_under_test` also exits, which leaves all of the dependencies running indefinitely even though they are no longer used.  They just sit there consuming resources and (in some cases) bound to ports.

@shin- Can you help me understand the scenario under which you believe the current behavior is correct?  To me, a `docker-compose` collection is a single contiguous unit.  Presumably they would all come and go together in most cases.  Is that not how you use `docker-compose`?  Is that not how `docker-compose` is intended to be used?

**Comment by ronin1** [comment] 2017-03-31 22:22
We actually have the same need for our integration test in CI. We only care about our application container (where we have the app). Sometimes the tests are run directly on the application container, sometimes we run it on a separate test container and if the test pass or fail, we would like to tear down all containers.  Is there an easy way to do this with docker-compose?

**Comment by markbirbeck** [comment] 2017-08-24 12:53
I see what you are getting at @shin-, that when you explicitly start a service you aren't saying anything about the other services in the `docker-compose.yml` file, and so it might be counterintuitive to change the state of any services that Docker Compose didn't start.

But it also seems counterintuitive to _not_ stop any services that were started as a consequence of using `depends_on`. It completely threw me that secondary containers weren't being shut down once integration tests were complete.

Any thoughts on that aspect?

**Comment by amithgeorge** [comment] 2018-01-03 18:42
Any updates on this? Same use-case. Same issue.

**Comment by chris-vest** [comment] 2018-03-14 15:40
Could also use a solution here... Three containers in my compose, want to abort upon any one of them exiting. However services stay up, flag doesn't actually seem to have any effect?

**Comment by MicahZoltu** [comment] 2018-04-17 13:14
@GraemeF Assuming you have your dependencies setup correctly in `docker-compose.yml`, then you can just do `docker-compose up integration-tests --abort-on-container-exit` and I _believe_ that will do what you want and only terminate the docker-compose execution if `integration-tests` service exits.  If any of the things that `integration-tests` depends on exits, I _think_ it will keep running.

**Comment by MicahZoltu** [comment] 2018-04-17 13:15
@GraemeF Assuming you have your dependencies setup correctly in `docker-compose.yml`, then you can just do `docker-compose up integration-tests --abort-on-container-exit` and I _believe_ that will do what you want and only terminate the docker-compose execution if `integration-tests` service exits.  If any of the things that `integration-tests` depends on exits, I _think_ it will keep running.

**Comment by GraemeF** [comment] 2018-04-17 15:56
Thanks @MicahZoltu - I just spent some time experimenting with that and, unfortunately, the dependencies are left running afterwards which isn't ideal for my scenario. Nice idea though 😄

**Comment by MicahZoltu** [comment] 2018-04-17 16:33
Hmm, I just tested this again and I am witnessing the same behavior, the dependency containers are not exited when the primary container is with `--abort-on-container-exit`.  However, if I don't specify a service (e.g., just `docker-compose up --abort-on-container-exit`) then all of the containers exit.  Maybe I'm just mis-remembering how this used to work?  😢

**Comment by MicahZoltu** [comment] 2018-04-18 05:53
Hmm, I just tested this again and I am witnessing the same behavior, the dependency containers are not exited when the primary container is with `--abort-on-container-exit`.  However, if I don't specify a service (e.g., just `docker-compose up --abort-on-container-exit`) then all of the containers exit.  Maybe I'm just mis-remembering how this used to work?  😢

**Comment by fasmat** [comment] 2018-07-30 13:41
I'm also running into this problem.

We try to use docker-compose for our integration testing and after all test finish and the "main" container exits, it's dependencies are still running even when ``--abort-on-container-exit`` is set.

**Comment by damtur** [comment] 2018-10-31 15:55
Can I please have an update on this? It is counter-intuitive to me to not stop containers listed in `depends_on`.

**Comment by Alqio** [comment] 2019-05-20 12:35
Any updates on this?

**Comment by KevinGrandon** [comment] 2020-05-20 22:46
Fixing this functionality would be super nice. Right now it seems like a bug.

**Comment by MicahZoltu** [comment] 2020-11-19 12:59
I believe this should remain open.  While it does seem low priority, I believe the current behavior is quite counter intuitive and arguably wrong.

**Comment by ZukkyBaig** [comment] 2021-01-22 00:46
Any update on this? Just noticed this behaviour, and containers are just left there bound to ports after integration tests are ran.

**Comment by Alexander-Shukaev** [comment] 2021-03-23 11:13
Please, fix this bug.

**Comment by malcolm061990** [comment] 2021-07-19 14:48
Is someone here to help us solving the problem?

**Comment by ndeloof** [comment] 2021-09-07 06:16
IIUC the use-case reported on this issue, main reason to pass a service name to `compose up` is to select a subset of services to get logs.
For this purpose, an alternative approach I proposed on https://github.com/docker/compose/issues/8546 is to define services to attach to, but `compose up` would still manage other services, and as such stop them on completion. wdyt?

**Comment by Dzoge** [comment] 2022-03-18 09:52
You can disable logging on the container you don't want to see the logs for using:
```
logging:
    driver: none
```
and then start it up using 
```
docker-compose up --build --exit-code-from tests --abort-on-container-exit tests db some-other-container
```

**Comment by ndeloof** [comment] 2022-03-18 10:37
@Dzoge this hack won't work with Compose v2, which attach to containers (like `docker run` does) and does not rely on engine to collect logs

**Comment by MicahZoltu** [comment] 2022-09-22 04:11
I believe this is still a problem, and many people are patiently following this issue waiting for it to be fixed.

**Comment by ndeloof** [comment] 2023-01-04 15:15
updated reproduction example to use compose specification file format:
```yaml
services:
  db:
      image: postgres

  web:
      image: alpine
      command: /bin/true
      links:
              - db
```

then, I get the dependent service to be stopped on exit, when running latest v2.14.2:
```
$ docker compose up --abort-on-container-exit web
[+] Running 2/0
 ⠿ Container truc-db-1   Created                                                                                 0.0s
 ⠿ Container truc-web-1  Created                                                                                 0.0s
Attaching to truc-web-1
test-web-1 exited with code 0
Aborting on container exit...
[+] Running 1/0
 ⠿ Container test-web-1  Stopped  
````

@MicahZoltu can you please give v2.14.2 a try to confirm?

**Comment by MicahZoltu** [comment] 2023-01-05 07:56
Unfortunately using `postsgres` like this as an test case doesn't work because `postgres` without any parameters/configuration exits immediately.  I did a quick test using the following `docker-compose.yml` file and found that the `server` service was still running after the `short` service ended.
```yml
services:
  server:
    image: 'crccheck/hello-world'

  short:
    image: 'alpine'
    command: 'sleep 1s'
    links:
      - 'server'
```
Note: `crccheck/hello-world` was just some random dockerized web server I found whose only purpose is to illustrate a service that runs until stopped.

Running `docker-compose up --abort-on-container-exit short` results in only the `short` service exiting, while running `docker-compose up --abort-on-container-exit short server` results in both services exiting.

**Comment by ndeloof** [comment] 2023-01-05 09:56
ok, makes sense.
I created a draft PR trying to support this scenario, while I'm not please with the design, this could help us evaluate if/how we can address this

**Comment by ndeloof** [comment] 2023-05-10 14:56
investigated this issue based on this simple reproduction example:
```yaml
services:
  server:
    image: nginx

  test:
    image: 'alpine'
    command: 'sleep 1s'
    links:
      - 'server'
```

when ran with  `docker compose up --abort-on-container-exit test` AND server service isn't running yet, 2 services are created, but only the test server is stopped.

The question is: what do we expect here? running `test` require `server` to be started, but does this mean we also want the latter to be stopped? In other usage scenarios, the opposite is requested : running `test` is expected to start `server`, but then the latter _should_ not be stopped, so that subsequent execution of `test` (passing other parameters) will use the same instance. 

Also, what should happen if `server` is already running? Should it be stopped on command exit? What should happen is `server` is running 1 replica, but configuration require 2 off those, so we started a second one. Shall we kill only one container or fully stop the service.

I don't think there's any adequate answer here, and any decision to change the existing behavior will break another use-case. For this reason, I'm closing this issue as "not planned".

**Closed by ndeloof** 2023-05-10 14:56 UTC
Labels: kind/question, kind/enhancement

**Comment by MicahZoltu** [comment] 2023-05-10 15:35
Would it be reasonable then to request the addition of an option that allows starting multiple services but only showing logs for a subset of those?  Something like:
```
docker compose up --abort-on-container-exit --logging-for test
```
This would start both `server` and `test` and when `test` finished it would exit both `server` and `test` (as it does today if you don't specify a service), but it would allow silencing the logs for the backend services you don't care about during the test run.

**Comment by ndeloof** [comment] 2023-05-10 15:53
This is already possible with `docker compose up --abort-on-container-exit --attach test` as introduced earlier as a workaround for this issue
