### ISSUE TITLE
"Circular reference" when using extends

### ISSUE THREAD

**Issue by dunk** [docker/compose#1712] opened 2015-07-16 14:21 UTC
I get a circular reference when I use the pattern below, which I believe should work.

docker-compose.yml

    one:
        extends:
            file: another.yml
            service: two

another.yml

    two:
        image: ubuntu:latest
        extends:
            file: another.yml
            service: three

    three:
        user: blah

May be the same root cause #1343, but the behaviour is slightly different.

**Comment by aanand** [comment] 2015-07-16 14:47
Probably the same root cause, yes. I believe it was fixed in https://github.com/docker/compose/pull/1632, so 1.4 will have the fix.

If you need it urgently, you can try installing from master using Pip:

    $ git clone https://github.com/docker/compose
    $ cd compose
    $ pip install .

**Closed by aanand** 2015-07-16 14:47 UTC

**Comment by dunk** [comment] 2015-07-16 15:21
Yup, this does appear to already be fixed in master :-)
