### ISSUE TITLE
docker-compose exec not taking --host argument of the executable correctly

### ISSUE THREAD

**Issue by visualage** [docker/compose#8648] opened 2021-09-21 00:58 UTC
## Description of the issue
When executing an executable inside a container using `docker-compose exec` command, if the executable needs a `--host` argument, the command `docker-compose exec <container> <executable> --host <value>` does not work properly. `docker-compose` simply takes `--host <value>` as its own argument instead of the executable's. Tried `docker-compose exec -- <container> <executable> --host <value>` as well. One example is running `mongo` command inside a mongo docker container.

## Context information (for bug reports)

- [x] Using Compose V2 `docker compose ...`
- [ ] Using Compose V1 `docker-compose ...`

**Output of `docker(-)compose version`**
```
Docker Compose version v2.0.0-rc.3
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  mongo:
    image: mongo:4.2.3
    networks:
      default: null
networks:
  default:
    name: tmp_default
```

## Steps to reproduce the issue

1. `docker-compose up -d`
2. `docker-compose exec mongo mongo --host mongo` or `docker-compose exec -- mongo mongo --host mongo`

### Observed result
```
Cannot connect to the Docker daemon at tcp://mongo:2375. Is the docker daemon running?
```

### Expected result
```
MongoDB shell version v4.2.3
connecting to: mongodb://mongo:27017/?compressors=disabled&gssapiServiceName=mongodb
...
```

### Stacktrace / full error message

```
None
```

## Additional information

mscOS Big Sur 11.6 with Docker Desktop 4.0.1 (68347)

**Comment by ndeloof** [comment] 2021-09-21 05:44
I've added a test case for this usage: https://github.com/docker/compose-switch/commit/9e07182c1408e8eedac863e9d10eb170e18e4eef

and confirmed latest compose-switch manages this as expected.

**Comment by visualage** [comment] 2021-09-23 01:37
I mislabeled this as docker compose v2. it is actually docker-compose v1 `docker-compose` command.

**Comment by ndeloof** [comment] 2021-09-23 06:15
@visualage this _IS_ compose v2, behind the compose switch (to make it appear under `docker-compose` command) as demonstrated by `docker-compose version`

**Comment by visualage** [comment] 2021-09-23 06:24
Interesting. In my installation, `docker compose` indeed behaves correctly while `docker-compose` does not. Any theory on why?

**Comment by ndeloof** [comment] 2021-09-23 06:47
Right, because the bug is in the command translation https://github.com/docker/compose-switch/commit/9e07182c1408e8eedac863e9d10eb170e18e4eef

**Comment by ndeloof** [comment] 2021-09-24 07:40
Closing as already fixed (will be available with incoming Docker Desktop release)

**Closed by ndeloof** 2021-09-24 07:40 UTC
Labels: kind/bug, Docker Compose V2
