### ISSUE TITLE
[BUG] Unable to bind mount when mount source is within the daemon root

### ISSUE THREAD

**Issue by bohde** [docker/compose#12139] opened 2024-09-19 21:37 UTC
### Description

After upgrading Compose v2.29.6 from v2.29.2, the following service began failing:

```
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
```

Running `docker compose up -d` gives the following error message:

```
Error response from daemon: invalid mount config: must use either propagation mode "rslave" or "rshared" when mount source is within the daemon root, daemon root: "/var/lib/docker", bind mount source: "/", propagation: "rprivate"
```

### Compose Version

```Text
Docker Compose version v2.29.6
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.3.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.6
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 26.1.3
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.16-linuxkit
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.657GiB
 Name: d4d8c60ee1fe
 ID: 186ebd80-8c59-49b8-92ae-007c1c620318
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by zhaoqizqwang** [comment] 2024-09-19 22:37
same things happened to us. Running `docker compose -f docker-compose.yaml up --build -d` and got error Error response from daemon

**Comment by thaJeztah** [comment] 2024-09-19 23:02
Looks related to;

- https://github.com/docker/compose/pull/12133

The error is related to;

- https://github.com/moby/moby/pull/36055


cc @ndeloof @glours

**Comment by thaJeztah** [comment] 2024-09-19 23:03
I guess as a workaround, it would work to explicitly set the bind propagation for that mount

**Comment by mariovitale1979** [comment] 2024-09-20 08:20
had similar issue. Fixed by changing definition of volume .
Before
_/var/lib/docker/:/var/lib/docker:ro_

After
_type: bind
     source: /var/lib/docker/
     target: /var/lib/docker
     read_only: true
     bind:
       propagation: rslave_

**Comment by ridoo** [comment] 2024-09-20 08:28
We observed a similar issue (Note: we did **not** mount `/var/lib/docker/`).

We just had deployed our service under `/var/lib/docker-compose/` (for whatever reason). It seems the daemon just checks via some `startsWith` and complains the above exception. Moving to a different directory solved the issue for us.

**Closed** 2024-09-20 08:37 UTC
Labels: kind/bug, status/0-triage

**Comment by ndeloof** [comment] 2024-09-20 08:58
@thaJeztah here are the identified corner cases:
- we have to set propagation for WSL2 to be happy
- windows container don't support propagation to be set (must be left empty)
- daemon root require propagation to be `rslave`, but client can't guess what "daemon root" is.

based on those, I hardly can find a way for client to rely on `mount` API as a replacement for `bind`, as this require significant knowledge of the engine setup.

**Comment by glours** [comment] 2024-09-20 09:01
Thanks @ndeloof for the summary, I'm totally aligned with your final remark

**Comment by thaJeztah** [comment] 2024-09-20 13:29
Basically, in all of the above, the client does _not_ set an explicit bind-propagation, and (AFAICS), the daemon automatically sets the correct one (either `rprivate`  or `rslave`), so I'm curious why that failed on Docker Desktop (at least)

**Comment by ndeloof** [comment] 2024-09-20 13:33
@thaJeztah the issue is that Docker Desktop with WSL2 require propagation to be set. Maybe this should better be fixed there

**Comment by thaJeztah** [comment] 2024-09-20 14:02
Thanks!

For others; we followed up on Slack, and found the code in Desktop that's related.

Also, for transparency; I support reverting this change (temporarily) until we have a solution for this. This change was to move away from legacy APIs; nothing critical, and not (directly) user-facing.

**Comment by kmbuthia** [comment] 2024-09-20 15:38
Thank you @mariovitale1979

Just adding a formatted version of that answer for docker-compose...because yaml cares :)

```
volumes:
- type: bind
  source: /
  target: /rootfs
  read_only: true
  bind:
    propagation: rslave
- type: bind
  source: /var/lib/docker/
  target: /var/lib/docker
  read_only: true
  bind:
    propagation: rslave
```
