### ISSUE TITLE
I'd like to have something like "docker-compose login <container_name>"

### ISSUE THREAD

**Issue by victorliun** [docker/compose#1772] opened 2015-07-27 09:47 UTC
Hi

Is there something like "docker-compose login <container_name>", so I don't have to run "docker exec -it container_name bash" manually?

Thanks
Victor Liu

**Comment by josephpage** [comment] 2015-07-29 08:33
Probably duplicate of docker/compose#593

docker-compose will supports `docker-compose exec -it service_name bash` in the future.
Contributions are accepted ! :wink:

**Comment by dnephin** [comment] 2015-08-24 21:22
Closing as duplicate of #593

**Closed by dnephin** 2015-08-24 21:22 UTC
