### ISSUE TITLE
Unable to pull images while building when using credentials helper.

### ISSUE THREAD

**Issue by jkinkead** [docker/compose#4255] opened 2016-12-16 19:57 UTC
This is very similar to #3622 .

If I have a compose service with a `build` clause, and the image you're building has a `FROM` that uses my private repository, it fails with an unauthorized error.

Compose file:
```yml
version: '2'
services:
  broken:
    build:
      context: '.'
```

Dockerfile:
```Dockerfile
FROM my.private.repo/image:tag
CMD ["echo", "built"]
```

Output:
```
Building broken
Step 1 : FROM my.private.repo/image:tag
ERROR: Service 'broken' failed to build: Get https://my.private.repo/v2/image/manifests/tag: unauthorized: Unauthorized
```

I'm using Docker for Mac, version 1.12.3 (13776). `docker-compose -v`: `docker-compose version 1.8.1, build 878cff1`

**Comment by nkovacs** [comment] 2016-12-16 19:57
I think this is a duplicate of https://github.com/docker/compose/issues/4171, which was fixed in docker-py 2.0.

**Comment by jkinkead** [comment] 2016-12-16 19:58
Awesome, thank you!

Is there a way to update the bundled version of `docker-compose` that ships with Docker for Mac?

**Comment by shin-** [comment] 2016-12-16 19:59
Unfortunately there isn't, especially since docker-py 2.0 introduces some non-backward compatible API changes that Compose needs to be aware of. I'm afraid you'll have to wait for the upcoming 1.10 release.

**Comment by jkinkead** [comment] 2016-12-16 20:07
Thanks for the quick replies - I'm glad to hear it's likely fixed.

**Closed** 2016-12-16 22:05 UTC
Labels: duplicate
