### ISSUE TITLE
Hosts file not updated on container restart

### ISSUE THREAD

**Issue by icambron** [docker/compose#696] opened 2014-12-02 22:44 UTC
Fig very helpfully creates aliases between the name of the service and the first (?) container instantiated from it, so like `riemann` for `mycoolthing_riemann_1`. But it doesn't seem to keep them updated on restarts. Steps to reproduce:

Two containers, `app` and `riemann`, where `app` has a link to `riemann`:

From `fig run app bash`:
```
root@6861c5de152d:/code# more /etc/hosts | grep riemann
172.17.0.64     riemann
172.17.0.64     riemann_1
172.17.0.64     mycoolthing_riemann_1
```

Leave that up, but back at home and in another terminal, I do `fig restart riemann`. And then back in my in-container bash instance:

```
root@6861c5de152d:/code# more /etc/hosts | grep riemann
172.17.0.64     riemann
172.17.0.64     riemann_1
172.17.0.66     mycoolthing_riemann_1
```

Notice that the container has changed IPs, but the alias hasn't updated. So if I'm using the alias in my app code and I restart the container, I won't be able to find my links.

**Comment by dnephin** [comment] 2015-08-08 14:59
This is unfortunately a limitation of docker links. There isn't much we can do about it in compose, but there is work being done in docker to support networking where service discover is updated when containers restart.

Going to close this issue, since it's not actionable from compose.

**Closed by dnephin** 2015-08-08 14:59 UTC

**Comment by icambron** [comment] 2015-08-09 00:08
@dnephin I don't understand. In my example, the host file entry for the "real" Docker name *was* updated (see `mycoolthing_riemann_1`), just not the Compose-generated aliases. Am I misunderstanding something?

**Comment by dnephin** [comment] 2015-08-09 00:29
Ah, I see.

Are you able to reproduce this with the latest docker?

**Comment by icambron** [comment] 2015-11-05 03:05
I'm no longer able to reproduce this :+1:, though I suspect the fix was in Compose.
