### ISSUE TITLE
 log_timeout_error() TypeError

### ISSUE THREAD

**Issue by Nokel81** [docker/compose#3904] opened 2016-09-02 12:14 UTC
WIth docker (for mac) running I do "docker-compose up" and I receive this traceback.

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "contextlib.py", line 35, in __exit__
  File "compose/cli/errors.py", line 56, in handle_connection_errors
TypeError: log_timeout_error() takes exactly 1 argument (0 given)
docker-compose returned -1
```

**Comment by shin-** [comment] 2016-09-02 17:55
This has been reported in #3783 and fixed in #3784. It seems your `docker-compose up` command is timing out for some reason. Do you see anything happen before it, or does it just print stacktrace?

**Comment by Nokel81** [comment] 2016-09-06 12:15
No nothing before, I run the command and then this prints out

**Comment by shin-** [comment] 2016-09-06 17:44
That means `docker-compose` isn't able to connect to your host for some reason. I assume `docker info` works fine? What about `docker-compose ps` for example? Does this happen with all compose files or just one? Do you have a custom `$DOCKER_HOST` set?

**Comment by aripalo** [comment] 2016-09-12 12:08
I've got this one too with Docker for Mac. 

It mainly happens when running a docker-compose container and then putting the computer to sleep (or closing the macbook lid). But it has happened couple times even without putting the machine to sleep.

I've tried `docker-compose ps` and `docker info`, but both hang, so I've eventually aborted them (with `ctrl`+`c`).

Restarting Docker for Mac doesn't help, only full reboot (which probably means that some service/daemon requires restart that I don't know).

I'm running the latest stable version. Here's various app versions:

```bash
docker --version
# -> Docker version 1.12.0, build 8eab29e

docker-compose --version
# -> docker-compose version 1.8.0, build f3628c7

docker-machine --version
# -> docker-machine version 0.8.0, build b85aac1
```

**Comment by shin-** [comment] 2016-09-12 18:42
Hi @aripalo , thanks for the detailed report. Seeing as `docker info` seems to hang as well, I would say this is an issue with Docker For Mac. probably https://github.com/docker/for-mac/issues/268 . Do you mind commenting there? The team in charge of that project will be better suited to help.

**Comment by aripalo** [comment] 2016-09-12 19:12
@shin- Ah true! Thanks for pointing out! I'll leave a comment there as well. 

I'm not that familiar with the whole Docker ecosystem so I can't really say for sure (which is probably obvious), but… I'd say this is 50%/50% `compose`& `for-mac` issue 🙂

The _cause_ itself seems to be `for-mac` issue, but the _effect_ is still `compose` issue: I'd argue there is improvement to be done on handling the "`for-mac` hangs" situation.  

To me ```TypeError: log_timeout_error() takes exactly 1 argument (0 given)``` tells that there is some kind of timeout functionality built into `docker-compose`, but that seems to be buggy and not working as intended.

… but the main issue of course is that `for-mac` issue and I'll continue about it on https://github.com/docker/for-mac/issues/268.

---

Shoutout to all you Docker org members: I've been using Docker on AWS Elastic Beanstalk for few months and now replacing local Vagrant + VirtualBox based development environments with `for-mac` & `docker-compose`, which is easy to get going on with and for the most part works great! 👍 I'm really pleased with the whole Docker ecosystem! 👌

**Comment by shin-** [comment] 2016-09-12 19:47
@aripalo  awesome to hear you've had a good experience overall, thanks for the kudos :cat: 

Yeah, as far as the stacktrace is concerned, we already have a fix in master for it. See my [comment above](https://github.com/docker/compose/issues/3904#issuecomment-244444859). It will be in our 1.8.1 release!

**Comment by aripalo** [comment] 2016-09-13 09:55
Also anyone having that "Docker hangs" issue with `for-mac` should point themselves to https://github.com/docker/for-mac/issues/119

But just in case someone ends up reading this thread:

A temporary “solution” (until an actual fix comes along) is to run `sudo pkill docker` and then restart the Docker for Mac app.

**Closed** 2017-02-11 03:50 UTC
