### ISSUE TITLE
Proposal: Docker-compose build --push and private registries.

### ISSUE THREAD

**Issue by emilebosch** [docker/compose#2680] opened 2016-01-17 16:09 UTC
Use case: I have a couple of build files and a private registry and docker swarm running locally, i want to build and push to the private registry so swarm can access all the images.

The private registry is 10.0.0.0:4000 the build directory for containers is ./docker/lb/.

- I want to build the container and push it to my private registry using `docker-compose build --push`
- When running i want to pull it from that image (i.e private registry).

Instead of having `image:` and the `build:` mutuality exclusive in the yaml  we could just allow them both and add a `push` operator to `build`.

This way the workflow for private registries and running them would be made much easier when using swarm.

What you people think?

**Comment by dnephin** [comment] 2016-01-17 18:40
Duplicate of #2092 and #1126.  The first is merged into master and will be in 1.6

**Closed by dnephin** 2016-01-17 18:40 UTC
Labels: duplicate
