### ISSUE TITLE
allow removing something in docker-compose.override.yml

### ISSUE THREAD

**Issue by stefanfoulis** [docker/compose#3729] opened 2016-07-13 20:13 UTC
My usecase is that the base `docker-compose.yml` maps a certain port in the `ports` section. In my `docker-compose.override.yml` I'd like to change that port since I already have a different service running there on my host.
As far as I understand the current implementation it is only possible to add stuff, override extends the other file.
As far as I can tell there is no way to remove an entry. And I can't think of an obvious syntax for it.

**Comment by aanand** [comment] 2016-07-13 20:15
Correct. Best practice is to not include anything in `docker-compose.yml` that you might not want to have in another environment.

**Comment by nkovacs** [comment] 2016-08-11 08:55
My problem with your suggestion is that docker-compose.override.yml might not exist (it's an optional file the developer can create locally). I only want to use docker-compose.override.yml to locally customize ports, like this:

docker-compose.yml:

```
version: '2'
services:
    web:
        ports:
            - 80
            - 443
        ...
```

docker-compose.override.yml:

```
version: '2'
services:
    web:
        ports:
            - 32080:80
            - 32443:443
```

This isn't a big deal because this will only result in 80 being exposed twice, once as a random port and once as 32080. I think it would make sense in this case to only expose it as 32080 automatically (without having to specify anything in the override to remove the original config value)

**Comment by tomekit** [comment] 2017-01-17 14:42
Facing the same problem. I've got one specific host which shouldn't start the one of the docker containers for given service. Yeah, maybe my `docker-composer.yml` approach is not the best, but I can see the need of removing something.

**Comment by paunin** [comment] 2017-01-24 08:05
Does anyone got script to remove ports from docker-compose file ? :)

**Comment by paunin** [comment] 2017-01-24 13:56
Alright, there is no solution so far, so I got a simple port-remover 
https://github.com/paunin/docker-compose-v2-ports-remover

In general I dont think docker-compose should allow to do it, as then logic of merging many files is gonna be complex...

**Comment by bluemoehre** [comment] 2017-03-13 11:38
This was already solved here https://github.com/docker/compose/pull/3939

**Comment by jedie** [comment] 2018-04-27 08:32
It's also not possible to removed a service, isn't it?

**Comment by OnkelTem** [comment] 2018-06-06 08:04
Having an "override" thing that cannot do half of the job... well, it's something.

**Comment by mqu** [comment] 2018-08-02 08:34
I'd like to be able to override some services and disable some others.

**Comment by sauron918** [comment] 2018-09-10 07:08
Same issue, I'd like to have possibility to **remove** port, dns, etc in `docker-compose.override.yml` but not override or extend with another one..

**Comment by keithy** [comment] 2018-10-31 01:18
Anyone notice that the only thing that you can't do with docker-compose.overide.yml, is to actually override anything!

**Comment by gnumoksha** [comment] 2018-11-13 00:04
I would like to remove some services because I rarely use them on my machine, so I ended up with the following `docker-compose.override.yml`:
```
version: '3.5'

services:
  elasticsearch:
    image: hello-world

  selenium:
    image: hello-world
```

**Comment by darakian** [comment] 2019-01-31 23:54
To add two more cents to the pile. It can happen that you pull a docker-compose.yml from another group and want to not run some of what they have turned on. Please add some syntax for removing.

**Comment by memiux** [comment] 2019-03-25 03:24
```yml
services:
  elasticsearch:
    entrypoint: ["/bin/true"]

#   ¯\_(ツ)_/¯
```

**Comment by ajutzeler** [comment] 2019-04-02 13:29
I personnally use the same hack as @gnumoksha. But it is very limited as it does not work with a service originally defined with the `build` option.

Would love some new syntax to solve this issue in a more elegant way.

**Comment by port22** [comment] 2019-05-03 10:47
My use case is a full-stack-developer yml for all, and for specific persons I want to provide specific override.ymls which either exchange values as also remove things like volumes completely.

A simple approach would have been the extend function, but not merging them, instead completely override everything. Yes, maybe in some cases you would repeat code (unless you can yaml-merge/include anchors from another file?) but at least it is more obvious who can use what without changing a single line.

**Comment by speller** [comment] 2019-06-02 02:01
Three years passed and still nothing?

**Comment by immanuelfodor** [comment] 2019-06-22 06:41
Stumbled upon this issue when trying to override the `dns` settings of a random Github project without modifying their `docker-compose.yml`. The new `dns` servers are appended to the original list instead of overriding the original ones - as I supposed it will work based on the file name. This behavior is misleading IMHO.

**Comment by Somebi** [comment] 2019-06-23 08:19
Same problem here... It seems it's not overriding some values correctly. Can't remove either.
For example i'm overriding with `network_mode: host `and need to remove `links`, because otherwise it's throwing error:

`ERROR: for processor  Cannot create container for service processor: conflicting options: host type networking can't be used with links. This would result in undefined behavior`

Setting `links: []` doesn't help, `links: null` or` links: ~` throws format error.

**Comment by pptime** [comment] 2019-06-26 12:13
This must be an interesting feature

**Comment by pptime** [comment] 2019-06-26 20:57
If the above saying is true, it means that the inherent parser is not able to just load several dictionaries and then apply the overriding of keys following some arbitrary order, which is not complicated in nature.

The truth is that the current design has made a key dependent behaviour. ref https://docs.docker.com/compose/extends/

My feeling is that it would be better to go for a more intuitive behaviour for developers, like that in multiple inheritance cases. The current use case consists of combining multiple yaml files in the same command line, which looks just like a one layer inheritance. The better would even be able to support multiple layer multi-inheritance using some kind of inclusion key word. Also, to specify the case when child will either merge or simply override, some key words like "super" could hence be interesting to have.

"Composition" could be a workaround to achieve the same thing as "inheritance". In the case of docker compose file one may do the something similar. The key word "extend" becomes helpful in this case, which may , yet, result in a more verbose compose file. Also, one would need to very carefully craft each file so that things are always extended/override but not removed.

**Comment by thomaspeitz** [comment] 2019-07-24 12:21
```
#!/usr/bin/env ruby
require 'yaml'

data = YAML.load_file "docker-compose.yml"

majorVersion = data['version'][0].to_i
serviceName = ARGV[0]
image = ARGV[1]

if majorVersion == 3
  data['services'][serviceName]['image'] = image
  data['services'][serviceName].delete('build')
else
  puts 'Version #{majorVersion} not supported yet. Please ask your cloud-ops team!'
  exit 1
end

File.open('docker-compose.yml', 'w') { |f| YAML.dump(data, f) }
```

Needed a small script which removes build and adds image to a docker-compose service. Maybe this helps other building CI scripts as well e.g. removing a service.

From my point of view the remove feature should be added to docker-compose overwrite as it decreases user experience of docker-compose a lot.

**Comment by keithy** [comment] 2019-07-24 18:19
Hi Thomas,

I wrote a simple script, docker-compose-use, as the basis of my AngelBox toolkit. This makes docker-compose files "composable". You will find this at http://github.com/keithy/sprankle-pod and http://github.com/keithy/angelbox

**Comment by gothrek22** [comment] 2019-08-27 07:58
@thomaspeitz or just use yq. you can easily edit parts of yaml with it.

F.e. Adding image: `yq w -i ./docker-compose.yml services.nginx.image nginx:latest`
or removing ports:  `yq d -i ./docker-compose.yml services.db.ports`

**Comment by sshishov** [comment] 2019-09-02 23:10
It is ridiculous that the team of "professionals" of `docker-compose` cannot solve this easy issue for years. And even more funny that override file cannot even properly override anything.

**Comment by mlensment** [comment] 2019-09-08 22:42
Any progress on this?

**Comment by typoworx-de** [comment] 2019-11-13 10:16
I also vote for this. Already tried adding ```override_strategy: overwrite``` in the given yaml-section which won't work (anymore?!) mentioned here #2260 

I would also vote for such an option which also would resolve deleting by setting a property to "[]" or "" to empty it.

**Comment by rekliner** [comment] 2020-01-14 06:28
I'm still hoping this gets addressed.  The best solution for me is using "image: hello-word" for unneeded services but it's so smelly.
The only alternative is to ditch the override feature completely and duplicate much of the original docker-compose.yaml into a completely alternate version for production...not DRY or ideal for environment consistency but seems to be the standard practice.

**Comment by liamjones** [comment] 2020-01-14 08:55
>  The best solution for me is using "image: hello-word" for unneeded services but it's so smelly

Option that might be slightly less smelly? - we tend to leave the image, etc as-is and do something like `entrypoint: /bin/sh` in the override file so the container runs `sh` then exits (rather than running its usual entrypoint/cmd).

**Comment by ptheofan** [comment] 2020-02-18 10:16
> It is ridiculous that the team of "professionals" of `docker-compose` cannot solve this easy issue for years. And even more funny that override file cannot even properly override anything.

Truly remarkable and only one of the many. Why not substitute it with a map instead? It's not like you can bind to the same host port twice. Why not a map where you could easily say, override it to "nothing" for example by doing `8080: -`
```yml
ports:
     8080: 80
     21000: 5432

# ... in some other file extending the prev config
ports:
    8080: -
```

No wonder why people move so passionately to Kube.

**Comment by herbetom** [comment] 2020-03-13 12:40
I just stumbeld accross this issue while searching a way to override a port. Kinda sad that this isn't possible. Semms to me quite essential.

**Comment by J7mbo** [comment] 2020-03-22 19:05
Because this isn't yet implemented, I had to create to copies of `docker-compose.yml`, remember to use the correct one at any given time, and now update both whenever I want to make a change that is irrelevant to environment.

My use-case is elasticsearch and TLS. Dev uses a self-signed cert so needs a root CA and SSL verification mode set to certificate only, whilst Prod uses letsencrypt TLS set up during provisioning.

Here are my dev environment vars:

```
            - xpack.security.enabled=true
            - xpack.security.transport.ssl.enabled=true
            - xpack.security.transport.ssl.key=certs/key.pem
            - xpack.security.transport.ssl.certificate=certs/cert.pem
            - xpack.security.transport.ssl.certificate_authorities=certs/rootCA.pem
            - xpack.security.transport.ssl.verification_mode=certificate
            - xpack.security.http.ssl.enabled=true
            - xpack.security.http.ssl.key=certs/key.pem
            - xpack.security.http.ssl.certificate=certs/cert.pem
            - xpack.security.http.ssl.certificate_authorities=certs/rootCA.pem
            - xpack.security.http.ssl.verification_mode=certificate
```

Here are my prod vars:

```
            - xpack.security.enabled=true
            - xpack.security.transport.ssl.enabled=true
            - xpack.security.transport.ssl.key=certs/key.pem
            - xpack.security.transport.ssl.certificate=certs/cert.pem
            - xpack.security.http.ssl.enabled=true
            - xpack.security.http.ssl.key=certs/key.pem
            - xpack.security.http.ssl.certificate=certs/cert.pem
```

If I try and run prod with any of the `ssl.certificate_authorities` vars, even as empty strings, elasticsearch will not start. They should not be empty strings, *they simply shouldn't exist*.

Given this use-case, I now have to have a dev docker-compose and a prod docker-compose, which are completely identical bar the above change in environment variables.

It would be very useful to not have to do something like this.

**Comment by mschwartz** [comment] 2020-03-30 20:39
My use case for this missing feature is to have development and production setups.

By default, I want to just type 
```
docker-compose up
```
and be in development mode.  This bind/mounts the source code over the application within the container so I can edit and see the changes happen within the container immediately.

When I go into production mode, I (think I) have to do something like this:
```
docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.production.yml up
```
And the production.yml would remove the binds.

There are probably better ways to achieve this, but this is a real world use case.

I mean, I could have a .development.yml file that I always have to use in development and if I don't it's production.  But then I'm typing the -f x3 all the time, when the short docker-compose up is what I'd like to type 99% of the time.

**Comment by keithy** [comment] 2020-03-31 03:13
You need to have a look at my docker-compose-use script see github.com/keithy/sprankle-pod
a more advanced form is available in https://github.com/keithy/angelbox

**Comment by mschwartz** [comment] 2020-03-31 03:17
Yeah, sh scripts or aliases can soften the sharp edges, but it's still not the same ;)

**Comment by keithy** [comment] 2020-03-31 03:23
its pretty close you can type: `docker-compose-use` whereas a built in would be `docker-compose use`

**Comment by nick-brady** [comment] 2020-05-01 16:50
My use case is I wanted to mount `/etc/letsencrypt` in `docker-compose.yml` and have my `docker-compose.override.yml` remove the bind so that when a developer types `docker-compose up`, they are not trying to mount `/etc/letsencrypt`.

I will end up creating a `docker-compose.production.yml` which does nothing but add the bind mount because of this. Not the biggest deal, but definitely leaves a sour taste. Would appreciate definitive feedback from the docker team on plans here, though silence I suppose is answer enough.

**Comment by mschwartz** [comment] 2020-05-01 16:54
```
   web:
      remove:
          volumes:
              - /the/one:i/want/to/remove
      volumes:
         - /the/one:I/want/to/add
```

**Comment by nick-brady** [comment] 2020-05-01 16:55
Looks like should have done more research. Thank you for documenting that in this thread!

**Comment by mschwartz** [comment] 2020-05-01 16:55
No, that's a suggestion!

It's not implemented that I know of.

**Comment by masto** [comment] 2020-05-03 18:09
This is clearly shouting into the void as evidenced by four years and several people actually writing the code and getting no response on their PRs. But I just ran into this myself so I'm adding my voice to the chorus. Why not this, why not that? My use case is to take a pristine docker-compose.yml that comes from an upstream package I don't control, and put only a minimal set of changes in my production override file to adjust it for my environment. One of those is to delete port mappings I don't want.

Of course, I am capable of solving this in other ways (and have done so to unblock my project) but it introduces more maintenance hassle and additional complexity on top of a system which already has a mechanism for layered configuration.

**Comment by hubertnnn** [comment] 2020-05-26 11:29
@mschwartz
The remove key looks nice, but its still quite limiting (it allows you to remove a component from the service but not a service as a whole).
How about something like this (I assume `!` is not allowed in key names since those should be alphanumeric, so there should be no conflict):

docker-compose.yml:
```
version: '3'
services:
  web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - FOO=foo1
      - BAR=bar1
      - BAZ=baz1
    volumes:
      - .:/var/www/html
  useless:
    image: something-useless
```

docker-compose.override.yml:
```
version: '3'
services:
  !useless: ~       # remove entire useless service
  web:
    !volumes: ~    #remove all volumes
    !ports:            # replace entire list of ports with this
      - 8080:80
    environment:
      - !FOO=abc # replace one env variable
      - !BAR         # remove the other one
```

This will result in following merged yaml
```
version: '3'
services:
  web:
    image: nginx
    ports:
      - 8080:80
    environment:
      - FOO=abc
      - BAZ=baz1
```

**Comment by hinorashi** [comment] 2020-07-31 01:56
any update on progress guys, btw pls stay safe during covid pandemic :whale:

**Comment by rsjohn** [comment] 2020-10-06 15:08
SAD!

**Comment by signalwerk** [comment] 2020-10-07 14:47
@rsjohn Welcome 👋   This is an open source project and we all do our best to keep the spirit high! it's always awesome to encourage and to contribute in an open community. I noticed your comment and would like to invite you to actively participate in the discussion and/or codebase. All opinions and inputs are always welcome. But please consider; people here are often working on a voluntary base to provide you with an awesome product that works out of the box. 

Do you have time to take on that Issue to provide a solution? We would love to have a [Pull reques](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests) on this to get it off the table? That would be super awesome!

**Comment by gemmadlou** [comment] 2021-01-13 10:30
Not too sure if this helps anyone other than myself. Environment variables can be maps so they are overridable:

> I'm using `docker-compose version 1.27.4`.

`docker-compose.yml`
```yaml
environment:
  APP_KEY: ${APP_KEY}
  APP_URL: ${APP_URL}
  OVERRIDE_TEST: "HELLO"
```

In `docker-compose.override.yml`
```yaml
environment:
  OVERRIDE_TEST: null
```

To see the difference run:

```bash
docker-compose config
```

It will appear as null. Then in the box, view the system environment variables by running the container:

```bash
docker-compose run your-service printenv
```

It shouldn't be there.

**Comment by djbios** [comment] 2021-01-27 13:18
Any progress?

**Comment by archfz** [comment] 2021-02-10 19:59
I mean this really should be an easy feature to implement :/

**Comment by gnat** [comment] 2021-02-26 11:52
Encountered this as well- it's an obvious feature that many people need. Added more .yml files as a workaround, but really not ideal!

**Comment by vschoener** [comment] 2021-02-26 14:15
Came across here to remove volumes from override in a specific case I don't need them and unfortunately, we can't.

**Comment by gnat** [comment] 2021-02-26 14:24
> Came across here to remove volumes from override in a specific case I don't need them and unfortunately, we can't.

This was my exact use case too actually, to remove unused volume mounts.

**Comment by Nielio** [comment] 2021-03-22 15:44
> @thomaspeitz or just use yq. you can easily edit parts of yaml with it.
> 
> F.e. Adding image: `yq w -i ./docker-compose.yml services.nginx.image nginx:latest`
> or removing ports: `yq d -i ./docker-compose.yml services.db.ports`

In case someone wants to use this in a dind gitlab-runner.
You have to install it and use a slightly other syntax. Here is a working example for removing a service from a compose from a git submodule.

```yaml
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  STACK_DEV: blabla
  SERVICE_COMPOSE: blabla/docker-compose.yml

stages:
  - compose

compose-develop:
  stage: compose
  before_script:
    - apk update 
    - apk add git jq py3-pip
    - pip3 install yq
    # pull sub repository
    - git submodule update --remote
    # remove traefik from service compose.yml
    - yq -y -i 'del(.services.traefik)' $SERVICE_COMPOSE
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker stack deploy -c $SERVICE_COMPOSE -c compose-dev.yml --with-registry-auth $STACK_DEV
```

**Comment by dm17** [comment] 2021-03-25 22:00
The two main use cases I see in this thread, which I also have, are prod vs dev (with certs vs no/self certs). In my environment, basically all of this stuff is contained in docker-compose.yml's '-labels'... So, perhaps there a way to run a docker-compose disabling the input of all labels?

Adding support, thanks! :)

**Comment by umstek** [comment] 2021-05-10 18:45
I'm new to docker. 

Ended up creating a base `docker-compose.yml` with everything common, `docker-compose.dev.yml` for dev, `docker-compose.prod.yml` for prod, so no `docker-compose.override.yml` involved. 
And created a shell script to start these e.g.: 

```sh
#!/bin/bash

case $1 in
prod)
  docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build
  ;;
*)
  docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
  ;;
esac
```

What are the caveats of this approach? (Haven't encountered any yet.)

**Comment by breuerfelix** [comment] 2021-05-10 19:52
@umstek @dm17 https://github.com/docker/compose/issues/3729#issuecomment-623154878 <- this comment describes it the best

**Comment by dfanica** [comment] 2021-05-12 18:24
So I'm guessing there's not way to remove an option as of yet despite many people requesting this feature?! :sad_panda:

**Comment by dm17** [comment] 2021-05-13 22:15
Asking for clarification on the compose override docs here; seems relevant here: https://github.com/docker/docker.github.io/issues/12845

**Comment by doman18** [comment] 2021-06-09 06:35
I have 4 different environments. Im adding now 5th where i want to remove 'image' section. Removing it from base docker-compose.yml and adding it for all 4 environments by overrides is far from productive solution. Some override with remove option would be perfect solution for such case.

**Comment by gnat** [comment] 2021-06-19 08:04
For removing entire services this seems to work in the latest versions of docker-compose as of this writing.

```yaml
version: "3.9"
services:
  app:
    deploy:
      replicas: 0
```

No solution for volumes that I can see, though.

**Comment by gamesover** [comment] 2021-11-19 16:22
Please keep `override` as is. If you want to extend the `ports`, well, just repeat the old ports in the `.override.yml` file

Now, I can only `extend` ports, rather than `override` ports

**Comment by miaoz2001** [comment] 2022-03-13 02:18
Hi 

It might be just me, but I want to override the `environment` by removing it from the root file, then use env_file in the .dev.yml file. :)
Is there a workaround?

**Comment by jawys** [comment] 2022-04-02 22:46
If I recall correctly, it did not bind the port to any sleep command while using dev containers?🤔

**Comment by MrChrisRodriguez** [comment] 2022-04-21 21:09
I know this is about ports, and someone else was talking about volumes...  in my case, I want to overwrite profiles, another complex type (list). 

I echo other people's sentiments:
- to me, at least, `override` implies replace, not merge, and especially not "replace in some cases and merge in others"
- there should be a way to distinguish between `merge` and `overwrite` behaviors because both are useful

283 thumbs up and counting... that's a lot of thumbs

**Comment by ahmafi** [comment] 2022-06-05 09:18
The word **override** is kinda misleading. With the current behavior of not supporting real overriding (removing and setting something else), I'm using 3 docker files:

`docker-compose.yaml` : base configs that are common between production and development environments.
`docker-compose.dev.yaml` : development environment specifc config.
`docker-compose.prod.yaml`: production environment specifc config.

**Comment by REDLINK** [comment] 2022-06-30 14:04
> For removing entire services this seems to work in the latest versions of docker-compose as of this writing.
> 
> ```yaml
> version: "3.9"
> services:
>   app:
>     deploy:
>       replicas: 0
> ```

Interestingly, the documentation explicitly states that this
> _only takes effect when deploying to a swarm with docker stack deploy, and is ignored by docker-compose up_

Using [profiles](https://docs.docker.com/compose/profiles/) could be an alternative:

```
profiles:
      - disabled
```

Where "disabled" is an arbitrary name for a profile that's never enabled.
Obviously, that doesn't help if you're already using profiles and would need to remove one or all of them.
Anyway, an advantage would be that it can be overridden from the commandline to selectively start a service.

**Comment by kj** [comment] 2022-08-03 14:21
Perhaps there could be something along the lines of `omit_keys` (for excluding) and `pick_keys` key (for including only those specified; in case of large configurations) allowed at any level of nesting in the YAML which applies to the previously specified YAML file. Then you could remove services (in this case a 'foo' service) with:

```
services:
  omit_keys:
    - 'foo'
  bar:
    # ...
```

You could override ports by removing that key from a service:

```
services:
  foo:
    omit_keys:
      - 'ports'
    ports:
      - '8080:8080' # now the only port specified
```

Being usable at any level of nesting would make this very flexible, so you could remove or override just about anything (service, ports, volumes, any arbitrary key), while retaining the merging behaviour where it is desirable.

I haven't thought about this too deeply, so I'm not sure whether it's practical.

**Comment by logopk** [comment] 2022-08-03 20:43
@kj sounds reasonable without problems with backward compatibility

**Comment by osmarcf** [comment] 2022-08-19 14:26
There were several good suggestions about how to handle override. Let me suggest something also (trying to cover some of the cases I've seen reported in this thread):

Considering the default behavior of override is to **merge** properties.
But, **if specified**, a prefix sign would change the default override behavior:
- a `+` sign forces merge with previous contents of the referred property;
- a `~` sign forces replace a previously referred property;
- a `!` sign forces remove a previously referred property.

Unfortunately it does not respect the file pattern backwards compatibility, but it does not change the default behavior.

**Comment by signalwerk** [comment] 2022-08-23 20:33
@osmarcf I think I don't understand 100% your suggested taxonomy. You speak about prefixing the key. right?

Something like that: 

```yaml
services:
  foo:
    "!ports":
      - '8080:8080'
```
Please forgive me if I misunderstood your suggestion. 

Why would we need the `+`? Merging is the default pattern. No?

**Comment by osmarcf** [comment] 2022-08-23 21:00
Yes, @signalwerk !

Sorry that I haven't provided an example, but you understood it.

Considering (order matters):
`
docker compose -f first.yaml -f second.yaml
`

The + sign would serve as an "explicit" merge. Indeed, leaving a key without it would have the same behavior (merge). 

Using `+` sign (default behavior):
first.yaml:
`
services:
  foo:
    ports:
      - '8080:8080'
`

second:yaml
`
services:
  foo:
    ports:
      - '9090:9090'
`

resulting yaml:
`
services:
  foo:
    ports:
      - '8080:8080'
      - '9090:9090'
`

---

The ~ sign would replace any key set in a previous file.

first.yaml:
`
services:
  foo:
    ports:
      - '8080:8080'
`

second:yaml
`
services:
  foo:
    ~ports:
      - '9090:9090'
`

resulting yaml (replace any previous key):
`
services:
  foo:
    ~ports:
      - '9090:9090'
`

---


The `!` sign would remove key set in any previous file.
first.yaml:
`
services:
  foo:
    ports:
      - '8080:8080'
`

second:yaml
`
services:
  foo:
    !ports:
      - '8080:8080'
`

resulting yaml (remove key):
`
services:
  foo:
`

---

Maybe with these examples I could clarify what I thought.

**Comment by signalwerk** [comment] 2022-08-24 02:52
@osmarcf thank you for answering my question and providing the great examples.

**Comment by M-Pixel** [comment] 2022-10-18 05:41
> Best practice is to not include anything in docker-compose.yml that you might not want to have in another environment.

This is certainly the way to go for most software.

When contributing to an open-source project, however, that usually isn't a practical option.

**Comment by CodePint** [comment] 2022-10-26 12:37
Is this every actually going to be implemented? Multi-decade issues like this make me question my faith in humanity.

**Comment by hubertnnn** [comment] 2022-10-26 15:06
> > Best practice is to not include anything in docker-compose.yml that you might not want to have in another environment.
> 
> This is certainly the way to go for most software.
> 
> When contributing to an open-source project, however, that usually isn't a practical option.

No its not. 
Most software would use sensible defaults and allow overwriting them with custom values.
A database will use `/var/lib/mysql` as its data folder by default if you don't explicitly use it.
A web server would listen on port `80` unless you explicitly change it.
An image converter would use 90% quality setting on jpeg unless explicitly set to something else.

**Comment by 4n70w4** [comment] 2022-11-28 07:44
Hi! ANy news?

**Comment by jawys** [comment] 2023-01-13 15:21
bump

**Comment by OpNop** [comment] 2023-01-21 04:57
For me the big issues is trying to remember syntax to use other compose files, what would be nice is if the `docker compose up` command had an easy way to swap the override file

example would be 

`docker compose up`
runs like normal using the optional `docker-compose.override.yml`

`docker compose up dev`
runs `docker compose -f docker-compose.yml -f docker-compose.dev.yml up`

`docker compose up prod`
runs `docker compose -f docker-compose.yml -f docker-compose.prod.yml up`

**Comment by gnat** [comment] 2023-01-21 06:04
In 2023 I simply ship a small `.sh` script to make up for docker-compose shortfalls: https://github.com/gnat/doit

**Comment by InCogNiTo124** [comment] 2023-01-21 09:10
@OpNop how about writing a `dev.env` and a `prod.env` file, with respective `COMPOSE_FILE=...` entries and them just running `docker compose --env-file=prod.env up`

**Comment by CRC-Mismatch** [comment] 2023-02-13 23:53
> > > Best practice is to not include anything in docker-compose.yml that you might not want to have in another environment.
> > 
> > 
> > This is certainly the way to go for most software.
> > When contributing to an open-source project, however, that usually isn't a practical option.
> 
> No its not. Most software would use sensible defaults and allow overwriting them with custom values. A database will use `/var/lib/mysql` as its data folder by default if you don't explicitly set it. A web server would listen on port `80` unless you explicitly change it. An image converter would use `90%` quality setting on jpeg unless explicitly set to something else.

I'm unsure if you disagree with "certainly the way to go for most software" or "however, that usually isn't a practical option", but... I'm giving my 2c anyway :shrug: 

Sometimes, in a corporate team the "sensible default" may be to expose the service in its' default port, since at any given time, some random developer may need to clone the source and quickly reproduce and debug some failures that are happening in production. The real world isn't quite "sensible" as we all would hope it to be...

Sometimes, things can (and do) go wrong in production, and whoever is available will have to fix it ASAP. So, to make things easy, the projects are all created with all dependency services exposed at their default ports, and important non-environment-specific IDE configurations committed. With this, even developers that don't have much experience (if any at all) with Docker and Docker Composer can just clone the project, open it up in the IDE, "press play" (or follow some foolproof 2-step instructions to bring the stack up) and debug whatever they need: send requests to APIs, access the back-offices in their browser, run queries directly in the databases or check whatever else they may need to in any service via local tools, without having to waste time finding out which ports lead to what and modify profiles or set up new connections to "make it work".

It may not seem like it, but this saves a lot of time, usually wasted by an inexperienced (in Docker) developer thinking he's done something wrong and trying all sorts of remedies, or just resorting to "whatever is working" before asking the team; usually flying blind and taking 5x longer to investigate a tiny problem or validate his new feature - and I've seen worse, some times, with no way to tell, the developer "sticks to what they CAN tell" and end up completely reinventing the wheel to solve a basic problem that could be easily noticed with direct access.

OTOH, if an experienced developer has to implement something that requires two projects running locally at the same time, he'll have to edit the committed docker-compose schema and risk committing something that wasn't supposed to be committed, instead of being able to just create a docker-compose.override.yml and override the "other" project's exposed ports with `ports: ~`...

To me, going with "That's how software is supposed to be developed" and "it's best practice to do it like so" are just bad excuses for either "we don't know how to make it work", "we don't want to spend the time and effort implementing it" or "it works good enough as it is, so we don't think it's needed".  :man_shrugging:

**Comment by debbyglance** [comment] 2023-04-16 22:04
Just chiming in to say "me too"

**Comment by ndeloof** [comment] 2023-05-03 08:32
https://github.com/compose-spec/compose-spec/pull/340 has been approved and merged
support in compose-go (https://github.com/compose-spec/compose-go/pull/380) will be available in next release

**Closed by ndeloof** 2023-05-03 08:32 UTC

**Comment by J7mbo** [comment] 2023-05-03 08:38
Damn, I remember reading this in 2016 and 7 years later it's still nice to know that it got in.

**Comment by default-value-serhiia** [comment] 2023-05-24 05:17
Yeah! It finally happened! Thank you!

**Comment by ndeloof** [comment] 2023-06-13 14:20
@hubertnnn yes indeed, `!reset` only can be used reset value to type's default (empty)
to _replace_  port, the simplest option for now is to rely on variables:

```yaml
services:
  foo:
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
```     

so you can run compose with a local `.env` file to set those variable to 8080,8081

**Comment by kj** [comment] 2023-06-13 15:04
I think this is where I was confused too. What if you want to _remove_ a port (or volume, or similar) rather than just replace it? I'm struggling to see how you can actually replace the whole value of ports.

**Comment by vviikk** [comment] 2023-06-26 13:49
For a more complete workaround you can use variables like in @ndeloof's [answer](https://github.com/docker/compose/issues/3729#issuecomment-1589415603)

```
services:
  foo:
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
```

and set the `containerEnv` setting in the `devcontainer.json`.

```jsonc
{
    // ...
    "containerEnv": {
        "HTTP_PORT": "8123"
    }
    // ...
}
```

**Comment by dokgu** [comment] 2023-08-19 04:47
So how are we supposed to override ports using `docker-compose.override.yml`?

I have a `docker-compose.yml` file with a predefined port mappings - those ports are already in use so I need to override them. I don't want to make any modifications to the `docker-compose.yml` file because my changes will get overwritten with updates.

**Comment by ndeloof** [comment] 2023-08-23 10:21
```yaml
services:
  workflow-app:
    ports: !reset [] // empty list won't trigger a parsing error
```

(and please, don't set a `version:` attribute, this is an obsolete practice!)

**Comment by olitomlinson** [comment] 2023-08-23 10:26
@ndeloof awesome thanks so much! Thank you for the guidance around the obsolete practice. Much appreciated.

**Comment by kj** [comment] 2023-08-25 13:58
@ndeloof I just want to check if I understand correctly.
```
ports: !reset []
```

Here, the value `[]` is ignored. It's just the default value for ports. So whatever you pass to ports is ignored, meaning that you cannot override it with a new set of ports. For example:

```
# docker-compose.yml
services:
  foo:
    ports:
      - '1000:1000'
      - '2000:2000'

# docker-compose.override.yml
services:
  foo:
    ports: !reset
      - '1000:1000'
```

The intention being to remove port 2000, but keep port 1000. That isn't possible at all currently (or anything involving replacing the full list)?

**Comment by ndeloof** [comment] 2023-08-25 14:01
> The intention being to remove port 2000, but keep port 1000. That isn't possible at all currently (or anything involving replacing the full list)?

yes indeed, this isn't yet supported.
You will have to use 2 override files, first one to reset to empty list, second one to set port 1000
_or_ maybe you can tweak the original compose file to offer more flexibility via variables ?

**Comment by kj** [comment] 2023-08-25 14:04
Thanks for clarifying @ndeloof (and so quickly!). It's good at least to know for certain that I'm not missing something,

**Comment by ndeloof** [comment] 2023-10-17 14:46
feel free to create an issue on github.com/compose-spec/compose-go for this purpose
I don't have any specific plan for this, but we are debating a major refactoring of compose-go library which could make this easier in the future

**Comment by quarky42** [comment] 2023-11-07 23:24
My development system has https_proxy and http_proxy environment variables set in order for applications (python, npm) to download their dependencies.
Docker Desktop assumes that if I have a proxy defined on the system, come hell or high water it is going to force my containers to have that proxy in them.  On Linux I can add the proxy to the /etc/systemd/system/docker.d/proxy.conf file and Docker will respect the fact that I don't want that environment variable stuffed into my containers.   I haven't found a similar method for Windows yet.  It knows about the proxy so I've got to deal with it in the container.

I need the proxy to be used for build time, and I'm careful to use "ARG" in my Dockerfiles for building so that I can use the proxy during build time and exclude it for runtime, but docker compose has other plans.

Being able to:
`  environment: !reset`
`      - VAR1: var1_value_here`
and not get any other variables besides VAR1 in my container is exactly what I want.  Others that want to inherit environment variables from the host can simply leave off the !reset.

This would mean I could explicitly tell docker to let me have 100% control of what environment variables get defined.

If someone has created the issue over on the compose-spec/compose-go github, can you please link it here as I would like to add my support for this feature.  I have been fighting environment variable proxy garbage off and on for a year and I'm sick of it. I need a solution, like the one proposed above, that works on all OSes regardless of the underlying config.   At the docker-compose.yml and docker-compose.override.yml level I ought to be able to definitively nail down the "truth" of how a container is defined and have it be defined that way on any system I run it.

**Comment by ndeloof** [comment] 2023-11-08 07:36
@quarky42 `HTTP_PROXY` (and related) build args are automatically set based on your client configuration (`~/.docker/config`, `proxies` section`), you don't need those to be declared in your compose file.

**Comment by quarky42** [comment] 2023-11-08 16:57
> @quarky42 `HTTP_PROXY` (and related) build args are automatically set based on your client configuration (`~/.docker/config`, `proxies` section`), you don't need those to be declared in your compose file.

I don't want them to be set.  I don't have them set in ~/.docker/config because that will set them in the containers.... Which is what I don't want.

On Linux, the solution is to set the environment variables in /etc/systemd/system/proxy.conf

This works.  There is no equivalent for Windows.  Having !reset at a block level would ensure that I can create a config that explicitly denies all environment variables.  When working on a project shared by multiple developers, it is very important to be able to have a consistent container generation.


I want to EXCLUDE all (100%) environment variables at the docker-compose.yml level.  Currently, proxy values are being carried into my containers.  Having support for !reset on a block level would ensure that only explicitly set values were used.

**Comment by ndeloof** [comment] 2023-11-08 17:44
Do you have a comparable issue having such variables set when you run a plain `docker buildx build ...` for your Dockerfile(s)?

**Comment by quarky42** [comment] 2023-11-09 05:38
In short: no, we do not build 30 services across 3 nested projects each with about 10 subprojects each by first building each Dockerfile individually, nor are we interested in doing that.

When you have a team of devs using Windows, Linux, and Mac, it is critical to have control at the docker-compose.yml level of what makes it into and doesn't make it into the container.

On Linux and Mac, that control is there.  On Windows Docker Desktop, I have not found a way to prevent it from embedding proxy info when using the latest version of Docker Desktop.

I can get close on Windows, but there is still a variable there that shouldn't be.

**Comment by ndeloof** [comment] 2023-11-09 08:41
my question was not to use this on a daily basis, but to confirm you only get such a variable issue when building with compose, and a plain `docker build` get a "clean" environment

**Comment by quarky42** [comment] 2023-11-09 15:49
Thank you for the clarification. I do appreciate it.  I will have to build an image manually on the CLI as I don't have anything like that.  It'll be Monday before I'm back in the office.

The remote servers have a couple manually built images but those are Linux and I know they are good.   They weren't at first, but I figured out the use of build args plus the systemd level conf file and that fixed them.  Also those get built and tested with a script, so not as much hands on as it could be.

**Comment by paolomainardi** [comment] 2023-12-06 17:15
It works, thanks a lot!

I have just an issue with vscode extension:

![image](https://github.com/docker/compose/assets/8747/be32de38-dc6f-4117-af28-222f674353a2)

It seems that the schema is missing something https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json ?

**Comment by ndeloof** [comment] 2023-12-06 17:27
@paolomainardi `!reset` is a yaml (custom) tag, it is not defined by the (json) schema

**Comment by paolomainardi** [comment] 2023-12-06 17:43
thanks @ndeloof so the issue is with the vscode official docker extension

**Comment by zhfkt** [comment] 2024-03-12 09:57
It is finally supported 

```
services:
  app:
    ports: !override
      - "8443:443" 
```

Pls check - https://docs.docker.com/compose/compose-file/13-merge/#replace-value
