### ISSUE TITLE
`run` / running one off commands on scaled services?

### ISSUE THREAD

**Issue by vincentriemer** [docker/compose#1646] opened 2015-07-04 18:38 UTC
Looking through the documentation & from doing my own testing this doesn't seem possible. Would this be something to look into implementing? I'm currently trying to use this for load testing other services. Doing `docker-compose up --no-deps test` after scaling the service works but the logging stops tailing once one of the containers exits.

**Comment by dnephin** [comment] 2015-09-29 15:06
Yup, there is an issue with the logs when you start new containers. See #1115 and #1866 

Going to close this as a duplicate of #1115

**Closed by dnephin** 2015-09-29 15:06 UTC
