### ISSUE TITLE
[BUG] service can't be used with `extends` as it declare `depends_on`

### ISSUE THREAD

**Issue by r3nor** [docker/compose#11544] opened 2024-02-26 08:56 UTC
### Description

When trying to bring up a compose project that makes use of `extends` feature, I am getting the following error:

```
service "nginx" can't be used with `extends` as it declare `depends_on`
```

### Steps To Reproduce

1. Have a docker-compose.yml project with extends, like this:

```
nginx:
    extends:
      file: ./nginx/compose.yml
      service: nginx
    container_name: "${SERVER_NAME:}-nginx"
    env_file: .env
```

and the nginx/compose.yml:

```
version: "3.9"

services:
  nginx:
    image: nginx:1
    restart: unless-stopped
    depends_on:
      - web_app
    volumes:
      - ./html:/var/www/html
```

2. `docker compose up`

3. See error: service "nginx" can't be used with `extends` as it declare `depends_on`

### Compose Version

```Text
2.24.6
```

### Docker Environment

```Text
N/A
```

**Comment by ndeloof** [comment] 2024-02-26 15:02
This is the expected behavior, see https://github.com/compose-spec/compose-spec/blob/master/05-services.md#restrictions

**Comment by meriouma** [comment] 2024-02-26 17:50
This seems to be a new restriction added in 2.24.6. We have an `extends` combined with `depends_on` and everything was working fine with 2.25.2 and previous versions. Not sure why this wasn't flagged as a breaking change?

**Comment by r3nor** [comment] 2024-02-26 18:05
Yeah, same for me. Was working fine on `2.24.5` and broke on this new `2.24.6` release.

**Comment by meriouma** [comment] 2024-02-26 18:09
This makes reusing blocks much harder, as fragments cannot be used across files. As far as I know, using `extends` was the only way to have reusable `depends_on` blocks while allowing to separate services in multiple files and have a common file to extend from.

**Comment by r3nor** [comment] 2024-02-26 19:20
@meriouma maybe you want to check out include: https://docs.docker.com/compose/compose-file/14-include/

**Comment by nhorton** [comment] 2024-02-27 17:56
> @meriouma maybe you want to check out include: https://docs.docker.com/compose/compose-file/14-include/

That is not sufficient. It is common to do stuff like have an image like "background worker" and then have 3 instances of it - high-pri, medium-pri, and low-pri. You could then have the base depend on stuff like your DB and message bus and such, then just have 3 instances that extend the base. Now you have to repeat those dependencies over and over in the instantiations. This is definitely more degradation in compose.

We have used Compose for development purposes with a Kubernetes cluster for deployment. It deeply feels like Compose has been losing functionality while Kubernetes has been gaining it, and Kind is becoming more and more compelling to replace Compose from these sorts of things.

**Comment by davidlougheed** [comment] 2024-02-27 19:11
encountering this too. why is a breaking change being included in a patch release at all?

**Comment by davidlougheed** [comment] 2024-02-27 19:23
what's also frustrating here is that everything used to work as-intended before compose 2.24 and its use of a not-even-prod-ready compose-go project, but there wasn't really a clear alert that everything was going to break.

**Comment by Leonid99** [comment] 2024-02-28 01:03
> This is the expected behavior, see https://github.com/compose-spec/compose-spec/blob/master/05-services.md#restrictions

@ndeloof So, what is the supported way of extending services that depend on other services?

**Comment by ndeloof** [comment] 2024-02-28 08:48
@Leonid99 there's no way currently

**Comment by luciangabor** [comment] 2024-02-28 09:41
It's possible to merge depends_on "later":

```console

$ find *.yaml -print -exec cat {} \;
compose.yaml
include:
  - path:
      - defs.yaml
      - deps.yaml
defs.yaml
services:
  x:
    image: x

  y:
    image: y
#    depends_on:
#      - x

  z:
   extends: y
deps.yaml
services:
  y:
    depends_on:
      - x

```

```console

$ docker compose config
name: deps
services:
  x:
    image: x
    networks:
      default: null
  "y":
    depends_on:
      x:
        condition: service_started
        required: true
    image: "y"
    networks:
      default: null
  z:
    image: "y"
    networks:
      default: null
networks:
  default:
    name: deps_default

```

**Comment by luciangabor** [comment] 2024-02-28 09:49
... and if you want to "inherit" the depends_on, `deps.yaml` could be like this:

```yaml
services:
  y: &idem
    depends_on:
      - x
  z: *idem

```

**Comment by pironim** [comment] 2024-02-28 12:37
Got this error with ubuntu update 

from docker-compose-plugin (2.24.6-1~ubuntu.22.04~jammy) 
to (2.24.5-1~ubuntu.22.04~jammy)

**Comment by ndeloof** [comment] 2024-02-28 13:17
sure, but the same applies to other resources, without such a constraint:

file.yaml
```yaml
services:
  service:
    image: image
    volumes:
      - hidden:/work

volumes:
  hidden: ...
```

**Comment by luciangabor** [comment] 2024-02-28 13:36
about that, extending services defined like this: https://docs.docker.com/compose/compose-file/05-services/#ipv4_address-ipv6_address doesn't work either, but it's not caught by checks if there's a homonym network around

**Comment by ndeloof** [comment] 2024-02-28 13:38
that's my point: consistency check just validate there's a resource for any declared reference, whenever this might not have been declared in the original compose file. As we already do for networks/volumes, I don't see any reason we don't do the same for dependent services

**Comment by Leonid99** [comment] 2024-02-28 16:06
The problem with this approach is that if more than one service derives
from the base service (and this is always the case — why would you go into
the effort of sharing functionality if there is just one service), you will
need to copy-paste the “depends_on” stanza into each one.
Also, if there is more than one service in the derivation chain, it will
make the derived services unusable on their own, i.e. consider a situation
where you have service “x" extending service “y" which extends service “z”,
all of which depend on the service “foo”. This change moves the “depends_on
foo” logic from z to x. Before this change, you could happily start a
container with services z and y, while after the change, only service x is
usable.

**Comment by davidlougheed** [comment] 2024-02-28 18:36
hmm I removed my `extends` in favour of includes + merging and now I get bizarre network errors where services are not joining some (but not all) of the declared networks, leading to name resolution errors. maybe related, or maybe not

**Comment by felipecrs** [comment] 2024-02-29 18:04
This is the cleanest solution I found for this issue:

```yaml
services:
  app-abstract:
    image: nginx
    profiles: [abstract]
  app-1:
    extends: app-abstract
    profiles: !reset []
    depends_on: ...
  app-2:
    extends: app-abstract
    profiles: !reset []
    depends_on: ...
```

But it's far from ideal having to add and reset `profiles` like this, not to mention VS Code does not like the `!reset` thing.

This is to say that there is no clean solution for this issue, one that would still allow to extend services within the same compose file without having to create extra compose files.

Perhaps, @ndeloof, you can consider allowing services to be marked as `abstract: true`. Such services would not be rendered by docker compose, they'd rather just be useful for other services extend from.

**Comment by silverwind** [comment] 2024-03-01 12:55
Does the change mean that affected `depends_on` never actually worked and can therefore be safely removed? What did compose previously do when it encountered such an `depends_on`?

**Comment by felipecrs** [comment] 2024-03-01 13:01
Extending depends_on was working before this change.

**Comment by rbax** [comment] 2024-03-01 22:34
I want to reuse another developers service without making them change their code. If I 'include' I am stuck with their implementation. why can't I just overwrite with my own 'depends_on' and move on?

**Comment by felipecrs** [comment] 2024-03-01 22:42
BTW I don't think you were able to overwrite `depends_on` before. What you happen is that their `depends_on` would be merged with yours.

**Comment by hapylestat** [comment] 2024-03-10 15:24
example on how to make stupid changes

**Comment by dmitryuk** [comment] 2024-03-11 07:28
@ndeloof please a look for how many linked issues produced this change, I vote for reverting this behavior. Мy company also has tens of projects with currently broken `depends_on`

**Comment by ndeloof** [comment] 2024-03-11 07:33
@dmitryuk already in progress: https://github.com/compose-spec/compose-spec/pull/470

**Comment by darxriggs** [comment] 2024-03-11 07:46
This issue was closed two weeks as go as `not planned`.

Shouldn't it be reopened, now that the relevant restriction in `compose-spec` has been lifted?

**Comment by kierans** [comment] 2024-03-13 01:43
Thanks @ndeloof for fixing the spec. 

The change broke my project as I have the base `docker-compose.yaml` which declares my API server (which `depends_on` a database image) built from the project source (ie: compiling code) and a `.devcontainer/docker-compose-dev.yaml` which `extends` the base service, but changes the `build.target` so that an image is used that has all the developer dependencies and mounts the source files.

This used to work so that the developer image/container would still depend on the DB which worked well for the development team.

**Comment by faelin** [comment] 2024-03-14 21:51
Now that the spec has been updated, is there a projected timeline on updating the compose project to meet the revised spec?

**Comment by ndeloof** [comment] 2024-03-14 21:55
will be part of tomorrow's release

**Comment by faelin** [comment] 2024-03-14 21:56
Thanks for the fast update @ndeloof!

**Comment by ctrlaltf24** [comment] 2024-03-20 22:39
@r3nor Try now, latest published version fixed it for me (2.25.0).
```
$ docker compose version
Docker Compose version v2.25.0
$ docker --version
Docker version 26.0.0, build 2ae903e
```
Thanks @ndeloof !

**Comment by sheyko94** [comment] 2024-03-21 07:22
Hello there, do we have an ETA for the version 2.25 to be released on Docker Desktop? My company heavily depends on this fix, for now I workaround the issue by download **docker-compose** instead and working with it, but the entire company is trained on the platform to use **docker compose** - would be nice to have the fix in place.

**Comment by matthiasPOE** [comment] 2024-03-25 10:20
@ndeloof does this mean we should stop extending services as this feature will be deprecated in future?

**Comment by ndeloof** [comment] 2024-03-25 10:21
@matthiasPOE no, we relaxed this restriction in the spec https://github.com/compose-spec/compose-spec/pull/470
issue is closed by release v2.26.0

**Closed by ndeloof** 2024-03-25 10:21 UTC
Labels: kind/bug, status/0-triage

**Comment by gander** [comment] 2024-03-29 18:32
```shell
/usr/lib/docker/cli-plugins/docker-compose version
```

**Comment by Morriz** [comment] 2024-03-30 14:01
@gander are you referring to OSX Docker Desktop? That location does not exist in my version of Sonoma.

**Comment by gander** [comment] 2024-03-30 14:30
@Morriz 
> @gander are you referring to OSX Docker Desktop? That location does not exist in my version of Sonoma.

Yes, my **Linux Mint** location. Check other from https://github.com/docker/compose or use `find` command.

**Comment by Morriz** [comment] 2024-03-30 17:17
Yeah, tnx. I was able to follow the original install instructions from Docker.

**Comment by beni0888** [comment] 2024-04-02 16:56
Any idea about when the fix will be released in OSX Docker Desktop?

**Comment by ndeloof** [comment] 2024-04-02 17:06
should happen in a few days

**Comment by beni0888** [comment] 2024-04-02 17:24
In case someone else is facing issues because Docker Desktop is still running an old version of the docker-compose plugin, I've found this useful video explaining how to easily upgrade the docker-compose plugin used by Docker Desktop.

**Comment by beni0888** [comment] 2024-04-03 06:36
You're right! Fixed!!
