### ISSUE TITLE
NEVER HAD THIS ISSUE: "image for service has been removed"; "pull access denied" 

### ISSUE THREAD

**Issue by danielmaartens** [docker/compose#7406] opened 2020-04-28 14:12 UTC
@shin- @aanand @bfirsh @mnowster 

# Description of the issue
I have always been able to run the following commands with no issue. I did not need to log in to docker or anything, but now I keep on getting this error:
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/49619761/80494961-930d9880-8967-11ea-91b5-80e5d4b9e1e9.png">

This worked a couple of months ago (which was the last time I had to run these commands for this specific project). I had to recently deploy this app again on a new digital ocean server and now I get the above error with all my dockerized applications.

What exactly can cause this change in behaviour ?

***Here are the commands and relevant files:***

```
docker build -t ipic/site-new .
docker-compose up -d
```

***Relevant Files***

`docker-compose.yml`
```
version: "3.0"

services:
  ipic-site:
    container_name: ipic-site
    image: ipic/site-new:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - 8080:8080
      - 80:80
```

`Dockerfile`
```
FROM php:7-fpm-alpine

RUN mkdir -p app
WORKDIR /app

RUN apk --update add wget \
  curl \
  git \
  grep \
  build-base \
  libmemcached-dev \
  libmcrypt-dev \
  libxml2-dev \
  imagemagick-dev \
  pcre-dev \
  libtool \
  make \
  autoconf \
  g++ \
  cyrus-sasl-dev \
  libgsasl-dev \
  supervisor \
  nodejs \
  npm \
  openssl \
  zip \
  unzip \
  git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN echo "Installing dependencies and setting up app... Get some coffee, this may take a while..."
RUN echo "Installing PHP extensions..."
RUN docker-php-ext-install mbstring pdo pdo_mysql >/dev/null 2>&1
RUN rm /var/cache/apk/*

COPY . /app
COPY .env /app/.env

RUN composer install
RUN npm install

RUN npm run prod

EXPOSE 80
EXPOSE 8080

CMD php artisan serve --host=0.0.0.0 --port=80
```

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b

```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:18:17 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:17:52 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  ipic-site:
    container_name: ipic-site
    environment:
      APP_DEBUG: "true"
      APP_ENV: prod
      APP_KEY: ''
      APP_NAME: Ipic Site
      APP_URL: http://ipicgroup.com
      AWS_ACCESS_KEY_ID: ''
      AWS_BUCKET: ''
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ''
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      DB_CONNECTION: mysql
      DB_DATABASE: ipicgr_db1
      DB_HOST: sql2.jnb1.host-h.net
      DB_PASSWORD: d5f7y19F
      DB_USERNAME: ipicgr_1
      LOG_CHANNEL: stack
      MAIL_DRIVER: smtp
      MAIL_ENCRYPTION: 'null'
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PASSWORD: 'null'
      MAIL_PORT: '2525'
      MAIL_USERNAME: 'null'
      MIX_PUSHER_APP_CLUSTER: '"$${PUSHER_APP_CLUSTER}"'
      MIX_PUSHER_APP_KEY: '"$${PUSHER_APP_KEY}"'
      PUSHER_APP_CLUSTER: mt1
      PUSHER_APP_ID: ''
      PUSHER_APP_KEY: ''
      PUSHER_APP_SECRET: ''
      QUEUE_CONNECTION: sync
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: 'null'
      REDIS_PORT: '6379'
      SESSION_DRIVER: file
      SESSION_LIFETIME: '120'
    image: ipic/site-new:latest
    ports:
    - 8080:8080/tcp
    - 80:80/tcp
    restart: always
version: '3.0'

```

## Steps to reproduce the issue
1. run `git clone https://github.com/danielmaartens/ipic-site-laravel-vue`
2. make a copy of `env.example` and save as `.env`
2. Run `sh run.sh` in root directory.

### Observed result
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/49619761/80495609-6efe8700-8968-11ea-9740-88139c5925b3.png">

### Expected result
```
Successfully built <image id>
Successfully tagged ipic/site-new:latest
Sending build context to Docker daemon  <size>
```

Should not try to pull latest or have to log in. Should just successfully tag the built image as :latest and run the container.

## Additional information

OS: MacOS Mojave 10.14.5

**Comment by thaJeztah** [comment] 2020-04-28 15:41
I see you use the `docker` cli to build the image, and `docker-compose` to use it; do you have a `.env` file in the directory from which you're running `docker-compose up` ? If so, does it contain a `DOCKER_HOST` environment variable? Perhaps `docker-compose` is connecting with a different daemon than your `docker cli` is communicating with.

The "pull access denied" error that's shown indicates that `docker-compose` could not find the image

**Comment by dinyadin** [comment] 2020-04-28 19:17
yes i think @thaJeztah  is correct the docker_host environment variable should be defined

**Comment by thaJeztah** [comment] 2020-04-28 20:45
well, it doesn't have to be set, but if it's set in one case, and not in the other, then it's possible that two different docker daemons are used (which could explain the problem)

**Comment by dinyadin** [comment] 2020-04-28 20:49
yup got it @thaJeztah

**Comment by danielmaartens** [comment] 2020-04-29 07:30
@thaJeztah 

Thank you for your response !

Logically that does seem like the solution ! However, I have never needed to set a docker host so I'm not sure where I can find the appropriate host I'm supposed to use ? Where can I find such a list ? And how do I know I'm using the right one ?

**Comment by thaJeztah** [comment] 2020-04-29 08:38
You wouldn't have to set `DOCKER_HOST` if you want to use the default (both the `docker` cli and `docker-compose` should default to use the `/var/run/docker.sock` unix socket on Linux and macOS, but you can change it, for example, if you have other daemons running (which could be remote).


_However_, it was just an assumption; I previously replied from my phone, but just tried to reproduce your issue, and I saw the same problem. Looking at your reproduction repository, it does `docker build -t ipic/site-new .` followed by `docker-compose up -d`, however, it doesn't check if the `docker build` was successful.

The `docker build` actually fails;

```
Step 7/17 : RUN echo "Installing PHP extensions..."
 ---> Running in 20a9ef6344b2
Installing PHP extensions...
Removing intermediate container 20a9ef6344b2
 ---> d6dcb8733e79
Step 8/17 : RUN docker-php-ext-install mbstring pdo pdo_mysql >/dev/null 2>&1
 ---> Running in 5c7b43ce3d8f
The command '/bin/sh -c docker-php-ext-install mbstring pdo pdo_mysql >/dev/null 2>&1' returned a non-zero code: 1
```

As a result, the `ipic/site-new` image is not built successfully, so doesn't exist, which is causing `docker-compose` to produce that error (it can't find the image it's looking for, so now tries to pull it from Docker Hub, which also fails)

The line that fails in the Dockerfile suppresses all output and errors, so the actual reason for it to fail is not visible; removing the ` >/dev/null 2>&1` from the line;

```dockerfile
RUN docker-php-ext-install mbstring pdo pdo_mysql
```

And trying to build again, shows:

```
checking for oniguruma... no
configure: error: Package requirements (oniguruma) were not met:

Package 'oniguruma', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
The command '/bin/sh -c docker-php-ext-install mbstring pdo pdo_mysql' returned a non-zero code: 1
```

Which may give some clues why it's failing


Overall, I'd recommend;

- consider using `docker-compose up --build -d` instead of building separately. Using the `--build` option will make `docker-compose` build the image before running.
- if you want to use the `docker` cli to build (for example, to take advantage of buildkit when building the image), you can set the `COMPOSE_DOCKER_CLI_BUILD=1` and `DOCKER_BUILDKIT=1` environment variables, or add them to your `.env` file;
    ```
    COMPOSE_DOCKER_CLI_BUILD=1
    DOCKER_BUILDKIT=1
    ```
- if you want to continue using the `run.sh` script, add the `set -e` option to the script; that way the script will fail if any of the steps in the script fails (instead of "silently" continuing with the next step);
    ```bash
    #!/bin/sh
    set -e
    #docker stop ipic-site && docker rm ipic-site
    docker build -t ipic/site-new .
    #docker run -d -p 3300:3300 --name ipic-site ipic/site
    #rm -rf node_modules
    docker-compose up -d
    #npm install
    ```

I'll close this ticket because it's not a bug in docker compose, or docker itself, but feel free to continue the conversation

**Closed by thaJeztah** 2020-04-29 08:38 UTC
Labels: kind/bug

**Comment by danielmaartens** [comment] 2020-04-30 09:37
@thaJeztah 

So I've sorted the build issues out. Got it working locally. But now - any this is probably not the appropriate place to ask this question - I am getting the same issues above when trying to run this command after I run `eval $(docker-machine env ipic-site-new)`.

I use digital ocean for the hosting of this docker container. 

Is this where setting the `DOCKER_HOST` in .env comes in ?

When I run `docker-machine ls`, this is what I get:

![image](https://user-images.githubusercontent.com/49619761/80695901-e0f4de80-8ad6-11ea-8454-c38ab2e7bc8e.png)

Should I the variable in .env then look like this ?:
`DOCKER_HOST=64.225.31.56:2376`

**Comment by thaJeztah** [comment] 2020-04-30 09:47
Yes, `eval $(docker-machine env ipic-site-new)` will set the `DOCKER_HOST` environment variable. It should not be needed to set the `DOCKER_HOST` in your `.env` if you manually switch between environments before run `docker-compose ...`

If you _do_ set it, make sure it matches what `docker-machine env` sets; if you run `docker-machine env ipic-site-new` (without the `eval`) that command shows what environment variables it sets.

However, make sure that building the Dockerfile actually works, because I think that's the root-cause of the issue you were having

**Comment by danielmaartens** [comment] 2020-04-30 09:59
@thaJeztah 

Ah ok. I actually just needed to run the build manually and the `docker-compose up -d`.

It worked !

Thank you so much for your help 🙌🏼
