### ISSUE TITLE
[BUG] compose up --wait fails to deploy service with deploy.replicas: 0 on v2.23.1+

### ISSUE THREAD

**Issue by BodrickLight** [docker/compose#11237] opened 2023-12-01 12:30 UTC
### Description

We use `docker compose up --wait <service>` with a service that has `deploy.replicas` set to 0, in order to deploy the dependencies of the service, but not the service itself.
This worked on v2.23.0, but since updating to v2.23.1+, this now gives an error saying `<compose name> is missing dependency <service>`.

### Steps To Reproduce

1. Create the following `docker-compose.yml`:
```yaml
version: "3"
services:
  service-a:
    image: alpine:latest
    command: yes
  service-b:
    image: alpine:latest
    command: yes
    depends_on:
      service-a:
        condition: service_started
    deploy:
      replicas: 0
```
2. Run `docker compose up --wait service-b`

In `Docker Compose version v2.23.0-desktop.1` the output is:
```
[+] Building 0.0s (0/0)                                                                                                                            docker:default
[+] Running 2/2
 ✔ Network docker-repro_default        Created                                                                                                               0.0s
 ✔ Container docker-repro-service-a-1  Started
```

In `Docker Compose version v2.23.1` and above the output is:
```
[+] Building 0.0s (0/0)                                                                                                                            docker:default
[+] Running 2/2
 ✔ Network docker-repro_default        Created                                                                                                               0.0s
 ✔ Container docker-repro-service-a-1  Started                                                                                                               0.0s
docker-repro is missing dependency service-b
```

### Compose Version

```Text
Docker Compose version v2.23.1
```

### Docker Environment

```Text
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 74
  Running: 6
  Paused: 0
  Stopped: 68
 Images: 261
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.845GiB
 Name: UK-LT145
 ID: fc91ce6b-95e7-4b51-835d-d6cf5c5725a9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Anything else?

I believe #11110 introduced this issue.

**Comment by ndeloof** [comment] 2023-12-04 09:17
https://github.com/docker/compose/pull/11110 indeed introduced this regression, but the root cause is that `service.scale` is not set when you define `service.deploy.replicas` but the code relies on the former attribute 😖
[migration to compose-go/v2](https://github.com/docker/compose/pull/11207) will fix this issue

**Comment by ndeloof** [comment] 2023-12-05 21:57
https://github.com/docker/compose/pull/11207 has been merged, so I'm closing this issue as fixed

**Closed by ndeloof** 2023-12-05 21:57 UTC
Labels: kind/bug, status/0-triage
