### ISSUE TITLE
mount folder with fig vs with docker

### ISSUE THREAD

**Issue by robert-mygind** [docker/compose#938] opened 2015-02-09 13:22 UTC
Hi All

I have a problem when trying to mount a folder with fig vs. with docker. When using docker direct it works.

docker run -p 80:80 -v /Users/name/someproject/:/var/www/ -d eboraas/apache-php --name test1
works fine ...

when doing the same in fig.yml
volumes:
    - /Users/name/someproject/:/var/www/

it do not mount and the folder /var/www still have the original index.html "it works" from apache. 

fig --version
fig 1.0.1

docker --version
Docker version 1.4.1, build 5bc2ff8

**Comment by dnephin** [comment] 2015-02-09 15:35
I suspect this would be fixed by #858

As a workaround you should be able to `fig rm` to remove the old containers and data volumes.

**Comment by dnephin** [comment] 2015-09-04 15:55
We've done a lot of work on volumes since this issue was created. Going to close the issue, but please do re-open if you're still able to reproduce with the latest version.

**Closed by dnephin** 2015-09-04 15:55 UTC
Labels: kind/question
