### ISSUE TITLE
Maintain official packages

### ISSUE THREAD

**Issue by athyuttamre** [docker/compose#2758] opened 2016-01-26 20:42 UTC
I think it's a little strange that we need to install Compose by downloading a GitHub release. Why not package officially for `apt-get`?

**Comment by jrabbit** [comment] 2016-01-26 22:30
there are pypi packages already https://pypi.python.org/pypi/docker-compose

**Comment by athyuttamre** [comment] 2016-01-26 22:43
Yep! However, a package that is aware of operating system versions and corresponding errors would be very helpful. That way we know when `docker-compose` isn't compatible with a new version of say Debian.

**Comment by dnephin** [comment] 2016-01-27 00:37
Closing as duplicate of #2235

**Closed by dnephin** 2016-01-27 00:37 UTC
