### ISSUE TITLE
docker-compose broken on Docker Toolbox 18.06.1-ce Windows 10

### ISSUE THREAD

**Issue by daltonwamser** [docker/compose#6263] opened 2018-10-10 14:45 UTC
Hi, 

Why docker-compose doesn't work on Windows 10?

Thanks
![image](https://user-images.githubusercontent.com/42234489/46744598-bdc3cd80-ccab-11e8-9a84-a33b47b6bdcc.png)

## Context information (for bug reports)

```
Output of "docker-compose version"
```

```
Output of "docker version"
```

```
Output of "docker-compose config"
```

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message

```
(if applicable)
```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

**Comment by shin-** [comment] 2018-10-11 08:48
Duplicate of #6254

**Closed by shin-** 2018-10-11 08:48 UTC
