### ISSUE TITLE
docker-compose --rm always returns 1

### ISSUE THREAD

**Issue by heidarxvpn** [docker/compose#1424] opened 2015-05-18 04:41 UTC
It doesn't matter how I kick it, it always returns 1 and my ansible task fails! However, without `--rm` it returns 0.

docker-compose.yml
```
test:
  image: debian:wheezy
```
Ubuntu 14.04.2 LTS
Docker version 1.6.2, build 7c8fca2
docker-compose 1.2.0
```
root@megabox:~# docker-compose run --rm test true
root@megabox:~# echo $?
1
```

I believe the exit code comes from `compose/cli/main.py:346`, however, `--rm` doesn't seem to affect the exit code so this doesn't make much sense...
```
    ¦   ¦   exit_code = container.wait()
    ¦   ¦   if options['--rm']:
    ¦   ¦   ¦   log.info("Removing %s..." % container.name)
    ¦   ¦   ¦   project.client.remove_container(container.id)
    ¦   ¦   sys.exit(exit_code)
```
How come it's always 1?
It should also be noted that the containers still show up in `docker ps -a` despite using `--rm`, so I'm guessing something is wrong.

I thought it might be apparmor at first so I disabled it `service apparmor teardown` but no change.

Any ideas? Thanks!

**Comment by mattupstate** [comment] 2015-05-18 15:13
I also just came across this. I've tinkered with my installation a bit and so far it initially appears that the issue is with `dockerpty`. If I simply comment out [this line](https://github.com/docker/compose/blob/master/compose/cli/main.py#L345) all seems to work as I would expect just without container `stdout/err` output. However, notice that we never see the `Removing <container name>` output. This indicates to me that `dockerpty` is somehow messing up the output streams. However, the exit code issue is still beyond me at this point.

**Comment by heidarxvpn** [comment] 2015-05-19 01:38
Wait what, you comment out `service.start_container(container)` and it still works!? Actually, I'm not giving it option `-d` so it should never reach that. Or did line 345 change since you posted?

3304c68891a16ad5d3972a95688f2c4ed426d9c6 might be related to this?

**Comment by mattupstate** [comment] 2015-05-19 01:43
No, comment out the `dockerpty` line. Might have mistakenly linked there.

**Comment by heidarxvpn** [comment] 2015-05-19 04:22
I see, thanks. The issue must lie in dockerpty then, it's been updated recently. The only changes from before that I can see are:
https://github.com/d11wtq/dockerpty/commit/4e5f861adf22de8c72f49c79a19c2813fc260031
https://github.com/d11wtq/dockerpty/commit/630afa9ab8f5bb22129fd43d5269face5e3333d4

When I run docker-compose with --verbose the last thing I see is what I suspect this code in dockerpty being called: https://github.com/d11wtq/dockerpty/blob/master/dockerpty/pty.py#L234

I'll open an issue there as well.

**Comment by aanand** [comment] 2015-06-08 15:25
Thanks. Fix is in https://github.com/d11wtq/dockerpty/pull/44.

**Closed** 2015-06-08 20:51 UTC

**Comment by aanand** [comment] 2015-06-09 23:07
RC2 is out with the fix: https://github.com/docker/compose/releases/tag/1.3.0rc2
