### ISSUE TITLE
docker compose ps --services produces empty output (unlike docker-compose v1)

### ISSUE THREAD

**Issue by trysetnull** [docker/compose#9667] opened 2022-07-20 13:52 UTC
**Bug description**

`docker compose ps --services` does not display the services from the `docker-compose.yml` file.
docker-compose v1 does not have this bug.

**Steps to reproduce the issue:**
1. In a folder with a valid docker-compose.yml file (e.g. [vendor/github.com/theupdateframework/notary/docker-compose.yml](https://github.com/docker/cli/blob/4411b515f5e9798f371ca1300589fccd64fe5001/vendor/github.com/theupdateframework/notary/docker-compose.yml))
2. docker compose ps -all --services
3. <services are *not* listed>

**Describe the results you received:**

```
```

**Describe the results you expected:**

```
mysql
signer
server
```

The above expected output was produced by docker-compose v1 (`docker-compose-v1 ps --services`), version follows:

```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional information you deem important (e.g. issue happens only occasionally):**

NA

**Output of `docker compose version`:**

```
Docker Compose version v2.7.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.7.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 51
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24.89GiB
 Name: DE12148
 ID: 4PGT:7KHQ:WS2Z:FELS:LAF7:WHJO:N5S3:PRQV:RJ2Y:ZDHQ:HY3H:RIEM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**

NA

**Comment by glours** [comment] 2022-07-20 14:40
Duplicate of #9395 
You should use `docker compose config --services` if you want to list the services of a compose project, `docker compose ps --services --all` is intended to list running services of a compose stack (regular services and the ones started with oneoff containers)

**Closed by glours** 2022-07-20 14:40 UTC
Labels: kind/bug, Docker Compose V2
