### ISSUE TITLE
Make the composition parts a separate library

### ISSUE THREAD

**Issue by the-destro** [docker/compose#1860] opened 2015-08-12 21:53 UTC
I would like to have a stable python library to submit dictionaries of container configs and have it handle creating a composed set of containers. I have been able to use compose this way before but the internal API changes have been troublesome to keep up with.

**Comment by dnephin** [comment] 2015-08-24 23:47
Going to close as a duplicate of #954, check out the discussion there.

**Closed by dnephin** 2015-08-24 23:47 UTC
