### ISSUE TITLE
Automatic image naming is weird, change it or provide explicit naming option

### ISSUE THREAD

**Issue by JonasT** [docker/compose#1363] opened 2015-04-28 03:06 UTC
I have the following docker-compose.yml:

```
nginx:
  build: .
  ports:
   - "80:80"
```
.. along with this Dockerfile in the same directory:
```
FROM ubuntu

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y nginx

CMD nginx && tail -f /dev/null
```
Now if I do "docker-compose up", I get the following image entry:
```
jonas@cyberman#11: docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
nginx_nginx                        latest              70d6fcf2fc2c        29 minutes ago      261.1 MB
```

"nginx_nginx"? Really? You couldn't just use "nginx" as I named it?
If you really want to have such weird naming schemes, at least let me override it with a proper name.

**Comment by aanand** [comment] 2015-04-28 16:44
Duplicate of #652. In summary: yes, it's annoying, but for now we rely on the naming scheme to keep track of containers. In the next version we're going to switch to using labels (see #1356) and then it'll be possible to implement support for custom container names.

**Comment by Grokzen** [comment] 2015-09-14 08:48
@aanand Any plans to change the naming scheme in the near future via some new options or flags?

A new option in `compose.yml` for `image_name` similar to `container_name` that was implemented would be really nice to have.

**Comment by dnephin** [comment] 2015-09-14 17:51
I think to do this properly we'd want #1403, but that isn't currently possible with docker labels.

Instead of customizing the name, I think I would rather support some way of re-tagging the image to different names (something like #213). That way the "internal" names are consistent, but you can alias the image as anything you want for "external" use.

**Comment by bfirsh** [comment] 2015-09-24 13:08
Thanks for the suggestion, @JonasT. This is covered by #213, as @dnephin suggests, and I have also created https://github.com/docker/compose/issues/2092 to more formally propose this feature.

**Closed by bfirsh** 2015-09-24 13:08 UTC
Labels: area/config, kind/feature
