### ISSUE TITLE
Cannot create container for service. Invalid port specification with 1.13.0

### ISSUE THREAD

**Issue by SysOfM** [docker/compose#4796] opened 2017-05-05 08:47 UTC
I used the docker compose version 1.11 and after upgrading to 1.13.0 I had problems.

`docker-compose --version
docker-compose version 1.13.0, build 1719ceb`

Docker-compose file is version '2.1'.

The new version exits with an error:
```
Starting consul0 ... error
ERROR: for consul0  Cannot create container for service consul0: invalid port specification: "None"
ERROR: Encountered errors while bringing up the project.
```

The port specification of consul0 is:
```
    ports:
      - "8500:8500"
```

Similar problems with all containers, for example with nginx0:
 ```
 nginx0:
    image: nginx:alpine
    container_name: nginx0
    hostname: nginx0
    domainname: xxx.yyy.zzz
    networks:
      internal_network:
        aliases:
          - nginx0.xxx.yyy.zzz
    depends_on:
      - proxy0
    ports:
      - "80:80"
      - "443:443"
```

As far as I know everything should work. But as you see after the upgrade everything broke.
If you need more information feel free to contact.

**Comment by SysOfM** [comment] 2017-05-05 09:08
**Here's some information**

```
$ uname -a
Linux 333f5bb3a5b7 4.9.21-moby #1 SMP Wed Apr 12 01:18:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ docker --version
Docker version 17.04.0-ce, build 4845c56
$ python3 --version
Python 3.4.3
```

```
pip3 install --upgrade docker-compose
Requirement already up-to-date: docker-compose in /usr/local/lib/python3.4/dist-packages
Requirement already up-to-date: docker<3.0,>=2.2.1 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: cached-property<2,>=1.2.0 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: websocket-client<1.0,>=0.32.0 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: colorama<0.4,>=0.3.7 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: six<2,>=1.3.0 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: jsonschema<3,>=2.5.1 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: docopt<0.7,>=0.6.1 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: PyYAML<4,>=3.10 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: requests!=2.11.0,<2.12,>=2.6.1 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: dockerpty<0.5,>=0.4.1 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: texttable<0.9,>=0.8.1 in /usr/local/lib/python3.4/dist-packages (from docker-compose)
Requirement already up-to-date: docker-pycreds>=0.2.1 in /usr/local/lib/python3.4/dist-packages (from docker<3.0,>=2.2.1->docker-compose)
```

Simple example

```
cat docker-compose.yml
version: '2.1'
services:
  tst:
    image: alpine
    ports:
      - "8080:80"
```

```
# docker-compose up
Creating network "123_default" with the default driver
Pulling tst (alpine:latest)...
latest: Pulling from library/alpine
627beaf3eaaf: Already exists
Digest: sha256:58e1a1bb75db1b5a24a462dd5e2915277ea06438c3f105138f97eb53149673c4
Status: Downloaded newer image for alpine:latest
Creating 123_tst_1 ...
Creating 123_tst_1 ... error

ERROR: for 123_tst_1  Cannot create container for service tst: invalid port specification: "None"

ERROR: for tst  Cannot create container for service tst: invalid port specification: "None"
ERROR: Encountered errors while bringing up the project.
```

```
$ docker-compose config

networks: {}
services:
  tst:
    image: alpine
    ports:
    - None/tcp
version: '2.1'
volumes: {}
```

Verbose running:
```
docker-compose --verbose up -d
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.find_config_file: Trying paths: ['/home/xxx/.docker/config.json', '/home/xxx/.dockercfg']
docker.auth.find_config_file: Found file at path: /home/xxx/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Found entry (registry='xxx.yyy.zzz:4567', username='xxx')
docker.auth.parse_auth: Found entry (registry='https://xxx.yyy.zzz', username='xxx')
compose.cli.command.get_client: docker-compose version 1.13.0, build 1719ceb
docker-py version: 2.2.1
CPython version: 3.4.3
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: Experimental=True, KernelVersion=4.9.21-moby, Arch=amd64, Version=17.05.0-ce-rc1, ApiVersion=1.29, GoVersion=go1.7.5, MinAPIVersion=1.12, BuildTime=2017-04-11T20:55:05.654443025+00:00, Os=linux, GitCommit=2878a85
compose.cli.verbose_proxy.proxy_callable: docker info <- ()
compose.cli.verbose_proxy.proxy_callable: docker info -> {'Architecture': 'x86_64',
 'BridgeNfIp6tables': True,
 'BridgeNfIptables': True,
 'CPUSet': True,
 'CPUShares': True,
 'CgroupDriver': 'cgroupfs',
 'ClusterAdvertise': '',
 'ClusterStore': '',
 'ContainerdCommit': {'Expected': '9048e5e50717ea4497b757314bad98ea3763c145',
                      'ID': '9048e5e50717ea4497b757314bad98ea3763c145'},
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('123_default')
compose.cli.verbose_proxy.proxy_callable: docker inspect_network -> {'Attachable': True,
 'Containers': {},
 'Created': '2017-05-05T08:59:02.378041458Z',
 'Driver': 'bridge',
 'EnableIPv6': False,
 'IPAM': {'Config': [{'Gateway': '172.23.0.1', 'Subnet': '172.23.0.0/16'}],
          'Driver': 'default',
          'Options': None},
 'Id': 'ff63b3b078aad6c4f6785f59d000202836afd0e9e04424e5a060cae095ecee90',
 'Ingress': False,
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=123', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=123', 'com.docker.compose.service=tst', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('alpine')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': '',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': None,
            'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
...
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=123', 'com.docker.compose.service=tst', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: {<Service: tst>}
compose.parallel.feed_queue: Starting producer thread for <Service: tst>
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=123', 'com.docker.compose.service=tst', 'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
Creating 123_tst_1 ...
compose.parallel.feed_queue: Pending: {1}
compose.parallel.feed_queue: Starting producer thread for 1
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('alpine')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': '',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': None,
            'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('alpine')
compose.cli.verbose_proxy.proxy_callable: docker inspect_image -> {'Architecture': 'amd64',
 'Author': '',
 'Comment': '',
 'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': None,
            'Env': ['PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'],
...
compose.service.build_container_labels: Added config hash: 5b2dca53818ea7f275fb42520ac84c542243beb4b329d83dc6497a376c0edcf7
compose.cli.verbose_proxy.proxy_callable: docker create_host_config <- (links=[], init=None, group_add=None, mem_swappiness=None, tmpfs=None, cap_drop=None, sysctls=None, dns_opt=None, dns=None, shm_size=None, port_bindings={'None/tcp': [None]}, pids_limit=None, devices=None, userns_mode=None, security_opt=None, memswap_limit=None, cgroup_parent=None, volumes_from=[], mem_limit=None, init_path=None, binds=[], restart_policy=None, extra_hosts=None, cpu_quota=None, cap_add=None, mem_reservation=None, ipc_mode=None, network_mode='123_default', ulimits=None, log_config={'Type': '', 'Config': {}}, pid_mode=None, isolation=None, oom_score_adj=None, read_only=None, dns_search=None, privileged=False)
compose.cli.verbose_proxy.proxy_callable: docker create_host_config -> {'Binds': [],
 'Links': [],
 'LogConfig': {'Config': {}, 'Type': ''},
 'NetworkMode': '123_default',
 'PortBindings': {'None/tcp': [{'HostIp': '', 'HostPort': ''}]},
 'VolumesFrom': []}
compose.service.create_container: Creating 123_tst_1
compose.cli.verbose_proxy.proxy_callable: docker create_container <- (environment=[], image='alpine', volumes={}, ports=[('None', 'tcp')], host_config={'VolumesFrom': [], 'Binds': [], 'Links': [], 'LogConfig': {'Type': '', 'Config': {}}, 'NetworkMode': '123_default', 'PortBindings': {'None/tcp': [{'HostPort': '', 'HostIp': ''}]}}, networking_config={'EndpointsConfig': {'123_default': {'IPAMConfig': {}, 'Aliases': ['tst']}}}, detach=True, labels={'com.docker.compose.version': '1.13.0', 'com.docker.compose.container-number': '1', 'com.docker.compose.oneoff': 'False', 'com.docker.compose.service': 'tst', 'com.docker.compose.config-hash': '5b2dca53818ea7f275fb42520ac84c542243beb4b329d83dc6497a376c0edcf7', 'com.docker.compose.project': '123'}, name='123_tst_1')
Creating 123_tst_1 ... error
compose.parallel.feed_queue: Pending: set()

ERROR: for 123_tst_1  Cannot create container for service tst: invalid port specification: "None"
compose.parallel.parallel_execute_iter: Failed: <Service: tst>
compose.parallel.feed_queue: Pending: set()

ERROR: for tst  Cannot create container for service tst: invalid port specification: "None"
ERROR: compose.cli.main.main: Encountered errors while bringing up the project.
```

**Comment by shin-** [comment] 2017-05-05 18:48
I believe this is a duplicate of #4729

**Closed** 2017-05-05 23:34 UTC
