### ISSUE TITLE
Option to delay startup of service for arbitrary milliseconds

### ISSUE THREAD

**Issue by reflection** [docker/compose#1821] opened 2015-08-06 23:20 UTC
Trying out docker 1.4.0, I noticed that services were starting up so quickly that even with links between containers, sometimes the first service wouldn't be ready for connections before the dependent service was already up.  For example, I have elasticsearch and kafka containers that need to be started first, but they'd still be initializing when other containers would start flooding them with requests.

Can we have an option to delay a service's startup by a configurable amount of milliseconds?  Thanks.

**Comment by thaJeztah** [comment] 2015-08-06 23:24
I think this is a duplicate of #374

**Comment by dnephin** [comment] 2015-08-06 23:33
Yup, closing as duplicate of #374

**Closed by dnephin** 2015-08-06 23:33 UTC
