### ISSUE TITLE
CPU limit (`cpus`) field is not respected in Mac M1

### ISSUE THREAD

**Issue by sumerc** [docker/compose#9490] opened 2022-05-20 13:31 UTC
I have following for my clickhouse deployment:

```
version: "2"
services:

...

clickhouse:
    container_name: 'clickhouse'
    image: clickhouse/clickhouse-server
    cpus: 1
    mem_limit: 3G
    platform: linux/amd64
    ...
```

I can set my memory successfully but cannot set cpu limit with using `cpus` setting as above. I run the above via `docker compose up clickhouse` and then run `docker inspect <container_id> | grep NanoCpus` and always get `0` as result. 

When I ran the same application via `docker run` as following:

```
docker run --cpus=0.25 --platform linux/amd64 -ti .... clickhouse/clickhouse-server
```

I see correct `NanoCpus` value:

```
> docker inspect 3d1 | grep NanoCpus
"NanoCpus": 250000000
```

This is why I thought it might be a docker compose issue.

I have tried installing the latest version of docker-compose for Mac M1:

```
> docker-compose version
Docker Compose version v2.5.1
```

**Comment by sumerc** [comment] 2022-05-23 07:18
Hey @maxcleme ,

Please correct me if I am wrong but IIUC, to set CPU limits on docker compose:

- we need to use compose `v2` in non-swarm mode, (it is not supported anymore)
- we can use `v3` and swarm mode.

But in my example I already used `v2`. Am I missing something? I was using the reference here: https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources

**Comment by maxcleme** [comment] 2022-05-23 07:36
@sumerc,

Sorry for misunderstanding, you should be able to limit cpu using `cpu_count` instead of `cpus`, `cpus` has been [deprecated in compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#cpus).

Moreover, you should be able to do this in v3 as well

**Comment by glours** [comment] 2022-05-23 07:42
In fact Compose V2 is using the Compose Specification so you don't need the [`version` property](https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element) anymore 😉

**Comment by sumerc** [comment] 2022-05-23 07:56
Thanks for the pointers. Actually, setting `cpu_count` seems to change the `CpuCount` field in the `docker inspect` output. However, I still see more than `1 cpu` utilization in `docker stats` output. It reaches to `~%250` when load test in on.

I also read `cpu_count` is a Windows only option here -> https://stackoverflow.com/questions/56682105/whats-the-difference-between-cpus-and-cpu-count-in-docker . Is this information incorrect?

**Comment by sumerc** [comment] 2022-05-24 14:55
A small reproducer that might help us understand if there is really an issue or not:

I am using following application:

```
package main

import (
	"crypto/md5"
	"encoding/hex"
	"io"
	"time"
)

func myhash() {
	for {
		h := md5.New()
		io.WriteString(h, "abababbabababbabaaosdfhjkloasdfjopsdjfopisdjfsjdfjsdofj")
		hex.EncodeToString(h.Sum(nil))
	}
}

func main() {
	go myhash()
	go myhash()
	time.Sleep(100 * time.Second)
}
``` 

The relevant `compose` file:

```
services:
  app:
    container_name: "mycomposecpulimit"
    cpu_count: 1
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
```

And `Dockerfile`

```
FROM golang:1.18-alpine
RUN apk add git
RUN apk add gcc musl-dev
WORKDIR /app
CMD ["go", "run", "main.go"]
```

and when I run the app I see following in `docker stats`

```
f41a41661961   mycomposecpulimit   214.66%   18.61MiB / 5.8GiB   0.31%     876B / 0B         45.1kB / 979kB    19
```

and here is the inspect output:

```
> d inspect f41 | grep "Cpu"
            "CpuShares": 0,
            "NanoCpus": 0,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "CpuCount": 1,
            "CpuPercent": 0,
```

I said this before but when I ran this app with `docker run --cpus=1` CPU does not get beyond `%100` just as expected.

**Comment by laurazard** [comment] 2022-06-15 11:09
I think this might be fixed by https://github.com/docker/compose/commit/638d78516afae1d60f4b142943b6ceac51424714! Please check again after the next release and let us know if the issue is fixed.

**Comment by glours** [comment] 2022-06-24 08:26
Hi @sumerc 
Can you give a try to Compose `v2.6.1` and use the `deploy.limits.cpu` property which is the one intended to limit the usage of the cpu in the container? 
If everything works as expected, can you close the issue?

**Comment by solzun** [comment] 2022-07-13 18:06
@sumerc 
I'm seeing the same thing, the "cpu_count" is being passed as I see from Docker inspect:
...."CpuCount": 4,...

But the actual container will exceed these values.

I saw a lot about how this is no longer supported on Linux (and only applies to Windows), the weird thing is that if you run Docker Compose 1.x (before it was packaged up as an RPM with Docker 20.x), this is passed and honored in Compose format 2.2 through 2.4. So I don't think this is a Docker CE daemon/runtime limitation but Compose is not longer passing it in the format Docker's API picks up and honors judging by the runtime behavior.

I'm still trying to find a reliable way to set cpu limits in Docker Compose 2.x format (not all of us run Swarm and 3.x is not backwards compatible, tons of other links about this issue), using Docker Compose 2.6.x, and on Linux.

**Comment by solzun** [comment] 2022-07-14 16:09
@glours / @sumerc 

Confirmed Docker Compose 2.6.1 works on Linux to restrict the CPU setting while still using Docker Compose 2.x version format using:

>     deploy:
>       resources:
>         limits:
>           cpus: '4'
>           memory: 16384M

In Docker Compose 2.6.0 the above deployment attributes yield:
`"NanoCpus": 4,`

In Docker Compose 2.6.1 the above deployment attributes yield:
`"NanoCpus": 4000000000,`

This restrict memory/CPU fine as far as my testing, thanks for the fix @glours !

**Comment by glours** [comment] 2022-08-01 09:05
@sumerc can we close this issue as this [PR](https://github.com/docker/compose/pull/9552) should fixed it?

**Comment by sumerc** [comment] 2022-08-01 09:11
Hi @glours. Sure. I have not had the chance to test it, but it seems good. Thank you:)

**Closed** 2022-08-01 09:11 UTC
