### ISSUE TITLE
No output from "run" if STDIN is not a TTY

### ISSUE THREAD

**Issue by abesto** [docker/compose#1092] opened 2015-03-11 15:50 UTC
We hit this issue when using `docker-compose run` on Jenkins to run integration tests.

```sh
echo -e "main:\n  image: hello-world" > docker-compose.yml
docker-compose run main < /dev/null
```
produces no output at all. Adding `-T` makes no difference.

A hack to work around the issue (on OSX), sometimes prints only a character "H", sometimes the proper output:
```sh
echo -e "main:\n  image: hello-world" > docker-compose.yml
script -q /dev/null docker-compose run main < /dev/null
```

The same on Linux:
```sh
echo -e "main:\n  image: hello-world" > docker-compose.yml
script -q -c "docker-compose run main" /dev/null < /dev/null
```

**Comment by bschmeck** [comment] 2015-03-13 02:22
I've run into the same problem, and just opened #1103 to stop creating interactive dockerptys when running in an environment without a TTY.

The reason your given examples don't work when given `-T` is because dockerpty expects [multiplexed streams](https://docs.docker.com/reference/api/docker_remote_api_v1.9/#attach-to-a-container) when running without a TTY.  Dockerpty then closes after failing to demux STDOUT.

Dockerpty's demuxer implementation is [here.](https://github.com/d11wtq/dockerpty/blob/master/dockerpty/io.py#L147))

**Comment by emcfins** [comment] 2015-03-26 23:25
# dibs

**Comment by strokirk** [comment] 2015-04-10 08:14
Same for us, running `docker-compose -p ${PROJECT_ID} run -T --rm web py.test --create-db -x` produces no output, which makes figuring out which test failed take extra effort.

**Comment by bschmeck** [comment] 2015-04-10 14:01
FWIW, I traced this issue back to dockerpty: https://github.com/d11wtq/dockerpty/issues/32

When running a manually patched version of dockerpty, I see the full output from Jenkins and haven't run into any problems.

**Comment by emk** [comment] 2015-04-14 13:12
Thank you for figuring this out!

We're also hitting this error when running `docker-compose` under GoCD. Unfortunately, it makes it impossible to debug what our integration/deployment server is doing with Docker.

What steps need to be taken to get all the necessary patches written and merged? I can spend some cycles on this if it helps. `docker-compose` is seriously great, and we'd love to get this fixed.

**Comment by aanand** [comment] 2015-04-14 13:25
https://github.com/d11wtq/dockerpty/issues/32 sounds reasonable to me. Let's give it a shot and see if it breaks anything.

**Comment by emk** [comment] 2015-04-14 13:54
I found a particularly tidy workaround: Install `expect` (on Ubuntu, `sudo apt-get install expect-dev`), and prefix `docker-compose` with `unbuffer`:

```
unbuffer docker-compose run ...
```

This allocates a `pty` and displays the output appropriately.

**Comment by epintos** [comment] 2015-04-21 17:46
Thanks @emk! That workaround worked perfectly well!

**Comment by robwithhair** [comment] 2015-05-18 14:32
I had this same issue @emk 's fix worked fine for me too.  Using docker-compose inside jenkins.

**Comment by dnephin** [comment] 2015-05-31 18:09
The fix for this is included in docker-compose 1.3 as part of #658.

I think we can close this as a duplicate of #658

**Closed by dnephin** 2015-05-31 18:09 UTC

**Comment by robwithhair** [comment] 2015-05-31 20:01
Thanks, sorry for the duplicate issue. Didn't see that one. 

Sent from my iPhone

> On 31 May 2015, at 19:09, Daniel Nephin <notifications@github.com> wrote:
> 
> The fix for this is included in docker-compose 1.3 as part of #658.
> 
> I think we can close this as a duplicate of #658
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--

**Comment by samupl** [comment] 2022-02-16 12:51
Hey, I think this issue might have re-surfaced today.

I'm running the following  versions:

```$ docker version  
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:03 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:48 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
$ docker compose version
Docker Compose version v2.2.3
```

I'm running a pre-commit git hook that runs `pre-commit` inside docker:

```$ cat .git/hooks/pre-commit
#!/bin/bash
set -e

root_dir=$(git rev-parse --show-toplevel)
compose_file=${root_dir}/docker/docker-compose.yaml

docker-compose -f $compose_file run XXX pre-commit
```

Up to this morning I had docker compose v1.19, now I updated to compose v2. Before I updated, everything worked as expected. Right now, if I try to run `git commit -m TEST`, there's no output from docker. If I execute this script manually, it works properly. 

Most likely it has to do with the way `git` spawns the pre-commit script, but still. Adding `-T` makes the output visible.

**Comment by lauer** [comment] 2022-03-02 15:04
I see the same problem with the same docker-compose version - and thanks, the `-T` works solved the issue for now. 

`docker-compose -f $compose_file run -T --rm tests ci/script.sh`
