### ISSUE TITLE
[BUG] ALL containers which use NFS volumes do not start after reboot

### ISSUE THREAD

**Issue by the-hotmann** [docker/compose#11354] opened 2024-01-15 23:41 UTC
### Description

I am currently facing an issue with my Intel NUC running Debian SID that has persisted for about a year. Despite trying various solutions, I have been unable to resolve it satisfactorily.

My configuration is as follows:

```
NUC ==(NFS - docker-compose volume)==> SYNO
```

I run numerous containers within my docker-compose stack, all of which are set to restart with the `restart unless-stopped` policy. However, upon system reboot, all containers with NFS volumes mapped fail to start automatically. They remain inactive unless manually initiated. Interestingly, initiating a manual start or restart at any other time works seamlessly, and everything functions as expected.

I anticipate that all containers should initiate during a system reboot, and suspect there may be an underlying hidden race condition that eludes my detection.

Also it seems this is the very same issue as the issues mentioned here:
1. [LINK1](https://forums.docker.com/t/containers-with-nfs-volumes-wont-start-after-reboot/137604/5)
2. [LINK2](https://forums.docker.com/t/docker-compose-up-stuck-on-starting-when-using-nfs-volume/137374/2)
3. [LINK3](https://www.reddit.com/r/docker/comments/16ez2bb/containers_with_nfs_volumes_wont_start_after/)

### Steps To Reproduce

1. use docker-compose
2. configure any container
3. configure a NFS Volume like this:
```
volumes:

  share:
    name: share
    driver_opts:
      type: "nfs"
      o: "addr=192.168.178.2,nfsvers=4"
      device: ":/volume1/NFS_SHARE/"
```
4. use the named NFS-Volume in the configured container
5. do the restart test (`docker restart container_name`) after restart (`docker ps`)
6. do the reboot test (`reboot`) after reboots (`docker ps`)

### Compose Version

```Text
Docker Compose version v2.24.0
```
```
### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.11-amd64
 Operating System: Debian GNU/Linux trixie/sid
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.95GiB
 Name: h0tmann
 ID: 670157fc-30a9-4aa4-807c-4fa28aec7ec7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
```
### Anything else?

1. [LINK1](https://forums.docker.com/t/containers-with-nfs-volumes-wont-start-after-reboot/137604/5)
2. [LINK2](https://forums.docker.com/t/docker-compose-up-stuck-on-starting-when-using-nfs-volume/137374/2)
3. [LINK3](https://www.reddit.com/r/docker/comments/16ez2bb/containers_with_nfs_volumes_wont_start_after/)

**Comment by ndeloof** [comment] 2024-01-18 07:25
Can you please check this issue doesn't apply to a container created _without_ docker compose, i.e. using a plain `docker volume create ... && docker run ...` ?

**Comment by the-hotmann** [comment] 2024-01-18 10:37
Thanks, I will do so when I am at home and report back.

**Comment by the-hotmann** [comment] 2024-01-20 18:37
Here I am again.

1. I have stopped the whole docker stack
2. I have removed ALL volumes aswell
3. then I have re-created the volumes with the respective `docker volume create` command
4. then I have recreated the container with the respective `docker run` command
5. reboot

result is: the same issue persists!


Here the converted snippets:

`docker volume create`:

```
docker volume create \
  --name share \
  --driver local \
  --opt type=nfs \
  --opt o=addr=addr=192.168.178.2,nfsvers=4 \
  --opt device=":/volume1/SHARE/"
```

`docker run`:

```
docker run -d \
  --name filezilla \
  -p 5800:5800 \
  -e KEEP_APP_RUNNING=1 \
  -e TZ=Europe/Berlin \
  -e LANG=de_DE.UTF-8 \
  -v /var/docker/data/filezilla/:/config/:rw \
  -v share:/storage/SHARE/:ro \
  --ulimit nofile=65536:65536 \
  --restart unless-stopped \
  jlesage/filezilla
```

Same issue, this container does not boot up after reboot, even thou it is set to `--restart unless-stopped`

**Comment by the-hotmann** [comment] 2024-01-20 18:41
So yeah, this might not be a `compose` issue, but a generat docker issue.
I still would like to ask for this:

If you close this issue down, please atleast move or re-create it where it needs to belong to. If not, pleaese at least tell me where the right place would be, so I can re-create it there myself. I don't want it to go under because of beeing created in thewrong place.


Thanks in advance!

**Comment by ndeloof** [comment] 2024-01-20 18:54
Please report on https://github.com/moby/moby (issue can't be transferred as this is a distinct organization)

**Comment by the-hotmann** [comment] 2024-01-21 18:15
Thanks, have done so: https://github.com/moby/moby/issues/47153

Shall I close this issue, or can we leave it open?

**Comment by ndeloof** [comment] 2024-01-22 15:03
better close this one to avoid duplicates and confusion on where the root cause is

**Closed by ndeloof** 2024-01-22 15:03 UTC
Labels: kind/bug, status/0-triage
