### ISSUE TITLE
docker-compose fails reporting "Duplicate bind mount /var/lib/mysql"

### ISSUE THREAD

**Issue by biblyuk** [docker/compose#1785] opened 2015-07-29 15:48 UTC
"docker-compose up" fails reporting "Duplicate bind mount /var/lib/mysql"
while trying to mount "/var/lib/mysql" as host volume for mysql or percona image.

> $ docker-compose up
> Removing db_db_1...
> Recreating ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_ce40d9fe7e_db_db_1...
> Duplicate bind mount /var/lib/mysql

docker-compose.yml
>db:
>  image: mysql
>  environment:
>    MYSQL_ROOT_PASSWORD: root
>  volumes:
>-./data/:/var/lib/mysql/

Running on OSX 10.9.5 with  Boot2Docker-cli version: v1.7.1 (Git commit: 8fdc6f5),
Docker version 1.7.1, build 786b29d,  docker-compose version: 1.3.3.

Is there any way to fix this issue?

**Comment by aanand** [comment] 2015-07-29 16:12
Reproduced locally. Looks like a deduping issue with trailing slashes in paths. Working on a fix.

**Comment by aanand** [comment] 2015-07-29 18:00
Fixed in #1787.

**Closed** 2015-07-30 08:59 UTC
Labels: kind/bug
