### ISSUE TITLE
SWARM.md should mention overlays

### ISSUE THREAD

**Issue by kanzure** [docker/compose#2855] opened 2016-02-08 18:55 UTC
Since "links" are deprecated, seems prudent to mention overlay network in the SWARM.md file?

Alternatively perhaps these links could be mentioned:

* https://docs.docker.com/compose/networking/
* https://docs.docker.com/engine/userguide/networking/get-started-overlay/

The current SWARM.md file is: https://github.com/docker/compose/blob/28e652daec11aca600c1e26251c42565fe9f5fa2/SWARM.md

**Comment by dnephin** [comment] 2016-02-08 20:32
This is being worked on in #2807

Duplicate of #2656

**Closed by dnephin** 2016-02-08 20:32 UTC
