### ISSUE TITLE
local reference to x-networking hostname is missing

### ISSUE THREAD

**Issue by habelson** [docker/compose#2616] opened 2016-01-07 14:25 UTC
If, using a docker-compose.yml file and the --x-networking option, I create 2 containers. Each container will have an entry for the other in their /etc/hosts file correctly (underscore issue aside). However, the entry that container2 has for container1 isn't also in container1s /etc/hosts file. It seems like this should be there for completeness.

Alternatively, would it make sense that, in the absence of an explicit hostname parameter, the hostname of the container is set to the same value as what is added to /etc/hosts in other containers? Or is there a way to set the hostname to that dynamic value (in the case of scaling)?

**Comment by habelson** [comment] 2016-01-07 14:31
sorry, possibly a duplicate of #2551, however that issue seems to be interested in links and not the new networking feature

**Comment by dnephin** [comment] 2016-01-07 15:19
Yes, I think it's a duplicate of #2551, it's something we'd like to get fixed with the new networking alises (#2312, docker/libnetwork#737).

**Closed by dnephin** 2016-01-07 15:19 UTC
