### ISSUE TITLE
docker-compose uses previous volume from Dockerfile instead of the volume from docker-compose.yml

### ISSUE THREAD

**Issue by geertvanheusden** [docker/compose#1882] opened 2015-08-18 09:09 UTC
Hi,

I encountered an issue when using `docker-compose` version 1.4.0.
Let me try to explain it by describing the different steps I took.

* Create a **Dockerfile** with the following content:

```
FROM debian

VOLUME /test

CMD ls -la /test
```
* Create a **docker-compose.yml** file in the same directory with the following content:

```
test:
    build: .
```

* Run the following commands:

```
docker-compose build
docker-compose up
```

* The `ls` command should return zero files which is correct
* Now create a **testsrc** directory with a file in it  and update the **docker-compose.yml** file to:

```
test:
    build: .
    volumes:
      - ./testsrc:/test
```

* Run `docker-compose up` again and you will see that the **test** directory in the container is still empty. This behaviour is unexpected and in my opinion incorrect.

* Run `docker-compose rm` and `docker-compose up` and the result is correct. One file available in the volume on the container.

Removing the `volumes` line from the **docker-compose.yml** file will still result in one file available in the container when you don't execute the `docker-compose rm` command.

If this is not a bug it think the behaviour should be clearly explained in the docs.

Regards,

Geert

**Comment by aanand** [comment] 2015-08-18 13:40
@dnephin Since you worked on the volume copying code - do you think this is a bug? It looks like one to me.

**Comment by dnephin** [comment] 2015-08-18 14:06
I also consider this incorrect behaviour, but I'm not sure if it's a regression with the changes to volumes. I think this maintains the behaviour we've had all along (using `volumes_from`), although I'd have to test it to confirm.

Here https://github.com/docker/compose/blob/1.4.0/compose/service.py#L813 we always override the volumes with any data volumes from the previous container. We could do a more involved comparison, and only override them if the new volume is also a container volume (and not when the new volume is  now a host volume).

**Comment by atomantic** [comment] 2015-08-19 22:40
I'm not even getting the positive test to work. docker-compose isn't mounting the volume at all from the host (OSX).

Dockerfile
```
FROM debian

CMD ls -la /app
```

docker-compose.yml
```
test:
    build: .
    volumes:
      - ./app:/app
```

./app directory has a bunch of files and folders in it.

```
docker-compose build
docker-compose up
```
output:
```
⇒  docker-compose rm; docker-compose build; docker-compose up
Going to remove dockerized_test_1
Are you sure? [yN] y
Removing dockerized_test_1... done
Building test...
Step 0 : FROM debian
 ---> 9a61b6b1315e
Step 1 : CMD ls -la /app
 ---> Using cache
 ---> a7b8cf76749b
Successfully built a7b8cf76749b
Creating dockerized_test_1...
Attaching to dockerized_test_1
test_1 | total 4
test_1 | drwxr-sr-x  2 root staff   40 Aug 19 21:49 .
test_1 | drwxr-xr-x 28 root root  4096 Aug 19 22:40 ..
dockerized_test_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```

Am I doing something wrong?

⇒  docker -v
Docker version 1.8.1, build d12ea79
⇒  docker-compose -v
docker-compose version: 1.4.0

**Comment by brousselle** [comment] 2015-08-26 13:02
i confirm this is incorrect behavior: as if you test it with docker run [...] with all the relevant options,  bypassing docker-compose then it works as expected.
docker 1.7.1 compose 1.4.0

**Comment by gggeek** [comment] 2015-09-03 15:17
I confirm this - or at least similar behaviour.
docker-compose 1.2.0, docker 1.5.0

a) add to docker-compose.yml a volume definition, start the container, realize things do not work (e.g. you mounted the container's /var/log dir to the host, and apache does not start because it expects to find /var/log/apache2)
b) remove the volume definition from docker-compose.yml, use docker -rmi to delete all base images, start again with a docker-compose up

expected situation: the volume which is not defined any more should not interfere with the container

real results: the only way to have the volumes disappear for good is to run 'docker-compose rm -v'

**Comment by dnephin** [comment] 2015-09-03 15:21
@gggeek that scenario was fixed in 1.3.0

If you remove a volume (or change the path), it works correctly after 1.3.0. The last remaining "issue" is that the source of the volume is still preserved. So if you change from a data volume to a host volume that change is not recognized correctly.

**Comment by gggeek** [comment] 2015-09-03 16:26
@dnephin thanks.
When you say that the source is preserved, does it also apply to the case when the volume remains of type data but its source folder on the host changes?

**Comment by dnephin** [comment] 2015-09-03 17:01
Volumes are tracked by their container path, but after 1.3.0 host volumes are not copied over from the previous container.

I believe the only issue is when you start with a data volume at some path, and then try to make it a host volume at the same path.

**Comment by funkyfuture** [comment] 2015-09-25 13:59
> I believe the only issue is when you start with a data volume at some path, and then try to make it a host volume at the same path.

i can confirm for version 1.3.3 that:

- using an image that defines a volume
- in a `docker-compose.yml` that overrides that volume with a host volume
- after that project-folder is moved
- and re-upped
- the overridden volume's host path will still point to the previous path in the host fs
- while host-volumes that are only defined in `docker-compose.yml` are bound to the new project-folder

**Comment by dnephin** [comment] 2015-11-04 22:13
Going to close as a duplicate of #2308.

There will be a warning when a container volume masks an image volume.

**Closed by dnephin** 2015-11-04 22:13 UTC
Labels: area/volumes
