### ISSUE TITLE
building should support `docker build --file` option

### ISSUE THREAD

**Issue by iffy** [docker/compose#1228] opened 2015-03-31 18:30 UTC
I want to mimic something like `docker build --file something.Dockerfile .` in `docker-compose.yml`  But the `--file` option is not supported.  From `docker build --help`:

```
-f, --file=""        Name of the Dockerfile(Default is 'Dockerfile' at context root)
```

I'm happy to attempt a patch.  It looks like a name needs to be chosen for the `docker-compose.yml` name but that docker-py supports this already: https://github.com/docker/docker-py/blob/master/docker/client.py#L304

**Comment by dnephin** [comment] 2015-03-31 20:56
Duplicate of #834

**Closed by dnephin** 2015-03-31 20:56 UTC
