### ISSUE TITLE
Docker Compose fails to pull from private registry when using credential helper

### ISSUE THREAD

**Issue by ilyaBV** [docker/compose#4885] opened 2017-06-01 18:46 UTC
Docker seems to authenticate and pull images fine, but docker-compose fails. The docker container URLs below have been redacted. This issue seems to be present in versions 1.13.0 and 1.14.0rc1.

```
$ docker pull us.gcr.io//mysql:latest
latest: Pulling from /mysql
10a267c67f42: Already exists
c2dcc7bb2a88: Pull complete
17e7a0445698: Pull complete
9a61839a176f: Pull complete
a1033d2f1825: Pull complete
0d6792140dcc: Pull complete
cd3adf03d6e6: Pull complete
d79d216fd92b: Pull complete
b3c25bdeb4f4: Pull complete
02556e8f331f: Pull complete
4bed508a9e77: Pull complete
47cc4a3f7009: Pull complete
Digest: sha256:b899cae2e17184411adde639bd61ba808ada6d01514213c5569862c88a8d5649
Status: Downloaded newer image for us.gcr.io//mysql:latest
```
```
$ docker-compose pull
Pulling mysql (us.gcr.io//mysql:latest)...
ERROR: repository us.gcr.io//mysql not found: does not exist or no pull access
```
```
$ docker-compose --verbose pull
...
compose.cli.verbose_proxy.proxy_callable: docker inspect_image <- ('us.gcr.io//mysql:latest')
compose.service.pull: Pulling mysql (us.gcr.io//mysql:latest)...
compose.cli.verbose_proxy.proxy_callable: docker pull <- ('us.gcr.io//mysql', tag='latest', stream=True)
docker.auth.get_config_header: Looking for auth config
docker.auth.resolve_authconfig: Looking for auth entry for 'us.gcr.io'
docker.auth.resolve_authconfig: No entry found
docker.auth.get_config_header: No auth config found
ERROR: compose.cli.errors.log_api_error: repository us.gcr.io//mysql not found: does not exist or no pull access
```
```
$ cat ~/.docker/config.json
{
	"auths": {},
	"credHelpers": {
		"appengine.gcr.io": "gcr",
		"asia.gcr.io": "gcr",
		"b.gcr.io": "gcr",
		"beta.gcr.io": "gcr",
		"bucket.gcr.io": "gcr",
		"eu.gcr.io": "gcr",
		"gcr.io": "gcr",
		"gcr.kubernetes.io": "gcr",
		"us.gcr.io": "gcr",
		"mirror.gcr.io": "gcr"
	}
}
```

**Comment by shin-** [comment] 2017-06-05 18:05
What does GCR stand for? It seems we might be missing support for their auth method.

**Comment by ilyaBV** [comment] 2017-06-05 18:07
GCR is Google Cloud Registry. I authenticate using this credential helper: https://github.com/GoogleCloudPlatform/docker-credential-gcr

**Comment by shin-** [comment] 2017-06-05 18:42
Thanks! We do have an implementation for credential helpers support, but it seems it is outdated. Can you follow the [instructions](https://github.com/GoogleCloudPlatform/docker-credential-gcr#docker-clients-v111---v112-manual-installation) at the end of the README and check that it works?

**Comment by ilyaBV** [comment] 2017-06-05 18:55
I've updated my config file to resemble the old style:
```
$ cat ~/.docker/config.json
{
	"auths": {
		"https://gcr.io": {},
		"https://us.gcr.io": {}
	},
    "credsStore": "gcr"
}
```

After doing that `docker-compose pull` and `docker pull` work, so this functions as a workaround and confirms that only the old credential helper method is supported.

**Comment by shin-** [comment] 2017-07-07 00:29
This will be fixed in the upcoming 1.15 release.

**Closed by shin-** 2017-07-07 00:29 UTC
Labels: docker-py, kind/parity

**Comment by yachi** [comment] 2017-09-13 05:13
works for me on docker-compose 1.16.1 after running

```
 docker-credential-gcr configure-docker
```

**Comment by suvash** [comment] 2017-09-13 17:01
@yachi can you paste your config ?
`$ cat ~/.docker/config.json`

**Comment by jak** [comment] 2017-09-14 09:47
The issue I've had is Docker for Mac re-installing compose 0.14.0 in /usr/local/bin, so I've had to download the latest docker-compose and put it in a different path so it doesn't re-occur.

**Comment by yachi** [comment] 2017-09-14 10:23
@suvash 
gcloud sdk 170.0.1
config.json: https://gist.github.com/yachi/02a9ca4adf576f546b4188fb859507b6

**Comment by ernsheong** [comment] 2017-10-17 09:39
I've ran `docker-credential-gcr configure-docker` with docker version `17.03.2-ce` but I am still getting the error:

```
repository gcr.io/$PROJECT_ID/$IMAGE_NAME not found: does not exist or no pull access
```

Running `docker pull gcr.io/$PROJECT_ID/$IMAGE_NAME` works just fine.

**Comment by isaacuribe** [comment] 2018-01-17 04:07
I managed to have it working by adding the following volume:

-v ~/:/root

I believe there is an issue for docker-compose not seeing the config files from the host.

**Comment by russell** [comment] 2018-02-13 12:47
When running with

```
$ docker --version
Docker version 17.12.0-ce, build c97c6d6
$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
```

I had to run `docker-credential-gcr configure-docker` then add
```
  "credsStore": "gcr",
```
to ~/.docker/config.json so that `docker-compose build` would work if the base image needed to be fetched from GCR

**Comment by gastlich** [comment] 2018-02-19 11:28
```
gcloud docker --authorize-only
```
will create short-lived access for `['gcr.io', 'us.gcr.io', 'eu.gcr.io', 'asia.gcr.io', 'staging-k8s.gcr.io', 'k8s.gcr.io']`

and will make your `docker-compose` working

**Comment by yanc0** [comment] 2018-05-04 14:57
With the newest gcloud, `gcloud docker --authorize-only` is deprecated. 

Use `gcloud auth configure-docker` instead.

```
WARNING: `gcloud docker` will not be supported for Docker client versions above 18.03.
Please use `gcloud auth configure-docker` to configure `docker` to use `gcloud` as a 
credential helper
```

**Comment by jak** [comment] 2018-05-04 19:58
That method doesn’t work if docker-compose is invoked by another process, such as docker-sync. When the short lived access is removed there will be no workaround.

**Comment by theist** [comment] 2018-05-08 07:57
I've been using docker compose with GCR pulls for a while in CI nodes. What I had to do to get it working was:

At image creation ensure `docker-credential-gcr` is installed and the project is set, Activate a service account and perform a `docker-credential-gcr configure-docker` I needed to use a generated service account json because I was not able to complete the procedure with the default credentials.

Once al configured I had to do a docker login and then docker-compose was able to pull from a private GCR repo

```
gcloud components install docker-credential-gcr --quiet
gcloud config set project my_project
gcloud auth activate-service-account --key-file=/path/to/custom/service-account-key.json
docker-credential-gcr configure-docker

# Once configured and before starting any operation involving pulls

/usr/bin/docker login -u _json_key -p \"$(cat /path/to/custom/service-account-key.json)\" https://eu.gcr.io
```

The last step must be repeated before attempting any interaction with GCR, once logged in, it will work until the server is restarted.

This worked for me, not sure if it is the best option.

**Comment by kilianc** [comment] 2018-07-12 04:33
I can confirm this is still an issue today with `18.05.0-ce` and `1.21.2`

**Comment by shin-** [comment] 2018-07-12 14:11
@kilianc you are probably running into #5930 which is getting fixed in 1.22. You can test the release candidate to confirm.

**Comment by kilianc** [comment] 2018-07-26 23:01
@shin- it doesn't look like I am. I am simply getting a permission denied exactly like described here and I am on 1.22.0

**Comment by lacherogwu** [comment] 2023-09-23 16:07
I experienced something similar. It happened because I had an `.env` file with additional AWS credentials in the same directory, and it appears that docker-compose utilized those credentials.
