### ISSUE TITLE
Pulling an image for a service also pulls images for dependent services

### ISSUE THREAD

**Issue by viranch** [docker/compose#1764] opened 2015-07-24 08:39 UTC
I'm not sure if this a bug or is it intentional. Consider the following docker-compose.yml:

```yml
db:
  image: mysql

web:
  image: nginx
  links:
    - db:database
```

Now when I do a `docker-compose pull web` it also pulls the `mysql` image. This may not be desired in a production system. Pulling both images probably makes sense if `mysql` is not present, but if its present and I want to upgrade just `nginx`, compose should not force me to pull `mysql` also.

Neither can I find a workaround similar to `--no-deps` for the `up` command.

**Comment by viranch** [comment] 2015-07-24 08:41
Oh, btw:

```
$ docker-compose --version
docker-compose version: 1.3.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
$ 
```

**Comment by aanand** [comment] 2015-07-24 09:06
Duplicate of #1752

**Closed by aanand** 2015-07-24 09:06 UTC

**Comment by cweagans** [comment] 2015-10-15 23:06
Just opened a PR for this: #2199
