### ISSUE TITLE
Can no longer reference local image with docker-compose

### ISSUE THREAD

**Issue by MrMMorris** [docker/compose#923] opened 2015-02-05 21:57 UTC
With fig, I could do something like this:

`image: 50ff1e85c429`

and it would use the local image.

Now, with compose 1.1.0-rc2, I get this:

```
Pulling image 50ff1e85c429:latest...
Pulling repository 50ff1e85c429
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 445, in up
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.project", line 183, in up
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 258, in recreate_containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 243, in create_container
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Error: image library/50ff1e85c429:latest not found
```

**Comment by aanand** [comment] 2015-02-06 15:49
Does the image `50ff1e85c429` exist locally?

**Comment by MrMMorris** [comment] 2015-02-06 17:51
@aanand example:

```
$ docker build .
Sending build context to Docker daemon 179.5 MB
Sending build context to Docker daemon
Step 0 : FROM tianon/true:latest
Pulling repository tianon/true
1aac473d5946: Download complete
511136ea3c5a: Download complete
67fbec1390fc: Download complete
Status: Downloaded newer image for tianon/true:latest
 ---> 1aac473d5946
Successfully built 1aac473d5946
```

```
app:
  image: 1aac473d5946
```

```
Pulling image 1aac473d5946:latest...
Pulling repository 1aac473d5946
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 445, in up
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.project", line 183, in up
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 258, in recreate_containers
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.service", line 243, in create_container
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output
  File "/Users/ben/fig/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event
compose.progress_stream.StreamOutputError: Error: image library/1aac473d5946:latest not found
```

**Comment by thaJeztah** [comment] 2015-02-07 22:11
This looks to be the problem;

    Pulling image 1aac473d5946:latest...

Compose(?) automatically adds a `:latest` tag, also if the image is referred to by its ID.

Out of curiosity; have you tried if it works when the *full* ID of the image is used? You should be able to get the full ID via `docker images --no-trunc`.

**Comment by MrMMorris** [comment] 2015-02-07 22:13
```
$ comp up
Pulling image 569734b301027d5e34a5ebba8d4feb4f3a7209efecee56948454cd2513ba2c6a:latest...
Invalid repository name (569734b301027d5e34a5ebba8d4feb4f3a7209efecee56948454cd2513ba2c6a), cannot specify 64-byte hexadecimal strings
```

**Comment by thaJeztah** [comment] 2015-02-07 22:21
Ah, thanks for trying!

I just tried this directly on docker (1.5.0-rc2, on this host, but I don't think this changed after that), and that worked without problems, so I suspect compose is adding the `:latest` here, which is a bug.

@aanand looks to be a bug?

**Comment by aanand** [comment] 2015-02-10 15:24
Compose and the Docker CLI follow the same logic:

1. Try and create a container with the specified image.
2. If the daemon returns a 404, try pulling the image. Before doing so, if no `:` is present in the image name, add `:latest`.
3. Try and create the container again.

You can recreate this same problem with the Docker CLI using a nonexistent ID:

```
$ docker run 0000000000 true
Unable to find image '0000000000:latest' locally
Pulling repository 0000000000
FATA[0002] Error: image library/0000000000:latest not found
```

@MrMMorris: What does `$ docker run 569734b30 true` result in?

**Comment by MrMMorris** [comment] 2015-02-10 20:04
@aanand it results in ... nothing :smile: 
```
$ docker run 569734b30 true
$
```

**Comment by dnephin** [comment] 2015-02-10 20:08
I think this might be a bug here: https://github.com/docker/fig/blob/master/compose/service.py#L465

This was added recently to address the fact that `docker pull` without a tag will download all versions.  We probably need to figure out if the image is a name or the sha before adding latest.

**Comment by aanand** [comment] 2015-02-10 20:53
@dnephin The [relevant logic in Docker](https://github.com/docker/docker/blob/eb79acd7a0db494d9c6d1b1e970bdabf7c44ae4e/api/client/commands.go#L2142-L2145) is the same. That's not the problem.

The problem is that we're adding the `:latest` tag when attempting to create the container, not just when we pull, so IDs will always fail. [The offending lines are here](https://github.com/docker/fig/blob/de07e0471ef02d85c248144959fd6932d8adaaf7/compose/service.py#L456-L457) and were added in 8ebec9a67f470e94c5dd8f446f5f4197d6db486f. We should probably just remove them.

**Comment by dnephin** [comment] 2015-02-10 21:05
Cool, that's the change I was thinking of.  Right, the code I linked is correct for pull (which is how that line is used later on in `create_container()` (https://github.com/docker/fig/blob/de07e0471ef02d85c248144959fd6932d8adaaf7/compose/service.py#L239), but it's wrong for the initial `Container.create()` call. So removing it from `_get_container_create_options()` and just moving it to the `self.client.pull()` makes sense.

**Comment by MrMMorris** [comment] 2015-03-09 20:50
when's the next release? I just re-felt the pain of not being able to reference local images since Auto Builds are

**Comment by MrMMorris** [comment] 2015-03-17 19:38
when is the next release planned? This issue is really harshin' my local dev vibes ;)

**Comment by fullofcaffeine** [comment] 2015-04-08 06:30
+1

**Comment by aanand** [comment] 2015-04-08 10:17
@dnephin Could you make a PR with your fix?

@fullofcaffeine You can work around it for now by `docker tag`-ing your image with a name and referencing that.

**Comment by dnephin** [comment] 2015-04-22 01:37
@aanand sorry it's taken me a while to get to this, I've been quite busy the last couple of weeks, but I plan on getting it into a PR by the end of the weekend at the latest.

**Comment by dnephin** [comment] 2015-04-24 15:52
It turns out that this is actually broken in the docker cli as well (if you try to explicitly pull the image):

```
$ docker pull 8c2e06607696
Pulling repository 8c2e06607696
FATA[0009] Error: image library/8c2e06607696:latest not found 

$ docker images | grep 8c2e06607696
busybox                               latest              8c2e06607696        6 days ago          2.433 MB
```
But we can at least fix it so that it doesn't try to pull when the id is used (since it should already exist).

**Comment by dnephin** [comment] 2015-04-24 15:56
PR #1344 is up

**Comment by thaJeztah** [comment] 2015-04-24 18:59
> It turns out that this is actually broken in the docker cli as well 

Hm not sure it's *broken*; `docker pull` only acceps a *name*, not an ID (see the docs: https://docs.docker.com/reference/commandline/cli/#pull), so thinking of this again; that is expected?

**Comment by thaJeztah** [comment] 2015-04-24 19:05
(Note that `docker run` *does* support both ID and name)

**Comment by dnephin** [comment] 2015-04-24 19:30
Fair enough, broken is probably the wrong word. More that it has the same behaviour as `docker-compose pull`.

**Closed** 2015-04-29 15:46 UTC
Labels: bug, in progress
