### ISSUE TITLE
Stack Trace "ERROR: for web  a bytes-like object is required, not 'str'" 1.25.0-rc4 fails to run basic project

### ISSUE THREAD

**Issue by rfay** [docker/compose#6998] opened 2019-11-04 15:28 UTC
## Description of the issue

docker-compose (macOS) fails with rc4 (Docker Desktop Mac Edge 2.1.5.0). It looks like there's a syntax error or something. 

```
$ docker-compose -f badcompose.yaml  up
Creating ddev-d8composer-db ... done
Creating ddev-d8composer-dba ...
Creating ddev-d8composer-web ...
Creating ddev-d8composer-dba ... done
ERROR: for ddev-d8composer-web  a bytes-like object is required, not 'str'

ERROR: for web  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.36/containers/5154c7d2e17e152a31a3513dad4e4354a4a57ba514b83382faff45eec9bb85d1/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Ports are not available: /forwards/expose/port returned unexpected status: 500'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1106, in up
  File "compose/cli/main.py", line 1102, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[87400] Failed to execute script docker-compose
```

## Context information (for bug reports)

macOS Docker Desktop 2.1.5.0 - on macOS Catalina

**Output of `docker-compose version`**
```
docker-compose version 1.25.0-rc4, build 8f3c9c58
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
No extra config
```

## Steps to reproduce the issue

1. `docker-compose -f badcompose.yaml up`

### Stacktrace / full error message

```
ERROR: for ddev-d8composer-web  a bytes-like object is required, not 'str'

ERROR: for web  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 261, in _raise_for_status
  File "site-packages/requests/models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.36/containers/5154c7d2e17e152a31a3513dad4e4354a4a57ba514b83382faff45eec9bb85d1/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose/service.py", line 625, in start_container
  File "compose/container.py", line 241, in start
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 1095, in start
  File "site-packages/docker/api/client.py", line 263, in _raise_for_status
  File "site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Ports are not available: /forwards/expose/port returned unexpected status: 500'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1106, in up
  File "compose/cli/main.py", line 1102, in up
  File "compose/project.py", line 570, in up
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/project.py", line 556, in do
  File "compose/service.py", line 546, in execute_convergence_plan
  File "compose/service.py", line 467, in _execute_convergence_create
  File "compose/parallel.py", line 112, in parallel_execute
  File "compose/parallel.py", line 210, in producer
  File "compose/service.py", line 465, in <lambda>
  File "compose/service.py", line 457, in create_and_start
  File "compose/service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
[87400] Failed to execute script docker-compose
```

## Additional information

Here's the contents of badcompose.yaml. This exact style of yaml has been working for at least 2 years with various versions of docker and docker-compose.

```
networks:
  default:
    external: true
    name: ddev_default
services:
  db:
    build:
      args:
        BASE_IMAGE: drud/ddev-dbserver-mariadb-10.2:20191007_many_mariadb
        gid: '20'
        uid: '501'
        username: rfay
      context: /Users/rfay/workspace/d8composer/.ddev/.dbimageBuild
    command: ''
    container_name: ddev-d8composer-db
    environment:
      COLUMNS: '117'
      DDEV_PROJECT: d8composer
      LINES: '25'
      TZ: ''
    healthcheck:
      interval: 1s
      retries: 30
      start_period: 20s
      timeout: 2m
    hostname: d8composer-db
    image: drud/ddev-dbserver-mariadb-10.2:20191007_many_mariadb-built
    labels:
      com.ddev.app-type: drupal8
      com.ddev.approot: /Users/rfay/workspace/d8composer
      com.ddev.platform: ddev
      com.ddev.site-name: d8composer
    ports:
    - 127.0.0.1:32768:3306/tcp
    restart: "no"
    stop_grace_period: 60s
    user: '501:20'
    volumes:
    - source: mariadb-database
      target: /var/lib/mysql
      type: volume
      volume:
        nocopy: true
    - source: /Users/rfay/workspace/d8composer/.ddev
      target: /mnt/ddev_config
      type: bind
    - ddev-global-cache:/mnt/ddev-global-cache:rw
  dba:
    container_name: ddev-d8composer-dba
    environment:
      HTTP_EXPOSE: 8036:8036
      PMA_PASSWORD: db
      PMA_USER: db
      TZ: ''
      VIRTUAL_HOST: d8composer.ddev.site,sub1.ddev.site,sub2.ddev.site
    healthcheck:
      interval: 2m
      retries: 1
      timeout: 2s
    hostname: d8composer-dba
    image: drud/phpmyadmin:v1.11.0
    labels:
      com.ddev.app-type: drupal8
      com.ddev.approot: /Users/rfay/workspace/d8composer
      com.ddev.platform: ddev
      com.ddev.site-name: d8composer
    links:
    - db:db
    ports:
    - target: 80
    restart: "no"
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:20191025_mkcert_creation
        gid: '20'
        uid: '501'
        username: rfay
      context: /Users/rfay/workspace/d8composer/.ddev/.webimageBuild
    cap_add:
    - SYS_PTRACE
    container_name: ddev-d8composer-web
    environment:
      COLUMNS: '117'
      DDEV_PHP_VERSION: '7.2'
      DDEV_PROJECT: d8composer
      DDEV_PROJECT_TYPE: drupal8
      DDEV_ROUTER_HTTPS_PORT: '443'
      DDEV_ROUTER_HTTP_PORT: '80'
      DDEV_WEBSERVER_TYPE: nginx-fpm
      DDEV_XDEBUG_ENABLED: "false"
      DEPLOY_NAME: local
      DOCKER_IP: 127.0.0.1
      DOCROOT: web
      HOST_DOCKER_INTERNAL_IP: ''
      HTTPS_EXPOSE: 443:80
      HTTP_EXPOSE: 80:80,8025:8025
      LINES: '25'
      SSH_AUTH_SOCK: /home/.ssh-agent/socket
      TZ: ''
      VIRTUAL_HOST: d8composer.ddev.site,sub1.ddev.site,sub2.ddev.site
    external_links:
    - ddev-router:d8composer.ddev.site
    - ddev-router:sub1.ddev.site
    - ddev-router:sub2.ddev.site
    healthcheck:
      interval: 1s
      retries: 10
      start_period: 10s
      timeout: 2m
    hostname: d8composer-web
    image: drud/ddev-webserver:20191025_mkcert_creation-built
    labels:
      com.ddev.app-type: drupal8
      com.ddev.approot: /Users/rfay/workspace/d8composer
      com.ddev.platform: ddev
      com.ddev.site-name: d8composer
    links:
    - db:db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: '501:20'
    volumes:
    - source: nfsmount
      target: /var/www/html
      type: volume
      volume:
        nocopy: true
    - /Users/rfay/workspace/d8composer/.ddev:/mnt/ddev_config:ro
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - ddev-ssh-agent_socket_dir:/home/.ssh-agent:rw
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  ddev-ssh-agent_socket_dir:
    external: true
    name: ddev-ssh-agent_socket_dir
  mariadb-database:
    name: d8composer-mariadb
  nfsmount:
    driver: local
    driver_opts:
      device: :/System/Volumes/Data/Users/rfay/workspace/d8composer
      o: addr=host.docker.internal,hard,nolock,rw
      type: nfs
```

**Comment by jcsirot** [comment] 2019-11-05 15:24
Hello @rfay 
Thank you for opening this report. Could you provide a smaller Compose file triggering this issue? It seems to be related to the port forwarding issue described here: https://github.com/drud/ddev/issues/1888

**Comment by rfay** [comment] 2019-11-05 18:38
It could certainly be related to the port-forwarding issue in previous docker 2.1.4.0 issue (https://github.com/docker/for-win/issues/4935), although that one did not manifest in the same way - it did not hit a docker-compose problem. 

My bet is that you'll see the problem right away with this docker-compose file; maybe docker is not providing the expected result? I certainly don't doubt that it's docker's fault. Recent edge releases seem to have all had critical issues.

**Comment by eunomie** [comment] 2019-11-05 19:55
I finally found a minimal `docker-compose.yml` file that causes the same issue:

```yml
version: '3.6'
services:
  web:
    image: nginx
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
```

Output:

    ERROR: for 6998_web_1  a bytes-like object is required, not 'str'

With only one port

```yml
version: '3.6'
services:
  web:
    image: nginx
    ports:
    - 127.0.0.1::80/tcp
```

the container is running but the port forwarding doesn't work because of the unknown source port. We can see it with a docker inspect:

```json
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "127.0.0.1",
                        "HostPort": "32772"
                    }
                ]
            },
```

If you set the source port, it just works fine:

```yml
version: '3.6'
services:
  web:
    image: nginx
    ports:
    - 127.0.0.1:80:80/tcp
    - 127.0.0.1:443:443/tcp
```

And inspect looks good:

```json
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "127.0.0.1",
                        "HostPort": "80"
                    }
                ]
            },
```

You can refer to the docker compose documentation about ports to see the different allowed syntaxes: https://docs.docker.com/compose/compose-file/#ports

**Comment by rfay** [comment] 2019-11-05 21:20
Nice work. It would be nice to fix docker-compose to handle this (much) more gracefully of course. 

I do see the empty target port. That's to get an ephemeral port, and it has always worked in previous docker versions. In the context of this product, we can't just be taking up known localhost ports in advance.

**Comment by eunomie** [comment] 2019-11-06 09:40
Ok, so the issue looks like not to be related to random port but with multiple ports exposition.
That's why with the compose file with one random port worked.

It looks like to be related to some changes in Docker Desktop and not in Docker Compose. A ticket has been opened about it. I'll post an update here when I will have more information about it.

**Comment by eunomie** [comment] 2019-11-06 15:23
@rfay The fix should be released as part of the next Edge release.
https://github.com/docker/for-win/issues/4935

**Comment by rfay** [comment] 2019-11-06 16:39
Outstanding, thanks so much @eunomie . Nobody had responded on that issue for 22 days... did it get attended to due to your inquiry? If so, THANKS! And again, thanks for your responsiveness on this.

I hope docker-compose can also be fixed to be more resilient also, even though the underlying flaw is in docker...

**Comment by jmilkiewicz** [comment] 2019-11-13 21:17
facing the problem. Any workaround ?

**Comment by karudonaldson** [comment] 2019-11-13 21:21
> facing the problem. Any workaround ?

Rollback docker to version 2.1.3.0 and everything is fine, test the latest release of docker this morning the bug was still there :(

**Comment by rfay** [comment] 2019-11-18 18:55
Yay, Docker desktop edge 2.1.6.0 resolves this. Thanks so much for your work on  this @jcsirot.

**Comment by gvanto** [comment] 2019-11-19 08:23
I'm using Docker Desktop (Edge) v2.1.6.0 on Mac and also getting this error:

> a bytes-like object is required, not 'str'

**Comment by rfay** [comment] 2019-11-19 14:24
@gvanto try to provide a super-simple docker-compose file that will demonstrate this with 2.1.6.0. @eunomie did this in https://github.com/docker/compose/issues/6998#issuecomment-549992384 - Does that one give you the error? If not, try to trim yours down to get it.

**Comment by gvanto** [comment] 2019-11-19 14:46
@rfay the super-simple docker file of @eunomie does not produce this error (unfortunately). The docker-compose file is rather large, and was working OK until I updated Docker Desktop to this 2.1.6.0 version (from 2.1.4 version I think it was)

**Comment by rfay** [comment] 2019-11-19 14:55
@gvanto Please also try my docker-compose.yaml in the OP, but I think it will work for you. 

After that, the best thing is to try to cut yours down piece by piece. Use the "binary search" method, where you delete half of it (by services probably) and see if the problem is still there. Then do it again. Etc.

**Comment by eunomie** [comment] 2019-11-19 15:12
> @rfay the super-simple docker file of @eunomie does not produce this error

If this simple docker file doesn't produce the error, so it's not the same bug.
I suggest you to open a new issue and add all the details from the issue template.

**Comment by gvanto** [comment] 2019-11-20 11:53
Rolled Docker Desktop back to 2.1.0.5 (stable) and works now ...

Reason for upgrading to Edge was because it has a more recent Kubernetes version (more relevant to k8s documentation out there atm)

**Comment by juanluisbaptiste** [comment] 2019-11-26 05:32
Hi,

I'm having this issue on ubuntu 19.04, docker-compose version:

```

$ sudo docker-compose version
docker-compose version 1.25.0, build 0a186604
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019


```

docker version:

```
$ sudo docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 01:00:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:59:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

Going back to docker-compose 1.4.21 fixes the issue for me.

**Comment by damndaniel1337** [comment] 2019-11-26 17:43
> Hi,
> 
> I'm having this issue on ubuntu 19.04, docker-compose version:
> 
> ```
> 
> $ sudo docker-compose version
> docker-compose version 1.25.0, build 0a186604
> docker-py version: 4.1.0
> CPython version: 3.7.4
> OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
> ```
> 
> docker version:
> 
> ```
> $ sudo docker version
> Client: Docker Engine - Community
>  Version:           19.03.3
>  API version:       1.40
>  Go version:        go1.12.10
>  Git commit:        a872fc2f86
>  Built:             Tue Oct  8 01:00:44 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.3
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.10
>   Git commit:       a872fc2f86
>   Built:            Tue Oct  8 00:59:17 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.10
>   GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
>  runc:
>   Version:          1.0.0-rc8+dev
>   GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```
> 
> Going back to docker-compose 1.4.21 fixes the issue for me.

Which version do you mean? 1.4.21? I got the same version like in your output and it fails with the same error. 
What did you do?

**Comment by damndaniel1337** [comment] 2019-11-26 19:27
> Hi,
> 
> I'm having this issue on ubuntu 19.04, docker-compose version:
> 
> ```
> 
> $ sudo docker-compose version
> docker-compose version 1.25.0, build 0a186604
> docker-py version: 4.1.0
> CPython version: 3.7.4
> OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
> ```
> 
> docker version:
> 
> ```
> $ sudo docker version
> Client: Docker Engine - Community
>  Version:           19.03.3
>  API version:       1.40
>  Go version:        go1.12.10
>  Git commit:        a872fc2f86
>  Built:             Tue Oct  8 01:00:44 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          19.03.3
>   API version:      1.40 (minimum version 1.12)
>   Go version:       go1.12.10
>   Git commit:       a872fc2f86
>   Built:            Tue Oct  8 00:59:17 2019
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.2.10
>   GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
>  runc:
>   Version:          1.0.0-rc8+dev
>   GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
>  docker-init:
>   Version:          0.18.0
>   GitCommit:        fec3683
> ```
> 
> Going back to docker-compose 1.4.21 fixes the issue for me.

Which version do you mean. Version 1.4.2 doesn't work for me because it says "Unsupported config option for services service: 'db'"

**Comment by juanluisbaptiste** [comment] 2019-11-26 21:42
> > Going back to docker-compose 1.4.21 fixes the issue for me.
> 
> Which version do you mean. Version 1.4.2 doesn't work for me because it says "Unsupported config option for services service: 'db'"

I have never said version 1.4.2. Going back from docker-compose 1.25.0 to docker-compose 1.24.1 works for me.

**Comment by kyusupov33** [comment] 2019-11-28 18:53
<img width="733" alt="image" src="https://user-images.githubusercontent.com/29026701/69827522-c0271500-1228-11ea-9dfb-94383e2dc7fb.png">

ERROR: for nginx  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/local/lib/docker/virtualenv/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/docker/virtualenv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/4ad22cdd23306bc704be98bfef2901cbceee964f64374f88cfba5b5671e950c8/start

I have the same error on 2.1.0.5 version :(

**Comment by ian-axelrod** [comment] 2019-12-03 18:01
Any updates on this? I do not experience this issue, but my coworker does. He is on 2.1.6.0.

**Comment by rally25rs** [comment] 2019-12-12 14:43
2.1.7.0 also doesn't work. Unchanged yaml, just upgraded Docker and now nothing works. 😞 
Can we get this issue reopened?

**Comment by catbadger** [comment] 2019-12-17 14:52
Why is this closed?

**Comment by t638403** [comment] 2019-12-19 12:15
I seem to be having the same problem with version `1.25.0`.

docker-compose version:
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.0
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```
docker version:
```
Client:
 Version:           19.03.5-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838
 Built:             Fri Nov 15 03:19:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       633a0ea838
  Built:            Fri Nov 15 03:17:51 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.2.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by xZero707** [comment] 2019-12-19 14:09
Can confirm as well on version 1.25.0, build **b42d419**.

**Comment by davidsilveira** [comment] 2019-12-20 19:41
I've tried to use 1.24.* but the problem persists.

**Comment by davidsilveira** [comment] 2019-12-20 20:01
I've tried to use the version `1.25.1-rc1` but also does not works.

**Comment by FaithPatrick** [comment] 2019-12-23 09:18
I'm having the same problem with docker compose version `1.25.0, build 0a186604`
```
➜  docker-compose -v
docker-compose version 1.25.0, build 0a186604
➜  docker -v
Docker version 19.03.5, build 633a0ea838
```

**Comment by ibreathebsb** [comment] 2019-12-25 12:07
same 
```
docker-compose -v
docker-compose version 1.25.1-rc1, build d92e9bee
docker -v
Docker version 19.03.5, build 633a0ea
```

**Comment by flatline-studios** [comment] 2019-12-28 10:44
Same here.

```
docker-compose -v
docker-compose version 1.25.1-rc1, build d92e9bee

docker -v
Docker version 19.03.5, build 633a0ea
```

Using WSL 2:

```
wsl --list
Windows Subsystem for Linux Distributions:
Ubuntu-18.04 (Default)
docker-desktop-data
docker-desktop
```

**Comment by keyz182** [comment] 2019-12-30 11:14
Appear to be having the same issue here.

Stack Trace:
```
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\requests\models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.38/containers/07da02718216262d9bfa1109b6da73c5bf5a4ad5d1170db34b4d8d1a83fe8490/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose\service.py", line 625, in start_container
  File "compose\container.py", line 241, in start
  File "site-packages\docker\utils\decorators.py", line 19, in wrapped
  File "site-packages\docker\api\container.py", line 1095, in start
  File "site-packages\docker\api\client.py", line 263, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'Ports are not available: listen tcp 0.0.0.0:8545: bind: An attempt was made to access a socket in a way forbidden by its access permissions.'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 1107, in up
  File "compose\cli\main.py", line 1103, in up
  File "compose\project.py", line 573, in up
  File "compose\parallel.py", line 112, in parallel_execute
  File "compose\parallel.py", line 210, in producer
  File "compose\project.py", line 559, in do
  File "compose\service.py", line 546, in execute_convergence_plan
  File "compose\service.py", line 467, in _execute_convergence_create
  File "compose\parallel.py", line 112, in parallel_execute
  File "compose\parallel.py", line 210, in producer
  File "compose\service.py", line 465, in <lambda>
  File "compose\service.py", line 457, in create_and_start
  File "compose\service.py", line 627, in start_container
TypeError: a bytes-like object is required, not 'str'
```

It appears that the format of errors being thrown on container start has changed, such that the message is now bytes rather than str.

`create_api_error_from_http_exception` in the `docker-py` repo seems to handle it correctly by casting to str - https://github.com/docker/docker-py/blob/4.1.0/docker/errors.py#L24.

In compose it's assuming a string - https://github.com/docker/compose/blob/1.25.1-rc1/compose/service.py#L627

The naive fix seems to be to change `ex.explanation` to `str(ex.explanation)`.

**Comment by keyz182** [comment] 2019-12-30 12:20
Just confirmed that making the change outlined above fixed the error, and it now correctly passes through the actual error (`("b'Ports are not available: listen tcp 0.0.0.0:8545: bind: An attempt was made to access a socket in a way forbidden by its access permissions.'")` in my case).

Unable to do a PR currently as I'm having other issues on my system, but it's just a simple one-liner changing `ex.explanation` references to `str(ex.explanation)` in `compose.service.start_container`

**Comment by ulyssessouza** [comment] 2020-01-06 15:16
For the posterity:
Actually that's a problem in the error treatment of a string coming from an APIError.explanation, as @keyz182 mentioned in https://github.com/docker/compose/issues/6998#issuecomment-569649664. By this, the error just masks the real problem. [This PR](https://github.com/docker/compose/pull/7121) should fix the error treatment problem so you can see the real problem. Thank you all for the reportings and even the debugging from @keyz182 !

**Closed** 2020-01-06 15:56 UTC
Labels: kind/bug, status/0-triage

**Comment by danieltsc** [comment] 2020-01-19 07:58
I found a solution that worked well for me on Ubuntu. I saw this error happened only when I restarted docker service without stopping the running containers first. Then, when I tried to start them again, this error occured. I tried to see if my ports are available and not running in the background (using lsof -i:PORT) but nothing showed. But, if I tried this command using sudo ( sudo lsof -i:PORT ), I noticed that some PID's were running in the background. So I just killed them using ( sudo kill -9 PID ) and docker was working again properly. *Just in case someone still gets in trouble, this might help :)*

**Comment by davimello28** [comment] 2020-03-09 05:14
For anyone having the same problem, **check if the ports that you are binding from docker-compose are free in the host machine**.

**Comment by csquan** [comment] 2020-08-12 03:17
same problem，docker-compose version 1.25.0 under ubuntu

**Comment by ulyssessouza** [comment] 2020-08-12 08:14
@csquan Please try with the latest version of `docker-compose`

**Comment by jeandoyon** [comment] 2020-08-21 02:24
@csquan, please make sure your containers are not trying to use a port that is listening on your host. See above answers from danielts.

> I found a solution that worked well for me on Ubuntu. I saw this error happened only when I restarted docker service without stopping the running containers first. Then, when I tried to start them again, this error occured. I tried to see if my ports are available and not running in the background (using lsof -i:PORT) but nothing showed. But, if I tried this command using sudo ( sudo lsof -i:PORT ), I noticed that some PID's were running in the background. So I just killed them using ( sudo kill -9 PID ) and docker was working again properly. _Just in case someone still gets in trouble, this might help :)_

**Comment by sinisimattia** [comment] 2022-01-05 11:20
@jeandoyon's answer was the right one for me. Sure do hope this error could be made more explicative in the future

**Comment by ptandler** [comment] 2022-01-10 12:40
yeah, this can be called a self-explaining and very informative error message from docker-compose ...

Suggestion: what about a more concrete error message such as "port xyz already in use"

**Comment by chris-crone** [comment] 2022-01-10 12:46
👋 I'd recommend trying Compose v2 instead of Python Compose (v1). The error messages should be better there. For Linux you can download it [here](https://github.com/docker/compose/releases) (it will be in the packages soon) and it's included in Docker Desktop.

**Comment by ronaldaraujo** [comment] 2022-05-03 23:17
In this case, there was a container starting automatically. That is, when I started my work container the error was displayed.

Try running `docker ps -a` and check that there is no other container using the same port.

Hope this helps.

**Comment by anydev1103** [comment] 2022-06-07 19:48
Thanks a lot it works. I noticed my 80 port is occupied by other process, I killed, and it works.

> @csquan, please make sure your containers are not trying to use a port that is listening on your host. See below answer from danielts.
