### ISSUE TITLE
Linked container is not recreated when another linked container is recreated

### ISSUE THREAD

**Issue by kennu** [docker/compose#757] opened 2014-12-26 05:13 UTC
There seems to be a dependency problem with a Fig configuration that has one shared database container and two application containers using it. When one of the application containers is recreated (with fig up -d), Fig also recreates the shared database container, but it does not recreate the other application container. This causes the Docker link to go stale, and the non-recreated application no longer works.

I think that when Fig recreates a container, it should also recreate all the containers that are linked to it. Otherwise they stop working.

**Comment by aanand** [comment] 2015-01-05 12:24
OK, so if I understand it right, the problem is that if we have this `fig.yml`:

```yaml
db:
  ...

appA:
  links: ["db"]

appB:
  links: ["db"]
```

and I type `fig up -d appA` while everything's running, then `db` and `appA` will be recreated, but `appB` won't. In which case, yep, that's a bug.

Long-term, the solution I'd prefer is for Fig to determine that we don't *need* to recreate `db` - because no configuration has changed - and only recreate `appA`.

Still, `fig up -d db` will still need to recreate `appA` and `appB`. So `fig up` should probably recreate downstream containers.

(`fig up --no-recreate` doesn't need to do this, though. Just thinking out loud.)

**Comment by kennu** [comment] 2015-01-18 17:35
@aanand Yes, that's exactly the problem. My workaround is to manually recreate all the linked containers as "fig up -d appA appB" but it's easy to accidentally forget some of them, as every deployment script would need to know about all the linked apps.

**Comment by dnephin** [comment] 2015-09-18 20:40
This should be fixed in 1.4.0.  The default (with no services specified) will recreate the containers that have changed and any containers that depend on them.

**Closed by dnephin** 2015-09-18 20:40 UTC
