### ISSUE TITLE
Add pre/post command option

### ISSUE THREAD

**Issue by blackrosezy** [docker/compose#468] opened 2014-09-03 04:06 UTC
This is an idea to have options to run a command on `fig up` /  `fig stop` so script have a chance to do some prep.
e.g.:
```
pre-command: cp /root/.ssh/id_rsa .
post-command: do some cleanup, send email notification, etc.

web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
```
What do you think?

##### Update:
The `pre-command` and `post-command` will be run on host machine, not container.

**Comment by dnephin** [comment] 2015-09-01 15:05
Thanks for the feature suggestion!
I think this is a duplicate of #1341

I think we're going to enable this with #1510 instead.

**Closed by dnephin** 2015-09-01 15:05 UTC
