### ISSUE TITLE
Remove linked services when using run --rm.

### ISSUE THREAD

**Issue by brunocascio** [docker/compose#4182] opened 2016-11-24 19:13 UTC
**Steps to reproduce:**

```
backend_mongo:
    extends:
      file: common.yml
      service: mongo
    volumes:
      - mongo_data_dev:/data/db
    env_file:
      - .env.development

backend_api:
    extends:
      file: common.yml
      service: api
    depends_on:
      - backend_mongo
    links:
      - backend_mongo:mongo
    env_file:
      - .env.development
```

Run: `docker-compose run --rm backend_api <command>` 

It will remove the `backend_api` container but not the `backend_mongo` container.

Is it possible to remove them? Maybe, using `--remove-links` flag with something like `--new-linked-services` flag to prevent that the command remove another container already running.

**Comment by aramboi** [comment] 2017-02-13 15:12
Duplicate of https://github.com/docker/compose/issues/2791 (?)

**Closed** 2017-02-17 02:25 UTC
Labels: duplicate

**Comment by asjp** [comment] 2019-06-12 14:03
This problem still exists.

But the workaround has changed slightly, you now need:

`$ docker-compose rm -f -s`

to stop and force-remove all services.
