### ISSUE TITLE
V1 run.sh environment propagation breaks on multiline variables

### ISSUE THREAD

**Issue by lightoze** [docker/compose#9103] opened 2022-01-12 11:35 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

It's impossible to run container version of docker-compose when there is a multiline variable in the environment.

Suggested fix is to change ENV_OPTIONS command to the following:
```bash
printenv | sed -E "/^PATH=.*/d; /^\w+=.*/!d; s/^/-e /g; s/=.*//g; s/\n/ /g"
```

**Steps to reproduce the issue:**
```bash
$ export TEST=$'hello\ncruel world'
$ docker-compose --help
Unable to find image 'world:latest' locally
```

**Comment by mucst** [comment] 2022-01-13 11:52
Duplicate of issue https://github.com/docker/compose/issues/9106

**Comment by lightoze** [comment] 2022-01-13 12:32
Indeed we reported the same issue just a few hours in between.

I have now incorporated this workaround into my build script which patches docker-compose startup script, you can give it a try too:
```bash
sed -ri 's/^ENV_OPTIONS=.*/ENV_OPTIONS=\$(printenv | sed -E "\/^PATH=.*\/d; \/^\\w+=.*\/!d; s\/^\/-e \/g; s\/=.*\/\/g; s\/\\n\/ \/g")/' /usr/local/bin/docker-compose
```

**Comment by mucst** [comment] 2022-01-13 12:48
Hmm  I think there might be an error in the above snipped:
```
$ sed -ri 's/^ENV_OPTIONS=.*/ENV_OPTIONS=\$(printenv | sed -E "\/^PATH=.*\/d; \/^\\w+=.*\/!d; s\/^\/-e \/g; s\/=.*\/\/g; s\/\\n\/ \/g")/' /usr/local/bin/docker-compose

sed: couldn't open temporary file /usr/local/bin/sed7PVz58: Permission denied
```

The innermost "sed" might have an error in it?
```
$ printenv | sed -E "\/^PATH=.*\/d; \/^\\w+=.*\/!d; s\/^\/-e \/g; s\/=.*\/\/g; s\/\\n\/ \/g"

printenv | sed -E "\/^PATH=.*\/d; \/^\\w+=.*\/docker-compose; s\/^\/-e \/g; s\/=.*\/\/g; s\/\\n\/ \/g"
sed: -e expression #1, char 80: unterminated address regex
```

Do you, by the have have docker-compose installed as container? E.g. Is docker-compose is a script in /usr/local/bin ? Then you might want to see the "sed" that chains up env vars for the container (line 74)

**Comment by lightoze** [comment] 2022-01-13 12:56
The build is running inside a docker:20.10-dind container, complete docker-compose install script is the following:
```bash
curl -L --fail https://github.com/docker/compose/releases/download/1.29.2/run.sh -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
# https://github.com/docker/compose/issues/9103
sed -ri 's/^ENV_OPTIONS=.*/ENV_OPTIONS=\$(printenv | sed -E "\/^PATH=.*\/d; \/^\\w+=.*\/!d; s\/^\/-e \/g; s\/=.*\/\/g; s\/\\n\/ \/g")/' /usr/local/bin/docker-compose
```

It looks like there's some problem with sed attempting to create a temporary file. The second problem is because of character escaping, see original issue description for unescaped version.

**Comment by lightoze** [comment] 2022-01-13 14:14
Unfortunately this does not work in busybox (i.e. alpine based images) for two reasons:
1. printenv does not have --null option, but you can use `env -0` instead which seems to be more portable
2. busybox sed cannot handle null-terminated lines, so without installing GNU sed (`apk add sed`) this command would fail

In my solution updated docker-compose:74 looks like this instead:
```bash
ENV_OPTIONS=$(printenv | sed -E "/^PATH=.*/d; /^\w+=.*/!d; s/^/-e /g; s/=.*//g; s/\n/ /g")
```
What it does is simply deletes any line not matching the `^\w+=.*` pattern.

And another command is just to patch the script in place without having to open the editor, so you can easily include it in your build script.

**Comment by ndeloof** [comment] 2022-01-14 08:16
closing as duplicate

**Closed by ndeloof** 2022-01-14 08:16 UTC
Labels: Docker Compose V1
