### ISSUE TITLE
Container name restrictions

### ISSUE THREAD

**Issue by runningman84** [docker/compose#1384] opened 2015-05-03 17:57 UTC
Why am I not allowed to use these names?
```
~/dev/docker/project$ docker-compose up 
Invalid service name "piwik_data" - only [a-zA-Z0-9] are allowed
~/dev/docker/project$ docker-compose up 
Invalid service name "mysql-data" - only [a-zA-Z0-9] are allowed
~/dev/docker/project$ docker-compose up 
Invalid service name "piwik_data" - only [a-zA-Z0-9] are allowed
```

**Comment by dnephin** [comment] 2015-05-03 18:09
Duplicate of #869, #652, #799 and many others. See some discussion in those tickets.

**Closed by dnephin** 2015-05-03 18:09 UTC

**Comment by aanand** [comment] 2015-06-05 13:39
See https://github.com/docker/compose/issues/1519

**Comment by GInxh** [comment] 2018-07-25 19:50
It looks like docker kicks back an error when the header under the services that comes before the container name, differs from the container-name, that is the same as this error. That can be confusing for people. 

it is not a container name restriction, it is a restriction around the header for the container name, and the explicit container name differing that kicks back "invalid service name only [a-zA-Z0-9] are allowed", even if both comply by those standards, but differ in their conventions.
