### ISSUE TITLE
Fails to pull from private container registry

### ISSUE THREAD

**Issue by justingood-gfs** [docker/compose#6202] opened 2018-09-18 18:44 UTC
# Problem<a id="sec-1"></a>

`docker-compose` cannot pull from private container registry (gcp).

## Similar closed issues<a id="sec-2"></a>

-   <https://github.com/docker/compose/issues/4885>
-   <https://github.com/docker/compose/issues/5875>

## Versions<a id="sec-3"></a>

```bash
# mac-os : 10.13.6 (17G65)
# docker-machine: 0.15.0

$ docker --version
Docker version 18.06.1-ce, build e68fc7a

$ docker-compose --version
docker-compose version 1.22.0, build f46880f
```

## Docker credential gcloud<a id="sec-4"></a>

```bash 
echo gcr.io | docker-credential-gcloud get
{
  "Secret": "~~omitted~~",
  "Username": "_dcgcloud_token"
}
```

## Docker pull<a id="sec-5"></a>

```bash
$ docker pull gcr.io/my-gcp-container-registry-project/php:7.1.19-0-fpm
7.1.19-0-fpm: Pulling from my-gcp-container-registry-project/php
Digest: sha256:~~~~omitted~~~~
Status: Image is up to date for gcr.io/my-gcp-container-registry-project/php:7.1.19-0-fpm
```

## Docker compose pull<a id="sec-6"></a>

```bash
$ docker-compose --verbose build
...
docker.utils.config.find_config_file: Trying paths: ['/Users/justin/.docker/config.json', '/Users/justin/.dockercfg']
docker.utils.config.find_config_file: Found file at path: /Users/justin/.docker/config.json
docker.auth.load_config: Found 'credHelpers' section
...
compose.service.build: Building drupal
compose.cli.verbose_proxy.proxy_callable: docker build <- (path='/Users/justin/projects/project/drupal', tag='project_drupal', rm=True, forcerm=False, pull=False, nocache=False, dockerfile=None, cache_from=None, labels=None, buildargs={}, network_mode=None, target=None, shmsize=None, extra_hosts=None, container_limits={'memory': None}, gzip=False, isolation=None, platform=None)
docker.api.build._set_auth_headers: Looking for auth config
docker.api.build._set_auth_headers: Sending auth config ()
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.30/build?t=project_drupal&q=False&nocache=False&rm=True&forcerm=False&pull=False HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker build -> <generator object APIClient._stream_helper at 0x10c5525c8>
Step 1/6 : ARG REGISTRY=gcr.io/my-gcp-container-registry-project
Step 2/6 : ARG PHP_VERSION=7.1.19-0
Step 3/6 : FROM $REGISTRY/php:$PHP_VERSION-fpm
ERROR: compose.cli.main.main: Service 'drupal' failed to build: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

## Docker compose file<a id="sec-7"></a>

```yaml
version: '3.5'

services:
  ...
  drupal:
    container_name: drupal.${APP_NAME}.local
    build:
      context: ./drupal
    user: "${UID}:0"
```

## Dockerfile<a id="sec-8"></a>

```dockerfile
ARG REGISTRY=gcr.io/my-gcp-container-registry-project/php
ARG PHP_VERSION=7.1.19-0
FROM $REGISTRY/php:$PHP_VERSION-fpm

COPY d8/ /var/www/

ENV PATH $PATH:/var/www/vendor/bin

WORKDIR /var/www
```

**Comment by shin-** [comment] 2018-09-18 23:53
Duplicate of #5950 

It'll be fixed in 1.23.0 ; in the meantime, you should be able to use one of the workarounds mentioned in the other thread, or use a build from the master branch: https://bintray.com/docker-compose/master

**Closed** 2018-09-18 23:54 UTC
Labels: area/build, duplicate
