### ISSUE TITLE
Swarm network can't use in docker-compose.yml

### ISSUE THREAD

**Issue by cjk87927** [docker/compose#4601] opened 2017-03-10 08:28 UTC
I have two machines, In A, I crate the overlay network :
`docker network create --driver overlay --attachable --subnet 172.40.0.0/16 docker3`

In other machine,
I want use it in the docker-compose.yml
```
networks:
  docker3:
    external:
      name: docker3
```
and then I use command 
`docker-compose up -d`
the result is  
`
ERROR: Network docker3 declared as external, but could not be found. Please create the network manually using docker network create docker3 and try again.`

but I can use it in machines A, and use `docker run -d --net=docker3`  in machines B

Docker version 1.13.1
docker-compose version 1.11.2

**Comment by shin-** [comment] 2017-03-10 19:47
What does it say if you run `docker network ls` against machine B?

**Comment by cjk87927** [comment] 2017-03-11 08:09
@shin- 
docker network ls in B
```
NETWORK ID          NAME                DRIVER              SCOPE
e824d6d7560d        bridge              bridge              local
goxe4eon4zou        docker3             overlay             swarm
bb846f654eb2        docker_gwbridge     bridge              local
7c25fff0c286        host                host                local
18upe697ydo4        ingress             overlay             swarm
40aba0d8eb13        none                null                local
```

docker network ls in A
NETWORK ID          NAME                DRIVER              SCOPE
```
3ef0669cd894        bridge              bridge              local
c67505581b2d        docker1             bridge              local
goxe4eon4zou        docker3             overlay             swarm
9cfbc0a520d3        docker_gwbridge     bridge              local
dec64ba0354c        host                host                local
18upe697ydo4        ingress             overlay             swarm
c27e1dae707c        none                null                local
```

**Comment by xdexter** [comment] 2017-04-19 20:46
+1

**Comment by jegade** [comment] 2017-04-19 20:50
Could be related to https://github.com/docker/compose/issues/4399

**Comment by krabradosty** [comment] 2017-10-30 13:32
Still not solved

**Comment by soeren-helbig** [comment] 2017-12-10 00:18
@shin- are there any news on that? if needed, i could provide some more debug-information. or is there any advice on how to debug this problem by my self?

@cjk87927 have you fixed this problem? i ran into the same issue. starting a single container first works fine. if no other container on the worker node uses the overlay network, docker-compose up fails with the same error message as you posted.

would be very thankful for some help on that!

here is my setup...

* both hosts (manager & worker) running debian stretch

* ```docker info``` (manager node)
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* ```docker-compose --version``` (manager node)
```
docker-compose version 1.18.0-rc2, build 189468b
```

* ```docker info``` (worker node)
```
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* ```docker-compose --version``` (worker node)
```
docker-compose version 1.18.0-rc2, build 189468b
```

* created overlay network: 
```
$ docker network create -d overlay --subnet 10.10.10.0/24 --attachable docker_test
```

* ```docker network ls``` (manager node)
```
NETWORK ID          NAME                DRIVER              SCOPE
556dce9ba5fc        bridge              bridge              local
yddwfbe4ohwv        docker_test           overlay             swarm
dd8dfb90eb80        docker_gwbridge     bridge              local
2808636b8a84        host                host                local
vdnu6plp2m1k        ingress             overlay             swarm
7922223a1e5f        none                null                local
```

* ```docker-compose.yml```
```
version: "3"
services:

  mysql_worker:
    image: mysql:5.7
    networks:
       - my_test
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: beer
       MYSQL_USER: beer-master
       MYSQL_PASSWORD: 12345678

networks:
  my_test:
    external:
      name: docker_test
```

**Comment by pshomov** [comment] 2018-06-21 16:29
with 1.21.2 issue still present

**Comment by digger18** [comment] 2018-07-14 07:48
Same problem here with 1.21.2
This fix https://github.com/docker/compose/commit/1e9a66c75b10ca2a873c44f8dc972d4b570d8f91
Involves double check that the network is declared as `external` AND also declared as `overlay` network in the compose, am I correct?

If I declare my network this way:
`networks:
  prod:
    external: true
    driver: overlay`

I am getting:
`ERROR: Network prod declared as external but specifies additional attributes (driver).`

This is the expected behavior since according to: https://docs.docker.com/compose/compose-file/#external

> external cannot be used in conjunction with other network configuration keys (driver, driver_opts, ipam, internal).

So how can we resolve this?

**Comment by shin-** [comment] 2018-08-06 23:14
@digger18 Actually, that restriction is relaxed for versions > 2.0 (in the 2.x series) and > 3.3 (in the 3.x series), so it should work if you use a more recent version of the Compose format. We'll need to update the documentation accordingly.

Let me know if that helps.

**Comment by shin-** [comment] 2018-11-07 00:50
Created https://github.com/docker/docker.github.io/pull/7624 as a follow-up, and closing this as a result.

**Closed by shin-** 2018-11-07 00:50 UTC
Labels: area/networking, swarm

**Comment by enepomnyaschih** [comment] 2021-05-05 13:44
For whoever is wondering, the solution is to define the network in your Docker Compose file with the following properties:

    external: true
    driver: overlay

It works for Docker Compose format 3.4+

It took me half a day to figure it out even with the updated documentation and this thread.

**Comment by rwuthric** [comment] 2023-05-25 00:19
With newest version v2.18.1 of Docker Compose it seems to me that this issue is back. 

Our deployment codes with Docker Swarm and Docker Compose work fine with Docker Compose v2.17.3, but no longer after the update to v2.18.1. The observed issue is exactly the one described by @cjk87927 [here](https://github.com/docker/compose/issues/4601#issuecomment-285851809).

Our overlay network is described in Docker Compose as
```
external: true
driver: overlay
```
as explained by @enepomnyaschih.
