### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by linlinlinlin** [docker/compose#1696] opened 2015-07-15 08:47 UTC
Host docker version:1.6.2
docker-compose version: 1.3.2

I don't know how to reproduce this issue again. But open an new issue by following message.
Hope it can help docker-compose fix minor bugs.

When I am trying to type **docker-compose ps**:

```
    Traceback (most recent call last):
  File "/usr/local/python/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.2', 'console_scripts', 'docker-compose')()
  File "/usr/local/python/lib/python2.7/site-packages/compose/cli/main.py", line 32, in main
    command.sys_dispatch()
  File "/usr/local/python/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/python/lib/python2.7/site-packages/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/local/python/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/python/lib/python2.7/site-packages/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/usr/local/python/lib/python2.7/site-packages/compose/cli/main.py", line 195, in ps
    project.containers(service_names=options['SERVICE'], stopped=True) +
  File "/usr/local/python/lib/python2.7/site-packages/compose/project.py", line 301, in containers
    filters={'label': self.labels(one_off=one_off)})]
  File "/usr/local/python/lib/python2.7/site-packages/compose/container.py", line 28, in from_ps
    'Name': '/' + get_container_name(dictionary),
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by anentropic** [comment] 2015-07-27 08:53
I suddenly started getting this issue this morning

rebooted my laptop over the weekend

as far as I know I haven't changed anything in terms of docker version, boot2docker, docker-compose in the meantime...

**Comment by anentropic** [comment] 2015-07-27 09:16
not all commands affected, `docker-compose build` works fine

`up` and `ps` have problem above

`docker-compose start` seems to do something before failing, maybe informative:

```
docker-compose start
Starting backend_statsd_1...
Starting backend_elasticsearch_1...
Starting backend_postgres_1...
Traceback (most recent call last):
  File "/Users/anentropic/.virtualenvs/myproject/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.3', 'console_scripts', 'docker-compose')()
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/cli/main.py", line 32, in main
    command.sys_dispatch()
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/cli/main.py", line 392, in start
    project.start(service_names=options['SERVICE'])
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/project.py", line 197, in start
    service.start(**options)
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/service.py", line 128, in start
    for c in self.containers(stopped=True):
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/service.py", line 106, in containers
    filters={'label': self.labels(one_off=one_off)})]
  File "/Users/anentropic/.virtualenvs/myproject/lib/python2.7/site-packages/compose/container.py", line 28, in from_ps
    'Name': '/' + get_container_name(dictionary),
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

repeating with `--verbose` mode...

```
...
Starting backend_elasticsearch_1...
docker start <- (u'b357cc6436fcd8da47ff3e5e9640f09db4a81f5c484ed5a243d4ab22637c38ea')
docker start -> None
docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=backend', u'com.docker.compose.service=postgres', u'com.docker.compose.oneoff=False']})
docker containers -> (list with 1 items)
docker inspect_container <- (u'2f8e3fcf2ed2a7baff37d37ea82c90bbdeb3a73f501e9349cfec3d006004b8c8')
docker inspect_container -> {u'AppArmorProfile': u'',
 u'Args': [u'postgres'],
 u'Config': {u'AttachStderr': False,
             u'AttachStdin': False,
             u'AttachStdout': False,
             u'Cmd': [u'postgres'],
             u'CpuShares': 0,
             u'Cpuset': u'',
             u'Domainname': u'',
             u'Entrypoint': [u'/docker-entrypoint.sh'],
...
backend_postgres_1...
docker start <- (u'2f8e3fcf2ed2a7baff37d37ea82c90bbdeb3a73f501e9349cfec3d006004b8c8')
docker start -> None
docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=backend', u'com.docker.compose.service=neo4j', u'com.docker.compose.oneoff=False']})
docker containers -> (list with 1 items)
Traceback (most recent call last):
(...as above)
```

...so it looks like `docker inspect_container` step is failing on my `postgres` container

Thinking back now I had to hard-reboot my laptop on Saturday after it froze up, so I'm guessing something got corrupted in my docker containers then

**Comment by anentropic** [comment] 2015-07-27 12:05
I fixed it eventually by stepping through like:

```
$ docker ps --all | grep postgres
a763941b8b52        backend_postgres        "/docker-entrypoint.   About an hour ago   6 minutes ago
$ docker rm a763941b8b52
```
try again:
```
$ docker-compose up -d
Creating backend_statsd_1...
Creating backend_elasticsearch_1...
Creating backend_postgres_1...
Creating backend_neo4j_1...
Creating backend_mongodb_1...
Cannot start container 27d1f1b77af7c969b9d5b622e82532ddd6cf04f5a3c92f017c34b953ef2c2762: Cannot find child for /backend_mongodb_1
```
ok, next failure... do the same
```
$ docker ps --all | grep mongodb
27d1f1b77af7        backend_mongodb        "/docker-entrypoint.   About an hour ago   6 minutes ago
$ docker rm 27d1f1b77af7
$ docker-compose up -d
...
```
etc...

**Comment by aanand** [comment] 2015-08-10 15:28
Duplicate of #1593

**Closed by aanand** 2015-08-10 15:28 UTC
