### ISSUE TITLE
Pass --detach-keys to docker-compose

### ISSUE THREAD

**Issue by Gijsjan** [docker/compose#3311] opened 2016-04-12 11:36 UTC
`docker run` has the option to pass an alternative sequence to detach. Currently it is mapped to `ctrl-p ctrl-q`, but I heavily use `ctrl-p` in the cli and Vim, so I would like to remap. Is that possible with Compose? If not, this is a feature request. :)

**Comment by crhan** [comment] 2016-06-28 06:13
while docker cli supports detach-keys. I do want the same feature applied in docker-compose too.

**Comment by vladimir-mencl-eresearch** [comment] 2016-06-28 09:51
+1 - this would be a very useful feature

**Comment by qinix** [comment] 2016-07-28 11:24
+1

**Comment by ihucos** [comment] 2016-09-06 16:26
+1

**Comment by 110y** [comment] 2016-10-15 10:18
+1

**Comment by ihucos** [comment] 2016-10-17 09:01
+1

**Comment by schasse** [comment] 2016-11-01 10:17
:+1:

**Comment by jaywhy13** [comment] 2017-01-24 13:18
+1 Question though... it's possible to save detachKeys in ~/.docker/config.json. When Compose runs Docker, why doesn't it use these configs?

**Comment by chhabrakadabra** [comment] 2017-04-01 16:57
+1

**Comment by 110y** [comment] 2017-04-11 06:28
My workaround
```
docker container exec -it $(docker-compose ps -q mycontainer) bash
```

**Comment by scmx** [comment] 2017-04-12 08:40
I'm experiencing the same issue. (using Docker for Mac)

I've remapped my `~/.docker/config.json` like this:
```json
{
  "detachKeys": "ctrl-q,ctrl-q"
}
```
and it's working fine for normal `docker run` but not for `docker-compose`.

Would be awesome if the config file was read when using `docker-compose`. 🎉  Keep up the good work with this tool.

**Comment by kelly-apollo** [comment] 2017-07-04 03:05
+1

**Comment by amosbird** [comment] 2017-08-05 20:08
Hi, is there a pr for this?

**Comment by geezhawk** [comment] 2017-09-08 15:32
+1

**Comment by scrooloose** [comment] 2017-10-10 14:21
+1

**Comment by ihucos** [comment] 2017-10-20 19:12
+1 again

**Comment by 0xBADDCAFE** [comment] 2017-10-28 17:44
+1

**Comment by kdeloach** [comment] 2017-11-21 17:12
+1

**Comment by Nondv** [comment] 2017-11-28 16:39
Is there any movement?

+1

**Comment by summergirl21** [comment] 2017-11-30 18:45
Is this something that would be useful? If so I would be interested in tackling it.

**Comment by jaywhy13** [comment] 2017-11-30 19:10
Yes! Exceptionally so

**Comment by Nondv** [comment] 2017-11-30 19:41
@summergirl21 for example, it's not really comfy to use bash history via `C-p` because docker treats it as  prefix and waits for next key. This is kinda frustrating:)

**Comment by mtsmfm** [comment] 2017-12-01 19:02
I sent a PR to fix this problem.
https://github.com/docker/docker-py/pull/1826

I guess it takes a while to get merged and released so I built patched docker-compose:
https://bintray.com/mtsmfm/docker/compose#files

It respects [our `detachKeys` setting](https://github.com/docker/compose/issues/3311#issuecomment-293512041) as well as docker does.

Please let me know if you find any bugs 🐛

**Comment by hongliang5316** [comment] 2017-12-23 06:57
Nice Job 👍 .

**Comment by jaywhy13** [comment] 2017-12-24 13:24
Awesome

**Comment by lusitania** [comment] 2018-05-04 15:55
AFAICS docker/docker-py#1826 was merged 2018-01-31 for milestone 3.0.0. Can this issue be closed @Gijsjan, @mtsmfm?

**Comment by mtsmfm** [comment] 2018-05-04 16:01
> In which version of docker-compose will this feature become available?

It's available from docker-compose 1.20.0

https://github.com/docker/compose/commit/d8d484e0e19db5326afeb4cdf56864eceb81566c#diff-b4ef698db8ca845e5845c4618278f29a

**Closed** 2019-03-29 16:03 UTC
Labels: kind/feature

**Comment by nroose** [comment] 2021-11-29 23:56
This is again an issue for me. It was fixed for a long time with the .docker/config.json change, but now it's back.

**Comment by Jakob-Koschel** [comment] 2021-12-15 15:06
same issue here

**Comment by balazs14** [comment] 2022-02-27 11:18
I had docker.app running on an M1 mac, the detachKey (Ctrl-P remapped to something else) used to work. Now I am on an intel mac, probably has a later version of docker.app, and indeed it no longer works.

**Comment by georgexsh** [comment] 2026-04-16 03:57
This problem has returned, at least for me.

**Comment by scmx** [comment] 2026-04-16 07:25
> This problem has returned, at least for me.

Did you try https://github.com/docker/compose/issues/3311#issuecomment-293512041 ? It worked for me again just now (with docker compose).

**Comment by georgexsh** [comment] 2026-04-17 06:53
> Did you try [#3311 (comment)](https://github.com/docker/compose/issues/3311#issuecomment-293512041) ? It worked for me again just now (with docker compose).

I didn't notice that configuration, it’s been my machine for a while, and I just confirmed it works on Docker Desktop 4.67.0, thanks for pointing it out.
What I meant was that `docker compose exec --detach-keys 'ctrl-_,d' ...` doesn't work.
