### ISSUE TITLE
regression in 1.5.2 Ctrl+C force stop is not working

### ISSUE THREAD

**Issue by pedro-nonfree** [docker/compose#2543] opened 2015-12-14 03:22 UTC
In previous version 1.5.1 was working. Tested in two computers, in one directly with 1.5.2, in the other was working with 1.5.1 after update to 1.5.2, no.

So it stops because of the timeout

Example output, but here you cannot see nothing strange:
```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping pep-container ... done
Stopping idm ... done
Stopping pdp-container ... done
```

**Comment by aanand** [comment] 2015-12-14 12:56
I can reproduce this. It seems to hang if the second interrupt comes when a request to the API is in progress - if I comment out [the call to project.stop()](https://github.com/docker/compose/blob/a1217dc050144843acb54474ee877ab50fc2eb98/compose/cli/main.py#L663), or just hit Ctrl-C twice in quick succession, then the second Ctrl-C is always picked up.

**Comment by dnephin** [comment] 2015-12-14 21:58
Using a compose file with two services (both just `sleep 50`). I ran:

```
time docker-compose up -t 30
```

If I make this no-op change to print nothing:

```diff
diff --git a/compose/parallel.py b/compose/parallel.py
index 2735a39..1543229 100644
--- a/compose/parallel.py
+++ b/compose/parallel.py
@@ -44,6 +44,7 @@ def parallel_execute(objects, func, index_func, msg):
     errors = {}
 
     while done < len(objects):
+        print("", end='')
         try:
             msg_index, result = q.get(timeout=1)
         except Empty:
```

and run the same command, I see compose exiting within a second of the second ctrl-c.

My best guess right now is that it's an issue with thread scheduling.

Adding a print statement to the `force_shutdown` signal handler shows that without this change it is still firing, it's just taking a really long time for it to happen (which is what makes me think it's an issue with the thread getting scheduled).

**Comment by dbonev** [comment] 2015-12-14 22:27
@dnephin yeah, it seems that the signal handler doesn't get the chance to execute (it must run on the main thread), since q.get() -> except -> continue keeps the loop tight and the main thread busy.

I was doing similar tests and a no-op print in the exception handler seem to make it work too.  

```diff
--- a/compose/parallel.py
+++ b/compose/parallel.py
@@ -47,6 +47,7 @@ def parallel_execute(objects, func, index_func, msg):
         try:
             msg_index, result = q.get(timeout=1)
         except Empty:
+            print(''),
             continue

```

**Comment by cjerdonek** [comment] 2015-12-27 13:16
I provided more information on this in issue #2580.  However, in my case the issue wasn't with being unable to force stop.  It was with _prematurely_ going to force stop (i.e. before hitting Control-C a second time).

I didn't see this issue until after I submitted my own.

**Comment by cjerdonek** [comment] 2015-12-28 20:28
I took a look at the signal handling code and have a few comments that could make addressing this issue easier (as well as cut down on future issues):

First, I noticed that the signal handlers that are being registered seem to "do a lot."  My understanding is that it's best if signal handlers have simple logic and complete quickly.  In particular, they shouldn't have any code that blocks.  For example, rather than actually _doing_ the cleanup, the handler could set one or more application flags or trigger one or more processes to terminate (but not wait for them), and then quickly return or raise an interrupt exception.

Second, rather than setting different signal handlers at different spots in your code, you could set a single signal handler at the very beginning of your main method.  The signal handler can look at application state to know what it needs to do (e.g. which processes to trigger termination of).

Another spot where application cleanup could happen is in the global exception handler of your main method.  If you do that, another option is to raise an interrupt exception in your signal handler, catch it in your global exception handler, and do remaining cleanup that way (and so sharing the same cleanup code path).  This would also let you keep calls to exit() confined to your main method.

I think the above could help with the threading issues and also make the code easier to reason about.

**Comment by dnephin** [comment] 2015-12-28 21:23
> In particular, they shouldn't have any code that blocks. ...rather than actually doing the cleanup, the handler could set one or more application flags

I think this applies more to daemons than interactive clients. With this model how would we support the second shutdown step to KILL the services? I don't think it would be possible once you launch something in the background.  I don't think daemonizing a cleanup process is cleaner than just blocking and waiting for the shutdown. 

> rather than setting different signal handlers at different spots in your code, you could set a single signal handler at the very beginning of your main method. The signal handler can look at application state to know what it needs to do

Application state is bad, and should be avoided at all costs. I don't see any advantage to introducing more state. The signal handlers are already being setup in the main thread before spawning any other threads. What do we gain by having other code paths run through a no-op handler? The signal handlers are set in different spots because they do different cleanup.

> Another spot where application cleanup could happen is in the global exception handler of your main method. If you do that, another option is to raise an interrupt exception in your signal handler

That is similar what we had before 1.5.2. It had it's own set of issues (which were resolved with this change, #1040,  #2456, and many other duplicates). It might be worth trying to have the signal handler only raise an exception, and running the blocking part in a `try/except`, but I suspect we'll go back to having the issues we had before.

I don't like the idea of moving unrelated code to the global exception handler in main. This is not an improvement.

> so sharing the same cleanup code path

There is no code to share here, they do different cleanup.

-----

The feedback is appreciated.  I'm pretty sure the issue has to do with how python handles signals with threads (https://github.com/docker/compose/issues/2543#issuecomment-164572814). It would be really nice if our signal handlers could be really simple and do very little work, but I don't know how that's possible while maintaining feature compatibility.

I personally wouldn't mind dropping the behaviour of `up` that requires us to spin up a bunch of new threads to shutdown all the containers (and instead require a user to issue `docker-compose stop`), but I don't think that's a popular opinion.

**Comment by dnephin** [comment] 2015-12-28 21:36
Moving the shutdown logic to a `try/except` and having the signal handlers just raise the exception seems to fix the issue.  Maybe the problems we had before were because of `finally`.  I'll open a PR with the changes and we'll see if anyone can reproduce the previous issues.

**Comment by dnephin** [comment] 2015-12-28 22:04
Proposed fix in #2585 seems to resolve, let me know if it works for me.

**Comment by cjerdonek** [comment] 2015-12-29 01:19
@dnephin, Thanks for your thoughtful reply.

> With this model how would we support the second shutdown step to KILL the services?

You could for example have the signal handler set a `handler_already_called` flag to true at the beginning.  And then have the handler behave differently if the flag is true.  So you wouldn't really need a second handler.

For example, you could have the handler call a non-blocking "start graceful shutdown" method on each of the running operations if the flag wasn't true.  And if it was true, you could have it call a non-blocking "start kill" instead.  After the handler returns, you could have the main code simply wait for all running operations to complete.  It wouldn't even have to know what the operations are or what state they're in as long as the operation objects themselves share a common interface.

>  I don't see any advantage to introducing more state. ... What do we gain by having other code paths run through a no-op handler?

It's nice because readers of your code wouldn't have to check to see whether your signal handler is registered at a given spot in the code, or which handler is registered.

It's also a more flexible design.  For example, it would let you combine operations with a consistent approach and without any more work.  Say you have two operations A and B that each have their own shutdown cleanup.  If you have to manually register handlers before calling each one, if you wanted to run both A and B together, you would have to manually define and register a third handler, and so on.

One possible approach is to maintain the set of running operations as the only global state you have to keep track of.  Before beginning an operation, you would add that operation to that collection.  This way you avoid race conditions.  These operations could be objects that share an interface with methods like "start graceful shutdown," "start kill," "wait," etc.  With this approach, it would also be easier to reason about concurrency.

> There is no code to share here, they do different cleanup.

An example of the kind of thing you might want to share is reporting on the success or failure of the various operations you ran.  You might want to do this both if a signal is raised or isn't.  Or maybe you have a way of calculating the exit status you want to share in both cases (currently this part isn't DRY), or maybe you want to have a standard something to print to stdout prior to exiting in all scenarios.

**Comment by dnephin** [comment] 2015-12-29 20:57
There are lots of ways to design software, but not every design is applicable for every piece of software. Your suggestions would make sense if we had to register signal handlers at arbitrary times during the execution of a command, or if commands weren't independent from each other.  This is not the case. Each command is a completely independent operation. Signal handlers are only registered as the last step before blocking on a long-running operation, and are different for each operation. Additional global state or centralization does not improve anything in this case, nor does it actually address the problem described in this issue.

**Comment by cjerdonek** [comment] 2015-12-29 23:54
It doesn't seem like you understood my suggestion, or maybe I didn't explain it well. I'm suggesting a DRY way to approach the signal handling that would be easier to reason about and so be easier to be confident that it works. The fact that this issue is a regression and that the patch proposed earlier also had race conditions suggests that there is indeed a problem in this area.

Also, while this isn't central to my suggestion, there's nothing that says a signal handler must be "registered as the last step before blocking on a long-running operation."  Nor is my suggestion related to "registering signal handlers at arbitrary times."

I was suggesting that there be one signal handler something like this (this is only meant to be a sketch):

    def handle_signal(signalnum, frame):
        log("Handling signal: {0}".format(signalnum))
        already_called = State.handler_already_called
        State.handler_already_called = True
        operation = State.operation
        if operation is None:
            return
        if already_called:
            operation.start_kill()  # should return immediately
        else:
            operation.start_shutdown()  # should return immediately
    
        raise InterruptException()

The signal handler can be registered at the beginning of your main function (though this isn't central to my suggestion).  And you set `State.operation` prior to commencing the run or up operation.

With this approach, you can focus on the smaller problems of ensuring that `operation.start_kill()` and `operation.start_shutdown()` are non-blocking and do what you want for the operations you have (run and up).

**Comment by dnephin** [comment] 2015-12-30 17:15
I understood your suggestion. I disagree that it's a good way to solve this problem. You are free to submit a PR if you're interested, but any PR which adds global state, or requires us to replicate the default signal handler for other commands, is unlikely to be accepted.

**Closed** 2016-01-12 17:55 UTC
Labels: area/cli, kind/bug
