### ISSUE TITLE
.env file is not read

### ISSUE THREAD

**Issue by creynders** [docker/compose#4223] opened 2016-12-06 13:49 UTC
I'm trying to use ENV variables declared in a `.env` file in my docker-compose file (I.e. I don't want to use the `.env` file in a container, just in the build process).

I have the following:

```
# file: build/docker-compose.development.yml

...
foo:
    volumes:
        - "${PROJECT_SRC}/foo.txt:/app/foo.txt"
```
```
# file: .env
PROJECT_SRC=../src
```

Then I run docker-compose:

```
$ docker-compose -f build/docker-compose.development.yml build
```

But no matter where I put the `.env` file (i.e. next to or inside the `build` directory) docker always throws:
```
WARNING: The PROJECT_SRC variable is not set. Defaulting to a blank string.
```

Am I doing something wrong? Or doesn't it work with the `-f` flag? Or?

**Comment by dalejung** [comment] 2017-01-03 15:52
I ran into the same issue. The environment variables are set within the container itself and is accessible via the `environment` block. Maybe `volumes` are executed before `env_file` is run.

**Comment by dalejung** [comment] 2017-01-03 16:16
Taking a look, it looks like the `env_file` is processed in a finalization step. The `volumes` has already been interpolated with the incomplete environment dict by this point.

**Comment by rsynnest** [comment] 2017-02-15 17:23
@creynders The `.env` file must be placed in the directory where `docker-compose` is run from ([here's the documentation](https://docs.docker.com/compose/env-file/)). I've tested this with latest build, it still works. Your post is a bit confusing though because it looks like you are running a `build` command, which doesn't actually run the container, and hence doesn't use runtime variables like the one defined in your `volume` block. If you are trying to pass arguments to your `docker build` process to build an image, you should instead be using the [`args:`](https://docs.docker.com/compose/compose-file/#/args) key within the `build:` block in docker-compose.yml, and then you can work with those ARGs in your Dockerfile.

@dalejung I've noticed there is a bit of confusion surrounding environment variables (I was confused myself for a while). The documentation can be a bit unclear with its language on these terms, especially the [official example](https://docs.docker.com/compose/compose-file/#/envfile) which confusingly loads the `.env` file in the the `env_file:` block. To clear things up:

**`env_file`**
This file (or files) contains a list of docker environment variables which will be passed to the container as if they were in the `environment:` block. The files are explicitly defined in the `env_file:` config block. Anything in these files is passed as if it were via `docker run -e <env_file vars>`.

[**`.env`**](https://docs.docker.com/compose/env-file/)
This file must be placed in the same directory where docker-compose is run from, and is automatically loaded by docker-compose. It contains a list of environment variables on the host which you would like to use as [variable substitutions](https://docs.docker.com/compose/compose-file/#variable-substitution) (aka string replacement) within your docker-compose.yml. These vars are not passed to the docker container. The use case for this would be something like:
```
volumes:
    - "${PROJECT_SRC}/foo.txt:/app/foo.txt"
```
where `.env` contains `PROJECT_SRC=my/source/directory`.

**Comment by creynders** [comment] 2017-02-16 07:29
@rsynnest thank you very much for this explanation! So when I run `docker-compose build` the `.env` file is NOT automatically loaded? But when I run `docker-compose up` it is?
I only need the variable values inside my docker-compose file, both during building and upping, which, if I understand correctly, isn't possible using `.env`, right?

**Comment by rsynnest** [comment] 2017-02-16 17:28
@creynders When you run a `docker-compose build`, compose only uses 3 values from the docker-compose.yml file: `context`, `dockerfile`, and `args`. These are defined in the [**build**](https://docs.docker.com/compose/compose-file/#/build) config block. The `.env` is still loaded, it is always automatically loaded, even when you run `docker-compose build`. 

So, when you define your volume in your docker-compose.yml file, that volume is only created and mounted at runtime, not at build time. If you wish to create a volume at build time, you need to define a volume in your Dockerfile, with the one restriction being that you can't mount a host directory, you can only define a volume for the container (for example, Dockerfile: `VOLUME /foo/bar` is identical to the following runtime command: `docker run -v /foo/bar`).

Docker-compose is mainly a runtime tool. Image building is still almost entirely handled in the Dockerfile.

**Comment by creynders** [comment] 2017-02-18 16:08
Then why does it throw the warning? I have an `.env` file with `PROJECT_SRC=foo` and whether I run `docker-compose build` or `docker-compose up` it will always warn me that PROJECT_SRC isn't set, even though it is set in the `.env` file. However if I run `PROJECT_SRC=foo docker-compose up` the warning isn't thrown. I don't know, probably I'm missing something here, but it doesn't seem to make sense to me. Or it's broken.

**Comment by rsynnest** [comment] 2017-02-18 17:04
Hmmm strange. What version of compose are you running? The `.env` file was introduced in 1.7.0

**Comment by ulugbekov** [comment] 2017-03-10 05:21
I have the latest build docker-compose version 1.11.2, build dfed245
It is not reading .env variables.

**Comment by rsynnest** [comment] 2017-03-16 17:46
Ok, I just helped a friend with this same scenario. The issue is most likely syntax in your `.env` file.
Make sure the `.env` file has readable permissions, then check that syntax matches `KEYNAME=value`.
No Spaces Allowed! `KEYNAME = value` will not work.

**Comment by florianm** [comment] 2017-07-07 06:17
@rsynnest thanks for your explanation, helped me to understand. My confusion was that I factored out variables **after** building the images, and docker silently re-used cached images **without** my new variables. I had to delete images and volumes before the re-build finally recognised my variables.

**Comment by giovanniKleinCampigoto** [comment] 2017-07-14 22:55
make sure you didn't insert export before the env variables...

**Comment by ababushkin** [comment] 2017-08-10 01:11
I'm having the same issue on my end.

Here's my structure:

.
├── docker
│   ├── .env
│   └── docker-compose.yml

When I run docker-compose up -d from the docker folder, none of the contents of my .env file are being registered.

My .env file is written in the following format:

AWS_ACCESS_KEY_ID=<secret value>
AWS_SECRET_ACCESS_KEY=<secret value>

However, when I change my docker-compose to contain:

services:
  my_special_service:
    image: something
    env_file:
      - .env

Then everything works as expected.

Looks like a genuine bug?

Running MacOS.

docker-compose version 1.14.0, build c7bdf9e

**Comment by rsynnest** [comment] 2017-08-10 18:10
@ababushkin please read my [comment above](https://github.com/docker/compose/issues/4223#issuecomment-280077263)

To summarize, `.env` file variables are not passed to the docker container at runtime. The `.env` file is used for [variable substitutions](https://docs.docker.com/compose/compose-file/#variable-substitution) in config files only
The `env_file` block on the other hand passes env vars from a file to the container at runtime, serving the same purpose as the `environment` block or `docker run -e`. 

This bug is still not reproducible, @creynders are you willing to close this issue or are you still experiencing the problem?

**Comment by shin-** [comment] 2017-08-10 21:51
@rsynnest Thank you for taking the time to help people here.

I'm going to close this issue now as it is 1. not a bug and 2. a duplicate of #4189 (and several others)

**Closed by shin-** 2017-08-10 21:51 UTC

**Comment by ababushkin** [comment] 2017-08-11 00:10
@rsynnest thanks for the clarification - I must've skimmed over your previous comment but can see it now :)

**Comment by thebetterjort** [comment] 2017-08-29 18:16
Can the .env file be named variables.env in the env_file block. I'm only able to build using .env filename.

**Comment by jibusayone** [comment] 2017-10-20 16:20
@thebetterjort I managed to find a solution! I used the `env_file` setting itself, and defined the `variables.env` within the same line. And it worked like a charm!

Here is how my docker-compose.yml looks like:
```
services:
  web:
    env_file: variables.env
```

**Comment by KirillAmurskiy** [comment] 2017-11-08 06:15
@creynders I had the same problem. The variable is in .env file, but on `docker-compose run`  I had warning "Bla_bla_variable not found".
In my case problem was with...
**FILE ENCODING**
If .env file is in **Unicode** -> will be **warning**.
If .env file is in **ANSI** -> will be **OK**.

**Comment by realpablodias** [comment] 2017-11-12 23:35
@KirillAmurskiy Great! I changed from UTF-8 to ISO8859-1 and worked. But you know what? I just changed back to UTF-8 and it is still working (is this real life?)

**Comment by hynese** [comment] 2018-01-04 23:11
I'm also experiencing this problem on OSX.

```
docker version

Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:25 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:28:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mxr576** [comment] 2018-01-14 18:02
Same here.

**Comment by radovanobal** [comment] 2020-02-22 08:36
I get the warnings that the variables from the .env file are not loaded when I run docker-compose in CMD on windows but I do not get them if I run the same command from powershell.

**Comment by floatingpurr** [comment] 2020-04-09 10:16
> files is passed as if

@rsynnest, just a side question. Vars in `env_file:` are passed to containers. Are those vars used also for variable substitutions in the Compose?

**Comment by floatingpurr** [comment] 2020-04-09 10:17
> @ababushkin please read my [comment above](https://github.com/docker/compose/issues/4223#issuecomment-280077263)
> 
> To summarize, `.env` file variables are not passed to the docker container at runtime. The `.env` file is used for [variable substitutions](https://docs.docker.com/compose/compose-file/#variable-substitution) in config files only
> The `env_file` block on the other hand passes env vars from a file to the container at runtime, serving the same purpose as the `environment` block or `docker run -e`.
> 
> This bug is still not reproducible and I think is being caused by confusion around the term "environment variables".
> @creynders are you willing to close this issue or are you still experiencing the problem?

@rsynnest, just a side question. Vars in env_file: are passed to containers. Are those vars used also for variable substitutions in the Compose?

**Comment by rsynnest** [comment] 2020-04-09 16:57
> @rsynnest, just a side question. Vars in env_file: are passed to containers. Are those vars used also for variable substitutions in the Compose?

No

**Comment by filipbekic01** [comment] 2020-05-27 15:03
If you guys have trouble loading different `.env` than one in root docker composer directory, consuding using system link. For example `sudo ln -s /path/to/env .`. This might solve confusion.

**Comment by iquito** [comment] 2020-06-16 13:45
For me the `.env` file was not loaded because I was using the `--project-directory` option: in that case docker-compose reads the .env file from the `--project-directory` directory, not from the directory the compose file is in, which was not obvious to me at first. I wanted to add this in case someone else had the same problem and stumbled across this issue.

**Comment by jeterpan** [comment] 2020-09-21 17:20
I was wrong using require('dotenv'),config() in my main project .js file. The solution was using it in the begning of the config.js (a module where I load all the environment)

**Comment by ereztaiar** [comment] 2020-10-07 13:27
I am using mac and phpstorm,
Using the terminal in phpstorm the .env file is not working with docker-compose command and not setting the variables on the docker-compose.yml
Using the iterm there is no problem and docker-compose runs fine with no errors

**Comment by thaJeztah** [comment] 2020-10-07 13:30
@ereztaiar I would recommend opening a ticket in the JetBrains issue tracker; https://youtrack.jetbrains.com/issues/WI

**Comment by Vespira** [comment] 2021-04-09 13:16
> 
> 
> I am using mac and phpstorm,
> Using the terminal in phpstorm the .env file is not working with docker-compose command and not setting the variables on the docker-compose.yml
> Using the iterm there is no problem and docker-compose runs fine with no errors

I don't know about MacOS, but on Windows, with Docker over WSL2, the docker-compose impl. look for the specified .env file into the same directory as the provided .yml file.

Ex: if I'm at the root of my project, I type:
`docker-compose --env-file .docker.env -f ./docker/my-docker-compose.yml up -d`

note that `.docker.env` have to be in the `./docker` directory.

It's not the same behavior as with the Linux impl. we tested it out with a fellow developper using Linux (both using one of the latest docker-compose version).

**Comment by purefun** [comment] 2021-04-11 11:44
> note that .docker.env have to be in the ./docker directory.

@Vespira Thx. It also fixes on  macOS .

**Comment by WisaamFarhat** [comment] 2021-06-13 11:07
Hello,

I'm running docker-compose version 1.29.2, and docker version 20.10.7 running on Ubuntu 18.04.

I followed al the steps to try and resolve the same issue above, but haven't been successful. 

My .env file has correct syntax, as below:
==============
TEST_NETWORK=172.22.0.0/24
DOCKER_HOST_IP=192.168.1.223

MONGO_IP=172.22.0.2
....
===============

In my docker-compose.yaml I've defined the following at the top:
===============
networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
 services:
  mongo:
    build: ./mongo
    image: docker_open5gs_mongo
    container_name: mongo
    env_file:
      - .env
   ...
    networks:
      default:
        ipv4_address: ${MONGO_IP}
===============
However, upon running docker-compose up, i get this!!!..
===============
ERROR: for mongo  Cannot start service mongo: Invalid address 172.22.0.2: It does not belong to any of this network's subnets
===============

What could be the problem?

**Comment by mcfriend99** [comment] 2021-10-07 10:16
> @creynders The `.env` file must be placed in the directory where `docker-compose` is run from ([here's the documentation](https://docs.docker.com/compose/env-file/)). I've tested this with latest build, it still works. Your post is a bit confusing though because it looks like you are running a `build` command, which doesn't actually run the container, and hence doesn't use runtime variables like the one defined in your `volume` block. If you are trying to pass arguments to your `docker build` process to build an image, you should instead be using the [`args:`](https://docs.docker.com/compose/compose-file/#/args) key within the `build:` block in docker-compose.yml, and then you can work with those ARGs in your Dockerfile.
> 
> I've noticed there is a bit of confusion surrounding environment variables (I was confused myself for a while). The documentation can be a bit unclear with its language on these terms, especially on of the official examples which confusingly loads the `.env` file in the the `env_file` block. This is the best documentation page I've found on various environment variables: https://docs.docker.com/compose/environment-variables/.
> 
> Some blurbs to try to clear up any confusion:
> 
> **`env_file`** This file (or files) contains a list of docker environment variables which will be passed to the container as if they were in the `environment:` block. These files are explicitly defined in the `env_file:` config block. Anything in these files is passed as if it were via `docker run --env-file=FILE`.
> 
> **`.env`** file (https://docs.docker.com/compose/env-file/) This file must be placed in the same directory where docker-compose is run from, and is automatically loaded by docker-compose. It contains a list of environment variables which you would like to use as [variable substitutions](https://docs.docker.com/compose/compose-file/#variable-substitution) (aka string replacement) within your docker-compose.yml. These vars are not passed to the docker container. For example:
> 
> ```
> volumes:
>     - "${PROJECT_SRC}/foo.txt:/app/foo.txt"
> ```
> 
> where your `.env` file contains `PROJECT_SRC=my/source/directory`.

I ran `docker-compose up --build` from the same directory that contains the `.env` file and it still didn't pick up any of the environment variable. Any help here is appreciated.

**Comment by huangxin19990101** [comment] 2022-01-20 07:09
docker-compose --env-file .env.oat build 
it's working for me.

**Comment by emerson-pereira** [comment] 2022-02-27 18:42
> @ababushkin please read my [comment above](https://github.com/docker/compose/issues/4223#issuecomment-280077263)
> 
> To summarize, `.env` file variables are not passed to the docker container at runtime. The `.env` file is used for [variable substitutions](https://docs.docker.com/compose/compose-file/#variable-substitution) in config files only The `env_file` block on the other hand passes env vars from a file to the container at runtime, serving the same purpose as the `environment` block or `docker run -e`.
> 
> This bug is still not reproducible and I think is being caused by confusion around the term "environment variables". @creynders are you willing to close this issue or are you still experiencing the problem?

Thank you so much for the clarification. And is there no way to configure var sub in file?

**Comment by rezam7596** [comment] 2022-11-27 08:11
like @rsynnest said, my issue was syntax in my .env file. In my case I used a double-quote in double-quoted variable!
`PASSWORD="kg#"B4f2@K"`
Unfortunately, in this case, docker-compose is behaving like there is **no** .env file at all. there is no proper error or warning. I suggest that a proper warning be shown in case of .env file error.

**Comment by ayesparshh** [comment] 2024-06-27 09:23
@rsynnest hey can you please help me here 
![Screenshot 2024-06-27 144403](https://github.com/docker/compose/assets/96340685/23e8e29f-e1e0-4d93-9f9b-1a27d331b823)
im encountering this error please if you can refer my Github repo it will be helpful thanks
https://github.com/ayesparshh/url-shortner-go
