### ISSUE TITLE
Publishing the same port for two different protocols fails silently

### ISSUE THREAD

**Issue by Rme2001** [docker/compose#8557] opened 2021-08-06 14:06 UTC
**Description**

Publishing the same port twice, with different protocols (TCP/UDP) results in the only the UDP protocol being published for a specific configuration with Docker-Compose v2.0.0-beta.6. Docker-Compose v1.29.2 publishes both. 

**Steps to reproduce the issue:**
1. Checkout version 2.6.5 from https://github.com/api-platform/api-platform
2. `docker-compose build --pull --no-cache`
3. `docker-compose up -d`

**Describe the results you received:**
Output of `docker ps` wuth Compose v2.0.0-beta.6
![image](https://user-images.githubusercontent.com/2506544/128522044-de010da8-b3ad-4394-9db9-c77a2437fc03.png)

**Describe the results you expected:**
Ouput of `docker ps` with Compose v1.29.2
![image](https://user-images.githubusercontent.com/2506544/128516907-bb986309-e263-4aaa-b055-989ee3fd5bee.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

Tried to reproduce this with a minimal docker-compose, with just the Caddy service, however, that does not seem to create the problem, since both UDP and TCP ports are published there. So unfortunately, the best way to reproduce is to take the docker-compose.yml from the linked repo.

**Output of `docker-compose --version`:**

```
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)
WARNING: Plugin "/usr/libexec/docker/cli-plugins/docker-app" is not valid: failed to fetch metadata: fork/exec /usr/libexec/docker/cli-plugins/docker-app: no such file or directory

Server:
 Containers: 36
  Running: 4
  Paused: 0
  Stopped: 32
 Images: 72
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 24.84GiB
 Name: docker-desktop
 ID: BBG4:BUHA:GXOI:JG6K:3FBI:Z5H5:ZTPF:ZXND:757B:PPG2:5DQC:XKAI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

- Windows 10 (20H2 build: 19042.1110)
- Docker Desktop 3.5.2 (66501) WSL 2 Enabled (Ubuntu 20.04)

**Comment by dunglas** [comment] 2021-09-08 20:13
I can reproduce the issue with the RC 2 and `api-platform/api-platform`.

**Comment by ndeloof** [comment] 2021-09-09 07:58
ok, I eventually understood the root cause is `cady` service being declared in override file, ans as such this is a duplicate for into https://github.com/docker/compose/issues/8557

**Comment by ndeloof** [comment] 2021-09-09 07:59
Closing in favor of #8557 which offers a simpler reproduction scenario

**Closed by ndeloof** 2021-09-09 07:59 UTC
Labels: duplicate, Docker Compose V2

**Comment by piotr-cz** [comment] 2021-09-09 08:06
@ndeloof
For which issue is it a duplicate?
In Your previous comment you added link to this issue.

**Comment by ndeloof** [comment] 2021-09-09 08:13
updated, sorry bad copy/paste

**Comment by piotr-cz** [comment] 2021-09-09 08:22
Thanks!

**Comment by dunglas** [comment] 2021-09-09 09:22
Thank you!
