### ISSUE TITLE
[BUG] `include` cache contains stale objects

### ISSUE THREAD

**Issue by thespad** [docker/compose#11518] opened 2024-02-17 16:49 UTC
### Description

I'm not sure if this is a bug or working as intended or if I'm just missing something, because there's no real documentation around it.

I'm using `COMPOSE_EXPERIMENTAL_GIT_REMOTE` to include compose config from a git repo. I have two hosts that I'm using it to keep identical config across using:

```yaml
include:
  - git@github.com:thespad/somerepo.git#master:infra/compose.yml
```

This *mostly* works, however, I discovered that if you use a relative volume path in the compose file, e.g.:

```yaml
    volumes:
      - ./config:/config:rw
```

Then `include` will use the version of the folder from the git repo and not the local filesystem relative to the compose.yml, and this means it really sits in somewhere like `/home/user/.cache/docker-compose/7e6045c855a5bb0666286dc1574eded04235cd1e/infra/config`

However, if I update a file in that directory in the git repo and then recreate the container, it doesn't update the cached copy of the file and continues to use the existing one.

There don't seem to be any cache-busting args for compose `up` and deleting part of the cache just means the files go missing and compose does not attempt to replace them, you have to delete the entire `7e6045c855a5bb0666286dc1574eded04235cd1e` directory and potentially recreate all containers that are part of the project.

What criteria does compose use to decide whether or not to update the cache? Does it need to be a change to the specific compose.yml being included rather than just new commits to any files or folders in scope? Does it only refresh the cache as a whole and not individual files or folders within it? Is there a way to force a cache invalidation without deleting the folder from the local machine?

### Steps To Reproduce

1. Set COMPOSE_EXPERIMENTAL_GIT_REMOTE=true
2. `include` a remote git repo in your compose project that contains a relative volume path
3. Modify the remote path in the git repo
4. Recreate the container
5. Observe that it is still using the local cached copy of the files

### Compose Version

```Text
Docker Compose version v2.23.3
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    25.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3
    Path:     /home/user/.docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 25.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-1045-raspi
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.7GiB
 Name: pi1
 ID: 9739e21c-dc5f-4ca5-9136-f94b401a5977
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true
 Default Address Pools:
   Base: 172.20.0.0/16, Size: 24
```

**Comment by ndeloof** [comment] 2024-02-18 13:27
This is the intended behavior: included model is considered a standalone compose definition, just like you ran `docker compose up` in another folder just before you started your application. 

To support your use case you should rely on a variable set in the included compose project to define the `config` path to be bind mounted.

**Comment by thespad** [comment] 2024-02-18 13:43
Thanks for clarifying.

So in which scenarios will compose update its local cache of the compose project? Is it purely when there is a change to the referenced compose.yml? And if so does it refresh the whole cache at that point or is it selective?

**Comment by ndeloof** [comment] 2024-02-18 13:49
In this scenario, the local cache would actually just reflect the exact same if you had manually cloned the other git repository and ran the application by yourself.
This is obviously not a pattern we expect to be used as "reusable components". I wonder we should make the file in local cache read-only to help detect such misuse, but the reported error would probably make it had for users to understand the root cause.

**Comment by thespad** [comment] 2024-02-18 13:55
Yeah I'm not particularly advocating for any specific use case (although being able to use a config file from the remote repo - read-only or not - on multiple devices, has its advantages), but for that to work the cache would need to refresh whenever the remote repo changes, not just the file(s) being directly included - or at least have an arg you can pass to `up` to force a refresh.

The behaviour of the relative paths makes perfect sense *once you understand what include is doing under the hood*, it just wasn't what I expected it to do initially.

**Comment by ndeloof** [comment] 2024-02-18 14:24
if you use a git tag (or just implicit HEAD) in your git URL, compose will detect latest commit on remote branch is not the one in the cache and will then get a fresh new local copy.

**Comment by luciangabor** [comment] 2024-02-18 18:41
If I correctly read the intent, here's an example of how volumes can be used to share predefined data between containers.

With a `compose.yaml` like this:

```yaml

include:
  - path: payload.yaml

services:
  service:
    pull_policy: build
    build:
      pull: true
      dockerfile_inline: |
        FROM busybox
        CMD cat /payload/file
    volumes_from:
      - payload:ro

```

and an `payload.yaml`

```yaml

services:
  payload:
    pull_policy: build
    build:
      dockerfile_inline: |
        FROM scratch
        VOLUME /payload
        COPY <<EOF /payload/file
        content
        EOF
    init: true
    entrypoint: docker-init --version

```

using `docker compose up --renew-anon-volumes` achieves that ... at the expense of a lot of anon volumes:

```console

$ docker compose --progress none up --renew-anon-volumes service
Attaching to service-1
service-1  | content
service-1 exited with code 0

$ sed -e 's/content/updated \0/g' -i payload.yaml

$ docker compose --progress none up --renew-anon-volumes service
Attaching to service-1
service-1  | updated content
service-1 exited with code 0

```

This implies that the files to share are inside an image, and it works because the content of the volume is initialized with them at volume creation time (unless explicitly disabled).

This example should work, regardless where the included yaml resides, but, I'd prefer to use named volumes (ditch the `VOLUME` directive too) and renew their data using a `docker compose down -v && docker compose up` cycle ... and, if the data is always remote, I'd rather use additional contexts and copy the data where needed.

Hope this helps.

**Comment by ndeloof** [comment] 2024-02-21 13:34
closing this issue as "answered"

**Closed by ndeloof** 2024-02-21 13:34 UTC
Labels: kind/question
