### ISSUE TITLE
config filters out new 'deploy' key

### ISSUE THREAD

**Issue by rapha-opensource** [docker/compose#4732] opened 2017-04-13 02:52 UTC
I'm using 1.11.2 (as listed in the online docs).

I'm using 'docker-compose config' to generate a stack file from a list of 'version 3' compose files,
now that 'extends' is gone.
I added a 'deploy' key to some services in their individual compose file.

When generating the final stack file using 'docker-compose -f ... -f ... -f ... config > stack.yml', I noticed my deploy keys were gone.

Is this the expected behavior?

Also looked in the code (compose/compose/config/config.py) and saw this warning string:
'Compose does not support deploy configuration...', yet the documentation for compose lists 'deploy' as a valid key.

I'm deeply confused as to how we are supposed to use compose in combination with stack.
The only conclusion I can come to is we must maintain a duplicated single file for use with stack.

**Comment by shin-** [comment] 2017-04-13 21:00
Duplicate of #4517 
Please upgrade to `1.12.0`!

**Closed by shin-** 2017-04-13 21:00 UTC
