### ISSUE TITLE
Hostnames with underscore

### ISSUE THREAD

**Issue by bibendi** [docker/compose#472] opened 2014-09-05 08:32 UTC
Hostnames with underscore fails in ruby URI validation

redis://redis_1:6379/4

```
 /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/uri/generic.rb:213:in `initialize': the scheme redis does not accept registry part: redis_1:6379 (or bad hostname?) (URI::InvalidURIError)
    /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/uri/common.rb:218:in `new'
    /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/uri/common.rb:218:in `parse'
    /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
    /usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/uri/common.rb:994:in `URI'
    /usr/local/gems/gems/redis-3.0.7/lib/redis/client.rb:345:in `_parse_options'
    /usr/local/gems/gems/redis-3.0.7/lib/redis/client.rb:67:in `initialize'
    /usr/local/gems/gems/redis-3.0.7/lib/redis.rb:31:in `new'
    /usr/local/gems/gems/redis-3.0.7/lib/redis.rb:31:in `initialize'
```

http://stackoverflow.com/questions/2180465/can-someone-have-a-subdomain-hostname-with-an-underscore-in-it

**Comment by vandekeiser** [comment] 2015-04-09 14:23
Does this mean that containers created with compose are unusable for web services? How am i supposed to configure the application that uses the web service (it validates the uri and fails)?

**Comment by dnephin** [comment] 2015-04-09 14:45
You can use the name of the service in the `docker-compose.yml` as the hostname. It doesn't contain any underscores. You can also add an alias to your link to the container, which should allow you to access it as just the alias.

In the 1.3 release of compose there should be support for naming your container as anything you want, which will make this more obvious.

**Comment by JeanMertz** [comment] 2015-07-18 14:48
I am not sure what the status of this issue is, but we're having problems with this as well.

Using the experimental build 1.8 (to use the new networking features), this is our current situation:

**docker-compose.yml**:

```yaml
api:
  build: .
  ports:
    - 80
```

**/etc/hosts**:

```
cat /etc/hosts
172.17.42.23	dev_api_1
```

**error**:

```
Bad url URL: "http://dev_api_1/api.json"
```

@dnephin mentions the possibility of using simply `api`, but it is not listed in the `/etc/hosts` file (and subsequently does not work).

@thaJeztah mentions that `_` characters are allowed in domains, which is *true*, but they are *not* allowed in hostnames, (valid: `_static.my-app.com`, invalid: `_static.my_app.com`).

@vandekeiser mentions using `domainname`, which I was not aware existed, so I'm going to try that now, but the default underscore hostname situation is still a pitty.

**Comment by dnephin** [comment] 2015-09-01 15:09
There's a lot going on in this issue. 

Part of this is a duplicate of #229

@JeanMertz all linked containers should have a name without an underscore, and you can also alias the links (http://docs.docker.com/compose/yml/#links) if you need to. If this isn't working for you for some reason, please open a new issue.

**Closed by dnephin** 2015-09-01 15:09 UTC

**Comment by donoghuc** [comment] 2020-04-02 15:11
I hope this simple examples saves someone some googling.
Use case: I want a resolvable hostname (in my case _without_ underscores) discoverable on a docker-compose network.
Here is the directory structure:
```
cas@cas-ThinkPad-T460p:~/why$ tree
.
├── docker-compose.yml
└── parent
    └── docker-compose.yml

1 directory, 2 files
```
In the `parent` directory I have the docker-compose network where I want the resolvable hostname without underscores:
```yaml
version: '3'
services:
  bad_hostname:
    image: rastasheep/ubuntu-sshd:16.04
    hostname: goodhostname
    networks:
      default:
        aliases:
          - goodhostname
    ports:
      - "20024:22"
networks:
  default:
```
Note how I set the `aliases` under the network key. This will end up being the discoverable hostname!
Now I can attach to that network in a separate docker-compose file like:
```yaml
version: '3'
services:
  outter:
    image: rastasheep/ubuntu-sshd:16.04
    ports:
      - "20023:22"
networks:
  default:
    external:
      name: parent_default
```
Finally if you attach to the `outter` container you can see that the hostname is resolvable by the alias you set.
```
cas@cas-ThinkPad-T460p:~/why$ docker exec -it why_outter_1 /bin/bash
root@d7dafbc45737:/# ssh root@goodhostname
The authenticity of host 'goodhostname (172.19.0.2)' can't be established.
ECDSA key fingerprint is SHA256:4utoWe5uVp79ImYqkPPukjmrGIfvDC5demc1sx8sY9c.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'goodhostname,172.19.0.2' (ECDSA) to the list of known hosts.
root@goodhostname's password: 
root@goodhostname:~# logout
```

**Comment by taseenb** [comment] 2024-12-28 19:00
Hostnames with underscores may fail in many circumstances. They also fail with MongoDB/Mongoose.

Re https://github.com/docker/compose/issues/9618#issuecomment-2564404024
