### ISSUE TITLE
[BUG] logs --follow gets stuck forever

### ISSUE THREAD

**Issue by nicks** [docker/compose#10351] opened 2023-03-06 19:30 UTC
### Description

I'm having an issue where `docker compose logs --follow` get jammed. It stops streaming new logs and also stays attached.

This is a distillation of a larger repro case: https://github.com/tilt-dev/tilt/issues/6053

### Steps To Reproduce

1. Use this compose file:

```
services:
  agent:
    image: python:3.7
    command: echo "BES"
```

2. In one terminal, run:

```
docker compose up -d
docker compose logs agent --follow
```

3. In a second terminal, run:

```
docker compose rm --stop --force agent
docker compose up agent
```

Expected behavior:
I'm not sure! I'd expect one of two things to happen:
- The 'logs --follow' terminal to print BES twice (once for each container)
OR
- The 'logs --follow' terminal to detach when the first container exits (this is what docker compose v1 does)

Actual behavior:
The logs --follow terminal stays attached but doesn't stream the new logs.

### Compose Version

```Text
Docker Compose version v2.15.1
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.3
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.18
    Path:     /usr/lib/docker/cli-plugins/docker-extension
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.25.0
    Path:     /usr/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.6.0
    Path:     /usr/lib/docker/cli-plugins/docker-scout
WARNING: Plugin "/usr/lib/docker/cli-plugins/docker-compose.14.backup" is not valid: plugin candidate "compose.14.backup" did not match "^[a-z][a-z0-9]*$"

Server:
 Containers: 34
  Running: 2
  Paused: 0
  Stopped: 32
 Images: 230
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-67-generic
 Operating System: Linux Mint 21
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.26GiB
 Name: grumpy
 ID: 9cba2c25-6ba4-4f6c-995c-53aacc5cc77e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by milas** [comment] 2023-03-24 20:57
> **Expected Behavior** I'm not sure! I'd expect one of two things to happen:

The expected behavior is that `--follow` will continue to watch logs for a service across updates...but also exit if everything is stopped [and not imminently coming back].

So in your example, it _should_ have stopped in the first terminal, since the service was removed entirely [and nothing else was being watched]. That's a bug 🙃  

This behavior is pretty recent fwiw - when Compose replaces a container on `up`, it does a create -> destroy -> start, and it now stores the ID of the container being destroyed in a label on the new container. Compose will not remove a service from the active set when it sees a destroy event for a container that it knows is being replaced.

[It's also not perfect, e.g. currently `docker compose restart <svc>` will cause a `logs --follow` session to immediately exit instead of waiting for the restart.]

---

[Debugged this but didn't have time to fix today, noting findings here]

When setting up logs / handling container events, need to refactor to ensure event handling is idempotent. We also need to FIRST establish `/events` channel THEN list containers to avoid a race.

If you change the repro to be `docker compose up -d; sleep 1; docker compose logs agent --follow`, it's unlikely to happen.

I can see different cases in here where it gets into inconsistent states based on what events (and potentially in which order) it sees, and that can result in it getting stuck indefinitely.

**Comment by ndeloof** [comment] 2024-10-11 12:12
Closing as obsolete

**Closed by ndeloof** 2024-10-11 12:12 UTC
Labels: kind/bug, status/0-triage
