### ISSUE TITLE
Compose 'up' command fails after second call

### ISSUE THREAD

**Issue by jlesquembre** [docker/compose#1176] opened 2015-03-25 17:02 UTC
With this simple .yml file:

```yaml
web:
  image: alpine:3.1
  command: echo "Hello World"
```

First time you run `docker-compose up`, everything works as expected:

```
Creating test_web_1...
Attaching to test_web_1
web_1 | Hello World
test_web_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```

But second time, compose doesn't display any output and never exits:

```
Recreating test_web_1...
Attaching to
```

Probably related to #753

**Comment by dnephin** [comment] 2015-03-25 17:53
Yup, duplicate of #753

**Comment by dnephin** [comment] 2015-07-03 14:31
Going to track this issue in #753

**Closed by dnephin** 2015-07-03 14:31 UTC
