### ISSUE TITLE
'docker-compose ps' fails if env file is missing

### ISSUE THREAD

**Issue by sherter** [docker/compose#1830] opened 2015-08-08 14:50 UTC
Compose refuses to list containers if a environment file is missing. This is an unnecessary limitation, isn't it? One could use ` docker exec $(docker-compose ps -q service) env` to restore the environment file, if the container is still running.

**Comment by aanand** [comment] 2015-08-10 10:53
I agree that there's no need for `docker-compose ps` to refuse to run if an env file is missing.

Although I don't recommend using that command - you'd also get unwanted variables like `HOME` and `PATH`.

**Comment by dnephin** [comment] 2016-02-03 19:37
Duplicate of #1973

**Closed by dnephin** 2016-02-03 19:37 UTC
Labels: kind/bug
