### ISSUE TITLE
[BUG] env_file processing seems to have quietly changed somewhere between 2.23.3-desktop.2 and 2.24.5-desktop.1

### ISSUE THREAD

**Issue by Philgo68** [docker/compose#11705] opened 2024-04-09 16:47 UTC
### Description

An environment file specified multiple times does not get applied the same way between 2.23 and 2.24

### Steps To Reproduce
While using Docker Desktop ver 4.26.1 on Windows consider this basic setup:
**default.env**
```
FROM_DEFAULT=1
DATABASE=TEST
```

**production.env**
```
FROM_PRODUCTION=1
DATABASE=LIVE
```

docker-compose.yml
```
services:
  env_test:
    image: ubuntu
    env_file:
      - default.env
      - production.env
    command: env
```

docker-compose.override.yml
```
services:
  env_test:
    env_file:
      - default.env
```

in 2.23.3-desktop.2 you get:
```
env_test-1  | DATABASE=TEST
env_test-1  | FROM_PRODUCTION=1
env_test-1  | FROM_DEFAULT=1
```

In 2.24.5-desktop.1 you get:

```
env_test-1  | DATABASE=LIVE
env_test-1  | FROM_PRODUCTION=1
env_test-1  | FROM_DEFAULT=1
```

Previous versions applied the default.env multiple times  (default/production/default), but currently it only applies the file the first time (default/production), quietly changing the env inside the container with the different compose versions.

If you change the override to have 
```
    env_file:
      - ./default.env
```

You can get the env to be applied twice (default/production/default) and get back to the old behavior.

### Compose Version

2.23.3-desktop.2 to 2.24.5-desktop.1

### Docker Environment

Docker Desktop for Windows 4.26.1
to 
Docker Desktop 4.27.2 and above.

### Anything else?

If this is an intended change, I could not find anything in the version changelog to indicate so.

**Comment by ndeloof** [comment] 2024-04-11 13:48
The root cause it that the loader has to guess if your override tries to change the definition of the first `default.env` env_file (as you can have long syntax to declare `required`) _or_ you want to load the same file multiple time in distinct order, which sounds odd.

A possible workaround is for you to use `!override` in your compose.override.yaml file so that values from the main compose file are just ignored:

```yaml
    env_file: !override
      - default.env
```

**Comment by Philgo68** [comment] 2024-04-11 16:41
Thanks for the !override example.  That will indeed make it more explicit what is desired.

Odd or not, that still doesn't address the fact that the "guess" that has to be made has changed results in recent versions.  If I had not caught this in our development environment by accident, our next deploy of the EXACT same project would have pointed to a different database when Docker was updated on the server.  This change in the "guessing" should at least be mentioned in the change log.

I would expect env_file processing (without the !override setting) to simply add the file(s) to the bottom of the list with no guessing or analysis.  Then apply them top to bottom, again with no guessing or analysis.  This is what seemed to be happening in the past.

**Comment by ndeloof** [comment] 2024-04-11 16:52
For sure I fully understand your concern with this change, I'm just saying this isn't a common pattern so wasn't identified earlier as a "feature".

> I would expect env_file processing (without the !override setting) to simply add the file(s) to the bottom of the list with no guessing or analysis. Then apply them top to bottom, again with no guessing or analysis. This is what seemed to be happening in the past.

That's the point. `env_file` items are not just file paths, they can have sub-attributes (`required`)  someone might want to override:

compose.yaml
```yaml
services:
  foo:
    env_file:
      - path: secrets.env
         required: false
```

compose.override.yaml
```yaml
services:
  foo:
    env_file:
      - path: secrets.env
         required: true
```

the entry to override is identified by path. so `env_file` merges both entries into a single one.
In the past, `env_file` didn't had such sub-structure so no dedicated merge logic was needed.

**Comment by Philgo68** [comment] 2024-04-11 17:18
Overriding the required flag AND sliding the entry down to the bottom of the list would maintain the old results for those odd duck projects like mine.  (But doesn't leave a way for someone to keep the env_file order alone, while resetting the required flag...)

I'll add the env_file: !override to my project so my odd duck keeps quacking.

Thanks for the conversation and I hope this helps out anyone else seeing unexpected env_file processing changes.

**Comment by ndeloof** [comment] 2024-04-12 09:10
sliding the entry down to the bottom would also have some impacts, as a second env file maybe relies on some variables set by the other one.

I'm closing this issue as "won't fix" as we have a reasonable workaround and more changes in this area would break some more regressions.

**Closed by ndeloof** 2024-04-12 09:10 UTC
Labels: kind/bug, status/0-triage
