### ISSUE TITLE
Bash completion syntax error

### ISSUE THREAD

**Issue by ksmithut** [docker/compose#1386] opened 2015-05-05 14:30 UTC
When loading the bash completion, it's giving me the following errors:

```bash
$ . /usr/local/etc/bash_completion.d/docker-compose
-bash: /usr/local/etc/bash_completion.d/docker-compose: line 97: syntax error near unexpected token `('
-bash: /usr/local/etc/bash_completion.d/docker-compose: line 97: `			_filedir y?(a)ml'
```

Notes and System Specs:
* Macbook Pro (Retina, 15-inch, Mid 2014)
* OS X 10.10.3
* installed via homebrew `brew install docker-compose`

Let me know if you need any further information to help in resolving the issue.

**Comment by thaJeztah** [comment] 2015-05-05 19:25
Could you add the version of bash that is used, i.e. `bash --version`. IIRC, OS X used an older version of bash, which could be relevant here.

/cc @albers :)

**Comment by ksmithut** [comment] 2015-05-05 19:37
`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)`

**Comment by albers** [comment] 2015-05-05 20:19
Darn! This is extglob shell option not being set. I thought I had added this option here, but it was just  for docker completion. On Ubuntu it is set anyway, but on Mac obviously not.

I'll look into it more deeply tomorrow. @thaJeztah Can you please assign the issue to me?

**Comment by thaJeztah** [comment] 2015-05-05 21:02
@albers would love to, but I don't have write permissions in this repository

ping @aanand @bfirsh @dnephin could one of you assign, and add a bug/regression label?

**Comment by dnephin** [comment] 2015-05-05 21:09
I'm not able to assign it to @albers, not sure why.

**Comment by thaJeztah** [comment] 2015-05-05 21:45
Hm, maybe because he's not a "collaborator"?

Well, looks like we will have to manually ping @albers on a daily basis then :smile:

**Comment by albers** [comment] 2015-05-06 10:13
@ksmithut 
Hi Keith, I think I fixed it, see #1391. Can you please check if this works for you?
You can install the fixed version with

    curl -L https://raw.githubusercontent.com/albers/compose/completion-extglob/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose

Upon next login, completion should work.

**Comment by ksmithut** [comment] 2015-05-06 13:55
That did the trick :) Thank you all for your quick response!

**Comment by ksmithut** [comment] 2015-05-06 13:56
whoops, I'll let you close it when it gets merged

**Comment by thaJeztah** [comment] 2015-05-06 14:00
NP, thanks for reporting, @ksmithut!

**Comment by albers** [comment] 2015-05-06 14:04
Thanks for the quick evaluation, @ksmithut!

**Closed** 2015-05-06 14:46 UTC
Labels: bug

**Comment by thaJeztah** [comment] 2015-05-06 16:37
@albers are similar changes required in the scripts for Docker, or do they already have this change?

thanks a lot btw for the quick fix!

**Comment by albers** [comment] 2015-05-06 21:48
Bash completion for Docker already contains this fix. It is safe.

**Comment by thaJeztah** [comment] 2015-05-06 22:19
@albers thx, just checking (better safe than sorry)
