### ISSUE TITLE
[Feature Request] Shared Networks

### ISSUE THREAD

**Issue by Tockra** [docker/compose#6269] opened 2018-10-12 05:17 UTC
## Description of the issue

For beginning I have to admit this request is releated with #6096 and #4179 . But since that issues wasn't discussed fair and the most discussion participants didn't understand the problem I open this specific feature request.
## Feature
There should be a equivalent for external networks which creates the network when it doesn't already exists.
You can do this e.g. by adding a different keyword like "shared" for networks.

What is a shared network?
A shared network is a network, which will be created if there isn't a network with the same name,
which won't be created (just used) if there is a network with the same name,
which will be delete if no other docker container uses that network, 
which won't be delted if a other docker container uses that network.

What is the intend? 
You can use docker-container in the same network without notice a specific order while using docker-compose up and you don't need to hack your intend with help of scripts.

## Example where to use the feature
I have n docker container which need to be in the same network because all of them need to interact with each other. I don't add all n services in the same docker file because reasons of overview.

I have to use a specific network name in the networks definition like this:
```
networks:
    my_network:
        name: cool-name
```
Now I have following possibilities:
1. Use above definition in 1 docker-compose file and in all other n-1 docker-compose files I have to use the "external" keyword.
=> **Problem:** I have to start the non-external network container before I start the n-1 docker container, I have to stop the non-external  network container after I stopped all other.
2. I use only the "external" keyword and create the network with "docker network create"
=> **Problem:** In my eyes that possibility offends the docker-compose principe. I'm using docker-compose to avoid docker commands. Additionally its not nice for other administrators if they want to use my docker-compose file
3. Use above definition in all n-1 docker-compose files.
=> **Problem:** If you try to docker-compose down a a container while a other container still uses the cool-name network you'll get a error. That is okay, because my solution is just a hack but it is annoying because my hack works and there is no other docker-compose-way to solute the problem of shared networks. 

## Example how to use the feature
Just add in every docker-compose.yml:
```
networks:
        my_shared_network:
            shared:
                name: cool-name-of-shared-network
```

I hope I could clarify my point of view and the importance of that feature. 
If there is a docker-compose way to realize shared networks than say it but don't mention ugly hacks, please. Just because there are ugly ways (see above) to realize a shared network it's not reason not to add that feature...

**Comment by shin-** [comment] 2018-10-12 07:47
Duplicate of #6096

**Closed by shin-** 2018-10-12 07:47 UTC

**Comment by Tockra** [comment] 2018-10-12 07:58
Yes I wrote that this is a duplicate. 

I thought that is the idea of open source technologie. 
Everybody can decide and/or work on a project. 
Not only you shin- ...

**Comment by shin-** [comment] 2018-10-12 08:04
Yes, and you can keep the discussion going in the original thread. Multiple issues discussing the same thing make it more difficult for everyone to keep track and serves no practical purpose.

**Comment by Tockra** [comment] 2018-10-12 08:06
Then reopen it please

**Comment by JonasT** [comment] 2018-12-31 01:03
@shin- I suggest this one here is opened, this describes the real problem, the other issue was a symptom.

The discussion in the other ticket IMHO isn't particularly relevant, since we didn't really get anywhere (or do you feel like we did?). I'm still interested in helping out with implementing this but I failed to get a response of any sorts of how to go about this (like, isn't there a way we can figure out how this should be designed that makes everyone happy?) other than me just randomly dumping a pull request that might not get accepted...

Hoping we can get somewhere with this! Let me know where you're at

**Comment by JonasT** [comment] 2019-04-15 21:40
@shin- @thaJeztah or anyone else, would it be possible to reopen this or any of the other mentioned issues and figure out if maybe something can be implemented? (as mentioned before I might be interested in helping with it) The discussion on this was just kinda cut off, but there are a couple of people affected by this
