### ISSUE TITLE
[BUG] docker compose -f <> ps consists of services not in the file

### ISSUE THREAD

**Issue by deeTEEcee** [docker/compose#10381] opened 2023-03-17 16:57 UTC
### Description

`docker compose -f docker-compose-test.yml ps ` still shows me services not created by this file.

### Compose Version

```Text
v2.15.1
```

**Comment by kamilpi** [comment] 2023-03-24 15:47
Hi @deeTEEcee 

It is not a bug. You just use the same project name for services inside this ```compose```.
https://github.com/docker/compose/blob/bfeb1dc2775c962c6994c662d063e18f2ac9956d/pkg/compose/create.go#L88

There is a label created when you are creating services from compose.
```
com.docker.compose.project
```

When you specify ```-p``` parameter then you can decide how this project should be named, if not then it will be generated from the directory name where this compose is.

So if you called a different project .e.g ```compose-test``` and this ```docker-compose-test.yml``` you have in the directory called the same then you will see all from ```ps``` command.

https://docs.docker.com/engine/reference/commandline/compose_up/#options

**Comment by bedilbek** [comment] 2024-04-16 12:28
@ndeloof, @kamilpi 
Why the behavior of `-f` is not consistent with other commands?

There were same issues with other commands that were already discussed and fixed:
1. `logs` did not respect `-f` before [2.11.0](https://docs.docker.com/compose/release-notes/#2110). It was fixed in the PR #9801 
2. `up` did not respect `-f` before [2.14.0](https://docs.docker.com/compose/release-notes/#2140). It was fixed in the PR #10028 

And why do you think the asked behavior is not desired? I would also want the behavior of `ps` to respect `-f` option in any circumstance.

**Comment by bedilbek** [comment] 2024-04-16 14:00
@ndeloof I am not really aware of decisions that were made to maintain desired backward compatibility.  However, introduced workaround is working as intended. Thanks. I also saw that this is relatively new feature that has been added recently.

**Comment by ndeloof** [comment] 2024-04-19 12:37
Closing this issue as workaround allows to get the desired behavior and maintain backward compatibility

**Closed by ndeloof** 2024-04-19 12:37 UTC
Labels: kind/bug
