### ISSUE TITLE
compose v2 'up' starts services that have scale: 0

### ISSUE THREAD

**Issue by briceburg** [docker/compose#8651] opened 2021-09-21 19:11 UTC
## Description of the issue

compose v2 starts service containers that have `scale: 0`. compose v1 did not. 

previously I used `scale: 0` to mark a services as a oneshot service, and would use `docker-compose run <oneshot service>` to  start it.

## Context information (for bug reports)

compose v2 rc 3

(previous behavior was from compose 1.29)

example composition
```yml
---
version: "3.9"

services:
  nginx:
    image: nginx:1.20
    volumes:
      - shared:/usr/share/nginx/html:ro
    ports:
      - 80

  oneshot:
    image: alpine:3.14
    command: echo "hello" > shared/index.html
    scale: 0

    volumes:
      - shared:/app/shared:rw

volumes:
  shared:
```

## Steps to reproduce the issue

1. add `scale: 0` to a service
2. bring up the stack with docker compose up
3. notice that the service with scale: 0 was started

### Observed result
```
$ docker compose up
[+] Running 2/0
 ⠿ Container product-1_oneshot_1  Created                                                                                                                                                                                   0.0s
 ⠿ Container product-1_nginx_1    Created                                                                                                                                                                                   0.0s
Attaching to nginx_1, oneshot_1
oneshot_1  | hello
oneshot_1 exited with code 0
nginx_1    | 2021/09/21 19:02:49 [notice] 1#1: using the "epoll" event method
nginx_1    | 2021/09/21 19:02:49 [notice] 1#1: nginx/1.20.1
nginx_1    | 2021/09/21 19:02:49 [notice] 1#1: OS: Linux 5.10.47-linuxkit
```

### Expected result

to only start/create the nginx service

**Comment by mat007** [comment] 2021-09-22 04:49
Probably a duplicate of #8571?

**Comment by briceburg** [comment] 2021-09-22 14:37
@mat007 it does look related to #8571 -- That issue deals with scale in the runtime flags versus setting in the spec file / compose definition... however if the internals normalize it may cover my situation here too. Is there a good way to test?

**Comment by mat007** [comment] 2021-09-23 10:04
Not super easy as it’s been fixed in an upstream project in https://github.com/compose-spec/compose-go/pull/184 which I don’t we have updated in compose yet (@ndeloof could confirm).

We have a Docker Desktop release planned for in about a week, so there will definitely be a new compose V2 release a couple of days before that, though.

**Comment by ndeloof** [comment] 2021-09-23 11:14
this indeed has been fixed by https://github.com/compose-spec/compose-go/pull/184 + https://github.com/docker/compose/pull/8620

**Closed by ndeloof** 2021-09-23 11:14 UTC
Labels: kind/bug, Docker Compose V2
