### ISSUE TITLE
1.3.0 Unable to build image from private base image on Docker Hub

### ISSUE THREAD

**Issue by adambiggs** [docker/compose#1577] opened 2015-06-19 18:32 UTC
Using the latest version of Docker/Machine/Compose, trying to `$ docker compose build` a Dockerfile that is `FROM` a private base image hosted on Docker Hub doesn't work anymore:

```
$ docker-compose --verbose build app

Compose version 1.3.0
Docker base_url: https://192.168.148.247:2376
Docker version: KernelVersion=4.0.5-boot2docker, Os=linux, ApiVersion=1.19, Version=1.7.0, GitCommit=0baf609, Arch=amd64, GoVersion=go1.4.2
Building app...
docker build <- (nocache=False, stream=True, tag=u'my_project_app', rm=True, path='/Users/adam/my-project/app', dockerfile=None)
docker build -> <generator object _stream_helper at 0x10f2bd640>
Step 0 : FROM my-repo/my-private-image:latest
Pulling repository my-repo/my-private-image
Service 'app' failed to build: Error: image my-repo/my-private-image:latest not found
```

`$ docker pull my-repo/my-private-image` works as expected, but Compose still tries & fails to pull the image after this due to #1568.

Specifying the same private image directly in `docker-compose.yml` works totally fine:

```yml
privatetest:
  image: my-repo/my-private-image
```

```
$ docker-compose pull privatetest

Pulling privatetest (lightmaker/php:latest)...
latest: Pulling from my-repo/my-private-image

asdf123: Pull complete
asdf234: Pull complete
asdf345: Pull complete
...
Status: Downloaded newer image for my-repo/my-private-image:latest
```
----

```
$ docker version

Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
```
```
$ docker-compose version: 1.3.0

CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```
```
$ docker-machine --version

docker-machine version 0.3.0 (0a251fe)
```

**Comment by aanand** [comment] 2015-06-19 18:54
Duplicate of #1568, fixed by #1570

**Closed by aanand** 2015-06-19 18:54 UTC

**Comment by adambiggs** [comment] 2015-06-19 19:00
Oops, sorry. I thought #1568 only covered reusing local images that have already been built, but I should have read the description more thoroughly.

**Comment by aanand** [comment] 2015-06-19 20:12
Hm, actually I'm not sure this is a duplicate: if `docker-compose pull` works, then `docker-compose build` should work too, even with the bug described in #1568.

Do `docker pull` and `docker build` both work fine?

**Comment by MrMMorris** [comment] 2015-06-19 21:30
@aanand running into this while trying to solve another edge case. `compose up`, `compose build` and `docker build` all fail saying it can't find the private image. `docker pull` on that image works but then `compose up/build` still try and fail to pull the image.

**Comment by MrMMorris** [comment] 2015-06-19 21:37
`docker build -t blah .` works after `docker pull` but `compose up/build` does not

**Comment by aanand** [comment] 2015-06-19 22:00
After `docker pull`, does `docker build --pull .` work?

**Comment by MrMMorris** [comment] 2015-06-19 22:06
nope, same error. 

`Error: image company/dockerfiles:node-latest not found`

**Comment by aanand** [comment] 2015-06-19 22:31
OK, it sounds like you're experiencing two bugs, one of which is #1568 and one of which looks like a Docker bug: if `docker pull` works, then it seems like `docker build --pull` should too. It might or might not be a known issue, but I'd recommend searching/asking on [docker/docker](https://github.com/docker/docker).

For now, you can work around both by pulling the base image first, and then building, using the tag that Compose will look for:

    $ docker pull my-repo/my-private-image
    $ docker build -t <projectname>_<servicename> .
    $ docker-compose up

Here, `<projectname>` is the prefix given to each of your containers and images (it's the name of the current directory with all non-alphanumeric characters stripped), and `<servicename>` is the name of the service which uses the image.

**Comment by MrMMorris** [comment] 2015-06-19 23:48
@aanand I was the one who originally submitted the local image bug (https://github.com/docker/compose/issues/923). Was it not fixed with 1.3.0? https://github.com/docker/compose/pull/1344

I did what you suggested and it worked :+1:

**Comment by adambiggs** [comment] 2015-06-19 23:50
@aanand 

- `docker build` throws the same error if the base image doesn't exist locally
- After `$ docker pull my-repo/my-private-image`, `docker build` works as expected
- But `docker build --pull .` still fails

**Comment by rosskukulinski** [comment] 2015-06-20 00:05
I am also experiencing this issue as @adambiggs mentions.  ```docker build --pull``` always fails, ```docker build``` will succeed if the image has previously been pulled by ```docker pull```.

All using Dockerhub private repo.

**Comment by aanand** [comment] 2015-06-20 00:26
@adambiggs OK, that confirms what I thought. The workaround I detailed above should work for you; please let me know if it doesn't.

@rosskukulinski thanks for opening https://github.com/docker/docker/issues/14057. I'll keep an eye on it.
