### ISSUE TITLE
[BUG] critical error with max length project name

### ISSUE THREAD

**Issue by aid219** [docker/compose#11818] opened 2024-05-15 09:36 UTC
### Description

I used the doker in conjunction with windows 10 and vs-code. I experimented with the "name:" parameter in docker-compose.yml" file, and when I entered a name there with a length of a couple thousand characters and launched - "docker-compose up -d " the image was created and the container started. But when I opened the desktop application after that, I could no longer stop the container or delete it, all my attempts were interrupted with an error of too long a name. Restarting the application and restarting the computer did not give results, as a result, I had to uninstall the docker application and install it again

### Compose Version

```Text
v2.26.1-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.27
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.23
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.6.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.146.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.727GiB
 Name: docker-desktop
 ID: 46db15d9-f6b2-497b-8da5-28962cd4212d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

**Comment by glours** [comment] 2024-05-15 09:48
Hello @aid219 
Just to be sure, when you reference `name` you're talking about the Compose project name and not the image name, right?

**Comment by aid219** [comment] 2024-05-15 11:29
yes, its compose project name. For example, here is a docker-compose.yml file, but only the length of the name was much longer_

name:"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
services: 
    golang:
      build: ./
      image: im21
      container_name: golang21
      restart: always
      ports:
        - 80:7667

**Comment by aid219** [comment] 2024-05-15 11:49
now I tried to recreate the situation, the behavior is slightly different, now I can't do anything in the container section and I can't start a new one, last time I had access to the container section, but when I tried to stop and delete it, it gave an error

![1](https://github.com/docker/compose/assets/50398121/f6427ec9-8d3f-425f-acf8-78c3399e6155)
![2](https://github.com/docker/compose/assets/50398121/4864b12e-c1b4-4546-bcd0-f9e4b19b609e)

**Comment by aid219** [comment] 2024-05-15 12:06
yes, you're right, this is a docker desktop error, it stops from the terminal without any problems, do I need to send all the information to another branch again now, or can you somehow transfer it?

**Comment by glours** [comment] 2024-05-15 12:20
Thanks, I would take care of it 👍

**Comment by glours** [comment] 2024-05-15 16:21
@aid219 what is your Docker Desktop version? Did you use WSL2 or Hyper-V as virtual machine? Are you using Windows or Linux containers? 
I can't reproduce the issue on both Windows and Macs with the latest version of Desktop 🤔

**Comment by aid219** [comment] 2024-05-19 00:05
i use WSL2

**Comment by aid219** [comment] 2024-05-20 07:01
As far as I know, this is the Linux base of the container, now I have updated to the latest version of the docker - 4.30.0. And maybe you can't repeat the mistake due to the insufficient number of characters in the name, now I tried 5000,10000,20000 first and everything was fine. But after 42,000, everything breaks down. As you can see in the image, I have entered 42504 letters "z" in the project name. I will also show you my Dockerfile so that it will be easier for you to repeat
![docker123](https://github.com/docker/compose/assets/50398121/b2ba954e-3b72-44bb-af18-325f80c732cb)
![docker123_2](https://github.com/docker/compose/assets/50398121/c62a4667-85d3-479a-8263-9e1141a75408)
![docker123_3](https://github.com/docker/compose/assets/50398121/88ed4e99-0d3e-44a1-b285-be54d8fbd38e)

"

**Comment by aid219** [comment] 2024-05-20 08:04
and now I also cannot stop the container through the terminal as it turned out before, the command does not seem to do anything, as if it is executed without information output

**Comment by glours** [comment] 2024-08-06 14:12
Without any feedback for several months, I'm closing the issue

**Closed by glours** 2024-08-06 14:12 UTC
Labels: kind/bug
