### ISSUE TITLE
Regression in handling of environment variables declared in files set with `env_file`

### ISSUE THREAD

**Issue by camilledejoye** [docker/compose#9532] opened 2022-06-03 20:00 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Since the `2.6.0` release, environment variables defined with `env_file` in a docker compose file are overridden by the value of the same variable from the default `.env` file.

From the [Declare default environment variables in file documentation](https://docs.docker.com/compose/env-file/#compose-file-and-cli-variables):
> Environment variables defined in the .env file are not automatically visible inside containers.

**Steps to reproduce the issue:**
1. Create the following files
```yaml
# docker-compose.yaml
services:
  simple:
    image: alpine:latest
    env_file:
      - .env.base

  overridden:
    image: alpine:latest
    env_file:
      - .env.base
```
```yaml
# docker-compose-dev.yaml
services:
  overridden:
    env_file:
      - .env.local
```
```sh
# .env
MY_VAR=default
```
```sh
# .env.base
MY_VAR=base
```
```sh
# .env.local
MY_VAR=local
```
2. Run
```sh
docker compose run simple printenv MY_VAR && \
docker compose -f docker-compose.yaml -f docker-compose-dev.yaml run -it overridden printenv MY_VAR
```

**Describe the results you received:**

Current output:
```
default
default
```

**Describe the results you expected:**

Expected output:
```
base
local
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Removing the `.env` file generates the expected output.

Specifying the environment files manually also generates the expected output:
```sh
docker compose --env-file .env.base run simple printenv MY_VAR && \
docker compose -f docker-compose.yaml -f docker-compose-dev.yaml --env-file .env.base --env-file .env.local run -it overridden printenv MY_VAR
```
Which makes sense since the documentation specify that the files defined with `--env-file` on the command line will override the default file path ([here](https://docs.docker.com/compose/environment-variables/#using-the---env-file--option)).

Works in version `2.5.0` and `2.5.1` (who doesn't like irony).

**Output of `docker compose version`:**

```
Docker Compose version 2.6.0
```

**Output of `docker version`:**

```
Client:
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        aa7e414fdc
 Built:             Sat May 14 12:48:33 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       f756502055
  Built:            Sat May 14 12:47:27 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16.m
 runc:
  Version:          1.1.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., 2.6.0)

Server:
 Containers: 10
  Running: 0
  Paused: 0
  Stopped: 10
 Images: 15
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.18.1-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.57GiB
 Name: cdejoye-arch
 ID: YFDR:NZWH:MQ5W:LNXA:3F47:VZMQ:7MPC:MUKR:4LT6:SUFM:TRTW:BTFN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by glours** [comment] 2022-06-03 20:11
duplicate of #9521

**Closed by glours** 2022-06-03 20:11 UTC

**Comment by camilledejoye** [comment] 2022-06-03 20:14
Oups
