### ISSUE TITLE
Custom metadata in docker-compose.yml

### ISSUE THREAD

**Issue by gionn** [docker/compose#2684] opened 2016-01-18 12:27 UTC
Hi,

we would love the possibility to have arbitrary metadata in a docker-compose.yml file, to be simply ignored by compose itself, but would be consumed by third-party tools that integrates with compose.

We are aware of [labels](https://docs.docker.com/compose/compose-file/#labels), but they apply to single containers only.

Just to keep things simple, just having a first-level keyword like "metadata" that would not be treated as a new service by composer would be great.

An ugly and felon workaround would be to put metadata as comments inside the YAML, but then is not trivial anymore to parse a docker-compose.yml with any standard YAML library.

Thanks.

**Comment by dnephin** [comment] 2016-01-18 15:17
I believe this is a duplicate of #2578 and #1655

**Comment by dnephin** [comment] 2016-02-04 22:39
Going to close as a duplicate of the above linked issues.

**Closed by dnephin** 2016-02-04 22:39 UTC
Labels: area/config
