### ISSUE TITLE
env_file parsing does not handle unquoted whitespace cleanly 

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/compose#8763] opened 2021-10-07 10:23 UTC
**Description**

Using an env_file with unescaped whitespace keys breaks compose. Additionally, the error message does not really tell the user which file / line is in issue, or that it's an env_file issue at all

**Steps to reproduce the issue:**

docker-compose.yml:
```yaml
services:

  alpine:
    image: alpine
    env_file: variables.env
```

variables.env:
```
VAR=foo bar baz
```

run `docker compose config`

**Describe the results you received:**

```bash
% docker compose config
key cannot contain a space
```

Because the error message does not mention the env file, with a large Yaml config it's very unclear where the problem may lie

**Describe the results you expected:**

This works with v1:

```
% docker-compose config
services:
  alpine:
    environment:
      VAR: foo bar baz
    image: alpine
version: '3.9'
```

If the whitespace in the env file is valid, compose should behave the same as v1.

If it's not possible to change the env parsing at this stage, there needs to be an error message that makes it clear what has happened. Ideally we'd point to the line number in the .env file, but if that's not technically possible we could point to the line number of the env_file: in the Yaml

**Output of `docker compose version`:**

```
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.0.0)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 42
  Running: 16
  Paused: 0
  Stopped: 26
 Images: 73
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 11.68GiB
 Name: docker-desktop
 ID: 552J:DQQK:IROJ:YEMG:H5VB:EUS5:5MEX:VKDI:CQAG:KHXR:CLTY:TJY5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Comment by nawa** [comment] 2021-10-07 16:04
Also it doesn't handle `"` properly complaining `unexpected character "\"" in variable name near`

There was no issue in `v2.0.0-rc.3`

**Comment by jordanbrowneb** [comment] 2021-11-03 15:28
This is causing a major regression in our projects. Can anyone confirm if a workaround exists?

**Comment by dannylee8** [comment] 2021-11-05 01:24
I have this same issue, and agree with @ciaranmcnulty in regards to being okay with the issue being "fixed" or my env files being "fixed".  And, I agree that a succinct error msg would be useful to the community.  I imagine people will continue to stumble upon this issue and end up here *eventually*, as I did.

**Comment by jansonjc** [comment] 2021-11-05 05:20
Is there an official confirmation whether this will be fixed in docker compose or we need to "fix" our env files? If it is going to be fixed in V2, then there is no point in fixing all the env files, as we could continue to use v1.x until the fix is in place. Also, I agree with @dannylee8 and @ciaranmcnulty that a better error message would help.

**Comment by ulyssessouza** [comment] 2021-11-05 13:54
We will have a look at the parser to check how complicated that would be without breaking the multiline feature.
Since that's a forked code that's not that clear for now. I recommend to fix the env files for now. 
But we will have a look at this to try to fix that.

**Comment by cruizba** [comment] 2022-04-21 21:13
Is this issue fixed with this commit? https://github.com/compose-spec/godotenv/commit/655269e2565760ac457e473904300398c6150d47

I've updated my deployments to version v2.4.1 and seems to work without spaces

This is also mentioned here: https://github.com/docker/compose/issues/8879

**Comment by milas** [comment] 2022-09-02 16:11
There have been a lot of improvements around environment variable handling in recent Compose v2 releases between `.env` files, precedence rules, interpolation, and more.

The issue here has been resolved, this now works in v2:
```shell
❯ docker compose config
```
```yaml
name: compose-env
services:
  alpine:
    environment:
      VAR: foo bar baz
    image: alpine
    networks:
      default: null
networks:
  default:
    name: compose-env_default
```

**Closed as completed by milas** 2022-09-02 16:11 UTC
Labels: kind/docs
