### ISSUE TITLE
`Unicode error` with a unused file named using UTF-8 characters

### ISSUE THREAD

**Issue by ecuer-thomas** [docker/compose#1448] opened 2015-05-22 09:05 UTC
Hi,

Naming a file using UTF-8 characters, even when it's unrelated to any build process, leads to python's "UnicodeDecodeError". It's not a major issue, but the error message (traceback) is not really relevant.

```sh
$ ls
nginx/    api/   database/  docker-compose.yml

$ touch nginx/é
$ docker-compose -f docker-compose.yml build 
Building database...
Step 0 : FROM debian:wheezy
 ---> b96d1548a24e

[...]
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.utils.utils", line 73, in tar
  File "/code/build/docker-compose/out00-PYZ.pyz/os", line 284, in walk
  File "/code/build/docker-compose/out00-PYZ.pyz/posixpath", line 80, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

Version :
```
$ docker-compose --version
docker-compose 1.2.
```

Docker-compose.yml :
```yaml
$ cat docker-compose.yml 

database:
  build: database/

  expose:
    - "5432"
api:
  
  build: api/
  links:
    - database
  #ports:
  #  - "5000:5000"
  expose:
    - "5000"

nginx:
  build: nginx/
  links:
    - api
  ports:
    - "80:80"
    - "443:443"
```

**Comment by aanand** [comment] 2015-05-22 12:09
That file isn't unrelated to any build process - being inside the `nginx` directory, it's part of the `nginx` build, and is thus part of the tarball that's sent to the server.

This is probably a duplicate of https://github.com/docker/compose/issues/1314, which should be fixed by https://github.com/docker/compose/pull/1376.

**Closed** 2015-05-22 12:10 UTC

**Comment by opyate** [comment] 2015-05-31 13:08
Just a note: for me it was character ```0xcc```, which is ```Ì```. I grepped for it in my projects, and it flagged up a few binaries in ```.tox``` (which is [a Python test tool](https://pypi.python.org/pypi/tox)) which shouldn't be part of the build anyway, so I added it to ```.dockerignore``` and all is fine for the time being.
