### ISSUE TITLE
Compose build doesn't respect credential helpers

### ISSUE THREAD

**Issue by laszlocph** [docker/compose#5854] opened 2018-04-06 09:15 UTC
When I'm running `docker-compose build` it's not able to pull private base images.

**WHAT I EXPERIENCE**
I use docker-credential-gcr and my `~/.docker/config.json` is correctly set up.

* I'm able to do `docker pull myprivaterepo/myimage`
* I'm able to do `docker-compose pull` if the image is used as a service image
* I'm not able to do `docker-compose build` as the private base image cannot be pulled.

ERROR: Service 'hello' failed to build: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

**WHAT I EXPECT**
Since I'm able to pull the image with `docker pull`, Compose should be able to pull too even in a build phase.

**REPRO CASE**

Dockerfile
```
From myprivaterepo/myimage
```

docker-compose.yml
```
version: '3.2'

services:
  hello:
    build: &build
      context: .
```

**ENV**
```
cat ~/.docker/config.json 
{
        "auths": {},
        "credHelpers": {
                "asia.gcr.io": "gcr",
                "eu.gcr.io": "gcr",
                "gcr.io": "gcr",
                "staging-k8s.gcr.io": "gcr",
                "us.gcr.io": "gcr"
        }
}
```

```
$ docker --version
Docker version 18.03.0-ce, build 0520e24
$ docker-compose --version
docker-compose version 1.20.1, build 5d8c71b
```

**Comment by shin-** [comment] 2018-04-09 18:30
does using the CLI (`docker build`) to build that same image work? You mention that `pull` works in both cases, but I'm curious to know whether the `build` behavior is different or not.

**Comment by gregdaybreak** [comment] 2018-04-25 22:09
I also have this issue. Am using Google Container Registry and docker-compose cannot pull the image saying I do not have permissions. When I do a docker build and build the Dockerfile that way it works fine.

**Comment by gregdaybreak** [comment] 2018-04-25 22:11
actually I was able to get it to work by running 

gcloud docker --authorize-only

**Comment by shin-** [comment] 2018-04-25 22:16
@laszlocph Was this on Windows by any chance?

**Comment by laszlocph** [comment] 2018-04-26 06:39
Ubuntu 17.10 :(

**Comment by mklinke** [comment] 2018-10-08 23:29
Possibly related: #5950

**Comment by lmapii** [comment] 2018-11-27 15:38
same here on macos 
```
> uname -a
Darwin talentix.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

> docker -v
Docker version 18.06.1-ce, build e68fc7a

> docker-compose -v
docker-compose version 1.23.1, build b02f130
```
and linux
```
> uname -a
Linux 123-test 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> docker -v
Docker version 18.06.1-ce, build e68fc7a

> docker-compose -v
docker-compose version 1.21.0, build unknown
```

build passes if all images are retrieved using `docker pull`  `docker-compose build`

**Comment by laszlocph** [comment] 2019-10-10 08:02
Satisfying the stale bot with this comment. The above linked PR has promising work aiming to solve this.

**Comment by glours** [comment] 2019-10-10 16:14
Can't reproduce your issue with the last version of compose
```sh
> docker-compose version
docker-compose version 1.24.1, build 4667896
docker-py version: 3.7.3
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```
&
```sh
> gcloud --version
Google Cloud SDK 266.0.0
bq 2.0.48
core 2019.10.04
docker-credential-gcr
gsutil 4.44
```

Can you give a try & let me know ?

**Comment by laszlocph** [comment] 2019-10-21 11:50
I cannot reporoduce the issue anymore :+1: 

```
➜  docker-compose version
docker-compose version 1.21.0, build 5920eb0
docker-py version: 3.2.1
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
➜  docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:35:29 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by glours** [comment] 2019-10-21 14:20
Cool 👍 
So I close the issue, thanks for your feedback

**Closed by glours** 2019-10-21 14:20 UTC
Labels: area/build, docker-py, kind/bug, status/0-triage
