### ISSUE TITLE
Execution failure in non-ascii directory

### ISSUE THREAD

**Issue by AidanDelaney** [docker/compose#2234] opened 2015-10-21 09:45 UTC
Using docker-compose version 1.4.2 the execution of the build command fails if the underlying directory name contains non-ascii characters.  In the example below I use the u-umlaut character, which is in extended ascii and is common in several European languages.

A minimal working example is below:

```bash
$ mkdir Füü
$ cd Füü/
$ touch docker-compose.yml
$ $ cat << EOF > docker-compose.yml
web:
  build: .
  ports:
    - "8080:8080"

EOF
$ touch Dockerfile
$ docker-compose build
Building web...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.4.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 39, in main
    command.sys_dispatch()
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 135, in build
    project.build(service_names=options['SERVICE'], no_cache=no_cache)
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 242, in build
    service.build(no_cache)
  File "/usr/lib/python2.7/site-packages/compose/service.py", line 683, in build
    path = six.binary_type(self.options['build'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)
```

For information, my system has the following locale settings

```bash
$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by dnephin** [comment] 2015-10-21 14:53
I believe this is fixed in 1.5.0 and master. Would you mind trying it out with the release candidate? https://github.com/docker/compose/releases/tag/1.5.0rc1

**Comment by kuailedubage** [comment] 2015-10-23 08:17
I also meet the same problem when I use directory containing non-ascii characters(Chinese character).

**Comment by dnephin** [comment] 2015-10-23 15:08
Ok, for some reason this is passing in our test suite, but failing with the binary created by pyinstaller. I'm going to look into it some more.

**Comment by dnephin** [comment] 2015-10-23 15:34
It looks like upgrading pyinstaller to 3.0 fixes this issue. I've opened #2245 to upgrade

**Comment by kuailedubage** [comment] 2015-10-26 02:55
Thanks.But it didn't work until I replaced `"{}:{}"` with `u"{}:{}"` in line 510 of  `config.py` in `dnephin:upgrade_to_pyinstaller_3`

**Closed** 2015-10-26 11:54 UTC
Labels: area/build, kind/bug

**Comment by dnephin** [comment] 2015-10-26 15:02
@kuailedubage I wasn't able to reproduce the issue at all outside of the binary build (which doesn't let me edit the file).  I think you're hitting  a different, but related issue. The line you reference is about volumes, not the config path.

Would you mind opening a new issue with an example to reproduce the error? That way I can write a test for it and fix it.

Thanks!

**Comment by dnephin** [comment] 2015-10-26 17:35
I opened #2259
