### ISSUE TITLE
Panic when using "docker-compose down"

### ISSUE THREAD

**Issue by cdupont** [docker/compose#9215] opened 2022-02-28 17:30 UTC
**Description**

I get "index out of range" when using "docker-compose down".

**Steps to reproduce the issue:**

My docker-compose.yml:
```
version: "3.9"

services:
  wazigate-lora:
    build: .
```
I do:
```
$ docker-compose down
panic: runtime error: index out of range [0] with length 0

goroutine 24 [running]:
github.com/docker/compose/v2/pkg/compose.getCanonicalContainerName({{0x40004d9080, 0x40}, {0x178f060, 0x0, 0x0}, {0x400035cc80, 0x1c}, {0x40000a82d0, 0x47}, {0x40003f3480, ...}, ...})
```

Note that there are several containers with similar names:
```
$ docker ps -a
CONTAINER ID   IMAGE                                     COMMAND                  CREATED        STATUS                PORTS     NAMES
736403af7886   waziup/wazigate-lora:latest               "./wazigate-lora"        4 hours ago    Created                         waziup.wazigate-lora
b09fcec120a6   waziup/wazigate-lora:nightly              "./wazigate-lora"        44 hours ago   Removal In Progress             
```

**Output of `docker compose version`:**

```
Docker Compose version v2.2.3
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 28
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.92-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.706GiB
 Name: wazigate
 ID: 7XU2:PK3H:6YFI:KZSU:3K46:6B5H:OHG5:ECTK:JVYI:F63Y:SA6I:X5GT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support

```

**Additional environment details:**

I'm running on a Raspberry 4 with arm64.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
```
$ uname -a
Linux wazigate 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
```

**Comment by ndeloof** [comment] 2022-03-01 08:37
thanks for reporting this issue.
So container `b09fcec120a6 ` has no assigned name, probably because as part of the "Removal In Progress" state it gets un-named but we fell into some race condition trying to list containers by name.

**Comment by ndeloof** [comment] 2022-03-01 08:44
if this container still exists on your system (or you can reproduce this issue), could you please attach to this issue the result of `docker inspect <ID>` on such an unnamed container? Would help us understand why such a container is detected as part of the `down` command and how to address this issue
(we can offer a fool-guard solution to avoid panic, but better understand possible race condition here)

**Comment by cdupont** [comment] 2022-03-01 09:07
This morning the container is still there:
```
 $ docker ps -a
b09fcec120a6   waziup/wazigate-lora:nightly                  "./wazigate-lora"        2 days ago    Removal In Progress 
```
With no name.

```
$ docker inspect b09fcec120a6
[]
Error: No such object: b09fcec120a6
```
It seems that there is a problem in the removal process... How to avoid it?

**Comment by cdupont** [comment] 2022-03-01 11:54
Doing:
```
sudo systemctl restart docker
```
Solves the problem temporarily.
But it comes back in my next deployment:

```
$ docker ps -a
CONTAINER ID   IMAGE                                         COMMAND                  CREATED          STATUS                PORTS     NAMES
       
76db2574550c   waziup/wazigate-lora:nightly                  "./wazigate-lora"        2 hours ago      Removal In Progress
```


Here are my Jenkins log (it does a cycle docker-compose down; docker-compose pull; docker-compose up -d:

```
+ docker-compose down
Container waziup.wazigate-system  Stopping
Container waziup.wazigate-system  Stopping
Container waziup.wazigate-lora.forwarders  Stopping
Container waziup.wazigate-lora.forwarders  Stopping
Container postgres  Stopping
Container postgres  Stopping
Container redis  Stopping
Container redis  Stopping
Container waziup.wazigate-lora.chirpstack-network-server  Stopping
Container waziup.wazigate-lora.chirpstack-network-server  Stopping
Container waziup.wazigate-lora  Stopping
Container waziup.wazigate-edge  Stopping
Container waziup.wazigate-edge  Stopping
Container waziup.wazigate-lora  Stopping
Container waziup.wazigate-lora.chirpstack-application-server  Stopping
Container waziup.wazigate-lora.chirpstack-application-server  Stopping
Container waziup.wazigate-lora.chirpstack-gateway-bridge  Stopping
Container waziup.wazigate-lora.chirpstack-gateway-bridge  Stopping
Container waziup.wazigate-mongo  Stopping
Container waziup.wazigate-mongo  Stopping
Container waziup.wazigate-system  Stopped
Container waziup.wazigate-system  Removing
Container waziup.wazigate-system  Removed
Container waziup.wazigate-edge  Stopped
Container waziup.wazigate-edge  Removing
Container waziup.wazigate-lora  Stopped
Container waziup.wazigate-lora  Removing
Container waziup.wazigate-edge  Removed
Container waziup.wazigate-lora  Removed
Container waziup.wazigate-lora.chirpstack-application-server  Stopped
Container waziup.wazigate-lora.chirpstack-application-server  Removing
Container waziup.wazigate-lora.chirpstack-gateway-bridge  Stopped
Container waziup.wazigate-lora.chirpstack-gateway-bridge  Removing
Container waziup.wazigate-lora.chirpstack-application-server  Removed
Container waziup.wazigate-lora.chirpstack-gateway-bridge  Removed
Container waziup.wazigate-mongo  Stopped
Container waziup.wazigate-mongo  Removing
Container waziup.wazigate-mongo  Removed
Container postgres  Stopped
Container redis  Stopped
Container postgres  Removing
Container redis  Removing
Container waziup.wazigate-lora.chirpstack-network-server  Stopped
Container waziup.wazigate-lora.chirpstack-network-server  Removing
Container redis  Removed
Container postgres  Removed
Container waziup.wazigate-lora.forwarders  Stopped
Container waziup.wazigate-lora.forwarders  Removing
Container waziup.wazigate-lora.chirpstack-network-server  Removed
Container waziup.wazigate-lora.forwarders  Removed
Network wazigate  Removing
Network wazigate  Removed
+ docker-compose pull
redis Pulling 
wazigate-lora-forwarders Pulling 
chirpstack-gateway-bridge Pulling 
postgresql Pulling 
chirpstack-network-server Pulling 
wazigate-system Pulling 
wazigate-lora Pulling 
wazigate-mongo Pulling 
chirpstack-application-server Pulling 
wazigate-edge Pulling 
wazigate-lora-forwarders Pulled 
chirpstack-gateway-bridge Pulled 
chirpstack-network-server Pulled 
wazigate-system Pulled 
wazigate-mongo Pulled 
wazigate-edge Pulled 
wazigate-lora Pulled 
redis Pulled 
postgresql Pulled 
chirpstack-application-server Pulled 
+ docker-compose up -d
Network wazigate  Creating
Network wazigate  Created
Container waziup.wazigate-lora.chirpstack-gateway-bridge  Creating
Container waziup.wazigate-lora.chirpstack-network-server  Creating
Container waziup.wazigate-mongo  Creating
Container redis  Creating
Container postgres  Creating
Container waziup.wazigate-lora.chirpstack-application-server  Creating
Container waziup.wazigate-lora.forwarders  Recreate
Container waziup.wazigate-system  Recreate
Container waziup.wazigate-lora  Recreate
Container waziup.wazigate-edge  Recreate
Container waziup.wazigate-lora.chirpstack-application-server  Created
Container postgres  Created
Container waziup.wazigate-lora.chirpstack-gateway-bridge  Created
Container redis  Created
Container waziup.wazigate-mongo  Created
Container waziup.wazigate-lora.chirpstack-network-server  Created
Container waziup.wazigate-lora  Recreated
Container waziup.wazigate-system  Recreated
Container waziup.wazigate-lora.forwarders  Recreated
Container waziup.wazigate-edge  Recreated
Error response from daemon: No such container: 76db2574550c0ebffadc6704fb1e00d320cc8fd58be178ce1581f56da64600f9
```

Maybe I should wait some seconds between each commands?

**Comment by cdupont** [comment] 2022-03-01 17:24
At the moment the problem shows up only when triggered from my Jenkins script.
Here it is: https://github.com/Waziup/WaziGate/blob/master/Jenkinsfile#L39

It calls a script located on the Raspberry PI: https://github.com/Waziup/WaziGate/blob/master/update_containers.sh

If I call that script from the Raspberry PI, it works. The bug show up only when Jenkins calls the script (each time).

**Comment by MadLittleMods** [comment] 2022-03-25 20:49
Looks like a duplicate of https://github.com/docker/compose/issues/8566 except when doing `docker-compose up`

**Comment by ndeloof** [comment] 2023-05-03 09:09
This indeed has been fixed by https://github.com/docker/compose/commit/22b8c731c7f06a4623dc9554bd92d83aa7ad914a

**Closed by ndeloof** 2023-05-03 09:09 UTC
