### ISSUE TITLE
extra_hosts are replaced, not augmented, by override file

### ISSUE THREAD

**Issue by jmkgreen** [docker/compose#3889] opened 2016-08-30 11:01 UTC
Docker version 1.12, Compose version 1.8.

See https://github.com/jmkgreen/docker-compose-test for simple test. Launch then exec into the running container.

Observe:

```
jamesg@virt-04:~/docker-compose-test$ docker exec -it dockercomposetest_debian_1 bash
root@b5ff7abaf0fd:/# cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.0.2     bar
172.23.0.2      b5ff7abaf0fd
```

Notice how the host `bar` is added by the override file, however I expected to see both `bar` and `foo` as `foo` comes from the `docker-compose.yml` file. It appears that the override file for `extra_hosts` replaces the values already found at interpolation time rather than augments the values.

**Comment by shin-** [comment] 2016-08-31 22:07
Thanks!
This is a duplicate of #3733 and will be fixed by #3812. I'll close this issue, but you can follow the resolution on the other ticket.

**Closed by shin-** 2016-08-31 22:07 UTC
