### ISSUE TITLE
Release Candidate 1.3.0 Issue: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by iMerica** [docker/compose#1478] opened 2015-05-29 07:50 UTC
Just upgraded to the 1.3.0 release candidate and got this:

```
❯ docker ps                                                                                                                                                  
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
❯ docker-compose ps                                                                                                                                           local_dev_plus/git/master 
SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

```

I"m on Docker version 1.6.0, build 4749651

**Comment by iMerica** [comment] 2015-05-29 07:55
Just downgraded to 1.2.0 and everything works as expected.

**Comment by aanand** [comment] 2015-05-29 08:05
Duplicate of #890, see #1474 for the (OS X) fix. RC2 coming imminently.

**Closed by aanand** 2015-05-29 08:05 UTC
