### ISSUE TITLE
Support setting DOCKER_HOST in .env file

### ISSUE THREAD

**Issue by jmera** [docker/compose#9210] opened 2022-02-26 18:34 UTC
**Description**

With Compose V1 we have the ability to set a project-specific `DOCKER_HOST` in .env, with V2 this is no longer possible.

**Steps to reproduce the issue:**
1. Add an `.env` file with a custom value for `DOCKER_HOST`
2. `docker compose` commands target the _default_ docker host

**Describe the results you received:**
`docker compose` commands target the _default_ docker host

**Describe the results you expected:**
`docker compose` commands target the docker host specified in .env

**Output of `docker compose version`:**

```
➜  ~ docker compose version
Docker Compose version v2.2.3
```

**Output of `docker info`:**

```
➜  ~ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 5.804GiB
 Name: docker-desktop
 ID: 6IUW:D7VH:NGSI:3VVB:WPYB:EQ3V:6JCD:IARV:6M6N:VRTI:MXNT:RCJ2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
N/A

**Comment by hskingr** [comment] 2022-04-05 14:04
I have experienced the same issue as prullmann after following their procedure.

Output of `docker compose version`:

`Docker Compose version v2.2.3`

Output of `docker info`:

```Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 16
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: Y3MP:EXFO:AJ4H:JHN3:ERHA:QFDT:JG47:YUDW:WRNQ:RV44:DSJI:FRFY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false```

**Comment by ndeloof** [comment] 2022-04-06 07:52
related to https://github.com/docker/compose/issues/9345

**Comment by prullmann** [comment] 2022-05-05 11:01
> I have experienced the same issue as prullmann after following their procedure. The `DOCKER_HOST` variable does work for me in the `.env` file though.

Can you please elaborate what works for you and what not?

**Comment by prullmann** [comment] 2022-05-13 12:52
> Had to use compose V1 as a result to read DOCKER_HOST from .env file.

@trcoelho Does that work well for you?
I noticed in my project that some compose commands like `docker-compose exec` also don't work with v1.
Exec seems to only use DOCKER_HOST from .env to discover the container, but to connect, it falls back to the current docker context and thus fails with `Error: No such container: ...`.
This sounds very much like #6661.

When I run `docker context use ...` to set the docker context to match the DOCKER_HOST in the .env file, `exec` works.
Setting DOCKER_HOST or DOCKER_CONTEXT as an environment variable also makes `exec` work again.
Adding `COMPOSE_INTERACTIVE_NO_CLI=1` to the .env file as suggested in #6661 does not work for me.

However, I struggled to create a small example to reproduce this behaviour.
Does `exec` work for you with compose v1?

**Comment by hskingr** [comment] 2022-05-13 17:58
@prullmann 

```yaml
- DOCKER_HOST
- DOCKER_CONTEXT
```

Both do not work as environment variables in docker compose v2

They both work when docker compose is set to v1 in the docker desktop preferences with the command `docker-compose up`

`docker-compose version`
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```
`docker compose version`
```
Docker Compose version v2.5.0
```

`docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.5.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 25
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: WXIK:2PC3:ZMKD:EAVM:BDJZ:3ATQ:MKAG:J34Q:Z42E:OW6Q:CO2M:PBCV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by prullmann** [comment] 2022-06-04 12:35
A few days ago commit #9521 was merged that could also fix this issue.
It looks like it's already included in [Compose v2.6.0](https://github.com/docker/compose/releases/tag/v2.6.0) and [Docker Desktop 4.90](https://docs.docker.com/desktop/release-notes/#docker-desktop-490) which was released two days ago.

**Comment by trcoelho** [comment] 2022-06-06 12:02
Hi @prullmann .

Have checked and still docker compose V2 does not read DOCKER_HOST environment variable as V1 does.
Have tested on latest Docker Desktop Version:

`Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: 35KN:CMFC:RTCR:5FGL:BI4P:UUYB:W6QF:J7H4:VCOD:W4TD:RYBJ:43IN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false`
 
 `Docker version 20.10.16, build aa7e414`
 
 
 Thank you.

**Comment by prullmann** [comment] 2022-06-09 11:16
It seems #9512 by @ulyssessouza implemented feature request #9345 not by loading the default `.env` file or using one from the `--env-file` command line argument.
Instead it's loading an `env_file` specified in a `docker_compose.yml`, as described in issue #9521.

**Comment by trcoelho** [comment] 2022-06-20 12:35
Hello @prullmann , as we can confirm that is really happening, do we have any scheduled date as a result to solve that?

Thank you.

**Comment by prullmann** [comment] 2022-06-28 08:51
Hi @trcoelho, I am just a user trying to help getting this fixed.
From the [git history](https://github.com/compose-spec/compose-go/commits/master), it looks like @ulyssessouza and @glours worked on issue #9521, but I can't see if this fixes also our issue here.
[New releases](https://docs.docker.com/compose/release-notes/) seem to be every few weeks, so we'll see if it's fixed quite soon, I guess.

**Comment by requiem240sx** [comment] 2022-06-28 18:55
Also can confirm that this has burned/caught me off guard a few times.  I forgot a few months ago, got a new laptop and its happening again.  

I use DOCKER_HOST to remotely manage multiple local compose servers and not have configs on the server.  This appears to not be possible unless you toggle (enable compose v2) in the docker desktop settings.  

An update would be awesome to get this resolved.  I'm wondering if I there would be a different way to change the docker daemon to point to a remote host.

**Comment by trcoelho** [comment] 2022-07-04 12:14
Hello, have updated to the latest Docker Desktop version 4.10.0 and this issue was not resolved.

`docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.7)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: NVSC:HJGR:ZFQG:IGI7:NA5N:UKHL:7CMX:46VF:KJ2S:UABI:BQGJ:ONNY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

`docker --version`

Docker version 20.10.17, build 100c701


Thank you.

**Comment by prullmann** [comment] 2022-07-08 11:25
> I'm wondering if I there would be a different way to change the docker daemon to point to a remote host.

@requiem240sx There is DOCKER_CONTEXT, but that also does not work.

**Comment by trcoelho** [comment] 2022-08-03 17:05
Hello, do we have any news regarding this one?

I still think this is a bug on compose v2.

Thank you.

**Comment by ulyssessouza** [comment] 2022-08-12 18:26
What happened here is that the variable was correctly loaded but not applied into docker `APIClient`.
So it would work for interpolation but not to drive the client.

A fix is on its way -> https://github.com/docker/compose/pull/9745

**Comment by trcoelho** [comment] 2022-08-15 13:43
Thanks @ulyssessouza !

**Comment by trcoelho** [comment] 2022-09-05 13:11
Hi @ulyssessouza , when this will be available?

Thank you!

**Comment by milas** [comment] 2022-09-06 14:22
Re-opening because we had to revert #9745 in #9792 because it caused issues with TLS-enabled Docker hosts.

As a result, this is not currently available in the latest release of Docker Compose.

**Closed** 2022-09-08 16:35 UTC
Labels: kind/feature

**Comment by milas** [comment] 2022-09-23 19:46
Upon further review, we’ve decided to not support dynamically setting `DOCKER_HOST` via `.env` files in Compose v2 (#9871).

Compose v2 is a Docker CLI plugin, and we want to ensure consistent behavior across all CLI plugins, which means using the "inherited" Docker API connection provided to the plugin, respecting all options, such as the [active context](https://docs.docker.com/engine/context/working-with-contexts/).

If you were relying on this functionality, I’d recommend taking a look at projects such as [direnv](https://direnv.net/), which can automatically set environment variables such as `DOCKER_HOST` or `DOCKER_CONTEXT` based on the current directory.

**Comment by trcoelho** [comment] 2022-09-26 13:37
Well, don't get it because we have that behavior on docker compose V1, which helps a lot when we have to manipulate several environments remotely.

Believe keep using V1 then :).

Thanks for the updates.

**Comment by prullmann** [comment] 2023-01-13 12:58
> Upon further review, we’ve decided to not support dynamically setting `DOCKER_HOST` via `.env` files in Compose v2 (#9871).

@milas Thanks for clarifying, sounds sensible so far.
But what mechanism should now be used when managing different environments (like staging vs production)?

You say that compose should not define the connection depending on its own configuration (eg `.env.staging` or `docker-compose-staging.yml`).
That suggests compose should choose its configuration depending on the connection it gets (eg `DOCKER_CONTEXT`).
Eg by using an `.env` file like this:
```
COMPOSE_FILE=docker-compose.yml:docker-compose.${DOCKER_CONTEXT}.yml
```

Is that the way to go or are there more clever ways?

**Comment by trcoelho** [comment] 2023-02-24 00:45
Hi @milas , as per docker documentation this environment variable should work on docker compose V2:

https://docs.docker.com/compose/environment-variables/envvars/

Is this correct?

If DOCKER_HOST is unavailable for compose V2, what should be the correct way to deploy in different servers?

Thanks in advance.

**Comment by hansaskov** [comment] 2024-10-21 19:45
I know this was closed a while ago, but i would just like to chime in and say that this feature would have been really appreciated.
