### ISSUE TITLE
Windows volume mapping works only from home directory

### ISSUE THREAD

**Issue by tooda02** [docker/compose#2548] opened 2015-12-15 13:11 UTC
In Windows, the [Getting Started example](https://docs.docker.com/compose/gettingstarted/) works correctly only if the working directory is under the user's home directory (C:\users\username).  Otherwise, it fails with the message:

```
python: can't open file 'app.py': [Errno 2] No such file or directory
```

which occurs because the /code directory is empty in the container.

The example Dockerfile is:

```
FROM python:2.7
ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt
CMD python app.py
```

and docker-compose.yml contains:

```
volumes:
  - .:/code
```

A standard Docker build produces a working container (that is, /code/app.py exists) regardless of the working directory.  However, `docker-compose up` creates a working image only if run from C:\users\username or one of its subdirectories.

**Comment by dnephin** [comment] 2015-12-15 15:17
Yes, this is because Docker Machine only mounts that one shared folder by default. There's nothing we can do about this in Compose.

**Comment by tooda02** [comment] 2015-12-15 15:40
@dnephin If I take docker-compose out of the picture by running:

    docker build -t web .
    docker run web

the container starts without error and I can exec a bash shell that shows the directory:

![image](https://cloud.githubusercontent.com/assets/11247671/11815089/fc399f88-a2fe-11e5-8b76-335e6655001a.png)

Note that the example above is running outside the home directory.  So there is something about the interface between docker-compose and docker-machine that's causing this error.

**Comment by dnephin** [comment] 2015-12-15 15:46
There is no volume in that example. Is you were to use `docker run -v $PWD:/code` you'd have the same problem.

You can remove the `volume: ...` from the compose file to get it working with compose as well.

**Comment by tooda02** [comment] 2015-12-15 15:50
Thanks!  You are correct - removing volume makes it work.   So I'd suggest that you update the [Getting Started](https://docs.docker.com/compose/gettingstarted/) example to eliminate the Volume specification (or at the least, include a warning about this problem).

**Comment by aanand** [comment] 2015-12-15 16:01
The volume config is important, as it lets you edit the code and see changes immediately, but we don't actually demonstrate that.

There was a suggestion long ago to add the volume config in a separate step after getting the app running, and demonstrating the benefits. I still think that'd be a good change, and you're right that we should also warn about mounting issues.

**Comment by mikkotikkanen** [comment] 2016-02-02 08:16
Separate step would be nice. That's what I ended up doing in a project that uses docker-compose for local dev environment, since not everyone has similar mountings but at least they can get the thing running immediately and if/when they need the live updates, they can see step n+1.

**Comment by tarach** [comment] 2016-02-16 06:58
So there is no way around it? I tried mounting manually directory on other partition:
```
docker-machine.exe stop default
VBoxManage.exe sharedfolder add default --name "d/projects" --hostpath "D:\projects"
VBoxManage.exe showvminfo default | grep -i share -A4
docker-machine.exe start default
docker-compose up -d
// did not work
docker run -it -v "//d/projects:/d/projects" nginx /bin/sh
// did work to some extent
```
Hoping docker-compose will pick up on that automatically. But not only he didn't but also docker machine did mount only like 1 directory in projects ( the directory with docker files and also not all of them )

There isn't a way to make it work?

**Comment by jennet** [comment] 2016-07-07 09:46
have you shared the drive containing the project directory in the docker settings? (see [shared drive section here](https://docs.docker.com/docker-for-windows/#docker-settings))

Once I'd done that I was able to run the Getting Started tutorial fine.

**Comment by vweevers** [comment] 2016-07-13 15:23
Here's a workaround for volumes outside of `C:\Users`. I'm on Win8.1, Docker Machine 0.7.0, no git bash. Add a shared folder and mount it inside the VM:

```
cd d:\my-project
vboxmanage sharedfolder add default --name my-project --hostpath "%cd%" --transient

docker-machine ssh default "sudo mkdir -p /d/my-project"
docker-machine ssh default "sudo mount -t vboxsf -o defaults,uid=`id -u docker`,gid=`id -g docker` my-project /d/my-project"

docker-compose up
```

Notes:

- Add `--readonly` to the `vboxmanage sharedfolder` command to create a read-only share
- If `vboxmanage` is not in your `PATH`, try `"%VBOX_MSI_INSTALL_PATH%\vboxmanage"`
- Replace `default` with `%DOCKER_MACHINE_NAME%` if necessary
- You have to do these steps for every project

**Comment by aanand** [comment] 2016-07-13 16:46
You might want to give the [Docker for Windows beta](https://www.docker.com/products/docker#/windows) a try - it uses a different approach for file syncing and doesn't have the `C:\Users` restriction.

**Comment by vweevers** [comment] 2016-07-15 10:58
Made a tool for it: [docker-share](https://github.com/vweevers/node-docker-share). Give it a spin, when Docker for Windows is not an option for you. In its simplest form, the workflow is:

```
docker-machine start
@FOR /f "tokens=*" %i IN ('docker-machine env') DO @%i

cd my-project
docker-share mount -t
docker-compose up
```

**Comment by wulftone** [comment] 2016-07-17 16:01
I'm also having this problem in Windows 10.  I'm running Docker for Windows (latest, 1.12.0-rc4-beta19) to no avail.  I can `ADD` files but I cannot mount volumes.  My project is in a subdirectory under `C:\Users\me\Whatever\DockerProject`.  Would love to see this resolved!

**Comment by klawhk** [comment] 2016-08-02 03:38
@wulftone I am using Windows 10 too. I executed "docker inspect" and found the volume was mounted but the error still came out.
Finally I resolved by going to settings and set set Shared Drives. I hope it can help!
![image](https://cloud.githubusercontent.com/assets/16603649/17316320/84234e56-58a5-11e6-8372-4db98067cea5.png)

**Comment by philicious** [comment] 2016-08-04 23:04
As I also still see these problems with devs using Windows, I came over https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/105 and it seems this still is a problem and only working for some users, for others it does work after fiddling around with firewall, security policies etc and for others it just doesnt work

**Comment by enjikaka** [comment] 2016-08-16 14:20
@klawhk Thank you. That solved it for me. :)

**Comment by philicious** [comment] 2016-08-16 14:24
oh a little update: for me the problems were because of a firewall integrated in AV (AntiVirus), so shut that OFF. Windows Firewall itself doesnt seem to cause problems tho.

**Comment by barrystaes** [comment] 2016-10-19 14:38
[The above workaround comment](https://github.com/docker/compose/issues/2548#issuecomment-232390294) by @vweevers works great. When in doubt use `docker inspect` to find the mounted folders. I just mounted the entire project folder and that works fine.

**Comment by ztwo79** [comment] 2016-10-20 01:51
thank you @vweevers , great tool.

**Comment by markl17** [comment] 2017-02-15 17:53
by me it still automounts c:\users even though it is says in shared drives c how does one convince it to share c:\

**Comment by Lampei** [comment] 2017-06-11 15:17
I think this issue could be much more simply resolved by some more error handling in the docker-compose up command. If there was a way to inform the user (I guess info vs error) that the volume mount in windows using docker toolbox did not work because folder xyz does not exist (and then display where docker-compose is looking) would solve 99% of the problem. I know that much of my time was spent thinking it was something with the container I was using rather than not using my c:\Users\ directory even after I read the documentation. If I had seen in the console log that the mounting was from c:\Users I probably would have worked forward from there...or even to update the shared folders in VirtualBox.

**Comment by rafaelsoaresbr** [comment] 2017-06-16 13:53
Anyway to share another drive using Docker Toolbox/Kitematic?

**Comment by markl17** [comment] 2017-06-16 14:43
In Windows to mount another drive is easy but to get c: to mount is impossible it only mounts c:\users\`name of the user`

**Comment by Lampei** [comment] 2017-06-16 14:47
Well, it's not *impossible* @markl17 :)  The way to do it via VirtualBox (as this is the way I handle it on my machine), is to stop your running VM if it's running, click on the "Shared Drive" tab, and then add a new link to your C:\ drive.  Now start up your VM again.  Then from here you have full access to your entire c drive rather than just sub folders in your C:\Users folder.  It even gets auto-named for you to C_DRIVE  Then you can use this in your yml file and add your volumes.

**Comment by marcospgp** [comment] 2017-07-18 01:24
@Lampei exactly, I spent hours debugging my docker files because of this. Since this was my first time using docker, I was pretty lost as to what I was doing wrong.

 I finally tried getting a boilerplate project running out of the box and realized it wasn't my fault when it didn't work.

 In an obscure corner of the internet, I found something about C:/users and tried moving the project folder to my desktop. Worked like a charm.

 Why is this problem so hidden? It would be so easy to have some error message when you tried to mount a path that was not found.

 Where did I go wrong in this? What resource should I be paying attention to that I missed, in order to be aware of this and avoid spending hours solving a nonexistent problem in my code?

**Comment by dotview** [comment] 2018-01-16 10:09
Perfect! Thank you @vweevers !

**Closed** 2018-01-25 00:57 UTC
Labels: group/windows-client

**Comment by tomahim** [comment] 2018-08-30 22:48
Just did this small bash script if it can help : 

````
#!/bin/bash
PROJECT_PATH=${PWD}
PROJECT_NAME=${PWD##*/}

sharedfolder_exists=`vboxmanage showvminfo default | grep "Name: '${PROJECT_NAME}'"`
if [[ -z $sharedfolder_exists ]]
then
    vboxmanage sharedfolder add default --name ${PROJECT_NAME} --hostpath ${PROJECT_PATH} --transient
    docker-machine ssh default "sudo mkdir -p ${PROJECT_PATH}"
    docker-machine ssh default "sudo mount -t vboxsf -o defaults,uid=`id -u`,gid=`id -g` ${PROJECT_NAME} ${PROJECT_PATH}"
else
    echo "INFO : Shared folder already set"
fi
docker-compose up
```

**Comment by marcospgp** [comment] 2018-10-07 13:48
I can't believe I posted here a year ago. Hello past me! It just took me another day to rediscover the problem you solved a year ago!

Why can't we just add an error message to docker compose or docker toolbox? Please?

@shin- Can you please reopen?

**Comment by shin-** [comment] 2018-10-08 07:58
There's no way for Compose to know which folders you've mounted, and it is the intended behavior for non-existing folders to be created by Docker, as highlighted here: https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior . Many users rely on that behavior persisting in future versions.

If you want to see an error when you mount an unknown folder, use the [long syntax (mount syntax)](https://docs.docker.com/compose/compose-file/compose-file-v2/#long-syntax) instead.

**Comment by marcospgp** [comment] 2018-10-08 08:02
@shin- I believe even a small "Folder "path/to/folder" not found, will be created by Docker" would help.

Doesn't compose read the `docker-compose.yml` file? What do you mean there is no way for it to know which folders you've mounted? 

Thanks for the quick feedback!!
