### ISSUE TITLE
--env-file option

### ISSUE THREAD

**Issue by nmaro** [docker/compose#6170] opened 2018-09-06 15:31 UTC
This option has been discussed in a [couple](https://github.com/docker/compose/issues/4841#issuecomment-345242740) of [tickets](https://github.com/docker/compose/issues/745) but never had a ticket for itself.

One should be able to execute 

`docker-compose up --env-file=.env.test` (perhaps multiple env files)

to override the usage of `.env` file.

**Comment by alancapc** [comment] 2018-09-06 15:33
Good idea, this one.

**Comment by shin-** [comment] 2018-09-06 20:18
Current plans for environment files are spelled out here: https://github.com/docker/compose/issues/745#issuecomment-346492587

While I'm not entirely excluding the possibility of an `--env-file` flag at some point in the future, I think we'd first want to see whether the mentioned changes alleviate the issues with the current model. But at this time, I don't think the added complexity is worth it.

**Comment by nmaro** [comment] 2018-09-07 11:48
From what I understand that solution doesn't really solve an other requirement (which I assume many have): having many docker-compose file in the same folder and being able to launch them using different .env files.

To bring a concrete example, I have a `docker-compose.yml` and a `docker-compose.test.yml`. The second is based on the first one. When developing I just want to use `docker-compose.yml` with my local unchecked .env file (development environment), but `docker-compose.test.yml` is run during CI and should use a checked .env.test file.

How would you deal with this scenario?

For reference:

docker-compose.yml
```
version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
```

```
version: '3'
services:
  mysql:
    container_name: ch.migros.reactions-api-test-mysql
  mockserver:
    image: jamesdbloom/mockserver
    ports:
      - '1080:1080'
      - '1090:1090'
  api:
    build: ./api
    env_file: ./api/.env.test
    command: ['start:integration']
    ports:
      - '4000:4000'
    depends_on:
      - 'mockserver'
      - 'mysql'
  test:
    build: ./test
    env_file: ./test/.env.test
    depends_on:
      - 'api'
```

**Comment by janhn** [comment] 2018-09-13 13:45
On a related note, the '.env' filename is really way too generic to have as a default.
Should be something like .docker-compose.env instead.

Where .env is used for different things, and without the ability to override it makes the whole environment variable mechanism unusable.

**Comment by codextremist** [comment] 2018-09-13 15:45
Am I missing something ? Is the --env-file option already valid? If it is not, the documentation says otherwise 
[https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers](https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers)

**Comment by nmaro** [comment] 2018-09-13 21:52
> Am I missing something ? Is the --env-file option already valid? If it is not, the documentation says otherwise
> https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers

No that's different. With `env_file` you pass variables to *containers*, but *not to the process that generates the containers*. For example it wouldn't be enough to put MYSQL_ROOT_PASSWORD in the example above via `env_file` because somehow it is needed at the time the container is created.

**Comment by pirate** [comment] 2018-09-13 22:08
To expand on what @nmaro is saying and provide a summary of the ticket status as I understand it, @codextremist what this issue is discussing is being able something like so:

project folder:
```
dev.env
beta.env
prod.env
docker-compose.yml
```
```bash
docker-compose up --env-file=dev.env
```

Which would pass some variables from `dev.env` into the context of the `docker-compose.yml` file, not directly to the containers.  
`docker-compose.yml` then defines which variables get passed down to containers and how, allowing only the settings needed for that specific image to be passed down e.g.:

```yml
version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     (passed in from dev.env or prod.env, etc)
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      ...
```

Right now only one `.env` file is allowed in the root of the project, which allows for defining settings separately from the docker-compose file, but it doesn't allow for having separate sets of settings for different environments (potentially risky if people put prod passwords by accident into dev environments).  With `--env-file`, people could explicitly require passing the environment file they want to run with, instead of implicitly looking for a `.env`.

I strongly support this proposal since this would make many people's beta/prod/dev setup easier given the ability to pass env files by command line :)  Current hacks involving symlinking .env to the env file you want to have active are error-prone and less clear and explicit than a CLI flag would be.

**Comment by nolazybits** [comment] 2018-09-26 21:55
@shin- just wondering what is the current status on the --env-file option.
I see it is part of the doc but I am wondering if one can specify multiple --env-file to have them aggregated. (as talk in other issues). Would you mind commenting please?

**Comment by shin-** [comment] 2018-09-26 22:07
@nolazybits Assuming you're talking about the `env_file` field inside the Compose file, since we don't have an `--env-file` flag in `docker-compose`:

Yes, you can specify multiple env files for a service and have them be combined. See the [documentation](https://docs.docker.com/v17.12/compose/compose-file/#env_file).

**Comment by meglio** [comment] 2018-11-10 07:37
I'm interested in using --env-file as well.

**Comment by vijayant123** [comment] 2018-11-20 08:53
Can we please have this essential feature? The --env-file CLI option would complement the docker compose's ability to replace ${ENV_VARIABLE} with the variable's value. This somehow is essential in our many use cases.
Regards,
Vijayant

**Comment by Wirone** [comment] 2018-12-02 17:12
@shin- is there possibility to load multiple env files ONLY for processing `docker-compose.yml` while starting project? In Symfony 4.2+ there is Ruby's behavior for common `.env` file with ability to override values with `.env.local`. The problem is, we want to make `docker-compose.yml` configurable per developer (Traefik host, database local port etc), so we can't use `.env` for it and if we do:

```
env_file:
  - .env
  - .env.local
```

the values will be populated into container and there won't be possibility to dynamically change application's behavior with environmental variables from `.env`/`.env.local` because they won't be loaded since `APP_ENV` will be already loaded.

So what I would like to do is loading env files only for creating environment, but without passing them to container.. Any suggestions?

**Comment by Wirone** [comment] 2018-12-03 07:45
Another case. I moved docker-related environment variables to `docker/docker.env` (ignored in Git) and changed `docker-compose.yml`:

```
version: '3.4'

services:
  # ...

  php:
    env_file: docker/docker.env
    user: "${RUN_AS_USER:?You must define user:group for permissions handling, look at README}"
    build:
      dockerfile: docker/Dockerfile
      target: php-dev
      context: .
```

Now, when running project, I get `ERROR: Missing mandatory value for "user" option in service "php": You must define user:group for permissions handling, look at README` even if `RUN_AS_USER` is set in `docker/docker.env`. When I remove `:?` part, I get `WARNING: The RUN_AS_USER variable is not set. Defaulting to a blank string.`.

I know I can run `export RUN_AS_USER=$UID` or `RUN_AS_USER=user docker-compose up -d --build` but it would be soooooo good if `docker-compose` could pre-populate environment variables used within `docker-compose.yml`.

**Comment by deepaksood619** [comment] 2018-12-17 20:18
What if we can have a direct key value in docker-compose which specifies which file to use for substituting values in docker-compose file.

Example -
```
version: '3.7'
services:
  service-1:
    substitute_env_file:
      - ${MACHINE_ENV}.env
```

So for every different machine `MACHINE_ENV` can be defined in topmost environment. For example, developer can define `MACHINE_ENV=dev` for his machine, `MACHINE_ENV=prod` for production, `MACHINE_ENV=staging` for staging and so on, on respective machines. And according we can have `dev.env`, `prod.env`, `staging.env`, all checked into version control and using a single command of `docker-compose up` will load all environments according to the respective machine.

The practical use case that I face daily is while deploying `kafka` cluster, where environment variable `KAFKA_ADVERTISED_LISTENERS` must be passed for each `kafka` broker, and it cannot be put in `.env` because there are multiple kafka brokers in same machine, which need different values for each broker (but environment variable cannot be changed). Now this cannot be used in `dev.env` and `prod.env` because of the same name of every broker environment variable.

**Comment by landsman** [comment] 2019-01-06 02:55
Guys, please, let's create way how load specific `.env` file for each `docker-compose.yml` file.

Now I have clean project with folder structure:
```
app
db
doc
docker
|--- /dev/
|--------- docker-compose.yml
|--- /prod/
|------ docker-compose.yml
|--- Dockerfile
prod.env
dev.env
start_dev.sh
build_prod.sh
start_prod.sh
README.md
.gitignore
```

And I need just pass variables to each environment. 
This functionality missing me here a lot! 🙏

**Comment by zignd** [comment] 2019-01-09 02:47
Please add the `--env-file` flag, for the sake of consistency with the `docker` command at least.

For now, for those looking for a work around, I'm using the [`env`](http://man7.org/linux/man-pages/man1/env.1.html) command, like this:

```shell
env $(cat .env.test) docker-compose up
```

**Comment by smcardle** [comment] 2019-01-20 21:18
My preference would also be for the --env-file option.

I have a use case where this would be great i.e. deploying alfresco into containers.

Alfresco uses a properties file of its own to configure the services called alfresco-global.properties. This is just a PROP=VAL file the same format as the .env file.

It would be great to use this same global.properties file to also enable the configuration for docker-compose rather than having multiple files with repeated properties for both the compose setup and the service setup.

Steve

**Comment by coltenkrauter** [comment] 2019-01-29 17:06
My preference would also be for the --env-file option.

**Comment by ianfixes** [comment] 2019-02-08 18:35
> Please add the `--env-file` flag, for the sake of consistency with the `docker` command at least.

I agree

**Comment by Toilal** [comment] 2019-02-19 08:22
Other more specific filenames should be also read by default to avoid collisions with other tools parsing `.env` file ([symfony/dotenv](https://github.com/symfony/dotenv), [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv)), maybe `docker-compose.env` and `.docker-compose.env`.

**Comment by Toilal** [comment] 2019-02-19 08:27
And why not adding `COMPOSE_ENV_FILE` environnement variable to this list : https://docs.docker.com/compose/reference/envvars/ ?

**Closed** 2019-02-26 15:38 UTC
Labels: area/cli, kind/feature, kind/question

**Comment by Wirone** [comment] 2019-02-26 18:01
AFAIS #6535 does not cover all use cases mentioned here. It brings basic functionality of overriding default env file which is loaded during build. If I'm correct, it doesn't allow specifying multiple env files to be loaded, which was described [above](https://github.com/docker/compose/issues/6170#issuecomment-443523663) in the example where `env_file` option inside `docker-compose.yml` was used.

Am I correct?

**Comment by gtirloni** [comment] 2019-05-14 19:46
A generic way to solve this is to implement something like [kustomize](https://kustomize.io/) but for Docker, then users are free to patch their YAML files as they please.

I also came here looking for a way to specify an env file for different environments and I think the workaround seems to be duplicating my docker-compose.yml files in an ugly way.

**Comment by markusait** [comment] 2019-05-21 21:51
Is it possible to also load env variables from a .yaml file. Like this node [library](https://github.com/jeffijoe/yenv) does?

**Comment by Elyytscha** [comment] 2019-07-22 15:27
just saying i'm doing this via systemd:

```
[Unit]
Description=docker-compose
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
StandardError=null
StandardOutput=null

Environment=ENVIRONMENT=test.env
EnvironmentFile=/usr/local/src/sonarqube/test.env

# pull images
ExecStartPre=/usr/bin/docker-compose -f /usr/local/src/sonarqube/docker-compose.yml pull

# Compose up
ExecStart=/usr/bin/docker-compose -f  /usr/local/src/sonarqube/docker-compose.yml up -d

# Compose down, remove containers and volumes
ExecStop=/usr/bin/docker-compose -f /usr/local/src/sonarqube/docker-compose.yml stop

[Install]
WantedBy=multi-user.target
```

compose:
```
services:
  sonarqube:
    image: docker.registry.at/sonarqube:${SONARQUBE_VERSION:-latest}
    ports:
      - "${SONARQUBE_PORT:-9000}:9000"
    env_file: ${ENVIRONMENT:-local.env}
```

which was the only way i found to use the env vars from a file directly in the compose file while executing it (i dont like the .env file, i want multiple env files named by my convention for multiple environments)

**Comment by StuartHadfield** [comment] 2019-07-31 13:47
Worth noting: 

You will no longer be able to accomplish the OP's request - `docker-compose up --env-file=path/to/file.env` as a result of https://github.com/docker/compose/pull/6800 - which makes the `--env-file` arg a toplevel argument. 

Not sure if this should be reopened as a result - the original issue is not resolved? @slowr, what do you think?

**Comment by dnk8n** [comment] 2019-08-15 09:30
If this is closed, where is the open issue in the backlog? Or is this not even being considered at all?

**Comment by laertis** [comment] 2019-08-20 12:46
> And why not adding `COMPOSE_ENV_FILE` environnement variable to this list : https://docs.docker.com/compose/reference/envvars/ ? It seems to be really related to `COMPOSE_FILE` environnement variable.

That's actually a great idea although although you'd have to somehow the cyclic dependency when someone set `COMPOSE_ENV_FILE` inside the `.env` file as it is commonly done for `COMPOSE_FILE`

**Comment by jkoorts** [comment] 2019-09-19 13:52
Hi please add this feature. For a workaround I have to write scripts to feed it the right .env file for my many environments. If docker has is why not docker-compose too? does the reasoning for creating it for docker not apply for docker compose? and if not why not?.

Saying "its not worth the effort" is a bad argument since then I have to ask why was the effort worth it for docker?

**Comment by namgivu** [comment] 2019-12-10 10:46
> Please add the `--env-file` flag, for the sake of consistency with the `docker` command at least.
> 
> For now, for those looking for a workaround, I'm using the [`env`](http://man7.org/linux/man-pages/man1/env.1.html) command, like this:
> 
> ```shell
> env $(cat .env.test) docker-compose up
> ```

This is my charm and working. Thank you!

**Comment by yairmark** [comment] 2020-01-20 14:45
> Please add the `--env-file` flag, for the sake of consistency with the `docker` command at least.
> 
> For now, for those looking for a workaround, I'm using the [`env`](http://man7.org/linux/man-pages/man1/env.1.html) command, like this:
> 
> ```shell
> env $(cat .env.test) docker-compose up
> ```

To resolve the error `env: #The: No such file or directory` which is caused by env files with comments in change the above to:

```shell
env $(cat .env.test | grep "#" -v) docker-compose up
```

**Comment by Elyytscha** [comment] 2020-01-22 08:32
> > Please add the `--env-file` flag, for the sake of consistency with the `docker` command at least.
> > For now, for those looking for a workaround, I'm using the [`env`](http://man7.org/linux/man-pages/man1/env.1.html) command, like this:
> > ```shell
> > env $(cat .env.test) docker-compose up
> > ```
> 
> To resolve the error `env: #The: No such file or directory` which is caused by env files with comments in change the above to:
> 
> ```shell
> env $(cat .env.test | grep "#" -v) docker-compose up
> ```

just saying that all of those solutions with env in front are breaking auto-completion of docker-compose which i dont wanna miss

**Comment by json2d** [comment] 2020-02-08 03:14
> > > Please add the `--env-file` flag, for the sake of consistency with the `docker` command at least.
> > > For now, for those looking for a workaround, I'm using the [`env`](http://man7.org/linux/man-pages/man1/env.1.html) command, like this:
> > > ```shell
> > > env $(cat .env.test) docker-compose up
> > > ```
> > 
> > 
> > To resolve the error `env: #The: No such file or directory` which is caused by env files with comments in change the above to:
> > ```shell
> > env $(cat .env.test | grep "#" -v) docker-compose up
> > ```
> 
> just saying that all of those solutions with env in front are breaking auto-completion of docker-compose which i dont wanna miss

i think lets just make a VSCode extension to do this for us and call it a day

**Comment by JustinGrote** [comment] 2020-02-17 01:10
This is my workaround that I put in my .bashrc:
```bash
export COMPOSE_HOME=/home/jgrote/docker
alias dc="env PWD=$COMPOSE_HOME $(cat $COMPOSE_HOME/.env | grep -v '#' | tr '\n' ' ') docker-compose"
alias dcup="dc up -d"
complete -F _docker_compose dc
```

I can use dc for my special one, and then docker-compose if I need to use a non-special one. 

@Elyytscha this doesn't break autocompletion :)

**Comment by zignd** [comment] 2020-02-17 02:50
The feature has been implemented already https://github.com/docker/compose/pull/6535

**Comment by adamerose** [comment] 2020-06-10 11:51
> The feature has been implemented already #6535

Has it been included in a release yet or is there a roadmap for when it will be? This still doesn't work for me and I don't see it anywhere in the docs, it's not listed here: https://docs.docker.com/compose/reference/up/

**Comment by Loki-Afro** [comment] 2020-07-06 14:17
@adamerose 
works for me
```
pwirth@frenzy ~ % docker-compose --version
docker-compose version 1.25.4, build unknown
```

**Comment by MexsonFernandes** [comment] 2020-08-06 17:44
This works for me.

`
docker-compose --env-file .env up --build -d
`

Docker compose version is 1.26.2

**Comment by iraklisg** [comment] 2020-08-14 06:36
Is `--env-file` option available only with `docker-compose up` command? Because the command `docker-compose run --env-file .env.test ...` is not executed :confused: 

Docker Compose version 1.26.2

**Comment by MexsonFernandes** [comment] 2020-08-14 06:49
@iraklisg Check out this link https://docs.docker.com/compose/environment-variables/.

**Comment by bmarkovic** [comment] 2020-08-25 12:26
@MexsonFernandes the link doesn't mention `--env-file` for the `docker-compose` binary, which is what the discussion is about, given the merged PR.

Furthermore, pointing people to documentation in issues is rude, especially without an in-page anchor, and especially since few posts above the matter of documentation being outdated was raised. It's rude for two reasons. First, documentation changes over time and there is no guarantee that the information you saw will be there when someone else follows the link, and second, it's implies on your part an assumption that someone was either stupid or lazy as to not check relevant documentation before seeking answers in a Github issue.

**Comment by MexsonFernandes** [comment] 2020-08-25 13:24
> @MexsonFernandes the link doesn't mention `--env-file` for the `docker-compose` binary, which is what the discussion is about, given the merged PR.
> 
> Furthermore, pointing people to documentation in issues is rude, especially without an in-page anchor, and especially since few posts above the matter of documentation being outdated was raised. It's rude for two reasons. First, documentation changes over time and there is no guarantee that the information you saw will be there when someone else follows the link, and second, it's implies on your part an assumption that someone was either stupid or lazy as to not check relevant documentation before seeking answers in a Github issue.

@bmarkovic my bad. I will make sure to read off and mention proper links out here. 👍🏼

**Comment by dmitry-kulikov** [comment] 2020-10-16 12:13
`--env-file` was added with version 1.25.0, it is not mentioned in CHANGELOG.md.

**Comment by fbergen** [comment] 2020-12-01 23:30
> What if we can have a direct key value in docker-compose which specifies which file to use for substituting values in docker-compose file.
> 
> Example -
> 
> ```
> version: '3.7'
> services:
>   service-1:
>     substitute_env_file:
>       - ${MACHINE_ENV}.env
> ```
> 
> So for every different machine `MACHINE_ENV` can be defined in topmost environment. For example, developer can define `MACHINE_ENV=dev` for his machine, `MACHINE_ENV=prod` for production, `MACHINE_ENV=staging` for staging and so on, on respective machines. And according we can have `dev.env`, `prod.env`, `staging.env`, all checked into version control and using a single command of `docker-compose up` will load all environments according to the respective machine.
> 
> The practical use case that I face daily is while deploying `kafka` cluster, where environment variable `KAFKA_ADVERTISED_LISTENERS` must be passed for each `kafka` broker, and it cannot be put in `.env` because there are multiple kafka brokers in same machine, which need different values for each broker (but environment variable cannot be changed). Now this cannot be used in `dev.env` and `prod.env` because of the same name of every broker environment variable.

Running a similar version below, thought I'd mention:

```
docker-compose.yml

services:
  web:
     env_file: ${ENV_FILE}
```
and then only add one ENV_FILE var when running 
```shell
ENV_FILE=.env.test docker-compose run web
```

**Comment by Mugane** [comment] 2021-05-11 22:36
This looks like a popular request and a glaring omission from the docker-compose workflow, with no solution presented. 

Can someone explain why is this issue has been closed???

**Comment by daghsentinel** [comment] 2021-12-09 12:11
> This looks like a popular request and a glaring omission from the docker-compose workflow, with no solution presented.
> 
> Can someone explain why is this issue has been closed???

Looks like it has been resolved.
https://github.com/docker/compose/issues/6170#issuecomment-710008693
