### ISSUE TITLE
Compose 1.3 has disabled TTY in some cases

### ISSUE THREAD

**Issue by aidanlister** [docker/compose#1604] opened 2015-06-26 02:12 UTC
We used to be able to run something like:
    `docker-compose -p aesg run web python manage.py test --keepdb abas.apps.properties`

And whenever there was a import pdb; pdb.set_trace() it would drop to console .. now it doesn't.

OSError: [Errno 32] Broken pipe

**Comment by aidanlister** [comment] 2015-06-26 03:22
Cancel that ... it's all cases.

```docker-compose -p foo run web bash``` gives OSError: [Errno 32] Broken pipe

**Comment by aidanlister** [comment] 2015-06-26 03:23
```
docker-compose version: 1.3.1
CPython version: 2.7.6
OpenSSL version: OpenSSL 0.9.8zd 8 Jan 2015
```

**Comment by aidanlister** [comment] 2015-06-26 03:25
```pip uninstall ndg-httpsclient``` fixes the issue

**Comment by timmygee** [comment] 2015-06-26 05:08
This also happened to me. Seems at the moment we have the choice between the InsecurePlatformWarning on startup or TTY access

**Comment by aanand** [comment] 2015-06-26 20:11
You've installed via Pip, yes? What happens if you use the binary?

**Comment by appden** [comment] 2015-06-26 22:20
This is somewhat a duplicate of #1509. Thanks @aidanlister for the quick fix!

**Comment by edwinlunando** [comment] 2015-06-29 03:05
Is this solved? How about the main binary?

**Comment by aidanlister** [comment] 2015-06-29 03:15
It's not solved but it's also primarily a documentation bug - need to explicitly say not use use the ndg library and provide an alternative to get rid of the warnings

**Comment by voidlily** [comment] 2015-10-22 23:34
I ran into this issue today and found I had the same problem that `ndg-httpsclient` was installed. Like @aidanlister , uninstalling that package fixed it for me as well.

**Comment by justinanastos** [comment] 2016-04-15 17:30
I am still struggling with this issue. Where exactly would I find `ndg-httpsclient` installed?

**Comment by shin-** [comment] 2017-03-08 23:47
Closing as a duplicate of #1509

**Closed by shin-** 2017-03-08 23:47 UTC
Labels: area/run, kind/docs
