### ISSUE TITLE
Can't use linked resource with log driver

### ISSUE THREAD

**Issue by chiefy** [docker/compose#2657] opened 2016-01-14 16:56 UTC
I'm not sure if this is possible, but I was trying to do something like the following:

```
app:
  image: nginx
  ports: 
    - "80:80"
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://logstash:12201"
  links:
    - logstash

logstash:
  image: logstash
  expose:
    - "12201/udp"  
```

Currently this won't work, I assume because the log driver tries to initialize before any linking is done?

**Comment by dnephin** [comment] 2016-01-14 17:05
Correct, it doesn't work because the log driver urls needs to be accessible by the daemon, not by the container. The `logstash` alias is never provided to the daemon. With the upcoming changes to how DNS works in docker 1.10 there might be some way to get this to work, I'm not sure.

This is a duplicate of #2182, however I think the description does a better job of demonstrating the problem, so maybe we should keep this one and close the other.

**Comment by chiefy** [comment] 2016-01-14 17:16
thanks @dnephin I figured as much after I kept getting DNS errors.

**Comment by dnephin** [comment] 2016-02-01 21:55
@mavenugo, @mrjana, @dave-tucker

Now that docker 1.10 is using an embedded DNS server, is there any way that the daemon could query that DNS server itself to support this use-case?

**Comment by dnephin** [comment] 2016-02-12 19:52
ping @mavenugo again.  This seems to be a common request/issue (just had another question about it in IRC).

Is there any way the engine can use a name like `service.network` to access this service?

**Comment by lucj** [comment] 2016-02-16 10:14
Hi, do you have any update on that one ?

**Comment by dave-tucker** [comment] 2016-02-16 10:49
@dnephin I believe it's technically possible, but it's not a planned feature AFAIK.

What's the use case for running an instance of a log server per application?
As a workaround, you can use `--net=host`, for example:

```
app:
  image: nginx
  ports: 
    - "80:80"
  log_driver: "gelf"
  log_opt:
    gelf-address: "udp://localhost:12201"

logstash:
  image: logstash
  net: host
  expose:
    - "12201/udp"  
```

In the v2 format, you can even use `depends_on` to make sure that the `logstash` container is started first.

**Comment by lucj** [comment] 2016-02-16 11:20
Hi @dave-tucker thanks for the update.

I'd like to have a single compose file that gathers all the services of my application:
- api
- db
- www
- reverse-proxy
- ...

and also the services used by the app:
- elk stack
- ...

Each application's service (db, api, www, ...) should send their logs to the elk stack.
Does that make sense ?

**Comment by dnephin** [comment] 2016-02-16 17:08
@dave-tucker creating a completely isolated environment is one of the primary use cases of Compose. This is especially useful for reliable end-to-end testing.

Using the host is one workaround, but would fail on any shorted host (like a jenkins CI server), so it's something I often try to avoid.

@lucj you may need to open an issue on libnetwork or docker/docker to get the feature supported.

**Comment by dnephin** [comment] 2016-02-18 16:27
Sorry, that should have been "shared host". If you use `network_mode: host`  you can only have one thing listening on each port on the host, so trying to run two copies of it would fail.

**Comment by lucj** [comment] 2016-02-18 21:18
When I test with network_mode: host, I do not manage to have it working though.
My logstash service needs to have a link towards elasticsearch service (another service of the compose file). But this link is not compatible with the network_mode:

    ERROR: Conflicting options: host type networking can't be used with links. This would result in undefined behavior
      
The part of the compose file is:

      ...
      logstash:
        image: 'myrep/logstash:latest'
        command: 'logstash -f /etc/logstash/conf.d/logstash.conf'
        network_mode: host
        links:
          - elasticsearch
        depends_on:
          - elasticsearch
        expose:
          - '5514'
        restart: on-failure
      logspout:
        image: 'myrep/logspout:latest'
        command: '-c ''/bin/logspout syslog://localhost:5514'''
        entrypoint: /bin/sh
        depends_on:
          - logstash
        restart: always
        volumes:
          - '/var/run/docker.sock:/tmp/docker.sock'

Any idea of what is wrong ?

**Comment by StanSvec** [comment] 2016-08-02 01:17
Is there any other option than using logspout? For example if network_mode host is used for logstash then is there still any way how to make elasticsearch service accessible for logstash?

**Closed** 2019-03-27 17:50 UTC
Labels: area/logs, kind/question
