### ISSUE TITLE
[BUG] Docker Compose does not remove orphan containers

### ISSUE THREAD

**Issue by serious-angel** [docker/compose#12314] opened 2024-11-22 12:20 UTC
### Description

Greetings!

Thank you very much for the ineffably marvelous art, dear Community and Developers...

---

Is it possible that Docker Compose does not remove orphan containers if a custom Compose file is specified?

Compose shows the following warning despite the option `--remove-orphans` used:

```
WARN[0000] Found orphan containers ([project-nginx-run-d7bcc8a25373]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
```

Additionally, with each run, a new container gets created.

## Possible Workaround

Execute a general [Container Prune](<https://docs.docker.com/reference/cli/docker/container/prune/>) prior each Compose `run` execution stated in the case "Steps To Reproduce" steps below.

```
$ docker container prune -f;
```

---

What might it be? Is it an expected behavior? If so, what could be a more 

Best and kind regards ✨ 

### Steps To Reproduce

Let's suppose we are in directory `/opt/` and the Compose file is located at `/opt/project/dev.compose.yaml`:

```yaml
services:
  nginx:
    image: 'nginx'
```

Let's try running a wonderful container!

```bash
$ docker compose -f './project/dev.compose.yaml' run --remove-orphans -- nginx;
# Ctrl+D

$ docker compose -f './project/dev.compose.yaml' run --remove-orphans -- nginx;
# WARN[0000] Found orphan containers ([project-nginx-run-d7bcc8a25373]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
# Ctrl+D

$ docker compose -f './project/dev.compose.yaml' run --remove-orphans -- nginx;
# WARN[0000] Found orphan containers ([project-nginx-run-d7bcc8a25373 project-nginx-run-624045adb1bf]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
```

As we may see, orphan containers get accumulated.

### Compose Version

```Text
Docker Compose version v2.29.7
```

### Docker Environment

```Text
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-49-generic
 Operating System: KDE neon 6.2
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 31.27GiB
 Name: pc
 ID: DSWT:QYCK:SROK:2VOG:TMFT:IP4U:CIQI:TLJK:VING:MQE7:NOH4:D36Y
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: artworks
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Anything else?

Relative issues seem to be raised. For instance: https://github.com/docker/compose/issues/9718

**Comment by idsulik** [comment] 2024-11-22 19:26
Reproduced it using `Docker Compose version v2.30.3-desktop.1`, but couldn't reproduce it using the `main` branch code, so looks like it was fixed

**Comment by ndeloof** [comment] 2024-11-25 07:22
fixed by https://github.com/docker/compose/commit/bf521fe3ab66146b3c1dfc038de82bd9a3521971

**Closed by ndeloof** 2024-11-25 07:22 UTC
Labels: kind/bug, status/0-triage

**Comment by spardorp** [comment] 2025-01-11 18:47
i think this may do the job too.

when all used containers are running, the not running containers can be pruned.

> docker container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y
Deleted Containers:
fbd84bb5d7a5fc81c5a7dd7760091d4ed4db6a31e235140dca64cdbb613921b8
51e938ee441e76c20bd4c450650dd3a8e2034d33f731844bfd599ed11c4dc66e

Total reclaimed space: 79.03kB
