### ISSUE TITLE
[BUG] Segfault during buildx initialization if no builder available

### ISSUE THREAD

**Issue by rgeorgiev583** [docker/compose#10453] opened 2023-04-10 10:25 UTC
### Description

`docker compose build` crashes with a SIGSEGV and outputs the following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x39 pc=0x55ed3ede35a9]

goroutine 45 [running]:
github.com/docker/buildx/builder.(*Builder).Validate(0x55ed404b53a0?)
        github.com/docker/buildx@v0.10.4/builder/builder.go:111 +0x29
github.com/docker/buildx/builder.New({0x55ed404b53a0?, 0xc000414600}, {0x0, 0x0, 0x55ed3e1f6dc7?})
        github.com/docker/buildx@v0.10.4/builder/builder.go:101 +0x27f
github.com/docker/compose/v2/pkg/compose.(*composeService).doBuildBuildkit(0xc000302640, {0x55ed404a49e0, 0xc000606200}, 0x0?, {0x55ed3f7e0ff0, 0x4})
        github.com/docker/compose/v2/pkg/compose/build_buildkit.go:36 +0x9b
github.com/docker/compose/v2/pkg/compose.(*composeService).build.func1({0x55ed404a49e0, 0xc000606200}, {0xc00036c268, 0x4})
        github.com/docker/compose/v2/pkg/compose/build.go:97 +0x6c5
github.com/docker/compose/v2/pkg/compose.(*graphTraversal).run.func1()
        github.com/docker/compose/v2/pkg/compose/dependencies.go:127 +0x63
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

I tried to run `docker build .` separately, and it seems to create the image successfully:
```
Sending build context to Docker daemon  4.096kB
Step 1/1 : FROM alpine
 ---> 9ed4aefc74f6
Successfully built 9ed4aefc74f6
```

### Steps To Reproduce

I tested using a minimal example config for building of an image through Compose.  You can find it in `compose-build.zip`.  Just extract the files into a directory and run `docker-compose build` to reproduce the bug.
[compose-build.zip](https://github.com/docker/compose/files/11189843/compose-build.zip)

### Compose Version

```Text
Docker Compose version 2.17.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., 2.17.2)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 20.10.23-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: local
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc version: v1.1.5-0-gf19387a6bec4
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 6.2.9-1-default
 Operating System: openSUSE Tumbleweed
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.65GiB
 Name: rgeorgiev-elitebook
 ID: 6YAH:223S:VX5Z:TZHA:S55P:ICJJ:EWC2:YGV2:N3CJ:QKBC:6T34:XVEY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by milas** [comment] 2023-04-11 16:02
The failure here is initializing buildx. There's a bug in the error handling I'll look at fixing, but something has already failed by the time it's panicing.

Do you have any sort of custom builder configuration? What do `docker buildx ls` / `docker buildx inspect` return?

**Comment by UshakovMaksym** [comment] 2023-04-13 10:49
```
$ docker buildx inspect
docker: 'buildx' is not a docker command.
See 'docker --help'
```

```
$ docker -v
Docker version 23.0.3, build 3e7cbfd
```

**Comment by milas** [comment] 2023-04-13 20:31
@UshakovMaksym If you install buildx (https://docs.docker.com/go/buildx/), does the error go away?

**Comment by crazy-max** [comment] 2023-04-13 21:06
I'm not able to repro even without buildx and removing the buildx store:

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-14-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.936GiB
 Name: docker-test
 ID: 6PMT:VW3X:6G6E:5SFU:X5QN:AV7W:5GPX:QUVX:JLUA:P2GK:J2YA:2LT5
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 162
  Goroutines: 304
  System Time: 2023-04-13T22:51:50.535102537+02:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.16.0.0/16, Size: 24
```

```
$ docker context ls
NAME        DESCRIPTION                               DOCKER ENDPOINT               ERROR
default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
```

```
$ sudo apt-get remove docker-buildx-plugin
$ rm -rf ~/.docker/buildx
```

```
$ docker compose build
[+] Building 3.8s (6/6) FINISHED                                                                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                                                                     0.1s
 => => transferring dockerfile: 2.92kB                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                        0.1s
 => => transferring context: 45B                                                                                                                                                                         0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                                                                                               1.4s
 => docker-image://docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                                                                                 1.0s
 => => resolve docker.io/docker/dockerfile:1@sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14                                                                                     0.0s
 => => sha256:39b85bbfa7536a5feceb7372a0817649ecb2724562a38360f4d6a7782a409b14 8.40kB / 8.40kB                                                                                                           0.0s
 => => sha256:966d40f9ba8366e74c2fa353fc0bc7bbc167d2a0f3ad2420db8b9e633049462d 482B / 482B                                                                                                               0.0s
 => => sha256:dbdd11720762ad504260c66161c964e59eba06b95a7aa64a68634b598a830a91 2.90kB / 2.90kB                                                                                                           0.0s
 => => sha256:a47ff7046597eea0123ea02817165350e3680f75000dc5d69c9a310258e1bedd 11.55MB / 11.55MB                                                                                                         0.5s
 => => extracting sha256:a47ff7046597eea0123ea02817165350e3680f75000dc5d69c9a310258e1bedd                                                                                                                0.4s
 => CANCELED [internal] load metadata for docker.io/tonistiigi/xx:1.1.2                                                                                                                                  0.8s
 => CANCELED [internal] load metadata for docker.io/library/golang:1.20-alpine                                                                                                                           1.2s
canceled
```

As expected when creating a new builder instance in https://github.com/docker/compose/blob/af6f0ffb9e992502bad030d5c773f523ebd3ebc5/pkg/compose/build_buildkit.go#L36, the store is init:

```
$ tree -nh ~/.docker/buildx
/home/user/.docker/buildx
├── [4.0K]  activity
├── [  62]  current
├── [4.0K]  defaults
└── [4.0K]  instances

3 directories, 1 file
```

And `default` context is the current instance as expected as well:

```
$ jq . ~/.docker/buildx/current
{
  "Key": "unix:///var/run/docker.sock",
  "Name": "",
  "Global": false
}
```

@UshakovMaksym @rgeorgiev583 Can you give me the output of the following commands please:

* `tree -nh ~/.docker/buildx`
* `jq . ~/.docker/buildx/current`

@UshakovMaksym What's the output of `docker info`?

**Comment by UshakovMaksym** [comment] 2023-04-14 14:29
> @UshakovMaksym If you install buildx (https://docs.docker.com/go/buildx/), does the error go away?

i use docker in wsl without docker desktop
```
$ docker info
Client:
 Context:    wsl
 Debug Mode: false

Server:
 Containers: 5
  Running: 2
  Paused: 0
  Stopped: 3
 Images: 14
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.829GiB
 Name: MAKS
 ID: c6801e70-9903-436d-aaed-a76fba215054
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://127.0.0.1:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: No io.weight support
WARNING: No io.weight (per device) support
WARNING: No io.max (rbps) support
WARNING: No io.max (wbps) support
WARNING: No io.max (riops) support
WARNING: No io.max (wiops) support
```

**Comment by alex-konkov** [comment] 2023-04-20 08:58
Having this error when running docker-compose build in Intellij Idea. And strangely, the same command in terminal works fine. Maybe this would help you to troubleshoot.

**Comment by ndeloof** [comment] 2023-05-12 13:07
I'm not sure about the root cause for this, but with https://github.com/docker/buildx/pull/1732 being merged, we just need to wait for next buildx release to update compose codebase and get a proper error reported to user.

**Comment by qdm12** [comment] 2023-05-18 19:09
I tried to build buildx locally to verify this gets fixed (and also since it's blocking me for WSL dev containers), but I'm failing to build from master, a bit of help would be appreciated:

```sh
git clone https://github.com/docker/buildx.git .
go build -o ~/.docker/cli-plugins/buildx ./cmd/buildx/
# github.com/moby/buildkit/frontend/gateway/client
vendor/github.com/moby/buildkit/frontend/gateway/client/client.go:18:29: Reference does not implement comparable
note: module requires Go 1.20
```

🤔 Thanks!

**Comment by qdm12** [comment] 2023-05-18 19:22
Sorry for the 2nd notification; I did

```sh
$ git clone https://github.com/docker/buildx.git .
$ go build -o ~/.docker/cli-plugins/docker-buildx ./cmd/buildx
$ docker buildx version
github.com/docker/buildx v0.0.0+unknown
```

So this should be the right binary built from master, the error is still

```
[2023-05-18T18:54:09.898Z] panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x39 pc=0x1022e69]

goroutine 31 [running]:
github.com/docker/buildx/builder.(*Builder).Validate(0x22d3d80?)
	github.com/docker/buildx@v0.10.4/builder/builder.go:111 +0x29
github.com/docker/buildx/builder.New({0x22d3d80?, 0xc000418500}, {0x0, 0x0, 0x0?})
	github.com/docker/buildx@v0.10.4/builder/builder.go:101 +0x27f
github.com/docker/compose/v2/pkg/compose.(*composeService).doBuildBuildkit(_, {_, _}, {_, _}, {{{0xc00053f7a0, 0x26}
[2023-05-18T18:54:09.898Z] , {0xc000066d80, 0x5d}, {0x0, ...}, ...}, ...}, ...)
	github.com/docker/compose/v2/pkg/compose/build_buildkit.go:39 +0x72
github.com/docker/compose/v2/pkg/compose.(*composeService).build.func1({0x22c2c80, 0xc000266320}, {0xc0002478b0, 0x6})
	github.com/docker/compose/v2/pkg/compose/build.go:115 +0x6fe
github.com/docker/compose/v2/pkg/compose.(*graphTraversal).run.func1()
	github.com/docker/compose/v2/pkg/compose/dependencies.go:145 +0x59
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.2.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.2.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by ndeloof** [comment] 2023-05-20 06:29
Buildx is integrated in docker compose as a vendored library. To get this fix, you will need to bump buildx dependency in docker/compose repo and build compose

**Comment by ndeloof** [comment] 2024-10-11 12:07
I'm closing this issue as obsolete, with no activity for > 1 year
If issue is still relevant, please comment or create a follow-up issue

**Closed by ndeloof** 2024-10-11 12:07 UTC
Labels: kind/bug, area/build
