### ISSUE TITLE
Missing paramiko library breaks ssh connections when using "DOCKER_HOST=ssh://…"

### ISSUE THREAD

**Issue by rmoriz** [docker/compose#6428] opened 2018-12-23 20:33 UTC
## Description of the issue

paramiko python package is missing in the latest compose release (and also in the latest docker for mac edge):

### Expected:

```shell
# export DOCKER_HOST=ssh://user@remote-docker-host
# docker-compose ps
Name   Command   State   Ports
------------------------------
…
```

### Actual behavior

```shell
# export DOCKER_HOST=ssh://user@remote-docker-host
# docker-compose ps
Traceback (most recent call last):
  File "site-packages/docker/api/client.py", line 151, in __init__
NameError: name 'SSHAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/command.py", line 42, in project_from_options
  File "compose/cli/command.py", line 123, in get_project
  File "compose/cli/command.py", line 94, in get_client
  File "compose/cli/docker_client.py", line 127, in docker_client
  File "site-packages/docker/api/client.py", line 156, in __init__
docker.errors.DockerException: Install paramiko package to enable ssh:// support
[79659] Failed to execute script docker-compose

```

## Additional information

OS version / distribution, `docker-compose` install method, etc.

Tested and failing with:

````
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

… using release binary from github and `/Applications/Docker.app/Contents/Resources/bin/docker-compose` as part of the current Docker for Mac edge release (Version 2.0.0.0-mac82 (29268))

**Comment by rmoriz** [comment] 2018-12-23 20:36
seems like https://github.com/docker/compose/commit/6e697c3b978b5515636135384cec1ece3d7067ef already addresses the issue but the fix is not included in a release yet

**Comment by rmoriz** [comment] 2018-12-23 21:00
Workaround is just to stick with the existing tools (openssh) for socker-forwarding:

```shell

# setup
ssh -nNT -L /tmp/socket.remote:/var/run/docker.sock user@remote.example.com &
export TUNNEL_PID=$!
export DOCKER_HOST=unix:///tmp/socket.remote

# use docker, docker-compose here
docker-compose…


# shutdown and cleanup of the socket
kill $TUNNEL_PID
rm -f /tmp/socket.remote
```

**Comment by shin-** [comment] 2018-12-24 03:40
Duplicate of #6336

**Closed by shin-** 2018-12-24 03:40 UTC

**Comment by rmoriz** [comment] 2018-12-24 03:47
Shoot! I searched for "paramiko" :)
