### ISSUE TITLE
Add docker-compose logs -f for tailing log output

### ISSUE THREAD

**Issue by richardjortega** [docker/compose#1877] opened 2015-08-17 05:51 UTC
Wondering if it's possible to update the `docker-compose logs` endpoint to use a `-f` for following log output. 

Right now if you type `docker-compose logs` you have to wait for the logs to catch up. Depending on your app, this can take an extremely long time to catch up (typically in development or staging I have to run `docker-compose kill && docker-compose up -d && docker-compose logs` just so I don't have to wait for the log output to catch up. 

The Docker Engine api already supports this on their `docker logs` endpoint with an `-f` option. `docker logs -f <container>`.

Essentially this Docker issue but for Compose
https://github.com/docker/docker/issues/2997

**Comment by aanand** [comment] 2015-08-17 12:10
This would involve using the [logs endpoint](http://docs.docker.com/reference/api/docker_remote_api_v1.19/#get-container-logs) in `docker-compose logs`, as opposed to the [attach endpoint](http://docs.docker.com/reference/api/docker_remote_api_v1.19/#attach-to-a-container), but I think that's fine.

It would also only work for containers using the `json-file` logging driver, according to the API docs.

**Comment by aanand** [comment] 2015-08-17 12:10
Duplicate of https://github.com/docker/compose/issues/265

**Closed by aanand** 2015-08-17 12:10 UTC
