### ISSUE TITLE
Broken Pipe On Running bash

### ISSUE THREAD

**Issue by edwinlunando** [docker/compose#1509] opened 2015-06-04 05:35 UTC
Hi! I want to go to my container console, so I run `docker-compose run web bash`, but, it raise an error.

```
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.2.0', 'console_scripts', 'docker-compose')()
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/Library/Python/2.7/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/Library/Python/2.7/site-packages/compose/cli/command.py", line 27, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/Library/Python/2.7/site-packages/compose/cli/command.py", line 59, in perform_command
    handler(project, command_options)
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 345, in run
    dockerpty.start(project.client, container.id, interactive=not options['-T'])
  File "/Library/Python/2.7/site-packages/dockerpty/__init__.py", line 27, in start
    PseudoTerminal(client, container, interactive=interactive, stdout=stdout, stderr=stderr, stdin=stdin).start()
  File "/Library/Python/2.7/site-packages/dockerpty/pty.py", line 154, in start
    self._hijack_tty(pumps)
  File "/Library/Python/2.7/site-packages/dockerpty/pty.py", line 242, in _hijack_tty
    write_stream.do_write()
  File "/Library/Python/2.7/site-packages/dockerpty/io.py", line 164, in do_write
    raise e
OSError: [Errno 32] Broken pipe
```

Is it a bug?

**Comment by aanand** [comment] 2015-06-04 09:57
Ah, thanks for creating a separate issue. Could you paste your `docker-compose.yml`?

**Comment by edwinlunando** [comment] 2015-06-04 09:59
Here.

```
db:
  image: postgres
  ports:
    - 5432:5432

# elasticsearch:
#   image: elasticsearch:1.5.2
#   ports:
#     - "9200"

redis:
  image: redis:2.8.17
  ports:
    - 6379:6379

web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/sprinkles
  ports:
    - 3000:3000
  links:
    - db
    # - elasticsearch
    - redis
  environment:
    - DEV_DB_HOSTNAME=db
    - DEV_DB_NAME=sprinkles_dev
    - DEV_DB_USERNAME=postgres
```

**Comment by rogerroelofs** [comment] 2015-06-08 11:20
I'm having the same issue.

Here's my docker-compose.yml  My coworker is using the same yml file without incident.
```yaml
db:
  image: mysql:5.6
  ports:
    - "13306:3306"
web:
  build: .
  command: bundle exec unicorn -p 3000
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - db
```

**Comment by aanm** [comment] 2015-06-08 11:59
I saw this a couple of times after leaving compose running on foreground after a couple hours but I can't remember if it was related with the fact that I've suspended my machine or not, that's why I've never created an issue.
I'm running the compose demo yml file.

**Comment by appden** [comment] 2015-06-26 22:17
I'm experiencing this issue as well.

**Comment by mdarby** [comment] 2015-07-08 14:47
Same boat. Just started happening today. Upgraded boot2docker, et al.
`docker-compose run web rails console`

**Comment by michaelperret** [comment] 2015-08-12 11:10
any updates on this?

**Comment by voidlily** [comment] 2015-10-22 23:47
This is potentially a duplicate of #1604. The workaround described in that issue was to `pip uninstall ndg-httpsclient`. Uninstalling that package fixed the problem for me.

**Comment by saulshanabrook** [comment] 2015-12-29 04:21
I am getting the same error and I don't have `ndg-httpsclient` installed.


```bash
$ docker-compose --x-networking run --rm db pg_dump  <private> -h <private> -p 6402 dc36psfashsr9v | docker-compose --x-networking run --rm db pg_restore --verbose --no-acl --no-owner -h djangocanadanewyork_db_1 -p 5432 -d postgres
Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.5.2', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 54, in main
    command.sys_dispatch()
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 171, in perform_command
    handler(project, command_options)
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 421, in run
    run_one_off_container(container_options, project, service, options)
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 655, in run_one_off_container
    dockerpty.start(project.client, container.id, interactive=not options['-T'])
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/vendor/lib/python2.7/site-packages/dockerpty/__init__.py", line 27, in start
    PseudoTerminal(client, container, interactive=interactive, stdout=stdout, stderr=stderr, stdin=stdin).start()
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/vendor/lib/python2.7/site-packages/dockerpty/pty.py", line 153, in start
    self._hijack_tty(pumps)
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/vendor/lib/python2.7/site-packages/dockerpty/pty.py", line 241, in _hijack_tty
    write_stream.do_write()
  File "/usr/local/Cellar/docker-compose/1.5.2/libexec/vendor/lib/python2.7/site-packages/dockerpty/io.py", line 164, in do_write
    raise e
OSError: [Errno 32] Broken pipe
```

**Comment by saulshanabrook** [comment] 2015-12-29 05:08
When I run similar commands directly in Docker I get this error:

```
cannot enable tty mode on non tty input
Error deleting container: Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f
write /dev/stdout: broken pipe
```
 which I suspect is the underlying problem. So I think it's the fact that I am piping something to a container with a TTY allocated.

**Comment by jamshid** [comment] 2016-02-08 06:01
I was also getting the below error when using docker-compose 1.6 to run a service that starts a bash shell.

*WORKAROUND:* `brew uninstall docker-compose` and install the binary with a curl download ala https://github.com/docker/compose/releases/tag/1.6.0. This seems familiar maybe it was covered in another bug. 

```
$ docker-compose run foo
[...]# Traceback (most recent call last):
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.0', 'console_scripts', 'docker-compose')()
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 55, in main
    command.sys_dispatch()
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 174, in perform_command
    handler(project, command_options)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 507, in run
    run_one_off_container(container_options, project, service, options)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/lib/python2.7/site-packages/compose/cli/main.py", line 724, in run_one_off_container
    pty.start(sockets)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/pty.py", line 334, in start
    self._hijack_tty(pumps)
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/pty.py", line 370, in _hijack_tty
    write_stream.do_write()
  File "/usr/local/Cellar/docker-compose/1.6.0/libexec/vendor/lib/python2.7/site-packages/dockerpty/io.py", line 164, in do_write
    raise e
OSError: [Errno 32] Broken pipe
```

**Comment by millerdev** [comment] 2016-06-02 17:16
Also experienced this issue. `pip uninstall ndg-httpsclient` on the host (Mac OS X 10.11.5/boot2docker) fixed the issue.

**Comment by ricklindstrom** [comment] 2016-06-10 23:26
One simple thing to watch out for: If you are piping the output of docker-compose (or have a wrapper script that is piping), then getting rid of that pipe should probably resolve this error.

**Comment by shin-** [comment] 2017-03-08 23:44
As was pointed out by other comments, if you're still encountering this error, make sure you don't install `ndg-httpsclient` in the same environment as Compose.

**Closed by shin-** 2017-03-08 23:44 UTC
Labels: area/run, kind/bug
