### ISSUE TITLE
container logs are missing when `fig up` by Webstorm 

### ISSUE THREAD

**Issue by mileswang87** [docker/compose#1060] opened 2015-03-04 19:34 UTC
environment:
boot2docker v1.5.0
docker v1.5.0
docker-compose 1.1.0

`fig up` didn't show container logs when running, the only output is.
```
Recreating  test_web_1...
```

but when I stop the process, the whole logs will all come up at same time.
```
Recreating test_web_1...
Stopping test_web_1...

Attaching to test_web_1
Aborting.
web_1 | 4 Mar 19:21:06 - [nodemon] v1.3.7
web_1 | 4 Mar 19:21:06 - [nodemon] to restart at any time, enter `rs`
web_1 | 4 Mar 19:21:06 - [nodemon] watching: *.*
web_1 | 4 Mar 19:21:06 - [nodemon] starting `node ./bin/www`
Gracefully stopping... (press Ctrl+C again to force)
```

---------
Also encountering the same issue when running with gulp.
```javascript
/* gulpfile */
var gulp  = require('gulp');
var shell = require('gulp-shell');

gulp.task('docker', shell.task([
  'boot2docker up && $(boot2docker shellinit) && docker-compose up'
]));
```

**Comment by wangxunn** [comment] 2015-03-04 19:35
I end up modified and recompiled the source code, to forced logPrinter flush output after each write().  It seems temporary solved for me.
```
#in log_printer.py

    def run(self):
        mux = Multiplexer(self.generators)
        for line in mux.loop():
            self.output.write(line)
```
change to
```
    def run(self):
        mux = Multiplexer(self.generators)
        for line in mux.loop():
            self.output.write(line)
            self.output.flush()
```

**Comment by dnephin** [comment] 2015-09-18 20:55
Sounds like an issue with buffering

**Comment by dnephin** [comment] 2015-10-19 21:58
Going to close as a duplicate of #1549 since I believe they are both about buffering.

**Closed by dnephin** 2015-10-19 21:58 UTC
Labels: area/logs
