### ISSUE TITLE
Environment variables not being set by `docker-compose run -e VAR=VALUE`

### ISSUE THREAD

**Issue by abl** [docker/compose#6889] opened 2019-09-08 05:06 UTC
## Description of the issue

Using `docker-compose` I'm unable to get environment variables to be set at runtime. This is applying both to `docker-compose up` and `docker-compose run` with `-e` overrides. `docker run` works as expected.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Output of `docker version`**
```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.11
 Git commit:        8cdf373
 Built:             Thu Aug 15 06:47:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       62fd7b0
  Built:            Thu Aug 15 06:45:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  letsencrypt-dns:
    container_name: letsencrypt-dns
    environment:
      LETSENCRYPT_USER_MAIL: redacted@redacted.com
      LEXICON_LINODE4_AUTH_TOKEN: redacted
      LEXICON_LINODE4_TTL: '300'
      LEXICON_PROVIDER: linode4
      LEXICON_SLEEP_TIME: '1200'
    image: adferrand/letsencrypt-dns:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
    - /volume1/docker/letsencrypt-dns:/etc/letsencrypt:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.0'
```

## Steps to reproduce the issue

1. `docker-compose run --rm -e LETSENCRYPT_STAGING=true letsencrypt-dns env | grep LETSENCRYPT_STAGING`
2. `docker run --rm -e LETSENCRYPT_STAGING=true adferrand/letsencrypt-dns env | grep LETSENCRYPT_STAGING`
3. Attempt to run the above `docker-compose.yml` and note that all environment variables are as their defaults in the Dockerfile.

### Observed result

1. `LETSENCRYPT_STAGING=false`
2. `LETSENCRYPT_STAGING=true`
3. Various failures in the logs as all environment variables are set to their defaults.

### Expected result

1. `LETSENCRYPT_STAGING=true`
2. `LETSENCRYPT_STAGING=true`
3. Success.

### Stacktrace / full error message

N/A

## Additional information

Synology DSM 6.2.2-24922 Update 2 (synology_apollolake_918+); `docker-compose` installed via curl.

**Comment by AeroSW** [comment] 2019-09-08 22:07
I'm having the same issue here, except it is complaining with the following:

> ERROR: Invalid interpolation format for "environment" option in service "back-end": ENVIRONMENT Variable

I'm using a ".env" file in my project.
It is complaining about the first environment line, "VAR1: ${ENV_VAR1}", in my compose formatted as the following:
`environment:
    VAR1: ${ENV_VAR1}
    VAR2: ${ENV_VAR2}
    VAR3: ${ENV_VAR3}`

When I escaped the $ on each environment declaration, "VAR1: $${ENV_VAR1}", it ran the compose, but the environment variables were undefined, as expected.  Did something happen to the interpreter for the Docker Compose YAML?

P.S. I did have 1 line with a $ in the ".env", but it was something that I was not using, so I deleted the line outright, but I am still receiving this error.

**Comment by abl** [comment] 2019-09-09 06:03
Also of note - none of the variables in the `environment` section are set during `run` or `up`.

This YAML worked before so I assumed it was an issue in the `Dockerfile` but I can’t explain why `docker run` has different behavior.

No errors are surfaced by docker or docker-compose.

**Comment by Thilas** [comment] 2019-09-17 20:02
I have the exact same issue: environment variables defined in a `docker-compose.yml` file (using `environment:` or `env_file:` sections) are not set on the docker containers even though `docker-compose config` does show the expected configuration.

I noticed the problem a few days ago on existing projects that were working fine until then.

**Comment by Thilas** [comment] 2019-09-28 14:23
Any news about this issue? I just can't use docker-compose at all right now...

**Comment by Thilas** [comment] 2019-09-28 15:43
FYI, I just tried to update manually my docker-compose (1.24.0, provided by DSM Synology) to 1.24.1, and it is now back to normal.

**Comment by scyto** [comment] 2019-10-09 22:17
FYI, when calling US synology support they insist this is a docker issue and docker 'make the package' - obviously this is bogus as synology compile and tweak (significantly) the image. Can anyone confirm if the issue applies on other platforms with this exact version of docker compose? (my assumption is not, but would be good if someone could test)?

**Comment by scyto** [comment] 2019-10-09 22:22
some minor  variations in my versions, issue still present:
```
docker-compose version 1.24.0, build **0aa59064**
docker-py version: **3.7.2**
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```
```
Client:
 Version:           1**8.09.8**
 API version:       1.39
 Go version:        go1.11
 Git commit:        **2c0a67b**
 Built:             **Fri Sep  6 02:50:44 20**19
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11
  Git commit:       **1d8275b**
  Built:            **Fri Sep  6 02:51:05 2019**
  OS/Arch:          linux/amd64
  Experimental:     false**** ```

**Comment by scyto** [comment] 2019-10-10 16:36
@Thilas whats the command for updating to 1.24.1 compose?

**Comment by scyto** [comment] 2019-10-10 16:57
@Thilas  i used ```curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /var/packages/Docker/target/usr/bin/docker-compose``` to update, docker-compose version shows i did it right, were there any other steps as this has not fixed my issue with portainer :-(

**Comment by Thilas** [comment] 2019-10-10 19:42
@scyto, FYI I just ran the commands suggested on [GH's release page](https://github.com/docker/compose/releases):
```
curl -L https://github.com/docker/compose/releases/download/1.25.0-rc2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
and it fixed my issue.

**Comment by scyto** [comment] 2019-10-10 19:44
@Thilas thanks, i am a little confused did you fix the issue with 1.24.1 as you stated or this 1.25.0-rc2 release?

**Comment by Thilas** [comment] 2019-10-10 19:47
@scyto, sorry I just copy pasted the latest command from the release page but I did indeed upgraded to 1.24.1.

**Comment by scyto** [comment] 2019-10-10 19:49
thanks, neither worked for me deploying via portainer (never tested manually, guess i need to do that!)

**Comment by scyto** [comment] 2019-10-10 20:02
Ok, I ran the example at the top of the ticket.
The YAML variables are applying quite happily
```      LETSENCRYPT_USER_MAIL: redacted@redacted.com
      LEXICON_LINODE4_AUTH_TOKEN: redacted
      LEXICON_LINODE4_TTL: '300'
      LEXICON_PROVIDER: linode4
      LEXICON_SLEEP_TIME: '1200' ```

however the -'e STAGING=true' is not applying and still shows as false.  
So i guess while the env vars included in the yaml file are applying now, the -e overides are not?  Does anyone else see the same?

**Comment by scyto** [comment] 2019-10-10 20:15
I tried the repro at the top with the official synology packager docker -compose v1.24.0 and the 1.25.0-rc2 (as that should have all the 1.24.0 commits).  The variables in the YAML are applied, the variables in the -e are not.

**Comment by ndeloof** [comment] 2019-10-11 07:56
I tried to reproduce on a minimal scenario with latest docker-compose release :

```yaml
#docker-compose.yml
version: '3.7'
services:
  test:
    build: .
```

```yaml
#Dockerfile
FROM alpine
ENV FOO=BAR
```

```
➜  docker-compose run  test env | grep FOO
FOO=BAR
➜  docker-compose run -e FOO=ZOT test env | grep FOO
FOO=ZOT
```


Also tried with your specific scenario:
```
➜  docker-compose version
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
➜  docker-compose run --rm -e LETSENCRYPT_STAGING=true letsencrypt-dns env | grep LETSENCRYPT_STAGING
LETSENCRYPT_STAGING=true
➜  docker-compose run --rm -e LETSENCRYPT_STAGING=false letsencrypt-dns env | grep LETSENCRYPT_STAGING
LETSENCRYPT_STAGING=false
```

Also noted the [reference documentation](https://docs.docker.com/compose/reference/run/) doesn't clearly define how the `-e` option impact executed containers, it only has been assumed here it's comparable to the docker run option.

Please let me know if you still get this issue with minimal scenario, trying to identify the root issue for this problem.

**Comment by scyto** [comment] 2019-10-11 18:06
@ndeloof hi thanks for the simpler use case, this is my first time with docker-compose (and swarms) - portainer led me down this rat hole and i appreciate your hand holding her you did.  your simple case worked fine, i repeated the complex case and it was fine (1.24.0 docker-compose).  Only thing different i can think of is i did install the synology docker SPK package again from file (rather than package manager). And i may have got misled by the instruction `Attempt to run the above docker-compose.yml and note that all environment variables are as their defaults in the Dockerfile.`  i translated this to mean run `docker-compose up` which does result it false.

Of course it begs the question why it failed on 1.24.0 for others, and why portainer still fails to populate ENV  on synology, i will take it back to them.

**Comment by scyto** [comment] 2019-10-11 18:31
@ndeloof 
ok i think i have found the issue... when i run this no env var seems to get set... did i get synatx right?
```
 docker service create \
    --name test4 \
    --env MYVAR=rick \
    --mode global \
    nginx:latest
```
 i tired --env and -e and got same result.

(i realize this would mean it is not a compose bug but a docker bug....)

**Comment by ndeloof** [comment] 2019-10-14 06:03
Not sure what you expected, but works for me:

```
➜  docker service create \
>     --name test4 \
>     --env MYVAR=rick \
>     --mode global \
>     nginx:latest
f4u2155k85evw22gr9gn2ty5b
overall progress: 0 out of 1 tasks 
mciykuy9yqcs: running   [==================================================>] 
verify: Service converged 
➜  docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
5a89a2cf6000        nginx:latest        "nginx -g 'daemon of…"   6 seconds ago       Up 5 seconds        80/tcp              test4.mciykuy9yqcsjoibe752cph3l.iia7s0v4knje64utm928s9wfb
➜  docker exec -it 5a89a2cf6000 sh
# env
HOSTNAME=5a89a2cf6000
HOME=/root
PKG_RELEASE=1~buster
TERM=xterm
NGINX_VERSION=1.17.4
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NJS_VERSION=0.3.5
MYVAR=rick
PWD=/
```

I'm closing this issue, as simpler scenario demonstrate compose do behave as documented.

**Closed by ndeloof** 2019-10-14 06:03 UTC
Labels: kind/question, status/0-triage

**Comment by scyto** [comment] 2019-10-15 18:01
Just an update, official Synology response: 

```It looks like this is most likely being caused by the swarm function of the Docker, which is an issue that our developers are aware of. They are working on a fix, and it should be available in a future release, but there is no workaround in the meantime.```
