### ISSUE TITLE
thread.error: release unlocked lock

### ISSUE THREAD

**Issue by iMerica** [docker/compose#1069] opened 2015-03-05 19:05 UTC
I'm seeing this error when I attempt to stop services with control-c that were previously started with `fig up`

Full error:
```
Stopping foo...
Stopping baz
Stopping quuux
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 31, in main
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 21, in sys_dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 28, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.docopt_command", line 24, in dispatch
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.command", line 56, in perform_command
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.main", line 437, in up
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.log_printer", line 22, in run
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/fig.cli.multiplexer", line 25, in loop
  File "/Users/ben/fig/build/fig/out00-PYZ.pyz/Queue", line 182, in get
thread.error: release unlocked lock
```

The strange thing is: I don't have a user named "ben" on my machine.

**Comment by bfirsh** [comment] 2015-03-09 13:55
Nothing to worry about with the user "ben". I built the binary so my name shows up in the tracebacks. Sorry.

**Comment by iMerica** [comment] 2015-03-09 22:35
No worries. I should also mention that this error isn't actually breaking functionality. It's just something that's printed out when I send the SIGINT signal.

**Comment by deviantony** [comment] 2015-03-14 16:22
Having the same issue here with docker-compose:

```
^CGracefully stopping... (press Ctrl+C again to force)
Stopping a_1...
Stopping b_1...
Stopping c_1...
Stopping d_1...
Stopping e_1...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 455, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.log_printer", line 22, in run
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.multiplexer", line 25, in loop
  File "/code/build/docker-compose/out00-PYZ.pyz/Queue", line 182, in get
thread.error: release unlocked lock
```

Seems that the issue is also leaving unused files related to vfs in */var/lib/docker/vfs/dir*, I have to clean this folder manually.

Seems to be a duplicate of #189

**Comment by thaJeztah** [comment] 2015-03-15 16:20
Indeed, looks like a dup of #189

**Comment by aanand** [comment] 2015-07-16 11:07
Closing as duplicate of #189

**Closed by aanand** 2015-07-16 11:07 UTC
