### ISSUE TITLE
Using env_file with environment

### ISSUE THREAD

**Issue by ferrouswheel** [docker/compose#1171] opened 2015-03-24 21:22 UTC
The documentation is slightly ambiguous about what happens when you specify environment variables using both `env_file` and `environment`. It _does_ say "[Environment variables specified in environment override these values](https://docs.docker.com/compose/yml/#env_file)" but what about when environment doesn't specify the values like so:

``` yaml
  environment:
   POSTGRES_PASSWORD:
   POSTGRES_USER:
  env_file: .env
```

It'd be nice to have `POSTGRES_PASSWORD` and `POSTGRES_USER` in `.env` and have them in `docker-compose.yml` at the same time. Basically telling people, "hey, you need to provide these values" either in `.env` or  in the shell environment you run `docker-compose up` in.

If that's not possible or would only add confusion, then it'd be cool to add that the override happens _even when_ they are blank and read from the shell environment.

**Comment by cressie176** [comment] 2015-04-11 22:01
@ferrouswheel Sorry for off topic, but have you actually got POSTGRES_PASSWORD and POSTGRES_USER to work? If I specify those variable with -e to docker run everything works fine, but using docker-compose cannot connect

**Comment by ferrouswheel** [comment] 2015-04-11 22:14
@cressie176 I have. I use it for my open source docker-based [CI tool](https://github.com/docker-systems/baleen). See the docker-compose.yml there and the README.md.

As I remember it, the postgres container sets the user/password the *first time you run it*, so if you run it once with no credentials, it'll use the defaults the next time your start the container. Try removing the container completely and recreating it with the credentials you want to use.

**Comment by cressie176** [comment] 2015-04-11 22:15
Makes sense. Thanks

**Comment by thaJeztah** [comment] 2015-04-11 23:32
@ferrouswheel so, this issue is resolved, or did I interpret your previous comment incorrectly?

**Comment by ferrouswheel** [comment] 2015-04-11 23:34
@thaJeztah No sorry - that was a reply to the previous OT question.

**Comment by pikeas** [comment] 2015-05-07 19:22
+1, just got bit by this (even the specific case of POSTGRES_PASSWORD!).

I provided `POSTGRES_PASSWORD` as an unset value in `environment`, and `POSTGRES_PASSWORD=foo` in `.env`. Compose used the empty value in my environment instead of the value in `.env`.

Building on this (can open another issue, but compose already has a few too many of those...), there should be a way to require strict checking of all (or a subset of) environment variables, so that containers will fail to start if those variables are not set.

The simplest thing that could work is adding a new key called `environment_strict`.

**Comment by aanm** [comment] 2015-05-08 01:11
Doesn't the `extends` solve this?
https://docs.docker.com/compose/extends/#define-the-production-environment

**Comment by lupa18** [comment] 2016-03-24 16:26
I'm not sure if here or I must open a new issue, but.. when I use _environment_ values are parsing correct, but if I use _env_file_ with exactly the same values, container doesn't works well. 
The error can be reproduced for example with this:
```
db:
  image: mdillon/postgis
  env_file: env.conf
```

and this:
```
POSTGRES_USER: user
POSTGRES_PASSWORD: secret
POSTGRES_DB: base
```

Then, no error appears, but user and base are not created. If I put them inside compose file with _environment_ it works well. 

docker-compose version 1.5.2

thanks in advance !

**Comment by dnephin** [comment] 2016-03-24 16:56
I don't think that's a valid `env_file`. It should be `POSTGRES_USER=user`, etc. https://docs.docker.com/compose/compose-file/#env-file

**Comment by shin-** [comment] 2017-08-17 21:10
Closing: https://github.com/docker/docker.github.io/pull/4177

**Closed by shin-** 2017-08-17 21:10 UTC
Labels: kind/docs

**Comment by damianobarbati** [comment] 2020-01-10 22:27
@lupa18 how did you solve? 

@shin- I'm not seeing the env_file respected.

`.env.development` file:
```bash
POSTGRES_USER=root
POSTGRES_PASSWORD=webapp
POSTGRES_DB=webapp
```

`docker-compose.yml` file:
```yaml
    db:
        env_file: .env.${NODE_ENV}
        environment:
            - POSTGRES_USER=${POSTGRES_USER:?}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
            - POSTGRES_DB=${POSTGRES_DB:?}
        image: postgres:12-alpine
        container_name: ${POSTGRES_DB:?}-db
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./pg-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: unless-stopped
```

```
$ NODE_ENV=development NAME=webapp VERSION=1.1.0 docker-compose up --force-recreate --always-recreate-deps --renew-anon-volumes --remove-orphans --detach --build db

ERROR: Missing mandatory value for "environment" option in service "db":
```

Weird thing is this happens only with postgres image, because the other image in the yml is built correctly using the envs.

**Comment by rajeshhazari** [comment] 2020-10-08 12:28
I've this config that works, you have defined your **environment** variables as array is the issue:

compose-file
--------------------------
version: '3'
services:
  app-dev:
    env_file: ./scripts/env-${NODE_ENV}.conf
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:12-alpine
    container_name: "${POSTGRES_DB}-db"
    restart: always
    volumes:
        - ./pg-data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
        - 6432:5432
    networks:
        - dbnet
networks:
  dbnet:
    driver: bridge

scripts/env-dev.conf
------------------------------------

POSTGRES_PASSWORD=user321
POSTGRES_USER=user
POSTGRES_DB=app


export NODE_ENV=dev; export NAME=app_db;export VERSION=1.1.0;docker-compose up -d

**Comment by lnksz** [comment] 2024-02-08 13:54
I hit the same issue, and the above solution doesn't work.
I created a reproducer repo: https://github.com/lnksz/docker-compose-env-repro 

The variable definition from the default `.env` file can be used in the `environment:` attribute, but the variable from the `env_file:` attribute is only appended to the list of environment values, and seems like it cannot be used to initialize another variable from that.

I just cannot see this behavior described in the docs.
https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

> The [env_file attribute](https://docs.docker.com/compose/compose-file/05-services/#env_file) lets you use multiple .env files in your Compose application...

Sounds much like the `env_file:` attribute has the same properties like the default `.env` file.

**Comment by jrzerr** [comment] 2024-05-02 19:41
The above recommended by @rajeshhazari does not work.

Slightly simplified to avoid needing to set any variables in your shell

# compose.yaml

```
version: '3'
services:
  app-dev:
    env_file: ./env.conf
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:12-alpine
    container_name: "${POSTGRES_DB}-db"
    restart: always
    volumes:
        - ./pg-data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
        - 6432:5432
    networks:
        - dbnet
networks:
  dbnet:
    driver: bridge
```

# env.conf

```
POSTGRES_PASSWORD=user321
POSTGRES_USER=user
POSTGRES_DB=app
```

# output of `docker compose config`

```
 dockertest % docker compose config
WARN[0000] The "POSTGRES_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_DB" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string. 
WARN[0000] The "POSTGRES_DB" variable is not set. Defaulting to a blank string. 
WARN[0000] /Users/jeremyzerr/zerrtech/dockertest/compose.yaml: `version` is obsolete 
name: dockertest
services:
  app-dev:
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    container_name: -db
    environment:
      POSTGRES_DB: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: ""
    image: postgres:12-alpine
    networks:
      dbnet: null
    ports:
      - mode: ingress
        target: 5432
        published: "6432"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /Users/jeremyzerr/zerrtech/dockertest/pg-data
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
networks:
  dbnet:
    name: dockertest_dbnet
    driver: bridge
```

# Result

Clearly shows that the POSTGRES env vars are blank underneath the `environment:` property

**Comment by rouba002** [comment] 2024-05-06 15:28
I believe the answer is as always in documentation. But two things are happening here.

[https://docs.docker.com/compose/environment-variables/envvars-precedence/](https://docs.docker.com/compose/environment-variables/envvars-precedence/)

First, those variables, as they are not defined in your shell ENV are just replaced by blanks. Effectively overriding your env.conf, higher precedence. Try to set one of your VARIABLES in shell, eg. `export POSTGRES_USER="aaa"`, and then `docker compose config` again.

The '.env' file is really treated in a special way with docker compose and is, AFAIK only source used to interpolate compose.yml file. 
So if you copy your `env.conf` to `.env` yo should see variables replaced except for POSTGRES_USER, which is still taken from ENV of your shell.

[https://docs.docker.com/compose/environment-variables/set-environment-variables/](https://docs.docker.com/compose/environment-variables/set-environment-variables/)
There is this small warning notice

```
Important

Substitution from .env files is a Docker Compose CLI feature.

It is not supported by Swarm when running docker stack deploy.```

I do not claim this is 100% true, so feel free to correct me.

BR, rouba

**Comment by yuimbo** [comment] 2024-06-07 09:43
@rouba002 does this mean that it is impossible to rename/reassign variables provided via env_file?

What is the recommended workflow to use in this kind of situation? 
.env file has to be swappable due to the project having multiple environments, and the specific variable naming conventions of one particular service should not "leak" up to affect the entire monorepo's configuration.

**Comment by sieman216485** [comment] 2024-11-18 20:44
> The above recommended by [@rajeshhazari](https://github.com/rajeshhazari) does not work.
> 
> Slightly simplified to avoid needing to set any variables in your shell
> 
> # compose.yaml
> ```
> version: '3'
> services:
>   app-dev:
>     env_file: ./env.conf
>     environment:
>         POSTGRES_USER: ${POSTGRES_USER}
>         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
>         POSTGRES_DB: ${POSTGRES_DB}
>     image: postgres:12-alpine
>     container_name: "${POSTGRES_DB}-db"
>     restart: always
>     volumes:
>         - ./pg-data:/var/lib/postgresql/data
>     command: postgres -c config_file=/etc/postgresql/postgresql.conf
>     ports:
>         - 6432:5432
>     networks:
>         - dbnet
> networks:
>   dbnet:
>     driver: bridge
> ```
> 
> # env.conf
> ```
> POSTGRES_PASSWORD=user321
> POSTGRES_USER=user
> POSTGRES_DB=app
> ```
> 
> # output of `docker compose config`
> ```
>  dockertest % docker compose config
> WARN[0000] The "POSTGRES_PASSWORD" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "POSTGRES_DB" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "POSTGRES_USER" variable is not set. Defaulting to a blank string. 
> WARN[0000] The "POSTGRES_DB" variable is not set. Defaulting to a blank string. 
> WARN[0000] /Users/jeremyzerr/zerrtech/dockertest/compose.yaml: `version` is obsolete 
> name: dockertest
> services:
>   app-dev:
>     command:
>       - postgres
>       - -c
>       - config_file=/etc/postgresql/postgresql.conf
>     container_name: -db
>     environment:
>       POSTGRES_DB: ""
>       POSTGRES_PASSWORD: ""
>       POSTGRES_USER: ""
>     image: postgres:12-alpine
>     networks:
>       dbnet: null
>     ports:
>       - mode: ingress
>         target: 5432
>         published: "6432"
>         protocol: tcp
>     restart: always
>     volumes:
>       - type: bind
>         source: /Users/jeremyzerr/zerrtech/dockertest/pg-data
>         target: /var/lib/postgresql/data
>         bind:
>           create_host_path: true
> networks:
>   dbnet:
>     name: dockertest_dbnet
>     driver: bridge
> ```
> 
> # Result
> Clearly shows that the POSTGRES env vars are blank underneath the `environment:` property
> 
> I don't see why `.env` is treated differently than setting the `env_file:` to a different file. I don't understand the reasoning there.

Hello, @jrzerr 

I also faced the same issue but found a solution on this link.
https://forums.docker.com/t/variables-resolved-from-env-file-but-not-taking-effect-in-docker-compose-yaml/105394/2

The `env_file` is only for defining environment variables inside the running container, and it can not be used for variable substitution in `docker-compose.yaml` file.

**Solutions**

1. You can run: `source env.conf` before running `docker-compose up` so that those environment variables are set in your system environment.
2. You can rename `env.conf` to `.env` and then docker-compose will read them as environment variables to be used for substitution in your `docker-compose.yaml` file.
3. You can also tell compose the name of the environment file that you want to use like this: `docker-compose --env-file image.env up`

Thanks and regards.
