### ISSUE TITLE
Divergence of behavior between Docker and Docker-compose

### ISSUE THREAD

**Issue by pnathan** [docker/compose#1173] opened 2015-03-25 04:22 UTC
High-level overview:

`docker build .` successfully builds my docker image.
`docker-compose up` instead does not work.

---

Given the below files, when I do "docker-compose up" in a directory with all of them, I get a list of output; critically, the networking does not appear to work:
```
web_1 |     trivial-mimes trivial-types trivial-utf-8 xsubseq
web_1 |
web_1 | debugger invoked on a SB-BSD-SOCKETS:HOST-NOT-FOUND-ERROR in thread
web_1 | #<THREAD "main thread" RUNNING {1003037183}>:
web_1 |   Name service error in "getaddrinfo": -2 (Name or service not known)
```
However, when I do the (theoretically?) same operation in Docker by performing `docker run`, the appropriate splatter is delivered onto the terminal.

Expected behavior: `docker-compose up` behaves identically to `docker build` and `docker run`.
Observed behavior: `docker-compose up` does not appear to have networking capabilities fully baked, causing the bringup of the service to fail.

---

Here are the files:

_docker-compose.yml_
```
# a basic service.
web:
  build: .
  ports:
   - "5000:8000"
```

_Dockerfile_

```
run apt-get update
run apt-get install -y curl
run apt-get install -y bzip2
run apt-get install -y sudo
run curl -L -O  http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.6-x86-64-linux-binary.tar.bz2
run tar xjf /sbcl-1.2.6-x86-64-linux-binary.tar.bz2

run apt-get install -y make

run cd sbcl-1.2.6-x86-64-linux/ && sudo bash install.sh
run echo "hello"
add http://beta.quicklisp.org/quicklisp.lisp /quicklisp.lisp
run sbcl --load /quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(quit)'
add ./hello.lisp /hello.lisp
cmd sbcl --load /hello.lisp
```
_hello.lisp_ 

```
(require "sb-posix")
#-quicklisp
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                       (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))

(defparameter *pwd* (concatenate 'string (sb-posix:getcwd) "/"))
(push *pwd* asdf:*central-registry*)

(ql:quickload :ningle)

(defvar *app* (make-instance 'ningle:<app>))

(setf (ningle:route *app* "/")
      "Welcome to ningle!")

(clack:clackup *app*)

(loop while t
      do
         (format t "heartbeat")
         (sleep 60))

```

**Comment by thaJeztah** [comment] 2015-03-25 20:39
Have you tried to run the image that was built by compose via Docker? Ie;

    docker run -p 5000:8000 projectname_web

That should narrow down if the *image* wasn't built correctly or that the "run" isn't working right.

Also note that `docker-compose up` doesn't automatically re-build the image, so if you have made changes to your Dockerfile, or `hello.lisp` it's possible that the image doesn't contain those latest changes.

You can manually trigger a build via `docker-compose build web`

n.b. It looks like your Dockerfile is incomplete, because there's no `FROM ....`

**Comment by pnathan** [comment] 2015-03-27 01:58
1. docker-compose build web.
2. docker-compose up ;; getaddrinfo error, sad.
2. docker run ... projectname_web ;; yay

n.b., copypaste fail with the dockerfile - here's the full one

```
from debian:7.4
run apt-get update
run apt-get install -y curl
run apt-get install -y bzip2
run apt-get install -y sudo

run curl -L -O  http://prdownloads.sourceforge.net/sbcl/sbcl-1.2.6-x86-64-linux-binary.tar.bz2
run tar xjf /sbcl-1.2.6-x86-64-linux-binary.tar.bz2

run apt-get install -y make

run cd sbcl-1.2.6-x86-64-linux/ && sudo bash install.sh
run echo "hello"
add http://beta.quicklisp.org/quicklisp.lisp /quicklisp.lisp
run sbcl --load /quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(quit)'

add ./bake.lisp /bake.lisp
run sbcl --load /bake.lisp

add ./hello.lisp /hello.lisp
cmd sbcl --load /hello.lisp
```

**Comment by thaJeztah** [comment] 2015-03-27 13:17
Trying to reproduce (I don't have LISP experience, so just running your example);

I didn't have the `bake.lisp` file, so I commented these two lines;
```Dockerfile
#add ./bake.lisp /bake.lisp
#run sbcl --load /bake.lisp
```

After that, `docker-compose build web` and `docker-compose up web`, see this gist;
https://gist.github.com/thaJeztah/31032d48aed0d94367de (note: I have an alias `fig`, but it is actually `docker-compose`)

The container seems to be running fine, but connecting won't work;

```bash
curl http://[my-docker-host]:8000
curl: (7) Failed to connect to [my-docker-host] port 8000: Connection refused
```

*However*, it looks like you have swapped the port numbers in your `docker-compose.yml`, because the server in your container seems to be listening on port 5000, not 8000; 

```
web_1 | ; Loading "clack-handler-hunchentoot"
web_1 | [package clack.handler.hunchentoot]
web_1 | Hunchentoot server is started.
web_1 | Listening on localhost:5000.
```
(note that the server actually seems to be listening on `0.0.0.0:5000`, not just localhost)

Changing the `docker-compose.yml` to this;
```YAML
# a basic service.
web:
  build: .
  ports:
   - "8000:5000"
```

```bash
curl http://[my-docker-host]:8000
Welcome to ningle!
```

Tested on;
    docker-compose 1.1.0
    Docker version 1.5.0, build a8a31ef

**Comment by aanand** [comment] 2015-03-27 21:10
Long shot, but are you using Compose 1.2.0 RC1? There's a networking issue that's fixed in RC2.

https://github.com/docker/compose/releases/tag/1.2.0rc2

**Comment by dnephin** [comment] 2015-09-28 21:47
No response from OP and we haven't heard any other reports of this issue

**Closed by dnephin** 2015-09-28 21:47 UTC
