### ISSUE TITLE
entrypoint defined in docker-compose.yml wipes out CMD defined in Dockerfile

### ISSUE THREAD

**Issue by mericano1** [docker/compose#3140] opened 2016-03-15 22:30 UTC
Hi, I am following the example on https://docs.docker.com/compose/startup-order/ to make sure the database is running before I start the application.
My `Dockerfile` contains the command

```
CMD ["/usr/bin/java", "-jar", "/usr/lib/gumtree/api-server/server/api-server.war"]
```

and in my `docker-compose.yml` I have 

```
entrypoint: ["/usr/bin/wait-for-it.sh", "postgres001:5432", "-t", "120", "--"]
```

but after the postgres database starts the service container just exits straight away.

```
api_1        | wait-for-it.sh: postgres001:5432 is available after 42 seconds
postgres001_1 | LOG:  database system is ready to accept connections
api_api_1 exited with code 0
```

Looking inside the running container I can see the entrypoint does not have the command appended

```
docker exec b456a362e587 ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.2  0.0  21816  3200 ?        Ss   22:12   0:00 bash /usr/bin/wait-for-it.sh postgres001:5432 -t 120 --
```

If both command and entrypoint are in the same place (either in the `Dockerfile` or in the `docker-compose.yml`) the application starts up properly. 

```
› docker exec 6cafdb9fdcf2 ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.2  0.0  21816  3208 ?        Ss   22:10   0:00 bash /usr/bin/wait-for-it.sh postgres001:5432 -t 120 -- java -jar /usr/lib/gumtree/api-server/server/api-server.war
```

Any idea is this is a bug or I am doing something wrong?

Thanks

**Comment by dnephin** [comment] 2016-03-16 02:41
hmm, it does kind of feel like a bit in this case, but I think it's been this way for a while.  The output of `docker inspect <container name>` would be good to verify exactly what the engine is receiving.

**Comment by mericano1** [comment] 2016-03-16 09:58
Indeed @dnephin, the CMD gets wiped out

    › docker inspect 172ab44fb462
    ...
    "Cmd": null,
    "Image": "api-server",
    "Volumes": null,
    "WorkingDir": "",
    "Entrypoint": [
      "/usr/bin/wait-for-it.sh",
      "postgres001:5432",
      "-t",
      "120",
      "--"
    ]

**Comment by igorspasic** [comment] 2016-04-06 00:39
Same here.

**Comment by max-zelinski** [comment] 2016-05-02 11:03
the same, had to put CMD in compose yaml for now...

**Comment by NMichas** [comment] 2016-05-07 17:06
Same here on Docker beta for OSX:
* Docker version 1.11.1, build-5604cbe
* docker-compose version 1.7.0, build-0d7bf73

Adding the CMD in docker-compose (or re-specifying it after -- on wait-for-it) works, but it is not such a good solution considering it tightly couples the docker-file with the underlying image.

**Comment by derekmahar** [comment] 2016-05-12 23:26
I also encountered this issue in "[How can I make my Docker compose “wait-for-it” script invoke the original container ENTRYPOINT or CMD command?](http://stackoverflow.com/questions/37194733/how-can-i-make-my-docker-compose-wait-for-it-script-invoke-the-original-contai)" which I demonstrate using example [`docker-compose-wait-for-file`](https://github.com/derekmahar/docker-compose-wait-for-file).

```
derek@derek-lubuntu:~/Projects/docker-compose-wait-for-file$ docker-compose up
Creating dockercomposewaitforfile_create_1
Creating dockercomposewaitforfile_wait_1
Attaching to dockercomposewaitforfile_create_1, dockercomposewaitforfile_wait_1
create_1  | Sleeping for 10 s.
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
create_1  | Created file /wait/done.
dockercomposewaitforfile_create_1 exited with code 0
wait_1    | Found file [/wait/done].
dockercomposewaitforfile_wait_1 exited with code 0
 
```

Adding a `CMD` to image `ubuntu-wait-for-file` doesn't help:

```
derek@derek-lubuntu:~/Projects/docker-compose-wait-for-file$ git diff
diff --git a/ubuntu-wait-for-file/Dockerfile b/ubuntu-wait-for-file/Dockerfile
index 20e92c0..ccbabb7 100644
--- a/ubuntu-wait-for-file/Dockerfile
+++ b/ubuntu-wait-for-file/Dockerfile
@@ -1,3 +1,4 @@
 FROM ubuntu
 ADD wait-for-file.sh /
 RUN chmod +x /wait-for-file.sh
+CMD ["echo", "'Can you see me?'"]
derek@derek-lubuntu:~/Projects/docker-compose-wait-for-file$ docker-compose build
Building create
Step 1 : FROM ubuntu
 ---> b549a9959a66
Step 2 : ADD create-file.sh /
 ---> Using cache
 ---> 67e5db59f8e2
Step 3 : RUN chmod +x /create-file.sh
 ---> Using cache
 ---> c7e361b4408e
Step 4 : ENTRYPOINT /create-file.sh
 ---> Using cache
 ---> 0360027060ca
Successfully built 0360027060ca
Building wait
Step 1 : FROM ubuntu
 ---> b549a9959a66
Step 2 : ADD wait-for-file.sh /
 ---> Using cache
 ---> db75cb689f0e
Step 3 : RUN chmod +x /wait-for-file.sh
 ---> Using cache
 ---> d9a991cdd174
Step 4 : CMD echo 'Can you see me?'
 ---> Using cache
 ---> 19f4ad2a167c
Successfully built 19f4ad2a167c
derek@derek-lubuntu:~/Projects/docker-compose-wait-for-file$ docker-compose up
Creating dockercomposewaitforfile_create_1
Creating dockercomposewaitforfile_wait_1
Attaching to dockercomposewaitforfile_create_1, dockercomposewaitforfile_wait_1
create_1  | Sleeping for 10 s.
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
wait_1    | Waiting for file [/wait/done].
create_1  | Created file /wait/done.
dockercomposewaitforfile_create_1 exited with code 0
wait_1    | Found file [/wait/done].
dockercomposewaitforfile_wait_1 exited with code 0
```

**Comment by Satchitananda** [comment] 2016-05-24 04:34
Same, why docker guys not to fix it?

**Comment by ransingh** [comment] 2016-06-02 13:07
I am having the same issue.
entrypoint in docker-compose is wiping out CMD specified inside the dockerfile.

```JSON
           "Cmd": null,
            "Image": "ransingh/siglee-api:61e2686",
            "Volumes": {
                "/home/siglee/siglee-api/log": {}
            },
            "WorkingDir": "/home/siglee/siglee-api",
            "Entrypoint": [
                "./wait_for_db",
                "db"
            ],
```

**Comment by gannicottb** [comment] 2016-06-09 21:38
Same here. :(

CMD defined in the app Dockerfile like so:
`CMD ["java", "-jar", "./target/app.jar"]`

Entrypoint defined in docker-compose.yml like so:
`entrypoint: ["/usr/scripts/wait-for-it.sh", "db:5432", "-- "]`

Container inspect on the app:
`"Entrypoint": [
                "/usr/scripts/wait-for-it.sh",
                "cotillion_db:5432"
            ],
`

Would love to see this fixed so I don't have to copy the CMD from the container into compose (especially as a general practice for many such container + db setups).

**Comment by numbnut** [comment] 2016-07-21 13:53
Same for me on OSX:
docker: Docker version 1.12.0-rc4, build e4a0dbc, experimental
docker-compose: docker-compose version 1.8.0-rc2, build c72c966
It would be very nice to see this fixed.

**Comment by aanand** [comment] 2016-07-21 14:18
I'm not convinced this is a bug. It's consistent with `docker run`:

```dockerfile
FROM alpine
CMD ["echo", "default command"]
```

```console
$ docker build -t 3140 .

$ docker run --name no-entrypoint 3140
default command

$ docker inspect no-entrypoint
...
            "Cmd": [
                "echo",
                "default command"
            ],
...

$ docker run --name with-entrypoint --entrypoint echo 3140
<outputs a blank line>

$ docker inspect with-entrypoint
...
            "Cmd": null,
...
```

Apparently, this also happens when you set `ENTRYPOINT` in a Dockerfile which inherits a `CMD` from its parent image: see https://github.com/docker/docker/issues/19611.

The discussion in that issue suggests two things:

- This is by design.
- It's not well-documented.

On top of that, our startup order document is wrong, as @mericano1 has discovered. So I think this is a docs issue.

**Comment by derekmahar** [comment] 2016-07-21 14:52
If it's by design, then I think it might be useful for a container to have a straightforward mechanism to invoke the `ENTRYPOINT` or `CMD` of its parent, similar to how many object-oriented programming languages enable a constructor to invoke a parent constructor creating a chain of constructor invocations to the root object.

**Comment by numbnut** [comment] 2016-07-21 15:00
Just an addition about the docker-compose documentation. The docker-compose.yml in the [example](https://docs.docker.com/compose/startup-order/) implies that the command is not deleted, if the entrypoint is set in a compose file. Maybe the example is wrong, but that was the way I ran into this trap.

**Comment by aanand** [comment] 2016-07-21 15:17
Yes, that's what I mean. We should fix that, add a note to the `entrypoint` documentation in the Compose file doc, and also ensure it's noted in the Engine docs for the `ENTRYPOINT` Dockerfile instruction and `--entrypoint` flag.

**Comment by aanand** [comment] 2016-07-21 15:18
@derekmahar That's an interesting idea, but that discussion should probably happen in a new issue on docker/docker.

**Comment by MrShoco** [comment] 2016-07-25 15:21
Same here, +

**Comment by MrShoco** [comment] 2016-07-25 15:23
Same bug
Docker version 1.11.2, build b9f10c9
docker-compose version 1.8.0-rc2, build c72c966

**Comment by aanand** [comment] 2016-07-25 16:05
@MrShoco It's not a bug - please read the discussion.

**Comment by aanand** [comment] 2016-07-25 16:15
Compose-side docs updated in https://github.com/docker/compose/pull/3764.

**Comment by aanand** [comment] 2016-07-25 16:28
Engine-side docs updated in https://github.com/docker/docker/pull/25012.

**Comment by MrShoco** [comment] 2016-07-25 20:04
Thanks, a bug in the documentation misled me.

**Comment by lefterisnik** [comment] 2016-10-04 09:33
I face a similar problem when I have something like that on the docker-compose file:

```
entrypoint: /srv/wait-for-it.sh postgres:5432 --
command: bash -c "python manage.py migrate && uwsgi --ini /etc/web/uwsgi.ini --py-autoreload 1"
```

Also, when I try to run:

`docker-compose run web bash -c "python manage.py migrate && uwsgi --ini /etc/web/uwsgi.ini --py-autoreload 1"` 

I get a python console only.

What am doing wrong?

**Comment by adonay28** [comment] 2016-11-13 14:53
I'm facing this issue too:

i have the entrypoint in docker-compose.yml:
`entrypoint: ./wait-for-it.sh -t 60 --strict mydb:3306`

and the cmd in the Dockerfile:
`CMD ["java","-jar","Testone_10006.jar"]`

It waits until the db is available but then it doesn't do anything.

**Comment by Syy0n** [comment] 2016-11-13 16:51
still not fixed...

**Comment by ngocdaothanh** [comment] 2016-11-24 04:43
Hey, from the discussion above I understand that `entrypoint` in docker-compose.yml will override `CMD` in Dockerfile.

But is there a way to embed the original `CMD` in Dockerfile to `entrypoint` in docker-compose.yml?

**Comment by imaia** [comment] 2016-12-27 17:20
Why override CMD when someone is only overriding entrypoint? Maybe, this "feature" just complicates things. Maybe it is a bug.

**Comment by james-turner** [comment] 2017-01-06 08:43
I'm also inclined to say I don't like this behaviour. 

It would be preferable to either 
a) maintain the original CMD in the parent image, such that when the child image specifies ENTYPOINT the 2 are concatenated (as expected) so you get ENTRYPOINT + CMD.
b) allow the child image to invoke the parent CMD such that you can manually compose ENTRYPOINT + CMD without having to copy/paste CMD from the parent image into your child dockerfile. 

Otherwise; there is no way for child images to prefix a cmd in a parent image without having to duplicate the parent CMD invocation. The parent CMD might change in a subsequent version of the parent image, consequently causing the child image to break because the copied invocation is incorrect now.

**Comment by craigotis** [comment] 2017-01-07 16:51
This is really confusing to me. It seems crucial for a compose file to _prepend_ the command that's run by the underlying `Dockerfile`.

The compose file should _not_, IMO, be in charge of the commands run by the underlying `Dockerfile` unless that's the author's intention.

There needs to be a way to run a command (specified by the compose file) _prior_ to the execution of the underlying `CMD` specified by the `Dockerfile`.

**Comment by BBartosz** [comment] 2017-07-18 17:47
Ok so smb has idea how to fix this feature?

**Comment by shin-** [comment] 2018-03-28 21:05
Closing as this is not a Compose issue.

**Closed by shin-** 2018-03-28 21:05 UTC
Labels: area/config, kind/docs

**Comment by miguelpduarte** [comment] 2018-09-05 10:06
Is there a way to do this now?

I wish to prepend something to the command specified in the Dockerfile (in my case, a wait-for-it.sh call in order to wait for my DB service to start before the actual service starts) and have no way to call the "child" command (the one specified in the Dockerfile), having to resort to duplicating configuration, as mentioned above...

If there is no way to do this but to duplicate configuration I hereby request the issue to be reopened. Furthermore, this is clearly a compose issue, as defining the entrypoint in the docker-compose.yml file is what clears the command option - thus it cannot be anything **BUT** a compose issue.

**Comment by craigotis** [comment] 2018-09-05 10:55
I agree with @miguelpduarte's suggestion to reopen. If the maintainers (@shin-) disagree, can you please elaborate as to why this is:
> not a Compose issue.

Thanks

**Comment by shin-** [comment] 2018-09-05 16:05
Please refer to earlier responses in this thread: https://github.com/docker/compose/issues/3140#issuecomment-234267729

This is the engine's behavior. We can't do anything about it from Compose's end. If you want to suggest it be changed, you'll need to submit a proposal on the moby/moby repo.

**Comment by craigotis** [comment] 2018-09-05 17:09
@shin- Is it not possible for Compose to alter, even as a secondary option, the ability to _prepend_ the Docker container's command with the entrypoint command defined in the Compose file?

It seems if it has the ability to overwrite it, it should also have the ability to add to it, and that's what I think most of the folks in this thread are focused on accomplishing.

**Comment by ceoro9** [comment] 2020-01-08 15:17
Any updates? This overriding behavior is really annoying. 

The above proposed syntax to call CMD from Dockerfile was good.
> `entrypoint: ./wait-for-it.sh -t 60 --strict mydb:3306 && sh -c $DOCKERFILE_CMD`

**Comment by gnulnx** [comment] 2020-06-19 10:55
Because of this issue docker-compose is essentially worthless for anything but dev work.  You certainly can't prototype out prod deploys with it.  

Perhaps terraform is the better solution.

**Comment by brunojcm** [comment] 2020-07-30 03:11
Did anyone start an issue in the engine repo after all?

**Comment by Luc45** [comment] 2020-11-04 12:51
Christ, this is so annoying. Facing the same issue here.

**Comment by lobs001** [comment] 2021-01-26 16:01
Slight workaround:

If you have a custom image you can add a startscript to the build and call it inside the dockerfile and in the docker-compose you can call it again. Thats a way to avoid duplicate for more complicated entrypoints.

**Comment by cnaccio** [comment] 2021-06-13 14:00
OMG, I spent hours trying to figure out what I was doing wrong. This is so damn confusing. 

Is there an alternative to command or entrypoint to run a command on startup that can be configured in docker compose file?

**Comment by mursal-shydv** [comment] 2021-07-23 11:15
Still facing with this issue, wont be any update?

**Comment by jay-dee7** [comment] 2021-12-08 17:05
I dont get it. How is it that this issue hasn't been solved so far. By design is alright but clearly we have tons of community members requesting this feature. Would love to submit a PR if the maintainers would allow 🙏🏻

**Comment by BlakeGFitch** [comment] 2022-01-03 10:02
Just keeping this issue hot in 2022. Happy New Year! But still working around this. ;-)

**Comment by ansraliant** [comment] 2023-10-27 06:45
> Just keeping this issue hot in 2022. Happy New Year! But still working around this. ;-)

2023 reporting in. Cheers.

**Comment by ndeloof** [comment] 2023-10-27 07:24
Definitely not a docker compose issue, check github.com/moby/moby

```
$ cat Dockerfile 
FROM alpine
CMD ping localhost
$ docker build -t test .
..
 => => naming to docker.io/library/test   
$ docker run --entrypoint "/bin/echo" test

$ docker inspect xx
..
            "Cmd": null,
            "Entrypoint": [
                "/bin/echo"
            ],
```
