### ISSUE TITLE
expose field does not raise a validation error on invalid format

### ISSUE THREAD

**Issue by nathanleclaire** [docker/compose#2353] opened 2015-11-09 23:57 UTC
Consider:

```
leader:
  container_name: rethinkleader
  image: rethinkdb
  labels:
    - com.nathanleclaire.rethinkcluster
  environment:
    - affinity:label!=com.nathanleclaire.rethinkcluster
  expose:
    - "8080:8080"
  restart: always
follower:
  image: rethinkdb
  labels:
    - com.nathanleclaire.rethinkcluster
  command: rethinkdb --bind all --join rethinkleader:28015
  environment:
    - affinity:label!=com.nathanleclaire.rethinkcluster
  restart: always
```

Running this doesn't forward `8080` to `8080` on the leader instance for me.  Let me know if you're unable to dupe.

IIRC, Swarm will schedule `-p 8080:8080` just fine (won't schedule on nodes where that port is already in use), so it might be worth just throwing the API request over the fence anyway.

**Comment by dnephin** [comment] 2015-11-10 00:07
did you mean to use `ports:` ? `expose: ["8080:8080"]` is invalid config (or should be)

http://docs.docker.com/compose/compose-file/#expose
http://docs.docker.com/compose/compose-file/#ports

**Comment by dnephin** [comment] 2015-11-10 00:07
If that config file didn't raise a validation error, we should fix that

**Comment by nathanleclaire** [comment] 2015-11-10 19:23
Ah, nice point @dnephin.  Yes, I got my keywords mixed up and did mean to use `ports`.  The config file did not raise a validation error as far as I can tell.

**Comment by dnephin** [comment] 2015-11-25 17:09
Closing as duplicate of #2406 since it's already in a milestone.

**Closed by dnephin** 2015-11-25 17:09 UTC
Labels: area/config, kind/bug
