### ISSUE TITLE
"volumes_from" does not support ":ro" suffix

### ISSUE THREAD

**Issue by cu** [docker/compose#1750] opened 2015-07-21 21:49 UTC
Hello,

I have the following container configuration:

```
foodata:
    image: data-volume
    volumes:
        - /var/lib/foo
    comand: true
foobackup:
    image: data-volume
    volumes_from:
        - foodata:ro
```
When I run "docker-compose up", it returns the following error:

```
Service "foo-backup" mounts volumes from "foo-data:ro", which is not the name of a service or container.
```

It looks to me like docker-compose does not understand suffixes in "volumes-from", even though they have been supported in docker itself for a long time. For what it's worth, it appears that the "volumes" command does support suffixes.

**Comment by dnephin** [comment] 2015-07-22 01:25
This is fixed in #1420
Duplicate of #1188

**Closed by dnephin** 2015-07-22 01:25 UTC
