### ISSUE TITLE
`run --volumes` replaces volume configuration rather than adding

### ISSUE THREAD

**Issue by mtibben** [docker/compose#4728] opened 2017-04-12 01:16 UTC
Using [`run --volumes`](https://github.com/docker/compose/pull/4566) replaces all volumes in the docker-compose config.

It would be more useful to me to be able to specify the volumes to mount in addition to the ones in config. Perhaps `--append-volumes` or `--add-volumes`?

**Comment by shin-** [comment] 2017-04-12 20:06
Hi Michael,

By design, the volumes declared in config are never used for `docker-compose run`. The addition of `--volumes` doesn't change anything in that regard.

**Comment by mtibben** [comment] 2017-04-13 00:50
That doesn't seem correct @shin-, `run` does mount volumes:
e.g.
```
$ cat << EOF > docker-compose.yml
version: '2'
services:
  test:
    image: alpine
    volumes:
      - /test
EOF

$ docker-compose run test mount | grep test
/dev/sda1 on /test type ext4 (rw,relatime,data=ordered)
```

**Comment by andyneff** [comment] 2017-05-16 18:22
I have the same problem.

I agree with @mtibben, `docker run` does mount the volumes. Furthermore, I think this is good behavior, and definitely the desired behavior for me and my team. If it did not do this, it would severely limit the usability of docker-compose for us.

Since `--volume` was recently added in 1.12, I would vote for this being a bug.

A simple fix for this would be modifying _get_container_create_options and add

```
        override_options['volumes'] = (container_options.get('volumes', []) +
                                       override_options.get('volumes', []))
```

I like this fix because it lets me add to the volumes, not replace. Furthermore, because of the order, if I is `-v/--volume' to bind to a directory that is already specified in the docker-compose, the `-v/--volume` wins, and the original is not mounted.

**Comment by andyneff** [comment] 2017-05-16 23:27
@mtibben 
As hold over, here is a bash hack you can use to get all the mounts from `docker-compose config`

```bash
function docker-compose-volumes()
{
  local OLD_IFS="${IFS}"
  IFS=$'\n'
  DOCKER_VOLUME_FLAGS=(\
        $(sed -nE '/^services:$/b s; d;
                   :s; n; /^  '"${1}"':$/b f; /^ /b s; d
                   :f; n; /^    volumes:/b v; /^    /b f; d
                   :v; n; /^    -/{H; b v}; x; s|\n    - |\n-v\n|g; p'))
  IFS="${OLD_IFS}"
}

### Test it out ###

cat << EOF > docker-compose.yml
version: '2'
services:
  mytest:
    image: alpine
    volumes:
      - /dev/shm/f o  o:/test_b a  r:ro
      - test:/test_this
      - /test_t e  s   t
volumes:
  test:
EOF

# Run where "mytest" is the name of the service whose volume list you want to extract
docker-compose-volumes mytest < <(docker-compose config)

#Print it out to debug it
declare -p DOCKER_VOLUME_FLAGS

#Use it
docker-compose run "${DOCKER_VOLUME_FLAGS[@]}" -v /tmp:/some_other_test_dir mytest mount | grep test
```
and you should see something similar to

```
declare -a DOCKER_VOLUME_FLAGS='([0]="-v" [1]="/dev/shm/f o  o:/test_b a  r:ro" [2]="-v" [3]="test:/test_this:rw" [4]="-v" [5]="/test_t e  s   t")'

/dev/mapper/mint--vg-root on /test_this type ext4 (rw,relatime,errors=remount-ro,data=ordered)
tmpfs on /test_b\040a\040\040r type tmpfs (ro)
/dev/mapper/mint--vg-root on /some_other_test_dir type ext4 (rw,relatime,errors=remount-ro,data=ordered)
/dev/mapper/mint--vg-root on /test_t\040e\040\040s\040\040\040t type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

So spaces are no problem. As as long as you add your `-v`'s after the `DOCKER_VOLUME_FLAGS`, you can actually override the volumes

**Comment by mtibben** [comment] 2017-05-17 00:55
> Since --volume was recently added in 1.12, I would vote for this being a bug.

I agree @andyneff, it does seem like a bug. The behaviour is different to something like env vars where using the cli options are additive

**Comment by shin-** [comment] 2017-05-17 17:49
Sorry, it looks like I was working off some wrong assumptions here - I apologize. 
Let's follow up on #4830

**Closed** 2017-07-04 00:24 UTC
Labels: area/run, area/volumes, kind/enhancement
