### ISSUE TITLE
building local dockerfile from compose, hits windows max path length error

### ISSUE THREAD

**Issue by traviscooper** [docker/compose#2473] opened 2015-11-29 18:44 UTC
I can build and run containers on windows just fine.  But when including the `build: .` in my `docker-compose.yml`, the build step fails as it hits the max path error that was fixed in `docker`.   

Anyone else encounter the same issue have any workarounds?

**Comment by dnephin** [comment] 2015-11-30 15:34
What is this max path error?  Do you have a link to the docker issue and the PR that fixed it?

If you have a way to reproduce the error, that would be good too.

**Comment by thaJeztah** [comment] 2015-12-25 17:00
max path length in Windows is 260 chars https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx. Prefixing them with `\\?\` enables long paths. I should look for the PR in docker that fixed it

**Comment by dnephin** [comment] 2016-02-26 20:12
Full stack trace from #3026 
```
$ docker-compose.exe build
Building web
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\projects\compose\compose\cli\main.py", line 55, in main
  File "C:\projects\compose\compose\cli\docopt_command.py", line 23, in sys_dispatch
  File "C:\projects\compose\compose\cli\docopt_command.py", line 26, in dispatch
  File "C:\projects\compose\compose\cli\main.py", line 174, in perform_command
  File "C:\projects\compose\compose\cli\main.py", line 195, in build
  File "C:\projects\compose\compose\project.py", line 246, in build
  File "C:\projects\compose\compose\service.py", line 678, in build
  File "c:\projects\compose\venv\lib\site-packages\docker\api\build.py", line 49, in build
  File "c:\projects\compose\venv\lib\site-packages\docker\utils\utils.py", line 103, in tar
  File "c:\python27-x64\Lib\tarfile.py", line 2006, in add
  File "c:\python27-x64\Lib\tarfile.py", line 1878, in gettarinfo
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\ShapeR\\PycharmProjects\\esanum-ng\\src\\frontend\\library\\bower_components\\angular-api-sdk\\node_modules\\grunt-protractor-runner\\node_modules\\protractor\\node_modules\\accessibility-developer-tools\\src\\audits\\its\\FocusableElementNotVisibleAndNotAriaHidden.js'
docker-compose returned -1
```

**Comment by aldarund** [comment] 2016-02-26 21:47
Any chances it getting fixed soon?

**Comment by aldarund** [comment] 2016-03-01 09:59
This basically stop window user to work on nodejs project cause they have long path dependencies..

**Comment by johandavidsen** [comment] 2016-04-06 07:55
A work around for this issue is to remove the packages, which cause the error, from the node_modules folder. The contents of node_modules shouldn't be used in the container.

**Comment by jaygorrell** [comment] 2016-04-24 04:35
Adding node_modules to .dockerignore fixes this for many people.

**Comment by gordienkotolik** [comment] 2016-04-24 07:39
@jaygorrell that's not solution because node_modules content is required for IDE and development on localhost

**Comment by StefanScherer** [comment] 2016-04-24 15:13
@gordienkotolik That's true. But what about compiled dependencies / C bindings? Shouldn't these installed/compiled for Linux inside the Linux container with `RUN npm install`?

But I agree, using `docker-compose.exe` should also work for Windows containers where you can just add the node_modules tree.

**Comment by StefanScherer** [comment] 2016-04-24 15:20
Fixed in Docker Client/Windows Daemon

* Issue in docker/docker
  * https://github.com/docker/docker/issues/15775
* Fixes
  * https://github.com/docker/docker/pull/15898
  * https://github.com/docker/docker/pull/16594

**Comment by jaygorrell** [comment] 2016-04-24 16:00
@gordienkotolik For local development, these are generally bind mounted into the container which works fine, hence the 'many people'. You're right though if you truly need them built into the image locally, this won't work.

**Comment by kristinbaumann** [comment] 2016-06-21 04:58
Hi! I ran in the exact same issue. When I build the container on Windows, the following error message appears and the container is not built.

`WindowsError: [Error 3] The system cannot find the path specified: ...`

I saw the links provided by @StefanScherer with proposed fixes. But I don't understand how I can get my environment running. 

Could anyone please give me a hint?

**Closed** 2018-09-20 01:11 UTC
Labels: group/windows-client
