### ISSUE TITLE
Tag on fig build

### ISSUE THREAD

**Issue by satblip** [docker/compose#974] opened 2015-02-16 17:23 UTC
Hey,

Is there a workaround to tag our image on `fig build`?

Something like `fig build -t xxxxx/yyyyy`?

Thanks!

**Comment by dnephin** [comment] 2015-09-04 16:05
Not yet, duplicate of #213

**Closed by dnephin** 2015-09-04 16:05 UTC

**Comment by satblip** [comment] 2015-09-04 16:11
Thanks for pointing ;)
