### ISSUE TITLE
pyyaml 5.1

### ISSUE THREAD

**Issue by JanneSiren** [docker/compose#6765] opened 2019-06-23 20:11 UTC
ERROR: docker-compose 1.24.0 has requirement PyYAML<4.3,>=3.10, but you'll have pyyaml 5.1 which is incompatible.

**Comment by chris-crone** [comment] 2019-06-28 09:23
Hi @JanneSiren,

Thanks for the report, I believe this is a duplicate of https://github.com/docker/compose/issues/6619.

**Closed by chris-crone** 2019-06-28 09:23 UTC
