### ISSUE TITLE
Shared containers

### ISSUE THREAD

**Issue by andrewmichaelsmith** [docker/compose#657] opened 2014-11-18 15:47 UTC
Similar to #159 but with fig starting the linked container first. You would need some "global id" to indicate that this is a container shared between other fig.ymls.

So I might have:
app1/fig.yml:
```
couchdb:
    global_id: couchdb_database

app:
    links:
        - couchdb
```

app2/fig.yml:
```
couchdb:
    global_id: couchdb_database

app2:
    links:
        - couchdb
```

If I `fig up` app1 then couchdb is started. But If I `fig up` on app2 (after starting app1) then the pre-existing couchdb would be linked to app2.

This basically gets rid of a manual step of launching couchdb that I would have to do it #159

**Comment by dnephin** [comment] 2015-09-18 20:44
I'm going to close this as a duplicate of #318.  I don't think compose should be creating or starting a container that isn't configured as part of the `docker-compose.yml`

**Closed by dnephin** 2015-09-18 20:44 UTC
