### ISSUE TITLE
Variable expansion is broken if compose is installed as a container

### ISSUE THREAD

**Issue by jaycyb** [docker/compose#3091] opened 2016-03-08 08:25 UTC
### To reproduce it:

1- [install docker-compose as a container](https://docs.docker.com/compose/install/#install-as-a-container)

2- create this docker-compose.yml 
```yml
version: "2"

services:
  server: 
    image: phusion/baseimage:0.9.18
    environment:
      - "SSH_AUTH_SOCK=/ssh-agent"
    volumes:
      - "${SSH_AUTH_SOCK}:/ssh-agent"
    command: ssh-add -l
```
3- set the env variable
```bash
$ eval `ssh-agent -s`
Agent pid 20065
$ echo $SSH_AUTH_SOCK
/tmp/ssh-wP1px8LhMut/agent.20064
```

4- Start the container
```bash
$ docker-compose up
WARNING: The SSH_AUTH_SOCK variable is not set. Defaulting to a blank string.
Recreating tmp_server_1
ERROR: create .: volume name invalid: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
```

---

### Hacked solution:

1- Explicitly add the variable to the compose wrapping script...
```bash
$ vi `which docker-compose`
```

Right before the last line `exec docker run ...` , add this

```bash
DOCKER_ADDR="${DOCKER_ADDR} -e SSH_AUTH_SOCK"
```

2- Run again

```bash
$ docker-compose up
Starting 656a5e2528ad_tmp_server_1
Attaching to 656a5e2528ad_tmp_server_1
656a5e2528ad_tmp_server_1 | The agent has no identities.
656a5e2528ad_tmp_server_1 exited with code 1
```
---

I don't know what the proper solution should be but this proves that variable expansion is broken with this installation method.

**Comment by dnephin** [comment] 2016-03-08 15:31
Duplicate of #2613

There is a suggestion in that issue to make it work.

**Closed by dnephin** 2016-03-08 15:31 UTC

**Comment by jaycyb** [comment] 2016-03-09 03:38
Thanks. I wasn't that far off :)  so the current solution is 
```bash
$ export COMPOSE_OPTIONS="-e SSH_AUTH_SOCK"
```

**Comment by masip85** [comment] 2020-09-22 09:55
In fact, it doesn't:
```
WARNING: The SSH_AUTH_SOCK variable is not set. Defaulting to a blank string.
Creating sshforward_server_1 ... error

ERROR: for sshforward_server_1  Cannot create container for service server: create .: volume name is too short, names should be at least two alphanumeric characters

ERROR: for server  Cannot create container for service server: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```
I tried your same example @jaycyb without hacked solution. I've tried also using COMPOSE_OPTIONS inside .env file.

**Comment by uptycs-shivurh** [comment] 2024-02-15 13:33
For me, following worked - 

```
$ echo $SSH_AUTH_SOCK
/tmp/ssh-WNDj8xHE3q/agent.3361061
```

```
]$ printenv | grep SSH_AUTH_SOCK
SSH_AUTH_SOCK=/tmp/ssh-WNDj8xHE3q/agent.3361061
````

* File 
```
version: '2'
services:
  ansible:
    image: IMAGE_ID
    container_name: CONTAINER_NAME
    working_dir: /root/PATH/
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - PATH_FROM_HOST:PATH_AT_CONTAINER:rw
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    tty: true
    stdin_open: true
    command: bash
```
* Build 
```
sudo -E docker-compose up -d
```
* Run 
```
$ sudo docker exec -it CONTAINER_NAME bash
8dba8b31b2e2:~/
```
