### ISSUE TITLE
No output with docker-compose run

### ISSUE THREAD

**Issue by finalclass** [docker/compose#4076] opened 2016-10-26 09:58 UTC
Hey,
I'm running docker at:

```
Docker version 1.12.2, build bb80604
```

and docker-compose at:

```
docker-compose version 1.8.1, build 878cff1
```

I don't see any output (from container) in the console when I run "docker-compose run ..."

To reproduce create this simple **docker-compose.yml**

``` yml
version: '2'
services:
    hello:
        image: 'alpine'
```

run it like that:

```
docker-compose build
docker-compose run hello echo "hello"
```

I've also tried adding -T parameter:

```
docker-compose run -T hello echo "hello"
```

but it doesn't help.

When I run docker without compose then it works fine:

```
docker run alpine echo "hello"
hello
```

**Comment by shin-** [comment] 2016-10-26 20:37
Seems to be working for me:
```
$ docker-compose version
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.4
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
$ docker-compose run hello echo "hello"
hello
$
```

What operating system are you working on?

**Comment by finalclass** [comment] 2016-10-27 06:58
```
[root@fc dd1]# lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
[root@fc dd1]# uname -a
Linux fc 4.8.3-1-zen #1 ZEN SMP PREEMPT Fri Oct 21 09:32:34 UTC 2016 x86_64 GNU/Linux
```

**Comment by djmaze** [comment] 2016-10-31 13:22
Same problem here on Arch Linux. Same Compose version, but newer Docker version:

```
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   6b644ec
```

**Comment by djmaze** [comment] 2016-10-31 13:26
Just tried with the [prebuilt binary](https://docs.docker.com/compose/install/) instead. That's working! So it's probably abou the library version differences in the Arch version:

```
docker-compose version 1.8.1, build 878cff1
docker-py version: 1.10.5
CPython version: 3.5.2
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by rybakit** [comment] 2017-05-17 09:48
Same problem for me:

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 26 (Twenty Six)
Release:        26
Codename:       TwentySix

Docker version 17.05.0-ce, build 89658be
docker-compose version 1.11.2, build dfed245
```
However, I found a workaround - adding `sleep 1` before the actual command does the job:

```
docker-compose run hello sh -c 'echo hello' # no output
docker-compose run hello sh -c 'sleep 1; echo hello' # outputs "hello"
```

**Comment by dylanPowers** [comment] 2017-06-22 21:50
I had this problem when I used pip to install compose. The workaround for me was to install it from the official releases https://github.com/docker/compose/releases. Bummer to not have an easy way to update it :(

**Comment by hubertlepicki** [comment] 2017-06-22 21:54
@dylanPowers dude, that's some good timing. I was just googling this.

**Comment by c24w** [comment] 2017-08-25 14:13
`sleep 0.1` works for me and saves valuable ms of life each time :grin:

**Comment by stefanotorresi** [comment] 2017-08-31 15:17
confirmed on Manjaro Linux, installed via `pip`

```
[0] % lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.0.2
Codename:	Gellivara

[0] % docker-compose -v
docker-compose version 1.15.0, build e12f3b9

[0] % docker -v
Docker version 17.06.1-ce, build 874a7374f3

[0] % uname -msrvo
Linux 4.12.8-2-MANJARO #1 SMP PREEMPT Sun Aug 20 08:24:42 UTC 2017 x86_64 GNU/Linux

[0] % python --version
Python 3.6.2
```

I also fixed by using the binary instead.

**Comment by fogine** [comment] 2018-01-09 14:02
Same problem on Archlinux:

```bash
> uname -a
Linux username 4.14.6-1-ARCH #1 SMP PREEMPT Thu Dec 14 21:26:16 UTC 2017 x86_64 GNU/Linux

> docker-compose version

docker-compose version 1.17.1, build unknown                                                                                                                                                                                                  
docker-py version: 2.6.1
CPython version: 3.6.3
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

> docker version

Client:                                                                                                                                                                                                                                       
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.9.2
 Git commit:   1caf76ce6b
 Built:        Sun Dec 10 10:15:57 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   1caf76ce6b
 Built:        Sun Dec 10 10:16:13 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by ZimbiX** [comment] 2018-01-17 03:02
Playing with a few variations of the sleep time, it seems the terminal connection takes ~40ms, at least on my machine (Arch Linux).

I use this as the base of our entrypoint scripts:

```bash
#!/bin/bash

# Exit on fail
set -e

# There seems to be [a bug with docker-compose on Linux](https://github.com/docker/compose/issues/4076#issuecomment-324932294) where it takes ~40ms to connect to the terminal output of the container, so stuff logged to the terminal in this time is lost. The best workaround seems to be adding tiny delay like so:
sleep 0.1

# Finally call command issued to the docker service
echo 'Starting main command'
exec "$@"
```

**Comment by shin-** [comment] 2018-01-25 00:54
Can you try with 1.19.0 RC1? We shell out to the Docker CLI for run/exec now by default, which should sidestep the issue entirely.

**Comment by ZimbiX** [comment] 2018-01-26 11:11
@shin- Cheers! From some quick testing, this looks resolved :D

```bash
system in kafka-playtime/ on master 
› sudo docker-compose run --rm console sh -c 'echo a'            
Starting kafkaplaytime_zookeeper_1 ... done
Starting kafkaplaytime_kafka_1 ... done

system in kafka-playtime/ on master 
› sudo docker-compose run --rm console sh -c 'sleep 0.04; echo a'
Starting kafkaplaytime_zookeeper_1 ... done
Starting kafkaplaytime_kafka_1 ... done
a

system in kafka-playtime/ on master 
› sudo ./docker-compose run --rm console sh -c 'echo a'          
Starting kafkaplaytime_zookeeper_1 ... done
Starting kafkaplaytime_kafka_1 ... done
a
```

**Comment by shin-** [comment] 2018-01-26 18:30
🎉 

> Just curious - how did it work before instead of shelling out?

We used the API directly, leveraging the [Python SDK](https://github.com/docker/docker-py) and a project called [dockerpty](https://github.com/d11wtq/dockerpty/) that does the work of separating std* streams and I/O to the API socket. Unfortunately, it does struggle in some specific cases (as this issue highlights).

**Closed by shin-** 2018-01-26 18:30 UTC
Labels: area/run, python3
