### ISSUE TITLE
[Feature Request] Better handling of entropy on VPS

### ISSUE THREAD

**Issue by lonix1** [docker/compose#6931] opened 2019-09-29 07:03 UTC
**Problem**
Low entropy on VPSs cause docker-compose to hang for many minutes, for apps to be slow, etc.

Reported many times, including:
- https://github.com/docker/compose/issues/6678
- https://github.com/docker/compose/issues/6552
- https://github.com/docker/compose/issues/6462

*Will probably be reported again many times.*

**Workarounds**
There are two workarounds in those issues and on StackExchange:
- install `haveged` (and [some say](https://security.stackexchange.com/questions/34523/is-it-appropriate-to-use-haveged-as-a-source-of-entropy-on-virtual-machines) it isn't as secure/accurate as widely quoted... worth noting)
- patch `/usr/local/lib/<PYTHON_VERSION>/dist-packages/docker/transport/__init__.py` to [strip out the parts](https://github.com/docker/compose/issues/6552#issuecomment-508124668) that cause the problem

**Solutions**
1. *Please document these workarounds!* It's not a limitation of docker-compose itself, but many people encounter this problem only when using docker-compose. If documented it would avoid lots of wasted time and github issues.

2. The patching approach is ideal for our needs because we don't need that functionality, but it's an ugly hack - *it would be nice to have that as a config option* (i.e. not depend upon python stuff that isn't needed). And that would mean we don't need to remember to patch python on every update.

**Comment by f100024** [comment] 2019-11-15 11:14
Did someone try install `rng-tools`? Seems it helped me.

**Comment by lonix1** [comment] 2019-11-15 12:09
@f100024 The conventional advice is to install `haveged`, which worked for me (though the problems mentioned above still apply). How does `rng-tools` differ?

**Comment by f100024** [comment] 2019-11-15 13:29
I've based on this. https://tails.boum.org/contribute/design/random/

```
HAVEGE reliability
haveged relies on the RDTSC instruction, that apparently is useless in some virtualized environments. Also, the quality of random numbers output by HAVEGE is unclear, and the topic of many discussions.
Further research on this topic is left to be done.
This is why Tails also ships rngd. Still, it is not clear how these two daemons act together.

Hardware RNG trustworthiness and availability
It is not clear how much one can trust a hardware RNG, that is hard, if not impossible, to audit. Also, not all computers include a hardware RNG.
This is why Tails also ships HAVEGE. Still, it is not clear how these two daemons act together.
```

To check if your system have hardware random number generator(RNG). This should return something, otherwise try install `haveged`.
```
  grep -F -e rdseed -e rdrand /proc/cpuinfo
```

Installation:
```
$ sudo apt update && apt install rng-tools
```
In some cases rng-tools returned error:
```
...
Oct 26 04:11:02 ubuntuvps rng-tools[299]: /etc/init.d/rng-tools: Cannot find a hardware RNG device to use.
...
```
Added rng-device and restart daemon.
```
# echo "HRNGDEVICE=/dev/urandom" >> /etc/default/rng-tools && systemctl restart rng-tools.
```

**Comment by l3ender** [comment] 2019-11-15 22:24
I seem to be experiencing the same issues on my Mac using Docker Desktop. Is there any workaround?

**Comment by lonix1** [comment] 2019-11-16 07:59
@l3ender Not sure about mac, but look at the workarounds in the OP... and try `haveged`.

**Comment by mmlr** [comment] 2020-02-14 23:05
I've run into this on a VPS and wanted to use jitterentropy-rngd as suggested in the libsodium documentation (https://libsodium.gitbook.io/doc/usage#sodium_init-stalling-on-linux). There indeed was no package for my host system available, so I put it into a container instead. I've made a pull-request for jitterentropy-rngd with which one can just clone the repo and `docker-compose up -d` to have this solved: https://github.com/smuellerDD/jitterentropy-rngd/pull/10

**Comment by SlavikCA** [comment] 2020-05-27 06:48
Running docker-compose on VPS on Azure.
Ubuntu 20.04

Entropy looks good:
```
root@ub20azure:/home/slavik# cat /proc/sys/kernel/random/entropy_avail
3868
```

`haveged` is installed.

Can't do the python patch, because I don't have files mentioned:
```
root@ub20azure:/home/slavik# ls -l /usr/local/lib/python3.8/dist-packages/
total 0
```
Am I looking at the wrong place for python files?
Anything else I can do?

**Comment by poggdogg** [comment] 2020-06-15 17:05
I noticed that when changing the context to a higher directory that the build times change.  It looks like docker-compose does a recursive search and/or caching of all directories based on the context dir.  IE:
`root
- dir1 
- dir2
- dir3`
If all the files are in dir3 (including dockerfile) and we're setting the context as root and pathing to dir3 to build it still takes a much longer time than if we are to change context to dir3. 

This is unfortunate because if we need to copy artifacts from other directories then performance takes a hit.

**Comment by immanuelfodor** [comment] 2020-12-12 19:26
unstale

**Comment by lonix1** [comment] 2021-06-11 08:10
not stale
still a major issue

**Comment by phillip-elm** [comment] 2021-07-05 06:04
Yeah this is particularly nasty as even `--version` and `ps` hang with no reason given. SIGINT doesn't always break out of the app either, I've had to kill it by PID a few times. This behaviour makes debugging very difficult, especially in scripts.

It sounds to me like this might not be something easily fixed, as these issues date back to as late as 2019. Perhaps a few workarounds could be implemented to make this easier for people until a long-term solution can be implemented?

Some that come to mind include:

1. Show a warning if the offending method takes more than a second or two, explaining why it's delayed.
2. Ensure that SIGINT actually works when Compose is in this state.
2. Have a reasonable and/or configurable timeout where the process terminates if the initialisation takes too long.
3. I'm not aware of the internals of compose, but perhaps Compose could defer calling the offending method until it's needed, if at all, so that commands like `--version` always work.

**Comment by lonix1** [comment] 2022-01-04 02:54
!stale

**Comment by lonix1** [comment] 2022-07-10 13:44
not stale

**Comment by artursudnik** [comment] 2023-06-18 13:41
I have never faced this issue anymore after starting using `docker compose`

**Comment by ndeloof** [comment] 2023-08-07 08:44
I'm closing this issue as obsolete: Docker Compose V1 has reached end-of-life and we are not accepting any more changes. Please try and reproduce your issue with Compose V2 and create a new issue or PR with the relevant Compose V2 information.

**Closed by ndeloof** 2023-08-07 08:44 UTC
Labels: Docker Compose V1

**Comment by dgtlmoon** [comment] 2023-11-23 11:00
+1 confirmed here `docker compose` works way better, no more delays when starting a huge docker-compose.yml projects

`docker-ce 5:24.0.7-1~ubuntu.22.04~jammy`
`docker-compose-plugin 2.21.0-1~ubuntu.22.04~jammy`

I tried all the fixes for entropy/haveged etc etc but in the end `docker compose` wins over `docker-compose`
