### ISSUE TITLE
env_file interpolation broken in compose v2

### ISSUE THREAD

**Issue by jakeberesford-palmetto** [docker/compose#8980] opened 2021-11-30 15:45 UTC
In many of our containerized applications, we use interpolation of env vars in the env_file to read environment variables set on the host machine. This allows our developers to set common environment variables once, and use them across different projects with minimal setup. When upgrading to docker compose v2.x we noticed that these interpolated environment variables no longer work. 

If we move those interpolated environment variables into the `environment` configuration in the compose file they work as expected. We will likely migrate to this implementation. However, I'm sure others will experience the same issue.

I have not seen release notes, open issues, or documentation around this specific bug.

**Steps to reproduce the issue:**
1. clone the minimal reproduction repo here: https://github.com/jakeberesford-palmetto/docker-compose-env-var-bug
2. export an environment variable in your shell `echo "\nexport SHELL_FOO='foo'" >> ~/.zshrc && . ~/.zshrc`
3. Run the container, grep for "FOO_VAR"

**Describe the results you received:**
`FOO_VAR=`

**Describe the results you expected:**
`FOO_VAR=foo`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version v2.1.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 21
  Running: 0
  Paused: 0
  Stopped: 21
 Images: 1
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: SWAN:UOAI:KBDX:4XDI:I5YC:D2VH:AHTD:4Q55:VJP4:IZGN:3JUB:2DWZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**

**Comment by bkuhl** [comment] 2021-12-08 18:25
This is a duplicate of https://github.com/docker/compose/issues/8799

**Comment by ndeloof** [comment] 2021-12-09 07:26
not a duplicate, same area but distinct issue

**Comment by ndeloof** [comment] 2021-12-09 07:28
tested with docker compose 2.2, seems issue has been fixed in the meantime

```
docker-compose-env-var-bug docker-compose up
[+] Running 1/0
 ⠿ Container docker-compose-env-var-bug-env_var_test-1  Created            0.0s
Attaching to docker-compose-env-var-bug-env_var_test-1
docker-compose-env-var-bug-env_var_test-1  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
docker-compose-env-var-bug-env_var_test-1  | HOSTNAME=93f233e9610e
docker-compose-env-var-bug-env_var_test-1  | FOO_VAR=foo
docker-compose-env-var-bug-env_var_test-1  | HOME=/root
docker-compose-env-var-bug-env_var_test-1 exited with code 0
```

**Closed** 2022-01-21 13:24 UTC
Labels: Docker Compose V2
