### ISSUE TITLE
Provide RPM and DEB packages for compose

### ISSUE THREAD

**Issue by dnephin** [docker/compose#2235] opened 2015-10-21 15:40 UTC
Not everyone likes to install binaries (#1288).

It might be good to provide a system package for compose. We should use https://github.com/spotify/dh-virtualenv for the debian package and look into a similar approach for the rpm.

**Comment by jacek99** [comment] 2015-10-21 15:45
I would recommend to just work with the respective Debian and Fedora/CentOS communities and get that rolled into the default system repositories.'

Just my $0.02

**Comment by atrauzzi** [comment] 2015-10-27 02:09
That ends up being less than optimal for a project that's moving as quickly as compose.  You'll just end up with a pile of people coming in reporting that new features aren't working.

Better to have a PPA so that you can do updates outside of the distro release cycle.

**Comment by dnephin** [comment] 2015-10-27 18:51
It sounds like there is a deb for it (https://packages.debian.org/sid/docker-compose) but it's already a few versions behind.

**Comment by dnephin** [comment] 2015-10-27 18:54
And a fedora package https://admin.fedoraproject.org/pkgdb/package/docker-compose/

**Comment by voltagex** [comment] 2015-10-31 00:23
Couldn't this be done in the same way as https://docs.docker.com/installation/ubuntulinux/ and https://docs.docker.com/installation/fedora/? i.e. host on *.docker.org

**Comment by dnephin** [comment] 2015-11-02 15:56
Hosting the packages is the easy part. Most of the work here is making sure the package works for older versions of distros.

**Comment by athyuttamre** [comment] 2016-01-27 00:39
Would you consider doing this once development pace has stabilized?

**Comment by StefanScherer** [comment] 2016-01-27 07:44
What about putting the docker-compose binary that is also available at the GH release into DEB/RPM?
No python/virtualenv required on the target machine.

Creating such a package with [fpm](https://github.com/jordansissel/fpm) should be very easy. We've done similar things at work (sorry private repos) and put some integration tests behind the build to test the DEB/RPM package at CircleCI within debian/centos Docker containers.

If there is interest in such things I can check if we can open source that parts as an example.

**Comment by alexanderadam** [comment] 2016-02-12 11:31
I totally agree that it would nice to have it packaged but for ubuntu I don't think it's useful to add another PPA. I would rather like to see current docker compose [in the already existing repository](https://docs.docker.com/engine/installation/linux/ubuntulinux/#update-your-apt-sources).

@dnephin apt repositories can have different packages per distribution anyway and as the other docker packages are already included it even should be easier to manage that compose and docker work nicely together.

Therefore I think providing automatic builds for the official docker repos should be in focus here (and not creating *additional* repositories).

**Comment by atrauzzi** [comment] 2016-02-14 16:39
@alexanderadam That's a good way to get outdated bug reports.  A PPA makes much more sense for a target that moves as quickly as docker+compose.

Indeed that's why people prefer to use the docker PPA.  What's in the ubuntu/debian repos just doesn't keep pace.

**Comment by mkantor** [comment] 2016-05-15 04:40
@atrauzzi unless I'm misreading, @alexanderadam is suggesting to host release builds of docker-compose in the docker repository (https://apt.dockerproject.org/), not rely on the the ubuntu/debian packagers.

**Comment by atrauzzi** [comment] 2016-05-15 11:33
Good enough! :)

**Comment by ksylvan** [comment] 2016-08-16 17:12
There is also this possibility. Run this shell script as `docker-compose`:

```
#!/bin/sh

if [ -t 0 ]; then OPTS='-it'; fi

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
       -v "$(pwd):$(pwd)" -w "$(pwd)" \
       $OPTS dduportal/docker-compose:latest ${1+"$@"}
```

**Comment by franklinyu** [comment] 2016-08-17 05:07
@ksylvan Why `${1+"$@"}` instead of just `"$@"`?

**Comment by Gaff** [comment] 2016-09-20 15:35
Also `docker-machine` while you're working on it?

**Comment by nevergone** [comment] 2016-10-27 07:53
What would there be need for in order for the solution of the issue to go on?

**Comment by alexanderadam** [comment] 2016-10-27 09:30
I doubt that anybody from the Docker team had a look on it.

@fsateler, in case you are the packager of the Debian package: is there anything particular to think of when packaging `docker-compose` as an Debian package (sorry for mentioning).

**Comment by fsateler** [comment] 2016-10-27 13:06
@alexanderadam yes, I am the downstream maintainer. I would of course be delighted to have help maintaining the debian package, but if you want to maintain an out-of-band package that is fine too.

If you go the out-of-band way, please consider the following:

1. Packages from such repositories should work with multiple releases (usually debian and ubuntu, in their various releases).
2. This means relying on distro-provided packages is harder. For example, a required version of a python module might not yet be available.
3. Care should be taken to not step over distro-provided packages (that is, overwrite a module with a newer version).

The linked dh-virtualenv above looks like it addresses the above three problems by shipping the complete venv into `/opt`. All that should be required then is to use the oldest supported disro release to build the packages, this seems a requirement of dh-virtualenv.

The alternative would be to have multiple repositories for the different releases, but that would be IMO much more trouble than it is worth.


PS: yes, the debian package is a bit behind, but that is mostly resolved, hopefully (we have now 1.8.0). We were stuck a while waiting for newer versions of some dependent modules.

**Comment by gyszalai** [comment] 2016-10-28 08:55
I think providing a snap or flatpak package could solve the dependency issues. Opinions?

**Comment by jasonmp85** [comment] 2017-02-23 22:14
So why isn't there already at least just a package with the binary in it? After poking around how exactly this binary is generated, it appears it's dynamically linked, so I guess there are concerns about breaking compatibility with older distros, but right now your "upgrade" steps are basically "blast over the old binary and hope it works", so I don't particularly see that as any sort of regression (i.e. the dependencies aren't specified as-is, and neither are compatible distros, so slapping the binary into a package would be no worse than the current scenario, and in some ways actually better, since it permits users to install `docker` and `compose` in one line rather than two separate ways).

I guess `compose` is kind of a dev tool in the first place, but it would be nice to see a better install story.

**Comment by alexanderadam** [comment] 2017-02-24 10:31
> So why isn't there already at least just a package with the binary in it?

@jasonmp85 just to clear this up: as [mentioned earlier](https://github.com/docker/compose/issues/2235#issuecomment-256635059) **there** [**are actually** packages](https://packages.debian.org/sid/main/docker-compose) and [fsateler (maintainer of the current Debian packages) wrote](https://github.com/docker/compose/issues/2235#issuecomment-256635059) that he would be more than happy if someone could support him maintaining these packages. And if you _don't need_ the latest Docker binaries you will be probably fine if you just use them together with the Docker binaries provided by your Distro (and you get security updates via your package manager as well).

However, there are a bunch of good reasons to prefer the _current_ version of Docker. Which is is most probably the reason the Docker people [created a PPA and wrote that you should use it](https://docs.docker.com/engine/installation/linux/ubuntu/). But docker-compose is missing here.

**Comment by franklinyu** [comment] 2017-02-24 14:28
Note: the Debian package is [already in stretch](https://packages.debian.org/stretch/docker-compose), the next release, and it has been in Ubuntu [since Xenial](http://packages.ubuntu.com/xenial/docker-compose). Being easy to update is more important than cool new functionality to me, so it being un-APT-able stops me from using the latest version.

**Comment by kfiresmith** [comment] 2017-04-07 00:07
+1 for a Compose RPM in the Docker Inc CentOS repos.  

As a new user of Docker CE I had assumed that compose was in the main RPM when I saw that there were only the two rpms (docker-ce, docker-ce-selinux) in the CentOS repo.  Had to google around to find this page and get caught up on the state of this.

**Comment by carlwgeorge** [comment] 2017-07-05 21:24
docker-compose is now available in the EPEL repository for RHEL/CentOS 7.  I was limited to version 1.9 because Red Hat only ships the Python SDK 1, and [newer versions require SDK 2](https://github.com/docker/compose/commit/04e5925a230d07a6ffd855b4c3812f5a6b54a523).  If at some point in the future Red Hat updates that to SDK 2, I can update docker-compose to a newer version.  For now, that version is compatible with compose file format 2.2, which is compatible with both the docker 1.12.6 and docker-latest 1.13.1 packages from the distribution.

**Comment by Toub** [comment] 2017-08-12 07:48
Would be nice to add compose to docker-ce in official debian repository: https://download.docker.com/linux/debian

**Comment by debrouxl** [comment] 2017-09-23 07:57
I also think it would be nice to add a docker-compose package into the official Debian repository :)

**Comment by francislavoie** [comment] 2017-09-28 05:59
As @Toub said, I wish compose was included with `docker-ce`. I went looking here: https://download.docker.com/linux/ubuntu/dists/xenial/stable/ to see if it was included, and it still isn't. The release notes say for Windows and Mac, Compose is included. Why not Linux? It's about time Docker, the _Linux_ tool, gets proper package updates for people running this on servers. It's stupid to have to maintain a separate script to keep Compose versions in line on production servers.

**Comment by ksylvan** [comment] 2017-09-29 17:53
I just use the shell script which runs `docker-compose` in a container.

**Comment by franklinyu** [comment] 2017-09-30 14:03
@ksylvan That's more like a workaround than a solution…

**Comment by alexanderadam** [comment] 2017-10-02 08:40
@ksylvan the idea of package managers is that you are [able to manage (ie. upgrade) your packages at once and having dependencies that match to each other](https://github.com/docker/compose/issues/2235#issuecomment-282258927). _Manual_ solutions (including yours) won't be able to enable this.

**Comment by hackel** [comment] 2019-03-08 19:08
Docker-compose desperately needs an official snap package.  It's cross-platform, encapsulates all dependencies, gives you automatic upgrades, and is just set it and forget it.  As a developer, having to remember to come manually check if any new versions have been released and manually install them is just silly.  Maintaining separate deb/rpm/whatever packages for each version of a distribution is extra work no one needs.

**Comment by kfiresmith** [comment] 2019-03-08 19:14
>  Maintaining separate deb/rpm/whatever packages for each version of a distribution is extra work no one needs.

There are lots of operating environments that cannot use a 3rd party package manager such as Snap due to policy controls.  Without going into too much detail, think GOVT sites, etc...
So while snaps are great for independent devs and other freewheeling environments, they are not an actual replacement to OS-native/Distro-native packages such as .deb/.rpm.

**Comment by sweepyoface** [comment] 2019-03-27 13:39
> > Maintaining separate deb/rpm/whatever packages for each version of a distribution is extra work no one needs.
> 
> There are lots of operating environments that cannot use a 3rd party package manager such as Snap due to policy controls. Without going into too much detail, think GOVT sites, etc...
> So while snaps are great for independent devs and other freewheeling environments, they are not an actual replacement to OS-native/Distro-native packages such as .deb/.rpm.

How about both? :stuck_out_tongue:

\---

For anyone looking to use this:

> There is also this possibility. Run this shell script as `docker-compose`:
> 
> ```
> #!/bin/sh
> 
> if [ -t 0 ]; then OPTS='-it'; fi
> 
> docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
>        -v "$(pwd):$(pwd)" -w "$(pwd)" \
>        $OPTS dduportal/docker-compose:latest ${1+"$@"}
> ```

the dduportal/docker-compose image hasn't been updated since `1.12.0`, and there is now an official compose image.

Use this instead (requires `jq` to be installed, or alias `jq` to also run with docker):

```sh
#!/bin/sh

if [ -t 0 ]; then OPTS='-it'; fi

latest=$(curl https://registry.hub.docker.com/v2/repositories/docker/compose/tags/ | jq -r '.results[0].name')

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
       -v "$(pwd):$(pwd)" -w "$(pwd)" \
       $OPTS docker/compose:"$latest" ${1+"$@"}
```
Note that this includes release candidate versions.

**Comment by FranklinYu** [comment] 2019-10-10 04:33
I would say let's close it since Docker team clearly isn't interested given that we don't hear from them for more than 3 years. Community cannot do anything because we don't control the repository. We have enough workaround above.

**Comment by cefn** [comment] 2020-02-27 06:22
For reference, following the most recent suggestion from @sweepyoface in https://github.com/docker/compose/issues/2235#issuecomment-477158800 on my system at least, access to /var/run/docker.sock requires sudo 

Without prefixing the docker-compose command with sudo...

```
$ /home/cefn/.local/bin/docker-compose --help
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```

**Comment by oxydaemon** [comment] 2020-02-27 06:36
> For reference, following the most recent suggestion from @sweepyoface in [#2235 (comment)](https://github.com/docker/compose/issues/2235#issuecomment-477158800) on my system at least, access to /var/run/docker.sock requires sudo
> 
> Without prefixing the docker-compose command with sudo...
> 
> ```
> $ /home/cefn/.local/bin/docker-compose --help
> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
> See 'docker run --help'.
> ```

You shouldn't need sudo, that is permission denied error to docker.sock.
Assuming you're running as user 'cefn', did you add that user to the docker group in /etc/group?

username@myserver:~$ ls -l /var/run/docker.sock 
srw-rw---- 1 root docker 0 Feb 27 14:33 /var/run/docker.sock

docker group members have read and write permissions

**Comment by cefn** [comment] 2020-02-27 07:19
> I switch to installing with `pip` within a [`venv`](https://docs.python.org/3/library/venv.html), and aliasing `docker-compose` to the binary within that `venv` ... it depends only on [`python3-venv`](http://packages.ubuntu.com/xenial/python3-venv).

The alternative https://docs.docker.com/compose/install/ under 'Alternative Install Options' is even simpler, and doesn't rely on python3-venv either...

`sudo pip install docker-compose`

Unfortunately 'Alternative Install Options' is set against tabs for 'Windows, Mac OS, Linux'. The Linux tab contains only curl-based instructions, (which swing free from software repositories or updates). 

I'd personally like to see 'install Pip' then 'pip install docker-compose' under the Linux tab. However, perhaps hiding the pip approach as an 'Alternative Install' is to avoid having to provide multi-os guidance [how to install pip](https://vgkits.org/blog/install-pip3-on-linux/).

**Comment by HMSCelestia** [comment] 2020-08-27 21:06
Unstale this.

**Comment by francislavoie** [comment] 2021-02-23 23:10
Unstale this, again.

**Comment by velovix** [comment] 2021-05-26 04:43
That is encouraging, but do we know yet if there are plans to include this on Linux by default after this gets past the preview? It appears to be included in edge releases for Windows and Mac, but not Linux. If you want to install it currently, you have to run a shell script.

**Comment by MAFLO321** [comment] 2021-12-01 16:38
is connected to #8011

**Comment by MAFLO321** [comment] 2022-03-11 05:56
I think this can be closed:
- https://docs.docker.com/engine/release-notes/#201013
- https://github.com/docker/docker-ce-packaging/pull/638

**Comment by thaJeztah** [comment] 2022-03-11 10:33
Yes! Let's close this

(additional documentation changes still to follow)

**Closed by thaJeztah** 2022-03-11 10:33 UTC
Labels: status/0-triage, area/packaging
