### ISSUE TITLE
Running `docker-compose run` from different shell scripts in same folder can lead to race condition leading to error & abort

### ISSUE THREAD

**Issue by JonasT** [docker/compose#5240] opened 2017-10-06 11:56 UTC
Running `docker-compose run` from different shell scripts in same folder can lead to race condition leading to error & abort:

```
ERROR: Cannot create container for service hermes: b'Conflict. The container name "/dockerbug150728952675791742_hermes_run_216" is already in use by container "7d3242d7020a3849afef92010eec6f1c515f80abf9a9a62018180e43a20c8514". You have to remove (or rename) that container to be able to reuse that name.'
```

Since this impacts the ability to use docker-compose from automated scripts, it would be nice if this special case could be somehow caught and resolved automatically in a way that avoids that error.

**Comment by shin-** [comment] 2017-10-06 19:02
Duplicate of #4688

**Closed by shin-** 2017-10-06 19:02 UTC
