### ISSUE TITLE
Networking strange behavior

### ISSUE THREAD

**Issue by Prevole** [docker/compose#1192] opened 2015-03-26 15:31 UTC
Hi there,

I recently installed the version 1.2.0rc1. I have a nodejs application that will poll an API every five minutes.

The docker-compose.yml is the following

```yaml
publibike:
  image: softengheigvd/iflux-publibike-event-source:v0.1.0
  env_file: ./.env
```
This is something really light and working well with 1.1.0.

But with the version 1.2.0rc1, I was not able to make the network working. I mean the polling process cannot reach the Internet from the container. I tried to run my image manually with Docker and it works. I tried to use net: bridge in the docker-compose file without effect.

Then I also tried to use net: host, with this config, it worked.

Do I miss something in the configuration somewhere ? At the moment, I reinstalled Compose version 1.1.0 and it works like a charm for what I need.

Thanks

**Comment by StevenWeathers** [comment] 2015-03-26 16:51
I'm having similar issues where I'm doing a proxy in nginx to an external host (example google.com), and it worked fine with 1.1.0 but with 1.2.0rc1 it's failing to reach the external host.

Was looking forward to using extends but I'll have to wait.

**Comment by aanand** [comment] 2015-03-26 17:46
This may be because of a DNS regression (#1172) that's been fixed in RC2:

https://github.com/docker/compose/releases/tag/1.2.0rc2

**Comment by aanand** [comment] 2015-03-26 17:48
@StevenWeathers If you're still seeing the problem with RC2, could you `docker inspect` the failing container and paste the output here?

**Comment by StevenWeathers** [comment] 2015-03-26 18:03
@aanand Actually my mistake, I had 1.2.0rc1 installed, just tried with rc2 and it's working fine again.

-Thanks!

**Comment by josephpage** [comment] 2015-03-26 19:31
Just updated from 1.2.0rc1 to 1.2.0rc2, it was failing too, and it's OK for me now.

**Comment by Prevole** [comment] 2015-03-27 09:16
I updated to version 1.2.0rc2 and it solved my issue.

**Comment by thaJeztah** [comment] 2015-03-30 21:47
I think this issue can be closed (given the above responses)?

**Closed** 2015-03-31 13:42 UTC
