### ISSUE TITLE
Docker-compose rejects windows style volume mappings

### ISSUE THREAD

**Issue by NCarlsonMSFT** [docker/compose#3897] opened 2016-08-31 23:03 UTC
When building windows containers a compose file like:

```
foo:
    image: windowsservercore
    volumes:
        - C:\foo:C:\bar:ro
```
Results in the error:
ERROR: Volume c:\foo:c:\bar:ro has incorrect format, should be external:internal[:mode] 

But if I call docker directly with "docker run -v C:\foo:C:\bar:ro windowsservercore" it is accepted as expected.

**Comment by friism** [comment] 2016-08-31 23:05
cc @dgageot

**Comment by NCarlsonMSFT** [comment] 2016-08-31 23:09
FYI if I use "/C/Foo:/C/Bar:ro" instead the error is:

ERROR: for foo  Invalid volume spec "/C/Bar": Invalid volume specification: '/C/Bar'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1

**Comment by shin-** [comment] 2016-08-31 23:17
@NCarlsonMSFT I think you're using an older version of compose, can you try upgrading to 1.8.0?

**Comment by shin-** [comment] 2016-08-31 23:19
It's a duplicate of #2487, which we fixed in 1.8.

**Comment by NCarlsonMSFT** [comment] 2016-08-31 23:26
I was on an older build, I switched to "docker-compose version 1.8.0, build d988a55" and am still getting the errors

**Comment by shin-** [comment] 2016-08-31 23:28
Can you share the full output of `docker-compose --verbose config`?

**Comment by NCarlsonMSFT** [comment] 2016-08-31 23:32
```
PS > docker-compose --verbose config
compose.config.config.find: Using configuration files: .\docker-compose.yml
ERROR: compose.cli.main.main: Volume C:\Foo:C:\Bar:ro has incorrect format, should be external:internal[:mode]
```

**Comment by NCarlsonMSFT** [comment] 2016-08-31 23:37
Interestingly if I run `docker-compose --verbose config` on the v2 equivalent of the file that succeeds:
```
compose.config.config.find: Using configuration files: .\docker-compose.yml
networks: {}
services:
  foo:
    image: windowsservercore
    volumes:
    - /c/Foo:C:\Bar
version: '2.0'
volumes: {}
```

**Comment by PatrickLang** [comment] 2016-09-02 01:36
here's another variation:

I created a directory and file on the host:
```none
PS C:\compose1> ls ~/shared


    Directory: C:\Users\vagrant\shared


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         9/1/2016   5:37 PM             16 hello.txt
```

And here's the docker-compose.yml:
```none
PS C:\compose1> cat .\docker-compose.yml
version: '2'
services:
  shell:
    image: microsoft/windowsservercore
    tty: true
    network_mode: "none"
    volumes:
      - ~/shared:/c/shared
```

It parsed ok:
```none
PS C:\compose1> docker-compose --verbose config
compose.config.config.find: Using configuration files: .\docker-compose.yml
networks: {}
services:
  shell:
    image: microsoft/windowsservercore
    network_mode: none
    tty: true
    volumes:
    - /c/Users/vagrant/shared:/c/shared:rw
version: '2.0'
volumes: {}
```

But failed to run:
```none
PS C:\compose1> docker-compose up -d
Creating compose1_shell_1

ERROR: for shell  Cannot create container for service shell: Invalid volume spec "/c/shared": Invalid volume specification: '/c/shared'
ERROR: Encountered errors while bringing up the project.
```

**Comment by shin-** [comment] 2016-09-08 17:25
Thank you for providing more details. I think I identified what the problem is and will be working on a fix.

**Closed** 2016-09-20 20:09 UTC
Labels: area/volumes, group/windows-client, kind/bug

**Comment by friism** [comment] 2016-10-09 01:56
@PatrickLang did you verify whether this solved your problem? I suspect it didn't...

**Comment by StefanScherer** [comment] 2016-10-09 09:10
No, it still doesn't work with docker-compose 1.8.1

**Comment by friism** [comment] 2016-10-11 21:38
New build available: https://ci.appveyor.com/project/docker/compose/build/master-2420/artifacts

**Comment by StefanScherer** [comment] 2016-10-11 21:57
Quick test:

```
C:\Users\vagrant\test> mkdir c:\shared
C:\Users\vagrant\test> cat .\docker-compose.yml
version: '2'
services:
  shell:
    image: microsoft/windowsservercore
    tty: true
    network_mode: "none"
    volumes:
      - c:\shared:c:\shared
```

Test with docker-dompose 1.8.1:

```
C:\Users\vagrant\test> docker-compose up -d
Creating test_shell_1

ERROR: for shell  Cannot create container for service shell: invalid volume spec "/c/shared": invalid volume specification: '\c\shared'
[31mERROR[0m: Encountered errors while bringing up the project.
```

Downloading artifact and testing again:

```
C:\Users\vagrant\test> wget -outfile docker-compose.exe https://ci.appveyor.com/api/buildjobs/mjk334rrdx7p591d/artifacts/dist%2Fdocker-compose-Window
s-x86_64.exe
C:\Users\vagrant\test> .\docker-compose.exe up -d
[33mWARNING[0m: The COMPOSE_CONVERT_WIN32_PATHS variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 62, in main
  File "compose\cli\main.py", line 114, in perform_command
  File "compose\cli\main.py", line 835, in up
  File "compose\project.py", line 372, in up
  File "compose\project.py", line 539, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 33, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\client.py", line 139, in _get
  File "site-packages\requests\sessions.py", line 477, in get
  File "site-packages\requests\sessions.py", line 465, in request
  File "site-packages\requests\sessions.py", line 573, in send
  File "site-packages\requests\adapters.py", line 370, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 374, in _make_request
  File "httplib.py", line 1133, in getresponse
  File "httplib.py", line 390, in __init__
  File "site-packages\docker\transport\npipesocket.py", line 99, in makefile
ValueError: buffer size must be strictly positive
docker-compose returned -1
```

**Comment by shin-** [comment] 2016-10-11 22:07
@StefanScherer Thank you for testing. What does it say when you run `.\docker-compose.exe version`?

**Comment by StefanScherer** [comment] 2016-10-11 22:10
@shin- 
```
C:\Users\vagrant\test> .\docker-compose.exe --version
docker-compose version 1.9.0dev, build 31904b7
```

**Comment by StefanScherer** [comment] 2016-10-11 22:12
And now without double dashes:

```
C:\Users\vagrant\test> .\docker-compose.exe version
docker-compose version 1.9.0dev, build 31904b7
docker-py version: 1.10.3
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by shin-** [comment] 2016-10-11 22:14
@StefanScherer Thanks - looks like we still have some challenges with named pipe support. In the meantime you can work around this by connecting via TCP using the `DOCKER_HOST` environment variable.

**Comment by StefanScherer** [comment] 2016-10-11 22:21
@shin- Thanks! Yes, setting `DOCKER_HOST` to TCP works.

But colored output in PowerShell also needs some care:

<img width="1204" alt="bildschirmfoto 2016-10-12 um 00 19 17" src="https://cloud.githubusercontent.com/assets/207759/19290784/a788c86e-9011-11e6-8922-60ae747aec84.png">

**Comment by shin-** [comment] 2016-10-11 22:23
@StefanScherer Thank you!

And agreed re: coloring. I think we have an issue open for that.

**Comment by realtebo** [comment] 2017-01-24 16:59
Same issue on windows 7.

My intent is to copy the content of dir `C:\Users\realtebo\Downloads\new\actual-wordpress\www` into `/var/www/html`

My docker-compose.yaml section 

```
 wordpress:
    container_name: wordpress
    image: php:5.5-apache
    volumes:
      - ./www/:/var/www/html
```


About docker-compose itselfs:
```
$ docker-compose --version
docker-compose version 1.9.0, build 2585387
```

The error:
```

ERROR: for wordpress  Cannot create container for service wordpress: Invalid bin
d mount spec "C:\\Users\\mirko.PHONIX\\Downloads\\new\\www:/var/www/html:rw": In
valid volume specification: 'C:\Users\realtebo\Downloads\new\www:/var/www/ht
ml:rw'
←[31mERROR←[0m: Encountered errors while bringing up the project.
```

I'm on Windows 7, so no PowerShell. My cli is inside MINGW64. 

what can I do?

**Comment by shin-** [comment] 2017-01-24 19:48
@realtebo Please update to docker-compose 1.10

**Comment by realtebo** [comment] 2017-01-25 08:14
@shin- How ? 

I just visited https://www.docker.com/products/docker-toolbox to re-install docker, but after a succesfull installation I got ... 

```
$ docker-compose --version
docker-compose version 1.9.0, build 2585387
```

Same identical build

**Comment by realtebo** [comment] 2017-01-25 08:23
@shin- : same identical error with docker-compose 1.10

**Comment by realtebo** [comment] 2017-01-25 08:33
For love of documenting and debugging, I tried to change declaration in the yaml file as is:

    volumes:
      - /c/Users/realtebo/Downloads/new/actual-wordpress/www:/var/www/html

And error is changed:

> ERROR: for wordpress  Cannot create container for service wordpress: create \c\U
> sers\realtebo\Downloads\new\actual-wordpress\www: "\\c\\Users\\realtebo\
> \Downloads\\new\\actual-wordpress\\www" includes invalid characters for a local
> volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
> ERROR: Encountered errors while bringing up the project.

**Comment by realtebo** [comment] 2017-01-30 13:27
@shin: any news on a new patch for windows users?

**Comment by shin-** [comment] 2017-01-30 20:08
@realtebo You say you're on Win7, I assume that means you're working with Docker Machine? If so, did you enable the `COMPOSE_CONVERT_WINDOWS_PATHS` environment variable? [See docs here](https://docs.docker.com/compose/reference/envvars/#/composeconvertwindowspaths)

**Comment by realtebo** [comment] 2017-01-31 08:40
@shin- : I created a `.env` file inside the same folder of `docker-compose.yml`.

This is the actual content of the file

    $ cat .env
    COMPOSE_CONVERT_WINDOWS_PATHS=1

This is actual version of docker-machine

    $ docker-machine version
    docker-machine.exe version 0.8.2, build e18a919
    
I asked to print environment vars set, but I canno see my new setting. 

```
$ docker-machine env
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="C:\Users\realtebo\.docker\machine\machines\default"

export DOCKER_MACHINE_NAME="default"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env)
```

What's wrong now ?
