### ISSUE TITLE
compose file dns has problem.

### ISSUE THREAD

**Issue by woshihaoren** [docker/compose#2529] opened 2015-12-10 08:53 UTC
# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

  # docker-compose version
docker-compose version 1.6.0dev, build 0fedd99
docker-py version: 1.5.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

##docker-compose.yml
thread:
    image: '10.255.33.19:5000/tomcat:${tag}'
    cpu_shares: 10
    mem_limit: '1g'
    dns:  10.255.96.19

when I up this file. 
ERROR: json: cannot unmarshal string into Go value of type []string

But,that is ok
thread:
    image: '10.255.33.19:5000/tomcat:${tag}'
    cpu_shares: 10
    mem_limit: '1g'
    dns:  
      - 10.255.96.19

**Comment by aanand** [comment] 2015-12-10 12:50
Duplicate of #2515, fixed in #2527

**Closed by aanand** 2015-12-10 12:50 UTC
