### ISSUE TITLE
Provide an environment variable with the name of the current container

### ISSUE THREAD

**Issue by dsyer** [docker/compose#408] opened 2014-08-13 23:33 UTC
I can see traces of it everywhere, e.g. in /etc/hosts:

```
172.17.0.198	848fdb642137
127.0.0.1	localhost
...
172.17.0.193	web_1
...
```

and 

```
$ env | grep web
...
WEB_1_NAME=web_1
...
```

so fig has injected it in there somehow, but not in a very accessible way. It would be great to be able to discover that at runtime.

**Comment by dnephin** [comment] 2015-09-01 14:49
Duplicate of #1503 which has a PR open for it, so closing this one.

**Closed by dnephin** 2015-09-01 14:49 UTC
