### ISSUE TITLE
Allow ENV variables in docker-compose.yml

### ISSUE THREAD

**Issue by mattes** [docker/compose#1287] opened 2015-04-13 20:06 UTC
docker-compose.yml
```
web:
  image: some-image
  volumes:
    - $PWD:/home/web
```

It would be really cool if ``env`` variables would get replaced with their actual values during ``docker-compose up``.

**Comment by mattes** [comment] 2015-04-13 20:11
ref: https://github.com/docker/compose/issues/939

**Comment by hauleth** [comment] 2015-04-17 21:14
:+1:

It will allow tools like `invoker` to run Composer apps in background.

**Comment by pwaller** [comment] 2015-04-28 11:19
Looks like a duplicate of #495

**Comment by aanand** [comment] 2015-04-30 17:53
Closing in favour of https://github.com/docker/compose/issues/1377

**Closed by aanand** 2015-04-30 17:53 UTC
