### ISSUE TITLE
Proposal for an exclude feature

### ISSUE THREAD

**Issue by jimzucker** [docker/compose#2803] opened 2016-02-02 01:37 UTC
Use case: You have a project with many components and users what to pick and chose which to install but he compose file installs them all.

Proposal: We add a option to put int he docker-cmpose.overrider.yml to exclude a image defined in the docker.compose

ie

some-image:
  exclude: yes

The behavior would be to ignore that entry in the docker-compose.yml

Can you let me know what the team thinks, I would be in interested in making the change.

**Comment by dnephin** [comment] 2016-02-02 16:03
I think this overlaps with #1294 and #1896

**Comment by dnephin** [comment] 2016-03-21 22:29
Closing as a duplicate of #1988 and #1896

**Closed by dnephin** 2016-03-21 22:29 UTC
