### ISSUE TITLE
Dependent services should not be re-created when re-creating depending services

### ISSUE THREAD

**Issue by viranch** [docker/compose#1397] opened 2015-05-07 10:48 UTC
Consider following `docker-compose.yml`:

```yml
web:
    build: .
    links:
        - db
db:
    image: mysql
```

I run the services.

```
$ docker-compose up -d
Creating project_db_1...
Creating project_web_1...
$
```

When I want to restart (recreate) my web service after some changes, I issue:

```
$ docker-compose up -d web
Recreating project_db_1...
Recreating project_web_1...
$ 
```

I would normally expect only my web service to start without interrupting the depending services.

But it doesn't happen so. The dependent services should not be re-created when recreating depending services. Dependent should only be started if not running already.

On the other hand, if I re-create dependent service, the depending service should be re-created, which does not happen.

```
$ docker-compose up -d db
Recreating project_db_1...
$ 
```
The web service then loses the link and has no idea of the new db service.

**Comment by aanand** [comment] 2015-05-07 11:14
> The dependent services should not be re-created when recreating depending services. Dependent should only be started if not running already.

Yes - assuming no configuration has changed for the upstream service, it shouldn't be recreated. I'm working on this in #1345. For now, use `--no-deps`:

    $ docker-compose up -d --no-deps web

> On the other hand, if I re-create dependent service, the depending service should be re-created

Arguably, yes, although there should be a flag to prevent it.

**Comment by luhn** [comment] 2015-07-26 02:22
I came here to report this bug.  I'm running 1.4.0rc2 and I want love the smart-recreate from #1345, but it almost always breaks my applications because **it's inverting the dependency graph.**  This behavior existed before #1345, too, if you upped only a single container at a time.

For example, here's a simple compose file I set up:

```yaml
a:
  image: nginx

b:
  image: nginx
  links:
    - a

c:
  image: nginx
  links:
    - a
```

Now, let's say we update a: 

```bash
$ docker-compose up -d --force-recreate a
Recreating tmp_a_1...
```

b and c, which are dependent on a, should have been recreated, but they weren't.  **Now the links from b to a and c to a are broken**:

```bash
$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
0cddf85e5d74        nginx               "nginx -g 'daemon of   2 minutes ago       Up 2 minutes        80/tcp, 443/tcp     tmp_a_1
c1d1add241f2        nginx               "nginx -g 'daemon of   3 minutes ago       Up 3 minutes        80/tcp, 443/tcp     tmp_b_1
a40f1198bd7b        nginx               "nginx -g 'daemon of   3 minutes ago       Up 3 minutes        80/tcp, 443/tcp     tmp_c_1
$ docker inspect 0cddf85e5d74 | grep IPAddress  # This is a's IP
        "IPAddress": "172.17.0.64",
        "SecondaryIPAddresses": null,
$ docker exec c1d1add241f2 cat /etc/hosts  # b has the wrong IP address
172.17.0.63	c1d1add241f2
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.61	a 00b69811c461 tmp_a_1
172.17.0.61	a_1 00b69811c461 tmp_a_1
172.17.0.61	tmp_a_1 00b69811c461
$ docker exec a40f1198bd7b cat /etc/hosts  # So does c
172.17.0.62	a40f1198bd7b
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.61	a 00b69811c461 tmp_a_1
172.17.0.61	a_1 00b69811c461 tmp_a_1
172.17.0.61	tmp_a_1 00b69811c461
```

In a similar vein, if we were to start from scratch and up B, a would be upped too, breaking the link from C to A.  **Updates will bubble up the wrong way on the dependency graph, breaking all links along the way.**  I can't emphasize enough the severity of this bug.  It will be made especially prominent by the release of the new smart-recreate feature, since a single updated container could break an entire deployment.  This should be resolved before 1.4 leaves RC.

Thanks for reading.  I appreciate the work you guys are doing with this.  I love how simple and straightforward it is.  The "cloud" ecosystem needs more software like this.

**Comment by aanand** [comment] 2015-07-28 10:05
> It will be made especially prominent by the release of the new smart-recreate feature, since a single updated container could break an entire deployment.

Are you talking about this scenario?

    $ docker-compose up -d
    Creating tmp_a_1...
    Creating tmp_b_1...
    Creating tmp_c_1...

    (...change configuration for a...)

    $ docker-compose up -d

Because if so, here's what will happen:

    $ docker-compose up -d
    Recreating tmp_a_1...
    Recreating tmp_b_1...
    Recreating tmp_c_1...

No broken links.

If you don't pass a list of services to `docker-compose up`, it will recreate services whose configuration has changed *or* which (transitively) depend on services whose configuration has changed.

I don't think we make this clear in the docs.

**Comment by luhn** [comment] 2015-07-28 22:36
Ah, I thought `up -d --force-recreate a` would behave the same as `up -d` after having modified A.  It does seem like the latter works as intended.  I apologize for the mistake.

However, the behavior of `up -d --force-recreate a` seems wrong, especially since it's breaking my linked containers.  It seems like it should behave the same as `up -d` after having modified A.

**Comment by dnephin** [comment] 2015-09-29 03:49
This should be fixed in 1.4.x.

@luhn The default should work for you now, but if  you need to force a recreate like that, I think using `--no-deps` will do what you want.

**Closed by dnephin** 2015-09-29 03:49 UTC

**Comment by viranch** [comment] 2015-10-18 10:24
@dnephin I'm backporting the fix for this issue to older versions (in my fork). Can you point me to the commit(s) that fix this?

**Comment by dnephin** [comment] 2015-10-18 15:42
I think you'll want at least #1399, #1960, #1939. Not sure if there are others
