### ISSUE TITLE
Docker 3.2.1 For Windows and WSL 2 Does not Read .env File or Find Local Images

### ISSUE THREAD

**Issue by 58bits** [docker/compose#8185] opened 2021-03-09 11:24 UTC
### Actual behavior

Docker 3.2.1 does not read local .env file nor does it find local images when running docker-compose under WSL 2 (Ubuntu 20.04 distro)

### Expected behavior

Should find and read .env, and find local images.

### Steps to reproduce

I've uninstalled 3.2.1 and reinstalled 3.1 and everything is working as expected.

Uninstalled 3.1 and re-installed 3.2.1 and the errors return - docker-compose says it cannot find the .env environment variables (reverting to blank values).

**Comment by stephen-turner** [comment] 2021-03-09 13:57
Thanks for the ticket. If it's solved by downgrading compose, it looks like a compose bug, so I've transferred it into the compose repo.

**Comment by ulyssessouza** [comment] 2021-03-09 14:41
Thanks @stephen-turner !

Hello @58bits! 

For the `.env` issue I would say that it's related to a fix on `project_dir`. For more info, please have a look at this release notes https://github.com/docker/compose/releases/tag/1.28.0

I'll close this issue because since it was created in Docker Desktop, it does not include enough info about `docker-compose` so that we can reproduce the issue. Please, create another one in this repository answering the template questions so that we can have a clear vision.

**Closed by ulyssessouza** 2021-03-09 14:41 UTC

**Comment by 58bits** [comment] 2021-03-09 15:34
@ulyssessouza - Yes! - it was the --project-dir settings, which now has to be specified before --file.  Thanks for taking the time to reply.
