### ISSUE TITLE
Output missing with container in TTY mode

### ISSUE THREAD

**Issue by phemmer** [docker/compose#1229] opened 2015-03-31 18:38 UTC
I'm trying to run several containers with TTY mode enabled (`tty: true` in config). When I enable TTY mode, commands such as `compose up` and `compose logs` do not show the container's output. However I can run `docker logs $cid` and the output shows up just fine.
The output does show up when the container exits, but not until then. And when it does show up, the first several bytes of the stream are missing. For example:

```
hello:
  image: busybox
  command: sh -c 'echo hello world; sleep 2; echo done'
  tty: true
```

```
# compose up
Recreating code_hello_1...
Attaching to code_hello_1
hello_1 | rld
hello_1 | done
code_hello_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```

Both lines showed up at the exact same time instead of having a 2 second pause, and note that the `hello wo` is missing.

This is using current master https://github.com/docker/compose/commit/43369cda9ce5f0fe4860c7160cfa6550d31e2417

**Comment by aknuds1** [comment] 2015-04-15 19:38
I guess this is the same issue as I'm experiencing [here](http://stackoverflow.com/questions/29659243/how-do-i-make-docker-compose-on-os-x-work-with-a-play-app)?

**Comment by dano** [comment] 2015-06-07 18:05
I'm hitting the same issue. It looks like this is because compose always assumes that the output it gets when attaching to or fetching the logs from the docker is multiplexed, but that's [not the case when the container is started with a tty](http://docs.docker.com/reference/api/docker_remote_api_v1.18/#attach-to-a-container):

>Stream details:
>
>**When using the TTY setting is enabled in POST /containers/create , the stream is the raw data from the >process PTY and client's stdin**. When the TTY is disabled, then the stream is multiplexed to separate >stdout and stderr.

This isn't actually documented with the logs API though, just the attach API.

Because of this compose tries to read in a header with which should provide a specific length ,etc. but really it's just getting the raw output from the container. It then waits to read `length` bytes before outputting anything from the stream. `length` can end up being pretty much anything; sometimes it's huge, so nothing is outputted, sometimes its small enough that you do see output, but with the pieces of the output that got used as a header missing.

**Comment by dano** [comment] 2015-07-08 20:39
FWIW, A fix for the docker-py issue I referenced above just got merged upstream.

**Comment by aanand** [comment] 2015-07-09 10:29
This will be fixed once docker-py 1.3.0 is out.

**Closed** 2015-07-14 15:55 UTC
Labels: bug

**Comment by javsalgar** [comment] 2016-11-14 09:26
I am having the same issue but only in OSX:

https://drive.google.com/file/d/0B_ulNhvK6XduT2RiY3VUdmZYNDQ/view?usp=sharing

```
ip-192-168-200-196: javsalgar$ docker --version
Docker version 1.12.3, build 6b644ec
ip-192-168-200-196: javsalgar$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
```

**Comment by dimitarivanov** [comment] 2016-12-11 07:45
Same on Windows:
```
PS C:\> docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 67
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 8 GiB
Name: ****
ID: MJGX:KUA2:WQZ7:GCQF:PXW2:D6A6:2DZU:C55T:RPED:SZDY:DGVA:R36H
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
```
PS C:\> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```
```
PS C:\> docker-compose version
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016
```

**Comment by choxi** [comment] 2022-04-04 21:03
It looks like this has regressed, I can reproduce the issue on Docker Desktop for Mac 4.6.1 with the original `hello` service at the top.

**Comment by Pajinek** [comment] 2022-04-12 08:54
Same issue that logs are missing in output.

>> Docker version 20.10.13, build a224086349
>> Docker Compose version 2.3.3
