### ISSUE TITLE
Values from env_file don't work in environment

### ISSUE THREAD

**Issue by lukeromanowicz** [docker/compose#6992] opened 2019-10-31 11:01 UTC
## Description of the issue
You cannot assign values saved in files referenced in `env_file` in environment section of docker-compose but values from `.env` file work just fine.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.23.2, build 1110ad01
```

**Output of `docker version`**
```
Docker version 18.09.5, build e8ff056
```
**Output of `docker-compose config`**
```
services:
  redis:
    environment:
      FOO: baz
      VALUE: bar
    image: redis:4-alpine
version: '3.0'
```

## Steps to reproduce the issue

1. Create following files:
docker-compose.yml:
```
version: '3'

services:
  redis:
    image: 'redis:4-alpine'
    environment:
      VALUE: ${FOO}
    env_file:
      - override.env
```
.env:
```
FOO=bar
```
override.env:
```
FOO=baz
```

### Observed result
```
$ docker-compose config
services:
  redis:
    environment:
      FOO: baz
      VALUE: bar
    image: redis:4-alpine
version: '3.0'
```
### Expected result
```
$ docker-compose config
services:
  redis:
    environment:
      FOO: baz
      VALUE: baz
    image: redis:4-alpine
version: '3.0'
```

### Stacktrace / full error message
N/A

## Additional information
N/A

**Comment by titpetric** [comment] 2019-10-31 15:43
Would it be unreasonable that variables from `environment` or `env_file` are evaluated for replacement in the YML file? The issue is that even `docker-compose config` isn't deterministic, as it can have `-f docker-compose.yml` as an argument, but will still read the .env file from $PWD, and not from the same folder where the config is located (even with an explicit `env_file [ .env ]`).

From what i see, `env_file` is resolved by `docker-compose config` into `environment: [...]`:

~~~
$ docker-compose config
services:
  test:
    environment:
      EXPOSE: '8080'
      VERSION: '3.5'
    image: alpine:3.7
    ports:
    - 80/tcp
version: '2.4'
~~~

Where the actual config has env_file:

~~~
version: '2.4'

services:
  test:
    image: alpine:${VERSION:-3.7}
    env_file:
      - docker-compose.env
    environment:
      - VERSION=3.5
    ports:
      - ${EXPOSE:-80}
~~~

so, some evaluation is already going on internally for the `config` output. And let's assume a negative response to my question here, and then we are left with the question, how can we load an `.env` file from a different folder, when using `docker-compose` together with the `-f` option?

**Comment by ps23** [comment] 2019-10-31 15:56
Exactly, taking the env_file input just adds the variables into 'environment', it does not do an envsubst so to speak. So the env_file is a fixed environment configuration file, while the .env file is simply a convenience. I do not know the reason behind it exactly but it covers two different approaches to how one could handle the config. If you want to use the env_file as yml substitute:

```
env $(cat <PATH>/docker-compose.env | xargs) docker-compose up
```

or also see my #6580

**Comment by titpetric** [comment] 2019-10-31 17:15
To answer my last question: The work around for my particular case may also be `--project-directory` in lieu of `-f`. (didn't go testing it, but it reads like it should work).

**Comment by jcsirot** [comment] 2019-11-04 16:37
Hello @lukeromanowicz 
Actually the behavior you are describing is the one expected.
As explained in the [compose documentation](https://docs.docker.com/compose/environment-variables/) (and in previous comments) the `environment` or `env_file` sections are used to inject environment variables into the service container started by Compose.
On the other hand the `.env` file is used to specify default values for the variables referenced in the Compose file.

**Closed by jcsirot** 2019-11-04 16:37 UTC
Labels: status/0-triage
