### ISSUE TITLE
Placement of option flag should not affect the command

### ISSUE THREAD

**Issue by k0pernikus** [docker/compose#2457] opened 2015-11-25 13:43 UTC
This will work:

    $ docker-compose up -d some_image

This won't:

    $ docker-compose up some_image -d
    ERROR: No such service: -d

It should not matter where the `-d` option flag is passed when running the command. Both should behave the same.

**Comment by aanand** [comment] 2015-11-25 15:27
I agree that from a UX perspective this is a total drag. Unfortunately it's non-trivial to fix with the current docopt-based implementation of command line parsing. Perhaps there's another CLI parsing library out there that makes it easier to achieve.

**Comment by dnephin** [comment] 2015-11-25 15:36
Python `argparse` works with any order of arguments, but I don't think it's worth it to change libraries.

There are plenty of linux tools that require option flags to come before positional args, I don't think it's really abnormal or unexpected.

**Comment by k0pernikus** [comment] 2015-11-25 17:20
@dnephin Only because other tools suck that is no justification to suck as well ;) So I don't buy into this appeal to common misbehavior.

BTAIM, it would help, if the docs would be more clear about this.

`$ docker-compose help up` prints:
```
Builds, (re)creates, starts, and attaches to containers for a service.

Unless they are already running, this command also starts any linked services.

The `docker-compose up` command aggregates the output of each container. When
the command exits, all containers are stopped. Running `docker-compose up -d`
starts the containers in the background and leaves them running.

If there are existing containers for a service, and the service's configuration
or image was changed after the container's creation, `docker-compose up` picks
up the changes by stopping and recreating the containers (preserving mounted
volumes). To prevent Compose from picking up changes, use the `--no-recreate`
flag.

If you want to force Compose to stop and recreate all containers, use the
`--force-recreate` flag.

Usage: up [options] [SERVICE...]

Options:
    --allow-insecure-ssl   Deprecated - no effect.
    -d                     Detached mode: Run containers in the background,
                           print new container names.
    --no-color             Produce monochrome output.
    --no-deps              Don't start linked services.
    --force-recreate       Recreate containers even if their configuration and
                           image haven't changed. Incompatible with --no-recreate.
    --no-recreate          If containers already exist, don't recreate them.
                           Incompatible with --force-recreate.
    --no-build             Don't build an image, even if it's missing
    -t, --timeout TIMEOUT  Use this timeout in seconds for container shutdown
                           when attached or when containers are already
                           running. (default: 10)
```

It implies that the option may come first, and this is how I found out what the issue I was having was, yet by no means is it clear that the order of the argument is mandatory. So one might add a line there to make the usage more clear, if making the order of options optional is too big of an issue.

**Comment by dnephin** [comment] 2015-11-25 17:23
You can put the options in any order, but the service names are not options, they are positional arguments, which is explicit from `up [options] [SERVICE...]`

If they could be mixed order it would be something like `up [options | SERVICE...]` or even just `up [options]`, where some of the options were service names.

**Comment by k0pernikus** [comment] 2015-11-25 17:32
@dnephin Thanks for clearing that up.

**Comment by dnephin** [comment] 2016-01-04 16:43
Closing this issue, since it's by design

**Closed by dnephin** 2016-01-04 16:43 UTC
