### ISSUE TITLE
Docker compose does not remove intermediate containers

### ISSUE THREAD

**Issue by dobryak** [docker/compose#9058] opened 2021-12-21 22:58 UTC
**Description**

`docker-compose build` or `docker-compose up` commands do not remove intermediate containers created during building of images.

**Steps to reproduce the issue:**

Structure of the compose project:
```text
.
├── docker-compose.yml
└── test
    └── Dockerfile
```

`docker-compose.yml` file:
```yaml
version: "3.4"

services:
  test:
    build:
      context: ./test
```
`test/Dockerfile` file:
```dockerfile
FROM php:5.6-fpm-alpine

RUN set -e && apk add --no-cache git
```

Run the command `docker-compose up -d`.

**Describe the results you received:**

```text
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS                      PORTS                                   NAMES
84c65de05c14   test_prj_test              "docker-php-entrypoi…"   12 minutes ago   Up 12 minutes               9000/tcp                                test_prj-test-1
344eacdf6b3b   6feac8f2ef42               "/bin/sh -c 'set -e …"   12 minutes ago   Exited (0) 12 minutes ago                                           sweet_newton

```

As you can see the intermediate container `344eacdf6b3b` was not removed after building.

**Describe the results you expected:**

```text
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS                      PORTS                                   NAMES
84c65de05c14   test_prj_test              "docker-php-entrypoi…"   12 minutes ago   Up 12 minutes               9000/tcp                                test_prj-test-1
```
I expect to have only the target container. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

```
Docker Compose version 2.2.2
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., 2.2.2)

Server:
 Containers: 26
  Running: 4
  Paused: 0
  Stopped: 22
 Images: 330
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc version: v1.0.2-0-g52b36a2d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.6-arch2-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.21GiB
 Name: REDACTED
 ID: REDACTED
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details:**
N/A

**Comment by ttwilliger** [comment] 2022-01-04 17:53
I am curious about this as well.  Is this now intended default behavior?  Is there some kind of flag that can be used to remove intermediate containers?

**Comment by mrjackwills** [comment] 2022-01-05 04:05
In the mean time, is there any way to remove these intermediate containers, without using prune

**Comment by ndeloof** [comment] 2022-01-05 07:47
I can't reproduce this issue with default installation. do you maybe have buildkit disabled?

**Comment by mrjackwills** [comment] 2022-01-05 14:26
> I can't reproduce this issue with default installation. do you maybe have buildkit disabled?

I have now enabled buildkit, and can confirm that when buildkit is enabled the intermediate containers are removed as expected

**Comment by dobryak** [comment] 2022-01-06 18:18
> I can't reproduce this issue with default installation. do you maybe have buildkit disabled?

Yes, I do have buildkit disabled

**Comment by ndeloof** [comment] 2022-01-06 18:19
assigning to @ulyssessouza who introduced "classic" builder support

**Comment by ndeloof** [comment] 2022-12-16 11:54
based on https://github.com/docker/compose/pull/9097, closing this one as "wont fix"

**Closed by ndeloof** 2022-12-16 11:54 UTC
Labels: Docker Compose V2
