### ISSUE TITLE
compose 1.28.2 Bug "No such file or directory: '/tmp/tmpoxytjd_f' "

### ISSUE THREAD

**Issue by Ayub-Khan** [docker/compose#8121] opened 2021-02-15 20:33 UTC
## Description of the issue
compose 1.28.2 build command fails with a weird error 
'FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpoxytjd_f''

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.28.2, build 67630359
docker-py version: 4.4.1
CPython version: 3.7.9
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bc
 Built:             Fri Feb  5 15:56:39 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf
  Built:            Fri Feb  5 15:58:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  elas_web:
    build:
      context: /home/ayub/elas/elas_web
      dockerfile: Dockerfile
    container_name: elas_web
    depends_on:
      mongo:
        condition: service_started
    image: elas_web
    ports:
    - published: 80
      target: 80
  mongo:
    command: mongod --port 27017
    container_name: mongo
    image: mongo:4.2.3
    ports:
    - published: 27017
      target: 27017
    volumes:
    - mongodb:/data/db:rw
version: '3.9'
volumes:
  mongodb:
    external: true
    name: mongodb

```

## Steps to reproduce the issue

1. docker-compose up --build
### Observed result
builds images and raises an error
### Expected result
builds images and brings up containers
### Stacktrace / full error message

```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Building elas_web
Sending build context to Docker daemon  90.11kB

Step 1/5 : FROM tiangolo/uvicorn-gunicorn:python3.8
 ---> 524e010ef786
Step 2/5 : RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false
 ---> Using cache
 ---> 601376cc945e
Step 3/5 : COPY ./pyproject.toml ./poetry.lock* /app/
 ---> Using cache
 ---> 0d2205601d34
Step 4/5 : RUN poetry install --no-root --no-dev
 ---> Using cache
 ---> 36fe3a0e8dae
Step 5/5 : COPY ./app /app
 ---> Using cache
 ---> 8ba66d1b6e04
Successfully built 8ba66d1b6e04
Successfully tagged elas_web:latest
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 192, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1165, in up
  File "compose/cli/main.py", line 1161, in up
  File "compose/project.py", line 670, in up
  File "compose/service.py", line 347, in ensure_image_exists
  File "compose/service.py", line 1131, in build
  File "compose/progress_stream.py", line 22, in stream_output
  File "compose/utils.py", line 50, in split_buffer
  File "compose/utils.py", line 26, in stream_as_text
  File "compose/service.py", line 1894, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpreq0pm2k'
[44042] Failed to execute script docker-compose
```

## Additional information
Everything works against the following compose version
```
docker-compose version 1.27.3, build 4092ae5d
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```
Os Info
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

**Comment by PudottaPommin** [comment] 2021-02-20 10:25
I have same problem with every 1.28.X version on Linux Mint 20.1

**Comment by mbritton-muso** [comment] 2021-03-02 19:17
Same issue with 1.28.5 on Linux, with a previously working setup. Here's my full stack trace:

> Traceback (most recent call last):
  File "/home/muso/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/muso/.local/lib/python3.8/site-packages/compose/cli/main.py", line 80, in main
    command_func()
  File "/home/muso/.local/lib/python3.8/site-packages/compose/cli/main.py", line 192, in perform_command
    handler(command, command_options)
  File "/home/muso/.local/lib/python3.8/site-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/home/muso/.local/lib/python3.8/site-packages/compose/cli/main.py", line 1165, in up
    to_attach = up(False)
  File "/home/muso/.local/lib/python3.8/site-packages/compose/cli/main.py", line 1145, in up
    return self.project.up(
  File "/home/muso/.local/lib/python3.8/site-packages/compose/project.py", line 664, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/home/muso/.local/lib/python3.8/site-packages/compose/service.py", line 347, in ensure_image_exists
    self.build(cli=cli)
  File "/home/muso/.local/lib/python3.8/site-packages/compose/service.py", line 1131, in build
    all_events = list(stream_output(build_output, output_stream))
  File "/home/muso/.local/lib/python3.8/site-packages/compose/progress_stream.py", line 22, in stream_output
    for event in utils.json_stream(output):
  File "/home/muso/.local/lib/python3.8/site-packages/compose/utils.py", line 50, in split_buffer
    for data in stream_as_text(stream):
  File "/home/muso/.local/lib/python3.8/site-packages/compose/utils.py", line 26, in stream_as_text
    for data in stream:
  File "/home/muso/.local/lib/python3.8/site-packages/compose/service.py", line 1901, in build
    with open(iidfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp98i_xuz0'

**Comment by DoubleDi** [comment] 2021-03-07 00:39
Same problem on ubuntu 20.04

**Comment by bertini36** [comment] 2021-03-08 13:33
Same problem here

**Ubuntu**: 20.04.2 LTS
**Docker**: 19.03.13
**Compose**: 1.28.5

**Comment by avere001** [comment] 2021-03-12 17:13
Same issue here as well. 

The image still finishes building and a subsequent call to `docker-compose up` succeeds. A temporary workaround is to run `docker-compose build` and `docker-compose up` separately.

**Ubuntu**: 18.04.5 LTS
**Compose**: version 1.28.5 (binary download)
**Docker**: 19.03.13 (snap package)

**Comment by Sanil2108** [comment] 2021-03-22 04:44
Facing the same issue. 

**Ubuntu**: 20.04
**Docker**: 19.03.13
**Docker Compose**: 1.28.5

**Comment by Hungryarie** [comment] 2021-03-22 20:21
Same here,

Ubuntu: 20.04
Docker version 19.03.13, build cd8016b6bc
docker-compose version 1.28.5, build c4eb3a1f

`Sending build context to Docker daemon  20.67MB

Step 1/6 : FROM alpine:3.10
 ---> 5641e2976510
Step 2/6 : RUN apk add --update sqlite
 ---> Using cache
 ---> 231188b61f85
Step 3/6 : RUN mkdir /db
 ---> Using cache
 ---> c6a958a8c872
Step 4/6 : WORKDIR /db
 ---> Using cache
 ---> ff325099d1af
Step 5/6 : ENTRYPOINT ["sqlite3"]
 ---> Using cache
 ---> b0e631bdc7d0
Step 6/6 : CMD ["test.db"]
 ---> Using cache
 ---> 2c68f4c749c2
Successfully built 2c68f4c749c2
Successfully tagged homeautomation_sqlite3:latest
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 192, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 369, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1131, in build
  File "compose/progress_stream.py", line 22, in stream_output
  File "compose/utils.py", line 50, in split_buffer
  File "compose/utils.py", line 26, in stream_as_text
  File "compose/service.py", line 1901, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpnj_mqshl'
[265997] Failed to execute script docker-compose`

**Comment by antoineverger1** [comment] 2021-03-24 18:16
Same here : 
Ubuntu 20.04.2
Docker version 19.03.13, build cd8016b6bc
docker-compose version 1.28.5, build c4eb3a1f

`Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 192, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 369, in build
  File "compose/project.py", line 519, in build
  File "compose/project.py", line 501, in build_service
  File "compose/service.py", line 1131, in build
  File "compose/progress_stream.py", line 22, in stream_output
  File "compose/utils.py", line 50, in split_buffer
  File "compose/utils.py", line 26, in stream_as_text
  File "compose/service.py", line 1901, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmph8ef2plc'
`

**Comment by antoineverger1** [comment] 2021-03-24 18:23
For everyone who struggled with the issue, it is fixed on my side. How ? I upgrade both docker and docker-compose to the latest stable versions (Docker:  20.10.15 / Compose: 1.28.6)

**Comment by ClimenteA** [comment] 2021-04-14 11:49
Same for me:
Ubuntu : 20.04
Docker version 19.03.13
docker-compose version 1.29.0

**Comment by Hungryarie** [comment] 2021-04-14 15:13
Upgrading to docker 20.10.6 was the solution for me

**Comment by mferretti** [comment] 2021-04-19 08:57
Same here

_Successfully tagged compose_database:latest
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1189, in up
  File "compose/cli/main.py", line 1185, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 364, in ensure_image_exists
  File "compose/service.py", line 1133, in build
  File "compose/service.py", line 1948, in build
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpvda_6evm'
[107987] Failed to execute script docker-compose_

Ubuntu: 20.04
Docker version 19.03.13, build cd8016b6bc
docker-compose version 1.29.1, build c34c88b2

Docker installed via snapcraft.io, the solution proposed by @Hungryarie is not applicable/testable here as the edge release il 19.03.15 (which has the same problem)

**Comment by Hungryarie** [comment] 2021-04-19 09:40
I got rid of snap and installed the newest version (https://docs.docker.com/engine/install/ubuntu/). Then it worked as expected!

**Comment by mferretti** [comment] 2021-04-20 10:05
I can confirm that docker 20 (not snap) actually fixes the error:
Docker version 20.10.6, build 370c289
docker-compose version 1.29.1, build c34c88b2

docker-compose up
Creating network "compose_default" with the default driver
Building database
...
Successfully built 5a12a56c6744
Successfully tagged compose_database:latest

**Closed** 2021-04-26 21:56 UTC
Labels: kind/bug

**Comment by aritrog** [comment] 2022-04-09 21:40
I have installed docker with snap and I faced the same issue. So, I removed snap and installed it the way mentioned in this page: [docker installation](https://docs.docker.com/engine/install/ubuntu/) it worked for me

**Comment by vap78** [comment] 2025-12-28 06:51
> I have installed docker with snap and I faced the same issue. So, I removed snap and installed it the way mentioned in this page: [docker installation](https://docs.docker.com/engine/install/ubuntu/) it worked for me

I had this error and the root cause was this one. Somehow the snap installation did not work with docker compose.
