### ISSUE TITLE
docker-compose 1.19.0-rc2: nsecureRequestWarning: Unverified HTTPS request is being made.

### ISSUE THREAD

**Issue by jamshid** [docker/compose#5642] opened 2018-02-03 22:46 UTC
Something broke after Docker for Mac Edge updated my docker-compose 1.18 to 1.19.0-rc2. 

I'm seeing  tons of `InsecureRequestWarning` whenever I use docker-compose with my Ubuntu 16.04 docker server, configured with docker-machine (now at 0.13.0).

Does compose no longer use the certs and key files in `DOCKER_CERT_PATH`? Compose works fine if I use explicit `--tlscacert` etc parameters.

```
$ eval $(docker-machine env 61)
$ env | grep -Ei 'machines|tls'
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/jamshid/.docker/machine/machines/61
$ docker-compose ps
...
/var/folders/83/y1z9b5111l35yb2rbnpzn7j00000gp/T/_MEIOolV7O/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
(repeated)
...
$ docker-compose $(docker-machine config 61 | xargs ) ps
(no InsecureRequestWarning)
```
That last command (which works) expands to:
```
$ docker-compose --tlsverify --tlscacert=/Users/jamshid/.docker/machine/machines/61/ca.pem --tlscert=/Users/jamshid/.docker/machine/machines/61/cert.pem --tlskey=/Users/jamshid/.docker/machine/machines/61/key.pem -H=tcp://192.168.1.61:2376 ps

**Comment by jamshid** [comment] 2018-02-03 23:02
Looking at `docker-compose --verbose` output I see it thinks it found an `auths` section and `credStore` (whatever that means):
```
$  docker-compose --verbose ps
compose.config.config.find: Using configuration files: ./docker-compose-uniq-port.yml,./docker-compose-base.yml,./docker-compose-uniq-port.yml
docker.auth.find_config_file: Trying paths: ['/Users/jamshid/.docker/config.json', '/Users/jamshid/.dockercfg']
docker.auth.find_config_file: Found file at path: /Users/jamshid/.docker/config.json
docker.auth.load_config: Found 'auths' section
docker.auth.parse_auth: Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
docker.auth.load_config: Found 'credsStore' section
urllib3.connectionpool._new_conn: Starting new HTTPS connection (1): 192.168.1.61
/var/folders/83/y1z9b5111l35yb2rbnpzn7j00000gp/T/_MEIoD8lBQ/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3.connectionpool._make_request: https://192.168.1.61:2376 "GET /v1.24/version HTTP/1.1" 200 541
compose.cli.command.get_client: docker-compose version 1.19.0-rc2, build a186c31
docker-py version: 2.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zh 14 Jan 2016
compose.cli.command.get_client: Docker base_url: https://192.168.1.61:2376
compose.cli.command.get_client: Docker version: KernelVersion=4.4.0-112-generic, Components=[{u'Version': u'17.12.0-ce', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-112-generic', u'Os': u'linux', u'BuildTime': u'2017-12-27T20:09:53.000000000+00:00', u'ApiVersion': u'1.35', u'MinAPIVersion': u'1.12', u'GitCommit': u'c97c6d6', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.9.2'}}], Arch=amd64, BuildTime=2017-12-27T20:09:53.000000000+00:00, ApiVersion=1.35, Platform={u'Name': u''}, Version=17.12.0-ce, MinAPIVersion=1.12, GitCommit=c97c6d6, Os=linux, GoVersion=go1.9.2
```

it's looking in my `~/.docker/config.json` which has 
```
{
  "auths" : {
    "https://index.docker.io/v1/" : {

    }
  },
  "credsStore" : "osxkeychain",
  "orchestrator" : "swarm"
}
```

Tried removing that config.json file but compose still shows `InsecureRequestWarning`.

**Comment by shin-** [comment] 2018-02-04 02:50
Duplicate of #5632 

Please download RC3 !

**Closed by shin-** 2018-02-04 02:50 UTC
