### ISSUE TITLE
Docker compose `env_file` entry doesn't load the expected env file

### ISSUE THREAD

**Issue by joaocasarin** [docker/compose#9443] opened 2022-05-05 05:36 UTC
**Description**

Basically the entry `env_file` in the docker-compose file is not loaded. What do I mean? Well, even with that entry set in the compose file, it is not loaded.

**Steps to reproduce the issue:**
1. Clone [this repo ](https://github.com/joaocasarin/aws-lambda-typeorm-error/tree/webpack) and checkout to the `webpack` branch
2. Run `docker-compose up -d`
**Describe the results you received:**
These are the warnings received when executing the compose cli:
![image](https://user-images.githubusercontent.com/48847394/166867963-df718356-1188-4b0f-8396-72d9682d1ff7.png)

**Describe the results you expected:**
The expected result is the exact same result as it is when using the command `docker-compose --env-file .env.test up -d`:
![image](https://user-images.githubusercontent.com/48847394/166868025-fe00f0de-35b1-44a3-806b-833aede6bcbc.png)

**Additional information you deem important (e.g. issue happens only occasionally):**
If you just use `docker-compose up -d`, and in the same folder as the compose file you have both `.env` and `.env.test` files, try adding different values for each of the variables in both files, for instance:
.env
```.env
DATABASE_DOCKER_DB=postgres
```

.env.test
```.env
DATABASE_DOCKER_DB=test-postgres
```

And after running the compose cli, just navigate to the container shell and run `echo "$DATABASE_DOCKER_DB"` to see which variable it loaded :).

**Output of `docker compose version`:**

```
Docker Compose version v2.4.1
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.4.1)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 3.839GiB
 Name: docker-desktop
 ID: VMGW:X7N7:LRHD:RWMQ:EHMS:PV76:QDQR:AAAI:TIFT:HU5R:EKZT:4TO7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details:**

Nothing at this moment.

**Comment by nbx3** [comment] 2022-05-05 09:29
I'm using 2.4.1 release and I believe this is same behaviour as i'm seeing. The file will be read if its called .env but it isn't read if it's called something else and specified with the env_file value within the compose file.

**Comment by thaJeztah** [comment] 2022-05-05 11:38
The `env_file` property in the compose file is the equivalent of `docker run --env-file`, which reads the file to set environment variables on the container that is started. Environment variables from that file are not used for interpolation in the compose file.

The (unfortunately chosen name) `--env-file` option on `docker compose --env-file` is specifying an alternative `.env` file, and those _are_ used to interpolate environment variables within the compose file.

**Comment by nbx3** [comment] 2022-05-05 12:02
A confusing and unfortunate situation but nice clear answer thanks

**Comment by joaocasarin** [comment] 2022-05-09 21:29
> Doh. I just stumbled on this also. It would be extremely useful to have an env_file option within docker-compose.yml to pull in env to be used for interpolation, especially for sharing config across multiple containers without having to repeat it for each container.

I completely support that idea hahaha

Is it possible to make that request?

**Comment by ndeloof** [comment] 2022-05-17 14:02
there's no entry in the compose file for this purpose, but a convention to load a `.env` file if present aside your `compose.yaml` file.

I'm closing this issue as "works as designed"

**Closed by ndeloof** 2022-05-17 14:02 UTC

**Comment by KES777** [comment] 2022-11-07 18:33
@ndeloof: Probably it was designed not so nice.

Agreed with @joaocasarin and @simsrw73, would be nice to have `env_file` at top level, which will work same as `docker compose --env-file xxx.env up`

@thaJeztah Very good description. Unfortunately documentation messed the fact that `.env` is not processed when `--env-file` is used.

**Comment by elhigu** [comment] 2023-03-30 18:11
Also with `docker-compose.yml` `env_file:` option one can create one file with defaults (which is committed to git) and then allow another file, which will allow each user to override some of the defaults without messing the file that is in the version control. That does not work with `docker compose --env-file ` switches.

**Comment by KES777** [comment] 2023-03-31 18:13
Related issue: https://github.com/docker/docs/issues/16113

**Comment by rltas** [comment] 2023-08-18 15:26
This is indeed confusing and there should be a hint in the docs imo because it's not really clear there.

**Comment by niraj-khatiwada** [comment] 2024-04-16 08:02
Oh man, `--env-file` flag caused me headache today. Just found out that it's not for substitution in compose file.
For some reason my `.env` file which is alongside the compose file, yet it does not pick the environments.

**Comment by ndeloof** [comment] 2024-04-16 09:43
@niraj-khatiwada `--env-file` flag **is** about (and only) substitution in compose file
