### ISSUE TITLE
When supplying Compose File via stdin, `-f` should still work.

### ISSUE THREAD

**Issue by Skn0tt** [docker/compose#6124] opened 2018-08-07 11:42 UTC
## Description of the issue

When supplying the `docker-compose.yml`-File via piping, you cannot specify another file with `-f`.
This makes overriding configs from for example [docker-app](https://github.com/docker/app) hard, because you need to create temporary files.

<details>
  <summary>Context information</summary>

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: true
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
</details>

---

## Steps to reproduce the issue

1. Create two configs: docker-compose.yml and docker-compose.dev.yml (which overrides some values in the first one)
2. `cat docker-compose.yml | docker-compose -f - -f docker-compose.dev.yml up`

### Observed result
```
ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './-'
```
### Expected result

It starts the instance.

## Additional information

macOS High Sierra, installed via SH (I think).

**Comment by shin-** [comment] 2018-08-07 18:10
Duplicate of #3440

**Closed by shin-** 2018-08-07 18:10 UTC

**Comment by inieves** [comment] 2020-05-21 05:07
You can specify /dev/stdin as the file you want to read from, and then pipe as normal.
e.g. -f /dev/stdin
Be sure to put all other -f arguments before this special -f argument.
When I did not put -f /dev/stdin after all other -f arguments I had problems with relative paths in those files that came after -f /dev/stdin.

You can read a little more at:
https://stackoverflow.com/questions/53695725/use-docker-compose-config-from-file-and-stdin

**Comment by magnusriga** [comment] 2024-02-28 13:43
@inieves Old thread, but I am was wondering if you know how to set the context correctly, when using stdin? It seems a relative path in the context will be relative to where the script runs from, which seems to be /dev on linux.

The command I am using:

`docker stack config --compose-file "${ROOTDIR}/.devcontainer/docker-compose.base.yml" --compose-file "${ROOTDIR}/.devcontainer/docker-compose.$env.yml" --skip-interpolation | docker compose --progress plain -f /dev/stdin build --no-cache`

Thanks a ton for any/all advice.

**Comment by luciangabor** [comment] 2024-02-28 14:18
`docker compose --project-directory /path/to/dir` would most likely work
