### ISSUE TITLE
Labels created in docker-compose file are not labeled with com.docker.compose.project

### ISSUE THREAD

**Issue by bsideup** [docker/compose#6636] opened 2019-04-08 12:19 UTC
## Description of the issue
Usually, every resource created by Docker Compose contains `com.docker.compose.project` label. But when compose creates a network, it is not labeled.

## Context information (for bug reports)
Testcontainers' users report a lot of unused, prunnable networks:
https://github.com/testcontainers/testcontainers-java/issues/955

## Steps to reproduce the issue

1. Create a Docker Compose file with a network
2. Start it
3. Inspect the created network, see `"Labels": {}`

### Observed result
Networks are not labeled

### Expected result
Networks (as well as any other Docker resource created by Docker Compose) should have a consistent `com.docker.compose.project` label set

**Comment by chris-crone** [comment] 2019-04-09 11:10
Hi @bsideup 

Thanks for the report. Can you please provide:
- An example Compose file that we can use to reproduce the issue
- Which version of `docker-compose` that you have seen this with

**Comment by bsideup** [comment] 2019-04-09 11:38
Hi @chris-crone,

Docker Compose v 1.23.2
Example:
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/test/resources/v2-compose-test-with-network.yml

**Comment by chris-crone** [comment] 2019-04-11 11:45
Thanks for the follow up.

I've confirmed that networks aren't labelled with that example. This appears to be a v2 issue as changing to v3, I see that the network is labelled.

Using:
```yaml
version: '3'
services:
  redis:
    image: redis
    networks:
      - redis-net

networks:
  redis-net:
```

I see:
```console
$ docker network inspect 6636_redis-net                                                                                                                                                                                                                                                                                                                                                                                 [13:43:33] 
[
    {
        "Name": "6636_redis-net",
        "Id": "1ff9571066bba2d522cc8e7485f496660d6d9528096180b1c8f56996514a7aa8",
        "Created": "2019-04-11T11:43:22.8889743Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.31.0.0/16",
                    "Gateway": "172.31.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "9eaf0011c9b783085e294617283245a91c570afa765ef45590a33be65775351c": {
                "Name": "6636_redis_1",
                "EndpointID": "a30b9404a0e9f5e8d7dd8646fc93c10409e9eb9647813700335eac20741494bf",
                "MacAddress": "02:42:ac:1f:00:02",
                "IPv4Address": "172.31.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "redis-net",
            "com.docker.compose.project": "6636",
            "com.docker.compose.version": "1.23.2"
        }
    }
]
```

**Comment by bsideup** [comment] 2019-04-11 12:36
Hi @chris-crone,

Thanks for trying, I did not know that it can be version specific!
Can we expect it to be eventually fixed in v2 or we need to find a workaround on our side?

**Comment by shin-** [comment] 2019-04-11 20:42
Hey @chris-crone @bsideup -- The reason for this is the v2.0 file format is mapped to an API version that didn't support labels on networks and volumes ([see the code here](https://github.com/docker/compose/blob/master/compose/network.py#L131-L140)). Using 2.1 or above will solve this issue.

**Comment by chris-crone** [comment] 2019-04-12 11:53
Thanks for the context @shin-!

@bsideup can you please try with a more recent version of the v2 file format and let me know if that fixes your issue. Note that if you specify `version: '2'` in your Compose file, it is actually version 2.0. If it fixes your issue, please close this issue.

**Comment by ulyssessouza** [comment] 2019-07-25 12:58
Closing by inactivity. Looks like changing the version fixes the issue.
Please ask for re-opening if it's not the case

**Closed by ulyssessouza** 2019-07-25 12:58 UTC
Labels: area/networking, format/v2, kind/bug
