### ISSUE TITLE
docker-compose pull doesn't work with private registry which needs authentication

### ISSUE THREAD

**Issue by eychenz** [docker/compose#3782] opened 2016-07-29 09:20 UTC
**Output of** `docker version` :
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

**Output of** `docker info` :
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-9962085-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 21.33 GB
 Data Space Total: 107.4 GB
 Data Space Available: 86.04 GB
 Metadata Space Used: 16.15 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.131 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.4-301.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: eychenz
ID: QSWI:HP6C:WN7X:AAQP:6MUT:CVIF:F576:YH7Q:MF56:J42A:LRLS:HLM7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Output of** `docker-compose version` :
docker-compose version 1.7.1, build 6c29830
docker-py version: 1.8.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h-fips  3 May 2016

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 24 workstation on Laptop 

**Steps to reproduce the issue:**
1. Enable authentication on Docker Trusted Registry.
2. Set the repositories to need authentication for pulling images.
3. Test if your setup works with `docker login` and `docker pull`.
4. `docker login` creates `~/.docker/config.json` which will be used by `docker pull`.
5. Create a `docker-compose.yml` file using images from your registry.
6. Try `docker-compose pull` to fetch images mentioned in the `docker-compose.yml`.
7. You'll see the message `ERROR: image xxx not found`

**Describe the results you received:**
Apparently `docker-compose` does not look for tokens at all, otherwise it should have found it in the default location.

**Describe the results you expected**
If authentication is already done, `docker-compose` should use the stored token and pull images.

**Additional information**
If `docker-compose` and `docker` are not meant to use each others token, at least I expect `docker-compose` to have a `login` command so it can authenticate itself against Docker Trusted Registry! Otherwise, the pull command doesn't make any sense either while having a private registry with authentication enabled.

**Comment by eychenz** [comment] 2016-07-29 09:41
**Update**
Checking `docker-compose --verbose pull`, I see that `docker-compose` is looking for the stored token, and it also seems it has found it properly. Yet still doesn't work.
_Here is the output of_ `docker-compose --verbose pull`:
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.auth.load_config: Found 'auths' section
docker.auth.auth.parse_auth: Found entry (registry=u'dtr.mycompany.com', username=u'myusername')
compose.cli.command.get_client: docker-compose version 1.7.1, build 6c29830
docker-py version: 1.8.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h-fips  3 May 2016
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: KernelVersion=4.6.4-301.fc24.x86_64, Os=linux, ApiVersion=1.24, Version=1.12.0, GitCommit=8eab29e, Arch=amd64, GoVersion=go1.6.3
compose.service.pull: Pulling myimage (dtr.mycompany.com/repo/myimage:latest)...
compose.cli.verbose_proxy.proxy_callable: docker pull <- (u'dtr.mycompany.com/repo/myimage', tag=u'latest', stream=True)
docker.api.image.pull: Looking for auth config
docker.auth.auth.resolve_authconfig: Looking for auth entry for u'dtr.mycompany.com'
docker.auth.auth.resolve_authconfig: Found u'dtr.mycompany.com'
docker.api.image.pull: Found auth config
compose.cli.verbose_proxy.proxy_callable: docker pull -> <generator object _stream_helper at 0x7ffb82e15a00>
Pulling repository dtr.mycompany.com/repo/myimage
ERROR: compose.cli.main.main: Error: image repo/myimage:latest not found

**Comment by dattran-vn01** [comment] 2016-08-07 15:56
can you show all images at here ? If your registry is v2, you can know all images in your private registry by opening http://[your registry host]:5000/v2/_catalog

**Comment by eychenz** [comment] 2016-08-08 07:40
Thanks for the reply.
My registry is v2, I'm using [Docker Trusted Registry](https://docs.docker.com/docker-trusted-registry/) and the image is visible on the DTR web interface.
I can also pull it using `docker pull`. But I have no chance with `docker-compose pull`.

**Comment by sambernet** [comment] 2016-08-09 21:54
I can confirm the issue on our end.

Using an on-premise private v2 registry with authentication enabled. Registry uses valid TLS certs.

This seems to be a regression between docker 1.12.0 and docker-compose 1.8.0:

- docker 1.12.0 direct pull -> OK (Image is retrieved from registry)
- docker-compose 1.8.0 vs docker 1.12.0 host -> NOK (Error: image _xy_ not found)
- docker-compose 1.7.1 vs docker 1.12.0 host -> OK

All tests run versus the same registry and try to pull the very same image file.

This is a major issue for us, as I can't just switch off authentication (registry is exposed in DMZ). I'll gladly provide more info where required.

**Comment by eychenz** [comment] 2016-08-10 08:24
I reported the issue on docker-compose 1.7.1.
After upgrading to 1.8.0, still I'm getting the same error as @sambernet mentioned.

To deal with the problem for now, I had to modify all our automation scripts and replace `docker-compose pull` by the lines below.
```
images=$(grep "image" ${COMPOSE} | awk '{print $2}' | sort | uniq)
for image in ${images}; do
    docker pull ${image}
done
```

_`${COMPOSE}` is referring to the `docker-compose.yml`._

**Comment by shin-** [comment] 2016-08-30 08:48
Hey folks, sorry to hear you're hitting this issue. I highly suspect it is due to Compose not currently supporting the new credentials store. This has been reported in #3622 already, and I encourage you to follow that issue as we try to find a solution for the next release. I'll close this to avoid duplicates. Thank you for your patience.

**Closed by shin-** 2016-08-30 08:48 UTC
