### ISSUE TITLE
docker-compose up creates directories on host system

### ISSUE THREAD

**Issue by strk** [docker/compose#2781] opened 2016-01-29 10:44 UTC
Running ``docker-compose up`` results in creation of directories specified via `volumes` directive on the host system. I think it would be better to error out if the host directory does not exist.

**Comment by strk** [comment] 2016-01-29 10:47
besides, the directories are created by the "root" user, even if `docker-compose up` was called by an unprivileged user (other than being allowed to use the docker sockets)

**Comment by dnephin** [comment] 2016-01-29 14:47
The directories are created by docker engine, not by compose itself, so this change would need to be made in the engine.

#16072 was the only related issue I could find , but it's for named volumes, not host volumes.

@thaJeztah do you know if there is any talk of this?

**Comment by thaJeztah** [comment] 2016-01-29 17:48
Yes, we marked that "feature" as deprecated in 1.9, and it's targeted for removal in 1.11;  https://github.com/docker/docker/blob/master/docs/deprecated.md#auto-creating-missing-host-paths-for-bind-mounts

> ### Auto-creating missing host paths for bind mounts
> Deprecated in Release: v1.9
>
> Target for Removal in Release: 1.11
>
> When creating a container with a bind-mounted volume-- docker run -v /host/path:/container/path -- docker was automatically creating the /host/path if it didn't already exist.
>
> This auto-creation of the host path is deprecated and docker will error out if the path does not exist.

**Comment by dnephin** [comment] 2016-01-29 17:53
Excellent. Closing this issue since it's being fixed by engine.

**Comment by dnephin** [comment] 2016-01-29 17:53
Thanks @thaJeztah !

**Closed by dnephin** 2016-01-29 17:53 UTC

**Comment by strk** [comment] 2016-01-30 09:01
Thanks everyone!

**Comment by mitar** [comment] 2016-05-30 07:25
Nooo. This was great feature. How can one then make sure paths exist if they do not yet? You have to wrap docker-compose then into a script?

**Comment by mitar** [comment] 2016-05-30 07:30
I think this signals well a need for the hooks: https://github.com/docker/compose/issues/1341

**Comment by thaJeztah** [comment] 2018-11-26 10:38
@verglor If I'm not mistaken, the "long form" volumes syntax will use the mount API, thus not create local directories (unless the daemon is too old to support that API); see https://github.com/docker/compose/pull/5490

**Comment by michaelarnauts** [comment] 2018-11-26 12:46
I'm not sure if there is an existing issue for the mount syntax in docker-compose. There are a lot of issues that specify "mount", but most handle issues with the volumes.

**Comment by thaJeztah** [comment] 2018-11-26 14:16
The `"volumes"` key in the compose-file is used both for (named) "volumes" and for bind-mounts (if you specify a host path instead of a volume name, or, in the long-form when specifying `type: bind`). Using the long form syntax should use the mount API, which prevents paths on the host from being created by the daemon;

```yaml
    volumes:
      - type: bind
        source: ./some/path/on/host
        target: /some/path/in/container
```

**Comment by speller** [comment] 2019-06-13 10:26
So, how a volume should be defined in `docker-compose.yml` file to allow a host directory to be automatically created without any additional custom magic scripts?

**Comment by thaJeztah** [comment] 2019-06-13 10:55
@speller the shorthand syntax will do that; https://docs.docker.com/compose/compose-file/#short-syntax-3

```yaml
volumes:
  - ./some/path/on/host:/some/path/in/container
```

Be aware though, that:

- the path will be created on the host where the _daemon_ runs (which might be a remote host, or a VM), not on the client. (Docker Desktop makes that largely "transparent", but other setups might not have the same)
- if the path on the host points to a _file_, and that file is missing, that docker will create a _directory_ in that location

Those were the reasons for not auto-creating the paths when using the long-hand syntax, as they've been cause for lots of confusion (and unexpected behavior).

**Comment by speller** [comment] 2019-06-13 11:55
@thaJeztah It doesn't in my case. That's why I've found this topic on google. I have a stack deployed with the docker-compose file. I'm using the short syntax. And docker fails to start containers if their volumes' host directories do not exist. The parent directory of the volume directory exists (and have the `root:root` ownership). But docker can't create a subdir for the volume. If I create the volume directory with `sudo` (the volume directory has the `root:root` ownership) container starts successfully and change directory ownership to `polkitd:root`.

**Comment by thaJeztah** [comment] 2019-06-13 12:07
@speller probably better to open a new ticket for that with details (information about the version of compose you're using, as well as engine version (output of `docker version` and `docker info`); if possible with minimal steps to reproduce. Are you only seeing that issue when using compose, or also when doing the same with `docker run` ?

**Comment by vaishnoavi** [comment] 2019-07-09 09:15
@thaJeztah : I am also facing the same issue. In my Dockerfile, I am changing the permission of some folder to non-root user. 
`chown -R non-root-user /usr/local/app_name`
When i try to start the container from docker-compose up or docker run, I am mapping the logs folder from the container to the host
`-v /path/already/present/the_last_folder_does_not_exits:/usr/local/app_name/logs. `
When i start the container, **the_last_folder_does_not_exits** gets created with the root user rather than non-root-user user. Can you provide me some info ?
My docker version : 17.05.0-ce

**Comment by volkflo** [comment] 2019-07-10 06:13
@thaJeztah I tried the long volume syntax as you mentioned above, but is there a way to print a warning if the file or directory on the host is missing?

**Comment by thaJeztah** [comment] 2019-07-10 09:31
When using the long syntax, it should print an error and fail;

```yaml
version: "3.7"
services:
  web:
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./some/path/on/host
        target: /some/path/in/container
```

```bash
docker-compose up
Creating network "repro-2781_default" with the default driver
Creating repro-2781_web_1 ... error

ERROR: for repro-2781_web_1  Cannot create container for service web: invalid mount config for type "bind": bind source path does not exist: /Users/sebastiaan/Projects/repro/repro-2781/some/path/on/host

ERROR: for web  Cannot create container for service web: invalid mount config for type "bind": bind source path does not exist: /Users/sebastiaan/Projects/repro/repro-2781/some/path/on/host
ERROR: Encountered errors while bringing up the project.
```

**Comment by volkflo** [comment] 2019-07-10 10:52
@thaJeztah Thanks for the example. My problem was that I tried this with an existing setup. 
But it is only working after running `docker-compose down -v`.
I think this is the correct behavior that is only working for ne created mounts?

**Comment by rulatir** [comment] 2019-12-05 02:46
> Nooo. This was great feature. How can one then make sure paths exist if they do not yet? You have to wrap docker-compose then into a script?

You have to anyway. Without auto-creation docker will error out. With auto-creation it will create the missing directories as root, which is equally undesirable. There is simply no way to avoid having to supply the missing functionality by writing some code.

On a related note, this deficiency of docker interplays in a nasty way with git's inability to store completely empty directories. Because of this, git cannot be used to ensure the existence of the host directories. The usual trick of putting .gitignore in the (almost) empty directory won't work, because the mount will hide the .gitignore file and git will now see the mounted content as untracked files.

**Comment by mitar** [comment] 2019-12-05 20:46
> With auto-creation it will create the missing directories as root, which is equally undesirable.

There could be a config to configure user under which to create the directory.

**Comment by dnck** [comment] 2019-12-06 13:39
> > With auto-creation it will create the missing directories as root, which is equally undesirable.
> 
> There could be a config to configure user under which to create the directory.

That would be great! I'm currently having the issue that docker-compose up creates the directories I need (great), but when I want to tear them down and build them back up again using Jenkins, my build fails because Jenkins can't tear down root owned volumes created by Docker.

**Comment by rulatir** [comment] 2019-12-08 01:27
> There could be a config to configure user under which to create the directory.

There could be? Optimist!

**Comment by qiangli** [comment] 2020-02-14 23:42
> There could be a config to configure user under which to create the directory.

or by default under: $USER:$USER

**Comment by nicolabeghin** [comment] 2020-03-25 15:20
Any news on this? thanks!

**Comment by thaJeztah** [comment] 2020-03-30 08:16
@nicolabeghin I tried reproducing, but I'm getting the error (as expected);

```bash
docker-compose up

Creating network "composetest_default" with the default driver
Creating composetest_web_1 ... error

ERROR: for composetest_web_1  Cannot create container for service web: invalid mount config for type "bind": bind source path does not exist: /Users/sebastiaan/Projects/test/composetest/some/path/on/host

ERROR: for web  Cannot create container for service web: invalid mount config for type "bind": bind source path does not exist: /Users/sebastiaan/Projects/test/composetest/some/path/on/host
ERROR: Encountered errors while bringing up the project.
```

@nicolabeghin after you ran `docker-compose up`, was a `some/path/on/host` directory created in your current directory? Could you also check if a `DOCKER_API_VERSION` environment variable is set in your environment?

**Comment by nicolabeghin** [comment] 2020-04-02 19:38
@thaJeztah thanks a lot for your followup! below the whole thing.

![image](https://user-images.githubusercontent.com/2743637/78293978-d53ee800-7529-11ea-9ca8-47eb206a1e52.png)

I confirm there's no `DOCKER_API_VERSION` environment variable set.

I must outline: running from scratch it *did* led to error as you suggested, but it didn't anymore after trying to change the version from 3.3 to 3.7 in order to check the minimum version required for this. After reverting back to 3.7, as shown above, it didn't fail anymore in any case and with any version.

**Comment by kirillt** [comment] 2021-01-04 13:25
Has syntax changed since April?

Compose file:
```yaml
version: "3.7"

services:
  db:
    image: hello-world
    volumes:
    - type: bind
      source: ./storage
      target: /storage
```

Running:
```bash
[user@localhost test]# docker-compose up
Creating network "test_default" with the default driver
Pulling db (hello-world:)...
latest: Pulling from library/hello-world
0e03bdcc26d7: Downloading [========>                                          ] 0e03bdcc26d7: Pull complete
Digest: sha256:1a523af650137b8accdaed439c17d684df61ee4d74feac151b5b337bd29e7eec
Status: Downloaded newer image for hello-world:latest
Creating test_db_1 ... error

ERROR: for test_db_1  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /tmp/test/storage

ERROR: for db  Cannot create container for service db: invalid mount config for type "bind": bind source path does not exist: /tmp/test/storage
ERROR: Encountered errors while bringing up the project.
```

**Comment by thaJeztah** [comment] 2021-01-04 13:45
@kirillt does the `storage` directory exist on your system? When using the advanced volumes syntax, the paths you bind-mount from the host must pre-exist

**Comment by kirillt** [comment] 2021-01-07 21:34
@thaJeztah I see that in last post (@nicolabeghin) folder `notexisting` was created.
Apparently, I interpreted it wrong as a desired behaviour and, in fact, it was a demonstration of the bug.

But is there any way of initializing non-existing folders before mounting them?
Except wrapping `docker-compose` with a `Makefile`?

**Comment by jjkoehorst** [comment] 2021-03-25 16:50
@kirillt I am very curious to this as well. Did you manage to find a solution?

**Comment by kirillt** [comment] 2021-03-25 23:04
@jjkoehorst if I remember correctly, no
I decided that Makefile is fine in that case

**Comment by Fire-Dragon-DoL** [comment] 2024-08-20 21:55
Would a decent course of action be to document this behavior in the compose syntax spec as well as in the docker command? Due to the difference between macOS where the directory is created as user ID 1000 and linux where the directory is created as `root`, there are some undesirable issues showing up, where something developed on macOS has a bug that's never discovered until executed on a linux machine or a very rare occurrence where the macOS developer creates a second user (id 1001) and run docker compose up and the directory created would be for the wrong user.

**Comment by sparrowt** [comment] 2024-12-04 15:11
Yes it could do with being made clearer at https://docs.docker.com/reference/compose-file/services/#volumes though, now that I know, it is kind of there, buried in under "Long syntax" > `bind` > `create_host_path` where it says:
> Creates a directory at the source path on host if there is nothing present. Compose does nothing if there is something present at the path. This is automatically implied by short syntax for backward compatibility with docker-compose legacy.

So the short syntax does have the "create host path" behaviour:
```
servies:
  foo:
    volumes:
      - ./path/on/host:/path/in/container
```
whereas the long syntax does not:
```
services:
  foo:
    volumes:
      - type: bind
        source: ./path/on/host
        target: /path/in/container
```
unless you explicitly add the following:
```
        ...
        bind:
          create_host_path: true
```

(Related docs for the CLI https://docs.docker.com/engine/storage/bind-mounts/#differences-between--v-and---mount-behavior)

**Comment by Fire-Dragon-DoL** [comment] 2024-12-05 07:10
> Yes it could do with being made clearer at https://docs.docker.com/reference/compose-file/services/#volumes though, now that I know, it is kind of there, buried in under "Long syntax" > `bind` > `create_host_path` where it says:
> 
> > Creates a directory at the source path on host if there is nothing present. Compose does nothing if there is something present at the path. This is automatically implied by short syntax for backward compatibility with docker-compose legacy.
> 
> So the short syntax does have the "create host path" behaviour:
> 
> ```
> servies:
>   foo:
>     volumes:
>       - ./path/on/host:/path/in/container
> ```
> 
> whereas the long syntax does not:
> 
> ```
> services:
>   foo:
>     volumes:
>       - type: bind
>         source: ./path/on/host
>         target: /path/in/container
> ```
> 
> unless you explicitly add the following:
> 
> ```
>         ...
>         bind:
>           create_host_path: true
> ```
> 
> (Related docs for the CLI https://docs.docker.com/engine/storage/bind-mounts/#differences-between--v-and---mount-behavior)

This is almost perfect, it should include the permissions/ownership the directory is created with and it could be part of the docs from my perspective!

**Comment by katettudelft** [comment] 2025-02-18 16:42
> it should include the permissions/ownership the directory is created with 

Was there ever a fix, or at least another open issue regarding this? It's a bit of a stumbling block for me right now.

**Comment by mvdbos** [comment] 2025-04-30 09:32
> Yes it could do with being made clearer at https://docs.docker.com/reference/compose-file/services/#volumes though, now that I know, it is kind of there, buried in under "Long syntax" > `bind` > `create_host_path` where it says:
> 
> > Creates a directory at the source path on host if there is nothing present. Compose does nothing if there is something present at the path. This is automatically implied by short syntax for backward compatibility with docker-compose legacy.
> 
> So the short syntax does have the "create host path" behaviour:
> ...
> whereas the long syntax does not:
> 
> ```
> services:
>   foo:
>     volumes:
>       - type: bind
>         source: ./path/on/host
>         target: /path/in/container
> ```
> 
> unless you explicitly add the following:
> 
> ```
>         ...
>         bind:
>           create_host_path: true
> ```
> 

Unfortunately, the conclusion that the long syntax does *not* create the host path automatically is not correct. This is only true if `create_host_path: false` is explicitly set. This issue is not caused by the [spec implementation](https://github.com/compose-spec/compose-spec) used by the CLI, but by the CLI itself.

In the CLI there is this piece of logic when creating the mounts/volumes:
```go
​    switch m.Type {
    case mount.TypeBind:
      // `Mount` is preferred but does not offer option to created host path if missing
      // so `Bind` API is used here with raw volume string
      // see https://github.com/moby/moby/issues/43483
      v := findVolumeByTarget(service.Volumes, m.Target)
      if v != nil {
        if v.Type != types.VolumeTypeBind {
          v.Source = m.Source
        }
        if !bindRequiresMountAPI(v.Bind) {
          source := m.Source
          if vol := findVolumeByName(p.Volumes, m.Source); vol != nil {
            source = m.Source
          }
          binds = append(binds, toBindString(source, v))
          continue
        }
      }
    case mount.TypeVolume:
      v := findVolumeByTarget(service.Volumes, m.Target)
      vol := findVolumeByName(p.Volumes, m.Source)
      if v != nil && vol != nil {
        // Prefer the bind API if no advanced option is used, to preserve backward compatibility
        if !volumeRequiresMountAPI(v.Volume) {
          binds = append(binds, toBindString(vol.Name, v))
          continue
        }
      }
```
Here we can see that both bind mounts and volume mounts are converted to a bind string if the mount does not use any features which require the mount API. This is checked in `bindRequiresMountAPI`. Let's have a look at that check:

```go
func bindRequiresMountAPI(bind *types.ServiceVolumeBind) bool {
	switch {
	case bind == nil:
		return false
	case !bind.CreateHostPath:
		return true
	case bind.Propagation != "":
		return true
	case bind.Recursive != "":
		return true
	default:
		return false
	}
}
```

Note that if `CreateHostPath` is not explicitly set to `false`, and no other bind options are set in the yaml, the case `bind == nil` will match. This results in it being treated as a normal volume, and therefore the host path will be created automatically alter on, even though the value of `CreateHostPath`, i.e. `create_host_path` is not set to to true.

**Comment by thaJeztah** [comment] 2025-04-30 11:31
Looks like there  was a recent change in that area (PR: https://github.com/docker/compose/pull/12734), which reverted some code-paths to use the old API; that sounds like a regression at least (as the advanced syntax should default to `create_host_path: false`)?

Could you open a separate ticket for that? (at least for visibility, and discussion whether that was intentional or a side-effect of other changes?)

**Comment by mvdbos** [comment] 2025-04-30 13:52
Done

**Comment by mvdbos** [comment] 2025-05-13 14:15
In the end, this was resolved by updating the compose spec docs to match the current logic in https://github.com/compose-spec/compose-spec/pull/599
