### ISSUE TITLE
Old logs dumped to terminal on startup

### ISSUE THREAD

**Issue by mikehaertl** [docker/compose#2116] opened 2015-09-30 08:48 UTC
Each time I use `docker-compose up` to restart an existing set of containers, I see huge amounts of old log messages dumped to the screen.

This was not the case before 1.4.0. Older versions did only output new messages.

I don't need this and suggest a feature to turn that off (unless there already is one, which I couldn't find).

**Comment by dnephin** [comment] 2015-09-30 13:56
This is a duplicate of #1756

You can `docker-compose rm` the containers if you want to remove the logs

**Closed by dnephin** 2015-09-30 13:56 UTC
Labels: area/logs, kind/bug

**Comment by mikehaertl** [comment] 2015-09-30 16:00
But I don't want to `rm` existing containers. For example during development I have a MySQL container and don't want to loose the DB content on each startup. But will continue discussion in the other issue then.

**Comment by dnephin** [comment] 2015-09-30 16:01
Yes, sorry, I was just suggesting that as a possible workaround for now. We still need to fix the issue.

**Comment by sunsided** [comment] 2015-10-12 17:05
Umh, but why is this closed if it's still to be done? :flushed: 

Having the same problem here.

**Comment by hixus** [comment] 2017-11-28 08:22
Any update on this. It's been 2 years.

**Comment by coreylenertz** [comment] 2017-12-18 03:48
@dnephin any progress on fixing the issue?

**Comment by michaelfranzl** [comment] 2019-01-03 18:39
I'm running into the same issue. `docker-compose up` is suddenly dumping one week worth of old logs, where previous invocations of `docker-compose up` didn't do that.

**Comment by kuzyn** [comment] 2019-03-02 16:13
Same here... Issue  https://github.com/docker/compose/issues/1083 seems to hold more usable info. It is also closed.
