### ISSUE TITLE
Scale a container specifying ports

### ISSUE THREAD

**Issue by thalescm** [docker/compose#1241] opened 2015-04-02 15:34 UTC
Currently the `docker-compose scale` command creates random ports for the new containers.

Is there a way to specify a port for the new containers?

**Comment by awarddev** [comment] 2015-04-29 15:34
I'm wondering the same thing.

**Comment by arthurtsang** [comment] 2015-08-20 22:22
in your docker-compose.xml, 

```
postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432:5432
```

it will bind to 5432, however, note that you can't have more than one instance on the same node for obvious reason.

**Comment by mandb** [comment] 2015-10-01 01:07
I think what would be valuable here is the ability to do:

```yaml
postgres:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=postgres
  ports:
    - 5432+:5432
```

Thus allowing the scale=4 to create 4 instances exposed on 5432, 5433, 5434, 5435, but all routing to their internal ports.  The reasons for this over a separate linked haproxy instance are many.

Naming convention and definitions here is open to improvement obviously.

**Comment by aanm** [comment] 2015-10-20 20:27
Doesn't port range works? ` - 5432-5440`

@arthurtsang It's a "yml" file, not "xml" ;-)

**Comment by dnephin** [comment] 2016-02-03 19:20
Duplicate of #722

**Closed by dnephin** 2016-02-03 19:20 UTC
Labels: kind/question

**Comment by jdchandler** [comment] 2017-06-24 20:22
Will this be implemented?

**Comment by jibinjose087** [comment] 2019-04-11 12:24
The below configuration in docker-compose file with a replica of 5 will create five containers with same VNC port and different internal IP or hostname. If we did the same thing on an ec2 machine then how we access those VNC desktops via public IP? 

====
  chrome_node1:
    image: selenium/node-chrome-debug:3.141.59-gold
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - test
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5557" /opt/bin/entry_point.sh'
    ports:
      - "5557:5900"
    deploy:
      replicas: 5
========

Adding the same entry multiple times in docker-compose file with different IP will do the trick but I am looking for any other alternative solution.
