### ISSUE TITLE
Suport Re-Following Logs on Single Service Restart

### ISSUE THREAD

**Issue by ComfyDust** [docker/compose#10331] opened 2023-02-28 19:07 UTC
### Description

When following logs via `docker compose up` or `docker compose logs -f`, the command automatically re-follows container logs when a service is restarted but only if multiple services are running. If only one service is running, the command detaches instead.

It would be handy to have the ability to re-follow logs even if only one service is running (e.g., via a new parameter).

For context, I'm currently writing a CLI wrapper that starts a docker compose application with two services, one of which is optionally activated via a profile. The primary service needs to be periodically restarted. When both services are running, `docker compose up` automatically reattaches to the container so the wrapper can simply continue printing results from STDOUT. When only one service is running, however, I need to restart the service, wait for it to be up, and re-attach. It would be nice to instead be able to consistently re-follow logs for both scenarios.

**Comment by ndeloof** [comment] 2023-03-01 06:56
Marking this as a bug, compose can detect service container is restarting, should not exit

**Comment by laurazard** [comment] 2023-03-01 11:44
@ndeloof we had a discussion about this on https://github.com/docker/compose/pull/10181, it's not that clear (and not a bug unless we want to change behavior from V1).

It works fine when there is a Compose file with multiple services (as logs doesn't exit, the new service starts and we reattach) but this issue is for when the Compose file only has 1 service defined. In that case, if a user runs `compose restart [xxx]` in another terminal, Compose has no way of knowing if the container will start again or not unless instead of immediately exiting we wait for a bit to see if service starts again,

**Comment by ndeloof** [comment] 2023-03-01 12:13
@laurazard I recently introduced a mechanism for compose to know a container is restarted, see https://github.com/docker/compose/pull/10236

**Comment by ndeloof** [comment] 2023-05-03 15:37
As we are stuck with docker engine limitation not to populate `State.Restarting` as a container is restarted by command, we have no technical way to implement this feature 🥺
I'm closing this issue, will obviously be reconsidered if something changes on Docker engine.

**Closed by ndeloof** 2023-05-03 15:37 UTC
Labels: kind/feature
