### ISSUE TITLE
Command line completion

### ISSUE THREAD

**Issue by fkthat** [docker/compose#9456] opened 2022-05-12 07:02 UTC
I'm following the instructions to set up bash command line completion for `docker compose`:
[https://docs.docker.com/compose/completion/#bash](https://docs.docker.com/compose/completion/#bash).

However, there's no such a file in the repo and I keep getting 404. Is there any way to have compose completion work?

**Comment by glours** [comment] 2022-05-12 07:04
Duplicate of https://github.com/docker/compose/issues/8550

**Closed by glours** 2022-05-12 07:04 UTC
