### ISSUE TITLE
Proposal: support for empty project names

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/compose#1621] opened 2015-07-01 04:41 UTC
Hi folks, I've been thinking about allowing empty project names (`-p ''`) to compose. I [simply want to have](https://www.youtube.com/watch?v=CQSRPMFDTSs) containers named `blog_1`, `cache_1`, `db_1`; not `dirname_blog_1`, `dirname_cache_1`, `dirname_db_1`.

This can be done by allowing empty string value to `--project`/`-p` flag. If the flag is not specified at all, it can look at the dirname for the value; otherwise it would just omit it. It would look like this:

    docker-compose -p "" up -d

WDYT?

**Comment by dnephin** [comment] 2015-07-03 01:58
An empty project name isn't going to be possible, because the project name is how compose keeps track of the containers that are "part of the composition". If it were empty, it would consider every docker container as "part of the composition".

I think what you're looking for is something like #1518, so I'm going to close this as a duplicate of that issue.

**Closed by dnephin** 2015-07-03 01:58 UTC

**Comment by ahmetalpbalkan** [comment] 2015-07-03 02:05
Sounds reasonable. Thanks.
