### ISSUE TITLE
the use of the -p flag should set COMPOSE_PROJECT_NAME value

### ISSUE THREAD

**Issue by CircleCode** [docker/compose#2565] opened 2015-12-22 10:07 UTC
as I understand it, `-p` overwrite the project name, but if you use `${COMPOSE_PROJECT_NAME}` in your `docker-compose.yml`, it won't use the `-p` value

**Comment by dnephin** [comment] 2015-12-22 16:34
Duplicate of #2565

**Comment by CircleCode** [comment] 2015-12-22 16:35
duplicate of which? (#2565 is this one)

**Closed by dnephin** 2015-12-22 16:34 UTC
Labels: duplicate

**Comment by dnephin** [comment] 2015-12-22 16:37
Oops, I copied the wrong number! #2294
