### ISSUE TITLE
Proposal: Use intermediate containers when recreating

### ISSUE THREAD

**Issue by withinboredom** [docker/compose#3028] opened 2016-02-26 15:44 UTC
Related to: #2444 

When running on swarm and trying to recreate containers, I get this error:

```
Recreating 74d03893fd_74d03893fd_flagshipcutter_forever_1
ERROR: unable to find a node with port 6713 available
```

Instead of trying to recreate the container, allow specifying a container to start as an intermediary between stopping, destroying and restarting.

In other words, instead of this oversimplified example:

``` bash
docker run -p ${external_port}:${internal_port} --volumes-from ${original_container} --name ${new_container_name} ${new_image}
docker rm -f ${original_container}
```

It would be

``` bash
docker run --volumes-from ${original_container} --name ${intermediary_name} ${intermediary_image}
docker rm -f ${original_container}
docker run -p ${external_port}:${internal_port} --volumes-from ${intermediary_name} --name ${new_container_name} ${new_image}
```

This way, downtime would be hugely minimised instead of stopping all services that may be at a specific scale before being able to bring them back up.

The intermediate container could be something very small (it just has to hold files) or it could be specified in the `docker-compose.yml`

**Comment by dnephin** [comment] 2016-02-26 20:33
I believe this is a duplicate of #2866, there is a bunch of discussion in that issue.

We used an intermediate container in Compose before version 1.4, and it caused multiple issues. Once rename was available we stopped using it.  I think it's very unlikely that we re-introduce intermediate containers. It's nice for the swarm case, but it breaks minimal images on engine, and there are other ways to work around the problem.

As of Compose 1.6.2 we no longer set this container affinity for containers that don't use anonymous volumes, so the easiest way to work around this problem is to either remove volumes, or use named or host volumes.

Also note this is only an issue if you expose a host port. 

We will continue to track other solutions in #2866

**Closed by dnephin** 2016-02-26 20:33 UTC
